;Chapter 1
;　月の美しい夜だった。@
`　'It was a beautiful moon that night.'`@
br
;　夜の校舎も大きな満月に彩られると、不気味さの中にも風情が感じられるものだ。\
`　Even the school building at night was colored by the full moon, and its ominous presence could be felt in the air.`\

;　満月には不思議な力があり、妖怪たちをも活発にさせる。@
`　The full moon has mysterious powers, and it even invigorates youkai.`@
;　だから満月の夜の学校妖怪たちは上機嫌。@
`　And so the school youkai are soothed when the full moon is out.`@
br
;　時に、殺伐とした魂のやり取りを休み、お月見会などという、風流な催しを開いてみたりもする……。\
`　Sometimes they even take a break from stealing brutally murdered souls and hold an elegent event known as the Lunar Festival...`\

bg black,22
bg gakkou_07y,22

;「えっと、えっとえっと……！@　もう一度、精神を集中して……。@……うーん………。@……えいッ。@/
`"Ummm, umumum...! `@`One more time, focus your mind... `@`...Mmmhmm... `@`..There~`@/

quakey 1,100

;きゃーーーッ、また裸ぁーーーッ！！」@
`Kyaaaaa, I'm naked agaaaaain!!"`@
br
;　毬枝の賑やかな叫びが旧校舎に木霊する。\
`　Marie's lively scream echoes through the old school building.`\

;bg black,22
;bg toire_01,22
;wait 300
bg black,22
bg toire_02,22

;　めそめそさんのトイレでは、毬枝が余所行きの格好の“着替え”に挑戦していた。\
`　In Mesomeso-san's bathroom, Marie was challenging herself to 'change' into her best outfit.`\



;　妖怪たちの着替えには、ちょっとしたコツがいる。@
`　The way youkai change clothes takes a bit of getting used to.`@
;　何しろ妖怪たちは霊的な存在。@本来、その姿は不可視で、肉体は存在さえしないのだ。@
`　After all, youkai are incorporeal beings. `@`Their forms are invisible, and their bodies no longer exist.`@
br
;　だから、服を買ってきて、それを着れば着替え完了とはならない。\
`　So they can't go out, buy clothes, and simply change into them.`\

bg black,22
bg toire_03,22
ld c,MAR_D2a,22
;ld c,MAR_D3a,80

;「この服に戻るのは簡単なんだけどなぁ……。@……うーん、よく精神を集中して、もう一度……。」\
`"Getting back into this outfit should be easy but... `@`...Okay, concentrate, one more time..."`\ 

;　妖怪の服装は、大抵の場合、依り代に大きく依存する。@
`　Usually, youkai outfits depend largely on spirit anchors.`@
br
;　彼岸花の場合は、依り代となっている西洋人形の服装が基本となる。@
`　In Higanbana's case, her Western doll is her anchor and the basis for her attire.`@
;　そして、死者出身である毬枝の場合、最期の時に着ていた服装が基本だ。\
`　And so for the deceased Marie, her attire is based on the clothes she wore in her final moments.`\

ld c,MAR_i4,80

;　それと異なる服装に外見を変えるには、妖力を用いて、自らの外見を装飾しなくてはならない。@
`　That means she has to use spiritual energy to change her outer appearance into a different outfit than the one she died in.`@
br
;　変えたい外見をよくイメージして、精神を集中。@……そして、気合一発！@　えいっ。\
`　She has to imagine what she wants to look like and gather her spirit. `@`...Then, in a burst of energy! `@`There~!.`\

se1 48
bg white,1
;bg black,22
bg toire_04,22

;　ドロンと煙が出るが、またしても裸に。\
`　A puff of smoke appears, and she's nude once again.`\

quake 3,300

;　別に誰かに見られているわけでもないのだが、@毬枝はきゃーきゃー騒いで、元の服に戻り、そして精神を統一して……、を何度も繰り返している。@
`　It's not as though anyone was watching her, `@`but Marie made a racket with her `Kyaaa kyaaa`s. `@`She went back to her old form and focused her spirit... repeating this over and over.`@
br
;　そこまで難しいことではないはずなのだが、@毬枝は元々、妖力が小さいし、その上、コツも掴んでいないので、なかなか思い通りに出来ないのだ。\
`　It wasn't something that was that hard, `@`but Marie's powers weren't much to begin with. `@`On top of that, since she still hasn't gotten the hang of it, she can't really change when she wants to change.`\

bg black,22
bg toire_03,0
ld c,MAR_D2a,22
;ld c,MAR_D1,80

;「うーん……。@そもそも私、素敵なお洋服って、全然想像できない……。@うーん……。」@
`"Hmmm... `@`Then again, I can't really imagine myself in a beautiful dress... `@`*Sigh*..."`@
br
;　あまりファッションに関心のなかった毬枝にとって、余所行きの服装を想像するのは、かなり難しいことなのだ。\
`　Since Marie didn't really have an interest in fashion, imagining the best Western clothes is pretty difficult for her.`\

bg black,22

;　今夜は、学校妖怪たちのお月見会。@
`　Tonight is the Lunar Festival for the school youkai.`@
br
;　普段、ギスギスすることが多い学校妖怪たちも、今夜ばかりは休戦。@仲良くお酒を酌み交わすという、和やかな行事なのだ。\
`　Only for tonigh, even the school youkai that often have conflicts with each other hold truces. `@`It's a harmoneous event where they mingle and drink together.`\

bg toire_06,22

;　何だかんだ言って、毬枝は未だに、学校妖怪の全員とは会っていない。@
`　For whatever reason, Marie still hasn't met all of the school youkai.`@
br
;　だから、彼らが一堂に会する今日を、とても楽しみにしていた。\
`　So she was really looking forward to meeting them today when they are all under the same roof.`\

bg black,22
mono 1
bg toire_05,0
ld l,MAR_w2,0
ld r,HIG_D5,22


;　さぁ、行こう！@　となったら、唐突に彼岸花に言われたのだ。@
`　Okay, let's go! `@`Higanbana said suddenly.`@
br
ld r,HIG_w4,80

;　ねぇ、毬枝。@あなた、そんなやぼったい格好で出掛けるのかしら？って。\
`　She said, Heey Marie. `@`Are you really gonna go out with a shabby outfit like that, I wonder?`\

ld l,MAR_d4a,80

;　彼岸花やスミレなどは、結構、立派な格好しているから良いのだが、……言われてみれば、毬枝はただの私服だ。@
`　Youkai like Higanbana and Sumire had rather splendid outfits and look fine, ...but to put it bluntly, Marie's clothes are plain.`@
br
;　無理もない。@その姿で彼女は死に、妖怪になったのだから。\
`　It's understandable. `@`She died and became a youkai in that state after all.`\

;ld r,HIG_D1,80

;　待っててあげるから、少しはマシな格好に着替えてらっしゃい。@要領は今、教えてあげた通り。@大丈夫、慣れれば自由自在よ。@
`　We'll wait for you, so go ahead and change into some better clothes. `@`Just do as I taught you. `@`You'll be fine, when you get used to it you can do it whenever!`@
br
;　………最初の内は彼岸花も廊下で待っててくれたのだが。@あまりに毬枝の要領が悪いので、とうとう愛想を尽かし、先に行ってるわと行ってしまったのだ。\
`　...At first Higanbana waited on her in the hall, `@`but Marie wasn't very good at the basics, so eventually she got impatient and said, "Kay, I'm going on ahead~."`\

bg black,22
mono 0
bg toire_03,0
ld c,MAR_D3,22
ld c,MAR_D2a,80

;「素敵なお洋服とか、全然思いつかない……。@……もうこの際、何でもいいから、とにかく早く着替えないと……。@………とにかく何でもいいから、……いいから……。」\
`"I can't think of any pretty dresses... `@`At this point anything would be fine, so I have to hurry up and change or... `@`Anyway, anything is good... anything..."`\

bg black,22
ld r,HIG_d5,22
;ld r,HIG_D1,80

;　素敵なドレスとか憧れるけれど、どうせ自分には似合わないに決まってる。@
`　I might want a pretty dress, but it's obvious it doesn't suit me.`@
br
;　何を着れば似合うかな、何を着れば似合うかな……。@思い付かない。\
`　What should I change into, what should I change into... `@`I have no idea.`\

mov %SMI_Isyou,2
cl r,0
ld l,SMI_w1,22
;ld l,SMI_D1,80

;　……素敵なお洋服とは言わないまでも。@……今日のお月見会に相応しい格好って何だろう。@
`　...Even if it's not a pretty dress, `@`I wonder what would be best to wear today on the Lunar Festival.`@
br
;　和服なんて着たことないから、イメージできないし……。\
`　I haven't worn a kimono before, so I can't imagine myself in one...`\

bg black,22
bg toire_04,22

;　……そっか。@考えてみたら、学校妖怪のビリっけつに加えてもらって、全員の前で挨拶するのは、これが初めてなんだ。@
`　...Oh yeah. `@`Now that I think of it, since they let me become the last school youkai, this is the first time I'll be greeting them face to face.`@
br
;　てっきり、お月様を見ながらお団子でも食べられるなんて思っていたけれど、とんでもない。@私は学校妖怪の新人で後輩。@粗相がないように気を付けなくちゃ…！\
`　Even though I had been thinking of eating sweet dumplings while gazing at the lovely moon, that's not what really matters! `@`I'm the new school youkai and they are my seniors. `@`I've gotta be careful not to make any mistakes!...`\

bg black,22
bg toire_03,0
ld c,MAR_i4a,22
;ld c,MAR_D1,80


;　浮かれた服はダメ、ぴしっとしたのじゃないとダメ……。@
`　I can't wear festive clothes, I can't wear clothes that aren't neat...`@
br
;　ぴしっとしたの、しっかりしたの、真面目なの、……。@
`　I need something neat, appropriate, serious...`@
br
;　うーんうーんうーん………。\
`　Hmmm Hmmm Hmmm...`\

se1 22

bg white,1
;bg black,22
bg toire_07,22

;　ドロン。@
`　Poof.`@
br
;　ようやく毬枝が着替えに成功した時には、もう、お月見会の始まりから１時間以上も経っていた。\
`　When Marie finally succeeded in changing clothes, the Lunar Festival had already been going on for more than an hour.`\

bg black,22
fede 0,1000
E_A

bg white,24
bg toire_01,24
bg black,24
bg k_kaidan_01,24

;　毬枝はそのままトイレを飛び出し、階段を駆け上がる。@
`　Marie rushes out of the bathroom, and runs up the stairs.`@
br
;　会場は屋上。@満月がもっとも映える、旧校舎屋上だ。\
`　The meeting place is the roof. `@`The old school building's roof is where the full moon shines the brightest.`\

se1 16

bg white,24
bg black,24

me1v 5,50

;「お、遅くなってすみませんでしたっ！！」@
`"I- I'm sorry for being laaaate!!"`@
br
;　屋上へ躍り出ると。@そこには不思議な光景が広がっていた……。\
`　She springs out onto the roof. `@`There, a strange scene was unfolding...`\

fede 0,1000
E_A

bg okujou_04,22

bgm1 31

;　普段なら、何もない、ひび割れたコンクリートの無機質な屋上が広がっているだけなのに。@
`　Even though normally a roof empty of anything but cracked concrete and inorganic matter should have spread before her...`@
br
;　儚くも美しい、黄泉の桜が、その大樹を茂らせ、満開の花を開いている。\
`　Vividly beautiful sakura from the underworld were in full bloom and covering a huge tree.`\

;　その白く、ほんのりと淡い光を放つ花びらの絨毯は、あまりに幻想的で美しい……。@
`　That sea of white flower petals gave off a faint glow, and they were magically beautiful...`@
br
;　その、幻想のような、満開の桜の下で、妖怪たちが大きな車座となって、杯を傾けている。\
`　Beneath those illusionary fully-bloom sakura, the youkai were sitting in a circle and indulging themselves with glasses of sake.`\ 

;　幻想的ではあっても、決して厳か過ぎず。@
`　It has its majesty, but it's not too extravagent.`@
;　宴席ではあっても、決して騒ぎ過ぎず。@
`　They were having a banquet, but they're not too noisy.`@
br
;　人の命を奪うことも厭わない妖怪たちが、今夜だけはそれを忘れる、@ささやかな一時が、そこにはあった……。\
`　Those youkai who had no quams about stealing people's lives away, leave that behind just for tonight. `@`This was a time for modesty...`\

;　みんな、ほろ酔い気分らしく、それぞれのお喋りに夢中で、毬枝の登場に気付いていないようだった。\
`　It seemed everyone was slightly intoxicated and engrossed in each other's conversations, so they hadn't noticed Marie's entrance.`\

bg black,22

mov %HIG_Isyou,2
;bg white,23
bg okujou_01y,22

ld l,HIG_D2,22
ld l,HIG_d4,80

;「遅いわよ、毬枝。@って、………なぁに、その格好？」\
`"You're late Marie. `@`And ...what's with the geddup?"`\
;cl c,0
;ld l,HIG_D2,0
ld r,ma2_n1,24
;ld r,ma2_D1,80

;「ご、ごめんなさい…！！@　何度、挑戦しても、全然ダメだったんですー！@　これでもう許して下さいぃぃ！」@
`"I- I'm sorry!! `@`No matter how much I tried, nothing worked! `@`Please just let me go like thiiiiis!"`@
br
;　１時間以上も挑戦して、毬枝がようやく成功したその服装は、…………中学か高校の制服っぽく見えた。\
`　The outfit that Marie had finally succeeded after trying for more than an hour... looked just like a middle school or high school uniform.`\

bg black,24
bg okujou_02,24
ld c,SAK_D3,26
ld c,SAK_D2,80
se1 47
quakey 1,100

;「うりゅー！@　素敵だよ、毬枝っ。@まるで高校生みたいだよ！」@
`"Uryu-! `@`Wonderful, Marie. `@`You almost look like you're in high school!"`@
;＜さくのしん

ld r,HOK_D3,24
ld r,HOK_D2,80

;「その服、……県立高の制服にそっくりだわ。」@
`"That outfit... it looks just like a uniform from an expensive private school."`@
;＜保健

mld l,ma2_D4a,23
;mld l,ma2_i1a,80

;「え？！@　ほ、保健室の先生ですよね？！@　どうしてここに？！」\
`"Wha?! `@`Y- You're the school nurse right?! `@`Why are you here?!"`\
;＜毬枝

ld r,HOK_D4,80

;「まーまー、硬いこと言わないのー。@いーじゃない、私が混じっても。@お酒もお月見も大好きなんだからー！」\
`"Hey hey, don't say such rash things. `@`Isn't it alright if I mingle a bit? `@`I love sake and gazing at the moon after all!-"`\
;＜保健

mcl l,0
bg black,23
bg okujou_01y,0
ld r,HIG_D5,23
ld r,HIG_w3,80

;「ふぅん。@……なるほど。@あなたのお姉さんが通っていた高校の制服、なのね。」@
`"Oooh. `@`...I get it. `@`That's the uniform your sister went to school with, am I right?"`@
;＜彼岸花
br
;　彼岸花が毬枝の心を読み、口にする。@
`　Higanbana says as she reads Marie's mind.`@
;　それを聞き、ようやく毬枝は、どうしてこの服になったのかを理解した。\
`　Hearing that, Marie at last realized why she ended up in those clothes.`\

bg black,22
mld c,ma2_D4a,22

;　毬枝のその服は、地元の県立高校の制服をイメージしたものだ。@
`　Her clothes were based on the local prefectoral high school's uniforms.`@
br
;　本物とは少し細部が違うかもしれないが、@……姉が着ていて、自分もいつか着たいと憧れ、夢見ていた服装そのものなのだ。\
`　Although it might have some minor differences, `@`...that outfit was something her sister had worn, and at some point Marie wanted it and dreamed of wearing it.`\

;bg black,22
bg okujou_01y,0
ld r,HIG_D1,22

mld c,ma2_D3a,80

;「素敵なドレスなんて思い付かないし……。@なら、少し真面目な服にならないかなと思ったらこんな服に……。」\
`"I couldn't really think of a pretty dress... `@`And after thinking I had to wear something more cordial, it turned out like this..."`\ 
;＜毬枝

ld r,HIG_D3,80

;「違うわね。@毬枝がその服を選んだのは、憧れていたからよ。」@
`"You're wrong. `@`You picked out those clothes because you wanted to wear them!"`@
;＜彼岸花

ld l,SAK_k2,22
;ld c,SAK_D1,80

;「………そうみたいだね。@……毬枝はよっぽど、その服を着たかったんだろうねぇ。」@
`"...Looks like it. `@`...Marie must have really wanted to wear that outfit."`@
;＜さくのしん

mld c,ma2_D4a,80

;「この服を、………私が……。」\
`"These clothes... I...."`\

ld r,HIG_D2,80

;「死んでしまった今となっては。@高校生になるなんて、叶わぬ夢だもんねぇ。@くすくすくす。@………良かったじゃない。@憧れの制服を着ることが出来て。@くすくすくすくすくす……。」@
`"Well since you're dead now, `@`you can't really have your dream of being a high schooler granted, can you? `@`*giggle*giggle* `@`...But isn't it nice? `@`Being able to wear that oufit you've dreamed of, that is. `@`Teeheeheeheehee..."`@

mld c,ma2_D3a,80

;「や、やっぱり、おかしいでしょうか……。」\
`"Y- You think it's strange... don't you?"`\

ld r,HIG_w3,80

;「おかしいわけないでしょ。@月を愛でる素敵な夜に、自分が着たかった一番の服を着て参加する。@……素敵じゃない。」@
`"It's not strange. `@`Being able to wear the clothes you've always wanted on this night when we can admire the moon. `@`...It's lovely, isn't it?"`@
;＜彼岸花
br
;　そう言って、彼岸花はくるりと回ってみせる。\
`　Saying that, Higanbana quickly turned to show Marie.`\

;se1 1
mcl c,0
bg white,23
bg okujou_01y,23
ld c,HIG_w3,23
wait 500
ld c,HIG_D4,22

;　彼女も、普段とは違う、よりドレスっぽい服を着ている。@
`　She's not her usual self, and she's wearing a more elegant dress.`@
br
;　そんな特別な格好が、今夜という夜が特別なものであることを教えてくれるのだ。\
`　That special outfit showed that tonight was a special occasion.`\

ld l,SAK_D4,23
;ld l,SAK_D4,80

;「素敵だよ、彼岸花も毬枝も！@　本当に素敵なカッコだよ！@　うりゅー！！」@
`"Higanbana, Marie, you're so pretty! `@`Your clothes look so lovely! `@`Uryu~!!"`@

ld r,ma2_w1,24
;ld r,ma2_D1,80

;「あ、ありがとうございます……。」\
`"T-Thank you..."`\

ld c,HIG_w2,80

;「さぁ、おいでなさい、毬枝。@末席の分際で大遅刻なんだから。@駆け付け三杯が嫌なら、みんなにお酌して回りなさい？@　私も一緒に回ってあげるから。@……あんた、初めて挨拶する連中も多いでしょうから。」\
`"Come along now, Marie.`@` After all, you're the lowest seat and already so late.`@` If they object to you rushing in three times, why don't you pour everyone their drinks?`@` I'll do it with you.`@` ...It's your first time greeting all these numerous colleagues."`\

bg black,22
bg k_kyou_03,22

;　妖怪たちのクラス、１３組で、一応、自己紹介はした。@
`　She had already introduced herself once to the Youkai class, class 13.`@`
;　しかし、空っぽの教室で自己紹介をしただけだ。\
`　But all she really did was introduce herself to an empty classroom.`\

;　妖怪たちも、簡単に気を許したりしない。@よって、その姿を安易に現したりはしないのだ。@
`　Youkai won't let their guard down so simply.`@` As a result, they do not show themselves easily.`@`
;　だから、学校妖怪八席全員に直接会えるのは、これが初めての機会なのだ。\
`　That's why this would be her first chance to directly meet all eight members of the school Youkai.`\

bg black,22

;　ちょっとドキドキもするけれど、……仮にも自分も学校妖怪の一員、しっかりご挨拶しなきゃ。@
`　It made her a bit nervous, but ...for that moment, as she too was a member of the School Youkai, she had to toughen up and greet them.`@`
;　宴席のルールに疎い毬枝でも、こういうものは上席者からご挨拶すべきと想像は出来る。@
`　Even Marie, who was unfamiliar with the rules of the banquet, could guess that at a thing like this she would need to address the senior members.`@`
br
;　毬枝は彼岸花に連れられ、まずは学校妖怪序列第１位、校長先生のところへ。\
`　Marie let Higanbana lead her to the first seat of the School Youkai, the school's headmaster.`\

bg okujou_01y,22

;　校長先生は学校妖怪たちの長。@
`　The headmaster was the head of all the School Youkai.`@`
;　“存在”どころか、“存在したことさえ”全て消し去ってしまう力を持つ、最大最強の大妖怪なのだ。@
`　He had the power to completely erase that one "exists," or even "had ever existed." He was the greatest, strongest, and most important Youkai around.`@`
br
;　そして、その校長先生と一緒に上機嫌に杯を傾けあっているのは、何と保健の先生だ。\
`　And along with the headmaster, tipping back cups of wine, was that School Nurse.`\

ld l,HOK_D3,22
;ld l,HOK_D1,80

;「あーらー、いらっしゃ～い。@それにしても、素敵なお月様の晩よねぇ？@　うぃ～、ひっく♪」@
`"Oh my~, wel~come.`@` Anyway, isn't the moon lovely toniiight?`@` Wee~, hicc♪"`@`
;＜保健

;ld r,KOU_D1,22
ld r,KOU_D3,22

;「やれやれ……。@少し飲み過ぎだね。@お酒は飲むもの、君が飲まれてはあべこべでないかね？」\
`"Really now...`@` You've had a bit too much to drink.`@` Are you sure you're the one drinking, or is your alcohol drinking you?"`\
;＜校長

bg black,22
bg Air_03,22

;「いいのよ、いっそ、飲んでちょうだいよー！@　ったく。@あんた、学校妖怪の長でしょ？@　リーダーでしょー？！@　私に少しは素敵な男を紹介しなさいよー！@　うぃー！@　舐めんな※※～！！@　何が夢を諦めきれねぇだー！@　いい歳こいて、女を振る口実に夢とか語ってんじゃねー！！@　がおおおーー！！！@/
`"It's fine, now hurry up and drink~!`@` Ugh.`@` You're the head of the School Youkai, aren't you?`@` You're the leader, right~?!`@` Introduce me to a nice guy or something~!`@` Hey~!`@` Don't take me lightly,  ***~!!`@` The hell do you mean, 'give up on that dream~!'`@` Don't gimme those excuses about how after a certain age you can jilt a girl~!!`@` Gaaoooooo~~!!!`@`/

se1 47
quakex 1,100

;　ねぇほら！@　紹介しなさいよ、いい男！@　この際、人間でなくてもいいからー！！@　行き遅れとか嫌ぁああぁあッ、うわぁああぁあああん！！」\
`　Hey, you!`@` Get me a good man!`@` I don't even care if he's a human or not anymore~!!`@` I don't want it to be too late for me to marryyyyYyYyYYYyy, UwaaAAaAAA!!"`\

bg black,22
bg okujou_01y,22

;　笑ったり、吠えたり泣いたり、実に賑やかだ。@
`　Laughing, bellowing, and crying. It was awfully rambunctious.`@`
　あぐらをかいて座る校長先生の、恰幅の良いお腹に顔をうずめ、おーいおいおいと泣いている。@
　……こんな酔っ払いの相手は、なるほど、校長先生にしか務まるまい。@
br
　それにしても……、何で人間のはずの先生が、妖怪たちの宴席に？\


ld c,HIG_w3,22
ld c,HIG_D3,80

「人は泥酔すると、波長が人ならざる世に近付くのよ。@……まぁ、見ての通りのザマだし。@明日の朝には何の記憶も残ってないでしょうから、気にしなくていいんじゃない？@　さっきまで、延々と失恋話を語ってくれて、みんな大盛り上がりだったんだから。@くすくす。」\

　……まぁ、よくわからないけれど、楽しくやっているようだし、そっとしておくことにしよう。\

cl c,0
ld r,HIG_D1,23


「それより、毬枝。@校長先生にご挨拶して。@……こんな老いぼれでも、一応、私たちの長なんだから。」@

mld l,KOU_D3,22
mld l,KOU_D1,80

「ほっほっほ。@一応はそういうことになるがね。」\

mcl l,0
ld l,KOU_D1,0
mld c,ma2_D2a,22
mld c,ma2_D4a,80

「きょ、今日は遅刻してすみません。@いつもお世話になっております、めそめその毬枝です。」\

ld l,KOU_D4,80

「どうだね。@妖怪の暮らしは。@面白いかね？」@

mld c,ma2_w2,80

「お、面白いかどうかはわかりませんが、……色々、興味深いです。」\

ld r,HIG_D4,80

「くすくすくすくす。@毬枝ったら、自分の狩りはろくろくしないくせに、@最近は人の狩りの邪魔ばかりしているのよ？」\

ld l,KOU_D1,80

「ほっほっほっほ。@狩りをするも自由、しないも自由。@誰かの邪魔をするのもまた自由。@如何なる者にも縛られぬことのみが、我ら学校妖怪の不文律。@……妖怪など、なろうと思ってもなかなかなれぬもの。@こうして学校妖怪に名を連ねることが出来たのも、何かの運命だ。@その運命、とことんまで翻弄されてみるも一興というもの。」\

mcl c,0
cl l,0
bg black,22
bg Air_03,22


　妖怪になってみてわかったが、……妖怪なんて、おいそれとなれるものじゃない。@
br
　自分が妖怪になれたのも、たまたまの偶然みたいなもの。\

　これは、とてもとても幸運な、……死後のもう一つの新しい人生なんだ。@
br
　でも、死後は死後。@私はすでに死んでしまっていて、全ては取り返しが付かない。\

bg black,22
bg okujou_01y,22
;mld c,ma2_w2,22
mld c,ma2_w1,22

「だからこそ。@………せめて、妖怪の身になった今は。@……本当になりたかった自分に、なってみたいんです。」@

ld l,HIG_D5,22
;ld l,HIG_D5,80

「なぁんて、凛々しいことをたまに言い出すわけだわ。@今度、私の狩りの邪魔をしたら、容赦なく八つ裂きなんだからね？」\

mld c,ma2_i3a,80

「彼岸花さんが、気の毒な人ばかりを獲物にしようとするからですっ。」\

;ld r,KOU_D3,24
ld r,KOU_D1,22

「ほっほっほっほ。@目を離していると、何を始めるかわからん彼岸花くんには、毬枝くんはちょうどいい鈴代わりだね。@……毬枝くん。@彼岸花くんをよろしく頼むよ。@……人形は人形。@一緒に遊んでくれる人がいて初めて、人形たりえるのだから。」\

ld l,HIG_w3,80

「失礼しちゃうわ。@毬枝で遊んでいるのは私だというのに。」@

mld c,ma2_w2,80

「くすくす。@……はいっ、校長先生。」\

mcl c,0
bg black,22
bg okujou_02,22
ld r,Hok_D4,24
ld r,Hok_D1,80

「……そうそう。@めそめそさんって、旧校舎の女子トイレの怪談だったわよねぇ？」@
;＜保健

ld l,ma2_D4,23
;ld l,ma2_D1,80

「え？@　はい、そうですけれど……。」\


　酔っ払って潰れていたと思った保健の先生が、ふいに月を見上げながら呟く。\

bg black,26

me1v 5,50

bg Air_03,22

「大昔。@新校舎なんかなかった頃。@ここは旧校舎じゃなく、立派な校舎だったわけ。@……生徒も大勢いた。@……当然、学校の七不思議も存在したわ。」\

bg black,22
bg okujou_01y,0
ld r,KOU_D1,22
ld r,KOU_D2,80

「………そうだね。@懐かしいよ。」@
;＜校長

ld l,HIG_w1,23
;ld l,HIG_D1,80

「でも、全て消えたわ。@人がいるところに怪談が生まれる。@……人が散れば、怪談も消える。」\
;＜彼岸花

mld c,HOK_D1,22
mld c,HOK_D3,80

「かつてはこの旧校舎にも、立派な七不思議が存在して、そのそれぞれを司る妖怪たちが君臨していたはず。@………しかし今は、誰も残っていない。」@
;＜保健

ld l,HIG_D5,80

「今の生徒たちは、……旧校舎の七不思議なんて、誰も知らないでしょう。」\
;＜彼岸花

mcl c,0
bg black,22
bg gakkou_07y,22
;wait 500
;bg black,22
;bg k_rouka_03,22

　かつて、新校舎などなかった大昔。@
　学校はこの旧校舎だけだった。@
　だからこの旧校舎には大勢の生徒が溢れ、……その生徒たちの中で、自然に七不思議が生まれたはずなのだ。@
br
　………しかし。@今の新校舎に通う生徒たちは、誰もそれを知らない。\

bg black,22
bg gakkou_01y,22

　めそめそさんという例外を除けば、全ての怪談は皆、新校舎かその周辺を指すものだ。@
　旧校舎は、不気味な場所として恐れられてはいるけれど。@
br
　かつて、そこにも学校という社会があり、その中にも七不思議があったことを知る生徒など、@………埃の積もった卒業アルバムに記された、大昔の卒業生たちしか知るまい。\

bg black,22

fede 10,1000
E_MA

bg okujou_01y,22
ld l,ma2_d4,23
;ld l,ma2_D1,80

「……忘れられた怪談の妖怪って、………どうなるんでしょう。」@

ld r,HIG_w3,24
ld r,HIG_D3,80

「死ぬのよ。@いえ、消えるというべきね。」\
;＜彼岸花


cl l,22

ld l,KOU_D2,23
ld l,KOU_D4,80

「忘れられることが、我々、学校妖怪の寿命とも呼べるかもしれんね。@死を超越した我らとて、そのような形での寿命からは逃れられぬとは面白いものよの。@ほっほっほ……。」\
;＜校長

cl r,22
ld r,HOK_D4,22
ld r,HOK_D2,80


「……そんな、妖怪たちの死に絶えた旧校舎に。@あなたは久々に住み付いた妖怪なのよ。@だから。@誰もいなくなって寂しかった旧校舎は、きっと、久し振りの客人であるあなたを歓迎していると思うわ。」@
;＜保健

mld c,ma2_D4a,22

「……………………………。」\
;＜毬枝

mcl c,0
bg black,22
bg k_rouka_02,22

　旧校舎には、今はもう、誰もいない。@
br
　時折、先生が訪れ、倉庫代わりに使っている教室に出入りしたり。@……あるいは、度胸試しや探検に忍び込んでくる生徒がいたり。\

　でも、それだけ。@……学校の喧騒を忘れて久しい、寂しい場所だ。@
br
　そこに、めそめそさんという新しい妖怪が住み付いたことを、……旧校舎は歓迎してくれるだろうか。\


bg black,22
bg okujou_01y,0
ld l,HIG_w3,22
ld l,HIG_D1,80

「ま。@……せいぜい忘れ去られない、恐ろしい怪談になることね。」@
;＜彼岸花

;ld r,KOU_D2,22
ld r,KOU_D1,22

「恐れられてこそ怪談。@夜をさらに深い闇に染めてこそ、昼が明るく輝くのだからのぅ。@ほっほっほ……。」\
;＜校長


　妖怪や怪談が、どんなに恐れられていても。@
　訪れる者が絶えて、誰も語り継がなくなったら、消え去ってしまう。@
　だからこそ彼らは生きるために、……人間たちに忘れられたくないと願うのだ。\

　それを思った時、……妖怪も人間と同じで、@……本質的には寂しがり屋なのかもしれないと、毬枝は思った。\

bg black,22

　校長先生にご挨拶を終え、次に向かう。@
br
　序列第１位の次は、序列第２位。\

bg okujou_02,0
ld l,SIN_D1,22
ld r,ma2_D4a,22

「えっと、紅茶紳士さん、でしたっけ？」@
br

E_A
se1 12
quakey 1,100

　その時、ドンッと一升瓶が床を叩く音がする。@

bgm1 1003

　見ると、……黒いマントを羽織り、あぐらをかいて座る大柄の男が毬枝を睨んでいた。\

;mov %IZA_isyou,2
ld l,SIN_D4,80

「くっくっく。@気にしないことですよ、イザナミさん。」\
;＜紅茶

ld r,IZA_D7,26
;ld r,IZA_D1,80

quakey 2,200

「おいッ、めそめその毬枝ッ！！@　テメェ、ちょっとこっち来い！！」\

　大柄の男は非常に不機嫌そうだ。@毬枝はすぐに失言を直感する。@
br
　そう、紅茶紳士は、影の序列第２位だ。@なら、本来の第２位が存在するはず。\



;ld c,HIG_w3,22
ld c,HIG_w4,22

「くすくすくす。@でもイザナミ、あんたが悪いのよ。」\
;＜彼岸花

;cl c,22
ld l,SIN_D3,80

「同感ですねぇ。@間違えられたくなければ、さっさと毬枝さんの前に姿を現せば良かったのですから。@くっくっく。」\
;＜紅茶紳士

cl r,0
ld c,IZA_D7,24
se1v 12,30
quakex 2,200

「うるせぇッ！@　俺ァ、狩りで忙しいんだよッ。@どこぞの糸目野郎が、すぐに人の獲物を横取りしちまうからなぁ？」@
;＜イザナミ

ld l,SIN_D1,80

「横取りとは心外です。@私は、辛い現実に打ちのめされた少年少女たちに、ただ夢を見せてあげているだけだというのに。」\

ld c,IZA_D6,80

「バーロー！！@　何が夢だッ。@夢ってのァな！@/
quakex 2,200
　自分の手でッ、こうガシッと、掴むもんなんだよ！」@

ld l,SIN_D2,80

「それが出来るほどたくましい子なら良いですが。@それが出来ぬ、か弱き子たちにも救いが必要なのではありませんか？」\

ld c,IZA_D5,80

「ケッ。@なァに甘っちょろいこと言ってやがんだか。@学校はな！@　荒野なんだよ、ジャングルなんだよッ。@ひとりで歩くことも出来ねぇ、貧弱なクソガキがのうのうと生き残れるところじゃねぇんだ！@　俺ァ、それを教えてやってるだけよ。@テメェなんざ、反吐が出る。@/

se1v 12,30
quakey 2,200

ガキの分際で夢だァ？@　百年早ぇってんだッ。」\

bg black,24
bg okujou_01y,24
ld r,SIN_D1,22
ld r,SIN_D2,80

「くっくっくっく！@　相変わらずな人です。@……ご無沙汰していますね、毬枝さん。」@
;＜紅茶

ld l,ma2_D4a,23
;ld l,ma2_D1,80

「ど、どうもご無沙汰しております、紅茶紳士さん。」\
;＜毬枝

ld r,SIN_D3,80

「人は生きるために、時には夢を見ることも大切とは思いませんか？@　……夢さえ見なくなったら、人に生きる意味などあるのですか？」@
;＜紅茶

;ld c,HIG_D5,23
ld c,HIG_w4,22

「……という甘言で、獲物たちをどれだけしゃぶり尽くしてきたやら。@くすくすくす。」\
;＜彼岸花

ld l,ma2_D3a,80

「夢も大事ですが。@……でも、夢は夢の中で見るべきで、……夢の中に生きるべきではないと思います。」\
;＜毬枝

;bg white,25
;se1 12
;quakey 1,100
;bg okujou_01y,0
;ld l,ma2_D4a,22

cl c,0
cl r,0

ld r,IZA_D5,24

se1v 13,50
quakex 2,200

ld r,IZA_D6,80

「よく言ったッ。@おい、紅茶野郎ッ、毬枝の言うこと、よォく耳をかっぽじって聞いとけよ！@　……毬枝、……お前ェ、死んでからだいぶ変わったなァ？@　根性出てきたぞ、気に入った。@……俺ァ、イザナミ。@学校妖怪序列第２位、１３階段の死神たァ、俺のことよ。」\

bg black,22

me1v 16,50

bg kaidan_01,22

　１３階段の怪談は、どこの学校でも定番中の定番だ。@イザナミはそれを司る。\

bg black,22

fede 10,1000
E_MA

bg okujou_01y,22
ld r,HIG_D3,22
;ld r,HIG_D1,80

「イザナミは恐ろしい妖怪よ？@　１３階段を踏ませた哀れな獲物を、どこまでも追い詰めて、恐ろしい地獄へ突き落とすの。」@
;＜彼岸花

ld l,IZA_D4,22
ld l,IZA_D5,80

「はッ、お前ェの狩りも大概だろーが！」\

cl r,0
cl l,0
ld c,IZA_D1,23

　握手を求められ、手を差し出すと、@……分厚い、がっしりした手に、痛いくらい力強く握られた。\

ld r,ma2_D3a,24
ld r,ma2_D4a,80

「ど、どうも……。@めそめその毬枝です。@よろしくお願いします。」@

ld c,IZA_D2,80

「おう。@お互い、バケモンだ。@せいぜいクソガキどもを、ガンガン地獄に突き落としてやろうぜッ。」\


ld r,ma2_d2a,80

　まぁその、がんばります……と曖昧に笑う毬枝であった。\

bg black,2
wait 1000

bg okujou_02,22

　序列第２位の次は第３位。@それは彼岸花のことだ。@
br

ld r,ma2_D1,24
ld r,ma2_w1,80
wait 300
ld l,HIG_D1,22
ld l,HIG_w3,80

　よろしくお願いします、こちらこそ、と白々しく二人で挨拶する。\

bg black,2
bg okujou_01y,22

　次は、序列第４位。@……これも会ったことはない。@初対面だ。@
br
　案内される先には、着物姿のスミレと並んで酒を酌み交わす、同じく着物姿の女性の姿があった。\

ld l,SMI_w1,23
ld l,SMI_w3,80
se1 47
quakey 1,100

「おぉ、毬枝なのじゃ！@　珍妙な服を着ておるわ！@　まるっきり似合わないのじゃ！」@
;＜スミレ

ld c,AZA_D4,22
ld c,AZA_D2,80

「そんなことはありませんよ。@とても良く似合っています……。@どうぞ、こちらへ。@毬枝さん。」\
;＜アザミ

ld r,HIG_D4,24
;ld r,HIG_D1,80

「紹介するわ。@学校妖怪序列第４位のアザミよ。」\
;＜彼岸花

cl c,0
mld c,AZA_D1,80

「アザミと申します。@どうぞお見知りおきを……。」@
;＜アザミ

ld l,SMI_w4,80

「私の姉者なのじゃ！！@　姉者は強くて賢くて、麗しくてとても残忍な大妖怪なのじゃ！」\
;＜スミレ

mcl c,0
cl a,0
mbg black,22

mcbg 22
ld r,ma2_D4a,22
;ld r,ma2_D1,80

「妖怪にも、姉妹がいるんですね。」@
;＜毬枝
br
　序列第４位のアザミと、序列第７位のスミレの姉妹。@
　学校妖怪の中で、唯一の姉妹だった。\

ld l,HIG_w3,23
;ld l,HIG_D3,80

「たまにね。@……まぁ、元々私たちは、誰かを親に生んでもらった存在ではない。@家族関係など、あってもなくても同じようなものだけれど。」\
;＜彼岸花
bg black,24
bg okujou_02,0
ld r,SMI_w4,24
ld r,SMI_w3,80

「お前のような、嫌われ者のひとりぼっちとは違うのじゃ！@　私と姉者は大の仲良しなのじゃー！」@
;＜スミレ

ld l,AZA_D4,23
ld l,AZA_D3,80

「うふふふふ。@この子ったら、すっかり酔いが回ってしまったようで……。」\
;＜アザミ

　妖怪の世界に、仮に家族関係があろうとなかろうと。@二人の関係はちょっと微笑ましいものに思えた。@
br
　その様子を見ている彼岸花が、わずかに寂しそうに口を尖らせているのを、毬枝は見逃さない。\

bg black,22
bg okujou_01y,0
mld c,HIG_D8,22
;ld r,ma2_D1,22

ld r,ma2_w1,22
ld r,ma2_w2,80

「……妖怪は、ひとりぼっちかもしれません。」@

mld c,HIG_w3,80

「何よ。」@

ld r,ma2_w1,80

「だから家族はいないけれど。@……でも、友達は作れると思います。」\

mld c,HIG_d2,80

「あぁ、そうだったわね。@あんたは、私のお友達だったわね。」@

ld r,ma2_w2,80

「だから、彼岸花さんが、ひとりぼっちだなんて思う必要は、まったくないと思います。」\

mcl c,0
ld l,HIG_d5,24

「やめてよ、私の心を読まないで。」@
br
　妖力を蓄えた妖怪たちは、相手の心を読み取る力を持つ。@しかし、毬枝にはその力はない。\

ld r,ma2_w1,80
wait 500
ld l,HIG_w1,80
cl l,22

　でも、わかるのだ。@友人だからこそ。@
br
　彼岸花は、ぷいっとそっぽを向いてむくれたふりをする。\

bg black,24
bg okujou_02,24
ld r,AZA_D4,22
;ld r,AZA_D1,80

「うふふふふふふ。@あの彼岸花に友達が出来るなんて。@つくづく、世の中はわからないものです。@どうか、これからも仲良くしてあげて下さいね。」\
;＜アザミ

　このアザミという人は、何だかいい人のような気がする。@
br
　魂を糧とする妖怪のひとりなのだから、素直な意味でいい人のわけもないのだが、@少なくとも、理不尽な性格ではなさそうだ。\

mld l,SMI_w3,23
mld l,SMI_w5,80

「そうだろうそうだろう、いい人に見えるであろう！@　しかし、このいい人っぷりこそ姉者の最大の武器なのじゃ！@　何しろ姉者の偽善者っぷりと言ったら、@/

cl r,0
ld c,AZA_D1,24
se1 48
mld l,SMI_i1,1
quakex 2,200

あいだだだだだだだだだッ！！！」\

ld c,AZA_D5,80

「うっふふふふふふふふふー…！！！@　スミレはたまにおかしなことを言い出すもので、うっふふふふふふ…！」@
br

mld l,SMI_i3a,80
se1 47
quakey 2,300
se1 48
mld l,SMI_i1,1
quakex 2,300

　どこをどう抓っているやら。@スミレは涙目で痛い痛いと飛び跳ねている。\

cl c,0
mcl l,0
mbg black,22

mcbg 0
ld c,HIG_w3,22
ld c,HIG_d3,80

「そうそう、アザミとスミレの姉妹らしいところがあるとしたら。@二人とも、いじめに絡んだ狩りをするという点かしら。@……学校はいじめでいっぱいだもの。@食いっぱぐれないわ。」\
;＜彼岸花

bg black,22

fede 0,1000
E_A

bg okujou_01y,22

bgm1 31

　残るは、序列第５位と第６位。@
br
　それにさくのしんが加わり、３人でお酒を飲んでいるようだった。\

ld c,SAK_D4,22
ld c,SAK_D2,80
se1 47
quakey 1,200

「うりゅー！@　毬枝ー！@　みんなにご挨拶は済んだー？」@

ld l,ma2_w2,23
;ld l,ma2_D1,80


「はい。@こちらの皆さんにもご挨拶したいと思いまして。」\

ld r,HIG_D2,24
;ld r,HIG_D1,80

「さくのしんは学校妖怪八席ではないけれど。@動物霊の長を務める大妖怪。」\
;＜彼岸花

ld c,SAK_D4,80

「うりゅー！@　だから僕もこうしてお呼ばれしてるのー！@　そうだ、毬枝。@紹介するね！@　この子は、序列第６位の……、@/
ld c,SAK_k3,80

……あれれ、寝ちゃった？@　うりゅー。」@
br
　毬枝より年下に見える小さな子が、猫のように丸まって、すやすやと眠ってしまっている。\

ld r,HIG_D3,80

「その子は、序列第６位、美術室のルノワール。@……大人しい子よ。@あまり熱心に狩りをする子でもないし。」\
;＜彼岸花

cl a,0
mbg black,22

mcbg 0
ld c,KYO_D2,22
ld c,KYO_D5,80


「……ルノは狩りをしなさ過ぎて、妖力がほとんど枯れちまったヤツだけどな。」\
;＜キョウ

ld r,HIG_w3,22

「元々、九十九神だからね。@ただ眠っているだけでも、本来の妖力は侮れないわ。」\
;＜彼岸花

　第７位のスミレは、いじめを撒き散らし、積極的な狩りをしていた。@
　にもかかわらず、このルノワールという妖怪は、ほとんど狩りをしないのに、序列はそれより高い。@
　だとするなら、元々、相当の大きな力を持つ妖怪に違いあるまい。\

ld l,ma2_w1,22

「では、あなたが第５位の……？」@

cl c,0
mld c,KYO_D1,80

「俺様は序列第５位の、鏡のキョウ。@……鏡の世界の境を司る番人よ。」\
;＜キョウ

mcl c,0
bg black,23
bg okujou_02,0
ld r,SAK_D2,23
;ld r,SAK_D4,80
se1 47
quakey 1,200

「キョウくんは僕と同じ、動物霊なんだよっ。@だから仲間なんだよ、うりゅー！」\

ld c,KYO_D2,23
ld c,KYO_D4,80

「俺様はお前みたいな草食ライオンの仲間じゃねぇっ。@俺様は狼だ、ウルフだ、ハイエナだ。@愚かな人間どもの、鏡に映る邪悪な面を引き摺り出し、狩り殺す。@クールなクールなハンターなのさ……。」\

　眼光鋭くそう言い、ぐびりと杯を傾ける。@
br
　……何と言うか、……独特の雰囲気を持つ人のようだ。\

ld r,SAK_D4,80

「これで挨拶回りは終わったでしょ？！@　毬枝も飲もー飲もー！！」\
;＜さくのしん

bg black,23
bg okujou_01y,23
ld l,HIG_D5,22
ld l,HIG_D4,80

「そうよ。@お月見会なのに、お酒の一杯も飲まないでおしまいなんて、あんまりだわ。」@
;＜彼岸花

ld c,ma2_D4a,24
;ld c,ma2_D1,80

「で、でも、私、大人じゃないですし…！@　お酒なんて飲んだことありませんしっ。」\

;ld r,KYO_D3,24
ld r,KYO_D5,24

「それ以前に、人間でもないだろうが。@それにこれは人間の世界の酒とは違う。」@
;＜キョウ

ld c,ma2_D4,80
「え？@　これ、お酒じゃないんですか？」\

bg black,22
bg Air_03,22

　赤い杯に、なみなみと注がれた透き通る液体は、ぱっと見にはお酒に見える……。@
br
　しかし、それに、はらりと桜の花びらが浮かび、月が浮かぶと、とても風流なものに見えるのだ。\

　顔を近付けると、ふわりと甘い、果物を思わせる香りが鼻を通り抜ける。@
br
　とはいえ、ダメダメッ、お酒は大人になってからっ。\

bg white,23
bg okujou_02,0
ld l,KYO_D2,23
;ld l,KYO_D1,80

「だから、酒じゃないって言ってるだろ。」@
;＜キョウ

ld r,HIG_d3,24
;ld r,HIG_d3,80

「あのね。@これは、黄泉桜の花びらを砂糖漬けにしたものを、桜のうろに入れ、@まー、色々としたのから搾り出した、言わばジュースというわけ。」\
;＜彼岸花

ld c,ma2_w2,22
;ld c,ma2_D1,80

「……あ、なんだ。@ジュースなんですか。@なら飲めます。」@

ld l,KYO_D1,80

「そら。@ぐびりと行って、フルムーンごと飲み干せ。」\
;＜キョウ

bg black,22

;ld c,ma2_i4a,80

「で、では失礼して……。@……ごくりごくり。」@

;cl l,22
;ld l,SAK_D2,26
;ld l,SAK_D4,80


「うりゅー！@　すごいー！@　毬枝、豪快な飲みっぷりー！！」\

;ld c,ma2_w2,80

bg Air_03,22

「ぷっはー！！@　ってこれッ？！@　ほ、本当にジュースなんですかぁ？！@　め、目が回って……、あぁあぁぁ～……。」\

;cl c,5
;ld r,HIG_w4,80

「えぇ、そうよ、ジュースよ、ジュース。@妖怪のジュースだけれどね。@くすくすくすくすくすくす。」\


bg black,24
bg okujou_01y,24
ld r,KYO_D6a,22
;ld r,KYO_D1,80

「おいおい、大丈夫かよこいつ。@……完全にぶっ潰れてるぞ。」@
;＜キョウ

ld l,HIG_d5,22
;ld l,HIG_w1,80

「でも美味しかったでしょ？」\
;＜彼岸花

ld c,ma2_D2a,6
;ld c,ma2_D1,80

「ぇぇ、はぃ～……。@目が回るけれど～……、おいひぃれすぅぅ～……。」@
br

cl c,5
se1v 13,50
quakey 2,200

　世界がぐるぐる回って、だけれども、とてもとても不思議な、幸せな気分でいっぱいになる。\

bg black,22

fede 0,1000
E_A

bg Air_03,22
dllefe 6,3
;print 22

bgm1v 1003,0

fedexx 70,0,0,0,0,0,3000
wait 1000

　世界が桜色に染まり、屋上に茂る黄泉桜がますますに花を開き、@花びらの嵐で祝福してくれるかのように感じられた。\


　毬枝が口にしたものは、人間たちの飲む酒とは異なる。@
br
　しかし、妖力の足りない毬枝が口にすると、人間が酒に酔っ払うのとよく似た症状を引き起こす。\

「ここは、旧校舎でもっとも妖力の高い場所。@……その妖力は古く、長く寝かされ、新校舎のそれとは比べ物にならないくらいに深い。@……それを養分に茂る黄泉桜から作られるその雫は、まさに絶品。@この世ならぬ味わい。@……もし、毬枝がそれをとても美味しく感じてくれたなら。@……それはこの旧校舎が、あなたを歓迎しているということなのよ。」\
;＜彼岸花

;bg black,22

　……さっき保健の先生に聞いた気がする。@
br
　忘れ去られた旧校舎には、今は誰も住まわない。@……そんな旧校舎に私が住み着いて、きっと旧校舎も喜んでいるだろう、って話……。\

bg okujou_04,0
ld c,HIG_w2,22
ld c,HIG_w1,80

「……だから、旧校舎はあなたを招いたのよ。@………そして、最高の黄泉桜の花で作った雫を、あなたに振舞いたかったに違いない。」\
;＜彼岸花

　確かに、………それはこの世ならぬ、絶品の味。@
br
　毬枝の全身を、温かな、じんわりとする心地良さが、やさしくやさしく染み渡るのだ。\

　降り積もる桜の花びらに、柔らかく埋もれ、……羽根布団の中で眠りに落ちていくかのような心地よさ……。@
br
　それは、生まれて初めて、そしてもちろん、死んで初めて味わう、極上の悦楽だった……。\

bg black,22

　……もう、彼岸花の声も聞こえない。@
br
　全てがやさしくやさしく降り積もって、……柔らかく包み込んでいく。\

　………そっか。@旧校舎はずっと、寂しかったんだ。@
　それで、私という妖怪が久し振りに住み着いて、……嬉しかったんだ。@
br
　……なら。@私は学校妖怪のみんなだけじゃなく、……旧校舎さんにも、挨拶をしなきゃ。\

　………こんにちは、旧校舎さん。@
　めそめその毬枝と申します。@
br
　どうかこれからも、よろしくお願いしますね………。@
　…………………………………。\

;print 0
bg white,2
dllefe_off
bg white,80

fede 0,3000
E_A
wait 1000


;※ここからはもう、毬枝の立ち絵はいつも通りに
mov %HIG_Isyou,1
;bg white,2

　………まるで、日曜日の朝の布団の中のような気持ちよさ。@
　いつまでもこうして、……眠っていたい………。@
　……あぁ、でも彼岸花さんがずっと呼んでる……。@
　返事してあげないと拗ねちゃう……。@……むにゃむにゃ……。\

bg black,2

me1v 16,50

bg okujou_01u,2
ld r,HIG_D5,22
;ld r,HIG_D2,80

「毬枝？@　いい加減に起きたら？@　妖怪だって風邪を引くのよ？」@

ld l,MAR_D2a,6
ld l,MAR_D4a,80

「……ふぁ……、彼岸花さん…………。@……あれ？@　…………………。」\

　いつの間にか、夜が明け始めている。@
　黄泉の桜もなくなり、宴席は影も形もなくなっている。@
br
　ちょっとみんなに挨拶しただけだったのに、@……私が眠っちゃったんで、そのままお開きになってしまったんだ……。\

ld r,HIG_d10,80

「それよりあんた。@何でこんなところで寝ているわけ？」@

ld l,MAR_D3a,80

「何でって。@……彼岸花さんたちに飲まされて……、それで気持ちよくなって………。」\

ld r,HIG_D9a,80

「何の話？」@
br

cl r,0
ld c,HIG_d9,24

E_A

se1 48
quakey 1,100

　彼岸花は、あんたまだ寝惚けてんの？　と言って、@毬枝の頭を、調子の悪いラジオのように叩く。\

ld c,HIG_D10,80

bgm1 8

「毬枝が、どうしても素敵な服で参加したいからって言って。@私、だいぶ待ったのよ？」@

ld l,MAR_D2a,80

「あ、はい……。@それでだいぶ遅刻しましたけど、参加して……。」\

cl c,0
ld r,HIG_D9,23

「何を言ってるの？@　あんた、結局、来なかったじゃない。」@

me1v 16,50

br
　彼岸花と話が噛み合わない。\

ld l,MAR_D3a,80

「……彼岸花さんこそ、何を言ってるんですか？@　私、こうして、ここに来て、一緒に皆さんとご挨拶をしたじゃないですか。」\

bg black,22
bg gakkou_07y,22

「ここに来てって。@……ここ、旧校舎の屋上よ？」@
「えぇ、はい。@旧校舎の屋上ですよ？」\

bg black,22
bg okujou_01u,22
ld l,HIG_d10,22
;ld l,HIG_D1,80

「何を言ってんの。@新校舎の屋上に決まってるでしょう？@　あんたまさか、ここだと勘違いして、ずっとひとりでここで待ってたわけ？！」@

ld r,MAR_D4a,24
;ld r,MAR_D1,80

「え、……で、でも…………。」\

ld l,HIG_D5,80

「あのねぇ。@あれだけ遅刻して到着して。@誰もいなかったら、場所を間違えたって普通は思わない？@　それで待ちくたびれて、寝ちゃってたってわけ？@　あぁ、毬枝……。@あんたって、そこまで愚かだったのね……。」@
br
　彼岸花は、さんざん毬枝を馬鹿にすると、肩を竦めながら嘆く。\

ld r,MAR_D2a,80

　でも、毬枝もわけがわからなくなってしまうのだ。@
　そんなはずはない。@確かにここで、みんなは宴席をしていたじゃないか……。@
br
　わけがわからず、ひょっとしてまだおかしな酔いが続いているのかと、毬枝は自分の頬を抓るしかない。\

ld l,HIG_w4,80

「せっかく、素敵な黄泉桜が茂って、美味しい桜酒が出来たのに……。@人間には味わうことの出来ない極上の味を、あんたに教えてあげようと思ったのに。@はーっ。」\

ld r,MAR_D4a,80

「はい。@……それはいただきました。@すごく美味しかったです。」@

ld l,HIG_D10,80

「飲めるわけないでしょ？@　あんた、来なかったんだから。」\

ld r,MAR_D2a,80

「……わ、私が寝惚けていたのかもしれないですけど。@……確かに昨夜、ここにも黄泉の桜が茂っていたんです。@そして私はその桜のお酒を……。」@

ld l,HIG_d9,80

「黄泉桜が、旧校舎の屋上に……？」\


mbg black,22

;bg white,8
;bg Air_03,0
;dllefe 6,3
;print 22

「は、……はい。@……すごい幻想的な、美しい光景でしたよね……。」@
br
　仮に、昨夜の宴席が丸ごと幻だったとしても。@
　あの屋上に咲き茂る黄泉桜の美しさは、断じて幻だったとは思えない。\

;dllefe_off
;print 0
;bg black,22

fede 1,1000
E_B

mcbg 0
cl a,0
;bg okujou_01y,22
ld r,HIG_d8,22
;ld r,HIG_d4,80

「……毬枝。@確かにその昔。@ここにも黄泉桜は咲いたそうよ。@でもそれは、ここに子供たちが通っていた大昔の話だわ。@今や寂れ、旧校舎には黄泉桜が花を咲かせる養分もないはず。」\

ld l,MAR_i4a,23
;ld l,MAR_D1,80

「で、でも、咲いてたんですよ？！@　すごく美しくて不思議な光景で……。」\

ld r,HIG_D5,80

「………………………………。@……それは本当に？@　だとしたら、とても珍しい、奇跡に違いないわ。@……そしてあなたは、その黄泉桜のうろのお酒を、飲んだわけ？」@

ld l,MAR_D4a,80

「はい……。@とても甘い香りと味で、……とても美味しかったです……。」\

textoff

fede 0,1000
E_A

ld r,HIG_D3,80

「…………………。@……何てことかしら、毬枝。@……あなたはひょっとしたら、すごく強運なのかもしれないわね。」@

ld l,MAR_D3a,80

bgm1 1003

「どういう意味ですか……？」\

ld r,HIG_D2,80

「妖力もお酒に似てて、古く長く寝かせたものは、より強い力を宿すの。@……だから、もしもこの旧校舎に奇跡的に黄泉桜が生えて、そこから作られた桜酒だったなら。@……恐らくそれは、この世のものとは思えぬほどに、美味なものだったはず。」\

;ld l,MAR_D1,80

　……そうだ。@毬枝は昨夜、確かにそんなことを言われた。\

ld r,HIG_w2,80

「だとしたら、羨ましいわ。@……新校舎の黄泉桜は、まだまだ若い。@美味しいには美味しいけれど、あんたが味わったそれには、足元にも及ばないはず。@……存在しないはずの旧校舎の黄泉桜に、最高のお月見日和の満月の晩に出会えて、@最高の桜酒を味わえたなんて。@毬枝は本当に幸運だわ。」\

ld l,MAR_D4a,80

　……毬枝は、何が何だか、まるでわからない。@
　でも、昨夜のお月見会が、夢か幻ではないことは確かなのだ。@
　彼女の襟元に付いた、黄泉桜の花びらが、それを静かに物語っていた。@
br
　毬枝は改めて、昨夜のことを話す……。\

bg black,22
bg okujou_03u,22

;ld r,HIG_D1,80

「……ふぅん。@不思議なこともあるものね。」@

;ld l,MAR_D2a,80

「私だって妖怪のはずなのに。@……昨夜、何があったのか、さっぱりです……。」\

;bg black,22
;bg Air_03,22

「あまりに素敵なお月見の晩だったし。@……あんた、人が良さそうだからね。@……旧校舎の主に、呼ばれちゃったんじゃないかしら。」@
「……………………。@……そうですね。@………そうかもしれませんね。」\

　ありがとう、旧校舎さん。@
br
　また、月の綺麗な夜には、ご一緒しましょうね。@
　どうか、今後ともよろしくお願いします。\


;＜おしまい＞

;※ここでOPムービー

bg black,2

fede 0,1000
E_A

movie "movie\higan_op1.mpg",click
;bg black,42

;bg e022,42
wait 1000
bg black,42
bgcopy ;背景をリセット

fede 0,2000
E_A
wait 2000

if %UMINEKOEND < 1 mov %UMINEKOEND,1 : mov %END_FLG,1 ;クリアフラグの変更

	saveoff            ;セーブオフで、処理を高速化する。
	erasetextwindow 0  ;テキストエフェクトを切る事で処理を高速化
	rmode 0            ;右クリックのメニュー表示の無効化
	textoff

goto *b_title
;reset


*higan7_opning
texton
csp -1

bg black,2
bgcopy ;背景をリセット

setwindow 31,16,22,16,26,26,0,2,20,1,1,#999999,0,0,639,479

!sd

mono 0
E_A

;■彼岸花の咲く前に

bg gakkou_01,2
bgm1 5
