;Chapter 4
;　美術室の中は静かだった。\
` The art room was silent.`\

;　下校時刻を過ぎて残っている生徒達は、大抵自分の教室か、校庭か、あるいは部室にいる。@
` Once the final bell rings and school ends, the remaining students can usually be found either in their one classrooms, the schoolyard, or the club rooms.`@
br
;　４階にあるこの美術室まで彼等の声が届くことはない。@まるで空間から切り取られたかの様にひっそりと静まり返っている。\
` Their voices hardly ever reach all the way up to the art room on the 4th floor. `@`It becomes so deathly quiet, it's as if the sound was torn from the very air itself.`\

bg black,23
bg bijutu_02,23
ld r,NOD_D1,22

bgm1 8

;　美術室の壁に掛けられている絵は、平均的な感覚を持つ生徒にとっては薄気味悪いものが多い。@
` To the average student, the pieces of art adorning the art room walls emanate a sense of eeriness.`@
;　そんなもので満たされている美術室に、好んで放課後に訪れようと思う生徒は、そう多くはない。\
` there are very few students who would go out of their way to visit this room after school just to see these walls of art.


ld r,NOD_D4,80

;　……そう言えば、@最近クラスのみんなが噂していた学校の八不思議の中に、美術室にまつわる怪談があったような。@
` ...On that note, `@`lately the entire student body has been talking about how the art room contains one of the school's eight mysteries.`@
br
;　美術室にかけられた絵を見ながら、野田裕貴（のだ　ゆうき）はそんなことを思い出していた。\
` As he stood looking at those walls of art, those rumors were at the forefront of the mind of Yuuki Noda. (野田裕貴)`\
bg black,22

;　確か、放課後、一人で美術室を訪れた子供の前に、絵から抜け出した妖怪が現れて問い掛けをする、@という怪談だった気がする。\
` According to those stories, `@`if a kid ventures into the art room alone after school, a youkai will come out of the paintings and ask them a question.`\

;bg black,1
mono 2
bg different_spiral_1a,22


;　……問い掛けってどんな問い掛けなんだろう……？@
` ...But what kind of question does he ask I wonder...?`@
;　「赤マント、青マント」みたいなやつかな……。\
` Maybe it's like the 'red cape or blue cape' ghost story...`\

;　それは学校の怪談としては有名なものだ。@昔からどこかしらの学校では必ず噂になっている。@
` It's a famous ghost story, usually set in a school. `@`It must have become an urban legend at some school a long time ago and spread from there.`@
br
;　……夜中、トイレに一人で入っていると、@赤マントという妖怪が現れて「赤マント、青マント、どっちが欲しい？」と問い掛けてくる。\
` ...The story goes that if you eneter the bathroom alone late at night, `@`a youkai called The Red Cape will ask you "Do you want a red cape or a blue cape? Choose one."`\

;　「赤マントが欲しい」と言うと体中を刺され、血まみれになって死んでしまう。@
` If you reply that you want a red cape, your body will be stabbed all over, and you will die a bloody death.`@
;　しかし、「青マントが欲しい」と言っても、今度は全身の血を抜かれて真っ青になって死んでしまう……。\
` And if you reply that you want a blue cape, all the blood will be sucked out of your body and you will die a cold death, leaving nothing but a blue colored corpse...`\
bg black,22
;bg black,1
mono 0
bg bijutu_04,0
ld c,NOD_D1,22

;　……そんなの、出会った時点で終わりじゃないか。@
` ...There's no way to survive a story like that.`@
br
;　この怪談を聞いたとき、裕貴はそんな風に思った。@八方塞がりで逃げ場がない。@フェアじゃない駆け引き。\
` That is what Yuuki thought when he first heard this ghost story. `@`Both choices were bound to kill you. `@`It wasn't fair.`\

;　学校によってはこの怪談にはいろいろパターンが違うらしい。@
` Apparently, this ghost story changes depending on which school its told at.`@
;　青マントの罰が「水責め」だったり、赤、青の他に黄色マントがあったり……。\
` Some versions of this story have The Red Cape use water torture, and some even include a yellow cape along with the other two...`\

;　ちなみに黄色を選んだ場合の罰は「感電死」らしい。@どんなパターンにせよ、「結局は殺される」と言うところは一貫している怪談なのだそうだ。\
` Incidentally the punishment for the yellow cape is apparently death by electrocution. `@`In all variations the pattern is the same. No matter what you do, you'll die.`\

;　しかし、クラスメート達が言うには、この美術室に伝わる怪談には一応逃げ場があるらしい。@
` But, according to his classmates, in the ghost story associated with this school's art room, there is one way out.`@
;　いくつか存在するルールを破らず、問い掛けに正確に答えさえすれば、助かるのだそうだ。\
` As long as you correctly answer the question without breaking any of the rules associated with the story, you'll be able to survive.`\
bg black,22
;bg black,2

;　……でも、もしもそんなシチュエーションが訪れたとして、@生きるも死ぬも選べるとしたら、僕は一体どっちを選ぶんだろう………？@
` ...But if he was put in that situation, `@`and his choice would decide if he lived or died, which choice would he make....?`@
br
;　裕貴にはそれが分からなかった。\
` That is what Yuuki wondered.`\
;　自分がいったい何を望んでいるのか。@助かるものなら助かりたいのか。@生きたいのか、それとも死にたいのか。@それがよく分からなくなっていた。\
` He wonders what he truly wants. `@`If he could survive, would he want to? `@`Would he want to live, or to die? `@`He simply does not know.`\
bg bijutu_06,22
;ld c,NOD_D1,22
;ld c,NOD_D4,80

;　自分は一体何を望んでるんだろう。@
` Just what does he want?`@
;　服の上から腕の傷をおさえる。@
` He rubbed a cut on his arm through his sleeve.`@
br
;　……自分で自分が、よくわからない。@
` Not even he himself knows.`@
;　わからないから、……今日もこうして、美術室にいる。\
` He has no idea... so today he has once again come to the art room.`\
bg black,22
E_A

;　その時。@……唐突に美術室の隅から声が聞こえた。\
` At that moment.`@`... A voice echoed out from the corner of the romm.`\
br
;「……………その絵、好き？」\
`"......Do you like those pictures?"`\
;■ここは野田君の立ち絵だけです




;bg bijutu_03,0
;ld r,NOD_D1,23

bg kaiga_02,22

bgm1 27

;　はっと声の方を振り返った裕貴の目の前に、一人の可愛らしい女の子が立っていた。\
` Startled, Yuuki turned around to see where the voice came from. Standing there was a cute, young girl.



;　柔らかそうな長い髪、大きな瞳、鮮やかな青いスカート。@
` She had long, soft looking hair, large eyes and a bright blue skirt.`@
;　一瞬息をするのも忘れるほど美しい少女だった。\
` She was so beautiful that for a moment he had forgotten to breathe.`\

;「……………その絵、好きなの？」@
`"......Those pictures. Do you like them?"`@
br
;　その子がまた聞いた。@綺麗な声だった。\
` She asked again. `@`She had a lovely voice.`\
ld r,NOD_D5a,24

;　裕貴はわかりやすいくらいおろおろした。@
` Yuuki was clearly nervous.`@
;　今日は美術部の活動の日じゃない。@放課後、裕貴以外の人間が美術室を訪れることはほとんどなかった。\
` There shouldn't be any activities in the art room today. `@`And very few people besides Yuuki would ever come all the way out to this room.`\


ld r,NOD_D4,80

;「………う、うん。@好きだよ。」@
`"....Y- Yeah. `@`I like them."`@
br
;　ようやく出た声は、少し上擦っていた。\
` He answered in a nervous voice after a long pause.`\


;「へぇ……。@珍しいね。@みんな、ここに飾ってある絵は怖いって言って、全然、見に来ないのに。」@
`"Really...? `@`How strange. `@`Everyone says that the pictures decorating the walls here are scary, and never come to see them."`@
ld r,NOD_D1,80

;「……確かに、……ちょっと偏っているかなぁ。」\
`"...That does seem... a little closed-minded."`\


;cl a,0
;bg bijutu_07,24
;ld c,NOD_D1,22

bg black,24
bg kaiga_01,24
;ld c,NOD_D1,22

;　改めて教室の壁にかけられた絵を見回す。@
` He took another look around at the art on the classroom wall.`@
;　美しい少女の絵、可愛らしい動物の絵の合間合間に、等間隔で残酷な絵画が飾られている。\
` Among the pictures of pretty girls and cute little animals, periodically there were much darker paintings adorning the wall.`\

;　何かの本で読んだのだけど、@恐ろしいもの、怖いものを見ることは、情操教育の上でも必要らしい。@
` He had once read in a book, `@`that seeing horrible and scary things is needed to develop a sense of aesthetics.`@
;　綺麗なものだけを見続けることの方が、逆に精神的に良くない影響を与えるのだとか何とか。\
` If all you ever see are pleasant and pretty things, then that can have a negative influence on your mental and emotional state.`\


;ld c,NOD_D4,80

;　……でも、それにしたってこの美術室の絵は極端な気がした。@
` ...but, even so, he couldn't help but feel that some of the art on these walls were too extreme.`@
;　どれも名画と呼ばれるものには違いないが、残酷な描写があり過ぎる。@子供が夜中一人で見たら泣き出してしまうくらい怖い。\
` Each and every one of them was probably considered a masterpiece, but they portrayed scenes far too dark. `@`They were so scary that if a kid saw them in the middle of the night, they would probably burst into tears.`\

;「この教室を訪れる子たちは、みんなそう思っていて怖がっているよ。@……美術室はオバケ屋敷みたい、って言ってね。」@
`"All the kids who come to this room think that they're scary.`@`... They say that they make the art room look like a haunted house."`@
br
;　少女はそう言って笑うが、少しだけ寂しそうだった。\
` The girl spoke with a smile, but something about it seemed lonely.`\


;ld c,NOD_D1,80
ld c,NOD_D2,80

;「確かに、ちょっと怖い絵も多いけれど。@……でも、僕は好きだよ。@ここの絵。」@
`"I mean, sure, there are a bunch of scary pictures here.`@`... But I like them. `@`These pictures."`@
;「………本当に…？」\
`"....Really...?"`\


ld c,NOD_D3,80

;「うん。@いつも見てるけど、@……やっぱり、巨匠と言われる人たちの絵は、どれもその、……迫力とかが、すごいと思う。」\
`"Yeah. `@`I see them all the time... `@`but it always amazes me at what an impact the art of a great artist can have."`\


;cl a,0
;bg black,22

;　それらの絵画を理解するには、裕貴はまだまだ幼いだろう。@
` Yuuki may be too young to completely grasp the meaning of these works of art.`@
;　しかし、……彼は、それらから形容し難いインスピレーションを感じている。@
` But... he had a hard time explaining the inspiration he felt from them.`@
;　それがどのようなものなのか、うまく説明する言葉が思いつかないから、それを迫力と表現するのだ。\
` He wasn't sure how exactly to put it into words, but they had a strong impact on him.`\

;ld c,NOD_D1,80

;　……確かに、クラスメートたちが美術室をオバケ屋敷と呼んでいるのは知っている。@
` ...He knew that his classmates called the art room a haunted house.`@
;　自分も、みんながそう思うのは無理もないと思っている。\
` He thinks it's natural for them to think that way.`\

bg black,23
bg bijutu_03,23


;　……でも、何となく、自分は美術室が好きだった。@
` ...But, for some reason, he really liked the art room.`@
;　怖い絵がたくさんあるのは知ってる。@……確かに怖い。@
` He knew that there were a lot of scary pictures in the room.`@`... and they scared him too.`@
br
;　でも、そんなものも含めて、……色々なインスピレーションに満ち溢れている。\
` But even those pictures... filled him with a strong sense of inspiration.`\


;bg bijutu_02,0
;ld r,NOD_D1,22


;　この美術室は、単調な日常から自分を解き放ってくれる、別世界への飛行場。@
` This art room frees him from the monotony of his everyday life. It is an airport to another world.`@
;　そんな風に感じ、……初めて知る異郷の文化のような、カルチャーショックを与えてくれるのだ。\
` That's the kind of feeling it gives him... It makes him experience a culture shock like learning about a mysterious new culture for the first time.`\
bg black,24
bg kaiga_02,24

;「…………美術室をオバケ屋敷と呼ばない子なんて、本当に珍しいね。」@
`".....It's rare to meet someone who doesn't consider this room to be like a haunted house."`@
br
;　少女はとても嬉しそうに笑った。@……まるで、自分のことを褒められたかのようだった。\
` The girl smiled joyfully.`@`... almost as if she herself had been praised.`\


;「君は、どの絵が一番好き？」@
`"Which picture is your favorite?"`@
;ld r,NOD_D1,80
ld l,NOD_D2,23

;「そうだなぁ………。」@
`"Hm, good question...."`@
br
;　壁にかけられた絵を見回す。\
` He looked over the pictures hanging on the wall.`\


;　恐怖を感じさせるピカソやゴヤの絵、それとは対照的に神々しい温かさを感じさせるダ・ヴィンチやフェルメールの絵……。\
` There were the works of Picaso and Goya that gave off a feeling of fright, and the contrastingly sublime and warm feeling works of Da Vinci amd Vermeer...`\

;　そのどれもが名画と呼ばれるに相応しい凄みや神聖さがあった。@でも、裕貴が一番好きなのはそのどれでもなかった。\
` Each of them was called a masterpiece, whether it was for their sacredness or their ghastliness. `@`But Yuuki's favorite painting was not one of them.`\
bg black,22

;「一番好きなのは、………この絵かな。」@
`"I think my favorite one... is this one..."`@
br
;　裕貴は一枚の絵画を指した。@少女が意外そうに目を開いたのがわかった。\
` Yuuki pointed to one of the paintings. `@`The girl's eyes opened wide in surprise.`\
bg kaiga_01,22

;　確かにインパクト、と言う点では他のものに比べて見劣りする、少しだけ地味な絵だ。@
` It was a somewhat plain painting. In terms of impact, it was hardly comparable to the others on this wall.`@
;　でも、裕貴にとっては一番印象的だったし、何より、純粋に他のどの絵よりも綺麗だと思った。\
` However, to Yuuki, this painting was the most impressive. He genuinely believed that it was prettier than any of the other paintings.`\

;　それは一人の少女の絵だった。@
` It was a painting of a girl.`@
;　短い鞭を持った英国風の美しい少女。@肩まである柔らかそうな髪。@鮮やかな青い色のスカート。@………………あれ。\
` She was a beautiful English looking girl, and was holding a short whip. `@`She had very soft looking hair that went down to her shoulders. `@`And she wore a bright blue skirt.`@`........ Wait.`\


ld r,NOD_D1,22

;「………なんだか、君、……この絵の子供によく似てるね。」@
`"....Hey, you... you look a lot like the kid in this painting."`@
;「………そう？」\
`".....Really?"`\


ld r,NOD_D3,80

;「うん。@髪とか、服とか…。@……ほら、そっくり。」@
`"Yeah. `@`You hair, your clothes...`@`... they're almost exactly the same."`@
me1v 16,50

br
;　改めて見ると、彼女は本当に似ていた。@まるで絵からそのまま抜け出して来たかのようだ。\
` Looking again, she really did bear a resemblence. `@`Almost as if she had crawled out of the very painting itself.`\

;「………自分じゃあんまり気に入ってないんだけど、ね。@この恰好。」@
`"....I don't really like it, honestly. `@`This appearance."`@
br
;　少女が苦笑しながら言う。@
` The girl replied with a bitter smile.`@
;　おかしなことを言う子だな。@……気に入らないんだったらわざわざそんな恰好しなきゃいいのに。\
` What a strange kid.`@`... If she didn't liked how she looked, then all she had to do was change it.`\



ld r,NOD_D2,80

;「でも……、僕は女の子らしくていいと思うけどな。」@
`"But.... I think you look good with a girly look like that."`@
br
;　嘘ではなかった。@学校に来るにしてはちょっと派手と言うか、@華美過ぎる気はしたけど、可愛らしい彼女の顔にはとてもよく似合っている気がした。\
` He wasn't lying. `@`He thought that it was perhaps a bit to flashy for school, `@`but he also felt like it suited the way her face looked perfectly.`\


;cl a,0
bg black,22

;　しかし、裕貴の言葉は、少女は明らかに不機嫌にしたようだった。@
` But, Yuuki's words had obviously displeased the girl.`@
;　露骨に顔をしかめ、大きな目を細めて裕貴を睨んできた。\
` She was obviously scowling. Her large eyes were now narrow and glaring at Yuuki.`\


bg bijutu_04,0
ld c,NOD_D5a,22
ld c,NOD_D4,80

;「…………え、あ……ごめん。」@
`".....oh, um... I'm sorry."`@
br
;　慌てて謝る。@………何かまずいこと言ったかな…？\
` He frantically apologized.`@`... Did he say something bad...?`\


ld c,NOD_D5a,80

;「えっと……、もし本当に気に入らないんだったら、服とか変えてみたらどうかな？@　それか、少し髪を切ってみるとか……。」\
`"Umm... if you really don't like how you look, why not try changing your clothes? `@`Or maybe cut your hair shorter..."`\

;　そう言ってから、また「しまった」と思った。@
` Once again, he immediately regreted opening his mouth.`@
;　もしかしたら彼女は厳しい家の子で、@着る服や髪型にいたるまで親に決められているのかもしれない。\
` It's possible that her parents may be strict, `@`and they won't let her choose her own clothes or hairstyle, or something like that.`\

;　だが、予想に反し、今度は少女は微笑んでくれた。@パッと花が咲いた様な可愛らしい笑顔だった。\
` But this time, unexpectedly, she smiled at him. `@`Like a a little flower opening up its petals, a cute smile spread across her face.`\

;「そっか……。@そうだよね。@たまには変えてみるのもいいかも、ね。@ふふふふふ……、そんなこと考えたことなかったな。」@
`"I see... `@`You're right. `@`It might be a nice to change things up every once in a while. `@`Fufufufu... I've never thought of it that way before."`@
br
;　やっぱりおかしなことを言う。@まさかいつも同じ服を着ているわけでもないだろうに。\
` She really does say some strange things. `@`There's no way that she would wear the exact same outfit every day.`\


bg black,22
;ld c,NOD_D1,80

;　それでも、少女が機嫌を直してくれたことに内心で、ホッと胸を撫で下ろす。@
` Still, he was relieved that she was in a good mood again.`@
;　だが、気持ちが落ち着いてくると、心に小さな焦りが生まれた。\
` But, once he calmed down, a slight impatience crept into his heart.`\
me2v 11,90

;bg black,22
bg bijutu_07,22

;　………どうやって彼女を美術室から追い出そう。@
` ...How was he going to get her to leave the art room?`@
br
;　この場に、このまま彼女に居続けられては困ったことになる。@
` If she sticks around this place for much longer, it'll become a problem.`@
;　裕貴には、この後この美術室でしなければならないことがあるのだ。\
` Because what Yuuki came to the art room to do, he needed to be alone for.`\
bg black,22
;bg Different_spiral_1b,22

;　いや、それを果たして自分が望んでいるのかどうか……、裕貴にはわからなかった。@
` No, actually, Yuuki still wasn't sure whether or not he wanted to do it.`@
;　どうしてこうやって毎日美術室に来てしまうのか。@
` Why was he coming to this room every single day?`@
;　この行き場のない気持ちから、助かるものなら助かりたいのか。@
` He feels like he has nowhere to go, but if someone could save him from that feeling, would he want to be saved?`@
br
;　……自分の感情のすべてが、淡い絵の具に塗り込められたように曖昧だった。\
` ...His own feelings felt unclear to him, as if they were covered over with layer of pale paint.`\
;　こんな、良く分からない気持ちや苦しみを抱えたままでも生きたいのか、@それともいっそのこと死んで楽になりたいのか。@
` Does he really want to keep living with the pain of having these vague feelings, `@`or would he rather just make it easy on himself and just die.`@
br
;　………いや、もしかしたら僕は……。\
` .....No, perhaps, I....`\
bg black,22

fedexx 0,50,0,0,0,0,2000
E_B
E_M2

bg bijutu_06,22

;　そんなことを考えていると、少女は裕貴から遠ざかる様に扉に向かって歩いていった。@
` As he was thinking about this, the girl turned and started walking towards the door, as if she was about to part ways with him.`@
br
;　もしかして、出て行ってほしい、という自分の気持ちが伝わったのだろうか……？@
` Maybe she picked up on the fact that he wanted her to leave...?`@
;　そんな都合のいいことを考えたが、もちろん言葉にもしないで気持ちなんて伝わるはずもない。\
` That what he had hoped, but of course, there's no way that she would have guess that without him telling her.`\



;　少女は入り口の近くにかけられた、一枚の絵の前でピタリと歩みを止めた。@
` The girl stooped directly in front of a picture hanging right next to the exit.`@
br
;　それは油彩画だった。\
` It was an oil painting.`\
bg black,22
bg kaiga_02,22

;　巨大な黒い胸像が、人間の形をした黒い影を押し潰している様子が描かれている。@
` The painting featured a dark silhouette in the shape of a human being crushed by a gigantic black bust.`@
;　絵の下には『つぶれた太陽』と題名が書かれた札が貼られている。\
` There was a small piece of paper placed beneath the paiting that titled the work "The Setting Sun."`\

;　この絵の作者は、かつてこの学校に通っていたらしく、@画家として有名になってから、母校であるこの学校に絵を寄贈したらしい。\
` Apparently the artist of this paiting had once gone to this school. `@`Later in life that person had become a famous artist and donated this painting to his old school.`\


;bg black,1
;mono 1
;ld c,NOD_D1,22

;　………作者の名前は何だったっけ。@
` ....What the name of that person again?`@
br
;　裕貴は、そのことを新谷先生に教えてもらった時のことを思い出した。\
` Yuuki remembered that Shintani-sensei had told him at one point.`\


;　男子生徒からすごく人気のある、綺麗で優しい美術の先生。@
` She was the kind and beautiful art teacher, who happened to be very popular with the boys.`@
;　その先生のことを思い浮かべるだけで胸が痛んだ。@切ないような苦しい様な胸の痛み。\
` Just thinking about that teacher caused a pain in his chest. `@`A heartrending and agonizing pain.`\

bg black,22
;ld c,NOD_D1,80

;　その時、不意に自分の望みが少しだけわかったような気がした。@
` At that moment, he suddenly felt like he understood a little better what his wish was.`@
br
;　もしかしたら僕は………。\
` Perhaps, if I could...`\


;bg black,2
;mono 0
;bg kaiga_02,0
;ld r,NOD_D1,22
bg kaiga_02,22


;「………ねぇ、野田裕貴くん。」@
`"....Hey, Yuuki Noda."`@
br
;　絵を見つめたまま、少女が呼びかける。\
` Still looking at the painting, the girl called his name.`\

ld r,NOD_D4,24
ld r,NOD_D5a,80


;　裕貴は違和感を覚えた。@自分は少女に名前を名乗っただろうか。@
` Yuuki felt like something was out of place. `@`Had he given the girl his name?`@
;　その違和感に付随するように、クラスメート達が噂していた怪談が思い出される。\
` On top of that unease, he remembered the ghost story his classmates had been talking about.`\
bg black,22
mono 1
bg bijutu_01,22

me2v 17,50

;　この学校で囁かれる八不思議の中の一つ。@
` Whispers about one of the eight mysteries of this school.`@
;　絵の中から抜け出した妖怪が、放課後に美術室を訪れた子供に問い掛けをする。@
` About the youkai that would crawl out of a painting after school in the art room, and ask a question.`@
;　その問い掛けに正しく答えられなかったものは、……祟られる。@
` If you couldn't answer that question correctly... then you would be cursed.`@
br
;　その妖怪の名前は……、“美術室のルノワール”。\
` The name of that youkai was... "Renoir of the Art Room."`\


;cl a,0
;bg black,1

bg black,22
mono 0
bg kaiga_02,22

me3v 5,50

;「………この絵の作者、誰だか知ってる？」@
`"....Do you know who made this painting?"`@
br
;　少女はぞっとするほど綺麗な顔で微笑んだ。\
` A smile crept across her beautiful face that made Yuuki shiver.`\
bg black,2

fedexx 0,100,100,100,0,0,2000

wait 1000

E_A

wait 1000


;「新谷先生、今日って何か予定ありますか？」\
`"Shintani-sensei, do you have any plans today?"`\
bg shokuin_03,0
ld c,NAF_D4,22
ld c,NAF_D1,80

me1v 24,50

;　新谷ナフミ（しんたに　なふみ）がトントン、と机の上で書類を整えていると、頭上に声が落ちて来た。\
` Nafumi Shintani (新谷ナフミ) was straightening out a stack of documents on her desk when a voice called out from above her.`\

;　新谷の席は、背中のすぐ後ろにコーヒーメーカーが置かれているため、@職員の大半がコーヒーを注ぎがてら、気軽に声をかけてくる。\
` Because the coffee maker was located directly behind her seat in the staff room, `@`so it was not uncommon for other staff to make small talk with her while pouring their coffee.`\

;　書類を引き出しにしまいながら振り返ると、井俣先生だった。@
` While putting the papers into a drawer, she turned her head around to see that it was Imata-sensei who was standing behind her.`@
;　年齢が近いこともあって、彼とは気軽に話せる仲だ。@飲みにでも誘ってくる気かな、と思ったら案の定誘って来た。\
` The two of them were close in age, so they would often make small talk. `@`Just as she was wondering if he was going to invite her out for drinks like usual, he did just that.`\

;「良かったらこの後飲みにでも行きませんか？@　駅前に良い雰囲気のお店、見つけたんですよ。」@
`"Would you like to go out for drinks after this? `@`I found a pretty nice place right by the train station."`@
br
;　新谷はすまなそうに顔を歪ませて、その前で手を合わせる。\
` Shintani made an apologetic face and replied.`\

ld c,NAF_D3,80

;「ごめんなさい、今日はこれから美術室で作業があるんですよねー。」\
`"I'm sorry, when I'm done here I've got some work to do in the art room today."`\


;　井俣先生の誘いをかわすのはこれで何度目だろう。@
` Imata-sensei had invited her out many times before.`@
;　毎回理由を付けて断ることに少しだけ罪悪感を感じるが、@懲りずに誘ってくる井俣先生もどうかと思う。\
` She was beginning to feel a little guilty always giving an excuse and turning him down, `@`but she was also wondering what he was thinking asking her out so often even though she was turning him down.`\


;cl a,0
;bg black,2
bg black,22
bg shokuin_04,22

;　今年で３３歳の彼は、別に恰好悪いわけではない。@清潔感があって保護者からの評判も良かった。@
` He turned 33 this year, and it wasn't exactly that he was uncool. `@`He had a good sense of cleanliness, and was popular among parents and other guardians.`@
br
;　生徒達に「熱血先生」と揶揄されるだけあって、@新谷から見ても単純な人だなぁとは思うけど、裏表のないさっぱりした性格は好感が持てた。\
` The students always tease him by calling him Hot-blooded-sensei. `@`Shintani sees him as a relatively plain person, but in truth, his refreshingly simple and honest personality held some appeal.`\

;　しかし申し訳ないが、新谷は年上の男には余り興味がないのだ。@
` But unfortunately, Shintani was not interested in older men.`@
;　子供の頃から好きになるのはみんな自分より年下の子たちばかりだった。@それは、四捨五入をすれば３０歳にもなる今に至っても全然変わっていない。@
` Since she was a kid, the only people she was ever attracted to were younger than herself. `@`Even now, at nearly the age of 30, that has not changed.`@
br
;　井俣先生は露骨に残念そうな顔をする。\
` Imata-sensei made an obviously disappointed face.`\

bg black,23
bg shokuin_02,0
;ld r,NAF_D1,22
;ld r,NAF_D1,23

;「そっかあ……。@良かったらその作業、僕も手伝いましょうか？　@……あ、いや、別にそんな、下心とかそういうのがあるわけじゃなくて！」\
`"I see... `@`Would you like me to help you out with that work?`@`... Ah, I mean, I'm not saying that because of have ulterior motive or anything!"`\

;　彼が顔を真っ赤にしてそんなことを付け加えるので、私は思わず苦笑してしまった。@
` As he tried to explain himself, his face got all red. Without thinking, my face formed into a wry smile.`@
br
;　本当に単純で分かり易い人だ。@これで下心がないんだとしたら、それはそれですごい。\
` He really was a plain and easy-to-read person. `@`If he really didn't have any ulterior motives, then that was quite the reaction.`\
ld r,NAF_D2,22

;「ふふふふふふ、大丈夫ですよ。@手伝ってもらうほどの量でもないんで。」@
`"Fufufufufu, it's fine. `@`It's really not that much work."`@
br
;　言いながら自分でも下手な言い訳だな、と思った。\
` As she spoke, she realized what a poor excuse she had given.`\

;　そんなに量がないんなら、さっさと終わらせて一緒に飲みにいけばいいじゃないか、と返されるかもしれない。@
` If it really didn't have that much work to do, then there's no reason that she couldn't get it done and go drinking with him, and she expected him to pick out that flaw.`@
;　だが、井俣が返して来た言葉は、それとは別の角度からのものだった。\
` But Imata's response wasn't what she had expected.`\

;「そうですかぁ。@……でもほら、あんな事故の後だし、一人で美術室にいるのは怖いんじゃないですか……？」\
`"Ah, Okay.`@`... but, aren't you afraid to go into the art room alone after that incident...?"`\


ld r,NAF_D4a,80

;　笑っていた新谷の顔が強張った。@
` Shintani strained to maintain her smile.`@
br
;　『あんな事故』、@……その言葉に一人の生徒の顔が鮮明に蘇る。@
` 'that incident'`@`... Those words alone made her vividly recall one student's face.`@
;　井俣先生がしまった、という顔を浮かべて謝った。\
` Imata-sensei's face immediately turned to an expression of regret and he apologized.`\

;「あ、ごめんなさい！@　無神経なことを言ってしまって。」@
`"Ah, I'm sorry! `@`I said something I shouldn't have."`@
ld r,NAF_D2,80

;「いえ……。@……大丈夫です。」@
`"No....`@`... It's fine."`@
br
;　かろうじて平静を取り戻して言うと、井俣先生がわざとらしく明るい声を出した。\
` She was just barely able to reply calmly. Imata-sensei replied with a force cheer in his voice.`\

;「……あんなの、ただの噂ですよね、噂。」@
`"...That was just a rumor, right? A rumor."`@
br
;　噂。@……生徒たちの話題は今、その“噂”で持ち切りだ。\
` A rumor.`@`... Right now, that 'rumor' was the hot topic among the students.`\

;cl a,0
bg black,22

fede 0,1000
E_A

bg shokuin_04,22

bgm1 8
;「“美術室のルノワール”……ですか？」@
`"You mean 'Renoir of the Art Room'?"`@
;「……くだらないですよね。@子供ってなんでああいう噂が好きなんでしょう。@……自分たちの友達が亡くなったって言うのに……。」\
`"...How silly. `@`Why do kids even like rumors like that?`@`... Even though one have their friends has passed away..."`\
;「……だからじゃないですか？」@
`"...Isn't it because of that reason?"`@
;「え？」@
`"Huh?"`@
;「友達が一人死ぬって、すごく大変なことだと思うんですよ。@子供が受け入れるには重過ぎるくらい。@……だから、妖怪とか、@そういう自分たちの知らない不思議な存在のせいって考えたくなるんじゃないですかね。」\
`"Having one of your friends die is a very serious thing to go through. `@`Maybe too serious for children to accept.`@`... So, it might be easier... `@`for them to place the blame on youkai or something else enigmatic like that."`\

;「……もしかして、新谷先生も信じてるんですか？」@
`"...Shintani-sensei, could it be that you also believe in that stuff?"`@
;「いえ。@……でも、信じたくなる時はありますよ。@私がもっとちゃんと気を配っていたら、あんなことにはならなかったんじゃないかって。@……そう思って落ち込んじゃう時もありますから。」\
`"No.`@`... But sometimes I want to. `@`Sometimes, when I'm feeling down I start to think... `@`If only I had paid better attention, maybe I could have prevented that from happening."`\
bg black,22

;「そんな！@　……あれは事故です！@　絶対に先生のせいなんかじゃありませんよ！」@
`"Don't think like that!`@`... That was just an accident! `@`There's no way at all that you were at fault!"`@
;「ありがとうございます。」\
`"Thank you."`\
bg shokuin_03,22
ld c,NAF_D4,26
;ld c,NAF_D3,80

;　無理矢理笑顔を作ると、新谷は立ち上がった。\
` Shintani forced herself to smile and stood up.`\
ld c,NAF_D2,80

;「……それじゃあ、私行きますね。@お疲れさまでした、井俣先生。」@
`"...Well then, I'll be going now. `@`Goodbye, Imata-sensei."`@
br

cl a,23

;　まだ何か言いたそうな井俣先生に背を向け、足早に職員室から出た。\
` Imata-sensei looked like he had something else to say, but she pretended not to notice and quickly turned and left the staff room.`\
se1 82
bg black,24
bg rouka_02,24
;bg rouka_02,22
;ld r,NAF_D1,24
ld r,NAF_D4a,22
;wait 1000

;cl r,25
;se1v 7,30
;quakey 1,100

;　後ろ手で扉をピシャリと閉めて、深い溜め息を吐き、思わずその場にしゃがみこむ。@
` She shut the door behind her and let out a deep sigh, involuntarily dropping into a crouch.`@
;　膝が床にあたり、ガツッと鈍い音を立てる。@少しだけ遅れて痛みがやってきた。\
` Her knees struck the floor and made a dull thud. `@`A short moment later a slight pain spread through her legs.`\
me1v 5,50

;　あれから数週間も経つのに、未だにあの日のことを思い出すと、心がひどく痛む。@
` It's been a few weeks since that incident, but the thought of it still brings a pain to her heart.`@
;　閉じかけた傷を指で無理矢理、開かれるかの様な暴力的な痛み。@
` It was a violent pain, like having a healing wound reopned by someone digging their fingers into it.`@
br
;　再び一人の男の子の顔が思い出される。\
` Once again, she remembered the face of that boy.`\

bg black,22
;bg black,0
mono 1
bg different_spiral_1a,0
ld c,NOD_D3,22

;　死んでしまった男子生徒。@容赦のない息苦しさに胸が圧迫された。@
` The face of that boy who had died. `@`Her chest mercilessly and suffocatingly seized up her chest.`@
br
;　……誰に言うでもなく、新谷は呟く。\
` ...Shintani muttered to herself, too quiet for anyone else to hear.`\

;「裕貴くん……。@……どうしてあんなことに…………。」\
`"Yuuki...`@`...Why? Why did that have to happen to you..."`\
cl c,2

bg black,22

fede 10,1000
E_MA

bg bijutu_01,22

;　野田裕貴が亡くなったのは先月のことだった。@
` Yuuki Noda passed away last month.`@
br
;　放課後、校内を見回っていた教師が、美術室で、石膏像の下敷きになっている彼の遺体を発見したのだ。\
` A teacher patrolling the building after school found him crushed underneath a plaster bust in the art room.`\

bg black,22
;bg black,1
bg bijutu_04,22

;　石膏像はギリシャ彫刻を複製して作られたかなり大きなもので、デッサンの練習用にと置かれているものだった。\
` It was a rather large bust, and was a reproduction of a Greek sculpture that was used in class to practice sketching.`\

;　野田裕貴はそれで後頭部を強く打った。@直接の死因はそれによる失血らしいが、ほとんど即死だったろうという話だ。\
` It hit Yuuki Noda on the back of his head. `@`Officially, the cause of death was extensive blood loss, but he probably died instantaneously.\


bg black,22
mono 0

;　恐らくだが、放課後、美術室に来た野田裕貴は、躓くか何かして机の下に倒れ込んだ。@
` Most likely, Yuuki Noda went to the art room after school and somehow tripped and fell under the desk supporting the bust.`@
br
;　その時、彼の身体が机の支柱に当たってしまい、@上に置かれていた石膏像がバランスを崩し、裕貴の上に覆い被さるように倒れてきた……。\
` At that point, he bumped the legs of desk, `@`and the bust resting on top of it lost its balance and came toppling onto Yuuki...`\
bg blood_1b,4
;wait 1000

bg black,42
mono 1
bg bijutu_03,22

;　……状況から考えて、大方そんなところだろう。@彼の死は不幸な事故と判断された。@
` ...That is nearly everything that is known regarding the circumstances of the incident. `@`It was judged that his death was just an unfortunate accident.`@
br
;　しかし、その一方で、生徒たちの間でこんな噂が囁かれていた……。\
` But in the meantime, a rumor has been spreading among the students...`\

bg black,2
;mono 0
;bg e010,22
;locate 0,5

E_A

br
;　野田裕貴は、“美術室のルノワール”の祟りにあって死んでしまったのではないか……？\
` A rumor that Yuuki Noda was cursed to his death by 'Renoir of the Art Room'...`\
bgm1 9

bg kaiga_02,22

;　“美術室のルノワール”と言うのはこの学校に伝わる八不思議の一つだ。@
` 'Renoir of the Art Room' is one of the eight mysteries handed down from year to year in this school.`@
;　普通、学校の怪談と言えば、七不思議が定番だが、@この学校ではいつの間にかそれよりも一つ多い八不思議になっていた。@
` As far as school ghost stories go, normally there would only be seven mysteries, `@`but at some point this school gained an eighth mystery.`@
br
;　まあ、これくらい大きなマンモス校なら、一つや二つ多くてもおかしくはないのかもしれないが……。\
` Well, it's not too odd for a mammoth school like this one to gain one or two more...`\
;bg black,22
;bg black,0
;mono 2
;bg different_spiral_1a,22


;　それはこんな怪談だ。@
` This is the story.`@
br
;　放課後、一人で美術室にいると、“ルノワール”という子供の妖怪が現れ、いくつかの問い掛けをしてくる。@
` If you go into the art room alone after school, a young youkai named 'Renoir' will appear before you and ask you a few questions.`@
;　その問いには正しく答えなければならない。@もしも嘘をついたり、間違えたりすると、ルノワールの恐ろしい祟りにあう……。\
` You must answer those questions correctly. `@`If you lie, or answer incorrectly, Renoir will force upon you a terrible curse...`\
bg black,22
;mono 0
bg rouka_04,22

;　野田裕貴が死んだのはその祟りのせいではないか……？@
` Was that curse to blame for Yuuki Noda's death...?`@
;　彼は、ルノワールの問い掛けに間違って答えたために殺されたのではないか……？@
` Was he killed because he answered Renoir's questions incorrectly...?`@
br
;　今、学校はそんな噂で持ち切りだった。\
` That is the rumor that was being spread around the school right now.`\

bg black,2
mono 0
bg rouka_02,22
;bg black,1
;mono 0
;bg rouka_01,0
ld r,NAF_D4a,22


;　だが、新谷はそんな噂は一切信じていなかった。@
` But Shintani doesn't believe that rumor in the slightest.`@
br
;　彼が死んだのは、怪談のせいなんかじゃない。@“ルノワール”なんてふざけた名前の妖怪のせいじゃ、絶対にない……。\
` His death wasn't because of some ghost story. `@`He didn't die because of some silly youkai named Renoir. She was sure of that...`\


;ld r,NAF_D1,80

;　しかし、どんな原因だったにせよ、彼が死んだ事実に変わりはなかった。@
` But, no matter where the blame is place, that doesn't changed the reality that he is dead.`@
;　裕貴くんはもうこの世にいない。@彼にはもう二度と会えない。@
` Yuuki is no longer in this world. `@`She will never see him again.`@
br
;　目を瞑ると、瞼の裏側に彼の姿が浮かび上がった。\
` When she closes her eyes, she can still see the way he looked on the inside of her eyelids.`\

;cl a,0
bg black,22
ld c,NOD_D3,22

;『……僕、新谷先生のファンだったんです。@』
`"...I'm your biggest fan, Shintani-sensei."`@
br
;　俯きながら、照れ臭そうに微笑んでいた彼の顔。@
` His smiling face, looking down at his feet bashfully.`@
;　あの笑顔を、こうやってすぐに思い出すことが出来る。@でも実際に見ることはもう二度と出来ない。\
` She could so easily remember his smiling face. `@`But never again could she see it with her own eyes.`\
bg black,22

fede 0,1000
E_A

bg rouka_02,22

me1v 5,50

;　書きかけの、あの絵を完成させることも永遠に叶わないのだ……。@
` Nor could she ever complete her painting she had been working on...`@
;　……それを思うと、再び深い溜め息が込み上げてきた。@
` ...When she realized that, she let out another deep sigh.`@
br
;　吐き出された溜め息は身体の線をなぞるように足元に下りると、澱の様に重く重く垂れ込めた。\
` The sigh spread throughout her body, descending down to her feet and hanging heavily there like sediment in a glass.`\

;　そのままジッとしてると、その澱みに足をとられて一歩も動けなくなりそうだった。@
` If she remained motionless she was afraid that she would be unable to get up and move another step.`@ 
br
;　グッと身体に力を入れて、澱みに飲み込まれる前に、無理矢理立ち上がる。\
` She used all of her strength to force herself to stand before that could happen.`\

ld c,NAF_D4a,6
;ld r,NAF_D1,26

;　……ふと膝を見ると血が滲んでいた。@
` ...When she looked down, she saw that her legs were stained with blood.`@
br
;　擦り剥いてしまったみたいだ。\
` She must have skinned her knees.`\

ld c,NAF_D2,80
;ld r,NAF_D1,80

;　傷を指でそっとなぞる。@そこから漂う鉄のような匂いが微かに鼻孔をかすめた。@
` She gently reached down and traced the cuts with her fingers. `@`A faint iron-like smell drifted up to her nose.`@
br
;　……保健室に行って絆創膏でも貰おうか。@
` Should she go to the infirmary and get a bandage?`@
;　新谷は指についた血をハンカチで拭うと、まだ脳裏をちらつく野田裕貴の残像を振り切る様に歩き出した。\
` Shintani wiped the blood from her fingers on a handkerchief and began walking, trying to get the image of Yuuki Noda to leave her mind.`\
bg black,2
bg gakkou_01u,22
wait 2000
bg black,22
bg Air_01,22
wait 2000
bg black,22

fede 0,1000
E_A

bg kaidan_01,2

wait 1000
ld r,NAF_D1,22

bgm1 8

;「また長居しちゃったな……。@早く作業終わらせないと、本当に夜になっちゃいそう。」\
`"I've stayed after too long again... `@`I need to hurry up and finish my work or it really will get dark."`\

;　４階までの階段を上がりながら、新谷は時計を気にした。@
` Shintani glanced at the time on her way up the stairs to the 4th floor.`@
;　保健の先生も、井俣先生と同様に新谷と歳が近いので、たまに保健室に行くとついつい話し込んでしまう。\
` The school nurse was also close in age to her and Imata-sensei, so every once in a while Shintani would end up going to the infirmary to talk to her.`\

;　少し天然なところがあるが、さっぱりした性格の彼女は話し易くて好きだ。@
` She was nice. Maybe a little ditzy somtimes, but Shintani still enjoyed talking with her.`@
;　絆創膏をもらうだけのつもりだったのに、お茶までご馳走になってしまった。\
` She had intended to just get a bandage and get back to work, but she ended up staying for tea too.`\


ld r,NAF_D2,80

;「今度は、美術室にも招待しようかしら。@……私もお茶を淹れるのは得意だし。」\
`"I wonder if I should invite her to the art room for tea this time.`@`... I'm pretty good at making tea myself."`\
bg black,24
;cl a,0
bg rouka_04,24

;　新谷は、紅茶を淹れる道具を美術室の机の中に隠している。@
` Shintani hid the things necessary for brewing black tea within her desk in the art room.`@
;　教頭が趣味のいい紅茶道具を職員室に持ち込んでいるので、@ならば遠慮はいらないとばかりに、自分もこっそり紅茶の道具を学校に持ち込んだのだ。\
` The vice-principal brought his own set of black tea making supplies to the staff room a while back. `@`So she decided to do the same and snuck her own set into school.`\

;　豊富な種類の茶葉の缶を用意しており、@その日の気分に合わせて、様々なブレンドを楽しむことが出来る。\
` She kept plenty of different tea leaves in a can, `@`so that she could enjoy any number of different blends depending on how she felt on a given day.`\
bg black,22


;　今日の作業を始める前にカモミールティーでも淹れよう。@
` Before starting her work today, she decided to make some chamomile tea.`@
;　あれは気分がリラックスして心が和らぐ。@
` That should help her calm down and relax.`@
br
;　そんなことを考えながら、美術室の扉を開ける。\
` She opened the door to the art room as she continued to consider what type of tea to brew.`\
se1 82
bg bijutu_06,23

fede 0,1000
E_A

;　………すると、不意に違和感を感じた。@
` ....But as she did, something suddenly felt out of place.`@
me1v 16,50
;　教室の中に誰かがいるような気配がしたのだ。\
` She felt like there was someone inside the room.`\


ld r,NAF_D4,24

;「………………………………。」@
`"............."`@
br
;　室内をぐるりと見回すが、飾られた彫刻やオブジェが薄暗い影を作っていて、すぐには中の様子が判断できない。\
` She tried to survey the inside of the room, but the various sculptures and artworks cast dim shadows over everything, and she couldn't properly assess if there was someone or not.`\


ld r,NAF_D4a,80

;「……誰かいるの？」@
`"...Is anyone in here?"`@
br
;　指をスイッチに伸ばして電気を付ける。\
` She flipped the light switch and the lights came on.`\
bg white,1
bg black,22
bg bijutu_07,2

fede 0,1000
E_A

;　……すると、視界の隅に一人の小柄な少年の姿が飛び込んで来た。\
` ...Then, out of the corner of her eye, she saw a petite, young boy.`\

;「………！」@
`".....!"`@
bgm1 29

br
;　新谷は一瞬、呼吸をするのを忘れて彼に見入ってしまった。@
` Upon seeing him, for a moment Shintani forgot to breathe.`@
;　その少年がハッとするほど美しかったからだ。\
` For the boy was startlingly beautiful.`\

;　愛くるしい子犬や子猫を連想させるような大きな瞳。@
` He had large eyes like that of a cute little kitty or puppy.`@
;　透き通るほどに白い肌。\
` And skin so white it seemed almost transparent.`\


;　栗色の髪は染めたような不自然さが全然なく、@白過ぎる蛍光灯の明かりに反射して星をまぶしたかのように輝いていた。\
` His chestnut-colored hair looked too natural to have been dyed, `@`and with the bright fluorescent light refelcting off of it, it shone like it was covered in stars.`\



;「………あ、すいません、先生。@勝手に入ったりして。」@
`"....Ah, sorry for startling you sensei. `@`I came into the room without asking."`@
;■ルノワールはしばらく立ち絵不要
br
;　変声期前の高い声だった。@繊細な楽器の様な響きは彼の容姿にとても似合っていた。\
` His voice was high pitched. Not yet changed by puberty. `@`Its delicate musical instrument-like quality fit his appearance perfectly.`\


bg black,22

;　……うちの学校にこんな綺麗な少年、いたかしら？@
` ...Has there really been such a pretty young boy going to our school?`@
;　いくら生徒の数が多いって言っても、こんなに目立つ子に気付かないはずないのに……。@
` There are a lot of students that go here, but she doubted that such a conspicuous kid would go unnoticed by her for this long...`@
br
;　……もしかして転校生なのかしら…？\
` ....Maybe he was a transfer student...?`\
bg bijutu_03,0
ld c,NAF_D4a,22

;　そんな考えを巡らしていると、少年は怒られるとでも思ったのか、申し訳なさそうな表情を浮かべて、上目遣いに新谷を見てきた。@
` While she was mulling this over in her head, the young boy was expecting to be scolded, and thus was looking up at her with an apologetic expression and puppy dog eyes.`@
;　怯えた小動物の様なその仕草に、新谷は再び息を呑む。\
` Seeing the boy acting like a small animal once again took away Shintani's breath.`\
ld c,NAF_D2,80

;「……いいのよ別に。@美術室に、何か用かしら？」@
`"...Don't worry about it. `@`Is there something you need in the art room?"`@
br
;　動揺を隠し、少年を安心させるように笑顔を向けた。\ 
` Hiding how shaken she was, she smiled at the boy hoping to calm him down.`\


;「えっと、その……。」@
`"Umm, well..."`@
ld c,NAF_D1,80

;「もしかして……、美術部の入部希望者？@　残念だけど今、美術部は休部中なの。@ほら、あんな事故があったばかりだから……。」\ 
`"Could it be... that you want to join the art club? `@`Unfortunately, the art club isn't active right now. `@`Since that accident just happened so recently..."`\


;「あ、違うんです！@　……僕、その……絵が見たくなって。@この絵、好きなんです、僕。」@
`"Ah, no. It's not that!`@`... I just... wanted to see this painting. `@`I really like this one"`@
br
;　少年ははにかみながら壁を見た。\
` The boy shyly looked over at the wall.`\
bg black,23
;cl a,0
bg kaiga_01,23

;　この美術室の壁にはピカソやフェルメール、レオナルド・ダ・ヴィンチなど無数の有名な絵がかけられている。@
` The walls in the art room were covered with famous works by artists like Picasso, Vermeer and Leonardo da Vinci.`@
br
;　もちろん本物ではなく、画集などからカラーコピーしただけのものだったが、@装飾の入った高価そうな額に入れられているため、それなりに見栄えはする。\
` Naturally, they weren't the originals, just color copies made from a book of prints, `@`but by putting them in decorate picture frames, they managed to look rather impressive.`\

;　彼が見ていたのはエッシャーの絵だった。@
` The one that the boy was looking at was a work by M.C. Escher.`@
br
;　階段の一番上の段が別の階段の一番下の段になって循環し、@無限に階段を上り下り続ける人々が描かれている。\
` It was a drawing of a never-ending staircase in which the top step of one staircase became the bottom step of another. `@`On this staircase were a group of people, endlessly ascending and descending.`\

;　いわゆる不可能図形と言われる「ペンローズの三角形」や、@「悪魔のフォーク」などの応用で描かれた、目の錯覚を利用した有名な騙し絵だ。\
` It's a print that puts the so-called concept of impossible objects like the 'Penrose Triangle' `@`and 'Devil's Fork' to use, and is a famous optical illusion.`\
ld r,NAF_D4,22
ld r,NAF_D1,80

;「これ私も好きよ。@面白いわよね、騙し絵って。」@
`"It like this one too. `@`Isn't it cool? It fools your eyes."`@
br
;　新谷の笑顔を見て、少年の白い頬がみるみるうちに紅潮し、薄いピンク色に染まる。@まるで小さな桜が咲いたようだった。\
` The boy looked at her smiling face and blushed, his cheeks turning a shade of light pink. `@`Almost as if a little cherry tree in full bloom.`\

;　その可愛らしい反応を見て、新谷は心がざわつくのを感じた。@
` Seeing this reaction from him made Shintani's heart flutter.`@
br
;　……もしかしたらこの子なら……。\
` ...Maybe, with this kid....`\

bg black,23
bg bijutu_06,23

;　チラリと窓の外を見ると、既に陽は傾きかけていた。@
` Glancing out the window, she saw that the sun was already setting.`@
;　生徒たちはとっくに帰る時刻だ。@それにあの事故が起きてからは授業以外で美術室に来る人間は滅多にいない。\
` The students have long since gone home. `@`Furthermore, ever since the accident people seldom come to the art room for any reason other than class.`\
bg black,22
bg bijutu_02,22
;ld c,NAF_D5,22

;　新谷は少年の肩に手を、……そっと置く。@
` Shintani gently laid a hand... on the boy's shoulder.`@
;　華奢なその肩が、緊張したようにビクリと揺れた。\
` As she touched that slender shoulder, he gave a slightly startled jump.`\
ld c,NAF_D2,22

;「……ねぇ君、この後って時間ある？」@
`"...Hey, can you spare some time?"`@
;「……え……？」\
`"...Huh....?`\


ld c,NAF_D1,80

;「………良かったら、私の絵のモデルをやってくれないかしら？」\
`"....I was wondering if you might be a model for the picture I'm drawing."`\

;　突然の申し出に、少年は驚いたように大きな目をさらに見開いた。@
` Seemingly surprised by her sudden request, the boy's eyes opened up very wide.`@
;　……もしかしたらこの子なら、私の絵を完成させてくれるかもしれない。\
` ...Maybe, with this kid I'll be able to finish my drawing.`\


ld c,NAF_D3,80

;「ちょうど、君みたいな男の子をモデルにした絵を描きたいと思っていたの。@……お願いできないかしら？」@
`"I've been wanting to do draw a picture with a boy like you as a model.`@`... Would you mind helping me out?"`@
br
;　胸の前で両手を合わせる。\
` She brought her hands together in front of her chest.`\
; ^^^ Note To Editor: Japanese body language for 'please'. Should this line be left out?

;　彼は目を何度か瞬かせると、足元に視線を落としながら小さな声で言った。\
` He blinked a several times before dropping his eyes towards his feet and answering in a small voice.`\
bg black,22

;「……本当に、僕なんかがモデルでいいんですか？」@
`"...Is it really okay for me to be a model?"`@
;ld c,NAF_D2,80

;「ええ。@君さえ良ければだけど。@…………嫌かな？」\
`"Yes. `@`All I need to complete it is you.`@`..... Do you not want to?"`\

;「いえ！@　……光栄です。@だって僕………。」@
`"No, that's not it!`@`... It would be a privilege. `@`Because I'm...."`@
br
;　俯いたままの少年は照れ臭そうに微笑み、数ヶ月前、野田裕貴が言ったのと全く同じ台詞を口にした。\
` And then, while looking down at his feet with a embarrassed smile, from his mouth came the exact same words that Yuuki Noda had said a few months before.`\
bg bijutu_06,22

;「…………僕、新谷先生のファンだったんです。」\
`".....I'm your biggest fan, Shintani-sensei."`\
bg black,2
fede 0,2000
E_A

wait 1000

bg bijutu_03,22
;ld r,NAF_D1,22

bgm1 8

;　美術室の中に、鉛筆でスケッチブックを擦るシャッシャッという音だけが響いていた。\
` Inside the art room only the sound of a pencil writing on a sketchbook page could be heard.`\

;　まだ部活動をしている子もいる時間だが、この美術室は校庭側に面していないため、子供達の声はほとんど聞こえてこない。@
` There were still kids participating in after school clubs, but because the art room doesn't face the schoolyard, their voices could barely be heard.`@
;　時折、階段を下りる足音だけが小さく響いてくるくらいだ。\
` And every once in a while the faint sound of someone walking down the stairs could be heard.`\

ld r,NAF_D4,22
;ld c,NAF_D1,80

;「……そんなに緊張しないでいいのよ？@　自然な表情が描きたいだけだから。」\
`"...No need to be so tense, okay? `@`I want to make sure and capture your natural facial expression."`\

;　気持ちをほぐそうと、モデル用の椅子に座った少年に笑いかける。@
` She smiled at the young boy modeling on the chair, hoping it would ease him up a bit.`@
;　少年は口元で少しだけ微笑んだが、その表情は硬いままだった。@
` He did have a small smile on his lips, but his expression seemed stiff.`@
;　肩や背中には力が入り、傍目にも緊張しているのが分かる。\
` His shoulders and back were also tense from the nerviousness of being watched by another.`\

;「ごめんなさい、なんか、こういうの慣れてなくて………。」@
`"I'm sorry, I'm not really used to doing this, so...."`@
ld r,NAF_D2,80
;ld c,NAF_D1,80

;「無理もないわよ。@モデルをやるのなんて初めてでしょ？」@
`"Don't worry. `@`It's your first time being a model, right?"`@

;「あ、いえ……。@その、一度だけやったことはあるんですけど、随分前のことなんで………。」@
`"Ah, no... `@`Actually, I've done it once before, but that was a long time ago..."`@
br
;　意外な答えに思わず、へぇと声が出た。\
` Finding his answer rather unexpected, she couldn't help but let out an impressed 'oh?'.`\

ld r,NAF_D1,80
;ld c,NAF_D1,80

;「それって絵のモデル？@　それとも写真か何か？」@
`"Did you model for a painting? `@`Or was it for a photograph?"`@
br
;　少年は困った様な顔を浮かべた。@なんと答えるべきか迷っているようだった。@
` The boy made a troubled face. `@`As if he wasn't quite sure how to answer.`@
;　その表情を見て、新谷にある想像が浮かんだ。\
` Seeing that expression made Shintani's imagination wander.`\


;cl a,0
bg black,22
bg kaiga_01,22

;ld r,NAF_D4,80

;　そう言えばこの学校は生徒の芸能活動を禁じている。@
` Come to think of it, this school prohibits its students from working as models or actors outside of school.`@
;　もしかしたら学校には内緒で、何かタレント的な活動をしたことがあるのかもしれない。\
` Maybe this boy had done some talent related work or something and had been keeping it a secret from the school.`\
;ld r,NAF_D1,80

;　何しろ、……これだけきれいな顔立ちだ。@
` At any rate... he certainly had the looks for it.`@
;　芸能事務所にスカウトされてもおかしくないし、@そこまでとはいかなくても、街角で声をかけられてモデルか何かのような形で雑誌に掲載されたことがあるのかもしれない。\
` It wouldn't be odd for a talent agency to scout him out. `@`Maybe it wasn't even that much. It could have been that he did voice work, promoting a store on street corners or modeled for a magazine.`\
;ld r,NAF_D2,80

bg black,22

;　……ふふふふふ。@あの小うるさい教頭じゃあるまいし、そんなの隠さなくても別に怒ったりしないのに。@
` ...Fufufufufu. `@`But she's not as fussy as the vice-principal, if this boy did do something like that and hide it, it's not like she'd be angry at him.`@
br
;　新谷がそれ以上問いつめずに絵に向き直ると、少年は心からホッとしたようだった。\
` When Shintani decided to drop the question and continue her drawing the boy looked relieved.`\

bg bijutu_04,22

;「あの……。@この絵って、コンクールか何かに出品したりとかしないですよね……？」\
`"Um.... `@`Umm, you're not going to enter this drawing in a contest or anything like that, right...?"`\
ld c,NAF_D4,22
ld c,NAF_D2,80

;「特にどこかに出したり、展示したりするつもりはないわよ。@あくまで私の趣味で描かせてもらうだけだから。」\
`"No, I don't especially intend to exhibit it or anything. `@`I just want to be able to keep pursuing my hobby."`\

;　昔は画家を目指したこともあったが、教師になった時にすっぱり諦めた。@
` In the past she had wanted to be an artist, but gave up on that when she became a teacher.`@
;　今でも絵は好きだが、それでどうこうなろうとは思っていない。\
` She still likes art, but she's accepted how things are.`\

;　言葉通り、これは単なる私の“趣味”だ。@
` It's nothing more than my 'hobby'.`@
;　飾るのはもちろん、誰にも見せるつもりなんてない……。\
` Naturally, she doesn't intend to show anyone this drawing of hers...`\

;「……良かった。@僕、目立ったりするの苦手なんで……。」@
`"...That's a relief. `@`I don't really like to stand out too much..."`@
br
;　そう言って少年は曖昧に目を伏せた。\
` He said while vaguely lowering his eyes.`\
;　もしかしたら芸能活動を咎められるのが怖かったんじゃなくて、@単に恥ずかしかったのかもしれない。@
` Maybe he wasn't worried about getting scolded for working outside of school at all. `@`Maybe he is just shy.`@
br
;　子供らしいその感覚を、新谷は微笑ましく思った。\
` Shintani found that sort of childish reaction charming.`\
ld c,NAF_D1,80

;「そうなんだ。@……でも、君くらい可愛かったら、嫌でも目立っちゃうんじゃない？@　クラスの女の子たちが放っておかないでしょ？」\
`"Really?`@`... But, with how cute you are don't get a lot of attention anyway? `@`I bet the girls in your class won't leave you alone."`\

;「そんなことないですよ。@男のくせに女みたいだって、いつも馬鹿にされてますから。」@
`"Not really. `@`Even though I'm a boy, I look like a girl, so I get made fun of a lot."`@
br
;　確かに。@少年の顔は下手な女の子よりもよっぽど可愛い。@
` That would make sense. `@`This boy's face is cuter than most girls out there.`@
;　女物の服でも着せて、ウィッグでも被せれば、男だと疑う者はまずいないだろう。\
` If he was wearing girl's clothes and a wig then very few people would even suspect him of being a male.`\

cl l,0
ld c,NAF_D2,23
;ld r,NAF_D1,80

;「ふふふふふふ、みんな見る目がないのね。@私は好きだけどな、君の顔。」@
`"Fufufufufu, none of them know true good looks. `@`I, on the other hand, like how your face looks"`@
br
;　少年が口を閉じた。@その頬がみるみる赤くなる。@
` The boy's mouth shut. `@`His cheeks turned red before her eyes.`@
;　そんな可愛らしい反応に気付かない振りをして、新谷は鉛筆を走らせる。\
` She pretended not to notice his cute reaction and kept moving her pencil.`\

;cl a,0
;bg bijutu_07,26
bg black,22
bg bijutu_07,22

;　新谷は、自分が男子生徒達から人気があることを知っていた。@
` Shintani knew that she was popular among the male students.`@
;　このくらいの年齢の子供にとって、優しくて綺麗な先生という存在はとても大きい。@
` To children of this age, having a teacher as kind and pretty as her is a big deal.`@
;　ひと月に１回はラブレターをもらうし、@新谷と親しくなりたいがために美術部に入部しようとする生徒も少なくなかった。\
` In one month she'll receive at least one love letter, `@`and there were numerous cases of students entering the art club in hopes of getting closer to her.`\

;　恥ずかしそうに新谷から視線を逸らしていた少年が、不意に口を開いた。\
` The embarrassed looking boy, still averting his eyes from Shintani, suddenly opened his mouth to say something.`\

;「あの……。@……先生は油絵も描くんですか？」@
`"Um...`@`... Sensei, are you going to do an oil painting as well?"`@
;「あら、どうして？」\
`"Oh, why do you ask?"`\

;「それって、油絵の道具ですよね……？」@
`"Isn't that a tool for oil painting over there...?"`@
br
;　少年は机の上にあるペンティングナイフを見ていた。\
` The boy was looking at a palette knife placed on her desk.`\
bg black,23
bg bijutu_05,23
ld c,NAF_D1,22
ld c,NAF_D2,80

;「ええ、そうね。@私、水彩画よりも油彩画の方が好きなの。@あの、絵の具を上にどんどん重ねていく感じが好きで。@前は放課後に描いていたりしたんだけど。@……教頭先生にごちゃごちゃ言われたんで、やめちゃったわ。」\
`"Yes, it is. `@`I enjoy doing oil paintings more watercolors. `@`I like being able to put layers of paint on top of each other. `@`I used to paint them after school... `@`but the vice principal started complaining about it, so I stopped."`\

;「怒られたって……。@どうしてですか？」@
`"Why... `@`did he get mad at you
ld c,NAF_D4a,80

;「油絵の具の匂いが教室に染み付いちゃうからって。@そもそもうちの学校の授業で油絵は教えてないのに、@自分の趣味のために美術室を私物化してもらっちゃ困るって、云々……。@本当、堅物なのよねあの人。@……自分だって私物を持ち込んでるくせに、ぶつぶつ。」\
`"He complained that the smell of my oil paints would never air out of the room. `@`Besides, since I don't actually teach oil painting in my classes, `@`he said that I shouldn't use the art room for my own hobbies... `@`Really, he's such a stubborn person.`@`... Even though he always brings in his own stuff to the staff room. *mumble mumble*`\

;「ぼ、……僕も、油絵の方が好きです。@……あ、もちろん、描くんじゃなくて見る方専門ですけど。」@
`"I-... I like oil painting too.`@`... Ah, I mean, I can't really do it, but I like looking at them."`@
br
;　少年はそう言いながら笑顔をつくった。@少しずつ緊張がほぐれてきたらしい。\
` The boy spoke with a smile. `@`It looks like he's eased up a bit.`\
ld c,NAF_D1,80


;　微笑み返しながら、新谷は少し愉快な気持ちになった。@
` Shintani smiled back at him, feeling a little happier.`@
br
;　油彩画は描かなくなったが、……結局、今も自分は趣味のためにこの教室を私物化しているのだ。\
` She may not be able to do oil paintings here anymore... but that hasn't stopped her from using it for her own hobbies.`\
ld c,NAF_D4,80

;　机の上に置かれたままのペンティングナイフにチラリと目をやる。\
` She glanced over at the palette knife sitting on the desk.`\

;　ナイフとは名ばかりの切れ味の悪い刃物。@
` It was a knife in name only. It lacked the sharpness of a real knife.`@
;　確かにこれは油絵の具を混ぜたり、キャンバスに塗り付けたりする時に使う画材だ。\
` It's a tool used for mixing oil paint and applying it to the canvas.`\
bg black,22

;　……だが。@新谷がこれを使うのは絵を描くためではない。@……これには、もっと素晴らしい使い道があるのだ。\
` ...However, `@`Shintani did not use it for painting.`@`...She had a much more wonderful use for it.`\
fede 0,1000
E_A

;bg black,2
bg bijutu_03,22
;ld r,NAF_D4a,22

me1v 11,90

;　シャッ、シャッ、シャッ、シャッ、シャッ……。@
` *scritch* *scritch* *scritch*...`@
; ^^^ Note To Editor: Sound of pencil on paper. Is there a better onomatopoeia?
br
;　先ほどよりも明らかに筆圧が強くなっていた。@実際、新谷は自分の中にある欲望を抑えるのに必死だった。\
` The intensity of Shintani's pencil strokes had obviously gotten stronger. `@`In actuality, she was frantically holding back a certain desire building up within her.`\

ld r,NAF_D4a,22

;　………まだ駄目。@
` ....No, I have to hold back.`@
;　焦らないで、じっくりと時間をかけなきゃ……。@
` I have to be patient and take my time...`@
;　そうしなきゃ私が本当に描きたいものは描けない。@最高の絵は完成しない。\
` If I don't I'll lose my chance to draw what I really want to draw. `@`I won't be able to draw my masterpiece.`\

;　……この子の信用を得るためには、二週間、いや、最低でも三週間は費やさないと。@
` ...In order to earn this kid's trust I need to bide my time for two... no, at least three weeks.`@
br
;　それに裕貴くんが死んでから、まだ一月も経ってない。@ほとぼりが冷めるのにもそのくらいは必要だろう………。\
` Besides, it hasn't even been one month since Yuuki died. `@`She needed at least that long to calm down about that.....`\
ld r,NAF_D6a,22
bg black,2

wait 1000

bg bijutu_02,22
;ld c,NAF_D2,2

;　スケッチを始めてどのくらい時間が経った頃だろう。@少年が不意にまた口を開いた。\
` She wondered how long it's been since she started her sketch, `@`when suddenly, the boy opened his mouth again.`\
E_A
;「………先生。」@
`"....Sensei."`@
br
;　それはさっきまでより一段低い声で、神妙な響きを持っていたので、@新谷は思わず鉛筆を動かす手を止めた。\
` His voice was much lower and meeker than it had been before now. `@`Shintani stopped moving her hand mid-stroke.`\


ld c,NAF_D3,80

;「何かしら？」@
`"What is it?"`@
;「……どうして裕貴くんはあんなことになってしまったんでしょうか。」@
`"...Why did that accident have to happen to Yuuki?"`@
bgm1 14

br
;　突然、野田裕貴の名前が出て来て、新谷は内心どきりとした。\
` Out of the blue, he mentioned Yuuki's name, and Shintani's heart jumped.`\


ld c,NAF_D4a,80

;「…………さあ。@よく分からないわ。」@
`"......Who can say? `@`I'm not really sure myself."`@
br
;　動揺を見せないように心掛け、平静を装いながら、逆に聞く。\
` Trying to hide how off guard his question caught her, she faked a calm voice and replied with her own question.`\


ld c,NAF_D4,80

;「……君、裕貴くんの友達だったの？」@
`"...Were you Yuuki's friend?"`@
;「いえ。@友達ってほど仲が良かったわけでもないんですけど……。」@
`"No. `@`I wasn't really close enough to him to be considered his friend, but..."`@
br
;　そうだろう。@野田裕貴は極端に内気な生徒だった。@友達らしい友達もいなかったはずだ。\
` That would make sense. `@`Yuuki Noda was an extremely timid student. `@`She wouldn't expect him to have had any good friends.`\


;「……先生は、あの噂をどう思いますか？」@
`"...Sensei, what do you think about that rumor?"`@
ld c,NAF_D2,80

;「あぁ、あの？@　……“美術室のルノワール”のこと？」\
`"Ahh, that one?`@`... the story of 'Renoir of the Art Room'?"`\

bg black,24
;cl a,0
bg kaiga_01,24

;　少年は頷いて壁に視線を向ける。@そこには一枚の絵がかけられていた。@
` The boy nodded his head and looked over at the wall. `@`Hanging there was a single painting.`@
;　花が生い茂る鮮やかな花壇の前に、英国風の青いスカートを履いた美少女が立ち、鞭を握りしめている。\
` In front of a flower bed filled with vibrantly colored flowers stood an beautiful English looking girl wearing a blue skirt and gripping a short whip.`\

;　その瞳はとても冷たく、その笑顔はひどく寂しそうだ。@
` Her eyes looked awfully cold, and her smile horribly lonely.`@
br
;　………それが、ピエール＝オーギュスト・ルノワール作『鞭を持つ子供』。\
` .....This was Pierre-Auguste Renoir's 'Child with a Whip'.`\

;　新谷は生徒達が話していた噂を、改めて思い出す。@
` Once again, Shintani recalled the rumor that the students had been spreading.`@
;　学校八不思議の一つ、“美術室のルノワール”の噂を。\
` A rumor about one of the eight mysteries of the school, 'Renoir of the Art Room'.`\


;　“美術室のルノワール”の怪談には、全部で五つの項目があるらしい。\
` Apparently there were five main parts to the story of 'Renoir of the Art Room'.`\
br
;　一、ルノワールに絵筆を借りてはいけない。@
` One, never let Renoir lend you a paintbrush.`@
;　二、ルノワールは美術室に掛けられた絵を指して、作者が誰かを尋ねてくる。@その画家の名を正確に答えなければいけない。@
` Two, if Renoir points to one of the pictures in the art room and asks you who made it, `@`you have to answer the name of the artist correctly.`@
;　三、ルノワールの問い掛けに嘘をついてはならない。@
` Three, you can't lie when answering Renoir's questions.`@
;　四、上記のどれかを破れば、ルノワールの祟りによって美術室にかけられた絵のどれかと、同じ運命を追うことになる。@
` Four, if you break any of the above three rules, you'll be cursed by Renoir to befall the same fate as one of the paintings on the art room walls.`@
br
;　そして、五。\
` And five.`\
br
;　……ルノワールは美術室に飾られた『鞭を持つ子供』に描かれた子供とそっくりの姿をしている。\
` ...Renoir looks just like the kid in the painting 'Child with a Whip' hanging on the art room's wall.`\


;　新谷は少年と共に『鞭を持つ子供』の絵を眺めた。@
` Together with the boy, Shintani stared at that painting, 'Child with a Whip'.`@
;　淡い色彩で描かれた、ぞっとするほど冷たい目をした美しい少女。@それを見つめたまま、新谷は彼に聞き返す。\
` At that pale hued painting of a beautiful girl with eyes so cold they could make you shiver. `@`Without looking away from that painting, Shintani asked him a question.`\

bg black,22
bg bijutu_04,0
ld r,NAF_D2,22

;「…………君は、どう思うの？」@
`"......What do you think?"`@
;「僕は、違うと思います。@ルノワールの祟りで裕貴くんが死んだなんて……。」\
`"I don't think it's true. `@`I don't think that it was Renoir's curse that killed Yuuki..."`\


ld r,NAF_D1,80

;「そうね。@私もそう思うわ。@あんなのはただの根も葉もない噂よ。@……警察は、彼はひとりで美術室で遊んでて、事故に遭ったんじゃないかって言ってたわ。@それで何かの拍子につまずいて、そこに運悪く石膏像が倒れて来て……。」@
`"Yeah. `@`I agree. `@`It was just a rumor, nothing more.`@`... The police said that he was probably just playing alone in the art room and an accident happened. `@`He probably just tripped at some point and unfortunately that bust fell on him..."`@
br
;　新谷は視線を動かした。\
` Shintani shifted her gaze away from the painting.`\

bg black,23
;cl a,0
bg kaiga_02,23

;　……『鞭を持つ子供』の右側にかけられた少し大きめの絵。@
` ...To the right of 'Child with a Whip' there was a slightly larger painting.`@
;　他の絵の様に額に入れられたカラーコピーとは違い、@この一枚だけはキャンバスに描かれた本物の油彩画だった。\
` This picture wasn't a color copy placed in a frame like the others. `@`It was the real thing. An oil painting done on a canvas. Unlike any other in the room.`\


;　……桜坂陽助作、『つぶれた太陽』。@
` ...'The Setting Sun' by Yousuke Sakurazaka.`@
br
;　新谷が聞いた話では、「挫折と再生」をテーマに絵を書き続けるこの桜坂と言う作者は、@昔この学校を卒業した生徒だったらしい。\
` Shintani heard that Sakurazka was a student that graduated from this school a long time ago. `@`Apparently the theme of 'failure and rebirth' was prevalent in many of his works.`\


;　若手画家として一躍注目を浴びるようになったのをきっかけに、@その転機ともなったこの作品を母校であるこの学校に寄付したそうだ。@
` When he was still a young he suddenly happened to hit it big. `@`When that happened he decided to donate this piece of art to the school he graduated from.`@
br
;　そして、野田裕貴の死が“美術室のルノワール”の祟りだと噂になったのは、@そもそもこの絵こそが原因だった。\
` And this painting was originally what started that rumor. `@`The rumor that Yuuki Noda's death was the curse of 'Renoir of the Art Room'.`\

bg black,22
;bg bijutu_07,26

;　『つぶれた太陽』は、いわゆる抽象画だった。@
` 'The Setting Sun' was an abstract painting.`@
br
;　巨大な胸像のような黒い影が、人の形をした淡い光を無慈悲に押しつぶしている。\
` A giant black bust was mercilessly crushing the pale silhouette of a human.`\

mono 2
bg Different_spiral_1b,22

;　……それは、野田裕貴の死んだ状況そのものだったのだ。@
` ...And that was the very same end that Yuuki Noda met.`@
br
;　あちこち汚れて黒ずんだ石膏像。@極端に色が白かった野田裕貴の小さな身体。\
` A blackened plaster bust. `@`And the small, deathly pale body of Yuuki Noda.`\


;bg black,22


;　“美術室のルノワール”、五つの項目のうちの一つ。@
` That was one of the main parts of the story of 'Renoir of the Art Room'.`@
br
;　……ルールを破った者は、ルノワールの祟りによって美術室にかけられた絵のどれかと、同じ運命を追うことになる。\
` ...Whoever breaks the rules of the story will be cursed by Renoir and will meet the same fate as one of the paintings on the art room walls.`\
bg black,22
mono 1
bg bijutu_01,22

;　放課後、美術室にいた野田裕貴はルノワールと遭遇し、彼女から問い掛けをされた。@
` Yuuki Noda had an encounter with Renoir in the art room after school, and had to answer her questions.`@
br
;　……そして彼は、それに答えられなかった、もしくは偽りを述べたため、@裕貴は『つぶれた太陽』になぞらえて殺されたのではないだろうか……。\
` ...He was then either unable to answer a question or told a lie, `@`and was killed in the same manner as 'The Setting Sun'...`\

;　それが今、学校中で蔓延している噂だった……。\
` That is the rumor that has been spreading around the school...`\

bg black,22
mono 0
bg bijutu_03,0
;ld r,NAF_D1,22
ld l,NAF_D1,22

;　ジッと絵を見つめていた少年が、不意に顔を歪めながら口を噤んだ。@
` Still staring at the painting, the boy's face distorted, mouth shut tight.`@
;　絵を見ているうちに、裕貴が死ぬところを想像してしまったのかもしれない。\
` He may have been imagining the scene of Yuuki's death.`\

ld l,NAF_D3,80
;ld r,NAF_D1,80

;「ごめんなさい。@やめましょうね、こんな話。」@
`"Sorry. `@`Let's drop this conversation here."`@
br
;　新谷は笑顔を向けたが、今度は少年の頬は赤くならなかった。@
` Shintani smiled at him, but this time the boy's cheeks didn't turn red.`@
;　眉根を寄せ、泣き出しそうな表情のまま、何かにじっと耐えているようだった。\
` His brow was furrowed and he looked like he deperately trying not to cry.`\


;bg black,2
;mono 1
;bg different_spiral_1b,0
;ld c,NAF_D1,22

ld l,NAF_D5,80

;　……きっと感受性の強い子なのだろう。@
` ...He must have been a very sensitive kid.`@
;　同じ学校の生徒とは言え、友達でもなかった少年の死を、彼は心から哀しんでいるように見えた。@
` Even though they weren't friends, just fellow students at the same school, it looked like he was genuinely grieving the boy's death from the bottom of his heart.`@
br
;　不謹慎この上ないが、新谷はその表情に見惚れてしまった。\
` With the utmost discretion Shintani admired that face of his.`\
me1v 17,50

bg black,0
ld l,NAF_D6a,22

;　……切なげで、苦しそうなその顔。@
` ...Such a heartrending and pained expression.`@
;　悲哀が滲んだことで、彼の美しい顔はより完璧になった気がした。@
` She found his beautiful face racked with sorrow to be beyond perfection.`@
;　背筋にゾクゾクと、快感にも似た震えが走る……。\
` A shiver ran down her spine...`\

bg black,22

;ld c,NAF_D1,80

;　………なんて、……綺麗なのかしら。@
` ...How ...beautiful.`@
br


;ld c,NAF_D1,80

;　…………限界だった。@
` ......I'm at my limit.`@
;　心の中のそわそわが、うずうずが、……とてもじゃないけれど、これ以上、抑えつけることが出来ない。\
` A temptation was rising in her heart... it wasn't much, but it was still too much for her to hold back any longer.`\


;ld c,NAF_D1,80

;　はぁ……。@
` Haaa....`@
br

;bg black,1
;mono 0
;　……っ……。@………………………………。\
`...ah...`@`............`\
bg bijutu_02,22
;ld r,NAF_D2,22

fede 1,1000
E_B
wait 1000
E_A

;　新谷の鉛筆を持つ手が止まる。@
` Shintani's hand stopped drawing.`@
;　その手は、わずかに震えていたが、@彼女の薄っすらとした笑みを浮かべるその表情には、それはおくびも出ていなかった。\
` Her hand was slightly shaking, `@`and she couldn't hide the slight smile that had spread across her lips.`\


ld r,NAF_D1,22

me1v 16,50

;「…………………お茶、飲む？」@
`"..........Do you want some tea?"`@
;「え？」\
`"Huh?"`\

;　新谷にとっては、それはとてもさりげない言葉だった。@
` To Shintani it seemed like a very nonchalant question.`@
;　しかし、少年にとっては、……何だか場違いな、唐突な言葉のように思えた。\
` But to the boy... it seemed entirely out of place and sudden.`\


ld r,NAF_D4,80

;「私、ここに自分用のハーブティーを淹れる道具を置いてあるの。@……ちょっと待っててね。@すぐ淹れてあげるから。」\
`"I have the things here for brewing herbal tea.`@`... Wait here a second. `@`I'll make you some."`\
bg black,23
bg bijutu_05,23

;　新谷は少年の返事も聞かずに立ち上がり、教師用の机に向かう。@
` Without waiting for his answer, Shintani stood up and walked towards her desk.`@
;　その引き出しの中から湯沸かし用のケトルとティーカップを取り出した。\
` Out of the drawer she took out her tea kettle and cups.`\

;cl a,0
;bg bijutu_05,23

;　ケトルをコンセントに差し込むと、５分も待たずにお湯が沸く。@
` Once she plugged the kettle in to the power outlet, it would take less than five minutes to bring the water to a boil.`@
br
;　……その間。@新谷にとっては、不思議な緊張感の沈黙で美術室内は張り詰めているように感じられた。@
` ...In that time, `@`Shintani felt a strange feeling of tension in the silence of the art room.`@
;　この感情は、……怯えでもなければ、緊張でもない……。\
` But that feeling... was neither fear nor nervousness...`\

;　瓶詰めにされた茶葉をいくつか取り出し、慣れた手つきで混ぜ合わせる。@
` She takes the bottled tea leaves out and quickly mixes them with a deft hand.`@
br
;　ハーブティーの爽やかな香りが、ふわりと美術室を満たした。\
` The refreshing smell of herbal tea gently filled the art room.`\

bg black,22
;bg bijutu_03,0

;「……すごくいい匂いですね。」@
`"...Doesn't it smell so nice?"`@
;ld r,NAF_D3,24

;「このハーブ、私がブレンドしたオリジナルなの。@すごくリラックスできるのよ。」\
`"This tea is my original blend. `@`It'll really help you relax."`\

;　……すごく、という部分を無意識に強調してしまう。@
` ...Unconciously she put much more emphasis the world 'really' than she had meant to.`@
;　ティーカップの中は毒々しいまでの赤い色の液体で満たされている。\
` She poured a bright red, almost poisonous looking liquid into their cups.`\

;　少年にティーカップを渡すと、彼は掌を暖める様に両手で持った。@
` She passed the boy his cup and he took it with both hands, as if to warm them.`@
br
;　手を伸ばし……、その白くて長い指に触れたくなるのを懸命に堪える……。\
` She supressed her desire to reach out her hands... and touch those long white fingers...`\
me2v 28,50

ld r,NAF_D5,2

;　……あぁ……、この子ったら爪の形まで本当に綺麗…………。@
` ...Ahh.... this kid. Even the shape of his fingernails were pretty......`@
br
;　新谷は、自らの眼差しで少年を舐め上げるが、……それに彼が気付く様子はない。\
` Shintani stared at the boy, tasting him with her eyes... and he didn't seem to notice.`\

;「……いただきます。」@
`"...Thank you for the tea."`@
br
;　そう言うと彼は目の高さまでカップを持ち上げ、そっと口を付けた。\
` The boy said, as he rose the cup to eye level and gentle placed it up to his lips.`\
ld r,NAF_D6a,22

;　………ゴクリ、……ゴクリ。@
` .....Gulp.... Gulp.`@
br

;ld c,NAF_D1,22

;　飲み込むたびに微かに動く細い喉を見つめながら。@……新谷は心の中で「めしあがれ」と呟く。@
` Shintani watched the muscles in his little throat move as he swallowed his tea.`@`... 'Drink up' she thought to herself.`@
;　白雪姫に毒リンゴを食べさせる女王になった気分だった。\
` She felt like The Queen giving a poison apple to Snow White.`\
bg black,2

fede 0,2000
E_A

;bg bijutu_06,2
bg bijutu_07,2

bgm1 30

;「……………ふぅ…。」@
`".......Hah..."`@
br
;　口から濃い紫煙を吐き出して、新谷は吸っていた煙草を空き缶のふちで消した。\
` A dark gray smoke escaped from Shintani's mouth as she extinguised the cigarette she had been smoking on the edge of an empty can.`\

;　新谷が煙草を吸うのは、この美術室だけだ。@
` The only place that Shintani ever smoked was in this art room.`@
;　職員室は禁煙だし、他の教員や生徒の前で喫煙する姿を見せるつもりもなかった。\
` Smoking wasn't allowed in the staff room, and she wasn't about to let the other teachers or students see her smoking.`\

;　たかだか一本煙草を吸っただけで“優しくて綺麗な先生”という男どもの幻想は簡単に崩れる。@
` If she was ever caught smoking, the illusion the boys have of her, being a kind and beautiful teacher, would be crushed instantly.`@
;　くだらないとは思いながらも、新谷はその幻想に合わせる不自由さを受け入れていた。@その方がいろいろと都合が良いからだ。\
` As stupid as she thought it was, Shintani still forced herself to maintain that illusion. `@`It was more beneficial that way after all.`\

;　可愛らしい笑顔で頼めば男性職員は当番を変わってくれたし、@ミスをして教頭に叱られていても、泣きそうな顔をすれば大抵、誰かが庇ってくれた。@
` If she put on a cute smiling face, at her behest she could make a male staff member switch watch duty shifts with her. `@`And if she was being scolded by the vice-principal, if she started to look like she was about to cry, she could usually make someone stand up for her.`@
;　あの井俣のようにあからさまな好意を抱かれるのだって悪い気はしなかった。@（かといって誘いに応じる気はなかったが……）\
` She didn't really mind the blatant moves made on her by men like Imata. `@`(But on the other hand, she had no intention of accepting their invitations either...)`\

bg black,22
bg bijutu_03,22

;　そして何より、………その幻想に魅せられた男子生徒を、こうやって虜にすることができる……。\
` But above all.... she could make those boys her were enchanted by her illusion into her captives. Just like this....`\
;　教室の奥にある古びたソファーの上で、少年は無防備に寝息を立てていた。@
` In the back of the classroom, on an old sofa, there sat the boy, defenseless and asleep. Breathing softly.`@
;　……よほどのことがない限り、あと２、３時間は目が覚めないだろう。\
` ...If everything goes as expected, he should awake 2 or 3 hours after the medicine took effect.`\

;bg black,0
;bg bijutu_05,0
;ld r,NAF_D1,22
;ld r,NAF_D1,80

ld l,NAF_D2,22
ld l,NAF_D6,80

;「ごめんなさいね。@……でも、それ。@身体には害がないから安心してちょうだい。」@
`"I do apologize.`@`...however, `@`this drug should not do any damage to your body, so rest easy."`@
br
;　新谷は空になったティーカップを見ながら、そう呟く。@
` Shintani muttered as she looked over at his empty teacup.`@
;　あどけない寝顔を見つめて、新谷はうっとりと目を細めた。\
` She then looked over at his innocent sleeping face, and narrowed her eyes.`\

;　……窓からは夕陽が差し込んでいる。@
` ...The light from the evening sun shone through the window.`@
;　部活動をしていた運動部の生徒たちもそろそろ帰っただろうか。@廊下や他の教室からも誰の声も聞こえない。\
` By now most of the students participating in sports clubs have most likely gone home. `@`Not a single voice could be heard coming from the other classrooms or halls.`\


;　こうして静寂に包まれた教室にいると、@この学校の中で生きているのは自分とこの美しい少年だけのような気がしてくる。\
` Being in this classroom wrapped in silence, `@`it made her feel like they were the only living things left inside this entire school. Her and this lovely young boy.`\
cl l,0
ld c,NAF_D5,3

;ld r,NAF_D1,80

;「本当に、なんて綺麗なのかしら……。」\
`"He really is so beautiful..."`\


;cl a,0
bg black,2

;　……いつからだったろう。@自分が幼い少年たちに心魅かれるようになったのは。@
` ...I wonder how long I've been like this. `@`I wonder when I first started being attracted to young boys.`@
br
;　元から年下が好みではあった。@高校の時も大学の時も後輩と付き合っていた。\
` I've always liked younger men. `@`I used to date those in lower grades than me in both high school and college.`\
mono 2
bg Different_spiral_1b,22

;　だが、その恋人達も、当然時間が経つにつれて大人になっていく。@
` But without fail each of her lovers would get older and become an adult.`@
;　子供のような感性をもった者も、@成長するにつれて、そんなものは最初からなかったかのように現実主義者になっていく。\
` Even if they childish and idealistic to start, `@`they would eventually grow past that and begin to look at the world from a more realistic point of view.`\

;　それはさながら、美しい花々が、永遠にその姿を留めておくのは不可能であるかのよう。@
` And just like that, the beautiful little flowers she knew would cease to be that way ever again.`@
;　どんな花々も、必ず散って、萎んでしまう……。@
` No matter the flower, it would eventually wilt and fade away...`@
br
;　だから。@……彼らの成長を知ると、途端に興味が失せてしまった。\
` So`@`.... just as they would inevitably grow up, she would inevitably lose interest in them`\


;bg bijutu_07,26

;　新谷は彼等の少年性を愛していたのであり、@男らしさやたくましさ、人間性などどうでも良かった。@
` Shintani loved those boy-like characteristics, `@`and couldn't care less about things like manliness or physical strength.`@
br
;　その極端な嗜好は、画家を諦め、教師になってからは、ますますに歯止めが効かなくなった……。\
` Once she gave up on being an artist and became a teacher, before long she could no longer repress her extreme preferences...`\
bg black,22
mono 0
bg bijutu_03,0
ld r,NAF_D6,22

;　目の前には、……本物の少年たちがいるのだ。@
` In front of her... were real young boys.`@
br
;　これまでに自分に縁のあった、@大人になりきれない、中途半端な少年性を持った男たちなど比べ物にならなかった。\
` Real boys were all around her, `@`and not a single one of those somewhat childlike men she dated before this could possibly compare.`\

;　新谷は美しき彼らを描き残したいと思った。@
` Shintani wanted to draw these beautiful boys.`@
br
;　ほんの一瞬、@あっという間に終わってしまう「少年」という時間を、永遠のものにしたかった。\
` She wanted to make that single moment, `@`that brief instant called 'boyhood' and capture it for an eternity.`\

;　しかし、描いても描いても、納得できる絵にはならなかった。@
` But, no matter how much she drew, she just wasn't satisfied.
br
;　やがて新谷は気が付く。\
` Until finally, she realized why.`\
;bg black,22
;mono 2
;bg different_spiral_1b,0

cl r,0
ld c,NAF_D6,4

;　自分が少年たちの“健全な姿”になど興味がないということに。@
` What she wanted to capture was not the wholesomeness and modesty of boys.`@
br
;　求めていたのは不健全な、……いや、……不道徳な姿。\
` What she wanted was much more immodest.... no.... downright immoral.`\
ld c,NAF_D6a,22
cl c,4
;ld c,NAF_D8,80

;　……自分の手により、汚され、乱れていく……。@そんな背徳的であさましい姿……。@それこそが、自分が描きたい唯一のものだったのだ。@
` ...To see them disgraced and corrupted by her own hand... `@`A corrupted and miserable appearance... `@`That was all that she wanted to draw.`@
br
;　その願望を理解して初めて。@……新谷は自分という存在を、心底に理解できたのだ。\
` She started to understand her own desires.`@`... And by doing so she could understand herself.`\
bg black,22
bg bijutu_04,22
ld r,NAF_D2,4

;　新谷は少年の傍らに座る。@
` Shintani sat beside the boy.`@
;　白い首筋にそっと指を這わせ、陶器の様な滑らかな肌の感触を、指先いっぱいに味わう。@
` She gently crept her fingers down the pale white skin on the nape of his neck, savoring the smooth ceramic like texture of his skin with her fingertips.`@
;　その滑らかな首には、不潔な大人を意味する無粋なる徴、……喉仏は、まだ出ていない。\
` His smooth throat didn't yet have that impure and inelegant indicator of adulthood... he was still without an Adam's apple.`\


ld r,NAF_D5,80

;　その指を背中に移し、今度は薄いシャツの上から肩甲骨を撫でる。@
` She lowered her fingers down to his back, caressing his shoulder blade through his thin shirt.`@
br
;　……翼の名残とは良く言ったものだ。@この子は本当に天使のようだ。\
` ...Some people say that our shoulder blades are the remnants of wings. `@`This child really seemed like an angel.`\


;　襟の間からチラリと見える鎖骨に触れたくてたまらなくなり、@新谷は彼のシャツのボタンに指をかける……。\
` Glancing down the collar of his shirt, she saw his collarbone and couldn't help but want to touch it. `@`Shintani reached down to undo the buttons on his shirt...`\
bg black,22

;ld r,NAF_D6,80

;「裕貴くんも可愛かったけど。@……この子はそれ以上だわ。@………ふふふふふふ。」@
`"Yuuki was cute.`@`... but this kid is so much more.`@`.... Fufufufufu."`@
br
;　新谷は野田裕貴の小さくて美しかった肉体を思い出した。\
` Shintani recalled the beautiful little body of Yuuki Noda.`\
bg black,22

me1v 28,50

;　白く無垢で、……甘く蕩ける、まるで穢れを知らぬ蜂蜜のよう。@
` Pure white... and so sweet, like a honey that knows no impurities.`@
br
;　しかし、この名も知らぬ少年のそれは、……まさに絶品、極上だった。\
` But, this boy who's name she did not know... his was unique, and of the finest quality.`\
;bg black,22
mono 2
bg bijutu_01,22


;　そう。@この学校の生徒たちは、みんな蜜を持っている。@
` Yes. `@`All of the students at this school had their own nectar.`@
;　蜜を持つ生徒たちがぎっしりとひしめくこの学校は、まさに蜂の巣だ。@
` The students were just like bees, hurriedly carrying nectar around day after day, and this school was their behive.`@
br

;cl a,0
;bg bijutu_06,0

;　そして、……その甘い蜜を、蜂たちは自ら美術室にやってきて、私に献上してくれる。\
` And... the bees bring their sweet nectar to this art room, and present it to me.`\


;　そう。@私は女王蜂。@
` Yes. `@`I am the queen bee.`@
br
;　この美術室に君臨して、……美しい子たちの甘い蜜を堪能する女王なのだ。\
` I am the queen who reigns over this art room... and satisfies myself with the beautiful children's sweet honey.`\


bg black,2


;　……くすくす。@それにしても馬鹿な話だ。\
` ....Hehehe. `@`Still, what a dumb story that was.`\


mono 1
bg kaiga_01,0
ld r,NOD_D1,22

;　“野田裕貴は、“美術室のルノワール”の祟りにあって殺されたのではないか。”@
` 'Yuuki Noda was killed by the curse of Renoir of the Art Room.'`@
br
;　生徒達の間で囁かれるその噂を、新谷は全く信じていなかった。\
` Shintani never once believed that ridiculous rumor passed around by the students.`\

;　裕貴が死んだのは祟りでもなんでもない。@
` Yuuki didn't die because of some curse.`@
;　だって裕貴が死んだ理由を、新谷はこの学校の誰よりも知っていたのだから……。\
` After all, Shintani knew what really killed Yuuki better than anyone else in this school did...`\
bg black,2
mono 0



bg black,22

E_A

;「…………何をしているんですか、新谷先生？」\
`".....What are you doing, Shintani-sensei?"`\
;■↑ルノワールの立ち絵で進めて下さい

bg bijutu_06,23

me1v 16,50

;　突然、背後からかけられた声に、新谷は心の底から驚いた。@
` Suddenly, a voice rang out from behind, and Shintani's heart jumped in surprise.`@
br
;　弾かれたように振り返ると、そこには一人の女生徒が立っていた。\
` She whipped her head around in a flash, and standing there was a single girl.`\
mld c,RUN_D7,2

wait 1000

mld c,RUN_D1,22

;　……それは透き通るような美しさを持ち、@……人間なら誰しもが最低限持っているはずの生臭ささえない、透明感を感じさせた。@
` ...She had a transparent feeling of beauty to her.`@`... Every single human should have at least a faint smell of flesh or skin to them, but this girl had none of that. She felt transparent.`@
br
;　しかし、今はその容姿の端麗さより、何の気配も物音もせずそこにいたことを驚くべきだった。\
` But, more so than her elegant appearance, what truly astonished Shintani was the girl's uncanny lack of presence or sound.`\
ld l,NAF_D5,23
ld l,NAF_D7a,80

;「………誰……！？」\
`"....Who are you...!?"`\
textoff
fede 0,1000
E_A

mld c,RUN_D5,80

bgm1 7

;「……くすくす。@先生が私のことを知らなくても。@私は先生のことをよく知っているわ。」@
`"...Hehehe. `@`Even if you don't know who I am. `@`I know who you are, sensei."`@
ld l,NAF_D6a,80

;「え…？@　……それは、どういう……。」\
`"Wha-...? `@`.... What do you mean by that...?"`\
bg black,22

;　新谷は、人の顔を覚えるのは得意な方だと思っている。@
` Shintani considered herself to be pretty good at remembering people's faces.`@
;　一度でも、美術室を訪れたことのある子なら、絶対に記憶してるはずなのに……。@
` If a kid has been in her art room, even only once, she should definitely be able to recall their face...`@
;　しかし、彼女の記憶に、その女生徒の顔はまったくなかった。\
` But this girl's face wasn't in her memory at all.`\
mld c,RUN_D1,80

;「いいじゃない。@私が、誰かなんて。」@
`"That's fine. `@`You don't need to remember who I am."`@
br
;　新谷の胸中に対して応えるかのように、女生徒は薄く笑う。\
` The girl gave a slight smile. It was as if she was responding to the voice in Shintani's mind.`\
bg bijutu_03,22
mcl c,0
ld l,RUN_D2,4

;「…………それより先生。@その子に一体何をしていたの？」@
`".....By the way, Sensei. `@`What are you doing to that kid there?"`@
br
;　女生徒は視線を、新谷の傍らで眠る少年に向けた。@
` The girl moved her gaze over to the boy sleeping next to Shintani.`@
;　新谷は慌てて立ち上がり、誤摩化すように少年から離れる。\
` Shintani stood up in a panic, as if trying to avoid the question by seperating herself from him.`\
bg black,24
bg bijutu_03,0
ld r,NAF_D2,24
ld r,NAF_D4a,80


;「あ、あぁ……。@この子は、その、絵のモデルをお願いしてたんだけど、急に具合が悪くなったみたいだったから。@……ソファーに寝かせていたの。」\
`"Ah, uhh... `@`I asked this kid to help me out by modeling for a picture, but he suddenly started feeling sick.`@`... So I had him lay down on the sofa."`\
ld l,RUN_D1,23
ld l,RUN_D5,80


;「へぇ……？@　でも具合が悪いんだったらここじゃなくて、@保健室に連れて行った方がいいんじゃないかしら…？」@
`"Oh...? `@`But if he's feeling sick why keep him here? `@`Wouldn't it be better to take him to the infirmary?"`@
ld r,NAF_D6a,80

;「……私もそう思ったんだけどね。@本人が、少し横になれば大丈夫だからって言うものだから。」\
`"...That's what I said. `@`But he kept insisting that he'd be fine and all he needed to do was lay down for a bit."`\
ld l,RUN_D8,80

;「……ふうん。」@
`"...Hmmm."`@
br
;　女生徒は一応、納得したようだった。\
` It looked like the girl accepted that answer for the time being.`\
bg black,22

;　……別に嘘はついていない。@
` ...She wasn't exactly lying.`@
;　ハーブティーを飲んだ後、急に眠気に襲われた彼は確かにそう言ったのだから。@
` He did say that he wasn't feeling so well right after drinking the herbal tea and starting to fall asleep.`@
br
;　……まあ、眠気を誘発するお茶を飲ませたのは、他ならぬ自分なのだが。\
` ...But, the one who made him drink that tea was none other than her.`\
bg bijutu_07,22

;　新谷は動悸を落ち着けようと、すうっと、長い息を吐いた。@
` Shintani took a deep breath to try and slow her heartbeat down.`@
;　………誰だか知らないけれど、これ以上ここで長話を続けて得をすることはない。@
` ....She had no idea who this person was, but Shintani had nothing to gain from continuing their conversation in this room.`@
br
;　新谷は、わずかに口調を強め、少し咎めるように言った。\
` Shintani lowered the tone of her voice and moved to shift the blame onto the girl.`\
;「あなたこそ、美術室に何か用？@　もうとっくに下校時刻のはずでしょう？」@
`"And what are you doing in the art room? `@`School got out hours ago."`@
br
;　言いながら、改めて彼女の顔を見る。\
` She spoke while looking over the girl's face one more time.`\

bg bijutu_04,0
ld c,RUN_D1,22

;　……顔は、確かに美しい。@……まるで、中世の彫像を見るかのように、美しい。@
` ...Her face certainly was beautiful.`@`... Almost like the beauty of a statue from Middle Ages.`@
br
;　しかし、……それはまさに彫像そのまま。@
` But... it wasn't just that. It was like she really WAS a statue.`@
;　冷たく、血の通った温かさを感じさせない、……まるで蝋人形のように冷え切った顔だった。\
` She was cold, and didn't appear to have any warm blood flowing through her veins... It was almost as if her face was that of a wax figure, frozen in time.`\
ld c,RUN_D5,80

me1v 16,50

;「くすくす……。@私には下校時刻なんて関係ないんですよ、先生。@だって、私には帰るところなんてないんだから。」\
`"Hehehe... `@`What time school ends bears no significance to me, sensei. `@`After all, I have nowhere to go home to."`\
;　……この町では、共働きの家庭はとても多い。@
` ...In this town there were many households that had parents who both worked full-time.`@
;　帰っても家に家族のいない生徒の一部が、@時にそう称して、家へ直帰せずに放課後を遊び歩くことがあるのを、新谷も知っていた。@
` There are some students that will go home to an empty house, `@`but others will sometimes choose to loiter around school after-hours. Shintani knew this.`@
br
;　しかし、……彼女の言うそれは、それとは何か違うように感じられた。\
` However... with the way this girl worded it, that didn't seem to be what she was talking about.`\
bg black,22

;　……それにしても。@
` ....Still.`@
br
;　何て美しい少女だろう。\
` She was such a beautiful girl.`\
ld_p RUN_D1
lsp2 4,$ld_pass,400,400,200,200,0
lsp2 5,$ld_pass2,400,400,200,200,0
print 22

;　それは「可愛い」とか「綺麗」と言ったありきたりな形容では収まらない。@
` Describing her with such ordinary words as 'cute' or 'pretty' just doesn't do her any justice.`@
;　女の新谷でさえ、見入ってしまうほどに求心力に満ちた魔性の笑みだった。@
` Her devilish smile held such powerful gravitational pull, that even a woman like Shintani couldn't take her eyes of it.`@
;　……まるで背中に氷の爪を立てられたように、ぞわりと総毛立つ。\
` ...It made her hair stand on end, as if claws of ice were running down her back.`\
csp2 -1
print 0
bg black,2

fede 10,1000
E_MA

bg bijutu_02,22
ld r,RUN_D1,22

;「あら。@……これが新谷先生の絵？」@
`"Oh, what's this?`@`... Did you draw this, Shintani-sensei?"`@
br
;　いつの間にか女生徒の手には、新谷のスケッチブックがあった。@
` At some point the girl had picked up Shintani's sketchbook.`@
;　その中の一枚のページを開き、興味深げに眺めている。\
` She had it open to a page that she was looking intently at.`\
;　……それは先ほどまで新谷が描いていた少年の絵だった。@
` ...It was the picture of this boy that she had been drawing before this.`@
;　まだ、顔しか描かれていない。@
` The only part she hadn't drawn of him was the face.`@
br
;　……首から下を描く前で本当に良かった。@新谷はホッと胸を撫で下ろす。\
` ...Luckily she drew everything beneath the neck first. `@`Shintani heaved a sigh of relief.`\
ld r,RUN_D8,80

;「ふうん……。@まだ書き掛けなんですね。」@
`"Hmm.... `@`It's not finished yet."`@
ld l,NAF_D4a,23
;ld l,NAF_D3,80

;「……えぇ。@ほら、彼が眠っちゃったから。」@
`"...Yeah. `@`Since, as you can see, he fell asleep."`@
ld r,RUN_D2,80

;「そうなんですか。@/
`"Ah, I see.`@/
cl r,0
ld c,RUN_D5,24

;……ねぇ、新谷先生。」@
`....Hey, Shintani-sensei."`@
br
;　女生徒が上目遣いに新谷の目を覗き込んでくる。\
` The girl peered into Shintani's eyes.`\
;ld l,NAF_D4a,80

　ぞくりとする、……こちらの魂の奥底を覗き込んでくるような瞳だった。\
` Shintani shivered... it was as if her eyes were looking directly into her soul.`\
ld c,RUN_D1,80

;「……良かったら。@……彼の代わりに私を描いてくれません？」\
`"...If you want to`@`... why don't you use me as a model in his place?"`\
fede 0,1000
E_A

ld l,NAF_D7a,22
bgm1 30
;「…………………え？」@
`".......Huh?"`@
br
;　突然の彼女の言葉に私は目を丸くした。\
` Upon hearing her sudden question, my eyes widdened.`\
;sss
ld c,RUN_D5,80

;「どうせ彼の目が覚めるまで先生はここにいるんでしょう？@　だったらその間に私の絵を描いてくれませんか…？」@
`"You're going to have to stay here until he wakes up, right? `@`So why don't you draw me in the meantime...?"`@
ld l,NAF_D6a,80

;「……………。」\
`"......."`\

ld c,RUN_D1,80

;「いいでしょ、先生。@……お願い。」@
`"It'll be fine, sensei.`@`... Please?"`@
br
;　………新谷は断れなかった。@
` ....Shintani had no choice.`@
;　覗き込んでくる女生徒の目が、@新谷がしようとしていたことを全て見透かしているように見えたからだ。\
` The eyes of this girl, `@`they look like she could see through everything Shintani was trying to do.`\
;csp2 -1
;print 0
bg black,22
bg kaiga_02,22

;　仮にやましいことが一切なかったとしても、@放課後の美術室に女教師が生徒を私的目的で連れ込んだ、などという言われ方をしたら。@……痛くもない腹を探られかねない。@
` Even if she wasn't doing anything wrong, `@`if that someone started going around saying that a teacher was bringing students to the art room after school for her own personal goals.`@`... It's entirely possible that she could be falsely accused of something.`@
;　この美術室という聖域を、壊されたくない。@
` She didn't want anyone to ruin the sanctuary that is her art room.`@
br
;　面倒事を避けたい新谷は、首を縦に振る他なかった……。\
` Wanting to avoid any trouble, Shintani could do nothing but nod her head in agreement...`\
bg black,22
bg bijutu_03,22


;　新谷は無言で彼女からスケッチブックを受け取り、新しいページを開く。\
` She silently took the sketchbook from the girl and turned to a new page.`\
ld c,RUN_D5,22

;「うふふふふふふふふ……。@ありがとう、新谷先生。」@
`"Ufufufufufu...`@` Thank you, Shintani-sensei."`@
br
;　女生徒は無邪気に笑うと、勧められてもいないのに、自らモデル用の椅子に座る。\
` The girl laughed innocently and, without any instruction from Shintani, went over and sat on the modeling chair.`\
ld c,RUN_D1,80

;「あら、この椅子、ソファーみたいにフカフカしてるのね。@座り心地が良いわ。」@
`"Oh my, this chair is really soft, just like a sofa. `@`It feels good to sit on."`@
;「………あんまり動かないでね。@うまく描けないから。」\
`"...Don't move around too much. `@`It makes it hard to draw."`\
ld c,RUN_D5,80

;「もちろん、大人しくしているわ。@………だけど、おしゃべりくらいはいいかしら？」@
`"Don't worry, I'll sit still.`@`... But can I at least move my mouth to talk?"`@
;「………少しくらいならね。」\
`"....If it's just a little."`\
ld c,RUN_D1,80

;「そうね。@……じゃあ、あの話はどうかしら？@　最近生徒の間でもちきりの、あの噂。@……“美術室のルノワール”。」@
`"Okay.`@`... So, what do you think of that story? `@`The one that the students have been talking about recently.`@`... 'Renoir of the Art Room'."`@
br
;　筆入れから鉛筆を取り出そうとしていた新谷の手が止まった。\
` Shintani's hand stopped right in the middle of getting a pencil out from her pencil case.`\
;ld c,RUN_D3,80

bg black,22

;「ぴったりの話題よね。@だってここは美術室なんだし。」@
`"I thought it would make for a good topic. `@`Since this is the art room and all."`@
;「………不謹慎じゃない？@　あんな事故があったって言うのに。」@
`"....Isn't that a bit rude? `@`Talking about that rumor so soon after the accident happened."`@
br
;　喉の奥に声が絡む。\
` Her voice got caught up in the back of her throat.`\
;ld c,RUN_D6,80

;「あら……。@じゃあ、先生は彼……、@野田裕貴くんが死んだのは事故だと思っているんですね？@　“美術室のルノワール”の祟りじゃなくて。」@
`"Oh....?`@` Then you think his.... `@`Yuuki Noda's death was an accident, then? `@`Not the curse of 'Renoir of the Art Room'."`@
;「……当たり前じゃない。@祟りなんて持ち出す方がどうかしてるわ。」\
`"...Obviously. `@`There's no such thing as curses."`\
;ld c,RUN_D1,80

;「ふぅん……。」@
`"Hmm...."`@
br
;　女生徒は愉快そうに微笑んだ。\
` The girl smiled pleasantly.`\
bg bijutu_02,22

;ld c,RUN_D3,80

;「じゃあ、もう一つの噂は聞きました？」@
`"Well then, have you heard the other rumor?"`@
;「もう一つの噂？」\
`"Other rumor?"`\
;ld c,RUN_D2,80

;「ええ。@野田裕貴くんがいじめを受けていた、という噂です。」@
`"Yeah. `@`The one that Yuuki Noda was being bullied."`@
;「…………。」\
`"......"`\
bg black,22

fede 0,1000
E_A

mono 1
bg shokuin_01,22

bgm1 18

;　それは生徒たちだけではなく、教員や保護者の間でも話題になったことだった。\
` It wasn't just the students that were talking about that, it was a hot topic among the staff and parents of other students as well.`\
;　美術室で発見された野田裕貴の遺体には、@生前から日常的につけられたたくさんの傷跡があったのだ。@
` When they found Yuuki Noda's body in the art room, `@`they discovered a lot of scars that were made when he was still alive.`@
br
;　裕貴の両親はクラス内でいじめがあったのではないか、と学校側を問い詰めた。\
` Yuuki's parents question the school on whether he may have been bullied by someone in his class.`\
;「……あれだって、ただの噂でしょ？@　担任の先生もクラスメートの子たちも、いじめの事実はなかったと否定したはずよ。」@
`"...Wasn't that just a rumor? `@`His homeroom teacher and fellow classmates all said that he wasn't being bullied."`@
;「ええ。@実際、いじめの証拠のようなものは何も見つからなかったそうですね。」\
`"Yeah. `@`It's true that they never found any evidence that he was being bullies."`\
bg black,22

;「そうよ。@……学校内の誰一人として、裕貴くんがいじめられている姿を見た人間はいなかったんだから。」\
`"Exactly.`@`... Not a single person in this entire school said they had ever seen him being bullied."`\
;「でも、目撃者がいないからと言って、@いじめがなかったとは限らないんじゃないかしら……？@　人目につかないような場所で暴力を振るわれていたかもしれないですよね？@　……例えば、ほら。」\
`"But, `@`does the absence of evidence really prove that he was never bullied....? `@`Aren't there still places that he could come into contact with violence without any of those people seeing?`@`... For example."`\
mono 0
bg bijutu_01,22

;　女生徒はそこで言葉を区切ると、首だけ回して美術室の扉を見た。\
` The girl paused in the middle of her sentence and turned only her head to look over at the door to the art room.`\
;「ここみたいに、内側から鍵がかけられる特別教室とか……。」@
`"A unique sort of classroom that can be looked from the inside, just like this one..."`@
br
;　新谷の前髪に隠れた額と握り込んだ掌から、嫌な汗がじわりと滲み出る……。\
` On her brow hidden beneath her bangs and in her clenched hands, Shintani started to sweat...`\
;「先生はご存知でした？@　裕貴くんの身体にあった傷は、殴られたり蹴られたりした様な単純なものじゃなくて、@変わった傷が多かったみたいですよ？@　まるで、切れ味の悪い刃物を肌に押し当てられたみたいな…………。」\
`"Have you heard this, sensei? `@`Apparently the marks on Yuuki's body didn't look like they were simply from him being punched or kicked. `@`He had a bunch of unusual marks on him. `@`Almost like a dull knife had been pressed against his skin....."`\
bg black,23
bg bijutu_02,0
ld c,NAF_D5,23

;「………………。」@
`"........"`@
br
;　新谷は、手元のスケッチブックに視線を落としたまま、@机の上に置きっぱなしにしたままのペンティングナイフを、目の端で捉える。\
` Still staring down at the sketchbook in her hands, `@`out of the corner of her eyes, Shintani saw the palette knife sitting on top of the desk.`\
bg black,23
bg bijutu_04,23


;　不自然に見えないよう、一間置いてからスケッチブックを持ったまま立ち上がり、@別の角度から女生徒を描くかのように机の方に移動する。@
` She waited a moment not to seem suspicious, then stood up holding her sketchbook. `@`Under the guise of getting a different angle of the girl, she moved toward the desk with the knife sitting on it.`@
br
;　そして女生徒の目を盗んでナイフを取ると、音を立てない様に注意して引き出しの中にしまった。\
` She stole the knife out from under the girl's eyes and, being careful not to make a sound, put it into the drawer in her desk.`\
bg black,22

;　……大丈夫。@彼女には気付かれていない。@ほっと胸を撫で下ろす。\
` ...It's okay. `@`She didn't notice. `@`Shintani let out a sigh of relief.`\
bg bijutu_03,0
ld r,RUN_D1,24

;　その場で立ったまま適当にスケッチブックに筆を走らせると、自分の椅子にゆっくりと戻った。\
` While still standing there she made a few strokes in the sketchbook with her pencil before slowly returning to her own chair.`\
ld r,RUN_D8,80

;「……私、思ったんですよ。@もしかして裕貴くんは、@いじめじゃなくて誰か大人の人に虐待されてたんじゃないかって……。」\
`"...I've been thinking. `@`Maybe Yuuki was being bullied at all. `@`Maybe he was being abused by an adult..."`\
ld l,NAF_D6a,23

wait 1000

ld l,NAF_D4a,80

;「………どうしてそんな風に思うの？」@
`"....Why do you think that?"`@
ld r,RUN_D6,80

;「火傷の痕です。」@
`"The burn scars."`@
br
;　新谷の喉から、ひゅっ、と息を吸い込む変な音が出た。\
` Shintani swallowed a breath and let a strange sound out of her throat.`\
;ld r,RUN_D3,80

bg black,22

;「裕貴くんの身体には、@小さくて丸い、火ぶくれみたいな火傷の痕がたくさんあったらしいんですよ。@まるで、煙草を押し付けられたみたいな。」\
`"On Yuuki's body, `@`there were multiple little, round scars from burn marks that looked like blisters. `@`Almost like someone had been burning him with the end of a cigarette."`\
;bg black,23
bg bijutu_04,22

;　新谷は再び机の上に目を向ける。@もう一度立ち上がってあそこまで行くのは不自然過ぎるだろうか……。\
` Shintani once again looked over at her desk. `@`She would draw too much attention to herself if she walked over to it again...`\
;　しかし、その心配は杞憂だった。@煙草はさっきしっかりと引き出しの中にしまった。@
` However, there was no real reason for her to worry. `@`She made sure to put her cigarettes into the drawer earlier.`@
br
;　それにこの部屋には灰皿がない。@机の上の空き缶も、パッと見には吸い殻が入っているとは分からないはずだ。@
` Besides, there isn't an ashtray in this room. `@`Even if you looked into the can sitting on her desk, at a glance you wouldn't be able to tell that there was a cigarette butt inside.`@
;　臭いだって、……様々な塗料の臭いがごちゃ混ぜになってて、わかるはずがない……。\
` As for the smell... there were so many different smells in an art room from the paint and materials that it shouldn't be noticable...`\
bg black,22
bg bijutu_07,22

;「………あら。」@
`"....Hmm?"`@
br
;　女生徒は首を傾げ、新谷の腰の辺りに視線を向けた。\
` The girl tilted her head and shifted her gaze to Shintani's waist area.`\
;「先生のそのポケットに入ってるのって、もしかしてライターですか？」@
`"Sensei, is that a lighter in your pocket?"`@
me1v 16,50

br
;　今度こそどきりと、新谷の心臓が跳ね上がった。\
` This time, Shintani's heart really did jump with fright.`\
bg black,22

;　慌ててジャケットのポケットを見る。@
` In a panic she looked down at her jacket's pocket.`@
br
;　……ぴったりとしたポケットの一部分だけが、@露骨にライターを想起させる小さな長方形の形に膨らんでいた……。\
` ...It was just a small portion of it, `@`but you could clearly see the small rectangular shape indicative of snugly tucked in her pocket...`\
bg bijutu_03,0
ld l,RUN_D7,22
ld l,RUN_D1,80

;「意外です。@先生、煙草を吸われるんですね。」@
`"That's surprising. `@`Sensei, do you smoke?"`@
ld r,NAF_D6a,22

;「……………………。」\
`".........."`\
ld l,RUN_D5,80

;「普段は隠してるんですか？@　まぁ、先生みたいなタイプだと、堂々と吸うのは肩身が狭いですよね。@今は男性の先生方でも吸わない人の方が多いですもんね。@くすくすくすくすくす。」\
`"Do you usual try to hide it? `@`Well, for a teacher like you, it must feel pretty shameful to smoke out in the open. `@`Especially since even the male teachers don't smoke as much any more. `@`Hehehehe."`\
ld r,NAF_D8a,80

;　ボキリ。@
` SNAP.`@
br
;　鉛筆を持つ手に思わず力が入ってしまったのだろう。@……ぽっきりと芯が折れていた。\
` Shintani must have put too much strength behind the pencil she was drawing with.`@`... and broke the lead right off the tip.`\
ld l,RUN_D3,80

;「あらあら、大丈夫ですか…？」@
`"Oh, what's wrong? Are you okay...?"`@
br
;　椅子に座ったままの体勢で、女生徒が手を差し出してきた。@
` Still sitting posed in her chair the girl extended a hand out towards Shintani.`@
;　その手には一本の鉛筆が握られている。\
` In that hand she held a pencil.`\
ld l,RUN_D1,80

;「良かったらどうぞ。@私のを使ってください。」@
`"If it's okay with you, `@`please use mine."`@
ld r,NAF_D6a,80

;「…………結構よ。」@
`"......No, it's fine."`@
br
;　新谷は筆入れからカッターを取り出し、折れた鉛筆を削りだした。\
` Shintani reached into her pencil case, got out a boxcutter and started to sharpen her broken pencil.`\
bg black,22

fede 1,1000
E_B

bg kaiga_02,22

;　削られていく鉛筆を見ながら、自分は一体何をしているんだろう、と思う。\
` Staring down at the pencil she was whittling away at, Shintani thought to her herself 'what the hell am I doing?'`\
;　この子さえ来なければ今頃は……。@
` If only this kid wasn't here, right now I'd be...`@
br
;　いや、まだチャンスがなくなったわけじゃない。@もともと今回は時間をかけるつもりだったのだ。@日を改めて、ゆっくりと…………。\
` No, it's not like her chances were ruined. `@`She just has to bide her time, like she intended to do before. `@`Be patient and wait for another day......`\
bg black,22

;　………………………。@……………。@
` ...........`@......`@
br
;　唐突に新谷は違和感を覚えた。@
` Suddenly, Shintani felt that something was out of place.`@
;　……今、この子はどこからさっきの鉛筆を出したのだろう……？\
` ....Where did that girl get that pencil from just now...?`\
bg Different_spiral_1a,22

;　彼女は筆箱はおろか、鞄のようなものも持っていない。@
` The girl wasn't carrying a bag with her, nevermind a pencil case.`@
br
;　差し出された鉛筆は、削りたてのように鋭く尖っていた。@黒光りした芯は鋭利な針のようですらあった。\
` The pencil that she had held out looked like it had just been sharpened. `@`The newly polished lead looked just as sharp as a needle.`\
;　ポケットにでも入れていた？@　いやいや、……剥き出しの鉛筆を、そのままポケットに収めて持ち歩くわけもない。\
` Did she have it in her pocket? `@`No... she probably wouldn't be able to carry around that pencil in her pocket without ruining the sharpness of the lead at least a little.`\
me2v 28,50

bg Different_spiral_1b,22

;　………唐突に取り出し、差し出してきた、一本の鉛筆。@
` .....She suddenly pulled out a pencil and handed it to Shintani.`@
;　ただそれだけのことのはずなのに、……どうしても違和感を拭えない。@
` That's all that happened... but no matter what Shintani couldn't shake her sense that something was out of place.`@
br
;　違和感？@　何の？\
` Out of place? `@`But what?`\

;　…………………………。@
` .............`@
br
;　新谷の脳裏を、ぼんやりと過ぎる、あの、怪談。@
` It had compltely slipped her mind. That ghost story.`@
;　美術室のルノワールの怪談が語る、最初の禁忌……。\
` The first of rule of the story of Renoir of the Art Room...`\
bg black,22

locate 1,5

;“ルノワールに絵筆を借りてはいけない。”\
`'Never let Renoir lend you a paintbrush.'`\
E_A



ld r,NAF_D6a,22

bgm1 16

;　背筋につーっと冷たい汗が流れる。@
` A cold sweat ran down Shintani's back.`@
br
;　鉛筆も絵筆ということになるのだろうか？@　もしも、あれを受け取っていたらどうなっていた？\
` Would a pencil count just the same as a paintbrush? `@`What would have happened if she had accepted that pencil?`\
;ld c,NAF_D7a,80

;　…………ど、……どうにもなるものか。@
` ......Wh- ...Would she have broken the rule?`@
br
;　あれはルノワールという妖怪の話だ。@
` It was a story about a youkai named Renoir.`@
;　妖怪から借りてはいけないのであって、@……見ず知らずとはいえ、女生徒から借りてはならないわけではない……。\
` So obviously she's not supposed to let that youkai lend her anything.`@`... But what about a random girl she doesn't even know the name of? That's not breaking the rules, right...?`\
bg black,0
ld c,RUN_D1,2

;　…………………………。@
` ............`@
br
;　………彼女は、……本当は、…………誰。\
` ....Just... who is....... this girl?`\


;　新谷は、目の前のモデルが、本当にただの女生徒で人間なのか、@………そんな当り前のことが、わからなくなりかけていた……。\
` Was the girl modeling in front of Shintani really just a normal human being?`@`.... She suddenly began to doubt something that she had never doubted before...`\
bg bijutu_03,0
ld c,RUN_D1,2

ld c,RUN_D5,80

;「どうしたんですか、先生？@　顔色が悪いですよ。」@
`"What's wrong, sensei? `@`You're looking a little pale."`@
;「………………。」\
`"........"`\
;　私は何だって、……放課後の美術室で、名も知らぬ少女の絵を描かされているのか。@
` Why am I doing this?.... Sitting in the art room after school being made to draw a picture of a girl who's name I don't know.`@
;　そもそも彼女は誰なのか。@……名前さえ知らない。@
` Who even is she?`@`... I don't even know her name.`@
;　いや、……そもそも、……何者かさえ、わかっちゃいない。\
` No... I don't even know... what she is.`\
ld c,RUN_D2,80

;「ああ、そう言えば、発見された時の裕貴くん。@………着ていたシャツのボタンを掛け違えてたみたいですね。」@
`"Oh, by the way, you know when they found Yuuki....`@` apparently the buttons on his shirt were mixed up."`@
;「……え？」\
`"...Huh?"`\
bg black,22

me1v 17,50

;　ボタン？@　掛け違えてた？\
` Buttons? `@`Mixed up?`\

;mono 1
;bg bijutu_03,22

;　新谷は記憶を呼び覚まそうとする。@だが、駄目だった。@
` Shintani tried to jog her memory. `@`But it was no good.`@
br
;　……あの時のことは、……ほとんど覚えていない。@それほどに慌てていた。\
` ...She couldn't remember... much of what happened then. `@`She was in too much of a panic.`\
;bg black,22
;mono 0
bg bijutu_02,22
ld l,RUN_D7,22
ld l,RUN_D3,80

;「私、不思議に思ったんですよ。@ほら、彼って随分と几帳面な性格だったじゃないですか。@いつも一番上のボタンまできちんと止めていたし。@……だから、もしかしたら、死んだ後に誰かが服を着せたのかもしれないなぁって……。」\
`"I thought it was really odd. `@`After all, he seemed to have a really orderly personality. `@`He always buttoned them up to the very top button.`@`... So, I was thinking, what is someone changed his clothes after death...."`\
ld r,NAF_D6a,24
ld r,NAF_D7a,80

;「……バカバカしい。@何？@　彼は死んだ時、裸だったとでも言うの？」@
`"...How absurd. `@`What? `@`Are you suggesting that was naked at the time of his death?"`@
br
;　言いながら、新谷はあることに気づく。\
` As she spoke, Shintani noticed something.`\
;　火傷の痕、掛け違えたシャツのボタン。@……何でそんなことまで彼女は知っているのだ？@
` The burn marks, the messed up buttons on the shirt.`@`... Why did this girl know all of these things?`@
br
;　実際に裕貴の遺体を見たのは放課後に見回りをした先生だけだ。\
` Practically the only person who actually saw Yuuki's body was the teacher who found it after school.`\
bg black,22
mono 1
bg bijutu_01,22

;　その後すぐに警察が呼ばれ、この教室は立ち入り禁止になったはずだ。@一般の生徒が彼の死体を見る様なタイミングはなかったはずだ。\
` Immediately after that the police were called, and at that point entering the classroom should have been off-limits. `@`There shouldn't have been any opportunity for a student to get a look at his corpse.`\
;　もしも見たとしたら……。@
` Assuming she saw the body...`@
br
;　……彼女はその時この美術室に“いた”ことになる。@
` ...Then that would mean that she was 'there' in the art room when it happened.`@
;　…………新谷と裕貴の２人しかいないはずなのに、“いた”ことに、なる。\
` ......Shintani and Yuuki should have been the only 2 people in the room, but she was 'there'.`\

bg black,23
mono 0
bg bijutu_03,0
ld c,RUN_D6,23
ld c,RUN_D3,80

;「彼が裸だったらおかしいですか？@　だってここは美術室じゃないですか。@何かの本で読んだんですけど、@デッサンの練習には人間の裸が一番良いんですよね？@　……ああ、そう言えば先生……、」@
`"Would it have been so odd for him to be naked? `@`After all, this is the art room. `@`I read in a book once, `@`that drawing the naked human form is the best way to practice sketching.`@`... Ah, by the way, sensei...."`@
br
;　女生徒が大きな瞳で新谷の目を覗き込む。\
` The girl's large eyes looked directly into Shintani's.`\
ld c,RUN_D5,80
me2v 16,50
;「……先生はヌードって、描かないんですか？」\
`"...Sensei, don't you do nude drawings?"`\
quakey 1,100

;　……ガタリ。@
` ....Bang.`@
br
;　椅子に座ったまま、新谷は後退る。\
` Shintani sank down into her chair.`\
;　背中は嫌な汗でべっとりだった。@
` Her back was covered in sticky sweat.`@
br
;　生唾を、ごくり、と飲み込みながら、………新谷は確信した。\
` She gulped down her saliva.... Shintani was now positive.`\
bg black,0
mld c,RUN_D5,2

;　………彼女は、知っている。@
` .....This girl knew.`@
br
;　この美術室で新谷がしてきたことを、彼女は全部見ていたのだ。\
` She saw everything that Shintani had done in this room.`\
;　誰が見ていた？@　誰もいなかった。@なのに、いた。@
` Who was watching? `@`There shouldn't have been anyone. `@`And yet, she was there.`@
br
;　……だとしたら。@それはもう、美術室に存在する、人ならざる存在しかありえない。\
` ....In that case, `@`she must have been there all along. The only possibility is that she is not human.`\
;　この女生徒こそ、“美術室のルノワール”だ。@それはもう疑いようがなかった。\
` This girl is 'Renoir of the Art Room.' `@`Of that she was sure.`\

bg bijutu_03,22
mcl c,0
ld c,RUN_D1,80

;「どうなんですか、先生？@　ヌードは描かないんですか？」@
`"Well, sensei? `@`Do you do nude drawings?"`@
;「……まさか、そんなわけ………。」\
`"...What are you talking about, of course I d-....."`\
;　そんなわけない、と言おうとして新谷は再び思い出す。@
` Shintani was about to say that she didn't, but once again she remembered something.`@
;　美術室のルノワールのもう一つの禁忌を。\
` Another of the rules of Renoir of the Art Room.`\
bg black,22
locate 0,5

;　……“ルノワールの問い掛けに嘘をついてはならない。”\
` ....'You can't lie when answering Renoir's questions.'`\
bg bijutu_03,0
ld c,RUN_D1,22
ld c,RUN_D5,80

me3v 28,70

;「“そんなわけ”？@　ふふふふふふ……“そんなわけ”何なのかしら？」@
`"'Of course I d-'? `@`Fufufufu... Of course you what?"`@
br
;　女生徒は、……いや、ルノワールは意地悪そうに笑う。\
` The girl... no, Renoir put on a sinister smile.`\
;　“そんなわけない”なら、それは嘘を吐いたということになる。@
` If she said 'of course I don't' then that would have been a lie.`@
br
;　……だったら何だと言うのか。@だったら、私をその祟りで飲み込んでしまおうと言うのか。\
` ...If she did, what would that mean for her? `@`If she did, would she have been caught in a curse?`\
;　もう、間違いない。@……この眼前の少女は、人間ではないのだ。@
` There was no doubt of it now.`@`... This girl before her was not human.`@
;　……それを理解して初めて。@……新谷は目の前の存在が、明らかに人間とは異なる気配を放っていることを理解する。@
` ...Shintani began to understand.`@`... Understand that the being in front of her eyes obviously lacked even a hint of humanity.`@
;　……………………。\
` ..........`\
bg black,22

;　そのルノワールからの、……ヌードは描かないのかという、問い掛け。@
` Renoir had asked if she drew nude picture.`@
;　嘘は吐けない。@それはルノワールの禁忌だ。@
` She can't lie. `@`That was one of the rules.`@
br
;　……………………………。\
` .............`\
bg bijutu_02,22
;ld r,RUN_D5,22
ld l,NAF_D4a,23
ld l,NAF_D6a,80

;「………描くわよ。」@
`"....I do."`@
br
;　声が震える。@
` Her voice trembled.`@
;　人ならざる者の問いに答えるということは、@それだけで恐ろしいことなのだと、彼女は初めて知る。\
` For the first time in her life, she felt how terrifying it was. `@`How terrifying it was to answer the question of something inhuman.`\
ld l,NAF_D7a,80

;「貴方の言う通り、人間の身体を描くのは難しいから。@……いい練習になるわ。」@
`"Just like you said, it's difficult to draw the human body.`@`... so it's good practice."`@
br
;　無意識のうちに、机の引き出しに視線が動く。\
` Unconsciously she shifted her gaze over to her desk drawer.`\




;＜＜＜＜＜＜＜＜＜＜＜＜＜＜




ld r,RUN_D1,22

;「へえ……。@じゃあ、もしかしてこの美術室でも描いたこともあるのかしら……？」@
`"Oh?.... `@`Well then, have you ever drawn one in this art room...?"`@
ld l,NAF_D6a,80

;「……………。」\
`"......."`\
;　新谷は口を閉じた。@
` Shintani closed her mouth.`@
;　答えないことは嘘にはならないはずだ。@
` She couldn't answer with a lie.`@
br
;　沈黙を守る間、……新谷は野田裕貴の美しい裸を思い出した。\
` While keeping silent... Shintani recalled Yuuki Noda's beautiful naked body.`\
bg black,5
mono 1
bg bijutu_03,0
ld c,NOD_D4,22
ld c,NOD_D5n,80

;　……未成熟な少年の身体。@
` ...His immature male body.`@
br

mono 0
print 0
mbg red1,1
mono 1
print 0
mcbg 22

ld c,NOD_D6,80

;　ペンティングナイフを振るたびについていく赤い線。@白くて美しい肌に、煙草の火で醜い焦げ痕をつける瞬間の、……ぞくぞくするほどの快感。\
` Whenever she moved the palette knife, a red line would follow. `@`And when her cigarette caused an unsightly burn mark on that beautiful white skin... she shivered with pleasure.`\
;bg black,22

cl c,22

mono 0
bg bijutu_03,2
wait 1000

ld c,RUN_D1,22
ld c,RUN_D5,80

;「ふふふふふふふふ。@……黙るなんてずるいわ。@暇潰しのお喋りくらい、付き合ってくれてもいいでしょう？@　モデルは動けなくて退屈なんだから。」@
`"Fufufufufufufu.`@`... Not answering? That's no fair. `@`You could at least let me kill some time by chatting. `@`It gets boring as a model, not being able to move."`@
br
;　そう言いながら、彼女は立ち上がる。\
` As she said that, the girl stood up.`\
;　少女が立ち上がっただけなのに、……まるで巨人に見下ろされるかのような気持ちになり、@新谷はビクリと震えて気圧された。\
` All she did was stand... but it almost felt like Shintani was being looked down on by a giant. `@`Shintani was overwhelmed and started to tremble.`\
cl c,0
mld c,RUN_D1,80

;「やめましょうか、もう茶番は。」@
`"Let's cut the nonsense."`@
ld r,NAF_D4a,24
;ld r,NAF_D4a,80

;「………茶番って、……どういう意味かしら……。」\
`"....Nonsense?... What do you mean....?"`\
mcl c,0
ld l,RUN_D5,24

;「くすくす、くすくすくすくす……。@わかっているくせに……。」\
`"Hehe, hehehehe.... `@`I already know..."`\
;　少女は笑う。@
`The girl laughed.`@
br
;　わかっているくせにと、笑う。@
` She laughed because she knew.`@
br
;　もう私の正体がわかっているくせにと、笑う……。\
` She laughed because she already knew what I had done...`\
ld r,NAF_D6a,80

;「…………そうね。@……やっぱり、……そうなのね……。」@
`"......Yeah.`@`... you do... I thought so...."`@
ld l,RUN_D1,80

;「くすくすくすくす………。」\
`"Hehehehe...."`\
ld r,NAF_D7a,80

;「貴方が噂の、………“美術室のルノワール”なのね………。」@
`"You are... 'Renoir of the Art Room' from the rumor, aren't you.....?"`@
br
;　精一杯強がって、そう口にするだけでも、新谷の全身には汗の玉が次から次へと浮かび上がった。\
` She spoke with all the courage she could muster, but in reality, Shintani's body was covered in beads of sweat.`\
bg black,23
bg bijutu_02,23
ld r,RUN_D2,22
ld r,RUN_D1,80

;「ご明察のとおり。@……学校妖怪序列第６位。@美術室のルノワールとは、私のこと。」@
`"How perceptive of you.`@`... Yes, I am the 6th Ranked among the School Youkai. `@`Renoir of the Art Room."`@
br
;　とうとう、……少女は名乗る。@
` At last... the girl gave her name.`@
;　人ならざる者だと、自ら名乗る。\
` An inhuman being willingly gave its name.`\
bg black,22
fede 1,1000
E_B

;　しかし不思議なもので、そうだと名乗られた方が、わずかに恐怖は和らいだ。@
` But, oddly enough, by hearing her name the fear that Shintani felt slightly lessened.
br
;　……新谷は目の前の存在を認め、……覚悟を決める。\
` ...By knowing who was standing in front of her... she gained the ability to prepare herself for what was coming.`\
bg bijutu_06,22

;ld l,NAF_D7a,23
ld l,NAF_D6a,23

;「自己紹介をありがとう。@なら私もしなくっちゃ。@……美術部顧問。@美術室の管理責任者の、新谷ナフミよ。」@
`"Thank you for your self-introduction. `@`I suppose I should do the same.`@`... I am the Advisor of the Art Club. `@`As well as the Manager of the Art Room. Nafumi Shintani."`@
br
;　声の震えが少しずつ治まる。\
` The trembling in her voice had lessened a bit.`\
;　人は、相手が何者かを量りかねている時が一番恐ろしい。@
` The most frightening thing for a person to face is something that can't gauge the danger of.`@
;　たとえ人ならざる者であったとしても、……正体がわかれば、腹も括れる。@
` Even if she is facing an inhuman monster.... as long as she knows what she's facing, she can brace herself for the worst.`@
br
;　玉のような汗で顔はびっしょりだが、……それでも、恐怖心は抑えられつつあった。\
` Her face was drenched with droplets of sweat... but she was still holding her fear back.`\
textoff

fede 0,1000
E_A

ld l,NAF_D7a,80

bgm1 13

;「……唐突に現れて、私に何の御用なのかしら？」\
`"...To suddenly appear before me like this, what business do you have with me?"`\
ld r,RUN_D5,80

;「バカなことを聞く女ね。@妖怪が人間を相手にして、考えることなんて一つしかないのに。@くすくすくす……。」\
`"You sure ask some stupid questions. `@`There's really only one reason for a youkai to appear before a human. `@`hehehe...."`\
ld l,NAF_D6a,80

;「怪談が伝えるとおりなら。@……私を絵の中に引き摺り込んでしまおうと言うのかしら？」@
`"Going by the ghost story.... `@`You must be here to drag me into a painting."`@
ld r,RUN_D2,80

;「それがルノワールの狩り。@絵の中は私の口の中。@永遠にその魂は、私の舌の上で転がり続けるの。」\
`"That is how Renoir hunts. `@`These paintings are my mouth. `@`And the souls that I've swallowed are endlessly tossed about on my tongue."`\
ld l,NAF_D2,80

;「悪いけれど。@そうそう簡単に貴方の思い通りにはならないわよ？@　……だって。@貴方にはルールがあるんでしょう？」@
`"Sorry. `@`But I don't intend to be eaten by you so easily.`@`... After all. `@`Even you have rules you have to abide by, right?"`@
ld r,RUN_D1,80

;「うふふふふふふふふふ……。」\
`"Ufufufufufufu...."`\
bg black,22

;ld l,NAF_D6,80

;「ルノワールに絵筆を借りてはいけない。@……さっきの鉛筆はそのつもりだったんでしょう？」@
`"You can't let Renoir lend you a paintbrush.`@`... Isn't that what you were trying to do by lending me a pencil earlier?"`@
;ld r,RUN_D5,80

;「良い勘をしていたわね。@受け取っていれば、今頃、絵の中の世界だったのに。@……くすくすくす。」\
`"Not bad. `@`You're right, if you had taken that pencil, right about now you would be inside a painting.`@`... Hehehe."`\
;ld l,NAF_D5,80

;「そして、あなたの問い掛けに嘘を吐いてもならない。@……言いたくないことなら黙秘すればいいんだし。@嘘にならない範囲で言い回すことだって難しいことじゃない。@それを守ることも簡単だわ。」@
`"Also, I'm not supposed to lie when answering your questions.`@`... If there's something that I don't want to answer though, I can just stay silent. `@`It's not that hard to not lie if I look at it like that. `@`It's a pretty easy rule to follow, really."`@
;ld r,RUN_D1,80

;「ふふふふふ……。」\
`"Fufufufu...."`\

;bg black,22
bg kaiga_02,22

;「となると。@……私をどうにかしようとしたら、貴方には１つしか方法がない。」\
`"And thus.... `@`There is only one more way for you to manage to take me."`\

locate 0,5

;“ルノワールは美術室に掛けられた絵を指して、作者が誰かを尋ねてくる。@その画家の名を正確に答えなければいけない。”\
`'If Renoir points to one of the pictures in the art room and asks you who made it, `@`you have to answer the name of the artist correctly.'`\
bg black,23
bg kaiga_01,0
ld l,RUN_D2,23
ld l,RUN_D3,80

;「そういうことだわ。@……うふふふふふ。@あなたは、これほどたくさん掛けられた絵画の作者を、@澱みなく正確に答えることが出来るかしら？」\
`"You're right.`@`... Ufufufu. `@`But, with this many pictures on the walls, `@`will you really be able to name the artist for all of them?"`\
ld r,NAF_D2,24

se1v 2,30
wait 1000

ld r,NAF_D6,80

;「私を誰だと思っているの？@　美術部顧問の新谷ナフミよ？@　その挑戦、受けてあげようじゃない。」\
`"Who do you take me for? `@`I'm the advisor of the art club, Nafumi Shintani. `@`Of course I'm up to that challenge."`\
ld l,RUN_D5,80

;「くすくす。@素敵だわ。@……なら、決めようじゃない。@この美術室の本当の主は、私なのか、あなたなのかね。」@
`"Hehe. `@`Perfect.`@`... Let's decide once and for all then. `@`Who is the true master of the art room, me or you?"`@
br
;　……ようやく、新谷は何かを理解する。\
` ...Shintani finally understood.`\
;　さっき自分を、人間ではなく、女王蜂に例えた。@
` Earlier she compared herself to a queen bee.`@
;　女王に蜜を献上する美しく幼い働き蜂たちが集う、蜂の巣だとこの学校を例えた。@
` And this school that the beautiful little bees gather in to bring her honey, she compared it to a beehive.`@
br
;　……なら、この学校は女王蜂にとって宮殿であり、その主は自分なのだ。\
` ...Then, as the queen bee, this school would be a palace, and she was its master.`\
ld r,NAF_D5,80

;「面白くないわけね。@この美術室の主を名乗る妖怪としては。」@
`"As a youkai who calls itself the master of the art room, `@`you're pretty boring."`@
ld l,RUN_D3,80

;「そういうことよ。@……人間が、昼間の学校でお勉強をしているだけなら私たちはどうでもいい。@でも、……夜の領域にまで踏み入ってくるなら、見過ごすわけにはいかないの。」\
`"That's just it.`@`... We couldn't care less if you humans use this school to study during the day. `@`But... we're not about to let any of you trespass on our nighttime domain."`\
bg black,22

;　そういうことだ。@
` Exactly.`@
br
;　……私が女王蜂を自覚した時点で、私は“彼ら”の領域に足を踏み入れていたのだ。\
` ...As a queen bee I have set foot into 'their' domain.`\
;　そうとも、夜の美術室は私の世界。@
` And the art room at night is my world.`@
br
;　学校の怪談風情に、譲り渡したりはしない……。\
` I won't hand it over to the likes of some ghost story...`\
ld_p RUN_D1
lsp2 4,$ld_pass,130,450,-200,200,0
lsp2 5,$ld_pass2,130,450,-200,200,0
print 22

;　美術室の妖怪、ルノワールと。@
` Renoir, the youkai of the art room.`@
br

ld_p NAF_D6
lsp2 2,$ld_pass,480,480,200,200,0
lsp2 3,$ld_pass2,480,480,200,200,0
print 22

;　美術室の女王蜂、新谷ナフミと。@
` And Nafumi Shintani, the queen bee of the art room.`@
br
;　両者が対峙し、睨み合い、……乾いた空気に火薬の臭いを香らせる。\
` They stood face to face, glaring into each other's eyes... The dry air between them smelled like gunpowder.`\
csp2 -1
print 0
bg black,23
bg bijutu_07,23

me1v 16,50

;　新谷は、ごくりと喉を鳴らしてから、ぐるりと美術室内の絵画を見渡す。@
` Shintani gulped and looked around at the artworks surrounding her.`@
br
;　……大丈夫。@どれも知ってる。@知っているはず……。\
` ...It'll be fine. `@`I know all of these. `@`I should know all of them...`\
bg black,23
bg bijutu_02,0
ld c,RUN_D8,23

;　ルノワールは私の瞳と絵画の一つ一つを見比べる。@
` Renoir examined my eyes as I looked at the pictures.`@
;　どの絵画に自信がないのか、私の瞳の奥をうかがうかのように……。@
` Carefully watching for one I looked uncertain about...`@
;　そして、一枚の絵画の前で歩みを止める。\
` And then, he stopped in front of a painting.`\
bg black,23
bg kaiga_02,23

;　それは一般的な感覚で言えば、とても不気味な絵画。@
` Overall it was a very eerie painting.`@
;　……裸の男が、子供を頭から喰らっているという、おぞましいもの。@
` It was horrible scene of a naked man eating off the head of a child.`@
;　美術室を訪れる子供たちが、真っ先に目を反らす絵画だ。\
` Nearly all of the kids who come to the art room will avert their eyes from it at first.`\
;「恐ろしい絵よね。@……将来、自分の子供に殺されるという予言に取り憑かれた男が、@５人もの子供を次々に食い殺す。」@
`"Frightening, isn't it?`@`... Obsessed with defying the prophecy that he would be killed by one of his own children, `@`this man ate each one of them, one after another."`@
;「………『我が子を食らうサトゥルヌス』ね。」\
`"....'Saturn Devouring His Son'."`\
;　額縁の下には、『我が子を食らうサトゥルヌス』という題名が記されているが、@作者の名はない。@
` The name of the painting, 'Saturn Devouring His Son', was written beneath the frame, `@`but the name of the artist wasn't.`@
br
;　……前任者の方針なのかどうかは知らないが、@美術室の絵画には皆、題名は記されていても作者の名は記されていないのだ。\
` ...She's not sure what reason the previous art teacher had for doing so, `@`but even though every picture hanging in the art room was labeled with its title, the artists' names were all left out.`\
bg black,22
bg bijutu_03,22
ld r,RUN_D7,24
ld r,RUN_D6,80

;「では、………答えてもらおうかしら。@この絵の作者の名前は？」\
"So... can you tell me? `@`Who did this painting?"`\
me2v 17,50

;　……さぁ、来た。@
` ....Okay, there's the question.`@
br
;　これが美術のテストか何かだったら、新谷は冷静にその答えを記憶から引き出し、鉛筆でそれを記せるだろう。@
` If this was just some art test or something Shintani would just calmly pull the answer from her memory and jot it down with her pencil.`@
;　しかし、……間違えたら殺されてしまうかもしれないというプレッシャーが、@思考を鈍らせる……。\
` But... if she gets the question wrong now, it could mean her death. `@`That pressure made it hard for her to think...`\
ld l,NAF_D2,23
ld l,NAF_D6a,80

;「………ゴヤ、……ね。」@
`".....It's... Goya."`@
ld r,RUN_D1,80

;「正確にお願いできるかしら？」@
`"Can you tell me the full name?"`@
ld l,NAF_D4a,80

;「……フランシスコ・デ・ゴヤよ。@……如何かしら……？」\
`"...Francisco de Goya.`@`... Right....?"`\
;　正解のはずだ。@間違ってるわけがない。@
` That should be right. `@`It has to be.`@
br
;　……なら、正解と即座に答えてくれればいいのに、@……ルノワールはもったいぶるように含み笑う。\
` ...She gave the answer quickly and correctly.`@`... So why was Renoir giggling like she had gotten it wrong.`\
ld r,RUN_D5,80

;「……くすくす。@そんなにも自信がないのかしら？」@
`"...Hehehe. `@`Do you really have so little confidence?"`@
ld l,NAF_D7a,80

;「この歳になって、美術のテストを受けることになるとは、思わなかったからね。@……それで？@　正解なの？@　どうなの？！」\
`"I wasn't expecting to be taking an art test at this age.`@`... So? `@`Was I correct? `@`What's the answer?!"`\
ld r,RUN_D3,80

;「あなたはテストの時、生徒が一問を解く毎に採点をしているの？」@
`"When taking a test don't the students have to wait until the end to figure out what they got right?"`@
br
;　テストを終えるまで、正解不正解は言わないつもりらしい。\
` So, apparently she didn't intend to tell the results until the test is finished.`\
;　しかし、一問でも間違えれば向こうの勝ちなのだから、テストを続行する理由がない。@
` But, if she gets even one question wrong she'll fail, so there would be no reason to continue the test anyway.`@
br
;　次の問題へ進むということは、正解していると考えても良いだろう……。\
` In that case, it wouldn't be wrong to assume that moving on to the next question means that she got the previous one right...`\
bg black,23
bg kaiga_02,23

;「なら、これは？」@
`"Well, what about this one?"`@
;「……ピカソよ。@……パブロ・ピカソ。」\
`"...Picasso.`@`... Pablo Picasso."`\
;　彼女が指したのは、『ゲルニカ』だった。@
` The picture she was pointing at was called 'Guernica'.`@
br
;　スペイン内戦の最中、ナチスによって無差別空爆を受けた都市ゲルニカを描いた大作。\
` It's an epic work created during the Spanish civil war in response to the Nazi's indiscriminate bombing of the city of Guernica.`\
;　死んだ子を抱き泣き叫ぶ母親、天を仰いで絶望する女、狂ったようにいななく不気味な馬……。@
` There's a mother crying out in grief at the loss of her child, a woman staring up at the sky in despair, and a ghastly horse neighing out in mad confusion....`@
br
;　戦争の悲惨さを描いた力作だが、@そんな背景を理解できない一般生徒にとっては、奇怪で薄気味悪い抽象画でしかないだろう。\
` It's supposed to be masterpiece that tells of the horrors of war, `@`but unfortunately most of the students that see it don't know the context, so they just think it's a bizarre abstract painting.`\
;「じゃあ、これは？@………『残酷の四段階』。」@
`"Okay, and this one?`@`....`The Four Stages of Cruelty'."`@
br
;　それは題名どおりの４枚の連続作品だ。\
` As the name suggests, it's a series of four prints.`\
;　残忍な性格の主人公の少年時代から末路までを描いたもので、@最後の１枚では、絞首刑で殺された後、@そのまま解剖学の授業に回されて腹を割かれるという、@ショッキングなもので締めくくられている。\
` They follow the life of a one cruel man from the time he was a boy up until his death. `@`And, as a shocking conclusion, `@`In the final print he has been hanged to death, `@`and his body is disected during an anatomy class.`\
bg black,22

;　残忍なる者には、残忍なる結末が待つ。@
` A cruel person will meet a cruel end.`@
br
;　そういう教育的なメッセージが込められているのだが、@それを理解できずに見せ付けられる子供たちにとっては、これはグロテスクな作品以上でも以下でもない。\
` That is the message that the series conveys. `@`But the kids who see this one can't understand that, and more or less think that it's just a gory picture.`\
bg kaiga_01,0
ld r,NAF_D2,24
ld r,NAF_D6,80

;「……趣味のいい絵ばかり選ぶのね。」@
`"...You choose such great pictures."`@

ld l,RUN_D7,23
ld l,RUN_D1,80

;「ありがとう。@私の気に入っている絵ばかりなの。」@
`"Thank you. `@`I'm only choosing the ones I like."`@
br
;　ルノワールはにやりと笑う。\
` Renoir grinned.`\
;　……ルノワールはその祟りで、犠牲者を絵の中に引き摺り込むという。@
` ...Renoir's curse causes the victim to be dragged into the painting.`@
br
;　愉快な絵なら、それは笑い事で済むが、@……先ほどから出題されるものは、どれも、実体験は遠慮したいものばかりだ。\
` Getting dragged into a pleasant or peaceful painting would just be laughable.`@`... So naturally, every picture that Renoir chooses is going to contain something that she wants to happen.`\
ld l,RUN_D3,80

;「それで？@　この作品の作者は？」@
`"And? `@`Who did this one?"`@
ld r,NAF_D5,80

;「……ホガース。@……ウィリアム・ホガースよ。」\
`"...Hogarth.`@`... William Hogarth."`\
cl l,24

;「ではこれは？@　そしてあれは？@　そしてそれは？」\
`"What about this one? `@`And that one? `@`And that one?"`\

cl r,24

;　新谷の博識に、ルノワールは焦りを覚えたに違いない。@
` Renoir was obviously growing impatient with Shintani's extensive knowledge.`@
br
;　舌打ちしながら、次々に出題し、そのペースを速めていく。@
` She clicked her tongue and sped up the pace, choosing one after another.`@
br
;　新谷も負けてはいない。@次々に作者名を当て、勢いに乗っていく。\
` Shintani wasn't going to lose. `@`She gave the names just as quickly, using Renoir's impatience against her.`\
bg black,22

fede 1,1000
E_B

bg bijutu_03,0
ld c,RUN_D9,22

;　……やがて、新谷は気付く。@
` ...Eventually, Shintani realized something.`@
br
;　彼女が正解を重ねれば重ねるほどに、……ルノワールが呼吸を荒げていくのだ。\
` The more questions she answered correctly... the quicker Renoir's breathing became.`\
;　気付けば、まるで全力疾走を終えたかのように、ぜいぜいと肩で息をしているのだ。@
` If she looked closesly she could see that Renoir was breathing so heavily it was almost like she had just finished running a marathon.`@
br
;　……どうやら、正解をされればされるほどに、妖怪の存在が追い詰められていくらしい。\
` ...It appears that the more question she gets right, the more cornered the youkai becomes.`\
;　なるほど、納得する。@
` I see, I understand.`@
br
;　これは私にとってだけの、一方的な戦いではないのだ。\
` This isn't just a one-sided fight.`\
;　私が負ければ、絵の中に引き摺り込まれて殺されてしまうように。@
` If I lose I will be pulled into a painting and killed.`@
br
;　彼女も負ければ、その姿を二度と現すことが出来なくなるに違いない。\
` But if she loses, she will never again be able to show herself here.`\
ld c,RUN_D6a,80

;「………やるわね……。@……ぜぇ………ぜぇ………。」\
`".....Not bad....`@`...Haa........ haa....."`\
;＜ルノワ

ld r,NAF_D6,24
ld r,NAF_D5,80

;「本当にバカな子だわ。@相手を選ばないからそういうことになるのよ。」@
`"You really are a foolish child. `@`This is what you get for not choosing your enemies carefully."`@
cl c,0
ld l,RUN_D7a,24

;「……そのようね。@……あんたを、どうやら侮っていたみたい……。」\
`"....You're right.`@`...It seems that I've underestimated you..."`\
ld r,NAF_D2,80

;「仮にも美術部顧問なのよ？@　この部屋に存在する絵画で、私に答えられないものは存在しないわ。」@
`"Did you think me saying I was the advisor of the art club was a joke? `@`There's not a picture in here that I can't name the artist of."`@
br
;　きっぱりと断言する。\
` Shintani asserted that she had the upper hand.`\
;　精神的優位に立ち、記憶の引き出しが自在に開けられるようになった彼女には、@もはや恐れるものなど存在しなかった。\
` With her mental superiority she could freely pull the answer to any of Renoir's question out of her memory. `@`There was no longer anything she was afraid of.`\
ld l,RUN_D6a,80

;「………ぜぇ………ぜぇ……。」@
`".....Haa...... haa......"`@
ld r,NAF_D6,80

;「もうおしまいかしら？@　それとも少し休憩しないと、出題も出来ないくらいに疲れちゃったかしら？」\
`"Are we finished already? `@`Or are you so worn out that you need to take a break?"`\
ld l,RUN_D7a,80

;「……そうね。@お言葉に甘えようかしら……。」@
`"...Yeah. `@`It looks like I may need to do just that..."`@
br
;　汗を浮かせながらも、わずかに微笑み、ルノワールは再び、モデルの椅子に腰を下ろす。\
` Dripping with sweat, and slightly smiling, Renoir once sat down on the modeling chair.`\
bg black,22

fede 0,1000
E_A

bg kaiga_02,22

bgm1 14

;「………ねぇ、先生。@さっきの質問なんだけど。@……やっぱり答えてはくれないのかしら？」@
`"....Hey, sensei. `@`What about my question from earlier?`@`... Are you not going to give me an answer?"`@
;「質問？@　全て答えているつもりだけれど？」\
`"Question? `@`Didn't I answer all of them?"`\
;「……この美術室で。@……誰かの裸を描いたことは、……本当にないの……？」@
`"...In this art room....`@`Have you really never... done a nude drawing of something in here....?"`@
;「………………。」\
`"........."`\
;　答えるつもりはなかった。@
` She had no intention of answering.`@
br
;　“美術室のルノワール”のルールでは、その問い掛けに嘘を吐いてはならないことになっている。\
` According the rules of 'Renoir of the Art Room' she couldn't lie while answering that question.`\
;　絵画の作者名については解答を求められるが、@それ以外については、嘘さえ吐かなければ回答の義務はないのだ。@
` If Renoir asked for the name of an artist she had to answer, `@`but any question other than that she was not obligated to answer in any way.`@
br
;　だからこそ、新谷は余裕の表情で、その問いに無言を返すのだ。\
` And so Shintani calmly replied to that question with silence.`\
ld r,NAF_D5,24

;「もう、何を企もうとも無駄よ。@この美術室の主は私。@……でも、真夜中の美術室に妖怪が住み着いてるのを許せないほど、私も心が狭くないつもりよ？@　これくらいにして、すごすごと引き上げたら？@　私の前に二度と姿を現わさないと誓えるなら、@私が下校した後の無人の美術室は、あなたの自由にすればいい。@……素敵なルームシェアリングでしょう？」\
`"Whatever scheme you're trying pull, it's not going to work. `@`I am the master of this srt room.`@`... But do you really rhinkg that I'm so close-minded as to not let a youkai take up residence in it during the middle of the night? `@`How's this for a deal? `@`If you vow to never show yourself before me again, `@`then after school is over and I've left the art room, you're free to do as you please.`@`... We'll be like the perfect roommates."`\
bg black,22
bg bijutu_04,0
ld c,RUN_D2,22
ld c,RUN_D6,80

;「………私の質問への返事はなし？」@
`"....You're not going to answer my question?"`@
;「私がヌード画を描いたことがあるか否かなんて、どうでもいいことでしょう？@　下らない。」\
`"Who cares if I've done a nude drawing or not? `@`It doesn't matter."`\
ld c,RUN_D5,80

;「ふふふふふ……。@本当に下らない、どうでもいいことなのかしら…？@　……どうでもいいことの割にはあなた、……動揺しているんじゃない……？」\
`"Fufufufu... `@`Are you sure it really doesn't matter...? `@`...You seem... pretty shaken up over something that apparently doesn't matter..."`\
;「………………………。」@
`"............"`@
br
;　追い詰められているのはルノワールのはずなのに。@
` Renoir should be the one who's corner right now.`@
;　……新谷は心の中を見透かされているような不気味さを味わう。\
` ...So why was Shintani the one who felt like she was being seen through.`\
ld c,RUN_D3,80

;「それじゃあ、質問を変えるわね。@きっとこれにも答えてはくれないんでしょうけど。」@
`"Alright then, I'll change the question. `@`Even though you probably won't answer this one either."`@
;「……もちろん、答えないわよ。@だから言うだけ無駄よ。」\
`"...Of course I won't. `@`After all, there's no reason to."`\
;ld c,RUN_D1,80

bg black,22

;「裕貴くんが死んだ時、先生は一体どこで何をしてたの…？」\
`"Where were you when Yuuki died...?"`\
;mbg red1,1
;mcbg 22

;「………………………。」@
`"............"`@
br
;　新谷のこめかみが引き攣った。@
` Pressure spread through Shintani's temples.`@
;　眼球の奥が、ちりっと痛み、その焦点がわずかに歪んだ。\
` A pain hit the back of her eyeballs, and blurred her vision a little.`\
bg bijutu_06,22
;ld c,RUN_D5,80

;「くすくすくすくす……。@やっぱり答えてはもらえないかしら？@　じゃあこちらで勝手に想像するしかないわね。@……もう家に帰っていたのかしら？@　それとも職員室でお仕事かしら？@　それとももしかして………。@……まさか、この美術室に…？」@
`"Hehehehehe.... `@`You're not going to answer are you? `@`Well then, guess I'm just gonna have to make my best guess.`@`... Were you already safe at home? `@`Or maybe you were still doing work in the staff room? `@`Or maybe......`@`...Maybe you were in this very art room...?"`@
;「……………………。」\
`".........."\
ld r,RUN_D1,22
ld r,RUN_D5,80

;「先生はこの美術室にいたんじゃない？@　野田裕貴くんと一緒に。」@
`"Were you here in this art room, sensei? `@`Were you with Yuuki when he died?"`@
br
;　その瞬間、フラッシュバックのようにあの日の出来事が思い出される……。\
` For an instant she had a flashback like memory to that day...`\
bg white,28
bg black,8
mono 1
bg bijutu_03,0
ld c,NOD_D6,22

me1v 16,50

;　最初に脳裏に映像として浮かんだのは右手だった。@
` The first image that appeared in her mind was that of a right hand.`@
;　突き出された自分の右手。@その手が裕貴の背中を押す。\
` Her right hand to be specific. `@`Reaching out and pushing on Yuuki's back.`\
;se1 10
cl c,25
;se2 13
quakey 2,200

;　テーブルの下に勢い良く倒れ込む裕貴。@
` Yuuki falling underneath the table.`@
br
;　ぐらりと大きく揺れるテーブルの支柱。@
` The legs shaking beneath the table.`@
br
;　彼に覆いかぶさる様に倒れていく石膏像。\
` The plaster figure falling down onto him.`\
bg black,29
mono 0

;se1v 13,100
;wait 50
;se2v 13,100
;quake 5,500
;wait 500
bg blood_1aR,2

;　………広がっていく赤い染み………。@
` .....An expanding red stain....`@
br
;　その真っ赤な染みの上で、まるで眠っているような野田裕貴……。@
` And lying on that stain, almost as if sleeping, Yuuki Noda...`@
br
;　それらが質の悪いスライドショーのように浮かび上がる。\
` It played out in her memory like a bad quality slideshow.`\
bg black,22
mono 1
bg bijutu_03,22


;「………どうして。」@
`"....Why?"`@
br
;　言葉が思わず漏れる。\
` The words unconsciously escaped her mouth.`\

;「…………どうして、……あんなことに………。」@
`".....Why... Why did you....."`@
br
;　裕貴くん、と呻くように彼の名を呼ぶ。\
` She called out Yuuki's name with a groan.`\
;　……そんなつもりはなかった。@
` ....I didn't mean for that to happen.`@
;　あの日私が彼に右手を伸ばしたのは、突き飛ばすためなんかじゃない。@
` When I reached out my hand, I didn't mean to shove you away.`@
br
;　むしろ逆。@
` It was the opposite.`@
;　彼を手放したくなかったからだ。@それなのに、どうして………。\
` I didn't want to let you go. `@`Why? Why did that happen....?`\

bg black,22
mono 0

me2v 28,50

;　その、心のわずかの隙間から、……ぬるりとルノワールが入り込む。\
` Renoir slipped in.... through that small gap in her heart.`\
;　くす、くすくすくすくすくす……。@
` Hehe, hehehehe....`@
;　いいわ、すごくいい。@
` Good, very good.`@
;　その身勝手な後悔、独りよがりの罪悪感。@
` Selfish regret, conceited guilt.`@
br
;　……素敵よ、今のあなたの魂。@
` ....Your soul is so wonderful right now.`@
;　どんどん素敵な味付けになって、本当にとっても美味しそう。@
` It's getting seasoned with such a delightful flavor, and it looks so tasty.`@
br
;　くすくす、くすくすくすくすくすくすくすくす…！！\
` Hehehe, hehehehehehehe...!!`\
bg bijutu_03,0
ld c,RUN_D10,22

;　ルノワールがパチリと指を鳴らす。@
` Suddenly, Renoir snapped her fingers.`@
br
;　すると机の引き出しがガタガタッと手品のようにひとりでに開いた。\
` And like magic the desk's drawer opened on its on.`\
E_A

se1 1010
bg white,23
se2 1010
bg black,23
se3 1010
bg white,23
se1 1010
bg black,23
se2 1010
bg white,23

me1v 17,50

;　あっと声を上げる間もなく、その中に入っていた大量の紙が生き物の様に舞い上がる。@
` Before Shintani could even say a word, dozens of papers came dancing out of that drawer as if they were alive.`@
br
;　美術室を覆い隠すかのように散らばるたくさんの紙。@紙、紙、紙……。\
` Papers scattered about everywhere, covering the art room. `@`Papers, papers, papers....`\
;se1 34
se1 1010
bg aka1,23

bgm1 30

;　それは絵だった。@
` They were drawings.`@
br
;　裸の少年が描かれた無数のスケッチだった。\
` Countless sketches of naked boys.`\
;　眠っている少年、縛られている少年。@
` Sleeping boys, bound boys.`@
br
;　ペンティングナイフによって赤い筋を浮かび上がらせる少年。@
` Boys covered in red steaks from a palette knife.`@
br
;　火のついた煙草を押し付けられ、熱さと痛みに必死に耐える少年、蹂躙され泣きわめく少年……。\
` Boys frantically enduring the pain and heat of being burned by a cigarette. Boys crying out from being trampled on....`\
;　余りにも背徳的なそのスケッチは、@唖然とする新谷の目の前に、スライドショーの様に次々と突きつけられる。\
` These excessively immoral sketches, `@`flew one after another past a Shintani's dumbfounded face like a slideshow.`\
bg black,23
bg bijutu_02,23

mld c,RUN_D1,6
lsp bgsp2,":a;bmp\background\efe\black1.bmp",0,0,255
print 6

;　ゆらりと……、ルノワールは立ち上がる。@
` Slowly... Renoir stood up.`@
;　その表情は暗く陰り、見えない。@
` Her face was shrouded in darkness, her expression could not be seen.`@
br
;　しかし、不気味でおぞましい、赤黒い妖気のようなものが全身から立ち上っていた。\
` But, an oddly horrifying red and black energy surrounded her whole body.`\
csp -1
print 0
mcl c,0
se1v 1010,30
bg black,23
se2v 1010,50
bg white,23
se3 1010
bg aka3,23

;　舞い飛ぶ無数のスケッチの中から数枚が飛び出て、新谷の眼前に突き付けられる。@
` Among the countless sketches dancing around the room, there were a few pages that stood out to Shintani as her eyes passed over them.`@
br
;　それはあの日、最後に描いた野田裕貴のスケッチだった。@
` They were the unfinished sketches of Yuuki Noda from that day.`@
;　傷だらけの身体。@やつれた顔。@憂いを帯び、必死に何かに耐えるようなその表情……。\
` His body covered in cuts and bruises. `@`His face looking worn out. `@`His expression of desperate perseverance, with a hint of sadness...`\
ld c,RUN_D1,22
ld c,RUN_D10,80
;「ふふふふふ、……うふふふふふふふふふ……。@さぁ、これが、美術室のルノワールの最後の問題。@……さぁ、新谷先生、答えてちょうだい。@……この絵を描いたのは、一体、だぁれ……？」\
`"Fufufufu... Ufufufufufufu.... `@`Now, this is the final question of Renoir of the Art Room.`@`... Answer this for me, Shintani-sensei.`@`... Who drew all these pictures...?"`\
bg black,22
mono 1
bg e020,22

;　これらのスケッチは、……証だ。@
` These sketches are... proof.`@
br
;　新谷ナフミが、野田裕貴の白くて幼い体を……、欲望の限り陵辱したことを示す、証だ。\
` Indisputable proof.... that Nafumi Shintani lustfully assaulted the young, pale body of Yuuki Noda.`\
;　そしてそれを、認めなければならない。@
` And now she had to admit it.`@
br
;　ルノワールが指した絵の作者を、偽りなく答えなければならない。\
` She had to truthfully answer the name of the artist of the pictures that Renoir was pointing to.`\
bg black,22
locate 0,5

;「さぁ、教えてちょうだい、新谷先生っ…！！@　この絵の作者は誰かしら…！！」\
`"Come on, answer me, Shintani-sensei...!! `@`Who drew these pictures...?!"`\
me2v 28,50

mono 2
print 0
bg Different_spiral_1b,22

;　認めろということ。@
` And by admitting to them...`@
br
;　スケッチには日付と時間までも記されている。@
` The date and time are written on those sketches.`@
;　それを認めれば、野田裕貴が死ぬ直前に、誰が一緒にいて何をしていたのかをも認めることになる。\
` By admitting to them, she is admitting what she was doing and who she was with just before the death of Yuuki Noda.`\
;　あれは事故ということになったんだ。@それもただの事故じゃない。@
` It was an accident. `@`But it wasn't just any old accident.`@
br
;　彼がひとりで美術室に入り込んで、ひとりで事故に遭ったという、単独事故ということに…！！\
` He went into the art room alone, and had a horrible accident all by himself...!!`\
;　なのにそれを認めろと？@　嫌だ、嫌だ、冗談じゃないッ！\
` What was there for her to admit? `@`No, no, this isn't funny!`\
ld c,NAF_D9a,22

;　美術室は私の巣！@　ここは女王蜂の玉座の間！@
` The art room is my hive! `@`This is the royal throne of the queen bee!`@
br
;　私はここに美しい、蜜の滴る子たちを連れ込んで、その白い肌を存分に貪るの…！！\
` This is where all the beautiful little bees bring me their honey, and I can covet their pale white skin as much as I want...!!`\
;　野田裕貴の件が公になれば、……私の理想郷が壊れてしまう。@
` If the case of Yuuki Noda's death goes public... my paradise will be ruined.`@
br
;　私の巣が、壊されてしまう……！！\
` My hive will be broken....!!`\
bg black,22
mono 0
bg bijutu_03,0
ld c,RUN_D5,22
ld c,RUN_D10,80

;「うふふふふふッ、うっふふふふふふふふふふふ！！@　さぁさぁ！！@　答えてちょうだい、教えてちょうだい！！@　これらの絵の作者は誰だと言うのかしら…？！」\
"Ufufufufufu! Ufufufufufufufufu!! `@`Come on!! `@`Answer me, tell me!! `@`Tell me who drew these pictures...!!"`\
;「……………………。@/
`".........`@/
E_A
;……新谷ナフミ。@……私よ。」\
`....Nafumi Shintani.`@`.... I did."`\
se1v 1006,50
mbg white,1
ld c,RUN_D6a,0
mcbg 22

;　新谷が、冷酷にそう答えた時。@……びしりとガラスにひびが入るような音がして、@……ルノワールの動きが止まった。\
` Shintani replied coldly.`@`... and suddenly the sound of glass being broken echoed through the room.`@`... and Renoir stopped moving.`\
me1v 16,50

;　……ルノワールの胸に、大きなひびが入っているのがわかる。@
` ...A huge crack streaked across Renoir's chest.`@
br
;　そして、ぶるりと震えた後、……それは木っ端微塵になって砕け散った。\
` And then, after suddenly shaking... she broke into a million pieces.`\
E_A
se1v 1006,100
mbg white,1
lsp bgsp,":a;bmp\background\efe\ware.bmp",0,0
print 1
mcbg 1
csp -1
cl c,0
print 22
bg bijutu_03,22

wait 2000

ld c,HIG_W5a,2

bgm1 27

;■これ以降、立ち絵は彼岸花に。@

;　その後には、……先ほどまでの姿とはまったく異なる、黒髪の女生徒の姿があった。@
` Then... standing there was an entirely different black haired girl.`@
br
;　……なるほど。@どうやらこれが、この妖怪の真の姿らしい。\
` ...I see. `@`This must be the youkai's true form.`\
ld c,HIG_W6,80

;「へ……ぇ……。@……まさか、……堂々と答える……、なんてね………。」\
`"O...h....`@`... I didn't.... think.... you would answer.... so confidently......`\
bg black,24
bg bijutu_04,24
mld c,NAF_D2,6
lsp bgsp2,":a;bmp\background\efe\black1.bmp",0,0,255
print 6
mld c,NAF_D7,80

me1v 17,50

;「そうよ。@その絵は私が描いた。@……だから何……？」@
`"It's true. `@`I drew those pictures.`@`... So what....?"`@
br
;　新谷の表情は、妖怪のルノワールでさえ、@ごくりと唾を飲み込まずにはいられない不気味な迫力を湛えていた。\
` Shintani had such an eerie expression on her face, `@`that even the youkai Renoir had to gulp.`\
mld c,NAF_D5,80

;「ふっふふふふふ。@……そうよ、そういう絵を描くのが、私の趣味なの、欲望なの、願望なの。@ごめんなさいねぇ、そういう人間で……。」\
`"Fufufufufu.`@`... That's right, doing these drawings is my hobby, my desire, my aspiration. `@`Sorry, but that's just who I am..."`\
;　新谷には見えていないだろう。@しかし、ルノワールには見えている。@
` Shintani probably hadn't noticed it, `@`but Renoir had.`@
br
;　自らの邪悪な欲望を明け透けに認めた彼女の全身からは、@妖怪でさえ気圧されるような妖気が噴き出しているのだ。\
` Emanating from the body of this woman who was so bluntly professing her evil desires, `@`was a powerful energy that normally only poured from the body of a youkai.`\
;　それは、新谷ナフミという人間が、人ならざる欲望を持つことを認めたということ。@
` This was because the human Nafumi Shintani was admitting to such an inhuman lust.`@
br
;　即ち、人ならざる者の世界に足を踏み入れていることを認めたということだ。\
` In other words, she was admitting to stepping foot into the world of those that are not human at all.`\
;　……だから今。@新谷ナフミは、人ならざる世界の住人として、ルノワールを威圧しているのだ。@
` ...So now, `@`as a denizen of the inhuman world, Nafumi Shintani was overpowering Renoir.`@
br
;　“美術室のルノワール”などという、か弱い怪談は今日を境に消え去る。\
` Today, the pathetic ghost story of 'Renoir of the Art Room' will cease to exist.`\
;mcl c,0
mld c,NAF_D6,80

;「そうね。@私は今日から、美術室の女王蜂を名乗ろうかしら？@　昼は可憐な教師として。@……そして夜は女王蜂として、この学校という名の巣に君臨するの。@幼く無垢で美しい働き蜂たちは、若き日の一瞬にしか持ち得ない蜜を私に捧げ、楽しませるの。」\
`"Yes. `@`From this day forward I will be known as the Queen Bee of the Art Room. `@`During the daytime as a sweet teacher.... `@`and during the nighttime as a queen bee, I will reign over this hive called a school. `@`And the beautiful, young and pure worker bees will being to me the momentary nectar called youth so that I may satisfy myself with it."`\
mld l,HIG_W5,22
;mld l,HIG_D4,80

;「…………素敵な妖怪だこと。@……教師たる者が生徒を働き蜂呼ばわりだなんて。@野田裕貴くんも、あなたにとってはたくさんの働き蜂の中の１匹でしかなかったの？」\
`"......What a great youkai.`@`... A teacher who denounces her students as nothing more than worker bees. `@`Was Yuuki Noda just be another one of those many bees to you?"`\
mcl c,0
mld r,NAF_D2,23

;「……彼は本当に素敵な蜂だったわ。@彼の蜜は、濃密で鮮烈で、全身が沸き立つほどに甘美だった。@彼は忘れ難い少年よ。@……本当に惜しい子を亡くしたわ。」\
`"...He was such a wonderful bee. `@`His honey was so rich and vivid that its sweetness made my whole body boil. `@`I will never forget him.`@`... With him gone, I've lost such a valuable boy."`\
mld l,HIG_W3,80

;「彼はあなたのことを好きだったわ。@……もちろん、幼い彼にはその感情を自覚することも難しかっただろうけれど。」\
`"He liked you, you know?`@`... Although, being such a young boy, naturally he was unable to realize it for himself."`\
mld r,NAF_D5,80

;「私は知ってたわ。@あの子は私のことが好きだった。@……母性を求める年頃のはずなのに、母親とは違う女性に、なぜか惹かれる甘酸っぱい感情。@それが恋というものだと気付くには、彼はまだまだ幼かったわね。@……でも、それでいいの。@私にとって、恋なんて概念を理解してしまうほどの年齢は、賞味期限切れなのだから。」\
`"I know he did. `@`He liked me.`@`... He was at an age where he should be wanting his mother's affection, but for some reason he was longing for another woman. It was a bittersweet feeling. `@`He was too young too realize that what he felt was love.`@`... But, that was fine. `@`Because I'm too old to feel such young love."`\
;　新谷は挑発的に、小指の先を、淫らにべろりと舐めて見せる……。\
` Shintani provocatively licked the end of her little finger in an obscene manner...`\
csp -1
print 0
mcl a,0
bg black,22

mono 1

bg bijutu_03,0
ld c,NOD_D3,22

;　確かに野田裕貴は魅力的な子だった。@
` Yuuki Noda certainly was a charming young boy.`@
br
;　白く無垢な肌だけではない。@
` And not just because of his pure white skin.`@
;　私への恋心を逆手に取り、獣欲の全てを受け止めさせることが出来た。\
` By falling in love with me he was able to turn the tables and accept all of my lust.`\
;　女王蜂は、かしずかれなくては君臨できない。@
` If no one serves the queen bee she cannot reign.`@
;　女王蜂に心から心酔し、敬服する働き蜂でなくては、仕える資格がないのだ。@
` If a worker bee does not have the admiration and adoration of their queen, they are not qualified to serve.
br
;　野田裕貴はその資格があった。@だから私に仕えることが許された。\
` Yuuki Noda had those qualifications. `@`So I allowed him to serve me.`\
bg black,22

mono 0

bg aka3,22

;　でも、ここは蜂の巣。@無数の働き蜂たちがひしめいている。@
` But this is a bee's hive. `@`And countless worker bees are busting in it.`@
;　私に蜜を運んでくれる働き蜂は、彼だけじゃない。@
` He isn't the only worker bee that brings me his honey.`@
;　彼には私に仕える資格があっただけ。\
` It's just that he was qualified to serve me.`\
bg black,22

;　失った今だから傲慢に言い切ろう。@彼が、最高の美の結晶だったわけじゃない。@
` Now that he is gone I will declare it with great pride. `@`He was not the most beautiful gem around.`@
br
;　彼よりも美しい子は他にもいる。@私に気がある子は他にもいる。\
` There are other kids more beautiful than he was. `@`There are other kids that I'm interested in.`\
bg bijutu_04,22
ld r,HIG_W3,24
ld r,HIG_W4,80

;「……なんて酷い先生なのかしら。@あなたの邪まな欲望を、その身で健気に受け止めてくれたのに。@そんな彼を気の毒に思うどころか、“彼が、最高の美の結晶だったわけじゃない”？」\
`"...You're such an awful teacher. `@`He bravely accepted your wicked desires with his own body. `@`But instead of feeling sorry for him, you say 'he was not the most beautiful gem around'?"`\

ld l,NAF_D6,23
ld l,NAF_D7,80

;「えぇ。@彼は素晴らしかったけれども、最高ではなかったわ。@いやむしろ、その賞味期限は尽き掛けてさえいた。@……あの子は私から逃げようとしたのよ。@私にただ仕えていれば良いものを！」\
`"Yeah. `@`He was great, but he was not the best. `@`Or rather, his usefulness just ran out.`@`... He tried to run away from me. `@`He should have just continued to serve me!"`\
ld r,HIG_W3,80

;「……欲望剥き出しのあんたの戯れに、これ以上、付き合い切れなかったんでしょうよ。」@
`"...He played along with your shameless desires, isn't that enough?"`@
ld l,NAF_D8,80

;「そういうことね。@あの時、あの瞬間、裕貴くんは私に仕える資格を失ったのよ。@……バカな子、そうしなければ、きっと死なずに済んだのに…！」\
`"That's just the thing. `@`At that time, at that moment, he lost the qualifications to serve me.`@`... What a stupid kid, if he hadn't of done that then he wouldn't be dead right now...!"`\
ld r,HIG_D5,80

;「……さんざん慰み者にしておいて、掛ける言葉が“バカな子”なの？」\
`"...You're going to call that boy who you treated so horribly as your plaything a 'stupid kid'?"`\
cl l,0
mld c,NAF_D7,23

;「えぇ、そうよ、バカな子よ。@私のことだけを見て、私のことだけを受け入れるお人形でさえいれば良かったものを…！」\
`"Yes, I will. He was a stupid kid. `@`He should have been a doll. A doll that only I could look at, and only I could play with...!"`\
ld r,HIG_W3,80

;「身勝手、ここに極まれりね。@……あなたに好意を持ち、堪えられなくなる最後の一瞬まで、あなたを受け止めようとその身を捧げ続けた彼に、@……謝りたいという気持ちはわずかほどもないのね？」\
`"You are the epitome of selfishness.`@`... He showed his affection for you and sacrificed his body for your desires until he couldn't take it anymore.`@`... and you're not even the least bit sorry?"`\
mld c,NAF_D8,80


se1 84
;「うふふふふ、うっふっふっふっふ！！@　そんなもの、あるわけがないでしょう！！@　私は女王蜂！@　私に好意を持つ蜂たちにかしずかれ、私は彼らの献上する蜜を楽しむの！@　私こそは美術室の女王！@　私に仕えられただけでも光栄なことなのよ？@　それを投げ出すなんて、身の程知らずの愚か者…！！@　裕貴くんに謝りたいという気持ち？@　そんなもの、これっぽっちもあるわけがない…！！@　だって私は、女王なのだから！！」\
`"Ufufufu, UFUFUFUFU!! `@`Of course I'm not!! `@`I'm the queen bee! `@`The other bees show their affection to me and I will enjoy their honey! `@`I AM the queen of this art room! `@`It should be an honor to serve me! `@`Those who don't feel honored to are fools who need to know their place...!! `@`Am I sorry for Yuuki? `@`Not even in the slightest...!! `@`After all, I am the queen!!"`\
mcl c,0
bg black,22
E_B

;　その時だった。@……美術室に、別の声が響いた。\
` It was at that moment.`@`.... That a different voice echoed through the art room.`\
fede 0,1000
E_A

;「…………ないんだね。@………裕貴くんに、……謝ろうという気は。」@
`".....You really aren't going to.`@`..... apologize..... to Yuuki, are you?"`@
br
;　この美術室に、自分とルノワール以外の誰がいたっけ…？！@
` There's someone else in this room besides me and Renoir...?!`@
;　新谷は驚き、反射的に声がした方を見る。\
` Stunned, Shintani reflexively turned towards where the voice came from.`\
bg bijutu_07,22

bgm1 7

;　そこには、いつの間にか一人の少年が立っていた。@
` A young boy was standing there.`@
br
;　……ソファーで眠っていたはずの、……あの名も知らぬ少年だ。\
` ....It was that nameless boy... who should have been sleeping on the sofa.`\
;「……あ、……ら……。@……目が覚めたの……？」@
`"...H.... uh... `@`.... You're awake....?"`@
;「ないんだね……。@裕貴くんに、謝ろうという気は……。」@
`"You really aren't.... `@`going to apologize to Yuuki, are you....?"`@
br
;　同じ言葉を、もう一度繰り返す。\
` He repeated himself.`\
;　……何なの、この子……。@
` ...What is up with this kid...`@
;　……………………。@
` ..........`@
br
;　私は何故、彼に名前を聞かなかったんだろう……？@
` Why did I ask him his name...?`@
;　いくら、唐突に現れた上玉の獲物とは言え、@名前も聞かずにモデルを頼んでしまったりするだろうか。\
` How many times had she suddenly met such beautiful pray, `@`but hadn't asked their name before asking them to model?`\
bg black,22
mono 1
bg bijutu_01,22

;　新谷は美術室に入って初めて彼を見た時の感覚を思い出そうとする。@
` Shintani can remember the feeling she had when she first entered the art room and saw him.`@
;　だが、それはまるで忘れかけた夢を思い出すかのような曖昧さで、つい先ほどのことのはずなのに、まるで思い出せない。\
` But, the memory's so fuzzy, it's almost like a dream she forgot after waking up. Even though it just happened, she can barely remember it.`\
;　……あの時、自分には、彼の名前を知ろうという考えが全くなかった。@まるでその考えだけを、あらかじめ誰かにごっそりと抜かれたように。@
` ...I never once wondered to myself what his name was. `@`It's almost like someone else took control of her thoughts.`@
br
;　私は一体、何に声を掛けてしまったのだろうか。@誰を描いてしまったのだろうか。\
` Who was I talking to again? `@`Who was I drawing?`\
bg black,22
mono 0
bg kaiga_01,22

;　その姿が、……その後ろの絵画と重なる。@
` The boy's visage... overlapped with that of a painting.`@
br
;　その絵画の名は、『鞭を持つ子供』。@
` Specifically, the painting known as 'Child with a Whip.'`@
;　ルノワールの作品だ。\
` The piece of art by Renoir.`\
;　……描かれている少女は髪が長く、スカートを履いている。@
` ...The girl in that painting has long hair and is wearing a skirt.`@
br
;　少年の髪は短く、スカートではないけれど、………顔が、……目が、……………。\
` This boy's hair is long, he doesn't have a skirt but..... His face... and his eyes......`\
;　……あぁ、今こそずっと覚えていた違和感に気付く。@
` ...Ah, I just realized what felt so out of place.`@
;　私はこの少年の顔をどこかで見たことがあるような気がすると、ずっと思っていたのだ。@
` I feel like I've seen that boy's face somewhere before, that's what has been bugging me.`@
br
;　この少年は………………、\
` This boy is........`\
;■ここで改めてルノワールの立ち絵登場。@

me1v 16,50

ld c,RUN_D2,6

wait 1000

ld c,RUN_D7,80

;「……よく、間違われたんだ。@……僕のことを、女の子って……。」@
`"...People make that mistake a lot.`@`.... Confusing me for a girl...."`@
;＜ルノワール

ld l,HIG_W3,22
;ld l,HIG_D3,80

;「ルノワールの『鞭を持つ子供』は、女の子を描いた絵だとよく間違われるけれど。@本当は少年なのよね。」\
`"People often make the mistake of thinking that Renoir's painting, 'Child with a Whip' is a portrait of a girl. `@`Actually, it's a boy."`\
;＜彼岸花

;　この絵が描かれた当時のフランスでは。@上流階級の家では、男の子にもスカートを履かせるのが流行っていたという。@
` In France, at the time this painting was done, `@`it was common for upperclass families to dress their boys in skirts.`@
br
;　……髪が長いから少女だと思い込んできたが、@……その髪をもし短くしたなら、……それはまさに、……この少年に瓜二つだった。\
` ...Because the hair was so long, I assumed it was a girl....`@` but if the hair was shorter.... that kid really would... look just like this boy here.`\
;　ルノワールの怪談は、その容姿についても語っている。@
` That similarity was also mentioned in Renoir's ghost story.`@
br
;“五、ルノワールは美術室に飾られた『鞭を持つ子供』に描かれた子供とそっくりの姿をしている。”\
`'Five, Renoir looks just like the kid in the painting 'Child with a Whip' hanging on the art room's wall.'`\
;　……彼は、髪を切ったのだ。@だから、わからなかった。@
` ...He cut his hair. `@`So I didn't realize it.`@
br
;　それに、思い返せば彼はこうも言っているのだ。@
` Besides, thinking back on it, he said something earlier.`@
;　さっき、少年をモデルに絵を描いていた時の会話……。\
` During our conversation when I was drawing him modeling...`\
bg black,22
mono 1
bg bijutu_02,0
ld r,NAF_D1,22


;『ごめんなさい、なんか、こういうの慣れてなくて………。』@
`"I'm sorry, I'm not really used to doing this, so...."`@
ld r,NAF_D2,80

;『無理もないわよ。@モデルをやるのなんて初めてでしょ？』@
`"Don't worry. `@`It's your first time being a model, right?"`@
;『あ、いえ……。@その、一度だけやったことはあるんですけど、随分前のことなんで………。』\
`"Ah, no... `@`Actually, I've done it once before, but that was a long time ago..."`@
;　前。@前とはいつのことだろう。@
` Before? `@`How long before was that?`@
br
;　それは一月前、とか、半年前、といった程度ではなく、@もっとずっとずっと“前”だったのではないだろうか。@昔、と言い換えてもよいほどの。\
` He didn't mean it was a month or half a year before. `@`He must have meant much, much longer 'before.' `@`In other words, during another era.`\
bg black,22

;　新谷が生まれるよりも、この学校が建てられるよりも。@
` From a time long before Shintani was even born, before this school was even built.`@
br
;　例えば、そう、百年以上とか………。\
` Basically, over a hundred years ago.....`\
bg kaiga_02,22

;　そして、新谷は絵を描きながらこうも思った。@この少年の顔は下手な女の子よりもよっぽど可愛い、と。@女物の服でも着せて、ウィッグでも被せれば、男だと疑う者はまずいないだろう、と。\
` Also, there was something else she thought to herself when she was drawing. `@`That this boy's face was cuter than most girls out there, `@`and that if he was wearing girl's clothes and a wig then very few people would even suspect him of being a male.`\
;　つまり……、もしも少年の髪が長くて、女の子の服……、@例えばスカートなんかを履いていたら、きっと少年を少女と間違えてしまうだろう、ということだ。\
` That is to say... if his hair was longer, and he was wearing girl's clothes.... `@`like a skirt, then he could be mistaken for a girl.`\
bg black,22

;　新谷は想像する。@少年の髪が伸びて、スカートを履かされた姿を。@スカートの色は………例えば、そう、青とか………。\
` Shintani imagined what he would look like. `@`If he had longer hair, and was wearing a skirt. `@`And if the skirt was colored.... a bluish color....`\

mono 0
bg kaiga_01,22
;ld c,RUN_D7,0
;ld l,HIG_D2,22

;cl c,0
ld r,RUN_D2,22

;「僕が、ルノワールだよ。@……学校妖怪序列第６位“美術室のルノワール”。」@
`"I am Renoir.`@`... 6th Ranked among the School Youkai, 'Renoir of the Art Room'."`@
ld l,HIG_D4,22

;「私は彼岸花。@学校妖怪序列第３位“踊る彼岸花”とは私のこと。」@
`"And I am Higanbana. `@`The 3rd Ranked among the School Youkai, 'The Dancing Higanbana'."`@
br
;　わけが、……わからない。@二人とも妖怪だったのだ。\
` That... makes no sense. `@`They were both youkai?`\
ld r,RUN_D3,80

;「……僕は、長いこと眠っていた妖怪でね。@……ずいぶん長いこと眠っていたから、……まだ力が全然蘇らないんだ。@……たまに姿を現すのがやっと。@それくらいの妖力しかない。@………だから、彼岸花に助けてもらったんだ。」\
`"...As a youkai, I've been asleep for a very long time.`@`... and because I was asleep for so long.... I've yet to recover all of my power.`@`... I've can only occasionally make my presense known. `@`That is how far my power has fallen.`@`... So, Higanban is helping me."`\
ld l,HIG_W3,80

;「私好みの魂ではないけれど。@狩りを少し手伝うだけで分け前がもらえるなら、まぁ、引き受けないこともないわ。@くすくすくす………。」\
`"Her soul doesn't really fit my tastes. `@`But as long as I'm getting my share of it just by helping in your hunt a little, well, I guess I can't complain. `@`Teeheehee...."`\
ld r,RUN_D1,80

;「ありがとう。@……あとは、……僕だけでも出来るから。」@
`"Thanks.`@`... I will... handle the rest from here."`@
br
;　そう言い、本当のルノワールが、ゆらりと歩み出る。\
` The real Renoir spoke and started to slowly walk.`\
;bg black,24
;bg bijutu_04,24


cl r,0
ld c,RUN_D8,24

cl l,2

me2v 28,50

;　華奢そうな容姿は先ほどと何も変わりないのに、……なぜか気圧され、新谷は後退ってしまう……。\
` He had the same delicate appearance that he had before.... but for some reason Shintani felt small compared to him, and started backing up...`\
ld c,RUN_D2,80

;「……裕貴くんは、本当にあなたのことが好きだった。@……その気持ちは、あなたなんかが思っているよりも、はるかに無垢で美しいくらいに。」@
`"...Yuuki really did love you.`@`... It was a feeling much more innocent and beautiful than you imagined."`@
br

cl c,5

;　ルノワールは屈み、床に落ちているスケッチを拾い上げる。\
` Renoir bent over and picked up one of the sketches from the floor.`\
se1v 1010,30
ld c,RUN_D8,6

「……だから。@……裕貴くんは、あなたに個人的な絵のモデルになってほしいって言われた時、@……とても嬉しかった。@自分の存在を、先生が必要としてくれたって思って。@……本当に嬉しかった。」\

　そのスケッチには、……痛々しい、陵辱の痕を晒す少年の裸体が、@記すことでさらに辱しめるかのように、克明に描かれている。\

ld c,RUN_D6,80

「……たとえこのような形であれ。@……それを受け止めることで、自分の気持ちも受け止めてくれるかもしれない。@……裕貴くんはそう信じて、あなたのどんな命令にも、黙々と従った……。」\

「そうよ。@それが臣従というものよ。@私の美貌の虜となった彼の、それは当然の使命。」@

cl c,0
mld c,RUN_D7,80

「……そう。@あなたは彼の好意を、一方的に貪り続けたんだ。@……裕貴くんだって、それがわからなかったわけじゃない。」\
ld r,HIG_W1,22
ld r,HIG_W3,80

「恋は盲目……。@裕貴は本当に好きだったのね。@こんな欲望の塊の女を。」@
;＜彼岸花

mld c,RUN_D2,80

「そしてあの日。@……裕貴くんは初めて、……あなたに反抗したんだ。」\

mcl c,0
bg black,2
se1v 11,40
bg white,23
bg bijutu_03,0
ld c,NOD_D4,22

　あの日。@裕貴は初めて、……ボタンを外そうとする新谷の手を、払った。\

ld c,NOD_D5a,80


『……先生、もう、やめて下さい……。』@
br
　彼はかすれた声でそう言って、初めて私を拒んだのだ。\

　私は、それが許せなかった。@
　私は女王なのに。@お前は私のものなのに。@私を、拒むなんて。@
br
　それが許せなくて、頭に血が上って……、私は乱暴に、無理やり服を脱がせようとした。\

se1 10
quakex 2,200
cl c,25
se2 13
quakey 2,200

wait 1000

bg black,29
mono 0

se1v 13,100
wait 50
se2v 13,100
quake 5,500

wait 500
bg blood_1aR,8

「裕貴は怖くなって、美術室から逃げ出そうとしたわ。@……あなたはその背中を、突き飛ばしたの。」@
;＜彼岸花
「………そして、裕貴くんは机にぶつかって倒れた。@……そこに、バランスを崩した石膏像が……。」\

bg black,22

me3v 5,70

bg bijutu_02,0
ld c,NAF_D7a,22
ld c,NAF_D8a,80

「じ、……事故よ。@……私は突き飛ばそうとしたんじゃない。@その肩を掴もうとしただけ。@……彼はひとりで転んで、ひとりで机にぶつかって。@……運悪く石膏像が倒れてきて、……当たり所が悪かっただけ。@……あれは全部、事故よ。@私は悪くなんかないわ…！！」\


bg black,24
bg bijutu_03,0
ld r,HIG_W3,24

「だそうよ…？」@
;＜彼岸花

ld l,RUN_D8,23
ld l,RUN_D2,80

「………そうだね。@……確かに、……事故かもしれないよ。@でも、僕が知りたかったのは、そんなことじゃない。@……そんなことじゃないんだ。」\

bg black,23
bg bijutu_04,0
ld r,NAF_D6a,23
;cl c,0
ld r,NAF_D7a,80

「……へぇ……。@……じゃあ、……何………。」@
br
　ルノワールの表情は、先ほどから淡白なままのはずなのに。@
　目を逸らさずにはいられない凄みに気圧され、新谷はなおも後退る……。\

ld l,RUN_D7,23
ld l,RUN_D3,80

「僕は、……彼に代わって聞きたかったんだ。@………先生にとっては彼が玩具でしかないことは知ってたし。@……先生が殺したわけじゃないことも知っていた。@……だからその上で、……今となってはもう、聞くことの出来ない彼に代わって、……聞きたかったんだ。」\

ld r,NAF_D6a,80

「………それは、………何よ……。」@

ld l,RUN_D6,80

「そしてそれは、……もう聞けたよ。@……そして、とても残念だった。」@

ld r,NAF_D7a,80

「何をよ…！@　私が何を答えたのよ…！！」\


ld l,RUN_D9,80

「裕貴くんに対して、申し訳ないという気持ちを、微塵も持っていないということだよ。」@
br
　無表情なルノワールが、その瞬間だけ歪む。\

ld l,RUN_D8,80

「あなたはあれだけ裕貴くんを慰み者にしたのに。@そして、その死の一端に関わったはずなのに。@……彼に対して申し訳ないという気持ちを、抱いてはくれなかった…。@それが、………僕には許せない。@……だから、狩る。@……裕貴くんの無念を晴らすために、@……僕は彼岸花の助けを借りて、……ここへこうして、現れたんだ……。」\

ld r,NAF_D8a,80

「は、……はは……！@　つまり、こういうことね。@……裕貴くんの魂が、あなたという妖怪になって、化けて出てきたというわけね。@はは、ははははは…！@/

se1 84

　はっははははははははははははは！！」\

ld l,RUN_D6,80

「……何が、おかしいの。」@

ld r,NAF_D7,80

「おかしいわよ。@だって、あなたは“美術室のルノワール”なんでしょう？」@

ld l,RUN_D2,80

「それが何…？」\

ld r,NAF_D8,80

「なら、あなただって同じだわ。@裕貴くんの仇が討ちたいなら、私に怪談のルールで挑まなくてはならない！」@

ld l,RUN_D6,80

「……そうだね。@……僕の、ルノワールの怪談のルールに則って、……あなたを、狩る。」\

ld r,NAF_D7,80

「ならば、どうやって？！@　さっき、そこの黒い髪の子が私に挑んで返り討ちにされたのを見ていなかったの？！@　私はどの絵画の作者も正確に答えることが出来るわ！@　そしてあんたの正体がわかった今、@あんたから絵筆を借りるなんてことはしないし、あんたの問い掛けに嘘を吐くなんてミスも犯さない！@　あんたがどれだけ私を憎もうとも！@　あんたは絶対に私に勝てないのよ！！」\

ld c,HIG_w3,22
;ld c,HIG_W4,80

「…………だそうよ。@くすくすくす。」@
;＜彼岸花

ld l,RUN_D2,80

「………………………。」\
;＜ルノワール

textoff
fede 1,1000
E_B

ld r,NAF_D2,80

「……何がおかしいのよ。@私に勝てないのは、すでにあんたが立証済みでしょうが。」@

ld c,HIG_D2,80

「勝てないも何も。@……ルノワールはもう、勝ち終わっているのよ？」\

textoff
fede 0,1000
E_A

cl l,0
mld l,RUN_D3,80

bgm1 6

「先生。@……もう忘れちゃいました？」@
;＜ルノワール

ld r,NAF_D6a,80

「……な、……何をよ……。」@
br
　黒髪の少女が、バカにするようにくすくすと笑う。@
　私ひとりだけが、まだ状況を理解していないとでも言うかのように、くすくすと笑う。\

mld l,RUN_D6,80

「僕がモデルになって。@……先生に絵を描いてもらってる時。@……僕は先生に聞きましたよね。」\

mcl l,0
bg black,22
mono 1
bg bijutu_02,0
ld c,NAF_D1,22

『……どうして裕貴くんはあんなことになってしまったんでしょうか。』@

ld c,NAF_D4,80

『…………さあ。@よく分からないわ。』\

　どうして裕貴くんは、あんなことになってしまったのか？@
　知っている。@だって、私の目の前で死んだのだから。@
br
　そう。@私は、知　ッ　テ　イ　ル…！\

bg black,22
mono 0
bg kaiga_01,0
ld r,RUN_D7,22
;ld l,HIG_D4,22


ld r,RUN_D6,80

「でも、あなたは言った。@……わからないと。」@

ld l,HIG_W4,22

me1v 16,50

「知っているのに、わからないと“偽った”わ。@……それが意味するところが、わかるかしら？@　……くすくすくすくす。」\
;＜彼岸花

bg black,23
bg bijutu_04,0
ld c,NAF_D9a,23

me2v 17,50

　新谷の顔から、……音を立てて血の気が引いていく。@
br
　その音はまさに、潮のようだった。\

bg black,22

“ルノワールの問い掛けに嘘をついてはならない。”@
“上記を破れば、絵のどれかと、同じ運命を追うことになる。”\

me3v 3,50

bg white,23
se1 20
bg kaiga_01,23
wait 100
bg white,23
se2 20
bg kaiga_02,23

　美術室中に掛けられた、@……おぞましい絵画の数々が、ぐるぐると新谷の回りを取り囲みながら渦を巻き出す。\

bg black,22
mono 2
bg Different_spiral_1b,22

me4v 28,70

　『サトゥルヌス』の世界で、生きながら貪り喰われる運命を？@　あるいは『ゲルニカ』の世界で、逃げ惑いながら戦火に巻き込まれる運命を？@　さもなくば『残酷の四段階』のような、死後にも腹を割かれて臓物を引き摺り出される無残な運命を？\


　嫌だ、嫌、嫌、嫌…！！@　どれも嫌、嫌、嫌、嫌ッ！！！\

bg black,22
mono 0
bg kaiga_01,0
ld c,RUN_D8,22
;ld l,HIG_D4,22

ld c,RUN_D6,80

「あなたに、裕貴くんへの謝罪の気持ちがあったなら、@……僕はあれが事故ということでも仕方がないと思った。@……だって、彼はそれでも最後まで、あなたのことが好きだったのだから。」\

quake 5,500

「やめてッ、嫌ッ、嫌ぁああああああぁああぁ！！」\

textoff

bg black,0
ld c,RUN_D6,2

fedexx 70,90,90,90,90,0,2000


ld c,RUN_D9,80

「でも、あなたにはそのような気持ちは微塵もないとわかった。@……だから、あなたを罰することにした。@……さぁ。@あなたの運命は、あなたが決めるといいよ。@どの運命であっても、……それは彼の魂が救われるまで、永遠にあなたを苛むものとなる。」\

bg black,23
bg bijutu_02,0
ld c,NAF_D9a,23
;ld c,NAF_D9a,80
quakex 2,300

「やめてッ、助けてッ！！@　誰かッ、誰かぁああぁああぁぁ！！！」@
br

cl c,23

　新谷は絶叫し、美術室を飛び出す。@……その後姿は、裕貴が彼女から逃げ出そうとした時のものにそっくりだった。\

bg black,24
bg bijutu_03,24
;se1 10
quakex 1,100

　美術室を飛び出す時、机にぶつかる。@
br
　かつてはそこに石膏像があった。@しかし、「事故」のあと、そこからは撤去されたので、彼女を罰する存在とはならなかった。\

bg black,24
bg bijutu_01,24
wait 500
bg black,24
bg rouka_02,24
;wait 300
;bg black,24
;bg rouka_01,24
wait 300
bg black,24
bg kaidan_02,24



　彼女は美術室を飛び出す。@そして金切り声で絶叫しながら、廊下を駆け抜け、階段を飛び降りるように駆け下りていく……。\

bg black,22
bg kaiga_01,0
;ld l,RUN_D7,0
ld r,HIG_W3,22
ld r,HIG_d3,80

「………転ばせて、保健室送りにでもしてやろうかしら？」@

mld c,RUN_D2,22

「その必要はないよ。@……彼女は自らの運命を選んだよ。@ここに飾られた絵の運命を、ね……。」@
br
　ルノワールは、壁に掛けられた絵画の一枚を見る。@
　彼岸花もそれに気付き、その題名を読み上げる。\

ld r,HIG_D4,80

「……なるほど。@『上昇と下降』ね。@……ちなみに作者はだぁれ？」\

mld c,RUN_D6,80

「マウリッツ・コルネリス・、@エッシャー。」\

mcl c,0

bg black,2
wait 2000
bg mugen_01,22

　新谷は荒く息を吐き、吸い、狂いそうな頭に無理矢理酸素を送り込みながら、必死に階段を駆け下りていた。@
　少しでもあの美術室から、いや、この学校から遠ざかりたかった。\

　極度の恐怖と緊張で、足の感覚は既にない。@限界の力のみで強引に動かしているに過ぎない。\

　それでも、動かさないと！　ここから逃げないと！@　走れ！　もっと走れ！@　動け左足！　右足！@　もっと！！　もっとッ！！！\

;bg black,22
bg mugen_02,2

　恐怖に駆られた彼女は、……いつまでも気付けない。@
br
　階段を降りても降りても、……降りても降りても、次の階に辿り着けない。@
　延々と踊り場が繰り返されるだけだ。\

　まるで、ハムスターが滑車の中でぐるぐると、何かに急き立てられるかのように走り続けるように。@……いつまでもぐるぐると、無限の階段を駆け下り続ける。\

　やがて彼女も、いつかは気付くだろう。@
br
　終わりなき無限の階段に、辿り着く先など存在しないということを。\

;bg black,22
bg mugen_03,2

　しかしそれでも、新谷の足は止まらなかった。@
　止まれば、あの美術室の恐ろしい絵画の何れかに飲み込まれてしまう。@
　その恐怖が、彼女を永遠に駆り立て続けるのだ。\

　それでもいつか気付くだろう。@……ここがすでに、絵画の中の世界なのだと。\

bg black,22

　何故か涙が止まらなかった。@それがどんな感情に起因するものなのかは分からなかった。@
　恐怖か、絶望か。@それとも、この期に及んでようやく、悔悟の念が湧いたのか。@
　涙と一緒に鼻水や涎までもが溢れ出した。\

　体中の水分をぼたぼたと垂れ流しながら、新谷は無限に階段を駆け下り続ける。@
br
　……地獄があるなら、ここだと思った。\

wait 2000

fede 0,2000
E_A

wait 1000

bg bijutu_06,22
;ld r,RUN_D8,0
;ld l,HIG_D1,22

ld c,HIG_w3,22

bgm1 5

「私の狩りとは趣きが違うけれど。@……あんたの狩りも、なかなかに残酷ね。」@

ld r,RUN_D2,22

「………彼女を殺しはしないよ。@……永遠の時間の中で、彼女が考えを改めてくれるよう、檻に閉じ込めただけだから。」\

cl c,0
ld l,HIG_d2,24

「じゃあ、私はこれで。@……ご馳走様。@あんな女の魂でも、たまには珍味でおいしいわ。@くすくすくすくすくす………。」\

bg black,24
bg kaiga_02,24

　彼岸花は姿を消そうとして、ふと気が付き、@もう一度、新谷の閉じ込められた『上昇と下降』という名の、無限階段の絵画を見る。\

「これ。@誰か気付くんじゃない？」@
「……さぁね。@……気付いて、本物のエッシャーの絵に興味を持ってもらえるなら、美術室の妖怪として嬉しいね。」\

　絵には、無限階段をぐるぐると回り続ける人々が描かれている。@
br
　その中に、………１人だけ女が描き足されているのだ。\

　疲れ切ってやつれ果て、顔は涙で化粧をぐちゃぐちゃにしている、哀れな女。@
br
　……足は擦り切れそうなほどにボロボロなのに、@……それでもなお、階段を下り続けることを永遠に強要されている……。\

bg black,22
bg bijutu_03,22
;ld l,HIG_D3,24
ld l,HIG_D5,22

「じゃあね。@いずれ、また。@……あんたももう少し狩りをして力を蓄えないと。@今回みたいに、いざって時に力が出せないわよ？@　スミレなんか、健気にずいぶん頑張っているというのに。」\

ld r,RUN_D8,24
ld r,RUN_D1,80

「そうだね。@……美術室で不真面目をする悪い子には、@たまには少しお仕置きをしてあげるのもいいかもしれない。」@

ld l,HIG_W3,80

「くすくすくす。@……じゃあね、ルノワール。@またいつか。@１３組のホームルームの時にでも。」\

cl l,42

　彼岸花は姿を消す。@
br
　後には、ルノワールと静寂を取り戻した美術室があるだけだった。\

cl r,0
ld c,RUN_D7,24

「……そうだね。@……彼岸花の言う通りかもしれない。@………僕にもっと力があれば。@……君を守ってあげることも出来たんだ……。」@
br
　ルノワールは、床に散っているスケッチの一枚を拾い上げる。\

　その一枚に描かれている裕貴は、……静かに柔らかく微笑んでいた。\

ld c,RUN_D2,80

「…………………。」@
br
　ルノワールが久々に出会った人間が、彼だった。@
　彼は自分と対話が出来る、貴重な波長の持ち主だった。\

bg black,22

　彼は美術に関心があり、短い時間とはいえ、素晴らしい話し相手になってくれた。@
br
　自分の髪が長く、スカートを履いているせいで、女の子に見られるのが悩みだと打ち明けたら。@……彼は言ったんだ。\

mono 1

bg bijutu_02,0
ld c,NOD_D2,22
ld c,NOD_D3,80

『……もし本当に気に入らないんだったら、服とか変えてみたらどうかな？@　それとも少し髪を切ってみるとか……。』@
br
　髪を切り、服を変えた。@
　その姿をもう一度、彼に見せたかった。\

bg black,22

mono 0

bg kaiga_02,22

「……裕貴くん。@………せめて、君の気に入ってくれた美術室がわずかでも美しくなるように。@………この部屋の新しい主となる先生に働きかけて、@……怖い絵だけじゃなく、楽しい絵も入れてもらおうと思うんだ。」\

　あの日、彼とこの部屋でした、様々な絵の議論が思い返される。\

　この絵はなんだか子供の落書きみたい。@
　この絵は怖いけど、色彩がすごく綺麗。@
br
　僕はこの絵が一番好き。@
　いや、僕はこっちの方が。@
br
　短かったけど、とても楽しい時間だった。@
　学校妖怪になってから、人間とこんなにも楽しく交流できるなんて、思ったこともなかった。\

　……人間はただのエサ。@彼らを怖がらせて生きるのが、自分たちの役目。@
br
　そう思い込んできたのに。@
　……………………。\

bg black,22
bg kaiga_01,0
ld c,RUN_D2,22
ld c,RUN_D8,80

「……そう言えば。@……彼岸花も、人間に興味を持ったことがあったって言ってたっけ。@………８位の子も、元は人間だそうだし。」@
br
　新谷のような、欲望の塊のような人間がいる一方で。@
　……時に、自分が妖怪であることさえ忘れさせてくれるような、……彼のような人間もいる。\

ld c,RUN_D1,80

「……面白いな。@人間は。」@
br
　だから絵画のモチーフに、人間はこれほど多く選ばれるのだ。\

cl c,2

bg black,2

fede 0,2000
E_A

wait 1000

bg bijutu_01,2

bgm1 29

　“美術室のルノワール”の怪談は、その後も時折、囁かれる。@
br
　放課後に、誰もいないはずの美術室で、不思議な少年に話し掛けられたという話が。\

　しかし、美術を愛する子と楽しく議論にふけるだけで、@恐ろしい目に遭わせようとしたという話は聞かない。@
br
　美術部員の間では、彼に出会えれば画力が上がるなどと言われ、崇められつつもあるようだ。\

bg black,22
bg kaiga_02,22

　……しかし、敬いを忘れてはならない。@
　妖怪は、敬う者には寛大だが、そうでない者には、……………。@
br
　美術室に飾られたエッシャーの絵に、女の姿が増えていることに気付く生徒は、まだいない。\


;＜おしまい＞


bg black,42

bg e022,42
wait 1000
bg black,42
bgcopy ;背景をリセット

fede 0,2000
E_A
wait 2000

if %UMINEKOEND < 4 mov %UMINEKOEND,4 : mov %END_FLG,4 ;クリアフラグの変更

	saveoff            ;セーブオフで、処理を高速化する。
	erasetextwindow 0  ;テキストエフェクトを切る事で処理を高速化
	rmode 0            ;右クリックのメニュー表示の無効化
	textoff

goto *b_title
;reset
*higan5_opning

texton
csp -1

bg black,2
bgcopy ;背景をリセット

setwindow 31,16,22,16,26,26,0,2,20,1,1,#999999,0,0,639,479

!sd

mono 0
E_A

bg ie_02,0
ld l,MIC_D1,22
;ld r,TOM_D1,2

ld l,MIC_D2,80

bgm1 19
