;Chapter 7
;　その日、かつての学び舎は、旧校舎という名前になった。@
`　That day, the building that used to be used as the schoolhouse was renamed as the Old School Building.`@
br
;　町の合併と大規模な再開発に伴い、@いくつもの学校が統合され、巨大な新校舎が誕生したのである。\
`　As a result of multiple smaller towns merging together and large-scale development, `@`the students and staff of many different schools were brought together under the roof of a New School Building.`\
bg black,22
bg kyou_01,22

;　いくつもの学校出身の生徒たちが一つの教室に入り混じり、@そこには新しいカオスと、新しい社会が誕生した。@
`　With students coming from so many different schools gathering in classrooms together, `@`a new form of chaos, as well as a new kind of society developed within those walls.`@
br
;　新しい学校には、まだ秩序もルールもない。@
`　This new school had yet to gain order and rules.`@
;　恐れるべき怪談も七不思議も、まだ誕生していない……。\
`　The ghost stories and seven mysteries that should strike fear into the students had yet to be born...`\
bg black,22
bg rouka_04,22

;　それまでに類を見ないほど大勢の子供たちが集う、その学校には、@……方々からあらゆる妖怪や悪霊が集まってきた。@
`　An unprecedented number of children gathered at this school.`@` ...As did various youkai and evil spirits.`@
br
;　この生まれたばかりのカオスを、自分の縄張りにしようと、狩場にしようと、@無数の妖怪たちが集まってきた……。\
`　Out of this newly born chaos, countless youkai gathered, `@`trying to establish their territory and make the school their new hunting grounds...`\
bg black,22

me1v 16,50

mono 2
bg Different_spiral_1b,22


;　今、学校には、名も無き無数の妖怪たちが跋扈している。@
`　Now, the school is being overrun by a myriad of nameless youkai.`@
br
;　もちろん、無慈悲な妖怪たちに、妖怪同士、仲良くしようなどという気持ちがあるわけもない。\
`　Of course, there is no reason to expect such ruthless youkai to try to get along with each other.`\
;　この巨大な狩場に自分の縄張りを広げようと、妖怪同士が殺し合い、喰らい合う。@
`　In the interest of increasing their territory in this giant hunting ground, these youkai killed and devoured each other.`@
br
;　新しき生徒たちだけでなく、……妖怪たちにとっても、そこはカオスのるつぼなのだった。\
`　The school was a melting pot of chaos not just for new students... but for youkai too.`\
bg black,22
mono 0
bg hoken_05,22

;　……彼女は、そんな学校に生まれた妖怪のひとりだった。@
`　...She was one of the monsters born into this school.`@
br
;　依り代は、西洋人形。@
`　Her form was that of a Western doll.`@
;　今では旧校舎と呼ばれる校舎の保健室の薬品棚の上に、長年飾られていた人形だ。@
`　For many years, she had adorned the top of the medicine cabinet in the old school building's infirmary.`@
br
;　それが新校舎の保健室に移され、……妖怪たちのカオスの中で、意思を持った。\
`　She was moved to the infirmary in the new building... and there, among the chaos of the youkai, she gained consciousness.`\
bg black,22
bg hoken_01,22

;　……彼女は、踊り出した。@夜の保健室でひとり。@
`　...She began to dance, `@`alone in the infirmary at night.`@
br
;　そして、自分が妖怪であることを理解し、自分の成すべきことを、本能的に悟った。\
`　And she began to comprehend that she herself was a youkai, and instinctively realized what she must do.`\
;　妖怪として、生きるために、人間の魂を獲物とすること。@
`　As a youkai, in order to live she must prey on the souls of humans.`@
br
;　そして、その獲物を奪われないために、他の妖怪たちと戦うこと。\
`　And so to make sure that her prey was not stolen from her, she fought against other youkai.`\
;mcl r,0
bg black,25
;bg white,1

se1 66

bg bite,26


;　この巨大な狩場を独占しようと、妖怪たちは互いが互いを憎み合い、殺し合っている。@
`　If one tried to monopolize this hunting ground, the monsters would kill each other out of mutual hatred.`@
;　生まれたばかりの彼女とて、それは例外ではない。@
`　She, as a newborn, was no exception.`@
;　より恐ろしい妖怪に見つかれば、問答無用で殺される。@
`　If she found a more fearsome monster, she would be killed with no questions asked.`@
;　百鬼夜行の校内で彼女が生き残るためには、戦わなければならなかった。\
`　In order for her to survive in this monster-infested school, she had to fight.`\
bg black,2

fede 0,2000
E_A

bg kouchou_01,22

;■校長室

ld l,MAR_D4a,23
;ld l,MAR_D1,80

bgm1 29

;「さくのしんちゃんも、……その戦いに巻き込まれたの？」@
`"Did Sakunoshin-chan get caught up in that too?"`@
;＜毬枝

ld r,SAK_D1,24
ld r,SAK_D2,80


;「僕は違うよ。@僕は学校妖怪じゃないもの。@僕の祠は、新校舎が出来るよりずっと前からここにあって、@僕もずっとここに住んでたのだから。」\
`"Not me.`@` I'm not a school monster.`@` My shrine and I have both been here for a long time.`@` Before this school building, in fact."`\
;＜さくのしん

;ld r,SAK_D4,80

;　さくのしんは、その幼そうな外見に似合わず、@この巨大マンモス校が誕生する以前からこの土地にいる長老格なのだ。\
`　Despite his youthful appearance,`@` Sakunoshin had been one of the Elders since long before this mammoth of a school was constructed.`\
bg black,23
bg kouchou_02,0
ld c,KOU_D2,23
;ld r,KOU_D1,80

;「懐かしいね。@……混沌とした時代だったよ。」\
`"How nostalgic.`@` ...It was such a chaotic time."`\
;＜校長

;mov %iza_Isyou,2
ld l,IZA_D3,23
;ld l,IZA_D1,80

;「有象無象の妖怪どもがぎっしりひしめいてやがった。@どいつもこいつも、クソガキどもの魂を独り占めしてやろうと、ギラギラしてやがったぜ。」\
`"They were just a ragtag group of youkai, all jam-packed into one place. `@`Each of them trying to create a monopoly on the souls of the brats."`\
;＜イザナミ

;ld r,SIN_D2,22
ld r,SIN_D3,22

;「あなたもその中のひとりだったわけですがねぇ。」@
`"You were one of them too, you know?"`@
;＜紅茶

ld l,IZA_D7,80

;「テメェもその中の１匹だろーがッ。」\
`"You were too, ya bastard."`\
;＜イザナミ

mov %SMI_Isyou,2
bg black,23
bg kouchou_03,0
ld l,AZA_D4,23
ld l,AZA_D2,80


;「うふふふふふ……。@今では懐かしき、まさに混沌のるつぼ。」@
`"Ufufufufufufu...`@` It is rather nostalgic. It really was a chaotic melting pot."`@
;＜アザミ

ld c,SMI_w5,22
ld c,SMI_w3,80

;「私と姉者の姉妹タッグで、海千山千の妖怪どもを、次々に葬ったのじゃ！@　毬枝には想像もつくまい！@　それはそれは、血で血を洗う、恐ろしい時代だったのじゃぞ！」\
`"Together as a sisterly tag-team we took down many sly old youkai one by one! `@`You can't begin to imagine what it was like, Marie! `@`My goodness, was it a bloody feud. It was quite a terrifying era!"`\
;＜スミレ

bg black,22
bg kouchou_01,0
ld r,MAR_D2a,22
ld r,MAR_D4,80

;「……そ、そうだったんですか……。@じゃあ、皆さんは全員、その時代を勝ち残ったわけですね……。」\
`"....Ah, is that so.... `@`So you all are the ones who won and survived that era then...?"`\
;＜毬枝

ld l,KYO_D2,24
ld l,KYO_D1,80

;「俺様やルノは、ぼんやり傍観してただけさ。」@
`"Some of us, like Ren and I, watched idly from the sidelines."`@
;＜キョウ

ld c,RUN_D3,22
;ld c,RUN_D1,80

;「……物騒だったからね。@僕は絵の中に隠れてたよ。」\
`"...Because it was dangerous you know. `@`I hid myself in the paintings."`\
;＜ルノワール

cl r,22
ld r,AZA_D1,24
ld r,AZA_D4,80

;「あの時代。@隠れ果せるだけでも、なかなか出来ることではありませんでした。」@
`"At that time, `@`just managing to find a place to hide yourself was no simple task."`@
;＜アザミ

cl c,22
ld c,KOU_D3,22
ld c,KOU_D1,80

;「そうだね。@……考えようによっては、戦って生き残る以上に、困難な生き残り方だったかもしれんね。」\
`"That's true.`@` ...In a sense, it may have been more difficult to survive than just fighting for it."`\
;＜校長

cl r,22
ld r,SIN_D4,24
;ld r,SIN_D1,80

;「そして、大勢の妖怪たちが淘汰されていき、力の優劣が次第に序列化していき。@……混乱していた子供たちも落ち着きを取り戻し。」\
`"And then, most of the youkai were weeded out, and a hierarchy gradually formed based on the differences in our powers.`@` ...And the disordered children too regained their composure."`\
;＜紅茶

cl l,24
ld l,IZA_D2,23
;ld c,IZA_D1,80

;「クソガキどもはようやく、新しい校舎の七不思議をまとめたってわけさ。@そして、俺たち学校妖怪にも秩序が訪れた、ってわけだ。」\
`"Those brats eventually compiled the seven mysteries of their new school. `@`And that's how our ranking system was established."`\
;＜イザナミ

bg black,23
bg kouchou_02,0
ld l,RUN_D1,23
ld l,RUN_D5,80

;「……妖怪はやっぱり、静けさの中に潜む方が素敵だと思うね。」@
`"...It really is best for youkai to lie low and hide quietly."`@
;＜ルノワール

ld r,KOU_D3,24
;ld r,KOU_D1,80

;「同感だね。@老いると、あの過酷な混沌は二度と御免というものだよ。」\
`"I agree. `@`Once you get old, that merciless chaos is something you'll never be able to face again."`\
;＜校長

mld c,KYO_D2,22
mld c,KYO_D5,80

;「毬枝は己のラックに感謝すべきだぜ。@……お前がここへ訪れたのがあの時代だったら、@瞬きを二つする間もなく、どこぞの妖怪に食い殺されていただろうぜ。@クックック。」\
`"You should be grateful for how lucky you are, Marie.`@` ...If you were around back in that era, `@`you would have been eaten up by another youkai in the blink of an eye. `@`Kukuku."`\
;＜キョウ

mcl c,0
bg black,22
bg kouchou_01,0
ld c,MAR_D4a,22

;「………そんな時代も……、あったんですね……。」\
`"....So there really was... a time like that..."`\
;＜毬枝

;　かつて、弱肉強食の恐ろしい時代があったという話は、彼岸花から少し聞いたことがある。@
`　I had heard a few stories from Higanbana about a frightening time when it was survival of the fittest for the youkai here.`@
br
;　大勢の妖怪たちが、食い合い、殺し合い。@……その結果、生き残って学校妖怪として君臨したのが、……今の彼らなのだ。\
`　She mentioned a large number of youkai killing and devouring each other.`@` ...And the ones who survived that era and reigned as the school youkai... is this group here.`\
bg black,22
ld c,KOU_D1,22
wait 300
ld c,KOU_u1,80
cl c,2

ld l,SIN_D1,0
ld r,IZA_D1,22
wait 300
ld l,SIN_D4,0
ld r,IZA_D8,80
cl a,2

ld c,HIG_w2,22
wait 300
ld c,HIG_w6,80
cl c,2

ld c,AZA_D5,22
wait 300
ld c,AZA_D2,80
cl c,2

ld c,KYO_D2,22
wait 300
ld c,KYO_D4,80
cl c,2

ld c,RUN_D2,22
wait 300
ld c,RUN_D10,80
cl c,2

ld c,SMI_D3,22
wait 300
ld c,SMI_w6,80
cl c,2

;　学校に七不思議が定着し、彼らに学校妖怪七席としての序列が出来て、@ようやく殺し合いの恐ろしい時代は幕を下ろしたのだ……。\
`　They established themselves as the seven mysteries of the school, and created a seven-rank school youkai hierarchy. `@`By doing so they finally closed the curtain on that terrifying era of killing...`\
bg kouchou_02,22
ld c,SAK_k3,22
ld c,SAK_k1,80

;「彼岸花は、……ものすごく強くて残酷で、特に恐れられていたんだよ。」\
`"Higanbana... who was terribly cruel and strong, was particularly feared among them."`\
;＜さくのしん

ld l,SMI_D4,23
;ld l,SMI_D1,80

;「うむ。@昔の彼岸花は、実に恐ろしい残酷妖怪だったのじゃ。」@
`"Yes. `@`Higanbana used to be an especially cruel youkai."`@
;＜スミレ

ld r,IZA_D3,24
;ld r,IZA_D1,80

;「……だなァ。@アレでもあいつ、だいぶ丸くなったんだぜ。」\
`"...Right. `@`In a way, she's mellowed out a lot since then, ya know?"`\
;＜イザナミ

bg black,23
bg kouchou_04,0
ld l,AZA_D4,23
ld l,AZA_D3,80

;「うふふふふふ……。@当時の彼女を覚えている者ならば。@……今なお、彼女を前にして、震えを抑えることは難しいでしょう。」@
`"Ufufufufufu.... `@`For those of us who remember how she used to be.`@` ...Even now it's hard to keep yourself from trembling with fear when she's standing in front of you."`@
;＜アザミ

ld c,KYO_D3,23
;ld c,KYO_D1,80

;「この俺様でさえ、あいつが眉を歪めると今でもブルっちまわぁ。」\
`"Even for someone like me, whenever she furrows her brow, my heart can't help but skip a beat."`\
;＜キョウ

ld r,RUN_D7,24
ld r,RUN_D6a,80

;「……さっき毬枝は彼岸花のこと、本人が言うほど残酷じゃないと言ったけれど。@……そう言えるのは、あの時代を知らないからこそなのかもしれないね。」\
`"...Marie, you said earlier that Higanbana was actually less cruel than she seems.`@` ...Maybe the reason you're able to say that is because you don't know how she was back then."`\
;＜ルノワール

bg black,22
bg kouchou_01,0
ld l,MAR_D4a,22

;「………………………………。」\
`"..............."`\
;＜毬枝

ld r,SIN_D1,24
ld r,SIN_D2,80

;「くっくっく。@まぁ、気にしないことです。@子供たちも成長し、やがて大人になるように。@私たち妖怪とて、月日と共に変化することを避けられぬのですから。」\
`"Kukuku. `@`Well, it's nothing to worry about. `@`Just like how children grow up and become adults, `@`it's inevitable that as youkai we too will change with time."`\ 
;＜紅茶

ld c,IZA_D4,22
;ld c,IZA_D1,80

;「毬枝の存在が、あいつをさらに丸くしているのかもしれねぇなァ。」\
`"Marie's presence might have chilled her out a bit too, ya know?"`\
;＜イザナミ

cl c,0
cl r,22
ld r,KOU_D4,22
;ld r,KOU_D1,80

;「ほっほっほ……。@かもしれんねぇ。@毬枝くん。@これからも彼女の友人でいてやってくれたまえ。」@
`"Hohoho.... `@`Maybe so. `@`Marie-kun. `@`Please remain Higanbana's friend for all our sakes."`@
;＜校長

ld l,MAR_w1,80

;「は、はい。」\
`"Y-Yes..."`\
;＜毬枝

cl r,22
ld r,SAK_D2  ,0
ld c,SMI_w1,22

ld c,SMI_w4,80

;「あの、恐ろしい彼岸花も、変われば変わるものよのぅ。」@
`"The once terrifying Higanbana has changed quite a bit now."`@
;＜スミレ

ld r,SAK_D4,80

;「うりゅー。@彼岸花だって、色々な出会いで成長もするし、心だって変化するんだよ。@妖怪だって、そういうところは人間と変わらないよ。」\
`"Uryuu. `@`Even Higanbana's heart can't help but change and grow after meeting new people. `@`In that sense, humans and youkai are alike."`\
;＜さくのしん

ld l,MAR_D1,80

;「………………………。」\
`"..............."`\
;＜毬枝

bg black,24
bg kouchou_03,0
ld l,KOU_D3,0
ld c,SIN_D3,0
ld r,IZA_D5,24
wait 300
ld l,KOU_D1,0
ld c,SIN_D1,0
ld r,IZA_D3,80

;　彼岸花を除く妖怪たちが、ぎっしりと校長室に集まり、お茶会を開いていた。@
`　All of the school youkai except Higanbana were packed in the principal's office having a tea party.`@
br
;　全員参加必須のお月見会ならばともかく、@このような気紛れな催しにこれだけの妖怪が集まるなんて珍しい。\
`　These moon-viewing parties required every one of them to attend, `@`but it was rare for this many of the youkai to attend such a frivolous get-together.`\
bg black,22
bg kouchou_04,0
ld l,SMI_w5,0
ld r,AZA_D4,22
ld l,SMI_w3,80
wait 300
cl r,0
ld c,AZA_D3,24
quakey 1,100

;　呼べば集まらないくせに、@気紛れなお茶会には、どやどやとこれだけの人数が集まってくる。@
`　Despite the fact that they never attend meetings even when told to, `@`somehow this many of them managed to gather for an arbitrary tea party.`@
br
;　天邪鬼なのは、どうやら彼岸花だけではないようだった。\
`　Apparently Higanbana wasn't the only one among them who had a dissenting opinion.`\
bg black,23
bg kouchou_03,0
ld l,SAK_D3,0
ld c,KYO_D2,0
ld r,RUN_D5,23
;wait 300
;ld l,SAK_D1,0
;ld c,KYO_D1,0
;ld r,RUN_D1,80

;　……彼岸花不在であるのをいいことに、彼らが語る彼女の昔話は興味深かった。\
`　...The rest of the youkai took advantage of her absence and talked amongst themselves about the tale of Higanbana, a subject that Marie was very interested in.`\

;　自分のことを、誰よりも残酷なと吹聴する彼岸花。@
`　Higanbana would always boast about how she was the cruelest youkai of them all.`@
;　しかし毬枝は、自称するほど残酷な人ではないと感じていた。@
`　But Marie didn't think she was quite as cruel as she would have everyone believe.`@
;（気紛れで天邪鬼な、実に面倒臭い性格である点はもちろん譲れないのだが）\
`(Of course, this did not excuse the fact that Higanbana was at times capricious, rebellious and altogether difficult to deal with.)`\
bg black,22
ld c,HIG_D4,22
;ld c,HIG_D1,80

;　そんな彼女が、いつの頃からか、丸くなり。@
`　But somewhere down the line, she had calmed down a bit.`@
br
;　やがては、毬枝という友人を作り、@……少なくとも、友人をからかって笑えるような、血の通った存在に生まれ変わった。\
`　Eventually she made friends with Marie.`@` ...And, at the very least, became a less cold-blooded being, who was capable of teasing and laughing with a close friend.`\
bg black,22
bg kouchou_02,0
ld c,MAR_D1,22
;ld c,MAR_D1,80

;　毬枝には興味があった。@
`　Marie was interested in Higanbana.`@
br
;　かつて、本人の自称と寸分違わず、残酷の化身であった彼女が。@
`　Interested in the past where she was truly the personification of cruelty that she claimed she was.`@
;　何をきっかけに、今日のようになったのか。@
`　And how she became how she is today.`@
br
;　彼女を変えた何かに、毬枝は関心を持った……。\
`　Marie was curious as to what it was that caused her to change...`\
bg black,2

fede 0,1000
E_A
wait 1000

bg okujou_01,22

me1v 5,50

wait 2000
bg black,22

bg okujou_02,0
ld c,HIG_D9,22

;　その頃、彼岸花の姿は、……屋上にあった。@
`　At that time, Higanbana... was on the rooftop.`@
br
;　その縁に腰掛け、長い髪やスカートを風に任せ、……眼下をぼんやりと眺めていた。\
`　She was perched on the edge, her long hair and skirt swaying in the wind... and staring blankly downwards.`\
;　眼下を、……二人の人影が歩いている。@
`　Beneath her.... two people were walking.`@
br
;　大人の男性の手を引いて、生徒が敷地内を案内しているように見えた。\
`　A student was leading a grown man by the hand, apparently giving him a tour of the school grounds.`\
bg black,22

fede 0,1000
E_A

bg gakkou_03,22
ld r,NON_D6,24
;ld r,NON_D3a,80

bgm1 1

;「こっちが第２校舎で……。@あ、足元、段差があります。」\
`"And this is the second school building.... `@`Oh, watch your step."`\
;＜野々宮

;ld l,SH2_D1,2
;wait 1000
;ld l,SH2_D2,80

;「……ありがとう。@助かるよ、野々宮くん。」\
`"...Ah, thank you. `@`You saved me there, Nonomiya-kun."`\
;＜大人秋一

;　胸元には、来校者であることを示す名札が付けられている。@
`　A name tag affixed to the person's chest indicated that they were a visitor to the school.`@
br
;　少なくとも、彼がこの学校の生徒でもなければ先生でもないことは確かだった。\
`　At the very least, it was obvious that this man was neither a student nor a teacher of this school.`\
;ld l,SH2_D3,80

;「……………この場所が、どんな光景かはよく覚えているよ。@僕にとってここは、思い出深い場所だからね。@……この学校がどんな光景なのか、今も瞼の裏に焼き付いているよ。」@
`"........I remember this scene well. `@`It's a place filled with memories for me.`@` ...This image of the school is still burned into my retinas."`@
;＜大人秋一

ld r,NON_D2,80

;「それは、楽しい光景ですか…？」\
`"Are they fond memories...?"`\
;＜野々宮

;ld l,SH2_D2,80

;「……はは。@それはどうかな。@……僕のいた当時は、いじめや乱暴がとても多い荒れた時代でね。」@
`"...Haha. `@`I wonder.`@` ...Y'know, in my time, bullying and violence were commonplace."`@
;＜大人秋一
br
;　男性は軽やかに笑う。@
`　The man laughed.`@
;　その様子を見る限り、彼の在校時、あまり穏やかな生活が出来たようには思えない。\
`　Considering the way he reacted, it seemed unlikely that his time spent at this school was very pleasant at all.`\
;　しかし、あれから長い時間が経っている。@
`　However, a long time had passed since then.`@
br
;　仮にいじめられていたにしても、その痛みはすでに癒され、思い出と忘却の彼方のようだった。\
`　Even if he had been bullied, that pain had probably long since healed, and his memories of it faded away.`\
;ld l,SH2_D1,80

;「……僕は当時。@……この校舎裏がお気に入りでね。@休み時間は必ずここで過ごしていたよ。」@
`"...Back when I went here... `@`I always loved coming back here behind the school. `@`I always used to spend my break time here."`@
ld r,NON_D1,80

;「涼しいですよね、ここ……。」@
`"It is nice and cool back here, isn't it..."`@
;ld l,SH2_D2,80

;「うん。@ひと気もないしね。@お気に入りだったんだ。」@
`"Yes. `@`And not many people came back here. `@`It was my favorite place."`@
br
;　男性は木の幹を撫でながら、当時を振り返る。\
`　The man was reminiscing while stroking the trunk of a tree.`\
bg black,22
bg gakkou_02,22

;ld l,SH2_D1,80

;「僕は、将来は画家になりたいと思っていたんだ。」@
`"I remember that I had wanted to be an artist when I grew up."`@
;ld r,NON_D6,80

;「画家、ですか……。」\
`"An artist...?"`\
;ld l,SH2_D3,80

;「そう。@感動や感情を、スケッチブックに書き留めることに面白さを覚えていてね。@……毎日、ここでひとり、喧騒を逃れ、目に付いた何かをスケッチブックに書き留めていたんだ……。」\
`"Yeah. `@`I remember the fun I had recording all my inspirations and emotions in a sketchbook.`@` ...Every day I'd come here to get away from all the hustle and bustle and sketch whatever caught my eye..."`\ 
bg black,22
;bg gakkou_02,22

;　それはとてもとても昔の話……。@
`　It was a story from long ago....`@
br
;　まだ、この校舎が新校舎と呼ばれ、誕生したばかりの昔の話………。\
`　A story from when this building had just been built and was still being called the 'new' school building...`\
bg black,2

fede 0,2000
E_A

mono 1
bg gakkou_01,2
wait 1000

me1v 16,50

mono 0
print 2

;　いくつもの学校が統合されたマンモス校の誕生。@
`　A mammoth school created through the integration of many smaller ones.`@
br
;　それは通う生徒たちに動揺と混乱をもたらした。\
`　It led to disorder and unrest amongst the students that now attended.`\
;　そして彼らの混乱はそのまま、人ならざる者たちの世界にももたらされる。@
`　And their unrest was brought into the world of the supernatural as well.`@
br
;　混乱した魂たちのひしめき合う新たなカオスの誕生に、@有象無象の妖怪たちが群れに群れ、狂乱し、跋扈していた……。\
`　Many confused souls were crowded together under one roof, and from this newly born chaos, `@`came a wave of small-fry youkai, all running rampant.`\
bg black,22
bg rouka_04,22

bgm1 10

;「ギャギャギャギャア！！@　人間どもがイッパイだぜ！@　喰らい放題だぜ！！」@
`"Gyahahahaha!! `@`Man, this place is just PACKED with humans!! `@`Eat your fill, everyone!!"`@
;「何てデケェ学校だぁ！@　クソガキどもの魂でギュウギュウだぜぇ！！」@
`"This school is huuuuuuge! `@`It's just crammed to the brim with these little shits' souls!!"`@
;「集るんじゃねえや、クソ妖怪ども！！@　こいつらの魂は全部、俺ンだ！！」@
`"Hey, piss off you damn youkai!! `@`All these souls are mine, ya hear?!"`@
;「邪魔すんじゃねぇ、俺はハラペコなんだ！！@　殺す殺す殺ーすッ！！」\
`"Don't get in my way! I'm starving!! `@`Kill kill killllll!!"`\
me2v 17,50

;　教室にも、校庭にも廊下にも体育館にも。@
`　In the classroom, hallways, gymnasium and schoolyard...`@
br
;　まるで小魚の大群が渦を巻くかのように、無数の妖怪や悪霊がひしめき、互いを喰らい合っていた。\
`　Countless youkai and evil spirits swam about like giant schools of fish, all eating one another.`\
bg black,22
bg rouka_03,22

;　この学校にひしめく子供たちの魂。@
`　This school was filled with the souls of children.`@
;　存分に食い荒らせるのは、生き残った、強い妖怪だけだ。@
`　Only the strongest youkai survived to continue eating to their heart's content.`@
br
;　生き残るには、他の妖怪たちを喰らい、誰よりも早く強くなるしかない。\
`　The only way for them to avoid being a meal for another youkai was to become stronger and faster than those around them.`\
;　子供たちは学校から逃げない。@
`　The children couldn't escape from the school.`@
;　ならば、先に喰らうべきは子供たちじゃない。@邪魔になる他の妖怪たちだ。@
`　So eating them could wait. `@`Instead, the first to get eaten were the youkai who impeded the progress of others.`@
br
;　人ならざる者にしか見ることの出来ぬ、@……弱肉強食の、恐ろしい生存競争が、学校中で繰り広げられていた。\
`　A struggle for survival of the fittest spread out across the entire school.`@` ...A battle where the only witnesses were those unearthly beings.`\
bg black,22
;bg white,1

;wait 1000

bg bite,22
se1 36
quakey 6,700

;「俺サマが最強だァ！！@　俺サマの邪魔をするヤツはみんな食い殺してやらァ！！」@
`"I'm the strongest!! `@`I'll kill all o' you bastards that get in my way!!"`@
;「食って強くなるんだ、食って強くなるんだ！@　フヒヒッ、弱そうな妖怪はいねぇかぁ！！」@
`"Eat and get stronger! Eat and get stronger! `@`Fuhihihihi! Any weak youkai around here?!"`@
;「強ぇ妖怪を喰らえば、たくさんの妖力が蓄えられるゾ！！@　俺たちクズ妖怪でも、群で襲えば勝てるゾ勝てるゾ！！」\
`"The stronger the youkai we eat, the more spiritual power we store up!! `@`If we attack in groups, even us weak youkai can win!!"`\
se3 66
bg white,1
bg bite,22
se1 36
quakex 5,600

;　弱い妖怪たちも、巨大な大群となれば、それは恐ろしい力を持つ。@
`　If the weaker youkai formed a giant group even they held a startling amount of power.`@
br
;　そのうねる巨体が、いくつもの教室を巡っては、そこを根城にしようとしていた妖怪たちを食い殺していく。\
`　The undulating mass swept many classrooms, devouring the youkai trying to entrench themselves inside. `\
bg black,22
bg rouka_01,22

me3v 28,70

;「ギャッハー！！！@　俺たちはクズじゃねぇ！！@　群れれば最強ダァ！！」@
`"Gyaahaha!! `@`We're not worthless!! `@`When we've got the numbers we're the strongest!!"`@
;「もう職員室も俺たちのものだゼ！！@　次だ次だ、次だ次だッ！！」\
`"The staff room is already ours!! `@`Go to the next room, go go go!!"`\
;「次はどこだ？」@
`"Where do we go next?"`@
;「保健室ダァ！！」@
`"The infirmary!!"`@
;「保健室は、変な人形に取り憑いたヤツが根城にしているらしいゾ！！」\
`"I heard that there's someone in there who's possessing a strange doll."`\
;「その肥えた妖力、俺らで食い尽くしてパワーアップだぁああぁあああ！！」@
`"We'll consume them and gain their powerrRRaaaAAH!!"`@
br
;　大蛇のようなうねりが職員室を飛び出し、廊下で螺旋を描きながら保健室の扉を破って飛び込む。\
`　Like a serpent, they wound out of the staff room and into the hallways before forming into a spiral and smashing through the infirmary door.`\
mov %HIG_Isyou,2
bg white,23
bg hoken_01,23

ld c,HIG_D9,2

;「………………………………。」@
`"................."`@
;＜彼岸花
br
;　保健室の妖怪、踊る彼岸花は、ぐるぐると渦巻く妖怪たちの群の中心で、@漂うかのように宙に浮かんでいる。@
`　The youkai of the infirmary, the Dancing Higanbana, floated lazily in the air, `@`as the mass of youkai circled around her. `@
;　その表情は、まだまどろみの中にいるかのよう……。\
`　She looked as if she was still sound asleep...`\

;「ギャギャア！！@　旨そうだぜ、この人形！@　かなり妖力を溜め込んでやがるッ！！」@
`"Gyaaahaha!! `@`She looks delicious! `@`She's got so much spiritual energy!!"`@
;「その妖力、いただきだぁああぁあああぁッ！！！」@
`"Consume that energggyyyYYyyy!!!"`@
;「食わせろッ、食わせろ食わせろ食わせろッ！！」\
`"Eat it, eat it, eat it!!!"`\
;「んんん？@　ビビってんのかァ、この人形ぉおおぉ！！」@
`"Hmmm?? `@`Are you scared, little dollyyyy?!"`@
;「何か言ってやがんゾ！@　小さい声で聞こえねぇヤ！！@　おいお前ェら、静かにしろ！！@　俺たちに食い尽くされる前に、最期に一言くらい言わせてヤレ！！」\
`"Speak up! `@`I can't hear your tiny little voice! `@`Hey shut up, everyone!! `@`Before we eat you up, let us hear your last words!!"`\
fedexx 0,50,0,0,0,0,1000
E_B
E_M2
E_M3

;　ぐるぐると渦を巻く妖怪たちの群が、びたっと止まり、台風の目の中のような静寂が訪れる。@
`　The maelstrom of monsters slowed to a halt, and became as still as the eye of a storm.`@
br
;　……だからようやく、……彼岸花が口にした言葉が聞き取れる。\
`　...Finally... they were able to hear the words coming out of Higanbana's mouth.`\
ld c,HIG_D8,80

;「…………食わせて………。」@
`"....Feed me...."`@
br
;　その表情は淡白なまま。@……眼差しは透明で遠く、心ここにあらずという感じだった。\
`　Her facial expression didn't change.`@` ...Her gaze was empty and her mind blank.`\
;　それは死を前に達観しているのとは少し違う。@
`　It wasn't quite the expression you'd expect from someone contemplating their own death.`@
br
;　目の前の妖怪たちの暴風がまるで、……数枚の木の葉が舞う、つむじ風程度にしか見えていないかのよう……。\
`　The storm of monsters before her... fluttered like the leaves of a tree being blown about by a whirlwind...`\
textoff
fede 0,1000
E_A

ld c,HIG_D9,80

;「……お前たちをみんな。@……私に、……食わせてちょうだい。」@
`"...All of you.`@` ...Feed... me."`@
br
;　西洋人形が、……ひらりと舞った。\
`　The Western doll... danced gracefully.`\
se1 66
bg white,8
bg aka3,1
se2v 84,100
quake 7,800
wait 500
bg black,2
wait 1000
bg rouka_04,2

bgm1 27

;　保健室に、彼岸花と名乗る恐ろしい妖怪が住み着いている。@
`　The fearsome youkai known as Higanbana settled in the infirmary.`@
;　その噂はやがて、学校に跋扈する妖怪たちで知らぬ者はないほどになった。@
`　Before long there wasn't a single youkai rampaging through the school that didn't know her name.`@
br
;　強い妖怪を喰らえば、それだけ大きな妖力を得られる。@だから、強さが知れ渡ることはさらなる死闘を呼び寄せることとなった。\
`　If a strong youkai is consumed, the large amount of spiritual power they had would transfer to the one who ate them. `@`So, once a youkai's strength became well known, that only caused more youkai to come asking for a fight to the death.`\
bg black,22
se1 36
bg BLADE2W,1
quakex 5,600
bg black,22
bg hoken_01,0
ld c,HIG_D9,22

;　彼岸花は敵を屠る時、……楽しくもなければ、悲しくもなかった。@
`　When she slew her enemies... Higanbana was neither happy nor sad.`@
br
;　彼女にとって、自分の存在する目的はひとつだけ。\
`　She only had one goal in life.`\
;ld c,HIG_D9,80

;　ただ、生きること。@
`　To keep living.`@
br
;　そして生きるためには、誰よりも多くの妖力を得て、強さを身に付けなければならない。\
`　To do so, she had to gather more spiritual energy, and become stronger than anyone else.`\
;　だから日々、常に何者かと殺し合い、あるいは騙し合い。@
`　That's why every day she would deceive and kill.`@
;　時には姿を隠して逃れ、裏をかいたり、あるいはかかれたり。@
`　Sometimes she would conceal her form and then either flee or sneak an attack on her opponent from behind.`@
br
;　彼女の毎日は、殺すか殺されるかの二つだけで全て表現できた。\
`　Every day her life could be defined a single expression: 'kill or be killed.'`\
bg hoken_05,22

;　……彼女はとりあえずのところ、まだ生きている。@
`　....For the time being, she was alive.`@
;　まだ生きているということは、……生き残れる程度の妖力を身に付けたということ。@
`　The fact that she was still alive... meant that she had gathered enough spiritual power to survive.`@
br
;　そしてそれは、さらなる強さを求める妖怪たちを、さらにさらに呼び寄せる……。\
`　And that power just kept drawing more youkai to her like a beacon...`\
bg black,22

;　迂闊に傷付き弱れば、好機とばかりに弱い妖怪たちが群れてくる。@
`　If she ever carelessly allowed herself to be wounded, the weaker youkai would jump on the opportunity and swarm her.`@
br
;　しかし力を付ければ付けるほどに、破格の獲物とばかりに強い妖怪たちが群れてくる。\
`　But if she gained too much strength, the stronger youkai would consider her too great a prey to overlook, and swarm her.`\
;　彼岸花にとって、今日、まだ命があるのは、己が強いからではない。@
`　Higanbana was not still alive today because she had strength.`@
;　彼女が強いのは、今日まで生き残ったことに対する結果でしかない。@
`　It was the exact opposite -- she had strength because she had survived until today.`@
br
;　彼女にとって、まだ命があるのは、………ただ、幸運だったに過ぎないと思っていた。\
`　She knew that the only reason she was still alive.... was nothing more than good luck.`\
bg Different_spiral_1b,22

me1v 5,50

;　今日を生き残れたとて、明日も生き残れる保証はない。@
`　There was no guarantee that she would survive either today or tomorrow.`@
br
;　自分が今日を生き残ることと引き換えに、誰かを殺して喰らったように。@明日は誰かが私を殺して喰らうかもしれない。\
`　Just like she killed someone this day in order to live, `@`she could easily be killed by someone else the next day.`\
;　………そんな、死線を潜り続ける日々に、@……彼女の表情は、喜びはおろか、怒りや悲しみさえ浮かぶことはない。@
`　....She lived every day on the verge of death.`@` ...Never showing anger, sadness, or least of all, happiness.`@
;　ただただ、………今日を生きるためだけに、誰かを喰らい続ける。@
`　All she did... was keep killing to survive the day.`@
br
;　そんな、……感情なき、肉食植物のような日々。\
`　She spent those days... emotionlessly, like a carnivorous plant.`\
bg black,2

fede 1,1000
E_B
wait 1000

bg okujou_01,2

;　……時に、静寂が訪れる。@
`　...Occasionally there was a lull in the attacks.`@
br
;　そんな時、彼女は屋上を好む。@
`　When that happened she preferred to visit the rooftop.`@
;　そして強い風に長い髪を散らし、……感情なき一輪の花のように、そこにたたずむのだ。\
`　She let the strong wind blow her long hair... as she stood emotionlessly, like a solitary flower.`\
ld c,HIG_D9,22

;「…………………………………。」\
`".................."`\

;　今日も、生きている。@
`　She was alive today, as well.`@
br
;　生きていると、考えることが出来る。\
`　When she was alive, she could think.`\
;　生きるために、生きる日々。@
`　She lived to live.`@
;　傷つけ、傷つけられ、殺し、殺され。@
`　Hurt or be hurt. Kill or be killed.`@
br
;　それが延々と、……尾を呑み込んだ蛇のように、繰り返される日々。\
`　These days repeated endlessly... like a serpent swallowing its own tail.`\ 
;ld c,HIG_D10,80

;　それをいつまで続ければいいのか。@
`　How much longer must this continue?`@
br
;　……彼岸花には、自分という存在が、わからなくなっていた。\
`　Higanbana no longer understood her own existence.`\
bg black,22

;　いや、それは正しい表現ではない。@
`　No, that wasn't quite right.`@
;　なぜなら彼女は一度だって、自分という存在が、@何のために在るのかを理解したことなど、ないのだから。@
`　Because that would imply that at one point she knew the reason for her existence. `@`But she did not. Not before and not now.`@
br
;　わかることはひとつだけ。@
`　There was only one thing of which she was certain:`@
;　死にたくないこと。\
`　She didn't want to die.`\
bg Air_02,22

;　だけれども、生き続けるには、日々、傷つけ、傷つけられ、苦痛に呻き合う。@
`　To keep living she would hurt and be hurt, and moan in pain.`@
;　死なないためだけに、……毎日を苦しむ。@
`　She suffered every day... just so she wouldn't die.`@
br
;　自分がなぜここに在るのか。@
`　Why was she here?`@
;　……わかるわけもなかった。\
`　...She had no way of knowing.`\
bg black,22
bg okujou_02,22

;　今は、静寂。@
`　It was silent.`@
br
;　誰も襲ってこない、黄昏時のわずかの空白。\
`　This dusk offered a small break from any coming to attack her.`\
;　頭を空にして、……殺し合いの熱を、わずかでも冷ます。@
`　She cleared her head... and took a short time to relax from the killing.`@
br
;　それだけが出来ることで、……多分、それだけが、彼女の感じられるわずかの愉悦だった。\
`　This was, perhaps, the only way... that she ever felt any miniscule amount of joy.`\
ld r,HIG_D8,22

;「……………………………。」@
`"..............."`@
br
;　今日は危なかった。\
`　Today had been a perilous day.`\
bg black,0
ld l,AZA_D2,0
ld c,SMI_w5,22

me2v 17,50

;　アザミとスミレの姉妹に執拗に狙われ、あとわずかで殺されるところだった。@
`　She had been targeted relentlessly by the sisters Azami and Sumire, and had almost been killed.`@
br
;　あの二人、取るに足らない弱小妖怪だと思っていたら。@……いじめを狩場に、子供たちの魂をたくさん喰らい、いつの間にか侮れない妖力を蓄えた。\
`　She thought that they had been insignificant lesser youkai.`@` ...But they had been using bullying to eat the souls of so many children that without Higanbana noticing, they had gathered a formidable amount of spiritual power.`\
ld l,AZA_D3,0
ld c,SMI_w6,80

;　……生き延びたければ、強くなるしかない。@
`　If she wanted to survive, she had no choice but to become stronger.`@
br
;　それが弱肉強食の人ならざる世界の、唯一の処世術。\
`　That was the single path to success in this survival of the fittest world of the supernatural.`\ 
bg black,22
fede 12,1000
E_M2

bg okujou_02,0
ld r,HIG_D8,22

;「………私も、……生きるために、狩りをしないとね………。」@
`"....In order to live... I must hunt..."`@
br
;　今日まで彼岸花は、人間の魂を狩りの対象としたことはない。@
`　Before today, Higanbana had never hunted the souls of humans.`@
;　生き残るために、襲い来る無数の妖怪たちを殺し、喰らい、それによって妖力を蓄えてきただけだ。\
`　All she had done to gain spirit energy before now was kill and eat the countless youkai that attacked her.`\
;　しかし、それだけでは足るまい。@
`　However, that was not enough.`@
;　積極的に狩りをし、より多くの妖力を蓄えなければ。@
`　She had to hunt more actively, and gain much more power.`@
br
;　それが、生き延びるために出来る、唯一の努力。\
`　That was the only thing she could do to survive.`\
ld r,HIG_D9,80

;　……人間の、獲物。@
`　...Human prey.`@
br
;　誰でもいい。@どこかに、適当な誰かがいないものか……。\
`　Anyone would be fine. `@`Surely, there'd be a suitable target somewhere...`\
bg black,25
bg gakkou_02,22

;　ふと眼下を見下ろすと、……そこは校舎裏。@
`　By chance, she happened to look down... and there behind the school building...`@
br
;　数人の男子の人だかりがある。@
`　There was a crowd of boys.`@
;　……どうやら、彼らの狩りらしい。\
`　...Apparently, they were hunting.`\
;　人間もまた、狩りをする。@
`　Humans hunted too.`@
;　集団で個人を攻撃して、その魂を刈り取る、いじめという名の狩り……。@
`　A type of hunting where a large group would attack an individual, reaping their soul. It was called bullying.`@
br
;　それがひと段落し、彼らはその場に犠牲者を残し、立ち去っていく。\
`　Once they were finished, they walked off and left their victim sitting there.`\
;「………食いカス、……か。」@
`"....Leftovers... huh?"`@
br
;　どこの誰だか知らないけれど。@
`　She had no idea who this boy was.`@
;　ふと見下ろしたら、目に付いた。@……狩りの動機はその程度でいい。@
`　She had just happened to look down and see him there.`@` ...But that was all the incentive she needed to start her hunt.`@
br
;　彼岸花は屋上より、ふわりと飛び降りる。\
`　Higanbana jumped from the rooftop and began to float gently down.`\
bg black,25
wait 500
bg gakkou_03,25
;quakey 1,100

wait 500

;　いじめられていた少年は、よろりと起き上がり、木陰にしゃがみ込んでいた。@
`　The bullied boy had unsteadily stood up and was now squatting next to a tree.`@
br
;　そして、大事そうに抱えていたスケッチブックを広げ、鉛筆を走らせ始める。\
`　Then, he opened an important-looking sketchbook, and began running a pencil over one of its pages.`\
;「……………変な子。」@
`".........What a strange child."`@
br
;　ついさっきまでいじめられていたのだ。@
`　Just a moment ago he was being bullied.`@
;　それから解放されて最初にやることが、@涙を拭うことでもなければ地団太を踏むことでもなく、スケッチブックを広げることなんて。\
`　And then the very first thing he did after being let go, `@`was not to wipe away his tears, or stamp his feet in anger, but to open his sketchbook.`\
ld c,HIG_D9,5

;　彼岸花は、ふわりと少年の前に降り立つ。@
`　Higanbana gently landed in front of the boy.`@
br
;　人ならざる者の姿は、人間には見えない。@稀な例外を除いて。@
`　Youkai are not visible to humans. `@`Save a few rare exceptions.`@
;　だから、少年の目が確かに自分の姿を追って、彼岸花はわずかに驚いた。\
`　So Higanbana was slightly taken aback when she noticed that his eyes were following her.`\
textoff

fede 0,1000
E_A

ld l,SHU_D6,26
;ld l,SHU_D1,80

;「………君、………今、空から降りてきたよね……？」@
`"....Did.... Did you fall from the sky just now?"`@
;＜秋一

bgm1 33

cl c,0
ld r,HIG_D9,23

;「……あなた、……私の姿が見えるの……？」@
`"....You... can see me...?"`@
br
;　それが彼岸花にとって、初めての人間との会話だった。\
`　That was the first conversation that Higanbana ever had with a human.`\
bg black,2
wait 1000
bg gakkou_02,2

;「……何をやってんの。」@
`"...What're you doing?"`@
;「絵を描いてるんだよ。」@
`"Sketching."`@
;「……何の絵……？」@
`"...Sketching what...?"`@
br
;　少年はさっきからスケッチブックに絵を描いている。@
`　The boy had been drawing pictures in his sketchbook for quite a while.`@
;　しかし、何を描いているのか、よくわからなかった。\
`　But, she had no idea what he was drawing.`\
;　目の前の草木を描いているようにも見えるのだが、決して写実的ではない。@
`　It looked as if he was drawing the leaves in front of him, but it lacked realism.`@
;　鋭く誇張され、毛羽立ったライン。@
`　The lines were fuzzy and greatly exaggerated.`@
br
;　まるで抽象画のように見えた。\
`　Almost like an abstract painting.`\
bg black,22
bg gakkou_03,0
ld r,SHU_D1,0
ld l,HIG_D10,22

ld r,SHU_D2,80

;「これは、今の僕の感情。」@
`"These are my feelings, right now."`@
ld l,HIG_D9,80

;「…………感情？」@
`"....Feelings?"`@
ld r,SHU_D4,80

;「そう。@……いじめられて、悔しかったという、今の僕の感情だよ。」\
`"Yes.`@` ...These are my feelings of frustration at having been bullied."`\
;　そう言われてスケッチブックを見直すと、……確かに何となくわかる。@
`　She looked at his picture again bearing this in mind... and somehow, it made sense to her.`@
br
;　目の前の校舎裏の景色が、@心情というフィルターを通して、悔しさに歪んで描かれていることが理解できる。\
`　She realized that he was drawing what this view behind the school looked like to him, `@`when it was warped by his feelings of frustration.`\
ld l,HIG_D10,80

;「何でそんなことを？」\
`"Why are you doing that?"`\
ld r,SHU_D1,80

;「嫌な感情は、こうしてスケッチブックに吐き出して閉じ込めるんだ。@……絵になれば、それはもうただの感情じゃない。@今日、僕が確かに経験した、生きた証になるんだよ。」\
`"I'm putting all my negative emotions into this sketchbook and locking them away.`@` ...When I transform them into pictures, they're no longer just emotions. `@`They're proof of what happened to me today."`\
ld l,HIG_D9,80

;「…………………？」\
`"............?"`\
;　やはり、人ならざる存在の自分が見えてしまうだけあって、@どこか普通の人間とずれているようだった。@
`　She expected as much. `@`It stood to reason that any human who could see her would be a little 'off' compared to normal humans.`@
br
;　しかし、彼岸花は、彼が言った一言に、なぜかとても興味を覚えた。\
`　But, for some reason, Higanbana was very intrigued by what he had said.`\
;cl l,0
;ld c,HIG_D10,23

bg black,22

;「生きた証って、……何よ。」@
`"What do you mean by... 'proof of what happened'?"`@
;cl r,0
;ld l,SHU_D4,24

;「簡単に言えば、今日を生きた記録。@……日記みたいなものかなぁ。」\
`"In a nutshell, it's a record of my life.`@` ...Like a diary, I guess."`\
bg gakkou_02,22
ld r,HIG_D8,22

;「形ある者は、ただ在り続けるために生きているんでしょう？@　それを記録することに、価値なんてあるの…？」\
`"Don't things with life continue living just so they won't die? `@`What's the point in making a record of that...?"`\
ld l,SHU_D1,23

;「それって、生きるために生きることが、ただ生きるための目的、ってこと？」@
`"Do you mean to say that staying alive is the only point to life?"`@
ld r,HIG_D10,80

;「……そうじゃないの？」\
`"...Isn't it?"`\
ld l,SHU_D3,80

;「それだけじゃ、面白くないんじゃないかなぁ。」@
`"I don't know, that doesn't sound very fun."`@
ld r,HIG_D9,80

;「…………………………。」\
`"................."`\
;　面白く、ない。@
`　Not fun.`@
br
;　……………その一言は、彼女を毎日苛む、不思議な感情を、短く正確に捉えていた。\
`　........The strange feeling that had tormented her day after day, was just summed up in two words.`\
bg black,22

;　そうだ。@私は今日まで、生きていて楽しいと思ったことはない。@
`　That's right. `@`I've never once considered living to have fun.`@
;　ただ死にたくないから生きてきただけだ。@
`　I just lived because I didn't want to die.`@
br
;　生きることで何かを得られるから生きているわけじゃない。\
`　I never thought that I could obtain something from living.`\
bg usagi_01,22
;ld l,hig_D8,0
;ld r,shu_D4,22

;ld l,HIG_D10,80

;「じゃあ。@……あなたは日々、何が面白いって言うの。」\
`"Well... `@`What do you consider to be fun in life?"`\
ld c,SHU_D3,22

;「感情だよ。@喜怒哀楽。@色んなことを日々、感じるでしょ？」@
`"Feelings. `@`Emotions. `@`We feel so many of them every day, right?"`@
;ld l,HIG_D9,80

;「…………………………。」\
`"..............."`\
ld c,SHU_D1,80

;「それを率直に楽しむんだよ。@それを、僕はスケッチブックに描いてるんだ。@……見て。@ほら。」@
`"Quite honestly, I enjoy them. `@`I make pictures of them in my sketchbook.`@` ...Here, `@`look."`@
br
;　少年はスケッチブックを捲り、過去のページのいくつかを私に見せる。\
`　The boy flipped through some of the previous pages to show me what he had drawn in the past.`\
se1v 1010,30

bg white,22
bg Air_02,22

;「この日の気持ち、わかるかなぁ。」@
`"Can you tell what I was feeling on this day?"`@
;「…………………………。」@
`".............."`@
br
;　柔らかな線、躍動する線が、何か豊かな感情を示してる。\
`　The light and lively lines suggest some sort of plentiful emotion.`\
;「これは、とても嬉しいことがあった日の感情。@じゃあ、これはわかる？」@
`"I was very happy on this day. `@`Here, what about this one, can you tell?"`@
se1v 1010,30
;「…………………………。」@
`".............."`@
br
;　少し深くて、わずかに重い線。@何かの失敗か後悔を感じさせる。\
`　These lines were thick, and somewhat heavy. `@`They gave a feeling of some sort of failure or regret.`\
;「これは、友達との約束をうっかり忘れて、失敗してしまった時の感情。@じゃあ、これは？」\
`"This was when I carelessly forgot about something I promised my friend. I felt like I had failed him. `@`Here, what about this one?"`\
se1v 1010,30

bg black,22
;bg Different_spiral_1b,22

;　暖かさを感じさせる豊かな線が描く絵。@
`　There were sketches drawn with rich lines, that gave off a warm feeling.`@
br
;　逆に、殺伐とした荒涼感を覚えさせる絵。@
`　And there were sketches that reminded her of a desolate bloodthirsty feeling.`@
br
;　ほとばしる稲妻のような線が描く絵に、柔らかな春の芽吹きのような線が描く絵。\
`　Sketches like a flash of lightning, and sketches like budding flowers on a gentle spring day.`\



;　それらは、日記としては確かに未熟だろう。@
`　They were awfully vague for a diary.`@
;　その絵だけを見て、その日に何があったのか、想像することは難しい。@
`　It would be very hard to guess what had happened on each of these days if you were just looking at the sketches without context.`@
br
;　……しかし、感情だけはわかる。@
`　....But they did portray emotions.`@
;　その絵を描いた時、彼がどんな感情を持っていたか。@それを読み取ることだけは出来るのだ。\
`　If there was one thing you could gather from his sketches, `@`it was what he was feeling at the time he drew them.`\
;bg black,22
mld r,HIG_D9,22
;mld r,HIG_D1,80

;　だから。@彼のスケッチブックは、ページを捲るごとに様々な感情が、まるで玉手箱のように飛び出した。@
`　So,`@` with each page you turned in his sketchbook, various emotions would jump out of it, like Pandora's box.`@
; ^^^ Note To Editor: Tamatebako - http://en.wikipedia.org/wiki/Tamatebako  Closest thing we have is pandora's box. Pascal suggested a jack-in-the-box, that could work too.
br
;　それは、……私にとってあまりに斬新で新鮮な驚きだった……。\
`　It was... a new and novel wonder to me...`\
;　感情。@
`　Emotions.`@
;　理念はわかる。@
`　I understand the concept.`@
;　自分の状況に対する、心が示す色だ。@
`　It's the color your heart takes on based on what happens around you.`@
br
;　色？@　……私の、ただ生きる日々に、色などあっただろうか？\
`　Color?`@` ...Do the days that I spend doing nothing more than living actually have a color?`\
;mld r,HIG_D10,80

;　ただ、生きるだけ。@
`　I'm just living.`@
br
;　何も面白くない、ただ生きるためだけに生きる日々に、色など、あるわけもない。\
`　My days aren't fun, I just live to keep living. I doubt they have a color at all.`\
;mld r,HIG_D1,80

;　しかし、このスケッチブックにはそれがある。@
`　But this sketchbook was filled with emotions.`@
;　愉快な感情だけじゃない。@不愉快な感情の数々さえ、それらはまるでハーモニーのよう。@
`　And not just pleasant emotions. `@`There were plenty of unpleasant ones too. All these emotions blended together to create a sort of harmony.`@
br
;　ページを捲る度に、数々の感情が歌い出す驚きに、@……私は、ただただ、茫然とするしかなかった……。\
`　Every time he turned a page, I was stunned.`@` ...Each time a slew of emotions would sing out...`\
bg gakkou_03,0
ld l,SHU_D1,22
ld l,SHU_D4,80

;「彼岸花さんって、妖怪なんでしょ？@　妖怪って、日々、どんな感情で生活しているの？」@
`"Higanbana-san, you're a youkai, right? `@`What kind of emotions do youkai feel during their lives?"`@
mld r,HIG_D9,80

;「………………………………。」\
`"................."`\
;　何も、答えることなど思いつかない。@
`　She couldn't think of an answer.`@
;　ただ、生きるためだけに生きる日々。@そこに感情など存在しない。@
`　She just lived to live. `@`There was no emotion in that.`@
br
;　だからつまり。@……自分の存在など、@このスケッチブックの前には、消しゴムのカスほどの存在価値もなかった。\
`　In other words... `@`when compared to this sketchbook, `@`her own existence wasn't even worth the eraser shavings left over from a mistake.`\
mcl r,0
bg black,22

me1v 5,50

bg Air_02,22


;　だから、私は初めて思った。@
`　So for the first time, I thought.`@
;　自分を、………不憫な存在だと思った。@
`　I thought... about my pitiful existence.`@
br
;　何も口に出来ず、俯く私に、……気付けば彼は、スケッチブックを向けていた。\
`　He watched me as I stood there, silently, eyes cast down... and then he started to draw.`\
;「…………何を……？」@
`"......What are you doing...?"`@
;「今日。@……学校に住む妖怪と出会えたという驚きの感情を書き留めてるんだよ。@ほら。」@
`"I'm recording... `@`the surprise that I felt today from meeting a youkai who lives at the school. `@`Look."`@
br
;　彼が、ほらと見せるスケッチブックのそこには。@
`　There, in his sketchbook...`@
;　……茫然と立ち尽くす自分の姿が、新鮮な驚きに満ちた線で、描き出されていた……。\
`　...was me, standing still in shock, drawn with lines full of surprise...`\
bg black,22
bg gakkou_08,0
ld r,SHU_D4,0
ld l,HIG_D10,22

ld l,HIG_D9,80

;「…………あなた。@……何者……？」@
`"......Who...`@` are you...?"`@
ld r,SHU_D1,80

;「ただの人間だよ。@名前は、有森秋一（ありもり　しゅういち）。」\
`"Just a human. `@`My name is Shuuichi Arimori (有森秋一)."`\
bg white,42
bg black,2

fede 1,2000
E_B
wait 1000

bg Air_01,22
wait 2000

bg rouka_04,22

bgm1 10

;「ギャアギャア！！@　恐ろしや恐ろしや！！@　保健室には近寄るな、近寄るな！！」@
`"Gyagyaaaaa!! `@`The horror! The horror! `@`Keep away from the infirmary!! Keep away!!"`@
;「保健室には恐ろしい妖怪が住み着いているゾ！！」@
`"A terrifying youkai is living in there!!"`@
;「そやつの名は、踊る彼岸花！@　残酷な残酷な妖怪だぞ！！」\
`"Her name is the Dancing Higanbana! `@`A cruel youkai if there ever was one!!"`\
bg rouka_03,22

;「ならばきっと、たっぷりの妖力を蓄えているはず！@　喰らえば、それは全て我らのものよ！！」@
`"Then she must be packed to the brim with energy! `@`If we consume her, it'll all be ours!!"`@
;「喰わせろ、彼岸花ぁああぁあ！！@　お前の手を足を、頭を肝を心の臓を食い千切らせろぉおお！！」\
`"We'll eat you, Higanbanaaaaa!! `@`Your legs, your arms, head, heart and liver -- we'll tear them to pieces!!"`\

bg black,0
ld c,HIG_D8,22


;「…………死にたくばいらっしゃい。@踊りたくばいらっしゃい。@この彼岸花、……お望みならば、好きなだけ遊んであげるわ。」\
`"......Enter, if you wish to die. `@`Enter, if you wish to dance. `@`I, Higanbana... will grant your wish, and play with you all you want."`\
;ld c,HIG_D1,80

se1 66
bg bite,2

E_MA

se2 36
quakey 5,600

;「「「キシャアアアアアアァアァッ！！」」」/
`"""Gyaaaaahaaaaaaaaaaaaa!!"""`/
quakey 2,300\

bg black,28
bg black,0
ld c,HIG_D9,22

se1 66
bg white,8
se2v 36,100
bg aka3,1
quake 7,800

;　引き裂き、食い千切り。@
`　Shredded skin, devoured flesh.`@
;　ぶちまけ、引き抜き、噛み潰す。@
`　Spewed blood, removed guts, chewed remains.`@
br

se3v 36,100
bg white,23
bg blood_1aR,1
quakex 2,300

;　壁にはべっとりと、怨嗟の内臓をぶちまけた妖怪たちの骸がはりつき、どろどろの血を滴らせる。@
`　The lifeless, begrudging bodies of the youkai splattered against the wall, their entrails torn out and blood trickling from them.`@
;　まだ死にきれない、臓物を噴き出した妖怪たちが、苦悶に呻き、彼岸花を呪う……。\
`　Though disemboweled, they were not fully dead yet, and they cursed Higanbana with their last anguished moans...`\
bg black,22

me1v 16,50

bg hoken_04,22

;　人ならざる者たちにとって、……保健室は、異形の屍で埋め尽くされていた。@
`　As a non-human would see it... the infirmary was filled with grotesque corpses.`@
br
;　その、内臓と血しぶきのべっとりとした部屋の中でも、……彼岸花にそれが赤く見えることはない。@
`　But even this room splattered with blood and innards... didn't look red to Higanbana.`@
;　ただ、退屈で荒涼とした、灰色に見えるだけだった。\
`　It looked like nothing more than a dull and boring grey.`\
mbg black,22

fede 1,1000
E_B

mbg hoken_05,22

;　……それでも、それを退屈なことだと認識できただけ、彼岸花は少し変わったのかもしれない。@
`　...Still, maybe the fact that she was able to realize that she was bored meant that she had changed a little.`@
br
;　苔やカビは、自分の日々を退屈だなどと思いもしないはず。@
`　Things like moss and mold aren't aware of boredom.`@
;　それを認識できたということは、彼岸花がそれらとは異なる存在に成長したことを示すのだから。\
`　So because she is aware of the tedium of her life, that indicates that Higanbana has grown beyond that sort of existence.`\
mbg black,22
mcbg 22
ld c,HIG_D8,2

;「…………………………………。」@
`".................."`@
br
;　全身に浴びた、魑魅魍魎たちの返り血は、しばらくの間、雑魚どもの群を遠ざけてくれるだろう。\
`　Having just covered herself in the blood of evil river and mountain spirits, the rest of the groups of small fry would probably leave her alone for a while.`\
cl c,22
bg black,22
bg okujou_01u,22
ld c,HIG_D9,22

;　彼岸花はふわりと屋上へ上がり、眼下を探す。@
`　Higanbana gracefully ascended to the rooftop and scanned the ground below.`@
br
;　そして秋一の姿を見つけ、ふわりと飛び降りる。\
`　Seeing Shuuichi's figure, she jumped gently down.`\
bg black,22

bg gakkou_02,22

;　……秋一の魂を、魅力的だとは思っていない。@
`　...She didn't find Shuuichi's soul that appealing.`@
br
;　しかし、彼のスケッチブックと、そこに描かれている何かは、@………自分に、何かを教えてくれるような予感をさせるのだ。\
`　But she had a feeling that there was something drawn within that sketchbook of his... `@`that could teach her something.`\
bg black,22

fede 0,1000
E_A

bg gakkou_03,22

bgm1 14

;　その日も、秋一は何人かの男子生徒達に殴られていた。@
`　That day, Shuuichi had been beaten by a group of male students.`@
br
;　秋一は無抵抗主義らしく、彼らは秋一をサンドバッグと呼んで、連日、好き放題にしていく。\
`　Because of Shuuichi's pacifist tendencies, they would call him a punching bag, and slam their fists into him day after day.`\

ld r,HIG_D9,22

;「………今日も随分やられたわね。」@
`"....You were hit quite a bit today, huh?"`@
br
;　声を掛けると、地面にうつぶせに倒れていた秋一が、ゆっくりと顔を上げる。\
`　She called out to Shuuichi as he lay prone with his face in the ground, and he looked up slowly.`\
ld l,SHU_D5,6
ld l,SHU_D4,80

;「あぁ、彼岸花さん。@こんにちは。」@
`"Ah, Higanbana-san. `@`Hello."`@
br
;　たった今、酷いいじめを受けていたはずなのに、けろりとした様子で挨拶する。\
`　Even though he had just received an awful beating, he greeted her nonchalantly.`\
;　もちろん、悔しい感情はあるだろう。@
`　Of course, he did feel frustrated about having been bullied.`@
;　しかし、その感情の揺らめきさえも、彼には今日という日を生きた証。@
`　However, even that little flicker of emotion was still proof that he'd survived the day.`@
br
;　いつものように、大事に抱えていじめっこたちから守っていたスケッチブックを開き、@その感情を描き始める。\
`　As usual, he opened his precious sketchbook that he had kept safe from the bullies, `@`and began recording his feelings.`\
;　理不尽ないじめに対する胸中を現すように、その絵は悲壮感に満ちている。@
`　In order to express the emotions he had from dealing with such unreasonable bullying, this picture was filled with a sense of despair.`@
br
;　決して、幸せな経験ではない。\
`　It was by no means a happy experience for him.`\
;　しかし彼は、そのようなことすらも、@いくつもの感情を描いたこのスケッチブックの中に混じってしまえば、@色とりどりの万華鏡のように見えるという……。\
`　But he did this for every emotion he felt, `@`so that if you were to mix the pages of the sketchbook together, `@`it would look like a multicolored kaleidoscope...`\
;　その精神的なしぶとさに、彼岸花は尊敬と呆れの入り混じった感情を覚え、肩を竦めるのだった。\
`　Higanbana shrugged her shoulders, with both a sense of amazement and respect for his mental and emotional tenacity.`\
textoff
fede 0,1000
E_A

ld l,SHU_D1,80

;「彼岸花さんは、今日はどういう日だったの。」\
`"How was your day today, Higanbana-san?"`\
ld r,HIG_D8,80

;「……今日も、性質の悪い雑魚妖怪どもの群に襲われたわ。@……噛まれたり、引っ掛かれたり、呪われたり嘲笑われたり。@……楽しいことなんて一つもないわよ。」\
`"...Like usual, I was attacked by a swarm of ill-tempered small-fry youkai.`@` ...I was bitten, hindered and cursed.`@` ...Not one fun thing happened at all today."`\
ld l,SHU_D4,80

bgm1 33

;「あはは。@今日も随分やられたのは、僕だけじゃないみたいだね。」\
`"Ahaha. `@`It seems like I wasn't the only one who had a rough time today."`\
;　秋一は笑う。@
`　Shuuichi smiled.`@
br
;　どんな死闘を潜り抜けたのか、知りもしないくせに、……という気持ちもあるが。@
`　He smiled even though he didn't know how close to death she could have been... which she was a bit annoyed at.`@
;　自分が今日一日を生き抜けたことを、笑いの感情で祝福してくれたことが、また新鮮だった。\
`　But, it was also refreshing to have news of her survival be met with a smile.`\
ld r,HIG_D9,80

;　……そうか。@生き抜けたことは、……笑うべきことなのか。\
`　...I see. `@`So surviving... is something to smile about.`\
bg black,22
bg Air_01,22

;「そうだね。@生きるってことはそれだけで、笑うべきことなのかもしれないよ。」@
`"That's right. `@`Just being alive may be reason enough to smile."`@
;「………………………。」\
`"............."`\
;「だって。@……貧しい国では、食べる物もなくて。@飢えで死んでいる人たちが、地球上には何人もいるはず。@そんな中で僕は、今日も家族と笑顔で挨拶して、おいしく給食を食べて、@ここでのんびりとお喋りを楽しんでるんだ。@それってすごく幸せで、笑顔になってもいいことなんじゃないかなぁ。」@
`"After all,`@` ...there are people all over the world, `@`living in poor countries with no food, `@`and dying of starvation. `@`I had the privilege of saying good morning to my family with a smile, and eating a delicious lunch, `@`and having a nice chat with you today. `@`I'm really happy about all that stuff, so that should be more than enough of a reason to smile."`@
;「………………………。」\
`"............."`\
bg black,22

;　同意したい気持ちはない。@
`　She didn't want to agree with him.`@
br
;　しかし、ただ生きるだけの昨日と同じ今日に、@秋一は何かを見て、感情を揺らめかせ、それを楽しんで生きている。@……それが、率直に羨ましかった。\
`　But yesterday and today, just by being alive, `@`Shuuichi was able to enjoy finding something to stir up emotions within him.`@` ...And quite frankly, she was envious.`\
bg gakkou_03,22
ld r,SHU_D2,24
ld r,SHU_D1,80


;「彼岸花さんには、ないの？@　……何か、嬉しいとか悲しいとか。@あるいは悔しいとか怒ったとか、そういう感情。」@
`"Do you not have any of those feelings, Higanbana?`@`... Like happiness or sadness?`@`Frustration or anger?"`@
ld l,HIG_D10,23
;ld l,HIG_D1,80

;「………………そういう、……感情。」\
`".......Feelings... like those."`\
;　その日、彼岸花はようやく理解した。@
`　That day, Higanbana finally understood.`@
;　自分には、感情というものがないのだ。@
`　She herself had no capacity for emotion.`@ 
br
;　だから、………日々が何も揺らめかない。@
`　That's was why... she never felt them.`@
;　昨日と同じ今日になる。@今日と同じ明日になる。@それが全て同じ灰色になってしまう。\
`　Yesterday was like today. `@`Today would be like tomorrow. `@`Everything is the exact same shade of gray.`\

bg Air_01,2

;　彼の言う、感情を理解したら、………私の毎日も、彩りを帯びるだろうか。@
`　If I could just understand the emotions he mentioned..... maybe I can bring a new color into my everyday life.`@
br
;　彼が見ている、スケッチブックの世界のような何かを、……私にも見ることが出来るだろうか。\
`　I wonder if I might be able to see things... like the way he sees the world in his sketchbook.`\
bg black,0
ld c,HIG_D9,2

;「感情。@…………………………。」@
`"Emotions.`@` .........."`@
br
;　私にはそれが、欠けている。@
`　I lacked those.`@
;　幾千の妖怪を喰らい、魂を呑み込もうとも。@……それがなければ、自分は人形でしかないのだ。\
`　Even though I've devoured thousands of youkai and swallowed their souls.`@` ...Without all that, I would just be a doll.`\
;ld c,HIG_D1,80

;　私は彼岸花だ。@彼岸花という、意思。@
`　I am Higanbana. `@`A concept called Higanbana.`@
br
;　意思とは、……感情から生まれる？\
`　Can a concept... have emotions?`\
bg Air_01,0
ld c,HIG_D9,2

;　私はようやく理解した。@
`　I finally understood.`@
br
;　私はまだ、妖怪でさえない。@
`　I'm not yet a youkai.`@
;　ただ魂を喰らうだけの、西洋人形。@
`　I'm just a western doll that eats souls.`@
;　感情を得て私は初めて、私たりえるのだ。\
`　Once I'm able to feel emotions, that will be when I'll truly become my youkai self.`\
bg black,2

fede 0,2000
E_A
wait 1000

bg Air_03,22
me1v 16,50
wait 2000
bg black,22
bg rouka_02,22

wait 1000

;mov %iza_Isyou,2
mld l,IZA_D6,25
E_A
se1 2
quakey 3,300

bgm1 23

;「おっとォ。@………おかしなところで出くわしたなァ。@踊る彼岸花ァ！」@
`"Ah.`@` ....What a strange place to find you. `@`Dancing Higanbana!"`@
;＜イザナミ

ld r,HIG_D9a,22

;「……………………………。」\
`"............."`\
;　運がなかった。@
`　How unlucky.`@
br
;　彼岸花の姿を求めて回遊する、雑魚妖怪どもの群を嫌って、おかしな廊下に身を潜めていたら、@そこには先客がいたのだ。\
`　As Higanbana wandered down an odd hallway trying to hide from the swarms of smaller youkai that sought her out, `@`she happened across another youkai.`\
bg black,22

;　死神、イザナミ。@
`　The Shinigami, Izanami.`@
;　好戦的な性格で大量の妖力を蓄える、大妖怪だ。@
`　He was an aggressive greater-youkai that had massive amounts of spirit energy.`@
br
;　かつては実力も伯仲し、互いに戦いを避け合う関係だった。\
`　The two of them had once had approximately equal levels of strength, and thus they avoided fighting each other.`\
mcl l,0
ld c,IZA_D2,3

;　しかし、最近は違う。@
`　But things have changed recently.`@
br
;　感情などというあやふやなものを求め、積極的な狩りをしない自分と、@……ますますに好戦的な狩りを繰り返すイザナミとでは、もう格が違う。\
`　Since she had started this vague search for emotions, and stopped actively hunting... `@`Izanami had started aggressively pursuing hunts more and more often, causing a rift between their once equal footing. `\
bg black,22
bg rouka_03,0
ld c,HIG_D9,23

;「………何よ。@…………やる気……？」@
`"....What.`@` .......Do you want to fight....?"`@
br
;　だからといって、怯えを見せれば、即、喰われる……。@
`　If she showed fear, she would be eaten immediately....`@
;　妖力が劣ることを悟らせるわけにはいかない。@……今でも実力が伯仲しているよう、装わねばならない。\
`　She couldn't afford to show him that her power was inferior.`@` ...She had to pretend that they were still on the same footing.`\
;ld c,HIG_D1,80

;　自分の妖力が染みついた、巣とも呼べる保健室でなら、何とか追い返すことも出来るだろう。@
`　If she was in the infirmary, her nest that was ingrained with her own spiritual energy, then she could probably manage to drive him away.`@
br
;　しかし、こんな冷え切った廊下では無理だ。@
`　But in this frigid corridor, that would be impossible.`@
;　保健室へ逃げ込む前に、食い千切られてしまう。\
`　She'd be torn to pieces before she could escape back to the infirmary.`\
ld c,HIG_D8,80

me1v 16,50

;　……踊る彼岸花と呼ばれるようになって、だいぶ久しく、………彼岸花は死を覚悟する。@
`　...For the first time since she had started being called the Dancing Higanbana.... she prepared herself for death.`@
br
;　ぞくりとした感触の滴りが、胸の内側をゆっくりと垂れ落ちるのを感じた。\
`　She felt a slow dropping sensation within her chest.`\

ld c,HIG_D10,22

;「…………………………………。」\
`"................."`\
bg black,24
bg rouka_02,0
ld c,IZA_D4,24
ld c,IZA_D5,80

me2v 28,70

;「お前とはそろそろ決着をつけてもいい頃だと思ってたぜェ。@……どうする？@　今、ここでやっちまってもいいんだぜ……？」\
`"I was thinking it's about time we settled things between us.`@` ...How about it?`@` Shall we do it right here, right now...?"`\
;　イザナミは校内では最強クラスの大妖怪だ。@その頂点を「校長先生」と争っている。@
`　Izanami is one of the strongest greater-youkai in all the school. `@`He was currently contending for the top position of 'Headmaster'.`@
br
;　彼が校長を超える妖力を蓄えようとしたら。@………自分のような、喰らい応えのある獲物を狙うのが手っ取り早い。\
`　If he was trying to amass enough spiritual power to contend for the spot of headmaster...... `@`then he would be quick to target filling prey such as herself.`\
;　イザナミの性格から考えて、@………少しでも隙を見せれば、今この場で戦わざるを得なくなるだろう。@
`　Given Izanami's personality..... `@`if she let him notice even the slightest chink in her armor, there's no doubt that he would start a fight right here, right now.`@
br
;　………それは、……避けたい。\
`　....I would like to... avoid that.`\
;　イザナミと戦えば、十中八九は殺されるだろう。@
`　If I were to enter a fight with Izanami, there's a ten to one probability that I'd be killed.`@
;　奇跡的に勝てたとしても、満身創痍。@
`　Even if by some miracle I were to win, I'd be gravely wounded in the process.`@
br
;　そんな弱り切った彼岸花という美味しい獲物を、雑魚妖怪どもが見逃すわけもない。\
`　A severely weakened Higanbana would be too delectable a snack for those small-fry youkai to pass up.`\
bg black,22

;　勝っても負けても。@……生き残れる可能性はない。@
`　Whether I win or lose.... `@`neither leaves any possibility of survival.`@
;　死の予感に、……心が震えるのを覚える。@
`　My heart trembled... at the foreboding of death.`@
br
;　死にたいわけもない。@
`　I don't want to die.`@
;　死を怯えるのは、生きる者に課せられた唯一の義務だ。\
`　Fear of death is the one thing that all living beings must feel.`\
me3v 17,70

mono 2
bg Different_spiral_1b,22

;　心臓が早鐘のように鳴る。@心の中でぐるぐると、冷たいスープが渦を巻く。@
`　My heart was pounding like an alarm bell. `@`And the blood felt like it was swirling around like a cold soup.`@
br
;　これほど冷たく凍った汗を浮かべるのは、これが初めての経験だった。\
`　This was the first time I that I had ever broken into a sweat this cold.`\
;　自分には幸運なことに、これまで力があった。@
`　I was lucky enough to have been the stronger one in my fights up until this point.`@
;　だから、どれほどの死闘であろうとも、……死を予感することはなかったのだ。@
`　So having never faced a life-or-death situation this bad before... I've never felt this apprehension from being on the verge of death.`@
br
;　そして今日、……初めてそれを知る。\
`　And today... for the first time, I understood.`\
;　私に引き裂かれる瞬間に、雑魚どもが浮かべる、……あの表情。@
`　I understood the facial expression that the smaller youkai made... the moment I tore them to pieces.`@
br
;　わずかでも気を許せば、それは私の顔にも浮かぶに違いない。\
`　If I let down my guard even the slightest bit, I'm sure my face would show that very same expression.`\
ld c,HIG_D9a,22

;　生きたい。@
`　I want to live.`@
;　死にたくない。@
`　I don't want to die.`@
;　そのための努力。@
`　Isn't there some way I can avoid death?`@
;　何かないか、何かないか。@
`　Something, anything.`@
br
;　気を許せば死ぬ。@何かを誤れば死ぬ。\
`　If I let my guard down, I will die. `@`If I make a mistake, I will die.`\
ld c,HIG_D9,80

;　なぜ死にたくない？@　生きたいから。@
`　Why do I not want to die? `@`Because I want to live.`@
;　なぜ生きたい？@
`　Why do I want to live?`@
br
;　……わからない。@
`　....I don't know.`@
;　でも、それを秋一が教えてくれそうな気がするのだ。\
`　But, I feel like Shuuichi would be able to teach me that.`\

bg white,1
mono 0
bg rouka_03,0
ld c,HIG_D10,22

;　この場をやり過ごせば、生き延びることが出来る。@また秋一に会うことが出来る。@
`　If I give it my all, I can survive. `@`I can meet with Shuuichi again.`@
br

se1 66

;　ごとりと。@
`　I heard a thud.`@
;　心の中の、重い重い石臼が、初めて音を立てて回ったのを聞いた。\
`　It was the sound of the heavy gears in my heart beginning to rotate for the first time.`\ 

se2 84
ld c,HIG_D5,80
wait 1000
bg black,2

fede 0,2000
E_A
wait 1000



bg gakkou_02,22

bgm1 4

;「それで、無事に逃げ切ることが出来たの？」@
`"So did you get away safely?"`@
;「出来なかったら、私はここにいないわ。」@
`"If I didn't, would I be here telling you about it?"`@
;「あはは、それもそうだね。」@
`"Ahaha... stupid question."`@
br
;　秋一は、命懸けだった今日一日を軽く笑って聞き、スケッチブックに鉛筆を走らせていた。\
`　Shuuichi laughed lightly at my near-death experience, and continued to draw in his sketchbook.`\
bg black,22
bg gakkou_03,0
ld r,SHU_D4,0
ld l,HIG_D8,22

ld r,SHU_D1,80

;「それで？@　今はどんな気持ちなの？」@
`"And? `@`How do you feel right now?"`@
ld l,HIG_D10,80

;「…………気持ちって？」\
`".......Feel?"`\
ld r,SHU_D4,80

;「無事に大妖怪から逃れることが出来た、今の彼岸花さんの気持ち。」@
`"You were able to get away from a great youkai unharmed today. How do you feel about that, Higanbana?"`@

ld l,HIG_D9a,80

;「……………………………。」\
`"................"`\
ld r,SHU_D1,80

;「殺されるって思ったんでしょ？@　策がうまくいって、何とかやり過ごせたんでしょ？@　その時は、どんな感情だったの？」\
`"You thought you were going to be killed, right? `@`You made a plan and gave it your all, and it went well, right? `@`How did you feel then?"`\
bg black,22
mono 1
bg rouka_02,0
ld c,IZA_D8,22

;　………イザナミに出くわした時。@……死を覚悟した。@
`　.....When I encountered Izanami.... `@`I prepared myself for death.`@
br
;　その時の心の中の、どきどきやばくばくは、感情と呼んでもいいのだろうか。\
`　I wonder if it would be right to call the thumping and pounding in my heart at that time an emotion.`\
bg black,0
mono 0
bg white,23
bg hoken_01,23
quakex 1,100

;　そして命辛々、逃げ延びて。@ようやく保健室に逃げ込んだ時の、あの安堵の深い深いため息は、@感情と呼んでもいいのだろうか。\
`　And after I narrowly escaped with my life. `@`And when I finally made it back to the infirmary, I took a deep, deep sigh of relief. `@`Would that be considered an emotion?"`\
bg black,22

;「………わからない、………けれど……。」@
`".....I don't.... really know..."`@
br
;　今日という一日が、……昨日までの淡白な灰色の一日とはまったく違う色に感じたのは確かだ。@
`　Today... I'm sure that I felt a different color today than the same old gray that I've been seeing for so long.`@
;　灰色なのは同じだけど、………昨日までのは、ぼんやりと曇った灰色。\
`　It was still a shade of gray.... but up until yesterday it was a boring and cloudy gray.`\
bg gakkou_02,22

;　今日のは違う。@触れたら裂けてしまいそうな、@……カミソリの刃を思わせるような、鋭利な銀色のような……。@
`　Today it was different. `@`Like a sharp silver... like a razor blade. `@`So sharp that if you touched it, it would slice your fingers open...`\
br
;　じゃあそれは灰色じゃない。@銀色だ。\
`　That's it, it wasn't gray. `@`It was silver.`\
bg black,22
bg gakkou_03,0
ld r,HIG_D9,22

;「………………………………。」\
`"................."`\
ld l,SHU_D2,23
ld l,SHU_D1,80

;「危なかったーという気持ちとか。@助かったーという気持ちとか。@……そういうものを、彼岸花さんは、もっともっと楽しんでいいと思うんだ。」@
`"Like, 'oh wow, that was dangerous', `@`or 'I'm glad I got out of there alright'.`@` ...I think it'd be nice if you could enjoy those feelings much more."`@
ld r,HIG_D10,80

;「………あの危機を、……楽しむ。」\
`"....Enjoying... the feeling of danger?"`\
ld l,SHU_D3,80

;「ちょっと違うかな。@無事に今があることを楽しむというべきか……。@彼岸花さんだって、きっと理解しかけてるはずなんだよ。@その証拠に、…………ほら。」\
`"No, not quite. `@`More like enjoying that you made it out safely.... `@`I'm sure that you're beginning to understand that feeling. `@`And this is proof of that...... Here, look."`\
se1v 1010,50

bg white,22

;ld_p HIG_D1
;lsp2 2,$ld_pass,300,480,200,200,0
;lsp2 3,$ld_pass2,300,480,200,200,0
;print 22

bg black,22

;　秋一は、たった今、描いていたものをこちらに向ける。@
`　Shuuichi turned his sketchbook around to show her what he had just been sketching.`@
br
;　そこに描かれているのは、……なんと、彼岸花の顔、だった。\
`　There on the page... was Higanbana's face.`\
;「………………私……？」@
`"......Me...?"`@
;「うん。@……今日の彼岸花さんは、いつもと違う表情を感じるよ。」\
`"Yep.`@` ...I think that your expression is different from usual today, Higanbana-san."`\
;「それは、………どんな。」@
`"How... so?"`@
;「笑ってると思う。」\
`"I think you're smiling."`\
csp2 -1
print 0
bg black,22
bg gakkou_03,0
ld c,HIG_D9,22

;「……笑……う……？」@
`"....Smil`!w1000`ing...?"`@
br
;　笑っているつもりなどなかった。@
`　She didn't think that she had been smiling.`@
;　しかし、秋一の描いたスケッチブックの中では、確かに彼岸花は笑っていた。\
`　But in the picture Shuuichi drew of her in his sketchbook, she was definitely shown smiling.`\
;「大妖怪をうまく騙して。@まんまと逃げ延びたことに、彼岸花さんは嬉しかったという気持ちを感じてるはず。@そして、危機を無事に乗り越え、今日という日をいつものように過ごせることに、安堵を覚えているはず。@……そんな気持ちが自然と、彼岸花さんを、いつもより生気のある表情にしているんだと思うよ。」\
`"You successfully outsmarted a great youkai, `@`and managed to get away, so you must have been happy about that. `@`And you must be relieved about averting a crisis and being able to go about your day normally.`@` ...I think that those feelings are naturally giving you a much more lively expression than usual."`\
ld c,HIG_D10,80

;「……………………………。」\
`"................"`\
ld r,SHU_D4,24

;「良かったね。@無事に今日が過ごせて。@苦難を乗り越えて辿り着いた、今日の夕焼けはどう見える？」\
`"Isn't that great? `@`You were able to make it to the end of today safely. `@`Now that you've overcome hardships, how does the sunset of the day you survived look right now?"`\
cl c,0
ld l,HIG_D9,24

;「……………いつもと同じだと思うわ。」\
`"......It looks the same as always, I think."`\
ld r,SHU_D1,80

;「そんなことないよ。@もっとよく見て。@昨日よりもずっと、鮮やかな夕焼け色をしているはずだよ。」@
`"No way. `@`Try looking harder. `@`I'm sure that the colors of this sunset look much more vibrant than yesterday's."`@
ld l,HIG_D10,80

;「……………………………。」\
`"................."`\
bg black,22

me1v 5,50

bg Air_01,2

wait 1000

;　秋一の、言う通りだ。@
`　It was as Shuuichi said.`@
;　今日の夕焼けは、これまでに一度も見たことのない、鮮やかな色をしていた。@
`　The colors of this sunset were more vibrant than I had ever seen before.`@
br
;　それを認めた時。@……私は心の中に不思議な感触を覚えた。\
`　Once I admitted that.... `@`I felt a strange sensation in my heart.`\
;　もし、心というものに容積があるならば。@
`　If the feelings within a heart could be measured by some physical metric...`@
;　握り拳程度しかなかったそれが、……ぶわっと広がるような、不思議な解放感。@
`　...Then it would have only been the size of a clenched fist... albeit rapidly expanding, with a sense of liberation.`@
br
;　まるで心臓の内側の狭い狭い世界が、……体よりも広く広く広がったかのような感触を覚えた。\
`　It was a feeling almost like the small confines of my heart... were suddenly becoming much, much larger than my entire body.`\
;　そして、内より湧き出る自分の心の声を初めて聞く。\
`　And for the first time, I heard a voice coming from within my heart.`\
bg black,22
;bg Different_spiral_1b,22

fede 10,1000
E_MA

;“あの雑魚妖怪ども、油断も隙もない……。@正直、侮り過ぎていたわ……。”@
`[You can't be too careful around those smaller youkai... `@`Honestly, I despise them...]`@ 
;“……それにしても今日は危なかった、……イザナミめ、死ぬかと思ったわ……。”@
`[Nevertheless, today was dangerous... I thought Izanami was going to kill me...]`@
;“あんな嘘を信じるなんて、イザナミも馬鹿よね、愚かなヤツ。”@
`[But he sure was an idiot, that Izanami. To think that he'd believe that lie I told him... Such an idiot.]`@
;“……色々あったけど。@……とにかく今日も。@……何とか生き残れたわ。@……何とか、ね……。”\
`[...Lots of things happened.`@` ...But somehow.`@` ...I survived today.`@` ...Somehow....]`\
bg black,22
bg Air_01,22

;　それを、感情と呼んでもいいのだろうか。@
`　Are these what are called emotions?`@
;　わからない。@
`　I don't know.`@
br
;　しかし、色に例えたなら、それは断じて灰色ではない。@
`　But, if I likened my feelings to colors, they were decidedly not gray.`@
;　様々な色が入り混じった、理解できないけれど、複雑な色に違いなかった。\
`　Various colors mixed and blended, and though I didn't completely understand, it was undoubtedly a complex hue.`\
;「私の目に映る、この鮮やかな夕焼けは。@………あんたにも見えているの。」@
`"Is this vibrant sunset that I see...`@` the same one that you can see?"`@
;「もちろん。@……それは、様々な感情を楽しむことで、もっと様々な彩を見せてくれるんだよ。」\
`"Of course.`@` ...That's because the more you enjoy the emotions you have, the more vivid the colors you see become."`\
bg black,22
bg gakkou_03,0
ld r,SHU_D4,0
ld l,HIG_D8,22

ld l,HIG_D10,80

;「……それが、生きることの楽しさ、なの……？」@
`"...So that's the key to enjoying life...?"`@
ld r,SHU_D1,80

;「楽しさの第一歩、かな。」@
`"Well, that's the first step, I guess."`@
ld l,HIG_D9,80

;「秋一は、もっと進んだ楽しさを見つけている…？」\
`"Does that mean that you're finding ever more enjoyment in your life, Shuuichi...?"`\
ld r,SHU_D4,80

;「うん。@彼岸花さんは、ようやく一日を無事に終えることの喜びを覚えたんだと思う。@……僕はもっと先。@未来を眺めることを楽しんでる。」@
`"Yep. `@`Higanbana, you have finally figured out the happiness of safely surviving a day.`@` ...I'm a bit beyond that. `@`I enjoy looking forward to the future."`@
ld l,HIG_D10,80

;「未来……………。」\
`"The future........"`\
ld r,SHU_D1,80

;「僕は将来、画家になりたいんだ。@それが僕の、夢。」@
`"When I grow up I want to become an artist. `@`That's my dream."`@
bg black,22

;ld l,HIG_D9,80

;「……夢……………。」\
`"...Dream........."`\
;ld r,SHU_D2,80

;「その日を目指して生きることは楽しいし。@その日を想像することもとても楽しい。@……そんな日々を積み重ねると、心から楽しくて、……僕は生きてるって、実感できるんだよ。」\
`"I enjoy looking forward to that day. `@`And I really enjoy imagining what it will be like.`@` ...The more days I spend working towards my dream, the more enjoyment I'm having... and that's when I feel like I'm truly alive."`\
bg Air_01,22
;ld l,HIG_D10,80

;「………………………………。」@
`"................"`@
br
;　秋一が何を言っているのか、今はわからない。@
`　I didn't understand what Shuuichi was saying right now.`@
;　でも、彼の言っていることがわずかでも理解できたなら、@……生きることにきっと、何かの楽しさを見出せるに違いない。@……そのことを、私は断じて疑わない。\
`　But, if I could just figure out how to grasp what he was saying, even a little bit... `@`I'm sure that I could figure out how to enjoy life.`@` ....I had no doubt of that.`\

;　今の私はまだ、ただ生きることだけで精一杯で、……それだけで頭がいっぱいだけれども。@
`　Right now I'm just trying to survive with all my might... so my head is filled with only thoughts about that.`@
br
;　きっといつかわかる。@理解できる気がする。@
`　Someday I'll be able to understand. `@`I'm sure I'll be able to grasp it.`@
;　秋一と一緒に過ごせば、いつか、きっと。\
`　If I keep spending my days together with Shuuichi, I'm sure I'll be able to do it, someday.`\
bg black,22

;　その時、不意に二人の後ろから声が聞こえた。\
`　Just then, a voice suddenly called out from behind them.`\
fede 0,1000
E_A

bg gakkou_03,23

;「……お！@　またこんなところにいたのかよ？！」@
`"...Hey! `@`You're here again?!"`@
me1v 5,50

br
;　振り返ると、そこには三人組の少年たちが立っていた。@
`　When they turned to look, there stood a trio of boys.`@
;　彼岸花にも見覚えがある。@……いつもいつも、秋一をしつこくいじめている連中だ。\
`　Higanbana recognized them.`@` ...They were the lot that were always persistently bullying Shuuichi.`\
;「お前さ、サンドバッグなんだから、勝手に歩き回るんじゃねぇよ、な？」@
`"You're our punching bag, so don't walk 'round without permission, 'kay?"`@
;「俺たちがムシャクシャした時に殴られるのがお前の仕事だろ？@　サボんじゃねーよ。」@
`"Your job is to take punches from us when we're pissed, got it? `@`Don't try to skimp out on us here."`@
;「それとも、俺たちが構ってあげないから、不貞腐れちゃったとか？@　あっはははは、悪ぃ悪ぃ、ちゃんと今日も遊んでやるからよー！」\
`"Or were you just out here sulking because we weren't paying attention to you? `@`Ahahaha, our bad, we'll be sure to play with you a lot today!"`\
;　ぎゃはははは、と少年たちは下卑た声で笑った。@
`　The boys laughed crassly.`@
;　その笑い声に、秋一が全身を強張らせるのがわかった。\
`　That laughter caused Shuuichi's entire body to go rigid.`\
ld r,HIG_D10,22

;「………三人とも、揃いも揃って頭の悪そうな顔をしてるわね。」@
`"......Just judging by their faces, it looks like all three of them are pretty slow in the head."`@
ld l,SHU_D1,23

;「そう見えるかい？」\
`"So you can tell?"`\
ld r,HIG_D9,80

;「私の目が節穴じゃないならね。@……逃げたら？」@
`"Anyone who isn't blind could tell that.`@` ...Why don't you run away?"`@
ld l,SHU_D5,80

;「追ってくるよ。@どうせ逃げ切れないし、機嫌を損ねて、その分、打たれるだけさ。」\
`"They'd catch me. `@`Besides, if I ran I'd just make them angry and they'd beat me that much more."`\
ld r,HIG_D10,80

;「……達観してんのね。@いじめられるのが苦じゃないの？」@
`"...So you're thinking things out in the long term. `@`Isn't this bullying causing you to suffer?"`@
ld l,SHU_D1,80

;「そりゃ辛いさ。@……でも別に、殺されるわけじゃない。@ちょっと彼らの意地悪に付き合うだけさ……。」\
`"It is tough.`@` ...But it's not like they're going to kill me. `@`They just rough me up a little...."`\
ld r,HIG_D9,80

;「…………………………。」\
`"..............."`\
;　秋一は、すでに成人している兄たちの影響なのか、非常に大人っぽく、達観している少年だった。@
`　Perhaps it was the influence of his older brothers, who were already adults, but Shuuichi was a very adultlike boy, who would carefully base his choices on the long-term consequences.`@
br
;　しかし、その異質さが、いじめっこたちの興味を引いてしまうのかもしれない。\
`　But that difference may have been what caught the eye of these bullies.`\
cl a,0
mbg black,22

bgm1 7

;　三人組は、ねちねちと秋一に絡みつき、小突いてくる。@
`　The trio of boys circled Shuuichi and started shoving him around.`@
br
;　秋一は曖昧に笑いながら、止してくれと言うだけだ。\
`　Shuuichi laughed awkwardly and asked them to stop..`\
;「抵抗すればいいのに。」@
`"Just resist them."`@
;ld c,SHU_D1,22
;ld c,SHU_D1,80

;「……彼らの怒りに油を注ぐだけだよ。@その内、飽きるさ。」@
`"...That would just be pouring oil on the fire. `@`If I just let them have their way, they'll get tired of it sooner or later."`@
br
;　秋一は、彼岸花に痛々しい苦笑いを見せる。@
`　Shuuichi showed Higanbana a pathetically forced smile.`@
;　……それを見て、……彼岸花は心の中に、初めて覚える疼きを知るのだった。\
`　...When she saw that... for the first time, Higanbana knew what it felt like to have an ache in her heart.`\
mcbg 0
;bg black,22
bg gakkou_02,22

;「じゃあ、投げるのはこの線からなー。」@
`"Alright, don't pass this line when you're throwing."`@
;「あ、俺一番でいい？」@
`"Hey, can I go first?"`@
;「お前、野球部なんだからハンデで左手で投げろよなー。」@
`"You're in the baseball club, so you gotta handicap yourself. Throw with your left hand."`@
;「おいおい、俺の黄金の右手を封じるつもりかよー？」\
`"Hey, hey, you're just trying to keep me from showing off my golden right armed pitch."`\
;　秋一に、そこから一歩も動くなよと脅した上で、@いじめっこたちは距離を取り、地面の石を拾い始める。@
`　After threatening Shuuichi not to move a step, `@`the bullies took a dozen steps back and started to pick up rocks off the ground.`@
br
;　何を始めようとしているか、明白だった。\
`　It was obvious what they were planning to do.`\
;　石は、小石と呼ぶには大きい。@当たり所が悪ければ、掠り傷程度では済まないかもしれない。@
`　The rocks were a little too large to be called pebbles. `@`If one of them were to hit him in the wrong place, he might not be getting away with just a few scratches.`@
br
;　しかし、秋一は動くなと命令されている。@
`　But, Shuuichi was ordered to not move at all.`@
;　秋一は固く目を瞑り、これから来る痛みに耐えようとしている……。\
`　Shuuichi shut his eyes tightly and braced for the oncoming pain...`\
ld c,HIG_D10,22
;ld c,HIG_D1,80

;「……………………………。」\
`"..............."`\
;＜彼岸花

bg gakkou_03,22

;　いじめっこのひとりが、石を握りしめ、振りかぶった時。@彼岸花はその石を睨み付けた。@
`　Just as one of the bullies was winding his arm back in preparation for a throw, `@`Higanbana glared intently at the stone he held.`@
br

se1 7

mbg white,1
mcbg 22

;　その瞬間、少年の持った石がすっぽ抜け、はるか頭上へ飛び去った。\
`　And suddenly, the stone slipped out of his hand and flew far above his head.`\
mbg black,26

fede 1,1000
E_B

;「………な、……何だ……。」@
`"....W-... What the...."`@
;「バーカ、お前どこ投げてんだよー。」@
`"Haha, you idiot, where were you aiming?"`@
;「いや、今、石が勝手に………。」@
`"No, I didn't do anything..."`@
;「おい……、あの石どこまで飛んでくんだよ？」\
`"Hey... how far is that rock gonna go?"`\
bgm1 15

mcbg 22

;　まっすぐにどこまでも垂直に飛んでいく石は、一度、宙で静止する。\
`　The stone which had flown straight up was now floating still midair.`\ 
;　石が空中に止まるわけがない。@いじめっこたちは茫然とそれを見上げ続ける。@
`　There was nothing that could have been holding the rock in the air like that. `@`The bullies just looked up at it, stunned.`@
br

E_MA

se1 20
quakey 1,100
wait 500
se2 20
quakex 1,100

;　すると、ブンっと、まるで蜂が舞うかのように、石が８の字を描いた。@
`　And then, like a wasp dancing through the sky, the stone started to make figure eights in the sky.`@
;　そして、その石が、まさに蜂のように襲い掛かってくるに至って、いじめっこたちは飛び上がって驚く。\
`　Then the stone swooped down, like a wasp ready to sting, and the bullies jumped in surprise.`\
se1 66
ld l,HIG_D10,22


;　その石を投げようとした少年めがけて、……石は唸りをあげながら、その頭部を正確に狙う。@彼が秋一に対してそうしたように。\
`　With a buzz it flew towards the boy who had tried to throw it... and aimed directly at the his head. `@`Just like where that boy was aiming to hit Shuuichi.`\

ld c,SHU_D6,24
quakex 1,100

;cl c,25
;E_ 3,1

bg black,1


;se2v 12,100

;　危ないっ。/
`　Watch out!`/
se1 13
quakey 3,300
@
br
;　そう叫び、秋一が少年に飛びかかった。@
` Screaming that, Shuuichi threw himself at the boy.`@
;　少年の身体を抱えるようにして、地面に倒れ込む。@
`　He wrapped his arms around the boy and tackled him to the ground.`@
;　狙いの逸れた石は地面に激突し、ガッという大きな音と共に粉々に砕け散った。\
`　Missing its target, the stone smashed into the ground and broke into tiny pieces.`\
fede 0,1000
E_A

me1v 16,50

;「…………秋一、……どうして………。」@
`".......Shuuichi, ...why......."`@
br
;　どうして秋一が庇うのか、彼岸花には理解できなかった。@
`　Why did Shuuichi protect him? Higanbana couldn't understand.`@
;　彼らは秋一の敵であるはず。@……なのに、どうして。\
`　They were his enemies.`@` ...So then, why?`\
;　秋一と共に地面に倒れた少年は、粉々になった石を見て少しの間、呆然としていた。@
`　For a short while after they hit the ground, the boy kept his eyes on the pieces of the broken rock, in a daze.`@
br

se1 10
quakex 1,100

;　だが、不意に我に返ると、自分に覆い被さる形になっていた秋一を思い切り突き飛ばした。\
`　But then he suddenly came to his senses, and realized that Shuuichi was still lying on top of him, and the boy pushed him off with all his might.`\
;se2 10
;quakey 1,100

;　罵声を浴びせながら立ち上がると、身体についた土を払い、倒れている秋一の足を爪先で蹴り上げた。@顔をしかめて秋一がうずくまる。@
`　The boy rattled off insults as he stood up and brushed the dirt off his body and started kicking Shuuichi's legs with the tip of his shoes. `@`Shuuichi cowered with a grimace on his face.`@
br
;　その行為に、……私は、全身が逆立つ感触を覚えた。\
`　This... made my entire body stand on end.`\
se3 66
;mbg white,1
;mcbg 22

;「……………………………っ。」@
`"..............!"`@
br
;　無意識の内に、右腕が上がる。@……そこに鋭い鍵爪が伸びる。@
`　Involuntarily, my right arm raised.`@` ....And my sharp claws grew.`@
;　……今この場でその薄汚い魂、私が引き裂いてやる。\
`　...I'll tear that mangy soul directly from his body, right here, right now.`\
;　まさにその瞬間、地面に伏せたままの秋一が呻くように言った。\
`　Just at that moment, Shuuichi, still face down in the dirt, spoke in a groan.`\
bg Air_01,22
;E_ 3,3

E_B

;「やめて、彼岸花さん……。」@
`"Don't do it, Higanbana-san...."`@
br
;　それは聞こえるか聞こえないかくらいの小さな声だった。@
`　It was a quiet voice that could barely be heard.`@
;　しかし、それは確かに聞こえ、……彼岸花は腕を止めた。\
`　But, Higanbana undoubtably heard it... because her arm stopped.`\
bg black,22
bg gakkou_02,22
;se1 10
;quakex 1,100
;wait 800
;se2 10
;quakex 1,100

bgm1 6

;　庇われたはずの少年は、顔を真っ赤にしながら、秋一を執拗に蹴っていた。@
`　The boy who Shuuichi had just saved continued kicking him on the ground, face bright red.`@ 
;　カッコつけて投げたつもりの石が、真上へ暴投してしまい、@しかもその石が自分に襲い掛かってくるように思って怯えてしまうなんて。@
`　Apparently he thought that as he was trying to show off with his throw, he ended up throwing a wild pitch that went straight up. `@`And furthermore, he had been frightened as the rock came back down at him.`@
br
;　それがこの上なく恥ずかしいことに思えたらしい。@それを誤魔化すかのように、秋一を何度も蹴る。\
`　It seemed that this had been something supremely embarrassing for the boy, `@`so he kept kicking Shuuichi to gloss over the fact.`\
bg black,22
bg gakkou_03,22

;　しかし、他の二人のいじめっこはそうではない。@
`　But the other two bullies weren't so oblivious.`@
br
;　どう投げたって、石があんな動きをして襲い掛かってくるわけがない。@
`　No matter how you throw it, there's no way a stone should be able to fly through the air like that.`@
;　すっかり興醒めしてしまい、薄気味悪そうに、砕けた石を見ている。\
`　Those two boys were no longer interested in bullying, and instead were chilled to the bone and looking at the pieces of the smashed stone.`\
;「……なあ、行こうぜ。@なんか気味悪いよ……。」@
`"...Hey, let's get out of here. `@`This is kinda creepy..."`@
;「そうだよ、そうだよ。@……行こうぜ……。」@
`"Yeah....yeah.`@` ...Let's go...."`@
br
;　それが、いじめっこたちの正直な気持ちだ。\
`　Those were the bullies' honest feelings.`\
se1 10
quakex 1,100

;　最後にもうひと蹴りを入れ、いじめっこたちはうずくまる秋一を残して立ち去る……。\
`　After putting in one last kick, the bullies took off, leaving Shuuichi crouching on the ground...`\
textoff

fede 0,1000
E_A
wait 1000

ld c,HIG_D10,22

me1v 5,50

;「……………どうして、庇ったの？」@
`".......Why did you protect him?"`@
;「だって、……あんなの当たったら痛そうじゃない。」@
`"Because... if that had hit him, it looked like it would have hurt."`@
ld c,HIG_D9,80

;「その痛そうなものをぶつけようとしたのは連中じゃないの？」\
`"But weren't they trying to use that rock to hurt you first?"`\
ld r,SHU_D5,6
ld r,SHU_D4,80

;「まぁ、そうだろうけどね。@あははは……。」@
`"Ah, I guess so. `@`Ahahaha..."`@
br
;　秋一は服に付いた砂埃を払いながら、立ち上がる。\
`　Shuuichi stood up, dusting off his clothes.`\
cl c,0
ld l,HIG_D10,24

;「……秋一は、どうしてそこまで達観していられるの？」@
`"...Shuuichi, why are you always so concerned with the consequences of things?"`@
ld r,SHU_D1,80

;「そのつもりはないんだけどね。」\
`"It's not like I really mean to."`\
ld l,HIG_D9,80

;「あなたはあいつらと同じ年の子供には到底、見えなくてよ。@……まるであなたは人間じゃないみたい。」@
`"Those guys may be the same age as you, yet they don't think like you do at all.`@` ...It's almost like you're not even human."`@ 
ld r,SHU_D4,80

;「それはひどいなぁ。@人間のつもりなんだけどなぁ。」\
`"What an awful thing to say. `@`I'm a human, and I'm trying my best to be one."`\
ld l,HIG_D8,80

;「きっと。@……秋一は、あいつらのような低俗な人間とは、物の見方が違うんだわ。」@
`"But surely.... `@`the way you look at things is different than that boorish lot."`@
ld r,SHU_D3,80

;「………そうかも、しれないね。」\
`"....Probably, I guess."`\
bg black,22

fede 0,1000
E_A

bgm1 33

;　私ははっきりと理解する。@
`　I understood clearly.`@
br
;　多分、秋一は、……並の人間たちとは見えているものが違うのだ。\
`　Shuuichi probably... saw things differently than the average human being.`\
bg Air_01,22

;　こうして、人ならざる存在である私の姿が見えているように。@
`　That is why he is able to see supernatural beings, such as myself.`@
br
;　そして、誰よりも美しく鮮やかな夕焼けが見えているように。\
`　And why he can see a sunset more vibrantly beautiful than anyone else.`\
;「秋一の目は、人間には見えない何かを見ることが出来ている気がするわ。@……それがとてもとても美しいから、@……あなたは人間同士の、低俗な諍いに目を奪われないんだわ。」\
`"I feel like you must be able to see things that other humans cannot, Shuuichi.`@` ...And what you see is so beautiful... `@`that you can't be bothered by the petty squabbles of your fellow man."`\
;　生まれながらに、人ならざる者たちの世界に近い波長を持つ者がいるように。@
`　In the same way that some people are born with wavelengths closer to the supernatural world...`@
br
;　生まれながらに、人ならざる何かを持って生まれる者もいるのかもしれない。\
`　...Maybe there were some people who were born with something non-human about them.`\
;　秋一は多分、……人ならざる目を持っているのだ。@
`　Shuuichi... could be said to have mystic eyes.`@
;　彼はその目に、感情というものを、美しい何かとして映し出すことが出来るのだ。@
`　With those eyes, he was able to perceive emotions as manifestations of beauty.`@
br
;　それがあまりに美しくて、鮮やかで興味深いものだからこそ……、@彼はその感動を忘れたくなくて、スケッチブックに記す。\
`　Because they were so beautiful and vivid... `@`he didn't want to forget how moving they were, so he recorded them in his sketchbook.`\
bg black,22
bg gakkou_03,22
ld r,HIG_D9,24

;「……そのスケッチブックに描いている絵。@………抽象画じゃないんでしょう？」\
`"...Those pictures you sketch.`@` .....They're not abstract art are they?"`\
ld l,SHU_D2,23
ld l,SHU_D1,80

;「………………うん。@……僕は、見えたままに描いているだけだよ。@幼稚園の頃に気付いたんだ。@……僕には、人とは違う世界が見えてるって。」@
`"..........No.`@` ...I just draw things as I see them. `@`I realized back when I was in kindergarten.`@` ...I see a different world than other people."`@
ld r,HIG_D8,80

;「…………………………。」\
`"............."`\
ld l,SHU_D4,80

;「それを家族に話したよ。@すごく驚いてた。@そしてお父さんが言ったんだ。@その目はきっと、神様からの授かりものに違いない、って。@……僕に見える世界をそのまま、絵に描きなさいって言ってくれたんだ。」\
`"I told my family about it. `@`They were very surprised. `@`And my father told me, `@`that these eyes must be a gift from God.`@` ...And that I should draw pictures of the world as I see it."`\
bg black,22
;bg Different_spiral_1b,22

;　秋一は自覚したのだ。@
`　Shuuichi was aware.`@
br
;　自分には、心の揺らめきを通して、人には見えない世界を見ることが出来ると。\
`　Aware that his perception of the world unseen by others, changed based on the swaying of his emotions.`\
;　そして、それを絵に描くことを覚えた。@
`　And he remembered how it looked by drawing pictures of them.`@
;　その絵から、描いた時の感情を思い起こせることを知った。@
`　That way, whenever he looked back through his sketchbook, he could recall the emotions of those times.`@
br
;　絵の腕を上達させれば、その感情を、他の人たちにも共有してもらえるかもしれない。\
`　If he improved his art, then he may be able to share his emotions with others.`\
bg black,22
bg Air_01,22

;　その時、思ったんだ。@……それが僕の、天職かもしれないって。@
`　Back then I wondered,`@` '...maybe this is my calling.'`@
;　……僕は感情を見ることが出来る。@それを絵に出来る。@……それを大勢に見せることで、みんなにも感じ取ってもらえる。@
`　...I can see feelings. `@`If I make them into pictures,`@` ...and show them to a lot of people, maybe they can feel them as well.`@
br
;　つまりそれって、僕が幸せな絵を描けば、大勢に幸せになってもらえるかもしれないってことでしょ？\
`　In other words, if I draw a happy picture, I wonder if I can make a lot of people happy.`\
;　そう思った晩、興奮して眠れなかった。@
`　On the night that I pondered those thoughts, I was so excited that I couldn't sleep.`@
;　どうして神様が僕にこんな目を与えたのかはわからないけれど。@……きっと、それが僕の使命なんだって思った。\
`　I don't know why God gave me eyes like these.`@` ...But I think that this must be my mission in life.`\
;　だから僕は、日々の感情を全て描き、練習するんだ。@
`　So every day, I'll keep drawing every emotion that I see, and keep practicing.`@
;　……感情を絵に表すことを繰り返して、練習して、上達するんだ。\
`　...I'll repeatedly express my feelings through my pictures, and practice to become more skilled.`@
;　だから毎日、僕は欠かさず絵を描くんだよ。@
`　So I vow to never go a day without drawing a picture.`@
;　喜怒哀楽、それだけに分類できない無数の感情の揺らめきをね。\
`　A picture of these countless emotions, uncategorizable in terms of normal human emotions.`\
bg black,22

;　彼岸花は思った。@
`　Higanbana thought to herself.`@
br
;　天使という存在が実在するならば。@……それはきっと、彼なのだ。@
`　If angels really exist,`@` ...then he must be one of them.`@
;　天よりを遣わされて、彼となって転生したのだ。\
`　An Angel sent from heaven, reincarnated in the form of a boy.`\
bg usagi_01,0
ld c,SHU_D1,22

;　何の為に？@
`　For what purpose?`@
;　人に、より多彩な感情を、教えるために。@
`　To teach people how to feel a wider variety of feelings.`@
br
;　そうだと断言できる。@
`　I can attest to that.`@
;　………だって。@……彼は私に、感情というものを教えてくれたのだから。\
`　.....Because,`@` ...he even managed to show me what emotions are.`\
ld c,SHU_D4,80

;「さっきは、僕を助けるために、ありがとう。」@
`"Thanks for trying to save me earlier."`@
ld r,HIG_D8,22

;「…………咄嗟にやってしまっただけよ。」@
`"......It was just on a whim."`@
ld c,SHU_D1,80

;「僕をいじめようとする彼らに対して。@怒りの感情を覚えてくれたんだね。」\
`"When they were bullying me, `@`that made you feel angry, right?"`\
;wait 500
ld r,HIG_D9,80

;「………………怒……り……。」@
`".....An...gry...."`@
br
;　それが、……あの時の、心がぎゅうっと締め付けられて、喉元まで這い上がってくるような感情の、名前。\
`　That's... the name of the emotion you get when your heart tightens up and creeps up to your throat.`\
cl c,0
ld l,SHU_D3,24

;「その怒りの感情の底には。@……僕のことを助けたいって感情があったんだよね。@それが、僕には見えてた。@それが嬉しかった。@……だから、ちょっといじめられかけたけれど、全然辛くなかったんだよ。」\
`"At the root of the feeling of anger,`@` ...was a desire to help me, right? `@`I could see that. `@`It makes me happy.`@` ...So, even though I was bullied a little bit, it wasn't painful at all."`\
ld r,HIG_D10,80

;「………………………………。」\
`"..............."`\
bg black,2

fede 0,2000
E_A
wait 1000

bg sadou_04,22

me1v 16,50

;　校舎の一階。@その一番奥にある茶道室。@
`　First floor of the school building. `@`The tea ceremony room in the far back.`@
br
;　生徒の個性を重んじることを方針にしているこの学校では、部活動に特に力を入れており、@このように普通の学校では珍しい教室も多数存在している。\
`　As a policy of respecting the individuality of students, this school put extra attention into the providing of extracurricular activities, `@`and thus there were many of these rooms specifically for club activities that you wouldn't find in a normal school.`\
;　だが、今この茶道室には、その厳かで静粛な雰囲気とは不釣り合いな生徒たちが座り込んでいた。@
`　But in this particular tea ceremony room, amongst a solemnly silent atmosphere, there sat a group of students that seemed altogether out of place.`@
br
;　あの、秋一を執拗にいじめていた三人組だ。\
`　They were the trio of boys that had relentlessly bullied Shuuichi.`\
bg black,22
bg sadou_03,22

;「何だったんだろうな、……さっきの。」@
`"What was that... back then."`@
;「いつまでビビってんだよ。@たまたま強い風が吹いたってだけじゃん。」\
`"You're always so nervous. `@`It was just a strong breeze, that's all."`\
;「そうだよな……。@ただの風だよな。」@
`"Yeah... `@`Just the wind."`@
;「当たり前だろ。@風じゃなきゃ何だってんだよ。@くだらねぇ。」\
`"Obviously. `@`What else could it be? `@`Stupid."`\
mov %SMI_Isyou,1

E_A
se1 82

mbg white,24
mcbg 0
ld r,SMI_D1,2

bgm1 18

;　その時、入口の襖がすぅっと開き、ひとりの少女が現れる……。@
`　Just then, the opening of the sliding screen door could be heard, and one girl stood in the doorway...`@
br
;　その少女は、………人ならざる者。@
`　That girl was..... not human.`@
;　しかし、彼らには人間のクラスメートに見えているようだった。\
`　But to them she appeared to be one of their human classmates.`\
ld r,SMI_D6,80

;「どうだったみんな？@　今日も玲子の仕返ししてくれた？」@
`"How did it go? `@`Did you guys get revenge for me -- Reiko -- today?"`@
; ^^^ Note To Editor: Sumire seems to speak in third-person when she's disguised as Reiko. I'll normally change it to first-perosn "I" or "me", but it's a little important to keep her name in this first dialogue in some way. -Jorwil
;＜スミレ私服
br
;　清澄玲子と名乗る彼女の正体は、……夕闇のスミレ。@
`　The true identity of this girl named Reiko Oosumi... is Sumire of the Twilight.`@
;　彼女は秋一のクラスに入り込んでいたのだ。\
`　She had infiltrated Shuuichi's class.`\
;「もちろんだよ、玲子ちゃん。@……なぁ？」@
`"Of course we did, Reiko-chan.`@` ...Right guys?"`@
;「ああ。@昨日よりボッコボコにしてやったよ！」@
`"Yeah. `@`We beat him even harder than yesterday!"`@
;「秋一の野郎、ざまぁみやがれってんだ…！」\
`"That bastard, Shuuichi. Serves him right...!"`\
cl r,0
ld c,SMI_D2,24

;「……そう。@でも玲子、心配……。@昨日もみんなが懲らしめてくれたのに、朝来たらまた上履き隠されてたし……。」@
`"...Yeah. `@`But I'm worried... `@`Even though you punished him for me yesterday, this morning my school shoes were missing again..."`@
;「え、そうなの？！」\
`"Ah, really?!"`\
ld c,SMI_D1a,80

;「うん……。@下駄箱の中になかったから、探したんだけど見つからなくて……。@そしたら秋一くんが焼却炉の中に捨てようとしてたのを見ちゃったの……。」\
`"Yes... `@`They weren't in the shoe rack, so I looked around for them, but to no avail... `@`Then, I saw Shuuichi-kun as he was throwing them into the incinerator..."`\
mov %SMI_Isyou,2
bg black,0
ld c,SMI_w6,22

me1v 28,50

;　もちろん、それはスミレのでっち上げだ。@
`　Of course, this was a fabrication on Sumire's part.`@
br
;　スミレはいじめを媒介にして狩りをする。@
`　Sumire was using bullying as a form of hunting.`@
;　適当な嘘をついて、いじめをする大義名分を与え、いじめっこを生み出す。@
`　She would use her lies to instigate bullying under the pretext of giving the boys a just cause.`@
;　彼女の魔性の涙が、それを可能とするのだ。\
`　Her Devil's Tears allowed her to do so.`\
mov %SMI_Isyou,1
bg black,22
bg sadou_02,22

;「マジかよ！？@　またやったのかよ、あいつ！」@
`"Seriously? `@`He did it again?!"`@
ld l,SMI_D6,23
ld l,SMI_D2,80

;「それに、秋一くん、今日も授業中とか体育の時間とかジーッと玲子のこと見つめてきて……。@何だか怖くて………。」@
`"What's more, Shuuichi-kun was staring at me all day today during class and gym.... `@`It's making me kind of scared....."`@
;「あの変態野郎ッ、……全然懲りてねぇじゃん！」\
`"That damn pervert... he hasn't learned anything at all!"`\
ld l,SMI_n3,80

;「それに、あんまり疑いたくないんだけど……。@最近は着替えとか、水着とか、そういうのなくなること多くて………。@……玲子……、怖い………。」\
`"And then, I want to believe that it wasn't him... `@`but recently my gym clothes, and swimsuit and stuff have all gone missing.....`@` ...I'm... scared...."`\
;　スミレは怯えながら、魔性の涙をぽろりと零す。@
`　Acting frightened, Sumire shed her Devil's Tears.`@
br
;　その涙は、いじめの味を教え、さらなるいじめっこを生み出す力を持つ……。\
`　Those tears had the power to give people a taste of what it's like to bully, and even birth new bullies.`\
quakey 1,100

;「秋一のヤツ、絶対ぇ許さねぇ！！」@
`"That bastard Shuuichi! I'm never gonna forgive him!!"`@
;「大丈夫だからな、玲子ちゃん！@　明日、俺らがまた思いっきり懲らしめといてやるからなッ！」@
`"It's okay, Reiko-chan! `@`Tomorrow, we'll really teach him a lesson!"`@
;「今度こそ、ギタギタにしてやろうぜ！！@　ぶっ殺したって構わねぇ！！」\
`"This time we'll beat him to a pulp!! `@`I don't even care if we kill him while we're at it!!"`\
cl l,0
ld c,SMI_n1,23

;「………ありがとう。@……玲子、あなた達しか頼れる人いないの。」\
`"....Thanks.`@` ...You guys are the only ones I can depend on."`\
;「おう！@　俺らに任せとけって！」@
`"Yeah! `@`Leave it to us!"`@
;「そうだよ！！@　二度と玲子ちゃんに手出しできないように、マジで腕の一本でもへし折っちまおうぜ！！」\
`"That's right! `@`We'll even go so far as to break one of his arms to make sure he never bothers you again, Reiko-chan!!"`\
ld c,SMI_D6,80

;「……でも、玲子怖いなぁ……。@みんなが私のために秋一くんを殴ったって知られたら、@……玲子、今までよりもっと秋一くんにいじめられちゃうかもしれない……。」\
`"...But I'm scared.... `@`If Shuuichi-kun finds out that you've been doing all of this for me... `@`he might just bully me even more..."`\

;「大丈夫だって！@　今まで通り、秋一や他のみんなには内緒にするからさ。」@
`"Don't worry! `@`Just like before we'll make sure to keep that a secret from Shuuichi and everyone else."`@
;「そうそう！@　まぁ、何も言わなくてもわかれって話だよな。@これはいじめじゃなくて、天罰だっつーの！」@
`"Yeah yeah! `@`It doesn't matter if we don't tell him. `@`This isn't bullying, it's divine punishment!"`@
;「普通、あんだけ絡まれたら、天罰だと思わねぇかよなぁ？！」\
`"Don't you think that if he's picking on you that much, it deserves divine punishment?!"`\
ld c,SMI_D2n,80

;「……玲子、思うの。@秋一くんも、あなたたちみたいに人の気持ちが分かる男の子になって欲しいなって……。」\
`"...I think, `@`that Shuuichi just wants to become a person that understands people's feelings like you guys...."`\
;「玲子ちゃんは優し過ぎるよ！@　普通、自分のこといじめる奴にそんな風に思えないって。」@
`"Man, Reiko-chan, you're too kind! `@`Most people don't try to sympathize with their bully."`@
;「それが玲子ちゃんのいいところなんだけどさ。」@
`"That's what makes you so great, Reiko-chan."`@
;「そんな玲子ちゃんだからこそ、俺たちで守らないと！」@
`"And that's why we'll protect you!"`@
;「うんうん！」\
`"Yeah!"`\
ld c,SMI_D5,80

;「ありがとう。@……じゃあ、みんな、明日もよろしくね。@/
`"Thanks you guys.`@` ...Alright, I'll be relying on you tomorrow too then.`@/
mov %SMI_Isyou,2

se1 84

bg black,0
ld c,SMI_w6,2

;……ふっふふひひひ……。」\
` ....Fufufuhihi..."`\
bg black,2

fede 0,2000
E_A

bg okujou_03u,22

me1v 5,50

;　黄昏時が近付き、空の色が橙から紫へ、淡く美しいグラデーションを見せる頃。@
`　As twilight approached, the sky turned from orange to violet, and displayed a beautiful gradient of colors.`@
br
;　彼岸花の姿は屋上にあった。\
`　Higanbana was on the rooftop.`\
bg black,22
bg okujou_01u,0
ld l,HIG_D8,22

wait 1000

ld r,KOU_D5,22

;「おや、彼岸花くんではないかね。@……お邪魔だったかな？」@
`"Oh, if it isn't Higanbana-kun.`@` ...I'm not interrupting anything, am I?"`@
;＜校長

ld l,HIG_D10,80

;「……邪魔だったら、有無を言わさず、引き裂いているわ。校長先生？」\
`"...If you were, I would be tearing you apart without hesitation right now. What is it, Headmaster?"`\
;　この恰幅の良い紳士の姿をした妖怪は、通称、「校長先生」。@
`　This youkai taking the form of a portly gentleman was known only as 'The Headmaster.'`@
br
;　その名の通り、すでに校内のあらゆる妖怪の頂点に立つことを、自他共に認める大妖怪だ。\
`　He's a greater youkai and, as his name suggests, is generally accepted as presiding over all the other youkai within the school.`\
;　かつては彼岸花と、壮絶な争いを繰り広げたこともある。@
`　A great battle had once unfolded between him and Higanbana.`@
br
;　しかし、校長が彼岸花と戦うことを望まなくなってからは、刃を交えることはなくなっていた。\
`　But his desire to fight her had faded, and the two of them no longer crossed swords.`\
bg black,22

fede 0,1000
E_A

bg Air_01,22

bgm1 8

;「ねぇ、校長先生。」@
`"Hey, Headmaster."`@
;「何だね。」\
`"What is it?"`\
;「……………………。@……私たち妖怪って、何のために存在するのかしら。」@
`"..........`@` ...Why do we exist, us youkai?"`@
;「わからんね。@だが、ひとつだけ言えることがあると思っているよ。」\
`"I'm not sure. `@`But there is one thing I can say for certain."`\
;「………何？」@
`"...What's that?"`@
;「人間が存在しなければ、我ら妖怪も存在できないということだよ。」\
`"If humans didn't exist, then we youkai wouldn't either."`\
;「……つまり、私たちは人間の一部だということ？」@
`"...Meaning we're just another part of humanity?"`@
;「そう言ってもいいかもしれんね。@あるいは、我らは人間の影なのかもしれん。@人間が存在するからこそ、その影に我らが存在できるのだよ。」\
`"You could say that. `@`Or maybe we are of the shadow of humanity. `@`That because humans exist, we are able to live in their shadows."`\
bg okujou_01u,0
ld l,HIG_D9,0
ld r,KOU_D3,22

ld l,HIG_D8,80

;「つまり、私たち妖怪は所詮、人間の寄生虫だということね。」\
`"In other words, us youkai are just parasites to humanity."`\
ld r,KOU_D2,80

;「君は、自分をそう思っているのかね？」@
`"Is that really what you think of yourself as?"`@
ld l,HIG_D9,80

;「………だって、そうでしょう？@　人間たちに取り憑き、魂のおこぼれを摘み食いして生き延びてる。@それが寄生虫じゃなくて、何だというのよ。」\
`"....But aren't we? `@`We survive by latching onto humans and pick away at the scraps of their souls. `@`If we're not parasites, then what are we?"`\
textoff

wait 1000
ld r,KOU_D1,80

;「君がそうだと思っているのなら、そうなのではないかね？」@
`"If that's what you think, then isn't that what we are?"`@
ld l,HIG_D8,80

;「……………そうね。」\
`".......I guess."`\
bg black,22

;　寄生虫に感情はいらない。@
`　Parasites don't need feelings.`@
;　ただ生きるためだけに、日々を繰り返せばいい。@
`　They just repeat day after day, living for the sake of living.`@
br
;　……でも、そんな日々に、緩慢な苦痛を覚えたのだ……。\
`　...But as those days passed, I felt a dull agony...`\
ld c,HIG_D9,22

;　なら、私は寄生虫じゃない。@
`　In that case, I must not be a parasite.`@
br
;　私は誰？@
`　Who am I?`@
;　私は妖怪。@
`　I am a youkai.`@
;　なら、妖怪とはどうあるべきなの……？\
`　Then what is a youkai really....?`\
bg black,22
bg okujou_02,22
ld l,KOU_D3,22

;「私は私なりの答えを見つけているがね。@だが、君にそれを教えて、押し付けようとは思わんよ。」@
`"I have found my own answer to that question. `@`But don't think that I'd try to impose my opinion on you."`@
ld r,HIG_D8,24

;「ケチ。」\
`"So stingy."`\
ld l,KOU_D1,80

;「ほっほっほっほ。@君はまだまだ若い妖怪だ。@色々と考えたまえ。@それがきっと、君のためになる。」\
`"Ho ho ho. `@`You're still a young youkai though. `@`Take some time to think about it. `@`I'm sure that it will benefit you."`\
ld r,HIG_D10,80

;「ねぇ、校長先生。@………あんたにはあるの？@　感情ってヤツ。」@
`"Hey, Headmaster.`@` .....Do you have them? `@`Emotions, I mean."`@
ld l,KOU_D4,80

;「あるとも。」\
`"I do."`\
ld r,HIG_D8,80

;「それは、………楽しいもの？」@
`"Do you.... enjoy them?"`@
ld l,KOU_D1,80

;「もちろん。」\
`"Of course."`\
ld r,HIG_D9,80

;「………それは、なくてはならないもの？」@
`".....Are they something that you need to have?"`@
ld l,KOU_D3,80

;「わからんね。@……ただ、一つだけ言えることがある。」\
`"I'm not sure.`@` ...But there is one thing I can say for certain."`\
ld r,HIG_D10,80

;「何？」\
`"What's that?"`\
bg black,22

;cl l,0
;ld c,KOU_D1,23

;「それがなければ、人間ではない、ということだよ。」\
`"Not having them, makes you not human."`\
;ld r,HIG_D8,80

;「私たち、妖怪よ？」@
`"But we're youkai?"`@
;ld c,KOU_D3,80

;「妖怪が人間の影であるなら。@私たちが持っていてもおかしいことではないね。」@
`"If youkai are the shadows of humans, `@`would it really be that strange for us to have emotions too?"`@
;ld r,HIG_D10,80

;「………………………………。」\
`"..................."`\
;bg black,23
bg okujou_01u,0
ld r,KOU_D3,22

me1v 5,50

ld r,KOU_D2,80

;「君はとても強い妖怪だが、未熟な存在でもある。@幸いにも、他の妖怪たちに脅かされない程度の妖力を持つことが出来た。@……なら今度は、自らについて考えることに時間を割くのも良いのではないかね。」\
`"You are a very powerful youkai, but you are young. `@`Fortunately, you had more spiritual power than the other youkai could shake a stick at.`@` ...So now, I think you should make some time for a little introspection."`\
ld l,HIG_D9,22

;「私の、……在るべき姿。@………為すべきこと。」@
`"How... I should be.`@` .....And what I should do."`@
ld r,KOU_D1,80

;「ほっほっほっほ。@考えたまえ、色々と。」@
`"Ho ho ho ho. `@`Take some time to think about it."`@
ld l,HIG_D8,80

;「そうね。@……そうするわ。」\
`"Yeah.`@` ...I'll do that."`\
bg black,2
bg okujou_03u,22

;ld l,KOU_D2,22

;「この学校の混乱も、なかなか落ち着かんね。@見たまえ、眼下の子供たちを。@……乱れ、恐れ、心を邪悪に支配されている。@誰かを見下し、常に傷つけていないと、自らの安寧さえ保てない。」\
`"The disorder in this school has been spreading too. `@`Go look at the students in the halls.`@` ...They're confused, scared, and their hearts are being ruled by evil. `@`They can't keep the peace unless they are constantly looking down on and hurting others."`\
;ld r,HIG_D10,22

;「……最悪のクソガキどもだわ。」\
`"...Horrible little brats."`\
ld l,KOU_D4,22

;「人間は陽の下に生きるよう定められた存在だ。@邪悪なる闇の中にまで、足を踏み入れてはならない。@……だからこそ、彼らの闇を領分とする存在が必要だと思うのだよ。@私は、それが妖怪の役目だと思っているよ。」\
`"Humans are beings that live in the sunlight. `@`They must not set foot into the evil darkness.`@` ...So there must be something that inhabits their darkness. `@`I believe that is the role the youkai play."`\
ld r,HIG_D8,22

;「それが、あんたなりの解釈？」@
`"That's your interpretation then?"`@
ld l,KOU_D3,80

;「押し付けようとは思わんよ。」\
`"Don't think that I'm pushing it on you."`\
ld r,HIG_D9,80

;「………子供たちって、………こうして見下ろしていると、本当に残酷よね。」@
`".....The way that.... these children look down on others is really cruel."`@
ld l,KOU_D2,80

;「学校の中では特に残酷だよ。@ここには、人間社会の秩序も法律も届かないからね。@一般社会では警察沙汰になるようなことも、ここでは喧嘩両成敗で済まされる。」\
`"It's especially cruel within these schools. `@`The order and laws of human society do not reach within these walls. `@`The police do not investigate disputes here, instead everyone taking part in a fight is considered at fault."`\
ld r,HIG_D8,80

;「誰がどう残酷だろうと、知ったことではないけれど。@……………………………。」@
`"But no one's really concerned with who started it.`@` ............"`@
br
;　秋一を石投げの的にしようとした連中を見た時の、……あのこみ上げる感じが、また胃の中いっぱいに広がる。@
`　One again, I felt that nauseating feeling spread throughout my insides... the same way it did when those boys tried to hit Shuuichi with that rock.`@
;　……………………………。\
`　.................`\
bg black,22

;　自分は何のために存在するのだろう。@
`　Why did I exist?`@
;　何のために存在すればいいのだろう。@
`　Why should I exist?`@
br
;　その答えの鍵を、………なぜか、あいつが持ってるような気がする。\
`　For some reason... I feel like he's the one who holds the key to that answer.`\
ld c,SHU_D4,22

;　秋一。@
`　Shuuichi.`@
br
;　あいつと話していると、その鍵が見つかりそうな気がするのだ。\
`　When I'm talking to him, I feel like I can find that key.`\
bg black,2
se1v 86,40
wait 500
se2v 86,1

bg okujou_02,22

fede 1,3000
wait 1000

ld r,KOU_D2,22

;「………何やら今日は騒がしいね。」@
`".....It seems like it's been quite hectic today."`@
ld l,HIG_D9,24

;「何？@　救急車？」@
`"What's that? `@`An ambulance?"`@
br

E_ 3,1

;　独特のサイレンが校門前で止まる。\
`　The characteristic siren stopped outside the school gate.`\
ld r,KOU_D5,80

;「誰かが怪我をしたようだね。」@
`"It seems that someone has been injured."`@
ld l,HIG_D10,80

;「…………………………………。」@
`"................"`@
ld r,KOU_D2,80

;「どうしたね？」\
`"Is something the matter?"`\
ld l,HIG_D9,80

;「……お喋りが出来て楽しかったわ。@次に会う時は殺し合いをしましょ。@……じゃあね。」@
`"...It was fun talking with you. `@`But next time we meet let's fight to the death.`@` ....See you."`@
E_A

se1v 20,30
cl l,22

br
;　挨拶もそこそこに、彼岸花は屋上から飛び降りる。\
`　With a hurried farewell, she jumped from the rooftop.`\
bg black,25

me1v 24,50

bg gakkou_03,22

;　ふわりと地面に降り立ち、人混みを掻き分ける。@
`　She landed gently on the ground and pushed her way through the crowd of people.`@
br
;　……どういうわけか、胸騒ぎがした。\
`　....She had a bad feeling about this.`\
bg black,22

fede 0,2000
E_A

mono 1
bg gakkou_08,22

bgm1 27

;　体育倉庫で見つかった秋一は、異様な姿で発見されたらしい。@
`　It seems that Shuuichi had been found in the P.E. storeroom, in a bizarre condition.`@
;　……最初、それを見つけた子は、誰かがふざけているのかと思ったらしい。@
`　...At first, the kid that found him thought someone had just been messing around.`@
br
;　なぜなら秋一は、頭にすっぽり紙袋を被せられていたからだ。\
`　Why else would Shuuichi's head be covered with a paper bag?`@
;bg black,22
mono 0
;se1 33
bg blood_1b,22

;　しかし、その紙袋は、血でべっとりと汚れていた……。\
`　However, the bag was drenched in blood...`\
bg black,22
bg gakkou_03,22

me1v 24,50

;「はい、担架通りまーす、担架通りまーす！！」@
`"Watch it! Stretcher coming through!!"`@
;「……どうしたの？@　何があったの？」@
`"...What's going on? `@`What happened?"`@
;「いじめらしいよ。@ざわざわざわざわ。」\
`"It looks like bullying. `@`mutter mutter mutter...."`@
ld c,HIG_D10a,22

quakex 1,100

;「秋一っ。秋一！」@
`"Shuuichi! Shuuichi!!"`@
;＜彼岸花
br
;　担架で担ぎ出される秋一に声を掛けるが、彼の意識はないようだった。@
`　She called out to Shuuichi as he was taken away on the stretcher, but he didn't seem to be conscious.`@
;　そして、……妖怪であるはずの彼岸花であっても、その秋一の顔のあまりの惨たらしさに絶句する。\
`　And... even Higanbana, who was a youkai, was at a loss for words at the gruesome condition of Shuuichi's face.`\
bg black,22
bg aka3,22

;　服を見れば、それが秋一であるとはわかるのだが。@……顔を見ただけでは、誰か判別することは不可能だ。@
`　She could tell that it was Shuuichi because of the clothes he wore.`@` ...But no one would have been able to tell that by looking at his face.`@
br
;　血まみれになって、ぶくぶくと腫れ上がり、どこが頬で鼻で口かもわからないほどなのだから……。\
`　His face was so swollen and bloodstained that he couldn't even make out where his cheeks, nose or mouth were...`\
;　秋一が無抵抗なのをいいことに、……際限なくいじめがエスカレートしたに違いない。@
`　Shuuichi never put up a fight... so the bullying must have escalated to no end.`@
br
;　いじめ？@
`　Bullying?`@
;　これはもはや、いじめと呼んでいいことなのだろうか。\
`　This can't just be called bullying anymore.`\
bg black,22

;　これは暴行でさえない。@蛮行だ。@
`　This wasn't even assault. `@`This was savagery.`@
br
;　人間に許された行為じゃない。\
`　To humans, this was an inexcusable act.`\
;bg kyou_04,22

;　しかし、学校の中という異世界では、許されてしまうのだ。@
`　But in this alternate universe known as school, this was regrettably forgiven.`@
br
;　学校は聖域。@ゆえに、あらゆる法律の治外法権。@
`　School was a sanctuary. `@`And therefore, exempt from the laws of the outside world.`@
;　いじめの兆しなどなかったと繰り返す教師たちは、ここであった全てを揉み消す。@
`　Teachers here smothered and covered up all signs of bullying.`@
br
;　これが、秩序なき、カオスなる学校世界なのだ。\
`　This was the orderless and chaotic world of school.`\
;bg black,22
bg gakkou_03,22

;　人混みを遠くから、三人組がくすくす笑いながら見ている。@
`　Standing apart from the crowd, a group of three students were watching the commotion and giggling.`@
br
;　いつも秋一をいじめていた、あの三人組だ。\
`　It was the trio that had been bullying Shuuichi.`\
;「何だよ、救急車かよ。@霊柩車が来ればいいのに！」@
`"What, just an ambulance? `@`A hearse would have been better!"`@
;「病院で死ねばいいのによ。@ぷーっくっくっくっく！！」@
`"Maybe he'll die in the hospital. `@`Heheheheheh!!"`@
;「正義の鉄槌、思い知りやがれ！@　げらげらげら！！」@
`"We brought down the iron hammer of justice upon him! `@`Hahahah!!"`@
;「俺たちがやったなんて、誰も見てねぇし！」@
`"And nobody saw us do it!!"`@
;「仮に見られてたって、俺たち、少年法で無罪だしー！@　ぷーくすくすくすくす！！」\
`"Even if someone did, we'd just be judged not guilty because of juvenile law! `@`Hehehahaha!!"`\
bg black,22
bg gakkou_02u,22
;ld c,HIG_D1,22

;　学校は聖域。@
`　School was a sanctuary.`@
br
;　ここでは子供は守られている。@
`　Children were protected here.`@
;　あらゆる魔手から。@そして、秩序からも。\
`　Protected from victimization. `@`And from discipline.`\
;ld c,HIG_D1,80

;　ここには、一般社会のあらゆる法も常識も届かない。@
`　The laws and common sense of the general public didn't reach here.`@
br
;　ただ、無法のジャングルで、無抵抗の小動物が肉食獣に喰われた。@
`　It was simply an unjust jungle, in which the smaller passive animals were eaten by the carnivores.`@
;　ただそれだけのことのはず……。\
`　That's just how things were...`\
bg black,2

fede 0,1000
E_A
wait 1000

bg byouin_01,22

bgm1 24

;　病院に担ぎ込まれた秋一は、集中治療室で手当てを受けていた。@
`　Shuuichi had been rushed to hospital and received treatment in the intensive care unit.`@
;　幸いにも峠を越えることが出来たようだが、重症であることに変わりはない……。@
`　Fortunately, he was able to survive the most intensive part of his hospitalization, but his condition was still critical.`@
br
;　そのベッドの傍らに、彼岸花はそっと姿を現す。\
`　Higanbana appeared silently at his bedside.`\
ld l,HIG_D10,2

;「……………………秋一。」\
`"..........Shuuichi."`\
;「………その声は、……彼岸花さんなの。」@
`"...That voice... is that you, Higanbana-san?"`@
;＜秋一は立ち絵不要です。@

ld l,HIG_D9,80

;「そうよ。」\
`"Yeah."`\
;「……学校の妖怪は、学校にしかいられないんだと思ったよ。」@
`"....I thought that school youkai couldn't leave the school."`@
ld l,HIG_D8,80

;「学校妖怪は学校で生きていくように出来ているわ。@……外へ出ることも出来るけれど、あまり居心地は良くないし、とても妖力を使う。@とても疲れることなの。」\
`"We live in the school.`@` ...We can leave it, but it makes us uncomfortable, and requires a lot of spirit energy. `@`It's very tiring."`\
;「………なのに、わざわざ来てくれたんだね。@……お見舞いに来てくれて、ありがとう……。」@
`"....Yet, you came all this way.`@` ...Thank you for coming to see me...."`@
ld l,HIG_D10,80

;「こんな目に遭っても。@まだ感情を楽しめるというの？@　この酷い有様でも、生きている証だと？」\
`"After going through such suffering, `@`do you still enjoy having emotions? `@`Do you still see this horrible state of affairs as proof that you're alive?"`\
mbg black,22

;「………………………………。」@
`"..............."`@
;ld l,HIG_D9,80

;「………………………。」\
`".............."`\
;　多少は嫌味のつもりで言った。@でも、いつもの秋一なら、あっけらかんと言い返してくれるはず。@……それを期待していた。@
`　I was being somewhat sarcastic. `@`Usually Shuuichi would shrug it off and laugh a little.`@` ...I waited for his usual response.`@
br
;　しかし、秋一は何も答えない。\
`　But he didn't answer at all.`\
;　当然だ。@この有様で、何を言えるというのだろう。@
`　It was only natural. `@`After all, what could he say in this situation?`@
br
;　その当り前に、彼岸花も言葉を失った。\
`　Naturally, Higanbana too was at a loss for words.`\
cl l,0
mcbg 22
ld r,HIG_D8,22

;「……死ぬわけじゃないでしょ。@しばらくは寝込むんだろうけど、どうせ数か月もしたら元通りよ。」\
`"...It's not like you're going to die. `@`You'll have to take it easy for a while, but in a few months you'll be back to normal."`\
;「………………………。@……元通りには、ならないみたい。」@
`"............`@` ...They said, they'll never be back to normal."`@
ld r,HIG_D9,80

;「何が…？」@
`"What won't...?"`@
;「目。」\
`"My eyes."`\
ld r,HIG_D10,80

;「目？」@
`"Your eyes?"`@
;「……もう、見えないって。」@
`"...I can't see anymore."`@
br
;　その言葉に、彼岸花はもう一度、絶句した。\
`　With those words, Higanbana was once again speechless.`\
bg black,22

;　彼女にも、もうわかっている。@
`　She understood now.`@
br
;　彼の目に宿っていた、人には見えぬ何かを見ることの出来る力が、失われているのがわかるのだ。\
`　He had lost that power in his eyes which enabled him to see things other people couldn't.`\
bg aka1,22

;　眼球破裂。@それも、両目が。@
`　They were ruptured. `@`Both eyes.`@
br
;　どれほどの慈悲のない仕打ちを受けたのだろう。@
`　How mercilessly had he been treated?`@
;　頭蓋の一部にもひびが入り、それでもなお、脳に障害が至らなかったのは奇跡だろう。\
`　A part of his skull had also been cracked. It was a miracle that he didn't have some sort of brain damage.`\
bg black,22
bg byouin_01,22

;「もう、一生。@……何も見えないって、先生が。」@
`"The doctor said.... `@`That I won't see anything ever again."`@
ld c,HIG_D9,22

;「………………………。」\
`".............."`\
;「悔しいなぁ……。@……もっともっと、……様々な感情を通して、……様々なものを見たかったのになぁ……。」@
`"It's frustrating...`@` ...There were... so many more emotions I wanted to have... and so many more things I wanted to see..."`@
ld c,HIG_D10,80

;「……両腕がなくなったわけじゃないでしょう？@　スケッチブックを広げて、鉛筆を握ることのできる腕は、ちゃんとあんたに付いているわ。」\
`"...It's not like you lost your arms, right? `@`You can still open your sketchbook and hold a pencil."`\
;「でも、もう見えないんだ。@見ることが出来ないんだ。@………無数の感情を通して、……万華鏡のように千変万化する景色を、見られないんだ……。@それを、絵を通して誰かに見せることも出来ない。@…………もう僕は、……画家にはなれないんだ…………。」\
`"But I can't see anymore. `@`I'm blind.`@` ......I can no longer see... the scenery constantly changing through countless emotions, like a kaleidoscope... `@`I can't show people what I see through drawing anymore.`@` .....I can... no longer become an artist......"`\
bg black,8

;　秋一の辛い記憶が、隠されることなく心から漏れ出ている。\
`　Shuuichi could no longer keep the painful memories from leaking out from his heart.`\
;bg note1,22
ld c,SHU_D3,22

;　……彼は目を潰されただけではない。@
`　...His eyes were not the only thing of his that was destroyed.`@
br
;　たくさんの感情を書き留めた、あのスケッチブックまで奪われ、……焼却炉に放り込まれたのだ。\
`　The sketchbook which he'd used to document all his feelings had been stolen... and thrown into the incinerator.`\
;se1 55
bg red1,1
bg black,0
ld c,SHU_D5,0
print 99,2000,"breakup.dll/llb"

se1v 1006,50

mbg white,1
lsp bgsp,":a;bmp\background\efe\ware.bmp",0,0
print 1
mcbg 1
;csp -1
;cl c,0
;print 22


;　彼が確かに見てきた光景の記録さえも、すでにこの世に残っていない。@
`　Every record he had made of the world he saw had been destroyed.`@
;　彼が生きた証が、奪われたのだ。@
`　The proof that he had lived, had been stolen from him.`@
br
;　生きた証とは、生そのもの。@
`　That proof that he had lived, was his life itself.`@
;　彼は、殺されたのだ。\
`　He had been killed.`\
csp -1
print 0
bg black,22
bg byouin_01,0
ld l,HIG_D10,22

;「……………ねぇ、秋一。」@
`"......Hey, Shuuichi?"`@
;「何……？」\
`"What is it...?"`\
ld l,HIG_D9,80

;「あんたは今、目を潰されて、夢まで潰されたわけだけど。」@
`"Your eyes, and even your dreams, are now crushed right?"`@
;「……うん。」\
`"...Yeah."`\

ld l,HIG_D10,80

;「それでもなお。@今のその感情ってヤツを。@……あんたは楽しんでいるの？」@
`"Nevertheless. `@`Can you still say... `@`that you enjoy your emotions?"`@
;「……………………………。」\
`".............."`\
ld l,HIG_D8,80


;「……ねぇ、答えて。」@
`"...Hey, answer me."`@
;「……………………。」@
`".........."`@
br
;　それっきり、秋一が答えてくれることはなかった。\
`　Shuuichi never did answer.`\
bg black,22

;　やがて彼岸花は気付く。@
`　Higanbana finally realized.`@
br
;　彼が人ならざる者である自分と、これまで交流できたのは、あの目の力に違いないと。\
`　His ability to communicate with youkai, was due to his eyes.`\

;　それが失われたのだから、……もう彼と話せないのは当然なのだ。@
`　He had lost them... So it was only natural that she couldn't speak to him anymore.`@
;　彼岸花は、一番聞きたかった最後の答えを、永遠に得られない。@
`　The final question that Higanbana wanted answered the most, would go forever unanswered.`@
br
;　その時、初めて。@……彼岸花は、校長の言葉を理解した気がした。\
`　And, for the first time... `@`Higanbana felt like she understood the words of the Headmaster.`\
me1v 5,50

bg Air_03,2

;　妖怪とは、人間の影であるということ。@
`　Youkai are the shadows of humans.`@
;　昼があれば夜があるなら。@人は昼を、妖怪は夜を支配すべき。@
`　If there is day, then there must be night. `@`Humans rule the day, while youkai rule the night.`@
br
;　彼は昼間に生きるに相応しい人間だった。\
`　As a human, he deserved to live in the daylight.`\
;mld c,HIG_D9,22

;　ならば、闇夜に生きるに相応しい者が、闇夜を支配しなくてはならない。@
`　And those who deserved to live in the dark of night, must also govern it.`@
;　人間如きが、その領分を誤ることがないように。\
`　So that those who are human never make the mistake of entering the dark.`\
bg black,22
bg byouin_01,22

mld c,HIG_D8,22

;「秋一。@……私はようやく理解したわ。@ありがとう。」@
`"Shuuichi.`@` ...I finally understand. `@`Thank you."`@
br
;　もちろん、秋一は答えない。@
`　Of course, Shuuichi didn't reply.`@
;　もう彼岸花の声を聞くことも、応えることもない。\
`　He would never hear nor respond to Higanbana's voice again.`\
mld c,HIG_D10,22
mcl c,2

;　彼岸花はふわりと姿を消し、病院を後にする。\
`　Higanbana's figure gently disappeared, and departed from the hospital.`\
bg black,22

fede 1,1000
E_B

bg Air_03,22

;　月明かりさえない闇夜を、人間たちが細々とした人工の明かりで辛うじて照らし出す、無機質な町。@
`　It was a dark, moonless night in an inorganic town, with the humans just barely fending off the darkness with feeble man-made lights.`@
br
;　こんな闇夜に人間が出歩くことはない。@
`　Humans never went out on nights as dark as these.`@
;　それは、人間は陽の下を歩くように定められ、闇の中を歩くように定められていないからだ。\
`　That was because humans walk under the sun, and not the cover of nightfall.`\
;bg black,22

;　ならば、学校もそうであるべきだ。@
`　The same held true for school.`@
br
;　学校妖怪もそうあるべきなのだ。\
`　And for the school youkai as well.`\
;bg Air_03,0
ld c,HIG_D8,2

fede 0,1000
E_A

se1v 84,100

ld c,HIG_w5,80

bgm1 20

;「ふ、ふっふふふふふふふ、くすくすくすくすくすくす……。」@
`"Fu, fufufufufufufufu, teeheeheeheehee...."`@
br
;　彼岸花は笑った。@初めて笑った。\
`　Higanbana laughed. `@`For the first time, laughed.`\
se1v 20,30

cl c,26
quakey 1,100

;　電柱から電柱へ飛び移り、闇夜を疾駆して学校を目指しながら、誰にも聞くことの出来ぬ声で笑い続けた。\
`　She leapt from telephone pole to telephone pole, galloping towards the school, all the while laughing in a voice no one could hear.`\
;「理解したわ、ようやく。@ようやく。@あなたのお陰よ、秋一。@あなたのお陰で、私はようやく理解できたっ。」\
`"I understand, finally. `@`Finally. `@`And I owe it all to you, Shuuichi. `@`Thanks to you I can finally understand."`\
me1v 5,50

bg black,22

;　自分の為すべきこと。@
`　I know what I need to do.`@
;　妖怪の在るべき理由。@
`　I know why we youkai exist.`@
br
;　闇の中に巨体を横たえる校舎の大空に、彼岸花は飛翔する。\
`　Higanbana flew towards the gigantic school on the horizon.`\
bg okujou_03u,22

;「ほら、夜の学校には人間など誰もいないっ。@……どうして？」@
`"Hey, at night, there are no humans at the school.`@` ....Why's that?"`@
br
;　それは、夜の学校を、私たちが支配しているから。\
`　It's because we rule the school at night.`\
bg black,24
bg okujou_01y,24
ld c,HIG_w3,25
se1v 12,40
quakey 2,200
wait 1000
ld c,HIG_w5,80


;「夜の学校は私たちのもの！！@　人間たちの誰にも、立ち入らせたりするものか！！@　神聖なる夜を侵す愚かなる者どもに鉄槌を！@　あぁ、夜の闇をさらにさらに暗く染めることこそ、/
`"The school is ours at night!! `@`No human must ever trespass on our domain!! `@`We will judge those foolish enough to invade our sacred night! `@`We will dye the night even darker,`/
se1v 84,100

;私たちの役目なのだから…！！」\
` because that's the role we play...!!"`\
bg black,2

fedexx 100,0,0,0,0,0,3000
wait 3000

E_A





me1v 26,50

;　ぺた、ぺた、ぺた、ぺた………。@
`　Pit, pat, pit, pat.....`@
;　ぺた、ぺた、ぺた、ぺた、ぺた、ぺた………。@
`　Pit, pat, pit, pat, pit, pat, pit, pat......`@
br
;　どこからか奇妙な音がする。@
`　A strange sound was coming from somewhere.`@
;　近いような、遠いような、耳のすぐ近くのような………。\
`　It sounded near, and far, and right beside his ears....`\
;「……………………………。」@
`"................"`@
br
;　再び眠りの世界へ戻ろうと、寝返りをうつ。@
`　In an attempt to go back to sleep, he turned over in bed.`@
;　そう。@少年はやっと眠れたのだ。@なのに、それを覚まされるなんて、腹立たしい。\
`　Yes. `@`He had finally gone to sleep. `@`And being woken was irritating.`\
;　彼は秋一にあの大怪我を負わせた三人組の一人だった。@
`　He was one of the three boys who had inflicted serious injury on Shuuichi.`@
br
;　今日の体育倉庫の一件の興奮が冷めず、なかなか寝付けなかったのだ。\
`　He was still worked up from what had happened in the storehouse today, and was having trouble sleeping.`\
;mono 1
;bg white,28
;mono 0
;bg kyou_01,22

;　少年にもわかっている。@普通なら、あれは犯罪だ。@警察沙汰の大事だ。@
`　Even the boy knew. `@`Normally this would be a crime. `@It'd be a police matter.`@
br
;　でも、学校の中は聖域！@　誰にも咎められない。@
`　But the school is a sanctuary! `@`Nobody can blame him.`@
;　とばっちりを恐れる教師たちが、全て揉み消して、なかったことにしてくれる。@
`　Teachers, out of fear of being victims of circumstance, would cover everything up.`@
br
;　いっそ、あいつがあのまま死んでくれないかな。@そうすれば、全部、うやむやにできる。\
`　Hopefully he'll die in the hospital. `@`Then the whole matter would blow over unsettled.`\ 
mono 1
bg gakkou_03,2

bgm1 10

;　それにしても秋一を袋叩きにするのは、本当に楽しかったッ！@
`　But even so, beating up Shuuichi was so much fun!`@
br

se1 10
quakex 1,100

;　ひとつ蹴るごとに、じわぁと充足感が広がり。@
`　First, each kick gave him a wonderful sense of fulfillment.`@
se2 10
quakey 1,100
br
;　ふたつ殴るごとに、じわぁと満足感が広がる。\
`　Second, each punch gave him satisfaction.`\
;　無抵抗の相手に乱暴の限りを尽くす、蹂躙。@
`　They inflicted a whole range of violent acts against their passive enemy.`@
br
;　それがこんなにも楽しいなんて！\
`　That was so much fun!`\
mov %SMI_Isyou,1
;bg black,22
ld c,SMI_D2,22

;　最初のきっかけこそ、クラスの女子の頼みだったけれど、もうそんなの関係ない。@
`　They originally just doing this for the girl in their class, but not anymore.`@
br
;　どいつもこいつも、ムカつくヤツはみんな秋一みたいにしてやる！\
`　They're going to make everyone they hate look just like Shuuichi did!`\
;bg black,22
bg e008,22

;　俺たちは自由だ。@学校では自由なんだ。@
`　We're free. `@`In school we're free.`@
;　誰にも縛られない、誰にも咎められない！@
`　We can't be bound by anyone. We can't be blamed by anyone!`@
br
;　ははは、あっはははははは、はーっはっはっはっはっは！！\
`　Hahaha, ahahahaha, haahahahaha!!`\
bg black,22
;mono 2
;bg Different_spiral_1a,22

fede 1,2000
E_B

;　ぺた、ぺた、ぺた、ぺた………。@
`　Pit, pat, pit, pat.....`@
;　ぺた、ぺた、ぺた、ぺた、ぺた、ぺた………。@
`　Pit, pat, pit, pat, pit, pat....`@
br
;　……なのに、さっきから何か聞こえてくる。@……耳障りでいらいらする。@
`　...He could still hear that sound.`@` ...It was grating his ears.`@
;　何だろう。@何の音だよ。\
`　What is that? `@`What is making that sound?`\
;　足音のようだが、近づいてくるわけでも、遠ざかるわけでもない。@
`　It was like footsteps, but they were neither approaching nor growing more distant.`@
;　まるで同じところでずっと足踏みをしているように聞こえた。@
`　It was almost like someone was pacing around the same place over and over again.`@
br
;　音の正体を確かめようと、意識を目覚めさせた時、……すぐに違和感の数々を覚えた。\
`　When he came to his senses and opened his eyes to try and ascertain the cause of the sound... something immediately felt very wrong.`\
bg black,22
mono 0
bg hoken_04,6

me2v 16,50

;「な、何だよこれ……。@身体が、動かな、い……。」@
`"Wh-what the... `@`I can't, move, my body..."`@
br
;　瞼だけは開くのに、……体はまるで金縛りのように、ぴくりとも動かない。\
`　Even though he could open his eyes, it was as though his whole body had been bound by chains, and couldn't move an inch.`\
;　そしてそれだけじゃない。@……天井が違う。\
`　And that wasn't all.`@` ...The ceiling was different.`\
;　どこ、ここ。@……自分の部屋の、……ベッドの上じゃ、……ない……。@
`　Where is this place?`@`... This... isn't my room... or my bed....`@
;　それを言えば、布団が硬過ぎる。@自分が毎日、就寝しているベッドじゃない。@
`　Now that he thought about it, his futon was too hard. `@`It wasn't the same bed that he crawled into every night.`@
br
;　こ、ここはどこ……。@一体……。\
`　W-Where is this... `@`What the...`\
ld c,HIG_D9,2

E_M2

;「…………目が覚めた……？」@
`"......Are you awake...?"`@
br
;　声とともに、誰かが少年の視界に入って来た。@
`　With that voice, someone entered the boy's field of vision.`@
;　ベッドに横たわる少年を、見下ろすような形で覗き込む……。\
`　A figure, peering down on him as he lied on the bed...`\
;　それは長い黒髪の美しい、可憐な少女に見えた。@
`　It looked like a pretty girl, with beautifully long, black hair.`@
br
;　ぞっとするほどの白い肌と、それとは対照的な漆黒の髪。@赤い唇は蠱惑的に輝き、見惚れてしまうほどに美しかった。\
`　Her chillingly white skin contrasted with her jet black hair. `@`Her red lips shone alluringly. She was so beautiful it was captivating.`\
bg black,22
bg hoken_01,22

;「……だ、………誰………。@……こ、……ここ……は………。」\
`"....Wh...Who.....? `@`...Wh... where am....?"`\
ld r,HIG_d8,22

;「私の巣よ。」@
`"This is my nest."`@
;「………巣、って………。」\
`"....Nest....?"`\
ld r,HIG_w1,80

;「あなた、保健室に来たことはないのかしら。@……そうよね。@人を怪我させるのは得意でも、自分が怪我をするのは得意ってわけじゃないものね。」@
`"I wonder if you've never been to the infirmary before.`@` ...Ah, that's right. `@`I guess just because you hurt others doesn't mean you get hurt yourself."`@
br
;　ようやく、埃と薬品の臭いの入り混じったものが鼻を突くことに気付く。\
`　Little by little he could begin to smell the stench of dust and medicinal chemicals as they stabbed at his nostrils.`\

;　……どういうこと？@
`　....What was the meaning of this?`@
br
;　信じられない。@ここは多分、………学校の、保健室のベッドの上なのだ。\
`　Unbelievable. `@`This was probably.... the bed in the school infirmary.`\
;　そんな馬鹿な。@自分は家に帰って、……夕飯を食べてお風呂に入って、……自分のベッドで眠ったはず。@
`　That makes no sense. `@`He was sure that he had gone home... eaten dinner, taken a bath... and crawled into his own bed.`@
br
;　なのにどうして、……こんなところにいるんだ………。\
`　So then... why was he here....?`\
bg black,22

me2v 16,50

bg hoken_02,22

;　廊下からちらりと見たことしかないけれど、……ここは紛れもなく保健室だ。@
`　He could only catch a glimpse of the hallway outside the door... but this was unmistakably the infirmary.`@
br
;　窓が開いているのだろうか。@……白いカーテンがゆっくりと大きく、……まるでハロウィンの幽霊のように大きくはためいている。\
`　Were the windows open?`@`... The white curtains were slowly fluttering... like a Halloween ghost.`\
;　風は感じられるが、生ぬるく澱んでいて、……その上、ねっとりとして感じられた。@
`　He could feel a breeze, but it was warm and stagnant.... But even worse, it felt wet and sticky.`@
br
;　……これは確かに現実のはずなのに、@……誰かの悪夢の中に引き摺り込まれたかのようにも感じられる……。\
`　...He was sure that this was reality,`@` ...but he felt as if he had been dragged into someone's nightmare...`\
bg black,22
bg hoken_01,22
ld c,HIG_d9,22

;「そうよ。@私があなたを招待したのよ。@……この踊る彼岸花が、あなたと踊りたくて、私の巣へ、ね……。」@
`"That's right. `@`I invited you.`@` ...The Dancing Higanbana has invited you to her nest because she wants to dance with you..."`@
br
;　保健室の不気味な西洋人形が、夜な夜な踊り出すという怪談を、確かにどこかで聞いたことがある。\
`　Yes, he was pretty sure he had heard a rumor about an odd western doll in the infirmary who dances every night.`\

;　でも、それがどうして自分を祟る？@
`　But, why was she cursing him?`@
br
;　保健室に入ったことさえ、一度もないのに…！\
`　He had never once set foot inside the infirmary...!`\
ld c,HIG_D2,80

;「……それは、あなたが敬いを忘れたからよ。」@
`"....Because you have forgotten to be respectful."`@
;「う、……敬いって、………な、……何の………。」\
`"R-... respectful..... of... What....?"`\
bg black,22
bg Air_03,22
;bg gakkou_08y,22

;「夜の闇への敬いを、よ。@……あなたは陽の下で生きることを定められた身でありながら。@……邪悪なる夜の闇にまで足を踏み入れた。@……人の世の法律はあなたを許すかもしれない。@……でもね。@……夜を司る私は許さない。」\
`"Respectful for the dark of night.`@` ...You are a being that should live in the light,`@` ...and yet you set foot into the wickedness of night.`@` ...The law of the human world may let you off easy.`@` ...But.`@` ...As a ruler of the night, I won't forgive you so easily."`\
bg black,22
bg hoken_01,0
ld c,HIG_D2,2

;　薄暗い明りに、次第に少年の目が慣れてくる。@
`　The boy's eyes had gradually gotten used to the dim light.`@
me3v 28,50

br
;　すると、少女の髪が、美しいだけでなく、………恐ろしいほどの長さを持つことがわかるようになる。\
`　But when they did, he realized that the girl's hair wasn't just beautiful.... it was horrifyingly long.`\
;　彼女の髪は、足元までどころか、四方八方に束ねられながら伸び、@部屋中にまるで蜘蛛の巣のように張り巡らされているのだ。\
`　Her hair reached down to her feet, and then grew off in all directions. `@`It was strung around the room like a spider web.`\
bg black,22
bg hoken_02,22

;　その髪がどこまで伸びているのか、目が追ってしまう……。@
`　His eyes followed where her hair led....`@
;　すると、……それは、少年の隣のベッドに向かっていた。@
`　And... traced it to the neighboring bed.`@
br
;　しかし、ベッドの境はカーテンで仕切られている。@向こう側で何が起こっているのか、わからない。\
`　However, there was a curtain between the two beds. `@`so he had no idea what was going on behind it.`\
mbg black,22
bgm1 10

;　ぺた、ぺた、ぺた、ぺた………。@
`　Pit, pat, pit, pat....`@
;　ぺた、ぺた、ぺた、ぺた、ぺた、ぺた………。@
`　Pit, pat, pit, pat, pit, pat, pit, pat....`@
br
;　さっきからずっと聞こえる、その奇妙な音に、……カーテンを潜り、髪の束が続いている……。\
`　The strange sound that he had been hearing all this time... was coming from just beyond that curtain that the hair draped over...`\
mcbg 22
ld c,HIG_w1,22

;「気になる？@　この音が。@…………いいわ、教えてあげる。」@
`"Are you curious? `@`Wondering what this sound is?`@`... Fine, then. I'll show you."`@
br
;　金縛りで身動き出来ぬ少年の顔を、彼岸花はぐいっとねじり、奇妙な音が聞こえる方へ向ける。@
`　Higanbana twisted the boy's paralyzed face towards where the sound was coming from.`@
;　そして、カーテンを一気に開き、……その光景を、見せつけた。\
`　Then she drew back the curtain... and showed him the scene unfolding behind it.`\
bg white,24

bgmvol 0

wait 1000

se1v 33,100
;bg aka1,22
bg e017,1

wait 1000

fedexx 70,50,50,50,0,0,2000

;「……………………ッッ？！？！」\
`"............?!?!"`\
me4v 17,70

;　ぺた、ぺた、ぺた、ぺた………。@
`　Pit, pat, pit, pat....`@
;　ぺた、ぺた、ぺた、ぺた、ぺた、ぺた………。@
`　Pit, pat, pit, pat, pit, pat.....`@
br
;　そこにいたのは、……彼の友人たちだった。@
`　There... were his friends.`@
;　そう。@秋一を執拗にいじめ続けた、いじめっこ三人組だ。\
`　Yes. `@`The boys who had relentlessly bullied Shuuichi.`\
bg aka2,22

;　だが、それは余りにも異様な姿だった。@
`　But their bodies were far too bizarre.`@
br
;　彼らの四肢には彼岸花の髪束が絡み付き、ベッドの上に吊るされるような形で立たされていた。@まるで操り人形のように。\
`　They were hanging above the bed, their limbs strung up by her bundles of hair. `@`They looked like puppets.`\
;　両手両足首、そして首をぎりりと締め付けるそれに操られて、……ぺたぺたと、……踊り続けることを強要されているのだ。@
`　Their wrists, ankles and necks were tightly bound... pit, pat, pit, pat... and they were being forced to dance.`@
br
;　彼らは、虚ろな目で口からは泡を吹き、生きた操り人形に成り果てていた……。\
`　They had soulless eyes, and were foaming at the mouths, having been reduced to living puppets...`\
bg black,22

;　あの、ぺた、ぺた、という奇妙な音の正体は、……もう、考えるまでもない。@
`　The source of the odd tapping sound... was now clear.`@
br
;　彼らが永遠に強要される、ダンスの足音だったのだ……。\
`　It was the sound of them being forced to dance endlessly...`\

bg hoken_01,0
ld c,HIG_w2,22
ld c,HIG_D3,80

;「さぁ、あなたも一緒に踊るといいわ。@……ダンスの経験がなくても大丈夫よ。@私が教えてあげるのだから。@……くすくすくすくすくすくす。」\
`"Go ahead, why don't you dance with them.`@` ...Don't worry if you've never danced before. `@`I'll teach you how.`@` ...Teeheehee."`\
se3v 84,100
se1v 66,100
bg white,8
se2v 34,100
bg aka3,22
quake 8,800

;「ひ、……ひいッ、……うわぁああぁ！！」@
`"H... hee... UWaAAAaa!!"`@
br
;　不気味に蠢く何本もの髪束が少年に巻き付き、彼を操り人形にして吊るす。\
`　Countless wriggling strands of hair wound around the boy, and strung him up like a puppet.`\
quake 8,800

;「や、やめてぇえぇ、ひぃいいいい！！！@　こんなこと、あるわけない！@　これは夢だッ、悪い夢なんだぁあぁあぁ！！」\
`"S-Stop it, AhHHHHH!!! `@`This isn't real! `@`This is a dream -- a nightmare!!"`\
ld c,HIG_w3,22

;「そうね。@普通の人間にとって、私たちとの出会いなんて、夢の中だけ。@さもなくば、闇の中だけだわ。@/
`"Exactly. `@`For a normal human to meet one of us, you'd have to be dreaming. `@`Or otherwise, within the darkness.`@/
ld c,HIG_w4,80

;……でも。@………踏み込んできたのはあなたたちの方なのよ…？@　夜の闇を敬いもせず、土足で踏み込んできたあなたたちのせい……。」\
` ...But,`@` ...you were the ones who stepped into our territory, right...? `@`You placed your dirty feet into the darkness of night, without even a hint of respect..."`\
bg black,22
;bg k_rouka_03,2

;　夜の闇は、さらに深い暗黒でなければならない。@
`　The darkness of the night had to be even darker.`@
;　そうでなければ、容易く人間たちは踏み込もうとしてしまう。@
`　If not, humans would too easily walk right into it.`@
br
;　ますますに闇を暗く染め、恐れられるようにするのが、妖怪の役目……。\
`　It's the youkai's duty to scare humans away by dying the darkness an even darker black.`\
;　如何なる常識も法律も届かない、学校という名の切り取られた異常世界。@
`　Common sense and laws did not reach as far as this abnormal world known as school.`@
br
;　その世界に唯一存在でき、彼らを裁くことが出来る法こそが、妖怪なのだ。\
`　The only ones able to judge them in this world, were the youkai.`\
;bg black,22
bg hoken_01,22

;　ぺた、ぺた、ぺた、ぺた………。@
`　Pit, pat, pit, pat....`@
br
;　ぺた、ぺた、ぺた、ぺた、ぺた、ぺた………。\
`　Pit, pat, pit, pat, pit, pat.....`\
ld c,HIG_w6,22

;「……くすくす、………うふふふふふふふふふふふふふふふふ。@あなたたちの拙いダンス。@見ていると不思議なの。@なぜか溢れてくる笑いを抑えることが出来なくなる。@……くすくす、くすくすくすくすくすくすくす…！！」\
`"...Teehee..... Ahahahahahahahaha. `@`You guys are so bad at dancing. `@`It's strange. When I watch you, `@`I just can't stop laughing.`@` ...Teehee, heeheeheeheehee!!"`\
se1v 84,100

bg black,22
mono 2
bg Air_03,22

;　窓の外には、人の世に昇ることは決してない、真っ赤な満月が浮かんでいる。@
`　Outside the window, there was a bright red moon floating in the sky, the likes of which would never be seen in the world of humans.`@
br
;　それを見上げ、彼岸花は心の底より笑った。\
`　Higanbana turned her eyes upwards toward that moon, and laughed from the bottom of her heart.`\
;ld c,HIG_w4,80

;　あぁ、わかったわ、秋一。@
`　Ah, I get it, Shuuichi.`@
;　これが感情というものなのね。@生きている証ということなのね。@
`　These are what you call emotions. `@`This is what you call proof of living.`@
br
;　あなたのお陰で、私はやっと、生きることが出来たわ。\
`　Thanks to you, I can finally live.`\
bg black,22
mono 0

bg hoken_01,22
ld c,HIG_w6,22

;「私は、踊る彼岸花。@学校の妖怪として、……学校の闇夜を、ますますに暗く染めてやるの。@……お前たち人間が闇を恐れるように。@闇に足を踏み入れることがないようにっ。@さぁ、踊りましょうよ、三人とも。@この踊る彼岸花と一緒にね。@……踊るのに疲れたら、目の前の友人に、自分の喉を噛み千切ってくれるよう頼むといい。@そして、それを頼むなら早い内がいいわね。@何しろ、最後のひとりは誰も殺してくれない。@永遠に私と踊り続けなくてはならないのだから。@………くすくすくす、うっふふふふふふふふふふふふ、/
`"I am the Dancing Higanbana. `@`As a youkai of the school... I will dye the night an even darker shade of black.`@` ...So that humans will fear the dark. `@`So that they'll never set foot within it. `@`Now, you three. `@`Dance along with the Dancing Higanbana.`@` ...When you tire of dancing, ask your friends to bite off your throat. `@`If you're going to tire, do it quickly. `@`The last one of you won't be killed. `@`Instead you will get to dance together with me forever.`@` ....Teeheehee, ufufufufufufufu,`/
se1v 84,100

;はっはははははははははははははは……。」\
` hahahahahahahahahahhaaaahaaaaa...."`\
;bg black,2
bg gakkou_01o,2

fedexx 70,90,90,90,90,90,2000

;　血のように真っ赤な月が照らす、人ならざる夜の保健室で。@
`　There in the infirmary, bathed in the moon's mystical blood red light.`@
br
;　踊る彼岸花と初めての犠牲者たちが、いつまでもいつまでも、明けない夜を踊り続けるのだった………。\
`　Will forever dance the first victims of the Dancing Higanbana.....`\
bg black,2

fede 0,3000
E_A
wait 1000

bg gakkou_03,0
;ld r,NON_D1,0
;ld l,SH2_D1,22


ld r,NON_D4a,22
bgm1 17

;「そんなことがあったんですか……。」\
`"Ah, so that's what happened...?"`\
;＜野々宮

ld l,SH2_D2,22

;「一時は死のうとさえ考えたよ。@何しろ、僕には文字通り、世界が真っ暗だったわけだからね。@しかし、気付いたんだ。@……感情は、目で見るものじゃない。@心で感じるものなんだ、ってね。@目が見えなくたって、感情を受け止めることは出来る。@こうして僕にはまだ、耳があるんだからね。」\
`"For a while I thought about dying. `@`After all, the world had become pitch black to me. `@`But then I realized.`@` ...You don't need eyes to experience emotions. `@`You feel them with your heart. `@`Even if you can't see, you can still have emotions. `@`And I still have my ears."`\
;＜大人秋一

ld r,NON_D2,80

;「それで、……ピアニストに？」\
`"So... that's why you became a pianist?"`\
bg black,22

;　有森秋一は退院後、盲学校に通いながら、音楽を学び始めた。@
`　After being discharged from the hospital, Shuuichi Arimori went to a school for the blind, where he started to study music.`@
br
;　感情を彩り豊かに感じる、彼の稀な感受性は、目が失われても、失われることはなかったのだ。\
`　He learned that his rare ability to feel emotions in a colorful way was not limited only to his eyes.`\
bg Air_02,22

;「僕は感情を、今度は音楽で描くことにしたんだ。@……世界は灰色なんかじゃない。@喜怒哀楽、様々な感情に満ちている。@それを通すことで、同じものでも無限の輝きを見せてくれるんだ。@……それを僕は知ってる。@みんなに伝えたい。@確かに失明は、僕にとって辛い出来事ではあったけれど。@……神様が僕に与えてくれた、使命を全うする上では、何の障害にもならなかったと、今は思っているよ。」\
`"Now I draw my emotions with music.`@` ...The world isn't gray. `@`It's full of a whole wide range of emotions. `@`Even if you feel the same emotion twice, there's an endless amount of brilliance you can gather from them.`@` ...I know that. `@`And I want to tell it to everyone. `@`It was hard for me at first, after losing my eyesight.`@` ...But nothing will get in my way of carrying out my mission given to me by God, that's what I think."`\
bg black,22

fede 0,1000
E_A
wait 1000

;mld c,SH2_D1,22
bgmonce"bgm0\d_25.ogg"
bgmvol 60

;　有森秋一。@
`　Shuuichi Arimori.`@
br
;　全盲のピアニスト。@
`　The blind pianist.`@
;　彼のピアノは、同じ楽譜からでも万華鏡の如き千変万化の音楽世界を奏で出すという。@
`　With his piano, even when playing the same song twice, his music would always portray an endlessly changing variety of sounds, like a kaleidoscope.`@
br
;　その彼が、卒業生として招かれ、体育館で生徒たちに講演を行なったのだ。\
`　As a graduate of the school he was invited to give a speech to the students in the gymnasium.`\
bg gakkou_03,0
mld c,SH2_D2,22

;「僕が伝えたかったのはね、目や耳の話じゃない。@感情の話なんだよ。@本来、世界は灰色なんだ。@ところが、僕たちの心が感情という絵の具を得て、世界を美しく着色してくれているんだよ。@………どのようなものであれ、感情は楽しむべきなんだ。@そしてそれこそが、生きていることの証なんだと、僕は思ってる。@……それが、子供たちに伝わってるといいんだけど。」\
`"My story is not one of eyes or ears. `@`It is a story of feelings. `@`The world itself is gray. `@`It's the emotions in our hearts that gives the world its beautiful colors.`@` .....Whatever the feeling, you should enjoy them. `@`And that is proof that you're alive, that's what I think.`@` ...And that's what I want to be made clear to you kids."`\
ld l,NON_D2,23

;「伝わりましたよ。@僕は、とても大切な話を聞けたと思っています。」@
`"You have. `@`I think that your story is a very important one to tell."`@
mcl c,0
ld c,SH2_D1,80

;「そうかい？@　なら、ありがとう。@……ところで、そろそろ時間かな？」\
`"Is that so? `@`Well, thank you then.`@` ...By the way, isn't it about time we go?"`\
ld l,NON_D6,80

;「あ、……はい。@じゃあ、職員室にご案内しますね。」\
`"Ah... yeah. `@`Okay, I'll show you to the staff room."`\


bg black,26
bg gakkou_02,2

;　木陰に座っていた秋一は、砂埃を払いながら、ゆっくりと立ち上がる。@
`　Having been sitting under the shade of the tree, Shuuichi slowly stood up, brushing the dust off of himself.`@
;　そして、ふと足を止め、校舎を見上げた。\
`　Then he paused, and rose his head up towards the top of the school building.`\
;「…………………………………。」\
`".................."`\
;＜修一

mov %hig_isyou,1
bg black,22
bg okujou_02,0
ld c,HIG_w1,22

;「………………。」@
`"..........."`@
;＜彼岸花
br
;　見えるはずのない目で、屋上の柵に腰掛けた彼岸花を見上げる。\
`　With eyes he should not be able to see out of, he looked up at Higanbana sitting on the railing on the rooftop.`\
bg black,22
ld_p SH2_D2
lsp2 2,$ld_pass,500,480,-200,200,0
lsp2 3,$ld_pass2,500,480,-200,200,0
print 22
;　……久し振りだね。@
`　...It's been a long time.`@
br
;　どうだい。@今の君は、感情を楽しんでいるかい？\
`　How did things go? `@`Are you enjoying having emotions?`\
ld_p HIG_w3
lsp2 4,$ld_pass,180,480,200,200,0
lsp2 5,$ld_pass2,180,480,200,200,0
print 22


;　お陰様で。@毎日、面白おかしいことばかりで退屈しないわ。\
`　Yes, all thanks to you. `@`I see so many fun and interesting things, that I'm never bored.`\
csp2 -1
print 0
bg black,22
bg okujou_02,0
ld c,HIG_w3,22

;　秋一は手を引かれながら、去っていく。@
`　Shuuichi, drew his outstretched hand back, and left.`@
br
;　彼岸花はその後姿を見送る。\
`　Higanbana watched his as he walked away.`\
ld c,HIG_d2,80

;「夜の闇をもっと深く。@だからこそ、陽の明るさが、より美しくなるのだから。」@
`"When the darkness of night is darker. `@`The light of the sun becomes brighter, and is that much more beautiful."`@
cl c,2

br
;　彼岸花はふわりと姿を消すのだった。\
`　Higanbana gently faded away.`\

bg black,22

;＜おしまい＞


mov %Free1,65 ;BGMの初期値+アルファ
	for %Free1 = 65 to 100 ;BGMボリュームを65から100までフェード。
		bgmvol %Free1 ;その瞬間のBGMボリューム
		add %Free1,5 ;フェードボリュームの増加速度（増加値）
		wait 500 ;フェードのスピード。
	next


  mov %Free1,1                   ;スクロールの現在値
   mov %Free2,1                   ;スクロールの増加値

   btndef ":c;bmp\background\efe\end_c.bmp"                   ;スクロール画像を読みこむ


gosub *higan2c_scroll                   ;スクロール実行本体

resettimer
waittimer 8000

prnumclear                                  ;数値ラベル設定クリア

bgcopy

csp 500
csp 510



bg black,42
bgcopy ;背景をリセット
mov %Free1,100 ;BGMの初期値+アルファ
	for %Free2 = 1 to 25 ;BGMボリュームを65から100までフェード。
		bgmvol %Free1 ;その瞬間のBGMボリューム
		sub %Free1,4 ;フェードボリュームの増加速度（増加値）
		wait 200 ;フェードのスピード。
		inc %Free2
	next
E_A

if %UMINEKOEND >= 11 : jumpf ;新規告知の表示を１回のみ行なうための処理
	se1 22
	bg "bmp\background\efe\TEXT006.bmp",22

	delay 10000
	bg black,22
	bgcopy ;背景をリセット
	fede 0,1000
	E_A
~ ;もしクリア後なら、この~まで処理を飛ばす

if %UMINEKOEND < 7 mov %UMINEKOEND,11 : mov %END_FLG,12 : mov %END_TEA_FLG,1 ;クリアフラグの変更
wait 5000



goto *b_title
;reset


*higan_extra_opning

texton
csp -1

bg black,2
bgcopy ;背景をリセット

setwindow 31,16,22,16,26,26,0,2,20,1,1,#999999,0,0,639,479

!sd

mono 0
E_A

;■冬休みのデイドリーム

me1v 16,50

wait 2000
bg Different_spiral_1b,22
wait 2000
bg Different_spiral_1a,2
bgm1 5

wait 2000

ld r,KYO_D2,2
