;Chapter 2
;「はあッ、はぁッ、はぁッ、はあッ！！」\
`"Haa, haa, haa, hAAA!!"`\

bgm1 12

bg rouka_02,22
wait 1000
bg rouka_03,22
wait 1000
bg kaidan_01,22
wait 1000
bg kaidan_02,22
wait 1000
bg black,25
bg rouka_01,25

se1v 13,50
quakey 2,200

;　心臓を吐き出しそうなほどに、少女は呼吸を荒げている。@
`　The girl was breathing so hard it seemed she was going to vomit her heart out her throat.`@
;　そして、廊下の途中で床にへたり込んだ。\
`　And then she sunk to the floor midway through the hall.`\

;　全身は汗でびっしょり。@足はこわばり、痙攣していた。@
`　Her entire body was drenched in sweat. `@`Her legs stiffened, cramped.`@
br
;　無理もない。@少女は校舎の中を、１時間も走り回っていたのだから。\
`　This was only natural. `@`After all, she had been running around the inside of the school for a full hour.`\

bg black,23
bg rouka_03,23

;　教室の時計はもうじき、０時を指そうとしている。@
`　The classroom clock seemed about ready to strike twelve o'clock.`@
;　しかし、窓の外は夕闇。@
`　However, outside the window it was twilight.`@
br
;　昼の０時のわけも、夜の０時のわけもない。\
`　It wasn't twelve o'clock in the day, nor twelve o'clock at night.`\


;　そして不思議なことに、……学校の中には少女の他に、誰の気配も感じられなかった。@
`　And mysteriously... aside from the girl, no one else appears to be in this school.`@
br
;　夕闇の、誰の人影もない校舎の中でずっと、……少女は１時間も走り回っていたのだ。\
`　The girl had been running for more than an hour... in this twilight, without a soul to be seen on campus, for ages."`\

;　少女の心臓は今にも爆発しそう。@
`　Even now her heart was exploding.`@
;　もう、走るどころか、立ち上がる気力さえなかった。\
`　She no longer had a place to run to, nor the energy to stand.`\

bg black,22

me3v 17,70

;「はぁッ、はぁッ。@……もう、嫌……。@もう、……走れない………ッ。@はぁッ、はあッ！@　はぁッ、はあッ、はあッ！！！」@
`"Haaa, haaa. `@`...No, I can't... `@`I can't... run anymore...... `@`Haaa, haAA! `@`Haa, haaa, hAAA!!!"`@
br
;　少女は怯えた表情で、床に這いつくばったまま、……ゆっくりと後ろに振り返る。\
`　As the girl crawled on the floor with a frightened expression, ...she slowly looked behind her.`\

;bg black,23
se1v 14,100
se2v 14,100
bg rouka_01,3

;　彼女の荒々しい息の他に、もう一つ、聞こえるものがあった。@
`　Something else could be heard aside from her harsh breathing.`@
br
;　それは、足音。@
`　And that was footsteps.`@`
;　踵でごつごつと踏み鳴らす荒々しい足音が、足早に近付いてくるのだ。\
`　The sound of heels, rough footsteps, trodding across the floor, were closing fast.`\

;「……嫌……、嫌…………。」@
`"...No... No......"`@
br
;　少女は四つん這いになっても、尚もその足音から逃れようとする。@
`　Even though the girl had collapsed on all fours, she tried to get away from the sound of those footsteps.`@ 
;　しかしもう、両脚は痙攣してしまい、立ち上がることすら叶わない。\
`　But she had already lost both her legs to cramping, and she couldn't hope to even stand up.`\

;　足音は容赦なく近付いてくる。@無慈悲にずかずかと近付いてくる。\
`　Relentlessly, those footsteps drew closer. `@`Mercilessly, they drew closer.`\


;「何でよ……。@何で私を祟るのよ……。@……もうお願いよ…、私を……、放っておいてよぉおおおぉおお！！」\
`"Why... `@`Why curse me... `@`...Please... Please... LEAVE ME ALOOOooOOoOOONE!!"`\


;　ずかずか。@
`　Thump thump.`@
;　ずかずかずかずか！！@
`　Thump thump thump thump!!`@
br
;　その漆黒のマントの人影は、足早に近付き、……とうとう少女に追い付く。@
`　That silhouette with a jet black cloak drew nearer at a fast pace... finally, he reaches her.`@  
;　そしてマントを大きく広げ、……その影で少女を覆った。\
`　And so he spreads his cloak wide... and covers the girl in that shadow.`\

se1 20
bg black,28


;「嫌……ッ。@……嫌ぁあああああぁああああぁああああッ！！！」\
`"No...! `@`...NOOOOOooooOOOOOOOOOOOooOOOOO!!!"`\

E_A

se2v 36,100
se3v 27,100

nega 1
bg BLADE2W,1

quakex 3,700





;　断末魔を叫ぶ少女の瞳には、……無慈悲な大鎌の冷酷な閃きが映っていた……。\
`　The horrific flash of a merciless scythe casts its reflection in the eyes of the girl... screaming in the throes of death...`\ 

textoff
nega off
bg black,2
wait 3000

se1 69
bg kyou_01,22

me1v 24,50

;「はいっ、じゃあ、ここまでー！@　日直、号令ー！」@
`"Okay, that's enough for today! `@`Time to go!"`@
br
;　授業の終わりを告げるチャイムが鳴り響き、先生は時計を見上げる。@
`　The teacher looked up to the clock as the bell signifying the end of class rang.`@
;　日直が、きりーつ、と号令をかける。\
`　Leaving class required following a daily routine that started with standing at attention.`\

ld c,AYA_D3,6

;　クラス全体が、がたがたと立ち上がる中、……私は少し遅れでのっそりと立ち上がる。@
`　While everyone else in class clammored to stand up... I lagged behind and sluggishly rose from my seat.`@ 
br
;　気付けば、黒板は文字でいっぱいだ。@
`　I noticed the chalk board was covered in writing.`@
;　ノートに写してなんかいない。@私はずっと俯いて、うとうとしていたのだから。\
`　My notes reflected none of it. `@`After all, I had spent the whole time dozing off with my head down.`\

;　そしてそれは、この教科だけに限らない。@
`　And my drowsiness wasn't limited to just this subject.`@
;　国語も算数も、理科も社会も、何もかも。@私のノートは真っ白だった。@
`　Language, math, science, social studies, etc, etc. `@`My class notes were completely blank.`@
br
;　当然だ。@私は学校でほとんどの時間を、寝て過ごすか、@ぼんやりしながら、人生についてを自問自答しているだけなのだから。\
`　It's not unusual. `@`I spend almost all my time at school sleeping through classes, `@`or I just daydream to myself pondering life's questions.`\

ld c,AYA_D1,80

bgm1 8

;　私の名は、相馬あや（そうま　あや）。@
`　My name is Aya Souma. (相馬あや)`@
br
;　名前なんて、どうでもいい。@
`　Names and stuff don't really matter.`@
;　死ねばただの骸。@そんなものに名前なんて意味がない。\
`　After I'm dead, I'm just a corpse. `@`Ascribing names to such things is meaningless.`\

ld c,AYA_D2,80

;　そもそも、生きてたって、名前になんか意味はない。@
`　So, after we've lived our lives, names are somewhat meaningless in the first place.`@
br
;　その証拠に。@私の名前が、あやだって、あやこだって、それは私に何の影響も与えない。\
`　Evidence for such. `@`My name, whether Aya or Ayako, has no real influence on me.`\

bg black,24
bg kyou_02,24

;　クラスの反対側に座ってぼんやりしているあの男子。@私は名前さえ知らないけれど、私の人生に何の影響も問題もない。@
`　That daydreaming boy sitting on the opposite side of the classroom. `@`Even though he doesn't even know my name, he has no particular influence over me and doesn't complicate my life.`@
br
;　同じように。@私の名前だって存在だって、彼の人生には何の影響も与えないのだ。\
`　In the same way. `@`My name, my existence, doesn't have any particular influence on his life either.`\


;　それは突き詰めれば。@
`　If we follow this logic.`@
;　このクラスの全員が、等しく誰の人生にも、何の影響も与えないのだ。@
`　Everyone in this class, equally in whoever's lives, doesn't particularly influence anyone.`@
br
;　誰が居ても居なくても。@どのような名前であろうともなかろうとも。@何の意味も為さない。\
`　Who lives or doesn't live. `@`Whatever name they have or don't have. `@`None of it has any real meaning.`\

bg black,22

fede 10,1000
E_MA

;　人間は、誰も彼も、何の存在価値もないのだ。@
`　Human beings, one and all, have no real value in living.`@
br
;　そして私たちは学校で、何の価値もないことを延々と教えられている。\
`　And so in school we're endlessly taught things of no real value either.`\

;　何を訴えたいのかわからない話の感想文を強要されたり。@
`　We're coerced into doing things like writing our thoughts on subjects we don't understand.`@
;　電卓が溢れたこの世界で、延々と計算問題を解かされたり。@
`　Or we're made to solve calculations in a world overflowing with calculators.`@
;　リトマス試験紙や石綿金網が、私たちの人生に何の影響を与えるのだろう？@
`　Just how do litmus tests and asbestos wire mesh influence our lives, I wonder?`@
br
;　……何て皮肉で馬鹿馬鹿しい話だろう。\
`　...What a cynical and foolish set of ideas, you must think.`\

bg kyou_03,22

;　いや、むしろお似合いか。@
`　No, rather, isn't it suitable?`@
br
;　何の意味も価値もない私たち。@何の意味も価値もないことを学ばされ、何の意味も価値もない人生を送ってる。\
`　For us, who have no real meaning or value. `@`Who are made to learn things of no real meaning or value, we're going through lives of no real meaning or value.`\

;　私にとって、世界も自分も全て無意味で無価値。@
`　Everything, the world, myself, all of it was meaningless and worthless to me.`@
br
;　だから。@
`　So.`@
;　どうして自分が生きているのか。@生きていなくてはならないのかも、理由がわからなかった。\
`　Why am I still alive? `@`I can't understand why I can't stop living either.`\

;　……どうして私は、この世に生まれてきたのだろう？@
`　...Why was I born into this world, I wonder?`@
;　先生も親も、人生には意味があって、生きていくことには明白な目標があるという。@
`　Teachers, parents, they say life has meaning, and that it becomes obvious what it is as you continue to live.`@
br
;　でも、それは何かと訪ねると、@小難しいことをぐちぐちと口にして煙に巻き、はぐらかしてしまう。\
`　But if I actually look into what they mean, `@`they'll mumble something ambiguous and give me the slip.`\

bg black,22

;　……ないのだ。@生きていることに、意味なんて。@
`　...There just isn't one. `@`There just isn't a reason for living.`@
;　なのに、生きている。@
`　Nevertheless, I'm still alive.`@
;　ただ惰性で、何となく生きているのだ。@
`　Just out of habit I continue to live somehow.`@
br
;　私には、それが堪えられなかった。\
`　I just couldn't stand it anymore.`\

;bg Different_spiral_1a,22
bg k_kyou_02,22

;　私がこの世に生を受けているなら、その意味を教えて欲しい。@
`　If I'm to continue living in this world, I want someone to tell me that reason.`@
br
;　こう生きて、このように意味を為すという、価値ある人生を与えて欲しい。\
`　Living like this, trying to find a reason, I want to be given a life that has value.`\

;　しかし、そんなものは存在しない。@
`　But something like that doesn't exist.`@
br
;　私はただ毎日、ぼんやりと学校に通うことを強要され、@学んでも学ばなくても、何の役にも立たない勉強を強いられている。@
`　I'm just forced to sluggishly commute to school every day, `@`and whether I learn or not, I'm forced into study that has no real use.`@
;　そんな無意味な日々に、私はもうとっくに堪えかねている。\
`　I stopped being able to bear these aimless days long ago.`\

bg black,22

;　……死にたいのか、と聞かれれば、イエスとは言わない。@
`　...Do you want to die? `@`If someone asked me that, I wouldn't answer yes.`@
;　死ぬことに意味があるなら、私はすぐにだって死ぬだろう。@
`　If there was a purpose in death, then of course I'd want to die as soon as possible.`@
br
;　でも、飛び降りたって、首をくくったって、きっとそれはとても苦しいことだ。\
`　But jumping and falling or hanging by the neck, those would undoubtedly be really painful.`\

;　わざわざ自らの手で、苦しいことをしなくちゃならないなんて、それこそ意味がない。@
`　The idea of having to cause harm to oneself with one's own hands, that's also meaningless.`@
br
;　……なら、ある日、突然、朝が来ないなんてことにならないだろうか。\
`　...One day, all of a sudden, what if the morning didn't come?`\

bg e002,22

;　朝にならないから、私は目覚めない。@
`　If morning didn't come, I wouldn't wake up.`@
br
;　ずっと寝たまま、永遠に。@
`　I'd stay asleep, forever.`@
;　そしてそのまま、雪が解けて消えるように、@……まるで初めから存在しなかったかのように、消えてしまいたい。\
`　And like that, just as snow melts, `@`...just as I had never existed in the first place, I'd want to disappear entirely.`\

;　だからそれは、自殺願望とは異なる。@
`　That's different than wanting to kill myself.`@
;　無意味な自分に相応しい、自分という存在の無意味化。@
`　I want to go to the meaningless void that so suits my meaningless self.`@
;　消滅願望とでも言えばいいのだろうか。@
`　One could say, perhaps, I want to erase myself.`@
br
;　多分。@私が唯一、夢と呼べるものがあったなら、それだった。\
`　Maybe. `@`If I could say I had one dream, that was it.`\

bg black,22

;　私、相馬あやは。@眠るように解けるように、……消えてしまいたかった。@
`　I, Aya Souma. `@`Wanted to disappear... as if asleep... like melting snow.`@
br
;　しかしそんな、この世ならざる死に方など、あるわけもない。@
`　Unfortunately there wasn't any way to die in this world like that.`@
;　それを望むなら、……この世ならざる何かに頼る他なかった。\
`　If I wanted that, ...then the only thing I could do was rely on something not of this world.`\

fede 0,1000
E_A

bg kyou_01,22
;ld c,AYA_D3,22

me1v 24,50

;　そんな時、クラスメートのおしゃべりが、偶然、私の耳に入る……。\
`　At that time, coincidentally, my classmates' chatter entered my ears...`\



;「１３階段なんて、本当にあるわけ？」@
`"A 13th step you say? Is there really such a thing?"`@
;「うん。@学校八不思議の、すっごい有名なやつだよ。」\
`"Yeah. `@`It's one of the most famous of the Eight School Mysteries."`\

ld r,AYA_D4,22

;　１３階段の怪談なら、私も聞いたことがある。@
`　I've also heard the story of the 13th step.`@
br
;　ぴったり１３段の階段なんて学校には存在しないはずなのに。@唐突に階段が１３段になってしまうらしいという怪異。@
`　Even though the school shouldn't have a 13 steps on a flight of stairs. `@`There's now this strange phenomenom that has just developed about a 13th step.`@
;　そして、それを踏んだ者には、恐ろしいことが起こるとか何とか……。\
`　And they say that horrors await those who stumble upon it, or some such...`\


;「１３階段を踏んじゃったら、どうなんの？」@
`"What happens when you step on the 13th step?"`@
;「死神が命、奪いに来るんだって。@どこまでもどこまでも追っ掛けて来るんだって。」@
`"They say the grim reaper comes to take your life. `@`I've heard it'll follow you wherever you go, no matter how far."`@
;「えー、何それ、やだー、あははうふふっ。」\
`"Huuuh? What is that? No way, ahaha,uhuhu."`\

ld r,AYA_D3,80

;　１３階段を踏んだら、死神が命を奪ってくれる、か。@
`　If you step on the 13th floor, the grim reaper will come for your life, huh?`@
br
;　………階段なら学校で毎日、上り下りをしてる。@
`　...I go up and down stairs every day at school.`@
;　でも、そんなものが現れて、私の命を奪ってくれたことは一度もない。\
`　But I've never experienced such a thing, and my life has yet to be taken from me because of it.`\

ld r,AYA_D2,80

;　…………………………。@
`　.........`@
br
;　死神、か……。@
`　Grim reaper, huh...`@
;　人の命を刈り取る、無慈悲な存在。@
`　Harvesting the lives of mortals, a being without mercy.`@
;　魂を奪い、黄泉へ連れ去ってくれるという、死への案内人。\
`　Snatching souls and ferrying them down to the underworld, the guide to death.`\

bg black,22

fede 0,1000
E_A
bgm1 5

;　………………………。@
`　.........`@
br
;　不思議だ。@本来、不気味に感じるべき存在である死神に、……私は不思議な憧れを抱いていた。\
`　It's strange. `@`Even though I should find the thought of a reaper unpleasant... these days I've strangely embraced a longing for it.`\

;　死神はどのように命を奪ってくれるのだろう。@
`　I wonder how a reaper would kindly take my life away.`@
br
;　ぱちりと、まるで電気のスイッチでも消すように、命を奪ってくれるのだろうか。\
`　I wonder if it would just take my life away like flipping off a light switch.`\

bg kyou_03,0
ld r,AYA_D2,22

;　そうだとしたら、……私にとって、死神の存在は、まさに慈悲だった。@
`　If that were true, ...then the grim reaper was truly a being of mercy.`@
br
;　自分にも世界にも、そして繰り返される毎日にも、何の意味も価値も見出せない私にとって、@ここは居るだけで身を焼かれる乾き切った地獄も同然なのだ。\
`　My life, this world too, and all of these days I'm made to repeat endlessly, they're all meaningless to me. `@`Just 'being' is the same as being burned and flayed in hell to me.`\

cl r,22

;　……ならば私の生の意味は。@
`　...Then my reason for living.`@
br
;　この世界から私を連れ去ってくれる、死神が訪れる日を、ただ待ち続けること。@この一点だけなのではないだろうか。\
`　Waiting for the day the grim reaper comes to take me away from this world. `@`Perhaps that is the only reason I have.`\

;　その日より、私、相馬あやは、@学校で階段を上り下りする度に、その段数を心の中で数えるようになった。\
`　From that day forth, each time I, Aya Souma, went up and down the stairs at school, `@`I started counting the steps in my mind.`\

bg black,22
wait 1000
bg kaidan_01,22

;　１段。@２段。@３段……。\
`　1. `@`2. `@`3 steps...`@\

;　私の教室は２階にある。@だから、毎日必ず上り下りがある。@
`　My classroom is on the second floor. `@`So everyday I had to go up and down those stairs.`@
br
;　しかしその階段は、１２段で踊り場に達し、さらに１２段で２階に至る。\
`　However, the steps end at the 12th step, and beyond the 12th step I'd arrive on the second floor.`\

;　……当然のことながら、@何度上り下りを試しても、１２段で踊り場で、さらに１２段で２階だった。@
`　...Like the most natrual thing in the world, `@`no matter how many times I'd try going up and down the stairs, I'd get off at the 12th step and arrive on the second floor.`@
br
;　その１２段が、……ある日、唐突に１３段になって、……死神が現れてくれないだろうか。\
`　I thought maybe that some day... suddenly a 13th step would appear... and a god of death would come for me.`\

;　６段。@７段。@８段……。\
`　6. `@`7. `@`8 steps...`\

;　そして私に安らかな、眠るような解けるような死を与えて欲しい……。@
`　I want to be given a peaceful death, like melting away in a dream...`@
br
;　………さぁ、今日も数えてみよう。@
`　...So, let's see what happens today.`@
;　あるはずのない、１３段目を求めて。\
`　I sought after the impossible, a 13th step.`\

bg black,22

;　１０段。@１１段。@１２段……。\
`　10. `@`11. `@`12...`\

bg kaidan_01,0
ld c,AYA_D1,22

;「１３段。@/
`"13 steps.`@/
E_A
ld c,AYA_D4,80
;……………………え。」@
`.........Wha."`@

me1v 16,50

br
;　私の右足は、１３段目を踏みしめていた。\
`　My right foot stood firmly on the 13th step.`\

cl c,0
ld r,AYA_D9,23

;　数え間違えた……？@
`　Did I miscount...?`@
br
;　望んでいたはずの１３段目を踏めたのに、私は咄嗟に踏み間違いだと思ってしまう。@
`　Even though I'd arrived on the 13th step I was looking for, I immediately jumped to the conclusion I had miscounted.`@
;　当然だ。@だって、階段は１２段しかないはず。\
`　Of course. `@`I mean, there should only be 12 steps on the stairs.`\

bg black,25
bg kaidan_03,25

;　私は慌てて階段を駆け下り、踊り場に戻る。@
`　I hurriedly ran down the stairs to the floor below. `@`
;　そして指で一段一段、声に出して数える。@
`　Once again, I counted each step with my fingers out loud.`@
br
;　……１０、１１、１２。@……１２段。\
`　...10, 11, 12. `@`...12`\

fede 0,1000
E_A

;　そうだ。@１２段だ。@/
`　Right. `@`Twelve steps.`@/
bgm1 14
;当然だ。@
`Obviously.`@
;　もう一度上り直し、声に出しながら数える。\
`　This time while climbing up once again, I counted the steps aloud.`\

bg black,22
bg kaidan_02,0
ld c,AYA_D7a,22

;「……１１段。@……１２段。@…………１２段で、終わり。@…………………。」@
`"...11. `@`...12. `@`.......At 12, it stops. `@`......"`@
br
;　私の左足は、確かに１２段目を数え、２階へ至っていた。\
`　My left foot had certainly sounded on the 12th step, and I arrived on the 2nd floor.`\

;　…………………………。@
`　.........`@
br
;　私は階段を上る時、無意識だが常に右足から上るのだ。@
`　When I went up the stairs, I unconciously always went up with the right foot.`@
;　だから、偶数である１２段を上れば、それは左足で至ることになる。\
`　And so, coincidentally my left foot would reach the 12th step.`\

ld c,AYA_D4a,80

;　……でもさっき、１３段を数えた時は、私は右足で至った……。@
`　...But just now when I counted out the 13th step, I had reached it with my right foot...`@
br
;　数え間違えただけでなく、……私は何かの気紛れから、左足で階段を上り始めたのだろうか。@
`　It wasn't just a miscount... by chance maybe I had started climbing the stairs with my left foot.`@
;　そんな気紛れが相まって、数え間違いをしてしまったに違いない………。\
`　It must have just been a combination of chance and miscounting...`\

ld c,AYA_D8a,80

;「……………でも、……そんなはずは………。」@
`"...But... that's impossible..."`@
br
;　自信はない。@
`　I'm not sure.`@
;　でも、今、数え直したらやはり１２段。@……それが、冷酷で淡白な、現実だ。\
`　But after I recounted just now, it was 12. `@`...That was the cold hard truth.`@

;　そして何よりも。@
`　Yet more than anything.`@
;　本当に１３段を踏んだなら、……現れなくてはならないはずの死神が、その姿を現さない。@
`　If I really stood on the 13th step... the grim reaper, that had to show itself, didn't appear.`@
br
;　……死神が現れない以上。@……私が１３段目を踏んだと思ったのは勘違いに違いないし。@……仮に本当に１３段目の怪異があったとしても、@……私を迎えに来てくれないのなら、何の意味もないのだ。\
`　...Since the grim reaper can't show itself. `@`...Then I must have simply mistook what I stood on to be the 13th step. `@`...And even if I had stood on a mysterious 13th step, `@`...it didn't mean anything because the reaper didn't come for me.`\

bg black,22
bg kaidan_01,22
wait 1000
bg kaidan_02,26
ld r,AYA_D1,26
ld r,AYA_D2,80

;「１、２、３…………。@………１１、１２。@……何度数えても、……１２段。」@
`"1, 2, 3... `@`...11, 12. `@`...No matter how many times I count it, I end up at 12."`@
br
;　……そんなものだ。@
`　...That's how it is.`@
;　私は、安堵とも落胆ともつかない溜息を漏らし、@……もう二度と、階段を数えながら上り下りすることはないだろうと思うのだった。\
`　I let loose a sigh of releif and disappointment. `@`...I thought I didn't need to go up and down the stairs to count again.`\

ld r,AYA_D3,80

;　馬鹿馬鹿しい…。@
`　How foolish...`@
;　やっぱり、１３階段なんて怪談、何の意味もない。@
`　As I thought, the tale of the 13th step has no real meaning.`@
br
;　私の生きる意味に何の意味もないように、……やっぱり、何の意味もないのだ。@
`　Just as it has no impact on my meaningless existence... it's meaningless.`@
;　私にも世界にも、何もかも、……意味も価値もない。\
`　Myself, the world, everything and anything, ...it's all useless, meaningless.`\

ld r,AYA_D2,80

me1v 16,50

;　消えたい。@
`　I want to disappear.`@
br
;　誰か私を消し去ってくれないだろうか。@
`　Won't someone help erase me?`@
;　この無意味無価値な世界から、@生きる意味も価値もない私を、そっと、水面に解ける粉雪のように……。\
`　I want to be erased from this meaningless valueless world. `@`I want my life without meaning to disappear, gently, like a snowflake on the water's surface...`\ 

;ld r,AYA_D3,80

cl r,22

fede 1,2000
E_B

wait 2000

bg black,42

;■あやが立ち去った後、階段に少し余韻を残してフェードアウトする。@

fede 0,1000
E_A

bg gakkou_01,2

bgm1 22

;　あやの学校での一日は、ぼんやりしているか、まどろんでいるか。@……あるいは机に突っ伏して眠っているかだけだ。@
` At Aya's school, whether she's daydreaming or dozing off,`@`...she just spends her days with her eyes closed laying down on her desk.`@
br
;　だから、彼女の一日は、常にぼうっとして霞んでいる。@
` So her days are always spent in a dreamy blur.`@
;　半分寝ているような、起きているような、……そんなまどろみの中で生きているのだ。\
` Seemingly half asleep, but seemingly half awake... she exists within that kind of dream.`\
bg black,22
bg gakkou_02,22

;　そんなだから、……食欲だって、あるわけもない。@
` Because of that... there's no way she'd have anything like an appetite.`@
br
;　給食の時間も、ほとんど箸は進まず、いつも残していた。@
` At lunch time the chopsticks go almost unused, and she always had leftovers. `@
br
;　そしてぼんやりと放課後を向かえ、ぼんやりと下校した。\
` So she listlessly met with the end of the school day, and listlessly went home. `\
bg black,22
bg roji_03,22

;　両親は共働きで帰りは遅い。@
` Her parents both worked, so they'd come home late.`@
br
;　かつてはテレビも見ていたが、その馬鹿馬鹿しい内容に何の意味も価値も見出せず。@……今では彼女は、家でもただぼんやりと横になって過ごすだけだった。\
` She used to watch television, but found no meaning or value in the idiotic content of the programs... `@`Now she just passes the time laying around in the house.`\
bg black,22
bg ie_04,22

;　いつものように、ぐたりと横になって見上げる天井。@
` As usual she lay still, gazing up at the ceiling.`@
br
;　……もう、染みの形さえ覚えてしまった。@
` ...She had already memorized the spots on the ceiling.`@
;　その染みの形に様々な空想の物語を思い浮かべたこともあったが、@すでにその無意味さに飽き果てている。@
` Her wild imagination could conjure up a variety of stories about these spots, `@`but she was already exhausted and tired of the senselessness.`@
br
;　だからぼんやりと、こうして死体のように放心するのだ。\
` That's why she listlessly emptied her mind like this as if she were a corpse.`\
;　意識がだんだん薄れてくる。@
` Her consciousness is starting to fade.`@
;　……このまま死ねないかな。@
`...She wondered why she couldn't die like this.`@
br
;　すると両親が帰って来て、食卓に呼びつけられるのだ。@
` When her parents returned, she was called to the dinner table.`@
;　もちろん、食欲などあるわけもない。\
` Of course, she had no appetite.`\
bg black,22

;　会話もなく、少し箸を付けて食卓を立つ。@
` There was no conversation, and she just played with her chopsticks a little and then left the dinner table.`@
;　そして部屋に戻り、また死体になる。@
` Then she returned to her room, and became a corpse again.`@
;　親に風呂を呼ばれるまでそれを続け、……入浴を済ませた後、また死体になる。\
` And continued as such until her parents called her for her evening bath... after which she returned to being a corpse once again.`\
mono 1
bg ie_04,22

;　消灯して深夜になって、布団に入っても死体のまま。@
`　Turning out the lights, even after slipping into her futon late at night she would remain a corpse.`@
br
;　眠るのは生きている人間のすることだ。@
` Sleep is for those who are alive.`@
;　死体は横になっているだけで、眠っているわけじゃない。\
` Corpses simply lay still -- they do not sleep.`\
;　……学校でも家でも居眠りばかりの彼女が、夜に快眠できるわけもない。@
` There's no way a girl who dozes off at school and at home all the time can sleep soundly at night.`@
br
;　だから、眠れない。@
` That explains why she can't sleep.`@
;　学校でも家でもそうであるように、@……まどろみと放心の入り混じった、どろどろの死体になって、@横になっているだけだった。\
` At school and at home, `@`...mixed with her sloth and dozing, she'd lay still and become a rotting corpse.`\

;　それで、せめて無心だったなら、彼女もさぞや気楽だったろう。@
` One would think because she was unconcious she would have been comfortable.`@
br
;　しかし、彼女は生きている。@
` However, she is still living.`@
;　だから、死体になりながらも延々と、@自分の意味や価値、生きることの意味や価値への自問自答を繰り返しているのだ。\
` So each time she would become a corpse,`@` she would repeatedly ask herself the meaning and value in her life.`\
;　それに窒息し掛けながら、希薄な意識のまま、緩い頭痛に彼女はずっとずっと苛まれ続けている……。@
` As she suffocates in this manner, in her dull conciousness she continues to be endlessly tormented by a throbbing headache...`@
br
;　だから、ふと意識が途切れて、わずかにでも眠り側に入った時だけが、@彼女の唯一の解放された時間だったに違いない………。@
` Thus, when her conciousness is suddenly cut and she can cross into sleep,`@` without a doubt that is her only release from the pain...`@
br
;　それが、相馬あやの、繰り返される死体のような日々だった……。\
` These were the repeating days of the corpse-like Aya Souma...`\
bg black,2
;mono 0

fede 0,2000
E_A
wait 1000

;■ここから、夢の中の世界。@（夢だとわかるようなフィルター処理はいらないです）

me1v 5,50

wait 2000

mono 0

bg rouka_02,42

mbg black,22
mcbg 22

wait 1000

;　………………………………。@
` ............`@
;　………ここ……は……？@
` .....Where... am I...?`@
br
;　紫色と橙色が入り混じった、黄昏色に染まった、どこか。@
` Somewhere where purple and orange mingled -- dyed the colors of twilight.`@
;　意識が戻ってくるにつれ、周りがはっきりと見えるようになってくる。\
` As her consciousness returned, her surroundings became visible.`\

;　そこは、………多分、学校の廊下だった。@
` This place is... probably, one of the school hallways.`@
;　自分が普段、よく使う廊下ではないけれど。@
` It's not a hallway I often use though.`@
br
;　多分、校内の、どこかの階の廊下だった。\
` Perhaps it was a hallway somewhere on the ground floor of the school.`\
bg black,23
bg rouka_03,23

;　ぱたぱたと、誰かが走る音が近付いてくる。@
` The patter of footsteps of someone running is drawing near.`@
br
;　それは、全身汗だくで呼吸を荒げた、一人の少女だった。@
` It was a lone girl sweating profusely and breathing heavily.`@
;　顔つきから、多分、上級生だろうと思った。\
` From her looks I thought she could be an upperclassman.`\

;　やがて、ふらりとよろめき、壁に寄りかかり、そのまま、ずり落ちるように座り込む。\
` At last, grinding to a halt, she leans against the wall and slides down to the floor.`\
se1v 13,50
quakey 2,200

;　彼女の爆発しそうな心臓と肺は、一度足を止めてしまったら、@もう二度と立ち上がる気力を与えてはくれないようだった。\
` As if her heart and lungs were about to burst, her legs stopped at once. `@`It seemed she could not muster up the energy to stand again.`\
E_A

;　ずかずか。@/
` Stomp...Stomp.`@/
bgm1 12
;……ずかずかずか。@
` Stomp...Stomp.`@
br
;　そんな彼女に、無慈悲な足音が近付いてくる。@
` With her like that, the sound of ruthless footsteps approached.`@
;　足早で重いその足音は、明らかに彼女を目標としていた。\
` Considering the heavy brisk pace, they were obviously after her.`\
se1 24

bg black,0
ld c,IZA_D3,42

bg rouka_03,0
ld c,IZA_D3,42

ld c,IZA_D2,22

;　廊下の彼方にゆらりと、その足音の主の姿が浮かび上がる。@
` Swaying in the corridor beyond, the figure of the owner of those footsteps appeared.`@
br
;　それは黒いマントを羽織った男の姿。@
` It was a man in a black coat.`@
;　肩に担ぎ上げているのは、……大きな大きな、鎌だった。@
` And on his shoulder he bore... a great, massive, scythe.`@
;　その姿を見て、死神を連想しない者はいないだろう。\
` Anyone could clearly see that he was a grim reaper, a shinigami.`\

me1v 17,70

;　少女にも、その禍々しい姿が近付いてくるのが見えているはず。@
` That must be be aparent to the girl as well as his ominous shadow drew closer.`@
br
;　しかし、もう立ち上がる気力はおろか、振り返る気力さえもないようだった。\
` However, she didn't have the energy to look over her shoulder or even stand.`\
;　死神は、そんな彼女になおもずかずかと近付いてくる。@
` The reaper was still stomping towards her.`@
br
;　すでに逃げる気力を失い、彼女が観念したことを認めると、にやりと笑った。\
` Having already lost the energy to flee, she accepted defeat, and grinned.`\
ld c,IZA_D5,80

;「何、座ってんだァ？@　もう逃げねぇのかァ……？@　……殺されちまうぞォ、おらァ！！」@
`"Huh? You're taking a break? `@`Aren't you going to ruun...? `@`...You'll be kiiiilled, SO GET UP!!"`@
;「………も、……もう、……無理です……。@……もう、走れません………。」@
`"....It's impossible.`@`...I can't run anymore...."`@
br
;　少女は荒い息のまま、懇願するようにそう言う。\
`　She said as if begging with her rough breathing.`\ 
ld c,IZA_D6,80

;「早く立たねぇと、俺が追い付いちまうぞォ？！@　泣き言いってねぇで、さっさと立てや、おらァ！！」@
`If you don't stand up I'm gonna catch up with you! `@`Stop crying and stand, GET UP!!"`@
;「無理です、もう無理です……。@こんなの毎日、……もう嫌です……。@許して……、許して下さい……！」\
`"I can't. I can't run anymore... `@`Every day is like this. I hate it. `@`Let me go...Please let me go..!"`\
ld c,IZA_D8,80

;「アホかてめェ。@俺ァ、死神だぞォ！！@　死神が獲物、許すわきゃねェだらァ！！」\
`"You must be stupid or something. `@`I'm a shinigami!! `@`Shinigami don't let go of their prey!!"`\
bg black,23
bg rouka_04,23

;「許して下さい…、許して下さい……。@私、何も悪いことしてないんです……。@いつもクラスのみんなにいじめられてて……、@どこにも居場所がないんです……。@なのにその上、……こんな目に遭わされるなんて……。@そんなのあんまりです…、あんまりです……。@何で、こんな私がこんな目に遭わされなきゃならないんですか……。@……死神なら、@私をいじめる人とか、もっともっと悪い人の魂を獲物にしてくれればいいのに……！」\
`"Let me live please...Let me live. `@`I won't do anything bad anymore... `@`I'm always bullied by everyone in class... `@`I don't have a place anywhere... `@`And to meet a fate like this...`@`I don't deserve this... not like this... `@`Why do I have to suffer like this? `@`If you're a shinigami, hunt the souls of the worse people that bully me!"`\
ld r,IZA_D6,6

;「俺ァな。@お前みたいな。@クソ落ち目なヤツが大好物なんだよォ…！！@　うっひゃっひゃっひゃっひゃ！！」@
`"You know what. `@`I like you. `@`Failures like you are my favourite food!! `@`Uhya hya hya hya hya!!!"`@
;「酷いです酷いです、あんまりですあんまりです…！！@　許して許して許して許して……！！」\
`"You're horrible! I don't deserve this, I don't...! `@`Please please please please let me go!"`\
;　とうとう死神は、少女のもとに辿り着く。@
` At last the shinigami arrived at the girl's side.`@
br
;　そして、担ぎ上げていた大鎌を、ゆっくりと少女に向ける。\
` and the scythe being held up was slowly pointed towards the girl.`\
cl r,0
ld c,IZA_D5,4

;「そんだけ喋れる体力がありゃァ、まだ逃げれるだろォが。@つまんねーんだよ。@俺は、必死な形相で逃げ回る獲物を追い掛けるのが堪らねェんだからよォ！」@
`"If you still have the strength to speak, then you should still be able to run away. `@`I just CAN'T STAND IT when my prey isn't running desperately here and there!!"`@
br
;　死神の男の表情が邪悪な笑みで歪み、笑い声を轟かせる。\
` The shinigami's face warped into a wicked smile as he roared with laughter.`\
;　しかしもう、少女は覚悟を決めている。@
` However the girl was already preparing to meet her end.`@
br
;　もう逃げ回ることと、その恐怖に耐えられないのだ。\
` She couldn't stand that terror of taking to fleeing again.`\
;「……殺すなら殺して下さい……。@どうせ生きてたって、いいことなんてない……。@……痛いのは一瞬、痛いのは一瞬……。」@
`"...If you're going to kill me then please do it.` @`I mean, there's nothing good about being alive either... `@`The pain will just be for a moment, ...just for a moment."`@
br
;　少女は念仏でも唱えるかのように、痛いのは一瞬と何度も何度も小声で繰り返す。\
`Like a prayer, the girl recited this over and over.`\
ld c,IZA_D8,80

;「けっ。@観念決めやがったかァ。@……馬鹿なヤツだぜ。@死が心地良いモンだと、本気で思ってやがんのかァ？@　くくく、くっひっひひひひゃっひゃっひゃ！！@　馬ァ鹿がァ！！！」\
`"Tch. `@`You've already given uuup? `@`What a fool. `@`You really think death is a good thing? `@`Kukuku, kuhihhihihihi hya hya hya!! FOOL!!!!"`\
;■ぶぉん、ずぎゃ！！@

se1v 20,100
bg black,1

wait 1000

se2v 36,100
;bg BLADE2W,1
bg rouka_03,1
quakey 7,1200


;　死神の鎌の無慈悲な刃が、どっかりと少女の背中に打ち込まれる。@
` The ruthless blade of the scythe drives into the girl.`@
br
;　鶏を絞め殺したかのような、細いねじ切れるような悲鳴が少女から漏れる。\
` A sound like that of a strangled chicken, a shrill shriek escapes her and is suddenly silenced.`\
se3v 66,100
se1v 55,100
bg blue1,1
bg rouka_03,0
print 99,2000,"breakup.dll/llb"

;　その瞬間、少女の全身が真っ青な炎を噴出して燃え上がった。@
` At that moment, her whole body burst into a deep blue flame.`@
br
;　その青い業火は、人の世の炎のどれよりも熱く、そして冷たかった。\
` That blue flame was hotter and colder than any flame of the human world.`\
;　全身を焼き焦がし、凍えさせ、苛み苛み、細胞の一粒ずつを激痛を伴わせながら焼き尽くしていく。@
` Her whole body burned and froze in torment, while her cells were devoured one by one.`@
br
;　少女はもう、身動きもしないが、@肉体の全てが焼き尽くされて消え去るまで、その意識ははっきりと残っており、@その激痛から逃れることは許されなかった。\
` The girl didn't stir anymore. `@`However, all of her flesh was cooked until it was erased, and her consciousness, which remained,`@`could not escape that terrible pain.`\ 
ld c,IZA_D3,22
ld c,IZA_D5,80

;「綺麗に死ねて、安らかな眠りにつけるとでも思ったかァ？@　違ェな。@……これでお前はもう、永遠に俺の獲物だぜ。@俺の地獄で、永遠に俺のために断末魔を聞かせやがれィ。@くっくくくくくく、ひゃっはっはっはっはっは！！」\
`"So ya thought you'd end up sleeping peacefully and dying a clean death? `@`Wroong. `@`...It's too late, and now you're my prey for eternity. `@`Now let me hear your agony in my hell for my enjoyment for the rest of eternityyy. `@`Ku kukukukukuku, hya ha ha ha ha ha!!"`\

bg black,0
ld c,IZA_D8,25

bg black,5

;bg black,22

me2v 28,100

;　全身を焼き尽くされて死んだ少女の魂は、奈落の底に落下していた。@
` The soul of the completely burnt girl fell into the depths of abyss.`@
br
;　無我の境地などとんでもない。@
` There was no unconciousness or loss of self.`@
;　全身は焼ける痛みと凍える痛みではちきれそうで。@どこまでも無限に落下していく恐怖で心も破裂しそうだった。\
` Her whole body burst with the pain of burning and freezing.`@` Her heart was full to burst from the plumetting endless horror.`\ 
se1 24
se2v 66,100
bg aka2,8

;　唐突に、漆黒の奈落の底が、姿を現す。@
` Abruptly, something emerged out of the jet black abyss.`@
;　それは見るもおぞましい、不気味な肉色の、ぶよぶよとした異界だった。@
` It was hideous to even look at, an eerie, flesh-colored organic alien world.`@
br
;　例えるなら、まるで胃袋の世界。@巨大なバケモノの胃袋の中そのものだった。\
` For example, it was as if it were a world of stomachs. `@`In fact, she was inside the stomach of a giant monster.`\
bg aka3,25
se3v 38,100
quakey 5,1000

;　そのおぞましく蠢く肉のひだの中に、少女は墜落する。@
` The girl crashed into the folds of that hideous, wriggling flesh.`@
br
se1 55

;　そこには、体を焼いて爛れさせる酸が一面から湧き出していた。@
` There, the acid used to burn and inflame her body gushed from the whole surface.`@
;　そしてびっしりと剣山のように鋭い牙が一面に生えだしていた。\
` And fangs packed like needles in a pincushion emerged.`\
se2v 55,100
quake 5,700

me3v 3,85

;　少女は全身を焼かれ、刺され、転げ回りながら絶叫する。@
` The girl's whole body was burned and pierced while she screamed and writhed.`@
br
;　皮膚がみるみる溶けて、肉色の人体標本のようになっていく……。@
` In a flash, her skin melted and became just like a bloody human anatomy dummy...`@
;　肉の大地は絶え間なく蠢き、少女を酸の海や牙の剣山の上で、嬲るように転がし続けるのだ。\
` The fleshy ground continued as if torturing her by rolled the girl over and over in a sea of acid and needles.`\
　それは紛れもなく、巨大な悪魔の胃袋が、彼女を消化しようとする行為だった。@
br
;　少女は苦痛に絶叫しながら、早く自分が事切れてくれることを願う。@
` The girl, screaming in pain prayed for her life to quickly end.`@
;　しかし、酸も牙も、全身の生皮を剥ぐかのように苛むのに、死には一向に至らせてくれない。\
` However, even though the fangs and acid had stripped her skin off, death did not come to her.`\

bg black,26
;bg k_rouka_03,0

bg black,0

ld c,IZA_D2,22
ld c,IZA_D6,80

;「死ねるわけねェだろ。@お前はもう、死んだんだぜ？@　だから二度は死なねェ。@二度と死ねねェ！！@　お前はそこで永遠に、俺の胃袋の中で嬲られて、俺に魂を啜り取られるんだよ！！」@
` "No way you can die. `@`You see, you're already dead? `@`You can't die twice, see. `@`You don't die twice!! `@`You'll spend eternity being tortured in my stomach, and I will digest your soul!!"`@
br
;　死神の男は眼下を見下ろし、苦悶の絶叫を抑えられない彼女を嘲笑う。\
` The shinigami looked on, ridiculing the girl who could not surpress her cries of anguish and suffering.`\

;　苦痛に喘ぐことしか出来ない少女にはわからないだろうが。@ここから見下ろせば、眼下には他にも何人もの哀れな犠牲者を見ることが出来る。\
`　The girl probably couldn't understand as all she could feel was the grip of agonizing pain. `@`If she could look down at the scene from above, she would see the suffering of countless victims.`\

bg black,26
bg aka2,22
se1 55

;　全身の皮をすっかり溶かされ、もはや男か女かもわからない姿になっても死ねず、@苦悶に転げまわる哀れな犠牲者たち。@
`　Their hides had clearly dissolved from their undying bodies that could no longer be distinguished as men or women. `@`Victims writhing in agony.`@
br
;　より長くこの地獄にいる者は、もはや人間としての姿さえ失いかけている。@
`　The ones that had spent too long in this hell didn't even appear human.`@
;　腕が千切れ、頭が千切れ、@……最後には、元が人であったことさえわからなくなる、肉塊と成り果てるのだ。\
`　Their arms and heads were split apart, `@`...and finally they'd reach a point where they'd become lumps of flesh that one would hardly have thought were once human beings in the first place.`\

me4v 16,70

;　しかしそれでも、死ねない。@
` But even then, they didn't die.`
br
;　もはや口さえなく、苦悶に呻き声を漏らすことさえ出来なくても。@
` Without mouths, they could no release their screams of agony.`@
;　永遠に死ねず、永遠にこの悪魔の胃袋の中で弄ばれ続けるのだ……。\
` An eternity without dying--they'd continue eternally being tortured in the stomach of this demon...`\

bg black,22
;bg k_rouka_03,0
;ld c,IZA_D4,22
;ld c,IZA_D3,80

;「これが俺の死後の世界だぜェ…？@　死は安らぎなんかじゃねェ。@永遠の苦痛の入口だ。@……こんな光景を見せられちまったら、@……二度と、雪が解けるように眠るように死にたいなんて、言えやしねェだろォ……？」\
`"This is my afterlife... `@`Death isn't paradise or anything of the sort. `@`It's the gateway to an eternity of pain. `@`...After letting me show you this, `@`...I bet you won't say anything about wanting to die in your sleep like melting snow, will ya...?"`\

fedexx 85,100,100,100,100,0,2000

ld c,IZA_D2,2
ld c,IZA_D3,80

;　死神が、……そう言いながら、見る。@
` While saying that, the shinigami looks.`@
br
;　“私”を、見る。\
` He looks at "me".`\
;　……ここって、……私の夢の中の世界じゃ、なかったっけ……？@
` But this... wasn't this the world of my dreams...?`@
br
;　テレビの向こうにいるはずの人物に、こちらを睨みつけられたかのような不気味さ。@
`　It was an unease almost as if an actor that should have been inside a TV set started to glare in my direction.`@
;　この不気味な何かは、どうせ私の夢で、@“私”には関係ないものと、心のどこかで決め付けていた。\
`　This uneasiness, somehow within my own dream, `@`my mind was following someone who had nothing to do with "me".`\

;　しかし、死神は“私”に向かって言っているのだ。@
` But the shinigami was speaking to "me".`@
br
;　雪が解けるように眠るように死ぬことが願望である、“私”に言っているのだ。\
` Speaking to "me" and my desire to die as if falling asleep, softly as snow melts.`\
;　死神は、にやにやと笑いながらも、決して私をその眼力から逃がしてはくれない。@
` The shinigami didn't let me escape from his grinning gaze.`@
br
;　私は夢の中であるにもかかわらず、……全身が金縛りになるような恐怖を覚えるのだった……。\
` Even though it was a dream, ...I felt a paralyzing fear all over my body...`\
se3v 66,100

bg white,48
me5 23
bg black,48
bg ie_06,48

fedexx 0,0,0,0,0,70,3000
E_B

;　………さっきからずっと聞こえるそれが、目覚ましのアラームであると気付けた時。@私は心の底から安堵した。@
` When I realized my alarm clock had been ringing for quite some time, `@`I was relieved from the bottom of my heart.`@
br
;　目を覚ました時。@私の全身は汗でびっしょりだった。\
` When I woke up, `@`my body was drenched in sweat.`\
fede 0,1000
E_A

bgm1 7

;　……恐ろしい夢に怯えて目を覚ました経験が、なかったわけじゃない。@
`...It's not as though I've never had the experience of waking up from a nightmare before.`@
;　しかし、今までのそれとは一線を画す何かだった。@
` But something about this really distinguished itself from past experiences.`@
br
;　そう、“何か”。\
` Yes, quite the "something".`\
bg black,22

;　あれは本当に夢だったのだろうか。@
` Was that really a dream?`@
br
;　こうして、何事もなく布団の中で目を覚ませたことを、これほど嬉しく思ったことはない。\
` I'd never been so happy to just be uneventfully laying wide awake in my futon.`\
mono 1
bg k_rouka_03,0
ld c,IZA_D5,22

;　……あの死神の男の眼光。@笑い声。@……あの胃袋のようなおぞましい世界で、@死ぬことも出来ず、哀れに蠢く犠牲者たちの苦悶の声。@
` ...That shinigami. `@`His laughter. `@`...the voices of those poor, undying, writhing victims in that world not unike a hideous monster's stomach.`@
br
;　全てがありありと思い出せる。\
` I could remember it all.`\
bg black,22
mono 0
bg ie_06,22

;　私は、母の「とっとと起きてきなさい！」という声が聞こえてくるまで、@しばらくの間、放心することしか出来なかった……。\
` I could only relax for a while until I could hear my mother's voice calling for me to wake up...`\
bg black,2
;wait 2000

fede 0,2000
E_A

;■通学路～学校

;me1 33

;bg roji_03a,22
;wait 1000
;bg black,22
;bg roji_04a,22
;wait 800
;bg black,22
bg gakkou_01,22
wait 2000
bg black,22
bg shoukou_01,22

bgm1 6

;　……あの夢は、一体、何だったんだろう。@
` ...What on earth was that dream?`@
br
;　あれが、ひょっとして、１３階段の呪いか何かだろうか。\
` By any chance, was it the curse of the 13th step?`\

;　呪いなんて、……あるわけがない。@
` No, surely not a curse...`@
br
;　多分、私は１３階段を踏んだと思い込み、@……自分が思っている以上に、怯えてしまっていたのだろう。@そしてそれを、ああして夢に見てしまったに違いない。\
` I thought I had probably stepped onto the 13th step, `@` and perhaps that frightened me deeper than I thought. `@`That must have been why I had that dream.`\
bg black,22
bg kaidan_01,22
ld c,AYA_D4a,22

;　私は昇降口から、……いつもの階段の前にやって来る。@
` From the entryway, ...I go up the front of the stairs as I always do.`@
br
;　他の生徒たちが、何の関心もなく、当然のように踏み越えていくその階段を、@……もう一度、指で数える。\
` Other students paid no attention, and so they went up the stairs as always. `@`...I'll count on my fingers one more time.`\
bg black,22
bg kaidan_03,22
;ld c,AYA_D7a,22
;ld c,AYA_D3,80

;　……１２段。@
` 12th step.`@
;　間違いなく、１２段だった。@
` Without a doubt, it was the 12th step.`@
br
;　そう。@やっぱりあれは、数え間違いだったんだ。@
` Right. `@`I had probably made a mistake while counting.`@
;　なのに、本当に１３階段を踏んだと思いこんで怯えて、あんな夢まで見て。\
` Even so, I was scared, convinced that I had actually stepped on the 13th step caused me to have that dream.`\
bg black,22
bg kaidan_01,0
ld r,AYA_D2,22

;　………私ってば、馬鹿みたい。@
` ...Jeez, I'm such an idiot.`@
br
;　そう心の中で呟きながらも、……私は多分、今も怯えていた。\
` Even while muttering this to myself...I was still scared.`\
;　私にとって、死は安らかなる終着点。@そう信じてきた。@
` Death would be a peaceful end for me. `@`I had believed that.`@
br
;　それを見透かされ、死後の世界はそのような甘いものではないと突きつけられた、あの衝撃。\
` Having seen been confronted with an afterlife that was not such a sweet thing after all, being forcefully disillusioned like that left an impact on me.`\
ld r,AYA_D4a,80

;　………………あんなの、どうせただの夢。@気にしちゃ駄目だ。@馬鹿馬鹿しい……。@
` .......Anyway, it was just a dream. `@`It's pointless to worry about it. `@`Foolish even...`@
br
;　そうは思いつつも。@……私はその階段を、心の中で数えながら上らずには、いられなかった……。\
` While thinking that`@`...I couldn't count any further while on those stairs...`\
cl r,2

;■あやが階段を去り、しばらく階段のままwait。@その後、死神フェードイン。@
;wait 3000

wait 1000

fede 0,2000
E_A
wait 3000

se1 24

ld c,IZA_D3,2

wait 1000

ld c,IZA_D5,80

;「大好物だぜ……。@……俺の大好物の、クソ落ち目な小娘じゃねェか……。@くっくくくくくく……！！」\
`"My favorite food...`@`...You're a real failure aren't you girl...? `@`Kukukukukukuku!!"`\
cl c,2
bg black,2

me1v 11,90

wait 2000

bg kyou_02,22

;　相馬あやの今日という日は、至極当然に、いつもと何も代わり映えはしなかった。\
` On this day, for Aya Souma, as usual, nothing changed for the better.`\
;　授業のほとんど全てを、ぼんやりとまどろんで過ごし。@
` She spent time dozing off and daydreaming through almost all of the lesson.`@
;　休み時間は机の上に突っ伏して眠った。@
` During recess she put her head down on the desk and slept.`@
br
;　給食も食欲はなく、いつものように残して、残飯を寸胴に戻した。\
` Since she had no appetite, she'd always leave food on her plate and give back leftovers.`\
;　それだけ。@……いつものようにぼんやりとした、単調で無意味な一日だった。@
` That was all there was to it. `@`...As usual, it was a monotonous and meaningless day.`@
br
;　………少なくとも、学校を終えるまでは。\
` At least...until she finished school.`\
bg black,22

E_A
wait 1000

bg kyou_01,22

me1v 24,70

;「ですから、家に帰ったら必ず、うがい、手洗いをするように。@いいですねー！」@
`"So, when you go home, `@`make sure to rinse your mouth and wash your hands!"`@
;「「「はーい！！」」」\
`"Yes!"`\

「では日直、号令ー！」@
`"Alright, classroom assistant please dismiss the class!"`@
;「きりーつ！@　れーい！！」@
`"Staaand! `@`Bow!"`@
br
;　さようならの号令で、学校から解放される。@
` After saying goodbye and being dismissed, she would be freed from school.`@
;　……別に家に帰ってもすることなんてないけれど、多少の解放感はある。\
` ...Apart from that, there was a sense of relief in that she didn't have to return home.`\
;「「「さよーならー！！！」\
`"Goodbyeeee~!"`\

E_A
se1v 2,50
nega 1
print 1
nega 0
print 22

wait 2000

ld l,AYA_D9a,22

bgm1 16

;「……………ッ。@………………え…？@　…………？！」\
`"......`@`......huh?`@`.....?!"`\
se2 33

;　突然に。@唐突に。@
` Suddenly.`@`Abruptly.`@
br
;　え……？@
` ...Eh?`@
br
;　な、……何が起こったのか、理解できない。\
` Wh... What happened, I don't understand.`\
cl l,22

;　クラス全員で先生に向かって、さようならと言った。@
` The whole class faced the teacher and said "goodbye".`@
br
;　その瞬間。@
` In that moment`@
br
;　世界が消えたのだ。\
` The world disappeared.`\
;　……いや、消えたといっても、真っ暗になったわけじゃない。@もちろん、ここが教室であることにも変わりはない。@
` ...No, saying that it ended would be wrong--it didn't even go dark.`@`Of course, there was no change even here in the classroom.`@
br
;　しかし、消えたのだ。@
` But it was gone.`@
;　この世界から、教室から、……私、相馬あやを除く、全ての人間が、@まるで蛍光灯がぽんと消えるかのように、……唐突に消え去ったのだ。\
` Like the pop of a flourescent light going out, `@`everyone in the world and in the classroom disappeared... except for me... Aya Souma.`\
bg black,23
bg kyou_02u,23
ld r,AYA_D9,24
ld r,AYA_D9a,80

;「…………なに………。@……え……………。」@
`"......What.....`@`.....ah..."`@
br
;　私はわけがわからず、周りを見渡す。@
` Without knowing why, I looked around.`@
;　しかし、どこにもいない。@誰もいない。@
` However, nobody was around. `@` Everyone was gone.`@
;　それどころか、学校全体のざわめきさえ消え去った。\
` On top of that, all the ambient school noise had vanished.`\
;　それは、この教室だけでなく、学校全体、@……いや、ひょっとすると、この世界そのものから人間が消え去ったことを意味するのかもしれない。@
`　It was as if it wasn't everyone in the classroom, but the entire school, `@`...no, it could even mean that the rest of the world had disappeared.`@
br
;　唐突の、無人の世界。@無音の世界。@
` Suddenly, it was a world without people. `@`A world of silence.`@
;　……意味が、わからない……。\
` ...What was the meaning of this...?`\
bg black,23
bg kyou_04,23

;　そうっと、廊下を覗いてみるが、……シンと静まり返っている。@
` I wondered and took a peek out into the corridor... it was dead silent.`@
br
;　隣の教室はおろか、この校舎丸ごとに、……誰も人の気配がしない。\
`　It wasn't just the neighboring classrooms either, because no one could be seen nor heard inside the building...`\

bg black,24
bg koutei_06u,24

;　教室に飛んで戻り、窓から校庭を見下ろす。@
`　Running back into the classroom, I looked down at the schoolyard from the window.`@ 
;　……何しろ下校の時間だ。@普段なら、昇降口から校門へと向かう行列を見下ろせるはずだ。@
`　...Nevertheless it was time to go home. `@`Normally, I should be looking down on a line of people heading towards the gate from the school entrance.`@
br
;　しかし、それがない。@
`　But there wasn't one.`@
;　ないどころか、……人っ子ひとり。@いや、動くもの一つさえ、見つけることが出来ない。\
`　There wasn't even a line ...not even a single soul. `@`Rather, I couldn't even see anything stirring outside.`\

bg black,22
bg kyou_02u,22
ld c,AYA_D9a,22
ld c,AYA_D8a,22

;「な、……何なの………、……これ………。」@
`"Wh, ...what... is this..."`@
br
;　空の色も、何だか変だ。@
`　Even the pigment of the sky was somehow strange.`@
;　まだ４時にもなっていない時間のはずなのに、@もう夕方のような、濃い橙色に染まっているのだ。\
`　Even though it shouldn't even be 4 o'clock yet, `@`the sky was stained a deep orange as if it were already twilight.`\
ld c,AYA_D7a,22

;　………この、嫌な橙色に染まった校内を、……私は覚えている。@
`　...I remembered seeing this detestibly orange colored school interior before.`@
br
;　あの、悪夢の中の光景だ。@
`　It was the background from my nightmare.`@
;　少女が死神に追われ、殺された、今朝のあの最悪な夢の中の光景だ。\
`　This was the backdrop to my horrific nightmare this morning where a girl was chased and murdered by a shinigami.`\

;　そんなはずは、そんなはずは……。@
`　No way, no way...`@
;　とにかく、こんな空の色は、６時くらいにならなければ見られないはず。@
`　Anyway, based on the sky being like this it must already be around 6 o'clock.`@
br
;　今が６時のわけがない。@ほらっ……！\
`　There's no way it's 6 o'clock. `@`I mean look...!`\

bg black,23
bg kyou_01,23

me1v 11,90

;　教室の時計を見上げる。@
`　I look up at the classroom clock.`@
;　確かに時計は、夕方の時間を示してはいなかった。@
`　Of course the clock didn't show it was the twilight hour.`@
br
;　しかし、…………どういうことなのか、１１時５５分を指していた。\
`　Although, ...for some reason it showed it was 11:55.`\

;　正午前……？@　お昼の時間？@　こんな夕焼け色の空なのに…？@
`　In the A.M....? `@`Day time? `@`Even with the sky colored by the sunset like that...?`@
;　意味がわからない。@
`　I don't understand why.`@
br
;　こんな夕方の１１時５５分の校舎に、……私以外の誰もいない世界。@
`　It's twilight at 11:55 in the school building, ...and I'm alone in the world.`@
;　私は唐突に何の前触れもなく、………この無人の校舎の世界にいたのだ……。\
`　I was suddenly and without warning, ...in a school building from an uninhabited world...`\

ld c,AYA_D5a,22

;「これ………。@……まさか、…………。@……でも、そんなはずは………。」@
`"This.... `@`It can't mean...... `@`...But there's no way..."`@
br
;　否定したい。@……でも、全身の細胞が、足元からじわじわと、……認め始めている。\
`　I want to deny it. `@`...But every cell in my body began to shiver starting with the soles of my feet... and I began to understand.`\

;ld c,AYA_D4a,80

;　ここは、……あの悪夢で見た世界そのものなのだ。@
`　This place... is the world I saw within my nightmare.`@
br
;　この世界で、名も知らぬ少女が死神に追われ、追い付かれて殺され、@……恐ろしい地獄に落とされた………。\
`　In this world, a nameless girl was pursued by a shinigami -- caught, killed, `@`...and then dropped into a terrifying hell...`\

E_A


;　その時、この世界で始めて、音を聞いた。@
`　At that moment, I heard a sound for the first time in this world.`@
;　自分以外に誰かが居てくれた、という安堵は一瞬だけ沸きあがったが、すぐに消えた。@
`　I had for a moment a sliver of hopeful excitement that someone else other than myself was there, but it immediately vanished.`@
br
;　なぜなら。\
`　Because.`\

se1v 14,100
bg black,22

;　………ずかずか。@
`　...Thump thump.`@
;　ずかずか、ずかずかずか。@
`　Thump thump, thump thump thump.`@
br
;　踵を踏み鳴らす、その重く足早な足音を、私はもう夢の中で知っていたからだ。\
`　The stomping sound of heels. `@`Heavy footsteps moving quickly. `@`I realized I was already inside the dream.`\

bg kyou_03,22

;　その足音が、どんどんこの教室に近付いてくる。@
`　Those footsteps were quickly closing in on this classroom.`@
br
;　私は呆然と立ち尽くし、……その音の主を待ち受けた。@
`　I stood listlessly, ...and waited for the owner of those footsteps.`@
;　あの死神でないことを祈って。\
`　I prayed it wasn't that shinigami.`\

;　そして、……その漆黒のマントを羽織り大鎌を背負った大柄な人影が、……ぬぅっと、廊下より姿を現す。@
`　Then... donning that jet black cloak across his back... a man with a large build slid open the door from the hallway.`@
br
;　それは、紛れもなく、………あの、………死神………。\
`　Tht was without a doubt... that... shinigami.`\

silent 3,1
se2v 82,100
;cl c,0
;ld l,AYA_D8a,24

wait 2000


ld R,IZA_D6,42
wait 1000
ld R,IZA_D8,80

se1v 2,100

wait 1000

bgm1 23

;「俺の学校へようこそォ！！@　くっくくっくっく/
`"Welcome to my school!! `@`Ku kuku ku ku`/


se1v 84,100

;ひゃっはっは！！」@
`Hya ha ha!!"`@
br
;　開口一番に死神が聞かせた笑い声は、……紛れもなく、あの悪夢の中で聞いたものだった。\
`　When I first heard the shinigami's laughter, ...it was without a doubt the same one I had heard from within that nightmare.`\

ld l,AYA_D7a,23

;　もう、私は目の前の光景にうろたえたりしない。@
`　I didn't let my guard down while watching this spectacle.`@
br
;　これが夢かもしれないなどと、頬を抓りもしないし、眉に唾を塗るようなこともしない。\
` This might be a dream, but I didn't attempt to pinch my cheek or wake myself up.`\

;　とにかく、目の前に、あの恐ろしい死神が実在することが現実であり。@
`　Regardless, the reality is that standing before my very eyes is that terrifying shinigami.`@
;　そして、逃げなければ殺されて、@あの恐ろしい肉色の、胃袋の地獄に落ちて永遠にもがき苦しむことになるのだ。\
`　Therefore if I can't run away I'll be killed, `@`and be plumeted into that horrific organ-colored hell stomach to writhe in agony for eternity.`\

ld l,AYA_D8a,80

;　冗談じゃない、冗談じゃない……。@あんな目に、遭わされたくなんかないっ。\
`　You've got to be kidding me... `@`I didn't do anything to deserve a fate like that.`\

ld r,IZA_D2,80

;「そうとも。@夢で見た通りだぜ。@俺はお前を追って、殺す。@お前は死にたくなけりゃ、必死こいて逃げまくってみろ。@俺ァ、お前らが汗だくになって逃げ惑うのを、@どこまでもどこまでも追い掛けるのが、最高の楽しみなんだァ！！@　そぅら、逃げろや、逃げろ！！@　俺に捕まったらどうなるか、お前はもう、知っているはずだぜェ…！！」\
`"Maybe. `@`It's just like you saw in your dream. `@`I'll chase you, and I'll kill you. `@`If you don't want to die, then try running away with everything you have. `@`You know, for me seeing your kind covered in sweat, `@`and chasing you everywhere, that's what I find truly fun!! `@`On you go, now run, RUN!! `@`You already know what's gonna happen to you when I catch you...!!"`\

ld r,IZA_D5,80

;　そう言いながら、死神は顎で、教室を出ろと促す。@
`　As he said that, the shinigami directed with his chin for me to get out of the classroom.`@
br
;　……もしそれを断れば、……この教室という袋小路で、即座に死神に捕まって、……地獄行きだ。\
`　...And if I refused to do that, ...he would catch me right away in this deadend classroom, ...and to hell I would go.`\

ld l,AYA_D5a,80

;　意味もわからない、わけもわからないっ。@
`　I don't know why, I don't know how.`@
;　でも、あんな地獄に落とされるなんて、絶対にごめんだっ。@
`　But being thrown into that kind of hell is something I want to avoid that at all costs.`@
br
;　私は死神の不敵な笑いと教室の出口を見比べながら、恐る恐る、教室を出る。\
`　As I looked at the classroom exit and watched that shinigami's fearless grin, carefully, carefully, I leave the classroom.`\


cl l,23

;　それでいいとでも言うかのように、死神はにやりと笑うと、ずかずかと足早に歩き始める。\
`　As if telling me I had done well, the shinigami sneered, and so the thumping of his footsteps began.`\

cl r,0
;ld c,IZA_D2,24
ld c,IZA_D6,24

me1v 17,70

;「さァ、ゲームの始まりだぜェ…！！@　お前はどこまで逃げ延びられるかなァ…？！@　楽しませてくれェ！！」\
`"Now then, the game begins!! `@`I wonder just how far and how long you can run...?! `@`Show me a good time!!"`\

bg black,23

me2v 5,70

bg rouka_04,23

;「だ、……誰かぁああぁあ！！@　誰か助けてぇええええぇぇぇ！！！」@
`"S- ...Somebodyyyy!! `@`SOMEBODY HEEEEeeeEEEEELP!!!"`@
br
;　防犯訓練の時に習った、助けを求める練習の通りに、私は廊下を駆けながら大声で叫ぶ。@
`　Just as I had learned from a crime prevention lecture, I screamed for help as I ran down the hallway.`@
;　……しかし、その声は廊下をどこまでも残響するだけ。@誰も応えたりはしなかった。\
`　...But all my screams did was echo through the hallways. `@`No one gave a response.`\

bg black,24
bg kyou_04,24
wait 1000
ld c,IZA_D3,22
ld c,IZA_D5,80

;「はっはっはァ！！@　この世界には俺とお前以外には誰もいねェ！！@　そんな大声を出すだけ、体力の無駄だぜェ！」@
`"Ha ha haa!! `@`You and I are alone in this world!! `@`Screaming like that is just a waste of stamina!"`@
br
;　死神が教室から出てくる。@早足ではあるが、駆けてはいない。@
`　The shinigami left the classroom. `@`He has a quick pace, but he doesn't run.`@
;　子供の足でも、走れば逃げ切ることは難しくないはず。\
`　Yet, if a child tried to outrun him, it would hardly be difficult for him to catch them.`\

bg black,23
bg rouka_01,23
wait 500
bg black,23
bg kaidan_02,23
wait 500
bg black,26
bg rouka_02,26
wait 500
bg black,24
bg shoukou_01,24

;　私はばたばたと階段を駆け下り、昇降口へ躍り出る。@
`　I came barreling down the stairwell and ran to the entrance.`@
br
;　とにかく、この学校から逃げ出そう。@そうすることで、死神の世界から逃げられるかもしれない。\
`　At any rate, I have to get out of the school. `@`Once I do that, I might be able to escape the world of the shinigami.`\

ld r,AYA_D8a,24


;　昇降口にはガラス戸が閉まっていた。@……こんなものが閉まっているところなんて、見たことがない。@
`　The entrance was shut with glass doors. `@`...I had never seen it closed with something like that before.`@
;　開けようとするが、開かない。@鍵でも掛かってる？@
`　It looks like it can be opened, but it won't let me out. `@`Does it need a key?`@
;　そうと思わしきものをがちゃがちゃといじるのだが、どうやっても開かない。@びくともしない…！\
`　I pondered this as I tried to force the door, but it won't open no matter what I try. `@`It won't budge...!"`\

;　そんなことをしている間に、死神の足音が階段を降りてくるのが聞こえる。\
`　While I was doing that, I could hear the shinigami's footsteps going down the stairwell.`\

bg black,23
bg shoukou_02,23
wait 500
ld r,IZA_D3,22
ld r,IZA_D5,80

;「無駄だぜェ。@俺の学校は、現世から切り離された異空間！@　扉も開かねェし、窓も開かねェ！　窓も割れねェ！！@　お前はこの校舎の中で、俺から走って逃げ回るしか生き残る方法はねェのさッ！！」\
`"It's pointless. `@`My school has its own space severed from the real world! `@`Doors won't open, windows won't open either! You can't even break them!! `@`The only way you can survive in this school now is by running away from meeee!!"`\

;　下駄箱の向こうに死神が姿を現す。@
`　The shinigami reveals himself across the shoe racks.`@
br
;　下駄箱一つを挟んで、ぐるぐると回って逃げながら、私は麻痺した頭の霞を懸命に払おうとしていた。\
`　Running in circles in-between the shoe racks, I drove away the paralyzing haze that seized my mind.`\

ld l,AYA_D5a,23

;「あ、……あんたは誰っ……。@……何で私をっ……。」@
`"Wh- ...Who are youuu... `@`...Why, why me...?"`@

ld r,IZA_D6,80

;「俺かァ？@　いいぜェ。@お前とはどれほどの付き合いになるか知らねェが、一応、自己紹介をしてやらァ。@俺は学校妖怪序列第２位「１３階段の死神」こと、イザナミさまよ！」\
`"Who am I? `@`Alright. `@`I don't know how long we're going to be seeing each other, but I guess I'll introduce myself. `@`I am The Second Rank of the School Youkai, "Reaper of the 13th Step", Izanami-sama!"`\

bg black,23

;　イザナミ。@それが死神の名のようだった。@
`　Izanami. `@`That was the name of the shinigami.`@
br
;　……何だかまるで、日本神話の中の神様みたいな名前……。\
`　...It was just like the name of the deity from Japanese mythology...`\

bg shoukou_02,23
ld c,IZA_D3,22
ld c,IZA_D6,80

;「俺に本来、名前はねェ。@ただの１３階段の死神だった。@それを、どっかの誰かが、黄泉津大神のイザナミの名を与えてくれた、ってわけだ。@気に入ったから、それ以来、俺の名前にさせてもらってるがなァ。@……しかしよ、イザナミってのは本来、女の名前だぜ？@　何とも間抜けな話だぜェ、くっはっはっは…！！」\
`"Until recently, I had no name. `@`I was just the Reaper of the 13th Step. `@`And then somebody somewhere told me the name of Izanami, Lord of the Underworld. `@`I liked it, so from that day forth I made that name mine. `@`...Although Izanami was apparantly originally a woman's name? `@`Can you believe it? Ku hah hah hah!!"`\

;　イザナミはそう話しながらも、決して、足を止めることはない。@
`　Even while Izanami carried on this conversation, his legs didn't stop.`@
;　ずかずか、ずかずかと息も乱さずに足早で歩き続ける。@
`　Thump thump, thump thump -- he continued to walk at his quick pace without letting out a single breath.`@
br
;　私は、まるで友達と鬼ごっこでもしているかのように、下駄箱の周りをぐるぐる回って逃げる。\
`　Almost like the games of demon tag I used to play with my friends, I was running in circles around the shoe racks.`\

bg black,23
bg shoukou_03,23
ld r,AYA_D5a,23
ld r,AYA_D6a,80

;「わ、……私、何か、あんたに狙われるようなことしたっ？！@　何で私がこんな目に……！」\
`"I... Did I do something to you to deserve this? `@`Why are you after me....!"`\

bg black,23
bg shoukou_02,23
ld l,IZA_D3,23
ld l,IZA_D6,80

;「踏んだだろうがァ。@俺の１３階段をよォ…！！@　お前はしっかりと数えて上ってたはずだぜ？@　忘れたとは言わさねェ！！@　１３階段は、言うなれば俺の釣り針よォ。@俺の大好物な、クソ落ち目のガキに踏ませて、俺の世界に引き摺り込むんだ…！！@　踏んじまったお前はもう俺の獲物よォ！@　泣いても喚いても、誰も助けちゃくれねェぜェ！！」\
`"You stepped on it, fool. `@`My 13th step!! `@`You counted it out clearly as you went up, didn't you? `@`I'm not gonna let you forget it!! `@`The 13th step is my fish hook, so to speak. `@`When my favorite prey, you deadbeats, step on it, then you're whisked off to my world! `@`You stepped on it, so you're my prey nowww! `@`Cry and scream all your like, no one is gonna save youuu!!"`\

;　やっぱり、１３階段の怪談は本当だったんだ。@
`　As I thought, the tale of the 13th step was real.`@
;　１３階段を踏んでしまったら、死神に獲物にされ、どこまでも追い掛けられるのだ。@
`　After stepping on the 13th step, you become prey of the shinigami, and he'll chase you no matter how far you run.`@
br
;　誰も助けてくれない。@出来るのは走って逃げることだけ。@それも、学校の外へは逃げられない。@
`　No one will save me. `@`All I can do is run. `@`Furthermore, I can't even run away from school.`@
;　捕まったら地獄行きの、死神との鬼ごっこなのだ。\
`　If he catches me, I'm bound for hell, like a game of demon tag.`\

bg black,23

;　……死にたいと願ったことはある。@
`　...I once prayed for death.`@
br
;　イザナミに捕まれば、それを叶えてもらえる。\
`　If Izanami catches me, he can grant my wish.`\

;　しかし、私が望む死とは、安らかな眠りのことだ。@
`　But the kind of death I want is in a peaceful sleep.`@
;　あんなおぞましい世界で、肉の塊にされて、永遠に嬲られるような世界に落ちることじゃない。@
`　I don't want to fall into that disgusting world and turn into a pile of flesh -- tormented eternally.`@
br
;　私の求める死は、あんたが与えようとしてる死とは、まったく違うもの…！！\
`　The death I desire is completely different than the death you want to give me...!`\

bg rouka_04,23

fede 1,1000
E_B

;　その時。@
`　Suddenly.`@
br
;　イザナミの肩越しに、時計が見えた。@
`　I saw the clock above Izanami's shoulders.`@
;　その長針と短針が頂点で重なり、０時を刻んだ。\
`　The long hand and short hand needles of the clock aligned, and the time was 12 o'clock.`\

fede 0,1000
E_A

;■チャイム

se3v 66,100
se1v 69,100
wait 200
se2v 69,85
;wait 200
;se3v 69,70

;　そして、チャイムが鳴り響いた。@
`　Then the bell sounded.`@
br
;　いつも聞いているチャイムと同じ音だったけれど、@まるで学校中の壁の中から染み出しているかのような、そんな凄みのあるチャイムだった。\
`　It sounded just like the usual school bell, `@`but the bell called as if it were oozing from the middle of the school walls.`\

se3 22
bg white,48

;　その途端、世界が真っ白な光で溢れ出し、眩しくて目を開けていられなくなる。\
`　In that moment, the world was enveloped in a white light, and in its radiance I couldn't open my eyes.`\

;　何？@　何事？！@
`　What? `@`What's happening?!`@
br
;　目がぐるぐると回り、気持ち悪くなって、立っていられない。@
`　I felt dizzy, queezy, and I couldn't remain standing.`@
;　遊園地のメリーゴーランドやコーヒーカップで感じるような眩暈。\
`　It was vertigo like going on the merry-go-round or coffee cup rides at an amusement park.`\


;　……駄目……、意識が……、……………………。@
`　...Oh no... I can't think straight... .........`@
br
;　………………………。\
`　.........`\

textoff
bg black,2
wait 3000

me1v 5,50

bg mansion_01,42

;　遠くから聞こえてくる風の音が、……町の喧騒であると気付くまでの間、@私はずっと頭を抱えてしゃがみ込んでいた。\
`　While I began to hear the sound of wind in the distance, ...seemingly amonst the clamor of the middle of town, `@`I had been crouched and holding my head for the longest time.`\

;　遠くで車の走る音。@どこかの家の換気扇の音。@自転車のベルの音や、走り回る子供の笑い声。@
`　The sound of cars in the distance. `@`The hum of a ventalation fan from someone's house. `@`The sound of bicycle bells and the laughter of children playing.`@
br
;　……恐る恐る目を開くと……。\
`　...Fearfully, carefully, I open my eyes and...`\

ld c,AYA_D6a,2

wait 1000

ld c,AYA_D9a,22

;「ここ…………、家…………………。」@
`"I'm... home........."`@
br
;　私は、いつの間にか自分のマンションの玄関前にいて、しゃがみ込んでいたのだ。\
`　Somehow I was crouching outside my family's apartment.`\

;　恐る恐る周りを見渡す。@
`　Fearfully, carefully, I look over my surroundings.`@
br
;　……あの恐ろしい死神の姿はない。\
`　...That terrifying shinigami isn't showing himself.`\

;ld c,AYA_D5a,80
cl c,22

;　これは、一体……、どういうこと………？@
`　Just... what does this mean...?`@
;　私はいつの間にかここにいて、しゃがみ込んでおかしな白昼夢を見ていたというのだろうか。@
`　Suddenly I'm here as if I had been daydreaming while squatting like that.`@
br
;　……………………。@
`　.........`@
;　……そんなはず、ない。\
`　...That can't be.`\

;　なぜなら私は、……昇降口でずっとぐるぐる逃げ回っていたから、@……疲れて、未だに息が乱れている。@
`　Because I... I had been running around the school entrance for ages, `@`... I'm still tired, and my breathing is still erratic.`@ 
br
;　体も汗でびっしょり。@足の関節も痛み、@ついさっきまで間違いなく自分が走り回っていたことを教えてくれた……。\
`　My body is even drenched in sweat. `@`The joints in my legs ache, `@`so I was absolutely sure until moments ago I assured myself I had been running away just moments ago...`\


bg black,22

;　何が何やらわからない。@
`　I have no idea what's going on.`@
;　あれは夢だったのだろうか…？@
`　Could that have been a dream...?`@
br
;　そんなわけはない。@でも、一つ確かなことがある。@
`　That's not possible. `@`Yet, I'm sure of one thing.`@
;　あの死神から、私は逃げ延びたということだ……。\
`　I had escaped from that shinigami...`\

bg ie_04,2

;　その晩。@私はまた夢を見た。@
`　That night. `@`I saw another dream.`@
;　今度は、これが夢の中であるということを、はっきりと自覚できた。@
`　This time I was clearly aware that I was inside a dream.`@
br
;　その夢の中で、……イザナミは再び、語り掛けてきた。@
`　In that dream, ...Izanami once again came to speak to me.`@
;　まるで讃えるように、両手を叩きながら。\
`　As if praising me, he clapped his hands together.`\

bg black,22
;bg rouka_02,0
ld c,IZA_D3,2

wait 1000

ld c,IZA_D6,80

bgm1 23

;「今日は逃げ延びたな。@だが、まだまだお楽しみは終わらねェ。@明日もたっぷりと楽しませてもらうからなァ。@何しろ俺は、クソ落ち目なヤツが、@汗だくになって逃げ回るのを追い詰めるのが、何より楽しいんだからよォ！@　くっひっひっひ！！@　楽しいゲームの幕開けだァ…！！」\
`"You got away today. `@`But the fun ain't over yet! `@`Let's have lots of fun tomorrow. `@`After all, there's nothing I love more in this world than chasing and catching you hopeless losers when you're dripping in sweat! `@`Ku hi hi hi hi!! `@`The curtains rise on our fun and games!!"`\

;「ゲーム……。@これはゲームだって言うの……。」\
`"Games... `@`Are you calling these games...?"`\

cl c,0
ld r,IZA_D5,23

;「あぁ、そうだ。@これは命を賭けたゲームってわけだ！@　そしてゲームだから、ルールもある。」@
`"That's right. `@`In these games, your life is at stake! `@`Because these are games, there are also rules."`@
br
;　ルールって？@
`　Rules?`@`
;　そう思った瞬間、@イザナミはにやりと笑い、口に出していないはずのその問いに答える。\
`　The moment I thought of it, `@`Izanami grinned as if he heard my thoughts even though I said nothing at all.`\

ld r,IZA_D3,80

;「ゲームを楽しむための、お約束ってわけさ。@まず。@俺は走らねェ。@どんなに早歩きをしようとも、絶対に走らねェ。@何しろ、俺が本気で走ったら、すぐにお前らを捕まえられちまうんだからなァ。@俺が大好きなのは、お前らが必死こいて逃げ惑って浮かべる苦悶の表情なんだ。@だから、お前ら子供の足でも逃げる余地があるように、@俺は絶対に走らねェんだ。」\
`"Basically I've made a few rules so that our game is enjoyable. `@`First off. `@`I won't run. `@`No matter how fast I walk, I'll never run. `@`After all, if I really ran, I could catch you all right away. `@`What I really love, you see, is seeing the anguish on your faces as you punks run for your lives. `@`So to ensure that even your shorter child-like legs can run from me, `@`I'll never run after you."`\

;　確かにそうだった。@
` That was certainly true.`@
br
;　イザナミはずっと早足だった。@決して走りはしなかった。@
` Izanami always walked briskly `@`...but he never ran.`@
br
;　大人の足だから、早足でも油断は出来ない。@
` Because he has adult legs, even though he's just walking quickly, you can't let your guard down.`@
;　でも、走って逃げれば、決して追い付かれることはない。@そんな速度だった。\
` But if he ran,`@` there was no way to avoid being caught in the end. `@`He was just that fast.`\
ld r,IZA_D2,80

;「そして、もう一つ、約束するぜ。@俺がお前の命を奪うのは、お前を捕まえた時だけだ。@お前が俺から逃げ続ける限り、命は奪わねェでやる。@呪いだとか事故だとか病気だとか。@そんなわけのわかんねェことでは殺さねェってわけだ。@……つまり。@お前が生きるか死ぬかは、お前の足だけにかかってるってェわけだ。」\
`"Just one more thing I'll promise you. `@`The only time I'll snatch your life away is when I catch you. `@`As long as you keep running from me, I'll let you live. `@`Curses, accidents, illness. `@`Basically, I'm not gonna kill you in some unknown way like that. `@`...In other words, whether you live or die, `@`depends on those little legs of yours."`\

;「に、……逃げ続ける限り、私は殺されない……。」\
`"As, ...as long as I continue to run away, I won't be killed..."`\
cl r,0
ld c,IZA_D5,24

;「そういうこった。@まァ、いつ根を上げるか、見物ってことだぜ。@くっくくくくく！」@
`"Exactly. `@`Well, it's quite the sight you see, when they give up the ghost - that is. `@`Ku kukukukuku!"`@
;「…………………………。」\
`".........."`\
;ld c,IZA_D6,80

bg Aka2,22

me2v 17,70

;「いいかァ。@俺は夢じゃねェ。@現実だ。@俺をしっかりと見てろ。@目を逸らすな。@生き延びたかったら、死に物狂いで逃げまくって、お前の悪足掻きを見せてみろ。@……大概のヤツは、最後にはおかしくなって、@これは夢だなんて言い出して、自ら逃げるのを止めちまう。@それじゃあ、面白くねェ！@　お前は、俺という現実を、しっかりと受け容れて、楽しませてくれよ！@　くっひっひっひ！」\
`"Listen here. `@`I ain't a dream. `@`I'm real. `@`Now get a good look at me. `@`Don't you dare look away. `@`If you want to live, run for your life, and let me watch you struggle helplessly. `@`...In the end my prey usually starts acting strange, `@`they start saying it's a dream, and then they go and stop running. `@`That ain't fun! `@`Get it through your head that I'm REAL, and let me have my fun!` @`Ku hi hi hi hi!"`\

;　わかってる。@これは夢の中だけれど、……夢じゃない。@
` I understand. `@`This is inside a dream... but not a dream.`@
br
;　イザナミが夢の中に現れて、私に語りかけているのだ。\
` Izanami has appeared in my dream and is talking to me.`\

ld c,IZA_D8,22

;「言っておくが。@もし、俺から逃げるために学校を休んだら。@即座にゲームはおしまいで、お前を地獄送りにしちまうからな。@俺のゲームから逃げることは許さねェ！@　お前は毎日、自らの足で俺を楽しませるために学校へ通うんだ。@せいぜい風邪を引かねェように気をつけるこったなァ…！@　くっくくくく、ひっひゃっひゃっひゃっひゃ！！！」\
`"I'll say one thing. `@`If you stop going to school to get away from me. `@`I'll whisk you away to hell and the game ends immediately. `@`I won't forgive cowards that run from my game! `@`You're gonna go to school every day and be my entertainment with those little legs of yours. `@`So you better be sure not to get a cold, 'kay?! `@`Ku kukukukuku, Hi hyahyahyahyahya!!!"`\

bg black,2
;bg gakkou_01,22

;　命懸けの、死神との鬼ごっこは、その日から毎日繰り広げられることとなった。@
` It was decided that a deadly game of tag would unfold with the shinigami every day from then on.`@
br
;　初日こそ、初めてということもあって混乱したが、@二日目は、多少の覚悟があったので、わずかに冷静でいられた。\
` On the first day, since it was the first time, I was confused.`@`On the second day, I had little preparation, and kept my cool only slightly.`\
bg kyou_02u,22

wait 2000

bg kyou_01,23

;　イザナミとのゲームは、帰りのホームルームが終わると同時に始まる。\
` The game with Izanami begins at the same time class ends.`\
ld c,IZA_D3,22

wait 1000

se1v 2,100
ld c,IZA_D6,1

;「さぁ、俺とのゲームの時間だぜェ、あやちゃんよォ！！」@
`"Well, it's time to play with me, Aya-chan!!"`@
br
;　そこは、校舎という巨大な密室。@ここから出る方法はない。@
` There, behind the closed doors of the school, `@`there was no way to get out.`@
;　この異世界から解放されるまで、とにかく、ひたすらに死神から逃げ回る他ない。\
` At any rate, until he let me go from that alternate reality, I had no other choice but to run away from the shinigami.`\
bg black,23

;　確かに、イザナミはルールの通り、決して走りはしない。@
` Indeed, as a rule, Izanami never ran.`@
;　早足で追っては来るが、決して走らない。@
` He always walked briskly but never ran.`@
br
;　だから、落ち着いて走れば、その分、逃げて距離を開くことが出来る。\
` So if I stay calm and run, I can make quite some distance between us.`\

;　恐らく、チャイムが鳴るまで逃げ切れば勝ちなのだ。@
` I'd likely win if I kept away until the chime rang.`@
br
;　そしてそのチャイムは１２時を指すと鳴り響く。\
` Of course, I'm referring to the chime that rings at 12.`\
bg rouka_04,22

;　……昨日は１１時５５分から始まったが、今日は１１時５０分から始まった。@
` Yesterday the game started at 11:55 yesterday, but it started at 11:50 today.`@
br
;　つまり、１０分間、イザナミから逃げ延びればいいわけだ。\
` In other words, if I can run from Izanami for 10 minutes, I'll be okay.`\
;　逃げ場はないから、ゴールはない。@
` Since there's no where to run to, there's no goal to reach.`@
br
;　つまり、校内をぐるぐるとずっと走り回っているしかない。\
` Basically, the only thing I can do is run around the school in circles over and over.`\
bg rouka_01,23
wait 500
bg black,26
bg kaidan_02,22

;　１階の廊下を走り抜け、２階へ上がり、呼吸を整える。@
` I run through the corridor on the first floor, up to the second floor and took a breath.`@
;　イザナミが階段の下にやって来たのを見届けてから、２階の廊下を走り抜ける。\
` After reassuring myself that Izanami was at the bottom of the staircase, I ran through the second floor corridor.`\
bg black,24
bg rouka_03,24

;　そして、その先の階段を下りて、再び、イザナミが階段に辿り着くのを待ち、呼吸を整える。\
` Then I go down the stairs at the other side of the hall, and while I wait again for Izanami to draw nearer, I take a breath.`\
bg black,23
bg kaidan_02,23
wait 500
bg black,23
bg rouka_02,23

;　そして再び１階の廊下を駆け抜け、階段を上り……、を延々とチャイムが鳴るまで続ければいいのだ。@
` Then I go to the first floor corridor again, and climb the staircase... As long as I keep repeating this endlessly until the chime rings I should be okay.`@
br
;　そんなシンプルな鬼ごっこであることを理解すると、さらに冷静さを取り戻すことが出来た。\
` Once I understood how it was a simple game of demon tag, I was able to pull myself together.`\
;　……確かに、捕まれば恐ろしい地獄が待っている。@
` ...Of course, hell awaited me if I got caught.`@
;　しかし、捕まらないようにすることは、決して難しいことじゃない。@
` But it was easy to not get caught.`@
br
;　ただこうしてぐるぐると、同じ廊下をずっと走り続けていればいいだけだ。\
` Just going round and round these stairs and running through the same hallways over and over was good enough.`@
bg black,23
bg rouka_03,23

;　それも、がむしゃらに全速力で走る必要はない。@
` On top of that, there wasn't a need to run with everything I had either.`@
;　ジョギングのように軽く走って逃げては、近付いてくるまで休んで、それから走るの繰り返し。@
` I could run lightly, like jogging, and then rest until he got too close, and then go back to running again.`@
;　それを、じっと心を落ち着けて、ほんの１０分間、繰り返すだけ………。@
` With that in mind, I can keep my cool, and I only have to keep running like this for ten minutes...`@
br
;　そう、心の中で何度も呟き、これは難しいことではないんだと、自分に信じ込ませようとする。\
` Right, and I sought to convince myself by thinking that in my mind over and over again -- that this wasn't that hard at all.`\
bg black,22

;　……信じ込ませようと？@
` ...But could I convince myself?`@
br
;　ちょっと走っては休み。@ちょっと走っては休み。@……それだけの繰り返しじゃないか。@それの何が、難しいことなんだ…？\
` Run a little, rest a little. `@`Run a little, rest a little. `@`I mean, all I had to do was keep doing that over and over? `@`Just what's difficult about that...?`\
　……………本当は、わかってる。@
` ......But I knew the truth.`@
br
;　小休止を挟めるとはいえ、……１０分間、走り続けるというのは、やはり疲れることなのだ。\
` However many breaks I take to catch my breath... running for ten minutes is really exhausting.`\
bg kaidan_01,22
ld c,AYA_D7a,24
ld c,AYA_D8a,80

;　……転ぶかもしれないし、万一、足を挫くようなことでもあれば、一巻の終わりだ。@
` I might fall down or sprain my foot, and if that happens, that'll be the end of the line for me.`@
br
;　それを意識すればするほど、階段を駆け下りる時、@慎重に下りたい気持ちと、駆け下りたい気持ちがせめぎ合ってぎこちなくなるのを感じた。\
`　The more I ran down the stairs, the more I thought. `@`I felt conflicting feelings between my desire to run fast and my desire to run with care.`\

;　これは簡単なことなんだと信じ込もうとする心も、@１分１分経つ毎にメッキが剥げ、心が焦ってくる。\
` No matter how much I reassure myself that this is easy, `@`with each passing minute I lose my cool and my heart beats faster.`\
ld c,AYA_D7a,80

;　もっともっと、遠くまで早く逃げた方がいいのではないか。@
` Perhaps I should run really, really far away?`@
br
;　いやいや、そんな焦って走って怪我でもしたらおしまいだ。@もっと冷静にゆっくりと走ればいいのではないか。\
` No no no, that's not right. `@`If I ran like that, what if I injured myself? `@`Then it'd be the end for me. `@`Maybe running calmly and pacing myself would be better?`\
;　それに加え、@どうしてこんな広大な学校の中で、自分だけが死神に狙われ、@こんな目に遭わなければならないのかという、@悔しさにも似た憤りも覚えた。\
` Not only that, `@`I could not think why, out of everyone in this huge school, the shinigami would be after me. `@`I felt something like pain and even regret, `@`that I had to meet such a horrible fate.`\
bg black,23
bg rouka_02,23
wait 500
ld c,IZA_D5,22
ld c,IZA_D6,80

;　様々な感情で頭がごっちゃになる。@少しでも休み過ぎると、あっという間にイザナミは近付いてくる。\
` My head is astir with all sorts of emotions. `@`Whenever I rest a just a little, Izanami quickly gets closer.`\
bg black,23
bg rouka_04,23

;　途中、教室の時計をちらりと見た。@
` Half way around, I glanced at the clock in the classroom.`@
br
;　あと１分。@大丈夫。@問題なく逃げ切れる。@
` Just one more minute. `@`I'll be okay. `@`I can escape without any problems.`@
;　体力も充分。@混乱もしてない。@……生き延びた。\
` I still had strength in me. `@`My mind was in order. `@`...I survived...`\
;se1 33

;　そう思った途端、……忘れていた、ある違和感と恐怖が蘇る。@
` As soon as I thought so, ...I had forgotten. A sense of fear and discomfort was reborn.`@
br
;　それは、昨日は１１時５５分から始まったのに、今日は１１時５０分から始まったということ。\
` I remembered that the game began at 11:55 yesterday, and today it began at 11:50.`\
mbg black,22

;　……たかが５分。@されど５分。@
` ...It's only five minutes. `@`Five more minutes.`@
br
;　まさか、………毎日、チャイムがなるまでの時間が延びていくのではないだろうか。\
` That couldn't mean that the time time until the bell rang would increase everyday... could it?`\
;　ほんの１０分間、駆け回っただけで、これだけ疲れているのだ。@
` I just had to run around for ten minutes, but I'm this tired already.`@
br
;　もしも、毎日時間が少しずつ延長していき、……やがては、１時間や２時間にも至ったら。@
` If the time extends little by little each day....eventually it'll reach one or two hours longer.`@
;　………それは恐ろしい想像だった。\
` ...That was a terrible thought.`\
mcbg 22

;　そして、時計は０時を指す。@
` Then, the clock strikes twelve.`@
br
se3v 66,100
se1v 69,100
wait 200
se2v 69,85

;　校舎中に鳴り響くチャイムの音。\
` The sound of chimes ringing in the schoolhouse.`\
bg black,24
bg rouka_03,0
ld c,IZA_D2,24
ld c,IZA_D3,80

;「とりあえず今日も、お前の勝ちのようだなァ。@くっひっひ…！！@　明日も楽しみにしてるぜェ？@　せいぜい、よくマッサージでもしておくんだなァ。@筋肉痛で走れねェなんて、興醒めにも程があるぜェ…！！@/
`"I guess that means you win today too. `@`Ku hi hi...!! `@`Look forward to tomorrow, 'kaay? `@`You should do some deep massaging. `@`There's a limit, and being unable to run because of pain in your legs is such a killjoy...!!`@/ 

se3v 84,100

;　ひっひゃっひゃっひゃっひゃ！！！」@
` "Hi hya hya hya hya hya!!!"`@
br
;　イザナミの笑い声と眩しい光で、全てが飲み込まれて消えていく……。\
` And with Izanami's laughter, everything was swallowed in a bright light and then began to disappear...`\
se1 22

bg white,48

fede 0,2000
E_A
wait 1000

me1v 16,50

bg mansion_01,2

;　我に返った時。@そこは昨日と同じに、自宅のあるマンションの前だった……。\
` Then I returned to myself. `@`I was in front my apartment, the same as yesterday,...`\

;■あやの自室

bg black,22

;　……これが夢であると。@信じることが出来たなら。@
` ...This is a dream. `@`I couldn't help but believe that.`@
br
;　しかし、イザナミが夢の中で言ったように。@……これは現実なのだ。@
` However, just as Izanami said in the dream, `@`...this is reality.`@
;　恐らくは、明日も明後日も、帰りのホームルームが終わる度に、@あの異世界で死神と命懸けの鬼ごっこをすることになるのだ。\
` Tomorrow, and probably the day after that, each time class ends, `@`in that seperate dimension, with my life at stake, that's when my game of demon tag against that shinigami begins.`\
fede 0,1000
E_A

bg ie_04,22

me1v 35,50

;　……横になって天井を見上げる。\
` ...I lay down and look up at the ceiling.`\
;　生きていることに意味を見出せず、死を願ったことが何度もあった。@
` Unable to see the meaning of living, I wanted to die so many times.`@
;　しかし、少なくともあの死神の与える死は、@私が望んでいたものとは余りに程遠い、恐ろしくおぞましいものだった。@
` However, the death that shinigami offered me, was far from the gracious death I wanted. `@`I was given a horrible, hideous fate.`@
br
;　それが嫌だから、私は逃げ延び、生き延びた。\
` I don't want that, so I escaped, and I continue living.`\
;　生き延びた…？@
` I continue to live...?`@
;　生きることに、何の価値も見出せないのに…？@
` Living, even though I can't see any point in it...?`@
br
;　………………………。\
` ...........`\
bg black,22
mono 1
bg rouka_03,0
ld c,IZA_D6,22

;　ほんの数分間とはいえ、死神との死闘を生き延びて得た、……生の一瞬。@
` Although it only lasted a few minutes, that life or death struggle with the Shinigami made me feel, for a moment... alive.`@ 
br
;　しかし、その一瞬には、何の意味もない。\
` But that moment had no meaning.`\
;　私には、死神のゲームを勝ち抜いても、何の喜びもなければ、何も得るものなどない。@
` Even if I survive the shinigami's game, I can't enjoy my victory - and I get nothing from it.`@
br
;　ただ、あの地獄だけは嫌で、逃げ延びただけ。@
` It was just that I didn't want to fall into that hell, and I just had to escape.`@
;　……罰ゲームだけあって、何のご褒美もないゲームというわけだ。\
` ...It was a punishment game, but a punishment game without any reward.`\
bg black,22
mono 0

;　つまり、……何の意味もないゲーム。@
` In other words...a game without any meaning.`@
;　もし、あの地獄を予め見せられていなかったなら、@私はきっと初日に、自ら進んで命を投げ出しただろう。@
` If, he hadn't shown that hell to me previously, `@`I'd have thrown away my life of my own volition on the first day.`@
br
;　………………………。\
` ...........`\
bg Different_spiral_1a,22

;　生きることにも価値がなく。@
` There is no value in living.`@
br
;　死ぬことにも価値がない。\
` Neither is there value in death.`\
;　結局。@……死神との放課後のゲームも、無意味、……無価値。@
` In the end.`@` ...even this game with the shinigami, it's meaningless... worthless.`@
br
;　ただ、あの地獄を拒否するためだけに、……校内を延々と走り回らせられる、苦行。@
` However, just to deny myself that hell... I run around the school - against my own will.`@
;　それを、いつまでもいつまでも永遠に。\
` I'll have to do that, forever and ever, eternally.`\
bg black,22

;bg aka1,0
;ld c,AYA_D5a,22

mono 1
bg kaidan_03,22


;　……１３階段を踏んだ時点で。@私はもう地獄にいるのだ、多分。@
`　...The moment I stepped on the 13th step. `@`I was already in hell, probably.`@
br
;　あのおぞましい胃袋の地獄と、校内を走り回らせられる地獄。@
`　That disgusting hell stomach and the hell of being forced to run around the school.`@

;　その２つのどちらかを、選ばされているだけなのだ。\
`　I could only choose between the two of them.`\

;ld c,AYA_D7a,80

;　……私は、いつまであの地獄のゲームを続けさせられるのだろう。@
`　...I wonder if I'll always have to keep playing that game from hell forever.`@
br
;　ゲームなら、終わりやゴールがあるべきではないのか。\
`　Since it's a game, shouldn't it have an end or a goal or something?`\

;ld c,AYA_D4a,80

bg black,22
mono 0

;　私の生には、確かに価値はないだろう。@
`　My life definitely has no meaning.`@
br
;　でも、望む形での死を求める権利は、私にだってあるはず。\
`　Still, I still want to have the right to choose how I die.`\

bg ie_04,22

;　いつか解けるように眠るように死ぬために、………今を生きる。@
`　For now I live... so that someday, I can die in my sleep and melt away.`@
br
;　死ぬために、生きる。@
`　I live to die.`@
br
;　……それも、何とも無意味なことに思えた。\
`　...Even that, too, seemed meaningless.`\

bg black,2
fede 0,2000
E_A
wait 2000



bg rouka_04,22

bgm1 15

;　それから、放課後のゲームは学校がある限り、毎日続いた。@
`　From then on, as long as I had school those afterschool games continued every day.`@
;　毎日、少しずつ、逃げ延びるための時間は増えていった。@
`　Every day, little by little, the time I needed to keep running away increased.`@
br
;　たまに気紛れに減る日もあったが、それは一日毎の誤差の範囲。@
`　Once in a while there were days when the time would decrease on a whim, but each time it seemed like a calculation error.`@
;　日々、着実にその時間ノルマは延び続けていった……。\
`　Every day, that time quota steadily continued to grow...`\

bg black,23
bg rouka_02,0
ld c,AYA_D6a,23

;　１階と２階の廊下を、とにかくぐるぐる走り続けるだけ。@
`　Regardless, I just had to keep running circles around the first and second floor hallways.`@
;　それをチャイムが鳴るまでひたすらに繰り返す。@
`　I would keep repeat that only until the chime sounds.`@
br
;　泣こうが喚こうが、それしか生き残る方法はない。\
`　Although I cried and screamed, running was all I could do to keep myself alive.`\

bg black,23
bg rouka_01,23

;　だからこそ、心を殺して、ただ黙々と走っては休み、また走った。@
`　That's why I steeled my emotions, silently I just ran, rested, and ran again.`@
br
;　１週間を超えた頃には、体育の時間に匹敵するくらいに走り回らされるようになっていた。\
`　After one week had passed, I had to run around almost as long as my P.E. period.`\

;　……もう、体がぎりぎりの限界だった。@
`　...Unfortuantely, my body was just about at its limit.`@
br
;　全身、汗だくで、肺も心臓も爆発しそう。@
`　My whole body covers in sweat, my lungs and heart seem full to burst.`@ 
;　最後は、脇腹を押さえながら、よろめくようにしか走れなかった。\
`　In the end, I could only run in a staggered stance while holding my side.`\

bg black,2

;　………まだまだ、時間は延びるだろう。@
`　...My time would probably keep growing and growing.`@
;　やがては１時間、……いや、それ以上を走らされるに違いない。@
`　Then it'll finally be an hour, ...no, no doubt I'll be made to run even longer than that.`@
br
;　不可能だ。@そんなにも走り続けていられるものか。@
`　It's impossible. `@`Does he really expect me to keep running like that?`@
;　このまま時間が延々と延び続ければ、………やがて絶対、……私は殺される。\
`　If time kept getting longer, longer still, and growing like this, ...then in the end without a doubt... I'll be killed.`\

bg black,2

fede 0,2000
E_A
se1 69
wait 2000

;■校舎裏～さくのしんの祠
bg gakkou_02,2

me1v 24,50
wait 2000

bg kyou_04,2

;　それは、以前、聞いたある噂だった。@
`　That was before I heard that rumor.`@
br
;　どこかのクラスに、霊感少女がいる、というのだ。@
`　The rumor that in some class there was a girl with a sixth sense.`@
;　その子は幽霊や妖怪に詳しく、特に学校の八不思議にも精通しているという話だった。\
`　They said that girl was familiar with spirits and youkai, and that she was well versed on the School's Eight Mysteries.`\

;　……もちろん、いい加減な尾ひれが付いてるだろう。@
`　...Naturally, it seemed they were probably exaggerating.`@
;　聞いた当時も、馬鹿馬鹿しいとしか思わなかった。@
`　Even when I heard it, I couldn't help but think it was foolish.`@
br
;　しかし、今となっては違う。@……溺れる者は藁をも掴むという言葉の意味が、今はひしひしとわかった。\
`　However, now things are different. `@`...I now knew all too well the meaning of the phrase 'a drowning man will even grab at straw'.`\

bg black,22

fede 0,1000
E_A

bg gakkou_03,22
wait 1000
bg black,22
bg hokora_02,22

bgm1 8

;　少女の名前は、桜田みちる。@
`　The girl's name is Michiru Sakurada.`@
br
;　彼女のクラスで聞いたら、昼休みにはここにいることが多いと言われた……。\
`　After asking in her class, they said she's often here during lunch break...`\

;　校舎裏の、茂みの陰にひっそりとある、小さな祠。@
`　Behind the school, hidden in the shade of the bushes, at the small shinto shrine.`@
br
;　その前にしゃがみ込み、何かぶつぶつと独り言を言いながら祠を撫でている眼帯の少女こそ、@……噂の桜田みちるに違いなかった。\
`　Crouched in front of it, that girl with an eyepatch muttered something to herself as she gently stroked the shrine. `@`...Just as the rumors had said, it was without a doubt, Michiru Sakurada.`\

;　……１３階段を踏み、毎日、放課後に、死神と追いかけっこをしていると言って、@信じてくれるだろうか。@
`　...If I tell her that I stepped on the 13th step and that every day a shinigami chases me after school, `@`would she believe me, I wonder?`@
;　そして何より。@……自分が助かる方法を、彼女が知っているだろうか。@教えてくれるだろうか。@
`　Nevertheless. `@`...Could she know a way to save me? `@`Could she tell me?`@
br
;　……祈るような気持ちで、私は彼女に話し掛けた。\
`　...With that prayer in mind, I started to talk to her.`\

ld c,MIC_D1,26
ld c,MIC_D2,80

;「………１３階段の死神？@　知ってる。@学校妖怪序列第２位、１３階段の死神、イザナミだよ。」@
`"...Shinigami of the 13th Step? `@`I know him. `@`That's The Second Ranked School Youkai, Shinigami of the 13th Step, Izanami."`@

ld l,AYA_D7a,23
ld l,AYA_D8a,80

;「そ、そう、それ。@……そのイザナミって死神に、……私が狙われてるって言ったら、@………信じてくれる……？」\
`"Y- Yeah, him. `@`...If I said that shinigami called Izanami was... targeting me, `@`...would you believe me...?"`\

cl c,0
ld r,MIC_D1,23

;「……………………………。」@
`"............"`@
br
;　桜田みちるは、……眼帯の向こうに隠されているという霊眼で、私をじっと見ているようだった。\
`　It seemed like.... Michiru Sakurada was staring a me intently... with her spirit eye hidden on the otherside of her eyepatch.`\

ld l,AYA_D4a,80

;　私はごくりと唾を飲み込んで、彼女が何かを口にしてくれるのを待った。@
`　I swallowed my saliva with a gulp, and I waited for her to say something.`@
br
;　しかし、彼女は沈黙したまま。@
`　However, she remained silent.`@
;　それどころか、私に関心がないかのように、そっぽを向いてしまった。\
`　As if somehow she didn't trust me, she finally looked the other way.`\

cl r,22

cl l,0
ld c,AYA_D5a,23

;「……ちょっと、桜田さん。@私の話を聞いてるの……？」@
`"...Wait, Sakurada-san. `@`Are you listening to me...?"`@

ld r,MIC_D3,22

;「静かに。@今、さくのしんさまとお話しているよ。」@
`"Certainly. `@`Right now I'm talking to Sakunoshin-sama."`@

cl c,0
ld l,AYA_D7a,24

;「ん、……んん……。」\
`"Hm, ...mmm..."`\

;　どうやら彼女は、祠の主に話し掛けているらしかった。@
`　It was almost as if she were conversing with the spirit of the shrine.`@
;　普段の自分ならどん引きするところだが、今はそういうわけには行かない。@
`　I would normally think she was pulling my leg, but right now I didn't have a choice.`@
;　……彼女が祠の主と会話を終えるのを待つしかなかった。\
`　...I just had to wait for her to finish her conversation with the spirit of the shrine.`@

bg black,22

fede 0,1000
E_A

bg hokora_01,22
bgm1 18
ld l,MIC_D3,26


;「………厄介だね。@さくのしんさまが言うには、イザナミは、かなり強力な学校妖怪らしい。」@
`"...You're in trouble. `@`Sakunoshin-sama tells me that Izanami seems to be an extremely powerful school youkai."`@

ld r,AYA_D4a,24

;「そのイザナミって死神が、……毎日、放課後に、……私を追い掛け回すの。」\
`"That shinigami, Izanami... he chases me around every day after school..."`\

ld l,MIC_D1,80

;「……１３階段を踏んでしまったんだね。」@
`"...You stepped on the 13th step then."`@

ld r,AYA_D7a,80

;「う、……うん……。」\
`"Y- ...Yeah..."`\

ld l,MIC_D2,80

;「１３階段はイザナミの呪いの刻印。@……獲物に決めた犠牲者にそれを踏ませ、@執拗に追い回して、地獄へ連れ去る……。」\
`"The 13th step is the seal of Izanami's curse. `@`...He causes his selected prey to step on it, `@`chases them around relentlessly, and drags them to hell..."`\
ld r,AYA_D8a,80

;「そうよ……。@……私はもう、何日も何日も、毎日、……放課後になると追い掛け回されてるの。@……お願いっ。@死にたくないの。@どうやったら助かるのか教えてっ。」\
`"That's right... `@`...I've already, for days and days on end, every day.... after class ends he chases me and runs me around. `@`...Pleeeease. `@`I don't want to die. `@`Please tell me how to save myself."`\

cl l,22

;「…………………………。」@
`"............"`@
br
;　彼女は再び祠の方を向き、その主と会話する。@
`　She once again turns towards the shrine and talks with the spirit.`@
;　そして、私の顔をじろりと見て、……答えた。\
`　Then she looked me straight in the face... and replied.`\

ld l,MIC_D3,22
ld l,MIC_D4,80

;「………イザナミの呪いは、四十九日、続くんだって。」@
`"...Izanami's curse lasts for fourty-nine days."`@

ld r,AYA_D5a,80

;「し、四十九日って、４９日間？！@　……って、な、７週間……？！」@
`"F- Fourty nine?! 49 days?! `@`...That means, s- seven weeks...?!"`@
br
;　私は仰天する。@いや、頭が真っ白になるのを感じた。\
`　The thought horrified me. `@`My mind went blank.`\

bg black,22
bg Different_spiral_1b,22

;　あの死神から解放されるには、……約２ヶ月もの間、毎日、逃げ続けなければならないのだ。@
`　To escape from that shinigami, I would have to run every single day... for almost two months.`@
br
;　それも、ただの２ヶ月じゃない。@
`　And that wasn't a regular two months.`@
br
;　毎日、少しずつ逃げる時間が延びている２ヶ月だ。\
`　Every day of those two months my running time would increase little by little.`\

;　今でさえ、もう体育の時間くらい走らされてる。@
`　Even now, I had to run for about as long as the amount of time I had for P.E.`@
br
;　このまま、さらにどんどんと時間が延びたら。@……最後には、１時間どころか、２時間、あるいは３時間、それ以上にもなるかもしれない。\
`　At this rate, if my time keeps getting longer and longer. `@`...In the end, it won't just be one hour, two hours, or three hours, it might be even longer than that.`\

bg black,22
bg hokora_02,0
ld l,AYA_D8a,22

;「そ、………そんなに……………。」@
`"T- ...That long......"`@

;ld r,MIC_D1,24
ld r,MIC_D3,22

;「イザナミの呪いから逃れるには、それしか方法はないって。@……お気の毒だよ。」\
`"That's the only way to escape from Izanami's curse. `@`..I'm so sorry for you."`\

ld l,AYA_D5a,80


;「じょ、除霊とか御守りとか！@　何かもっとその、呪いを払うような何かはないの？！@　イザナミを倒せるような何かはないの？！」\
`"E- exorcism or talismans! `@`Don't you have something that can, well, lessen the curse?! `@`Something to help me defeat Izanami?!"`\

ld r,MIC_D5,80

;「………イザナミは学校妖怪序列第２位の強力な妖怪。@……倒せる力を持つ妖怪は、第１位の校長先生しかいない。@……でも、かつての校長先生ならともかく、@今は老いて、狩りはずいぶん前に引退してる。@……だから、イザナミを倒せる学校妖怪は、存在しないんだよ。」\
`"...Izanami is the second strongest ranked school youkai. `@`...The only youkai strong enough to defeat him is the first ranked. `@`...Although he used to once be the headmaster, `@`now he's old, and has mostly withdrawn from hunting. `@`...So I would say no youkai that can defeat Izanami exists."`\

bg black,22

;　彼女が何を言っているのかさっぱりだ。@
`　I was clueless as to what she was talking about.`@
;　しかし、言いたいことはわかる。@
`　However, I realized what she wanted to say.`@
br
;　それしかないのだ。@
`　That was all I could do.`@
;　私が解放されるには、……４９日間、逃げ延びるしかないのだ。@
`　My only escape... is to keep running... for 49 days.`@
;　それ以外に、どんなインチキもズルも存在しない……。\
`　There was no way to cheat or wiggle my way out of it...`\

bg hokora_01,24
ld r,AYA_D6n,24

;「……私、………こ、……殺されるよ………。@あ、あんな地獄、落ちたくないよ…！！」@
`"...I... I'm gonna be killed... `@`I- I don't want to fall into that kind of hell...!!"`@

ld l,MIC_D1,23
ld l,MIC_D3,80

;「ご愁傷さまだよ。@……気の毒だけれど、私には何も出来ない。」\
`"My condolences. `@`...I'm so sorry, however, I cannot do anything."`\

cl r,0
ld c,AYA_D5a,24
quakex 1,100

;「た、助けてよッ！！@　あなただけなの！！@　他に頼れる人がいないの！！」\
`"S- Save meee!! `@`You're all there is!! `@`No one else can help me!!"`\

ld l,MIC_D5,80

;「……何か助かる方法があるなら、@私だって、さくのしんさまだって、教えたいと思ってるよ。@……でも、何もない。@だから、私だって辛いんだよ……。」@
`"...If there was a way to save you, `@`then I think myself or Sakunoshin-sama would tell you. `@`...However, there isn't one. `@`It hurts me to say it......"`@
br
;　私はしばらくの間、やり場のない怒りを胸の奥に押し込みながら、@ぐっと両手を握り締めて俯くことしか出来なかった……。\
`　For a time, a rage with nowhere to go welled up in my chest, `@`and all I could do was clench my fists tightly and hang my head...`\

bg black,2
bg hokora_02,0
ld c,MIC_D3,22

;「………さくのしんさまが言うには、@……過去には、イザナミの呪いから逃れることが出来た人間もいたって。」@
`"...Sakunoshin-sama says, `@`...there is a person who has escaped Izanami's curse in the past."`@
br
;　生還者がいた……？@
`　There was a survivor...?`@
;　それは、この絶望の暗闇にあっては、一条の光のようにさえ感じられた。\
`　That idea felt like a single ray of light in my darkness of despair.`\

ld c,MIC_D1,80

;「その人はずいぶん前に卒業してるそうで、名前も住所もわからない。@……でも、確かに逃れた人間はいたって。」\
`"He says that person seems to have graduated a long time ago, so he doesn't know their name or address. `@`...However, he says that there was definitely a person who escaped."`\

;　その人間は何者だろう。@
`　I wonder who that person is.`@
br
;　数時間を見事に走りきった、強健なアスリートなのだろうか。@
`　Perhaps they were some kind of extremely healthy athelete to be able to perform such a feat like running for so long.`@ 
;　……だとしたらお手上げだ。@私如き、ひ弱な小娘には、逆立ちしたって真似が出来ない。\
`　...If that's the case, it's just skill. `@`For a delicate little girl like myself, I can't even do a handstand.`\

bg black,22

;　でも、………そうとは限らない。@
`　But... it wasn't just that.`@
;　いや、むしろ、ひ弱な犠牲者の可能性の方が高いのではないだろうか。\
`　No, rather, perhaps that person was more likely to be the weak victim type.`\

;bg black,22
mono 1
bg rouka_02,0
ld c,IZA_D8,22

;　イザナミは言っていた。@自分は、クソ落ち目なヤツが大好物なのだと。@
`　Izanami had said it. `@`That losers are his favorite food.`@
;　健全なアスリートが獲物にされたとは到底思えない。@
`　I can't think he would make a healthy athlete his prey.`@
br
;　あのイザナミのことだ。@私のような、いつも俯いている無気力な少年少女を獲物としたはずだ。\
`　That Izanami. `@`He probably always makes downtrodden apathetic school girls like me into his prey.`\

bg black,22
mono 0

;　………なら。@数時間にもわたって、走り続ける体力があったとは、到底思えない。@
` However, `@`I hardly think I have the energy to run over a few hours.`@
;　何か、生き残るための秘密、秘訣、@……もしくは裏技のようなものがあるのではないだろうか。@
` Were there any secrets or tricks for survival?`@
br
;　それを聞きたい。\
` I wanted to hear them.`\
;　しかし、その人物はすでに卒業し、名前も住所もわからないという。@それを聞くことは叶わない………。@
` But that person had already graduated, and I knew not the name nor address. `@`I'd never hear such tips...`@
br
;　絶望する私に、桜田みちるはぽつりと言った。\
` Sakurada Michiru whispered to me as I despaired.`\
bg hokora_02,0
ld c,MIC_D2,22

;「……あなただけじゃないよ。@……男の子が１人、……今、イザナミの呪いに遭ってる。」\
`"It's not just you...`@`... A boy is also now caught in Izanami's curse."`\
ld l,AYA_D4a,23

;「男の子………？」@
`"A boy....?"`@
cl c,0
ld r,MIC_D1,23

;「うん。@さくのしんさまが言うには、つい最近、イザナミの呪いに遭って苦しんでる男の子がいるって。」\
`"Yeah. `@`Sakunoshin was talking about it recently. He said there's a boy who's suffering Izanami's curse."`\
ld l,AYA_D7a,80

;「それは……、どこの子？@　今もいるの？」@
`"Who is he? `@`...is he still around?"`@
ld r,MIC_D2,80

;「うん。@クラスと名前もわかるよ。」\
`"Yes. `@`I know his name and class"`\
bg white,2

bg black,24
bg kyou_04,24

fede 0,1000
E_A

me1v 24,50

;　私は、教えてもらったクラスに飛んで行った。@
` I flew to the class where he was taught.`@
br
;　……そこは、上級生のクラスだった。@
` ....this room was for upperclassmen.`@
;　もう一人の犠牲者、大里先輩は、そのクラスにいた。@
` The other victim, Osato-san was in there.`@
br
;　クラスメートが指差す先には、机に突っ伏して昼寝する、小太りの男子の姿があった……。\
` The classmates pointed at his plump figure, asleep with his head on the desk...`\
bg black,24
bg kyou_02,24

;　彼は居眠りではなく、本気で眠っているようだった。@
` Not just dozing, but sleeping in earnest.`@
br
;　……彼がいつからイザナミの呪いに取り込まれているかはわからないが、@私より長いなら、毎日、相当の時間を走り回らされているはずだ。@
` ...I have no idea how long he's been caught in Izanami's curse, `@`but if it's been longer than I have, then he's been forced to run around that much longer every single day.`@
;　疲労困憊で眠っているとしても、納得できた。\
` I was convinced he was asleep from exhaustion.`\

;　彼は酷く不機嫌に目を覚ましたが、私がイザナミの名を出すと、身を乗り出して立ち上がった。\
` He woke up crossly, but leaned forward when I said Izanami's name.`\

bg black,2

fede 0,1000
E_A

bg kaidan_03,22

bgm1 6

;「……昨日は、１０時半から始まった……。@もう……、限界だ………。」@
`"Tomorrow I start from 10:30... `@`I can't do this anymore..."`@
br
;　彼は私より早くから呪われているらしい。@イザナミから逃げる時間は、すでに１時間を超えていた。\
` It seemed he had been cursed earlier than I had. `@`The amount of time he had to run from Izanami had already reached over 1 hour.`\
;「……もう、……限界だ……。@来る日も来る日も……、ずっとずっと廊下を……。@昨日は、あと少しで追い付かれるところでチャイムだった。@……もう、……次は無理だ……。」@
`"...I'm already at my limit... `@`Day after day... always running in the corridors.`@`... yesterday, he was only a hair's breadth away from catching me when the chime sounded`@`... Next time, I'm done for...."`@
br
;　彼は頭をばりばりと掻き毟って俯いた。@
` He looked down and scratched his head roughly.`@
;　そんな彼に、４９日間、逃げ切れば助かると教えたところで、@さらなる絶望を重ねることにしかならなかった……。\
` He was told that if he escaped for 49 days, he'd be saved, `@`but that only added to his hopelessness....`\
se1 12
quakey 1,100

;「冗談じゃねぇよ……。@４９日も逃げ切れるわけねぇよ……。@………俺は死神に魅入られた時点で、もう死んだも同然だったんだ。@……どうせあの地獄に落ちるなら、@……とっとと観念すれば、余計に苦しむことはなかったんだ……。」\
`"This isn't funny... `@`There's no way that I can keep running away for 49 days...`@`.... I'm being haunted by a reaper, I'm already as good as dead.`@`... Eventually I will fall into that hell `@`....by doing this I'm only adding to my suffering. I should just give up now....`\

ld r,AYA_D4a,24

;「……あ、あと何日を残してるか知らないけれど…。@一緒に頑張ろうよ……。」\
`"...I...I don't know how many days are left, `@`but let's do our best..."`\
;「マジで言ってんのか？@　お前マジで言ってんのか？！@　来る日も来る日も！！@　しかもどんどん時間が延びていって！！@　もう嫌だ、限界だッ！！@　こんなの……、耐えられねぇ…！！！」\
`"Are you being serious? `@`You can't really be serious? `@`It just keeps going, day after day!! `@`And every day the time gets longer!! `@`I give up, I'm at my limit!! `@`I just can't.... take it anymore...!!!"`\

ld r,AYA_D2,80

;「………………………。」\
`"..........."`\
;「……どーせ、……俺なんて、勉強も出来ねぇし、取り得なんか何もねぇ。@……生きてたって何の意味もないクズなんだ……。@クズはクズらしく淘汰されろっていう、神様の思し召しなんだ。@……俺みたいなクズは、生まれてきた時点でもう、何かの間違いなんだ…。@……でもよぉ、そんなのあんまりだろぉよぉ……。@ぅおぉおおおぉおぉ……、ひっく、えっぐ……！！」\
`"...Besides... I'm bad at studying, and I don't have any redeeming features.`@`... Even if I survive I'm still just worthless trash.... `@`Trash will be weeded out like the trash it is, all because god wills it.`@`... It was a mistake for trash like me to even be born...`@`... It's just too much for me to handle.... 。`@`uOOOOooOO... hic, guh...!!"`\
;　とうとう、人目もはばからず泣き出してしまう。@
` Finally, he started crying out loud, not caring who heard.`@ 
br
;　私にとって、……彼は、本当に儚くて小さいけれど、………希望なのだ。@
` For me, ...he was a small, faint hope.`@
;　彼が４９日間を生き延びてくれれば、……私にだってきっと出来るという希望になる。\
` If he could survive for 49 days, I'm sure I could as well.`\
cl r,0
ld c,AYA_D8a,24

;「が、……頑張ろうよ。@……あいつは決して走らない。@確かに速いけれど、絶対に走らない…。@……確かに、１時間も２時間もずっと走っているのはものすごく大変だと思う。@……でも、それで自分の命が救えるなら、走るくらい何でもない……。」\
`"Still... hang in there.`@`... He won't ever run. `@`He may be fast, but he'll never outright run...`@`... Of course, running for 1 or 2 hours straight is incredibly difficult, I know. `@`But if you're doing it to save your own life, running for that long is nothing..."`\

;　世の中には、不治の病で自分に出来る努力は何もなく、@ただ天命に任せる他ない人だって大勢いる。@
` In this world there are many people who find themselves powerless in the face of an incurable disease. `@`Unable to save themselves, they have no choice but to let fate decide.`@
br
;　それに比べたら、どんなに苦しくとも、自分の努力で何とか出来る試練など、@まだ恵まれているはず……。\
` Compared to that, no matter how painful the trial, if you're given a a chance to overcome it by your own power, `@`that is a blessing in itself ...`\
quakey 1,100

;「毎日、毎日、何時間も走り続けるなんて、不可能だよ…！！@　そんなの出来るわけねぇ…！！@　第一、そこまで必死に走って走って生き延びて！@　その先に何が待ってるってんだよぉ？！」\
`"Running for that many hours, day in and day out, it's impossible...! `@`It just can't be done...! `@`I'd run and run, frantically trying to survive! `@`But what's waiting for me in the end? What's it all worth?!"`\

ld c,AYA_D7a,80

;「い、……生き延びることが出来るよ。」\
`Y-... You can survive.`\
;「だから！@　生き延びて、俺の人生に何の意味があるって言うんだよぉ？！@　勉強も出来ない、運動も出来ない！@　友達もいない、趣味なんか何もない！！@　毎日毎日、退屈で死にそうだった。@いやむしろ、死にたいとさえ思ってたさ…！！」\
`"I'm asking you! `@`What's the point of me suriving?! `@`I can't study, I can't exercise! `@`I have no friends, I have no hobbies! `@`Every day I felt like I'd die from boredom.`@`No, I wanted to die..!!"`\
bg black,22

;　雪が解けるように、眠るように死にたい。@
` Wanting to die as if falling asleep, or melting away like snow.`@
;　……彼の願望も、私と同じだった。@
` ...His desire was the same as mine.`@
br
;　いや、彼は私とまったく同じだったのだ。\
` No, everything about him was the same as me.`\
;　彼にとっても、人生は無意味であり、無価値だった。@
` For him, life was meaningless, worthless.`@
br
;　そんな彼にとって、４９日間もの試練を生き延びる価値など、何もない……。\
` To him, there was no point in surviving this ordeal for 49 days...`\
bg kaidan_04,22

me1v 5,70

;「生き延びたら、何かもらえるのかよ？！@　１００万円くれるのか？！@　願いでも叶えてくれるのか？！@　じゃあ、ドッジボールで強くなれるようにしてくれよ！@　漫画１００冊買ってくれよ！！@　……何もねぇ！！！@　仮に生き延びたって、また何もねぇ、退屈で死にそうな灰色の日々じゃねぇかよ…！！@　……終わってたんだよッ、最初っから俺の人生は…！！@　生まれてくるんじゃなかった……。@生まれてくるんじゃ……、なかっ……、ひっく、ぅぐぐぐ………。」\
`"Do I get something special if I survive?! `@` Will I get a million yen?! `@`Will I be granted one wish?! `@`If so, then make me a great dodgeball player! `@`Buy me 100 manga volumes!! `@`...No, I get nothing!!! `@`Even if I survive I'll get nothing! I'll just go back to my bland life and want to die from boredom...! `@`....My life was over from the very beginning...!! `@`I wish I was never born.... `@`I wish I'd never been b... hic... borrrn, g- gahh..."`\
;　もう最後は嗚咽しか聞こえなかった。@
` I could only hear sobbing in the end.`@
;　彼はもう、自暴自棄になっていた。@体力以上に、気力がもう限界なのだ。@
` He had become desperate. `@`Rather than physical strength, it was his willpower that had failed.`@
;　そして、彼の気持ちはそのまま、私の気持ちを代弁していた。@
` And his feelings resonated with mine.`@
br
;　……生き延びて、取り戻す日常に何の価値があるのか。\
` ...was there any worth in surviving and going back to normal life?`\
bg black,22

;　ない。@……無意味で無価値な、灰色の世界。@
` No.`@`...it was a meaningless worthless world. `@`A gray world.`@
br
;　あの、おぞましい地獄に落ちることだけは嫌だから、逃げ回ってはいるけれど。@その先に待つかつての日常には、彩りも輝きもない……。\
` The only reason we keep running around is to keep from falling into that gruesome hell. `@`All that awaits us should we succeed is the same bleak life we had before.`\
ld r,AYA_D2,22

;　何か得るもののために戦うなら、意味は見出せる。@
` If we were fighting to attain something, we would be able to find meaning in it.`@
br
;　しかし、何も得るものがなく、@……どうせいつか迎える破綻を、わずかに先延ばしするだけの苦行に、@私たちは一体、何の意味を見出せるというのだろう…？\
` But, there is nothing to fight for.`@`... We torture ourselves by putting off the inevitable, knowing that eventually we will have to accept failure. `@`What is the point to it all...?`\
bg kaidan_04,0
;ld r,AYA_D4a,22
ld r,AYA_D2,22

;　彼の言葉は、私の胸に抉るように突き刺さるのだ……。\
` His words pierced my chest as if gouging it...`\
;bg black,22

;「……俺もお前も、@……１３階段を踏んじまった時点で、……あいつの地獄に引き摺り込まれちまったんだ……。@あいつ、言ってるだろ？@　俺たちクズが必死な形相で逃げ回ってるのを見るのが楽しいって。@……あいつは俺たちを追い回して追い回して……。@さんざん楽しんだ後、結局は地獄に突き落とす、最悪の死神なんだ……。」\
`"...You and I `@`...the moment we stepped on that 13th stair... we were dragged into his hell... `@`He said so, right? `@`He loves to watch trash like us run around in desperation.`@`... To chase us around and around... `@`And after he's had his fun, he will throw us into hell. He's the worst kind of shinigami..."`\
cl r,0
mld r,AYA_D4a,22

;「………………………………。」\
`"............."`\
;「そりゃあよ、……あんな恐ろしい地獄、落ちたくはねぇよ。@……幸い、今日は水曜日だしな…。@今日は何とかなるだろうが、……もう次は無理だ。@……へへ、……へへへ……。@まぁ、……まぁ、今日まで生き延びた価値は、ちっとはあったかな……。@……お仲間に出会えて、愚痴を吐き出せて……、少しだけすっきりしたぜ……。@へへ、……へへへへへ………。@あんたも、……せいぜい足掻きな。@……自分が納得するまで。@………同じ地獄でも、納得するまで足掻いてからなら、……まだ、……マシかもしれねぇさ……。@……へへへへ………へへ………。」\
`"You know... I really don't want to go to that terrifying hell.`@`...Fortunately, since today is Wednesday...`@` I'll manage to survive somehow or another... but next time around, I'm doomed.`@`... heh... heh, heh... `@` Oh well, at least there was some point until surviving until today... `@`Since I was able to meet someone else who was cursed, and vent my frustrations... I feel kind of refreshed... `@`heh... heh heh heh... `@` You... are going to struggle too, you know? `@`...Until you can accept it. `@`You'll struggle until you realize that you'll be going to the same hell that I am, but... hey, I guess that's better than nothing...`@`...heheheh... heh..."`\
;mld r,AYA_D2,80

;　彼は達観したような、あるいは自嘲的な薄笑いを浮かべ、無理に笑っていた。@
` He was laughing forcibly, with a philosophical, almost self-mocking smile.`@
br
;　………彼に対し、掛ける言葉が、何も思い付かない。\
` ...Words to describe it didn't come to mind.`\
mcl r,0
bg black,22

;　これが、イザナミがそうであると称するように、本当にゲームなら。@
` If this really was a game like Izanami said,`@
;　ペナルティに対し、それに見合う褒美があってもいいはずだ。\
` then in exchange for a penalty for losing, there should be a corresponding reward for winning.`\
;　しかし、おぞましいペナルティがあるだけで、……生き延びることに、何の価値もない。@
` But there was just a very harsh punishment... there was no worth in surviving.`@
br
;　……そしてあいつは、そんな何の価値もない、クソ落ち目な人間が大好物で……。@
` ...And he liked those kinds of downtrodden, worthless humans. They were his favorite food...`@
br
;　………………………………。\
` ...........`\
fedexx 0,50,0,0,0,0,2000
E_B

se1 69

bg kaidan_02,22

;mld r,AYA_D4a,80

;　昼休みが終わるチャイムが鳴り響く。\
` The chimes signaling the end of lunch ring.`\
;　……私は彼に、明日か明後日にはもう会えないかもしれない。@
` ...I might not be able to meet him again tomorrow or the day after,`@
br
;　彼の顔には、……多分、死相と呼ぶべきに違いないものが、浮かんでいたから。\
` since I saw in his face what could only be called the mark of death.`\
;bg black,22
ld r,AYA_D7a,22

;　…………私もやがては、彼のように疲れきり、あの地獄を受け容れるようになるのだろうか。@
` ...I, now as tired as he was, started to embrace that hell.`@
br
;　………………………。\
` ............`\
;mld r,AYA_D7a,80

bg black,22

;　嫌だ……。@あんな恐ろしい地獄に、……絶対に落ちたくなんかない。@
` No... `@`I'd never want to fall into that horrible hell.`@
br
;　そう思うのは、私にまだ体力と気力があるからだろう。@
` The reason I can still think that way must be because I still have some strength and willpower left in me.`@
br
;　これから１週間後、２週間後に、彼の境地に至らないという保証は、どこにもなかった。\
` There's no guarantee that in one or two weeks I won't end up being just as hopeless as he is.`\
bg kaidan_04,22

;　別れ際に、……ふと気になることを思い出し、それを彼への最後の質問とした。\
` When I was turning to leave the classroom... I suddenly remembered what had been worrying me, and stopped to ask him one final question.`\
fede 0,1000
E_A

ld r,AYA_D8a,24

;「……さっき、@/
`"Earlier...`@/
bgm1 14
;……今日は水曜日だから何とかなるかも、って言いましたよね……？」@
`... you mentioned that since it's Wednesday, somehow you'll manage, right...?"`@
br
;　確かに言った。@今日は水曜日だしな、今日は何とかなるだろうがと、確かに言った。\
` I'm that's what I heard him say. `@`That since today is Wednesday he would somehow manage to surive. That's definitely what he said. `\
;「あ、……あぁ。@……理由はわからねぇが。@……どういうわけか、月曜と水曜と土曜は、少しだけ時間が短いんだ。@……逆に、火曜と木曜と金曜は長い。@昨日は火曜だから最悪だった。@……今日は水曜だから多少マシだが、……その次は木曜だ。@……もう、俺は助からねぇ……。」\
`"Ah... yeah.`@`... I don't know why... `@`but for some reason, on Mondays, Wednesdays and Saturdays, the amount of time I have to run is shorter.`@`.. but on the other hand, Tuesdays, Thursdays and Fridays are longer. `@`Yesterday was Tuesday, so it was the worst.`@`... Today is Wednesday so it's not as bad... but then it's going to be Thursday.`@`.... I'm not going to make it..."`\
;cl r,0
;ld r,AYA_D4a,80

bg black,22

mono 1
bg rouka_04,22

;　確かに、私の１週間も、少しその感じはしていた。@
` In my one week of running, I had also started to notice that pattern.`@
br
;　全体的に見れば、少しずつ日々のノルマは伸びている。@
` All in all, the daily quota is growing little by little.`@
;　しかし、確かに前日より時間が短い日はあった。\
` But there were some days that were shorter than the one before.`\

;　……しかし、彼の言う曜日とは合わない気がする。@
` ...But, the days of the week he mentioned felt off.`@
br
;　彼が言うには、昨日の火曜は、長いらしい。@
` According to him, it was yesterday, Tuesday, that felt long.`@
;　しかし、私にとっての昨日は、前日より短かった。\
` But for me, yesterday felt shorter than the previous day.`\
;ld r,AYA_D7a,80

bg black,22
mono 0

;　……私は、たまに短くなる日は、イザナミの気紛れか何かだと思っていた。@
` ....I originally thought that Izanami decided when a day would be shorter entirely on a whim.`@
;　しかし、彼が言うには、その短くなる日は曜日で決まっているという。@
` But, according to this boy, the short days were determined based on what day of the week it was.`@
br
;　その曜日が、なぜか彼と食い違う。\
` If that's the case, for some reason my short days were not the same as his.`\ 
;cl r,0
;bg black,22
bg Different_spiral_1b,22

me1v 19,70

;　必ず決まった曜日に短くなるという法則性がありながら、@……なぜか私と彼で、その曜日が異なるという不思議。@
` If there's a rule that dictates which days are shorter...`@` then it's odd that those days differ between us.`@
br
;　………どうせ死神の気紛れ。@考えるだけ時間の無駄だろうか。\
` ....I have to assume it's just on the whim of that shinigami. `@`Thinking about it is a waste of my precious time.`\
;　私は彼と違い、……まだまだ気力がある。@
` The difference between that boy and I... is that I still have the willpower left to fight.`@
;　あの地獄にだけは絶対に落ちたくないという、心の強さがある。@
` I the only reason I still have that determination is because I never want to fall into that hell.`@
br
;　……その強さがある内に、……何かの、必勝法のようなものを見つけ出す必要がある。\
` ...While I still have that strength... I need to find some way to ensure my survival.`\
;　イザナミは、クソ落ち目なガキが大好物。@
` Izanami's favorite prey is downtrodden, worthless kids.`@
;　かつての生還者だって、私と大差ない子だったに違いないのだ。@
` Even that former survivor must have been child no different than I am now.`@
br
;　その子は生還した。@……数時間を毎日、走り回ったとは到底思えない。@
` It was a child that survived.`@`... So I find it hard to believe that they ran around for hours on end every day.`@
;　うまくやり過ごしたりする、何らかの裏技がきっとあったのだ。\
` To get by, they surely had some tricks.`\
bg black,22

fede 10,1000
E_MA

bg kaidan_03,0
ld c,AYA_D7a,22

;　彼と私の、曜日の違い。@
` The days differed between him and I.`@
br
;　ここに、何かの秘密が隠されているに違いないと、@……私の中の、まだ死にたくないという気力が囁いていた。\
` There must be some sort of secret hidden in that fact...`@` that is what the determination in my heart whispered to me.`\
textoff

ld c,AYA_D7,22
wait 1000

cl c,22
bg black,42
fede 0,2000
E_A
wait 2000

bgm1v 23,0

fedexx 30,0,0,0,0,0,2500
fedexx 70,0,0,0,0,0,2500

bg kyou_02u,42

ld l,IZA_D5,2
;ld r,AYA_D8a,22

se1v 2,100
ld l,IZA_D6,80

;「へっへへへへ！！@　さぁ、あやちゃァん！！@　今日もぜぇぜぇしながら、汗だくで逃げ回る姿で楽しませてくれやァ…！！」\
`"Hahahahaha!! `@`Come on, Aya-chan!! `@`Let me see you gasping for air, drenched in sweat! Let me have my fun today too...!!"`\
ld r,AYA_D7a,22

;「……………………。」\
`".........."`\
cl r,23

;wait 1000
cl l,0
ld c,IZA_D5,23

;「さァ、走れや走れェ！！@　頭カラッポにして、チャイムまでひたすらに走り回れやァ！！@　くっひゃっひゃっひゃあァ！！」\
`"Come on, run, run!! `@`Empty your head and mindlessly run around until the bell rings!! `@`Kyahahahaha!!"`\
bg black,2
bg rouka_04,22


;　彼は水曜は短いと言っていた。@でも、やはり、私の水曜は違う。@時計の針は、昨日よりも遠退いていた。@
` He said that Wednesdays were shorter. `@`But, just like I thought, that wasn't the case for me. `@`The clock hands were further apart than they were yesterday.`@
br
;　……今日も１時間たっぷり、校内を駆け回ることになる。\
` ...Today I will be racing around the school halls for a full hour.`\
;　生き延びて何かをしたいなんて、前向きな気持ちは何もない。@
` I wasn't looking forward to survivng at all.`@
br
;　あるのは、あの地獄だけはごめんだという、後ろ向きな気持ちだけ。\
` All I wanted was to be spared a trip to hell.`\
bg black,23
bg rouka_02,23

;　……そんなこと考えるだけ、体力の無駄遣いだ。@
` ....Just thinking about such things was a waste of stamina.`@
br
;　イザナミの言う通り、……頭をカラッポにして、ひたすらに走り続けるのが最善なのだ。\
` It was just like Izanami said... The best things I can do is just empty my mind and run.`\
;　１時間は、運動の苦手な私には、すでに限界にも等しい時間だ。@
` For someone as unathletic as me, one hour was already my limit.`@
br
;　昨日までの私ならば、絶望に潰されそうになっていただろう。\
` If the events of today had no happened, I would probably be giving into despair right now.`\
ld c,AYA_D6a,24
ld c,AYA_D8a,80

;　……しかし、今は少しだけ違う。@
` ...But now it's a little different.`@
br
;　曜日に隠された秘密。@……それに気付けば、……ひょっとしたら、生き延びることが出来るかもしれないという希望がある。\
` I have some hope.`@`... there must be some secret or clue hidden in the days of the week... If I can find it, I might be able to survive.`\
cl c,23
bg black,23

wait 1000

bg rouka_03,2
ld r,IZA_D2,22

;「お前もよく頑張ったなァ。@……でもよォ、もう限界だろォ？」@
`"You're doing well.`@`... but you can't last much longer, can you?"`@

ld l,AYA_D7a,23

;「…………………………。」\
`"..........."`\
ld r,IZA_D5,80

;「そんなに死が怖ェのかァ？@　かつては死にたがりだったくせによォ。@……まァ、あんな地獄を見せられちゃァ、気が変わるのも無理はねェがなァ。@くっくくくく！！@　そうまでして、どうして生きたい？@　生きてたって、どうせただぼんやりと寝惚けて過ごすだけだろォが。」\
`"Does death really scare you that much? `@`Weren't you practically begging to die before?`@`.... Well, I guess if anyone was shown a glimpse of that hell, there's no way they'd still want to die. `@`Kuhahaha!! `@`Still, why are you trying so hard to survive? `@`Even if you do, you'll just return to wasting your life away in a half-awake daze."`\
;ld l,AYA_D7a,80
cl l,24

;「………………………。」@
`"..........."`@
br
;　挑発するかのように、イザナミは私を嘲笑い続ける。\
` As if trying to provoke me, Izanami keeps ridiculing me.`\
;ld l,AYA_D8a,80
;wait 500
;cl l,24
;wait 1000

cl r,0
ld c,IZA_D5,24

bg black,22
bg rouka_02,22

;　……どうして生きたいのかとか。@生きる意味とか価値とか、……考えたいこと、問い掛けたいこと、色々ある。@
` ...Why I want to live. `@`What meaning or worth there is in life... There are many things that I want to think about. Many things I want to ponder.`@
br
;　でも、汗だくになって走り回っていると、そんなことを考えている暇さえない。@
` But I wasn't free to think about such things while running around and dripping sweat.`@
;　あいつの戯言に耳を貸してる余裕なんて、私にはないのだ。\
` I don't have the leisure to listen to his nonsense.`\
bg black,23
bg rouka_01,23

me1v 17,70

;　ただ走って、ヤツが追い付くまでを休みに徹して、呼吸を整えて、……また走る。@
` I can only run, rest until he catches up, take a deep breath... and start running again.`@
;　それをチャイムが鳴るまで、ただひたすらに延々と繰り返す。@
` Until the bell chimes, I just repeat this pattern again and again.`@
br
;　汗だくになって、心臓が破裂するかと思うほどになるまで。\
` Repeat it until I'm sweating buckets and worried that my heart might explode.`\
bg black,22

;　………無我の境地で、ただひたすらに駆け回る内に、@その日はチャイムを向かえることが出来た……。\
` ....That day, by rushing around those halls in a sort of trance, `@`I was able to make it until the bell sounded...`\
se3v 66,100
se1v 69,100
wait 200
se2v 69,85
;wait 1000

wait 3000

fede 0,5000

E_B
E_MA

wait 1000

;bg white,48
;bg black,22

bg kyou_04,22

me1v 24,50

;　次の日。@
` The next day.`@
;　大里先輩を訪ねると、…………クラスメートは、そんな生徒はいないと笑った。@
` When I went to visit Osato-senpai..... his classmates laughed at me and said they didn't know anyone like that.`@
br
;　……何となく、わかってた。@
` I understand, more or less.`\
;　彼の存在は、席ごと、なくなっていた。\
` His existence, together with his seat in the classroom, have disappeared.`\
;　これが学校八不思議の、１３階段の死神に呪われた者の、……末路なのだ。\
` This was one of the eight mysteries of the school. The fate of those cursed by the Shinigami of the 13th step.`@
;　唯一の仲間を失い、……私の心が絶望に押し潰されそうになる。@
` It felt like... my heart was being crushed in despair at the loss my sole companion.`@
br
;　彼があの、胃袋の地獄でこれから永遠に苦しむことを思うと、恐怖に全身が凍り付きそうだった。\
` To think that he'd suffer in that stomach-like hell for all eternity... my whole body froze in terror at the notion of it.`\
se1v 11,30
quakex 2,100

;　教室の前で俯いていると、……上級生の女子に、どんと肩をぶつけられた。\
` I went to leave the classroom, my head hanging low.... Just then, I bumped shoulders with an upperclassman girl.`\
textoff

E_A

ld c,HIG_W3,22
wait 1000
ld c,HIG_D5,22

bgm1 5

;「何で下級生がこんなとこにいるの？@　そんなとこに突っ立ってたら邪魔だわ。@くすくすくすくす…………。」@
`"What's an underclassman like you doing up here? `@`If you're just going to loiter around, you'll only get in the way. `@`Teeheehee...."`@
;＜彼岸花
br
;　……可憐な子だった。@こんな髪が綺麗な女の子に生まれられたら、@さぞや人生が幸せだったろうに。\
`...She was pretty.`@` If I had been born with hair as beautiful as hers, `@`I'm sure I would have had a much better life.`\
cl c,22

;　私の脇を通り過ぎて教室に入った少女は、@壁に貼られている時間割を見て、肩を竦める。\
` The girl walked straight past me into the classroom, `@`looked at the class schedule posted on the wall, and shrugged her shoulders.`\ 
bg black,22
bg kyou_01,22
ld l,HIG_D5,22

;「本当に最低な時間割よね。@……どうして午後を優雅に楽しめる土曜日に体育なんかあるのかしら。」@
`"What a horrible schedule.`@`... Why do we need to have gym on Saturday afternoons? It just ruins my weekend."`@
br
;　……このクラスは、土曜日に体育の授業があるようだった。\
` ...It seems that this class has physical education on Saturdays.`\
ld l,HIG_W3,80

;「私、体育の授業は大嫌いなの。@……だから今日と明日は、多少はマシね。@あぁ、体育なんて、この世から消えてなくならないかしら。@……くすくすくすくす……。」\
`"I absolutely hate gym.`@`... If only our schedule for Saturday was a bit more like today or tomorrow. `@`I wish gym would just disappear from this world.`@`.. teehee..."`\
cl l,2
bg black,22
bg kyou_03,22

;　少女の肩越しに、このクラスの時間割が見える。@
` Looking over the girl's shoulder, I could see the schedule.`@
br
;　確かに、今日と明日、……木曜と金曜は、このクラスには体育の授業がないようだった。\
` Just as she had said, there wasn't P.E. on either today or tomorrow... Thursday and Friday.`\
;　……当然のことだが、……時間割はクラスによって違う。@
` ...It goes without saying... but each class has a different schedule.`@
;　このクラスでは、体育は、月曜と水曜と土曜にある。@
` In this class, P.E. was on Monday, Wednesday and Saturday.`@
br
E_A
;　……………それは、……彼が言っていた、走る時間の短くなる曜日だ。\
` ......These... match the days that he said were shorter.`\
bgm1 18

bg black,22

;　じゃ、じゃあ、私のクラスはどうだろう…？@
` Then... then what about my class...?`@
br
;　つまり………、体育の授業があると、……短くなる……？\
` Could it be... that on days with P.E. the time is shortened...?`\
bg koutei_01,2

me1v 31,50

;　その日の午後は、私のクラスでは体育の時間だった。@
` That afternoon, my class had P.E.`@
;　男子の悪ふざけが過ぎて、先生を怒らせてしまい、@その日は、延々と校庭を走り回らせられることになった。@
` Some boys took their pranks too far, and the teachers got angry, `@`and we were all made to run circles around the schoolyard for the entire time.`@
br
;　放課後のために、少しでも体力を温存しておきたかったのに……。\
` Even though I wanted to preserve as much energy as possible for after school...`\
bg black,22

;　その時は私は大いにぼやいた。@
` I complained the whole time.`@
br
;　しかし、放課後を迎え、イザナミの世界で時計を見上げた時。@……はっきりと確信した。\
` But when the end of the schoolday arrived, I looked up at the clock in Izanami's world, `@`and confirmed my suspicions..`\
fede 10,1000
E_MA

bg rouka_04,22

;「………す、すごく時間が、………減ってる…………。」\
`"....Th-... the time is much shorter..."`\
;　確かに体育のある曜日はいつも、時間が短かった。@
` It was true. On days with P.E. the time decreases.`@
br
;　体育の時には、準備運動のあと、必ず校庭をぐるりと走らされる。@
` During P.E., after a warm-up, we would always run a lap around the schoolyard.`@
;　でも、今日はそれに加え、さらにぐるぐると走り回らされた。@
` But today, on top of that, we were forced to run around in circles for a long, long time.`@
br
;　その分が、大きくチャイムまでの時間を減らしているのだ……。\
` And those minutes I spent running significantly decreased the time until the bell rang.`\
bg black,22
bg kyou_02u,22
ld c,IZA_D3,22
ld c,IZA_D2,80

;「おやおやァ…！！@　どういうわけか、今日はお楽しみの時間がちょいと短めだァ！」@
`"Aya, Ayaa!! `@`Looks like for some reason the time we had to play today got kinda short!"`@
br
;　イザナミはしらばっくれるが、……もう私にはわかってる。\
` Even though Izanami was playing dumb, I already understood.`\

;　そして多分。@……これが、イザナミのゲームの、唯一の必勝法……。@
` This was probably... `@`the only way to win this game of Izanami's.`@
br
;　その日、走っていれば走っているほど。@……イザナミの世界の時間は短くなるのだ。\
` That day, the more I ran... `@`the shorter my time in Izanami's world became.`\
bg black,23
bg kyou_04,23

;　昨日を生き残れた自分なら、時間がずっと短い今日を生き残るのは容易なこと。@
` I survived yesterday, and since the amount of time until the bell is much shorter today, this should be easy for me.`@
br
;　………明日、私のクラスには体育はないが。@もし、私の推理通りなら、@……休み時間などに走り溜めておくことで、@イザナミの世界の時間を軽減できるはず……。\
` .....I don't have P.E. tomorrow. `@`But if I'm correct.... `@`then I should be able to reduce my time in Izanami's world by going running during breaks between classes...`\
ld c,IZA_D3,22

;「……くっひっひっひ。@なァにを思いついたやらァ。@今日のお前は目の光り方が違ってるぜェ？@　気力、いや、希望に満ちてやがる。」\
`"...Kuhehehe. `@`Did ya realize something? `@`Looks like you've got a bit of spark in your eyes today. `@`Is it determination? No, looks like you've got some hope."`\
bg black,23
bg rouka_03,0
ld c,AYA_D8a,23

;「………………………………。」@
`"............"`@
br
;　希望に満ちている。@……確かにそうかもしれない。@
` I'm hopeful.`@`... That might be the case.`@
;　私は、生き残れるかもしれないことに、実感を覚え始めている。\
` For the first time, I feel like I might actually survive.`\
;　これで明日、休み時間に走り溜めて、実際に効果があったなら。@
` If I can gather up some running time during break tomorrow, I can do it.`@
br
;　……私は勝てる。\
`...I can win.`\
;ld c,AYA_D4a,80

cl c,24

;　無謀とも思える、４９日間の戦いを、生き残れるかもしれない。@
` I might be able to survive this 49 day fight. It's a matter of life and death.`@
br
;　全身を、じゅわっとしたものが駆け巡るのを感じた。\
` I could feel my body running with a new vigor.`\
;ld c,AYA_D7,80

bg black,22

;　私はやれる。@生き残れる。@
` I can do it.`@` I can survive.`@
br
;　あいつなんか怖くない。@私は逃げられる。@逃げ延びられる。\
` He's not scary. `@`I can run away. `@`I can make my escape.`\
;bg black,23
bg kyou_04,23

;　……逃げ延びて、何かを私が待っているの…？@
` ....Do I have something to look forward to if I escape?`@
;　その疑問に対する答えは、未だにない。@
` I still didn't have an answer to that question`@
br
;　でも、あのおぞましい地獄から逃れる方法が見つかっただけでも、@今は踊り出したいくらい嬉しい気持ちだった。\
` But I found a way to escape that gruesome hell.`@` I'm so happy right now, I could dance.`\
bg black,23
bg rouka_01,23

;　人生の意味とか価値とか、そんなものを今、考えても、それこそ何の意味も価値もない。@
` Even if I try thinking about the meaning or value in life, there just isn't any.`@
br
;　今はただ、生き残れるかもしれないという単純な喜びが、ただそれだけで嬉しかった。\
` Right now I'm just plenty happy that I have a possibility of surviving.`\
bg black,23
bg rouka_03,23
ld c,IZA_D3,22
ld c,IZA_D6,80

;「ほらほらァ！！@　走れ走れ走れェ！@　下らないこと考えてる暇があったら、汗水垂らして走りやがれ！@　今日は少し短めで許してやるが、明日からはガンガン時間を延ばして、たっぷり走らせてやるからなァ！！@　ひゃっひゃっひゃっひゃ！！」\
`"Come on, come on!! `@`Get runnin'! `@`If ya got time to think about dumb shit, then pick up the pace and start sweatin'! `@`I let ya get off easy today, but startin' tomorrow I'm gonna start kickin' the time length up a notch!! `@`Hyahahaha!!"`\
se3v 66,100
se1v 69,100
wait 200
se2v 69,85

bg white,8
bg black,42

fede 0,2000
E_B
E_MA
;wait 2000

bg okujou_03,22

wait 2000

bg black,22
bg koutei_04,22

me1v 31,50

;　二時間目の終わりの業間休みに、校庭に出るなんて、本当に久し振りのことだった。@
` It's been a while since I last went outside during recess.`@
br
;　体育の授業でもないのに、校庭を走るなんて、……それこそ、生まれて始めての経験だ。\
` It's also the very first time I've ever gone running laps around the schoolyard without being in P.E. class.`\
;　……どれくらい走れば、どれくらいの時間が減るのかはわからない。@
` ...I have no idea how time will be shaved off by my running.`@
;　でも、今ここでたくさん走っておけば、その分、放課後に楽が出来る。@
` But if I run a lot now, I should be able to take it that much easier after school.`@
br
;　何しろ、今ならば、誰も追って来ない。@
` After all, nobody is chasing me right now.`@
;　のんびりと自分のペースで走ることが出来る。@
` I can run leisurely at my own pace.`@
;　疲れたとしても、放課後までに体力を回復できる時間はたっぷりある。\
` Even if I tire, I still have plenty time to recuperate before school ends.`\
bg black,22

;　これが、イザナミのゲームの生き残り法。@
` That is the way to survive Izanami's game.`@
br
;　間違いない。@過去の生還者は、この秘密に気付いたのだ。\
` Without a doubt, `@`the previous survivor must have discoved this secret too.`\
bg koutei_05,22

;　元気な子供たちがボール遊びに夢中になる中。@私はひとり、黙々と校庭を走り続けた。@
` While the other kids are engrossed in their game of dodgeball, `@`I run around the schoolyard in silence.`@
;　業間休みだけでなく、昼休みにも同じく黙々と走り続けた。\
` It wasn't just at recess either. I ran the same way during lunch as well.`\
textoff

ld r,AYA_D6a,23

;「はぁっ、はぁっ、はぁっ…！！」\
`"Haa, haa, haaa!!"`\
ld r,AYA_D7a,80

;　今日は体育の授業はないが、体育で走らされるより、もっと多くを走ったと思う。@
` I didn't have P.E. today, but I think I ran even more today than I normally would in gym class.`@
br
;　…………その成果は、果たして出るのか。\
` .....I wonder if this will really work out as expected.`\
bg black,2

fede 0,1000
E_A

bg kyou_01,22

me1v 24,50

;「下校中には寄り道をしないようにー！@　では日直、号令ー！！」@
`"Make sure you go straight home once you leave school grounds! `@`Whoever's on duty today, please dismiss the class!!"`@
「きりーつ、きょーつけー！！」\
`"Stand! At attention!"`\
ld c,AYA_D7a,26

;　……帰りのホームルーム。@
` ....The final homeroom of the day.`@
;　私はぐっと両手を握り締めて、立ち上がる。\
` I clasped my hands tightly and stood up.`\
;　……私の推理が正しいかどうか、……証明される。@
` ...Whether or not my theory is correct... will be proven now.`@
br
;　お願い……、少しでも時間が減っていて………。\
` Please... decrease the time. Even if it's just a little...`\
E_A

;「「「さよーならー！！！」」」\
`"""BYEEEE~!!"""`\
se1v 2,50
nega 1
print 80
;print 2

bg white,42
nega 0
bg black,1

me1v 16,50

;　……そして、いつものように、放課後のイザナミの世界へ。@
` ...And with that, just like always, I was in Izanami's after-school world.`@
br
;　瞬時に無人となった教室で、私は、ごくりと唾を飲み込んでから、時計を見上げる。\
` In an instant, not a sole remained in the classroom. I gulped and looked up at the clock.`\
bg kyou_02u,22
ld l,AYA_D7a,22

;「…………………………。」\
`"..........."`\
se1v 82,85
wait 1000

ld r,IZA_D1,22

;　がらりと扉を開けて、教室にイザナミが入ってくる。@
` Izanami slams opens the door and bursts into the classroom.`@
br
;　そして時計を見上げ、肩を竦めながら笑った。\
` Looking up at the clock, he shrugged his shoulders and laughed.`\
ld r,IZA_D2,80

E_A
;「くっくっく……。@やれやれ、……気付かれちまったかァ。」@
`"Kukuku...`@`... well, well, well... Looks like you've gone and figured it out."`@
br
bgm1 20
;　時間は、……しっかりと短くなっていた。\
` The time... had definitely become shorter.`\
ld l,AYA_D7,80

;　私の全身を、あのじゅわっとした感触が駆け巡る。@
` That feeling of vigor ran throughout my whole body.`@
br
;　今日一日、かなりを走り、疲れていたはずなのに、……それがすぅっと引いていくのを感じた。\
` Since I was running laps all day, I should be tired... but I felt all of that exhaustion immediately leave me body.
ld r,IZA_D6,80

;「しかし、その努力。@いつまで続けられるかなァ？@　根気も気力もからっきしのお前によォ…！@　時間もまだまだこれから、ガンガン延ばしていくんだからなァ？！@　くっくくくくく！！@　まぁ、いいさァ。@今日も始めようじゃねぇか。@さァ、楽しい放課後の始まりだァ…！！」\
`"But, `@`how long can you keep up that routine I wonder? `@`After all, you ain't got any patience or willpower...! `@`And it's not like I'm just gonna stop incresing the time. In fact, I intend to lengthen it much more! `@`Kukukuku!! `@`Oh well, it don't matter to me. `@`What do you say we start now? `@`Now then, let's start our after school game...!!"`\
cl l,24

wait 1000
ld r,IZA_D5,80
bg black,23
bg rouka_03,23

;　私は廊下に走り出る。@それを見届け、イザナミも廊下に出る。@
` I rushed out into the corridor `@`and Izanami did the same.`@
br
;　……私はしっかりと床を踏みしめ、走り出した。\
` I dug my feet firmly into the ground, and started to run.`\
bg black,2

fedexx 85,0,0,0,0,0,1000

bg koutei_01,22

me1v 31,70

;　私は日々、走り続けた。@
` Every day I continued to run.`@
br
;　休み時間の度に走り、走り走り走りまくった。\
` Every break time I ran my heart out.`\
;　どうやら、予め走った時間は、イザナミの世界ではそれ以上にカウントされているらしい。@
` And it seemed that whatever amount of time I ran in advance, that counted for even more time in Inzanami's world.`@
;　つまり、予め、走っておけば走っておくほど、有利だということだ。@
` Thus, the more I ran in advance the more of an an advantage I had.`@
br
;　とにかく走った。@チャイムと同時に教室を飛び出し。@給食を終えると同時に教室を飛び出した。\
` I was always running. `@`As soon as the bell rang, I would dash out the classroom. `@`The moment I finished eating lunch, I would start running.`\
bg black,22
bg kyou_01,22

;　……そういえば、最近は給食を残さなくなった。@
` Now that I mention it.... recently I've been finishing my whole lunch.`@
br
;　何しろ、毎日毎日、走りまくっているのだから、お腹が空く。@
` After all, I was running every day so I've been hungry.`@
;　家での食事も残さなくなった気がする。\
` I think the same goes for my meals at home too.`\
bg black,22

E_MA

bg ie_04,22

;　不眠気味で、何度も寝返りをうっていたはずの夜も、@最近は灯りを消すと同時に、布団に沈み込むかのように眠れるようになった。@
` And even though I used to used to toss and turn at night, and struggle with insomnia, `@`recently, as soon as I shut off the lights I would immediately sink into my futon and fall asleep.`@
br
;　何しろ、毎日毎日、走りまくっているのだから、疲れてよく眠れるのは当然だ。\
` After all, since I was running with all my might every day, it's obvious that I'd sleep easily from being exhausted.`@
bg black,22
bg Air_02,22

;　体育の授業で校庭を走る時。@……前ほど苦手じゃなくなった気がする。@
` When I run in gym class now,`@` I don't have as much trouble as I did before.`@
br
;　当然だ。@私は毎日、どれだけの時間を走らされているというのか。@
` Of course.`@` I had been running for hours on end every day.`@
;　それに比べたら、@校庭をほんの数周、それも誰にも追い掛けられずになんて、問題にもならなかった。\
` I ran countless laps around the schoolyard every day. `@`Compared to that, running around during P.E. without anyone chase me was easy.`\
bg black,22
bg roji_03a,22

;　試しに、帰宅後も外に走りに行ってみたら、これも効果を示した。@
` As a test, when I got home in the evening I would go running as well. I could see results there as well.`@
br
;　もちろん、イザナミも私を諦めるつもりは毛頭ないらしい。\
` Of course, Izanami too had no intention of giving up on me.`\
bg black,22
bg rouka_02,22

;　日々、相当の時間を上乗せして挑んでくる。@
` Every day, I was challenged to a corresponding amount of time.`@
;　しかし私も、日々、相当の時間を走って、それを軽減している。\
` But as I ran more outside of that game, the time was ever decreasing.`\

;　それでも少しずつ時間は延びてくる。@
` Even so, little by little, extra time was tacked on daily.`@
;　一時期は３０分未満にさえ縮めた時間も、@最近はまた増え出し、元の１時間に戻ろうとしている。@
` For some time I was able to reduce the time down to 30 minutes. `@`But recently, it has been increasing again, and it returned back to a full hour.`@
;　しかし、……私も体力を付けてきている。\
` However... I fought with all my strength.`\
bg black,23
bg rouka_04,23

;　楽に走るコツのようなものも見つけた。@体力を温存できるペースも見つけた。@
` I found I trick to running easier,`@` and a pace that allowed me to conserve strength.`@
;　今の私なら、仮に１時間を超えたとしても、………やり果せる自信はあった。@
` Even if I had to run more than an hour.... I had confidence that I could do it.`@
br
;　そうしている内に、@……私はイザナミに追われるようになってから、すでに１ヶ月を超えるようになっていた。\
` In the meanwhile,`@`before I knew it, I had already reached one month of running away from Izanami.`\
bg black,2
wait 1000
bg rouka_02,23
wait 500
bg black,23
bg kaidan_01,23
wait 300
bg black,23
bg rouka_03,23

;　最近は、相当な距離を走り込んでいても、放課後の時間は１時間を超えてしまう。@
` Recently, even if I ran a considerable distance ahead of time, I'd still have more than an hour to go after school.`@
br
;　しかし、……私は負けなかった。@
` But... I wouldn't lose.`@
;　生きて４９日を越える自信を持っていた。\
` I was confident that I'd survive for 49 days.`\
;　時計をちらりと見る。@
` I glanced at the clock.`@
br
;　あと５分。@……今日のイザナミの放課後も、もうすぐ終わりだった。\
` Five more minutes.`@`... Izanami's after-school game would soon be over.`\
ld l,IZA_D4,22
;ld l,IZA_D4,80

;「頑張るじゃねェか。@最近はずいぶんと体力を付けやがってェ。@……そんなに地獄が嫌かァ？@　くっくくく、そりゃ嫌だろォなァ。」\
`"Well, ain't you doin' good? `@`You've been giving it your all lately.`@`... Is hell really that scary to you? `@`Kukuku, I guess that ain't surprising."`\
ld r,AYA_D7a,22

;「……あんな地獄、誰だってごめんよ。」@
`"...Anyone would want to be spared from that hell."`@
br
;　体力も付き、平常心を保てるようになった最近は、@イザナミに言い返せるくらいの余裕も出来た。\
` Recently, `@`I've even gathered enough strength and confidence to speak back to Izanami.`\
ld l,IZA_D2,80

;「俺ァ、お前がだんだん気に入ってきたぜ。」@
`"Ya know, I gradually came to like you."`@
ld r,AYA_D8a,80

;「……御免被るわ。@死神に好かれるなんて、冗談じゃない。」\
`"....Excuse me?`@` Who would want to be liked by a shinigami? What a joke."`\
cl r,23

ld l,IZA_D5,80

;「くっくくくくく！@　そりゃァ、違ェねェ…！」\
`"Kukukukuku!`@`Well, that's for sure...!"`\
bg black,23

fede 0,2000
E_A

bg rouka_04,23

me1v 5,50

;「なァ、あやちゃんよォ。@聞かせてくれ。@そこまでして、どうして生きたい？」@
`" Hey, listen to me Aya-chan.`@` Why do you want to live?"`@
;「……あんな地獄は絶対御免って、言ったはずよ。」\
`"...I told you. I'm definitely going to be spared a trip to that hell."`\
;「なら。@お前の望むような死だったらどうする？」@
`"Well then. `@`What if you could die in the manner you wished?"`@
;「……………………。」\
`"..........."`\
me2v 16,50

;「俺ァ、死神だ。@人間の魂を、死後のあらゆる世界に好きに連れて行ける。@あんな酷ェ地獄じゃなくて。@お前の望むような、眠るように消えられる世界に連れて行ってやってもいいんだぜ？」\
`"I'm a shinigami, ya know? `@`I can ferry the souls of the dead to a myriad of different afterlifes. `@`What if instead of that brutal hell, `@`I brought you to a world where you could vanish away as if falling asleep, like you wanted?"`\
bg black,24
bg kaidan_02,0
ld l,AYA_D2,24

;「………………………。@/
`"...........`@/
ld l,AYA_D3,80
;……冗談じゃないわ。」\
`....Don't mess wih me."`\

ld r,IZA_D1,24
;ld r,IZA_D3,80

;「冗談じゃねェさ。本当さ。@言ったろ？@　俺はクソ落ち目で生きる気力もねェ最低のクズが大好物なんだ。@……ところが、最近のお前はどうだァ？@　生き延びる為に努力を惜しまず、毎日毎日、きっちりと走り込んでやがる。@大した気力、生命力だ。@……そういうタマァ、俺の好物じゃねぇんだ。@だから、お前みたいなマズい魂に俺の胃袋は興味ねェんだ。」\
`"I ain't messin' around. It's the truth. `@`You said it yourself. `@`My favorite food are the pathetic little shits that no longer have the will to live.`@`... You, on the other hand... `@`Lately you've been willingly going running every day, giving it all your might. `@`You've got willpower and vitality.`@`... And I hate souls like that. `@`A gross tasting soul like yours would just give me indigestion."`\
ld l,AYA_D8a,80

;「なら……。@さっさとこの世界から私を解放してよっ。@冗談じゃないわ。」\
`"If that's the case...`@` Then hurry up and let me go already. `@`Give me a break!"`\
ld r,IZA_D4,80

;「仕方ねェさ。@俺の世界に引き込んだ以上、きっちり４９日は付き合わなくちゃならねェ。@それが俺のルールなんだ。@その間に、どれほどお前がマズい魂になっちまってもな。」\
`"Sorry, can't do that. `@`Once you've ended up in my world, you've gotta last the full 49 days. `@`That's my rule. `@`Even if it means I've gotta eat a soul that's gotten all nasty tasting."`\
ld l,AYA_D3,80

;「いい気味だわ。@……ご愁傷さまっ。」\
`"Oh no, that must be sooo horrible for you.`@`... I guess you reap what you sow."`\
cl l,24

wait 1000

ld r,IZA_D2,80

;「こう言っちゃなんだが。@俺もそうそう暇じゃねェ。@旨そうな魂ならいざ知れず、@お前みてェなマズい魂を追っ掛け回すなんて、時間の無駄もいいところだ。@そんな暇があったら、また別のクソ落ち目のガキを探しに行きたいところだぜ。」\
`"Ya know. `@`I don't have time for this either. `@`Having to chase you around, `@`when I'm not even sure whether you'll taste decent, it's a total waste of my time. `@`I would much rather be using that time to scout out other miserable brats."`\
;cl r,22
bg black,25
bg kaidan_01,22
ld c,AYA_D7a,24

;「じゃあ、私になんか構わないで、とっととそうしなさいよ。」\
`"Fine, hurry up and go then. It doesn't matter to me."`\
cl c,24
ld r,IZA_D3,22

;「言ったろ。@４９日が終わるか、お前が俺に捕まるか。@そのどちらかでしか、俺とお前の放課後は終わらねェ。@それが俺の、学校妖怪序列第２位、１３階段の死神のルールだ。」\
`"I just told ya. `@`Either go for the full 49 days, or get caught by me. `@`Those are the only ways to end our game. `@`That is my rule as the shinigami of the 13th step, 2nd ranked among the school youkai."`\
bg black,23
bg rouka_04,23

;「………お互い、何の得も意味もない放課後ね。@笑えるわ。」@
`"....So we're both just wasting our afternoons then? `@`That's laughably absurd."`@
;「まったくだァ。@……だからだ。@お前に相談があるわけだ。」@
`"Would ya listen to me? `@`...I'm trying to say, `@`I have something to discuss with you."`@
;「相談……？」@
`"Something to discuss....?"`@
br
;　私たちは、互いに足を止めることなく、会話を続ける。\
` Without either of us slowing our pace, we continue our conversation.`\
bg black,23

;「俺はもう、お前に興味はねェし、お前だってこんなのが延々と続くのもウンザリのはずだァ。@だからだ。@こうしよう。@俺に捕まれ。」\
`"Honestly, I don't care for you, and I'm sure you're getting bored of doing this every day too. `@`So here's the deal.`@`You. `@`Should let me catch you."`\
bg kyou_04,23
ld r,AYA_D7a,23
ld r,AYA_D8a,80

;「馬鹿と寝言は寝てからにして。」\
`"Cut the nonsense."`\
ld l,IZA_D4,23
ld l,IZA_D2,80

;「くっくっくっく！@　まァ、待て。@話は最後まで聞けって。@……俺は捕まえたヤツを、あの胃袋の地獄へ放り込む。@だが、お前みてェなマズい魂はいらねェ。@しかし、俺は死神だ。@捕まえた以上、死後の世界に連れて行かねェわけにはいかねェ。」\
`"Kukuku! `@`Don't be so hasty. `@`Hear me out.`@`... I usually take those I catch to that stomach-like hell. `@`But, I don't have any use for bad tasing souls like yourself. `@`However, I am still a shinigami. `@`Once I catch someone, I have to bring them to an afterlife."`\
ld r,AYA_D7a,80

;「……私に、あんたに捕まる利点がさっぱりないんですけど。」\
`"...And? I don't see how that's advantageous to me."`\
ld l,IZA_D3,80
E_A
;「お前の望んだ死を、与えてやるよ。」@
`"I can grant you the death you long for"`@
ld r,AYA_D5a,80

bgm1 7

;「……………え。」\
`"......huh?"`\
ld l,IZA_D1,80

;「お前の望みは、雪が解けるように眠るように、安らかに死ぬことだろ？」\
`"Your wish was to die peacefully like falling asleep or melting away like snow, correct?"`\

;　確かにそれは、……私の願望だ。@
` There is no mistake... that was my wish.`@
br
;　……………………。\
` ............`\
ld l,IZA_D2,80

;「それを叶えてやるよ。@そういう死後の世界もある。@お前の魂は、特別にその世界へ送ってやる。@それでどうだ。」@
`"I can grant it.`@` That sort of afterlife exists.`@` I'll make an exception and send you soul to that one instead. `@`How does that sound?"`@
ld r,AYA_D4a,80

;「……そんなの、………信用できるわけないでしょ。」\
`"......I ....I don't believe you."`\
cl r,24

bg black,22
;bg rouka_04,22

;「俺ァ死神だ。@その仕事で嘘は言わねェし、言うことも許されてねェ。」\
`"I'm a shinigami. `@`I don't lie about my job. I'm not allowed to."`\
bg kyou_04,0
ld c,IZA_D1,24

;　私は思わず振り返り、……イザナミを見る。@
` Without thinking, I looked back over my shoulder... and looked at Izanami.`@
br
;　死神はいつだって、私を挑発するようにへらへらしている。@
` This shinigami is always trying to provoke me.`@
;　しかし、今の瞳は、……なぜか信用できるような気がした。\
` But, for some reason... at that moment, I didn't feel like those were the eyes of a liar.`\
ld c,IZA_D3,80

;「俺はお前との放課後をとっとと終えて、新しい狩りを始めたい。@お前は、望みの死を手に入れて、安らかに眠ることが出来る。@どうだよ。@お互いに損がねェ話だとは思わねェか……？」@
`"Since I want to put an end to our after-school game and start hunting a new victim, `@`and you want to be able to rest peacefullly... `@`What do you think? `@`It's a win-win situation, right...?"`@
br
;　いつも、私を早足で追い立てていた死神が、……初めて足を止めた。@
` For the first time since he started chasing me... the shinigami stood still.`@
;　私は驚き、……自分も足を止めてしまう。\
` Dumbstruck... I stopped as well.`\
cl c,0
ld l,IZA_D1,24

;「相馬あや。@お前の望みを叶えられるのは、死神の俺だけだ。@………生きることに、何の価値も見出せない。@だからせめて、安らかに死にたい。@……その願い、俺にだけ叶えることが出来るんだぜ……。」\
`"Aya Souma. `@`The one who can grant your wish, is me.`@`.... Seeing no value in life, `@`and wanting to peacefully die because of it.`@`... I'm the only one who can grant that..."`\
ld r,AYA_D8a,22

;「……ま、……まっぴら御免よ。@私が人生を、どういう死に方で終えるかは私が探して私が決めるわ。@……あんたなんか頼らない。@信用できない。」\
`"...I... I beg your pardon? `@`The one who decides how I'll die should be me.`@`... Not you. `@`I don't trust you."`\
textoff

fede 0,1000
E_A

ld l,IZA_D4,80

;「ふ。@……くっくくくく。@/
`"Heh.`@`... kukukukuku.`@/
me1v 16,50
;……まァ、そう来るだろうよ。」@
`....Well, that time may come."`@
br
;　イザナミは頭を掻きながら肩を竦めて笑う。@
` Izanami scratched his head and shrugged his shoulders, then let out a laugh.`@
;　そして再び、足早に歩き出す。@私も足を再び動かす。\
` And once again, he began to move his legs. `@`As did I.`\
bg black,23
bg rouka_01,23

;　もうイザナミは何も言わなかった。@だから私も振り返らず、前だけを見て、黙々と走る。\
` Izanami didn't say anything more. `@`So I no longer looked at him. I just quietly ran, looking ahead.`\
bg black,22

;　……イザナミは、無慈悲な死神だけれど、今日まで嘘を吐いたことはない。@
` ....Izanami is a ruthless shinigami, but so far, he's never told a lie.`@
br
;　その彼が、かつての私が望んでいた死を与えてもいいと、言ってくれたのだ。\
` He had offered me that death that I had once dreamed of.`\
fede 0,1000
E_A

bgm1 24

;　なぜ断ったんだろう。@
` I wonder why I turned him down.`@
;　……イザナミが信用できないから断ったんじゃない。@
` ...It wasn't because I didn't trust him.`@
br
;　自分でも、……わからない。\
` Honestly... I'm not sure why.`\
;　最近は忘れ掛けていた問いが、再び頭を満たす。@
` The question that I forgot about, once again surfaced in my mind.`@
br
;　……私は、どうして生き延びようとするんだろう。@
` ....Why do I want to survive?`@
;　人は、死にたくないからだけの理由で、生きようとするのだろうか。\
` Do people keep living simply because they don't want to die?`\
;bg black,23
bg rouka_02,22

;　そんなの、人なら誰でも当り前だ。@
` I suppose that would be the most obvious reason.`@
br
;　生きるには、もっと意味とか価値とか目的とか、……色々とあるはず。@
` But, there's more to life than that... isn't there?`@
;　死にたくないから生きたいだなんて、……そんなの無意味で荒唐無稽だ。\
` Wanting to live because you don't want to die... that's meaningless. Absurd.`\
;　……私は未だ見つけられていない。@
` ...But I just can't find it.`@
;　生きる理由を、意味を価値を、目的を。@
` I can't find a reason to live. I can't find meaning, or purpose, or a goal.`@
br
;　ただ死にたくないからと、生き延びるために走り続ける日々。@
` These days that I spend running just because I don't want to die...`@
;　……それは、無意味で無価値な日々のはず。\
` They're meaningless and worthless.`\
bg black,23
bg rouka_03,23

;　でも、…………何だか、わからないのだ。@
` But..... there's something I don't understand.`@
br
;　かつてのぼんやりとした何の意味もない日々に比べたら。@
` Compared to the days before this, when I lived as if in a trance...
;　今の、生き延びるために努力を重ねる日々の方が、@……まだ、ささやかな価値があるように思えるのだ。\
` I feel like these days that I spend trying so hard every day to survive... `@`have slightly more value to me.
;　死にたくないなんて、誰だって当り前。@
` Obviously no one wants to die.`@
;　そんなの、生きるための理由にはならないはず。@
` But that shouldn't be a reason to live in itself.`@
br
;　生きるための理由というのは、……もっと崇高な目的とか使命とか、そういうもののはず。\
` Your reason for living should be... something more like a noble goal, or calling.`\
bg black,23
bg kaidan_01,23
ld l,AYA_D2,23

;　……でも私は、死にたくないからというだけの理由で、……今日も生き延びている。@
` ....but for me, the only reason I'm still living today... is because I don't want to die.`@
;　それは、無意味で無価値な日々のはず。@
` These should be meaningless, worthless days that I'm living.`@
br
;　……なら、死なせてもらえばいいはずなのに……。@
` ....So, I should be able to let myself die....`@`
;　何が正しくて何が誤りなのか、……自分でもわからなくなってきた……。\
` I have started to doubt myself... What is right? What is wrong? I'm not sure.`\
bg black,24
bg rouka_03,24
ld c,IZA_D7,24

;「おらァ！@　ペースが落ちてるぞッ。@追い付かれるぞォ！！」\
`"Hey~!`@`You've slowed down!`@`I'm gonna catch you!!"`\

bg black,23
bg kaidan_01,0
ld l,AYA_D2,23
ld l,AYA_D5a,80

;「ッ！」\
`"Ah!"`\
cl l,23
bg black,23
bg rouka_01,23

;　考え事をし過ぎた。@
` I was lost in thought.`@
;　いつの間にかペースが落ちていて、イザナミがすぐ近くまで迫っていた。@
` At some point my pace had slowed, and before I knew it, Izanami had drawn close.`@
br
;　イザナミが大鎌の柄で床をどんどんと叩き、ペースを上げろと怒鳴る。\
` Izanami banged the handle of his scythe on the ground and yelled at me to speed up.`\
bg black,24
bg kaidan_01,24
ld c,IZA_D7,24
;ld c,IZA_D8,80

;「走る時は頭をカラッポにしろ。@走ってれば頭がカラッポになる！@　下らねェこと考える暇があったら、ガンガン走って頭をカラッポにしろィ！@　俺のやさしいやさしい申し出を蹴りやがったんだ。@こうなりゃとことん付き合ってやらァ。@４９日間、バッチリ俺から逃げ果せてみやがれェ！！」\
`"If you're gonna run, empty your head. `@`Don't be thinkin' about dumb shit! `@`If you've got time to think, then start running harder! `@`You were the one who refused my generous offer. `@`So you'll have to stick it through 'til the end. `@`You've gotta run away from me for the full 49 days!!"`\
bg black,23
bg rouka_02,23

;　私は前を向いたまま、力強く頷いた。@
` Keeping my eyes fixed straight ahead, I nodded vigorously`@
;　彼の言う通りなのだ。@……余計なことは考えなくていい。@
` He was right.`@`... I shouldn't be thinking about unnecessary things.`@
br
;　人生の意味は何かと自問自答することそのものが、無意味で無価値なのではないのか。@
` What's the meaning of life? That's something that you can only answer for yourself.`@
;　そんな無意味なことで自分を苦しめるくらいなら、頭はカラッポの方がいい。\
` What is worthless and what is meaningless? If you're going to torment yourself over such meaningless question, you're much better off just emptying your mind.`\
　さぁ、何も考えずにカラッポになろう。@ただ、走ることに集中しよう。@
` So, I shall stop thinking, `@`and just concentrate on running.`@
br
;　そのカラッポの時が、一番、身も心も軽くなるのだ。\
` When my mind is empty like that, that's when my body and soul feel the lightest.`\
bg black,2

;　そんな日々が、何日も繰り返された。@
` This continued on for many more days.`@
br
;　カレンダーに付けた、４９日目が次第に近づいて来る。@
` According to my calendar, the 49th day was approaching.`@
;　その残り日数を数えることも、とても楽しかった。\
` Counting how many days remained was very fun.`\
bg air_02,22

fedexx 85,0,0,0,0,0,1000

;　毎日、頭をカラッポにして走り続け。@
` Every day, I would empty my head and continue to run.`@
br
;　汗だくで帰宅して、お風呂に入り。@
` I would come home drenched in sweat, and hop in the bath.`@
;　いっぱいごはんを食べて、ばったりと布団に倒れて、夢も見ないほどにぐっすり眠った。@
` Then I would eat a full plate of food, collapse into bed, and sleep so soundly that I didn't even dream.`@
br
;　……そして、とうとう、４９日目を迎えた。\
` ....and, finally, the 49th day arrived.`\
bg black,2

fede 0,2000
E_A

bg koutei_01,2

me1v 24,50

;　私は自分のことに精一杯だったので、学校の行事などはすっかり忘れていた。@
` I was so engrossed in my routine that I had completely forgotten about school events and the like.`@
br
;　その日は、学年のマラソン大会の日だった。\
` Today was the day of the annual school marathon.`\
;　かつては大嫌いだったマラソン大会。@
` A marathon I once loathed.`@
;　しかし今はまったく問題にならない。@
` But now, it would be no problem at all.`@
br
;　ひとりで校庭を走り回るか、みんなでマラソンをするか。@それだけの差だ。\
` The only difference was that instead of running around the schoolyard alone, `@`I'd be running with others.`\
;　しっかり走って、今日の最後の試練に挑もう。@
` I'll run my heart out, and take on this last challenge.`@
br
;　イザナミとの腐れ縁も、今日でおしまいだ。\
` My relationship with Izanami will end today.`\

bg black,22
bg koutei_05,0
ld r,IZA_D3,22
ld r,IZA_D2,80

E_A

;「いよォ。@/
`"Good.`@/
me1v 5,50
;今日は最高の走り日和だなァ…！@　くっくくくっくくくく！！」@
` Today's weather is great for running!`@`Kukukukuku!"`@
ld l,ay2_D5a,23
ld l,ay2_D8a,80

;「………ッ！！@　ど、どうしてここに……？！」\
`"......ah?! `@`W-why are you here...?"`\
;　それは紛れもなく、イザナミだった。@
` Without a doubt, it was Izanami.`@`
;　彼の物騒な姿はどうやら周りの人たちには見えていないらしい。@
` His unruly appearance didn't seem to be visible to the people around us.`@
;　放課後を待たずに現れるなんて、初めてのことだった。\
` This was the first time he had appeared in front of me before the end of school.`\
ld r,IZA_D3,80

E_A
bgm1 15

;「せっかく、マラソン大会なんて面白ェイベントがあるんだ。@そして、今日が俺とお前の長かった日々の最後だ。@……放課後に校舎をぐるぐるじゃあ、シメには面白くねェ。」\
`"I figured that since there's a marathon going on I'd stop by. `@`Besides, today is our final day together.`@`... and running around that building every day just ain't interesting any more, ya know?"`\
ld l,ay2_D5a,80

;「……まさか、今、………やる気なの……。」\
`".....No way. Don't tell me... that you plan on..."`\
ld r,IZA_D5,80

;「そういうこった…！@　ずっと歩いてるばかりで、俺も飽きちまったァ！@　せっかくのマラソン大会だ。@今日は俺も走らせてもらうぜェ…！！」\
`"Correct...! `@`I'm gettin' tired of walking all the time! `@`So, since there's a marathon today, `@`I figured that I could do some runnin' too...!!"`\
ld l,ay2_D7a,80

;「ッ……………。」@
`"ah........."`@
br
;　彼がどれほどの速度で走れるのかはわからない。@
` I didn't know for certain how fast he was able to run.`@
;　でも、大柄なその体格と長い足を思えば、かなりの速度で走れるのは間違いない。\
` But given his large build and long legs, he's got to be able to run pretty fast.`\
;　彼だって、毎日、１時間以上も早足で歩き続けているが、息一つ乱さないのだ。@
` Furthermore, `@`out of all those days that he had been chasing me for an hour or more, I had never once heard his breathing rate falter.`@
br
;　……相当の体力と脚力があるに違いない。\
` ...He must have considerable leg strength and stamina.`\
ld r,IZA_D2,80

;「怖ェか？」@
`"Are you scared?"`@
ld l,ay2_D4a,80

;「……………………。」\
`"..........."`\
ld r,IZA_D4,80

;「安心しろィ。@捕まえても、安らかに死なせるって約束はきっちり守ってやるからよォ。」@
`"Don't worry. `@`Even if I catch you, I'll still keep my promise to let you die gently."`@
ld l,ay2_D7a,80

;「………冗談じゃない。」\
`"...You're kidding."`\
ld r,IZA_D6,80

;「なら、せいぜい気合入れて走るこったなァ。@俺に捕まらずにゴールできたら、お前の勝ちだ。@捕まったら、……安らかに眠らせてやるぜェ。@くっくくくくく！」@
`"Nope. So you better give it your all. `@`If you can reach the goal before I catch you, you win. `@`But if I get you... I'll let you gently drift to sleep. `@`Kukukuku!"`@
br
;　イザナミは意地悪そうに笑い続けている。\
` Izanami continued to laugh malevolently.`\
cl l,24

;　私はそれを尻目に、少しでもスタートラインの前の方へ人ごみを掻き分けていく。\
` Closely watching him over my shoulder, I slowly started working my way through the crowds of people to the starting line.`\
cl r,0
ld c,IZA_D3,24

;「２０を数えてから追っ掛けてやらァ。@その間に、せいぜい距離を稼いでおくことだぜェ。」\
`"I'm gonna count to 20 before I come after you. `@`In the meantime try to distance yourself as much as possible."`\
bg black,22
bg koutei_04,22

;　スタートライン前は、男子たちがごった返している。@
` Boys crowded in front of the start line.`@
;　そんな中に混じろうとする女子は、私だけだった。@
` I was the only girl mixed among them.`@
br
;　先生がピストルを構える。\
` A teacher held up a pistol.`\
fede 0,1000
E_A

;「途中、歩いてもいいからな…！@　しっかり完走だけはしろよ！！@　よーい、」\
`"It's alright to walk along the way! `@`All that matters is that you finish!! `@` Okay! Ready!"`\
me1v 17,90

;　頑張って辿り着いた、今日。@
` I worked hard to reach this day.`@
;　それを絶対に無駄にしない。@
` I won't let it all be for nothing.`@
br
;　絶対に、……生き残ってやる。\
` I'm going to survive.... definitely.`\
;　………痛いくらいの沈黙が、先生の構えるピストルの引き金に注視させる。@
` ...I stood in utter silence, eyes fixated on the teacher's pistol for a painfully long time.`@
br
;　そして、……数瞬の沈黙を、乾いた火薬音が打ち破る。@
` Finally... the silence was broken by the sound of dry gunpowder.`@
;　その瞬間、数百人の生徒たちが、一斉に走り出す。\
` At that moment, hundreds of students took off all at once.`\
E_A
bgm1 21

mbg white,1
mcbg 42

ld c,IZA_D3,24
ld c,IZA_D6,80

;「さァ、走れ走れ、相馬あやァ！@　今日まであれだけ走り続けたお前だ。@その成果、見せてくれやァ…！！」\
`"Get goin'! Run! Run, Aya Souma! `@`Today is the day that you've been running for. `@`Show me how far you've come...!!"`\
bg black,22

;　イザナミの体は、見えない人間には透けるらしい。@
` It seems that Izanami's body is intangible to those who can't see him.`@
;　２０を数える彼の体をすり抜け、大勢の生徒たちの波が走り出していく。\
` While he was counting to 20, dozens of students passed right through him.`\
;bg black,24
;bg gakkou_05,22
bg ura7,24

;　人ごみに飲み込まれたら、自分のペースで走れなくなる。@
` If I was surrounded by the crowds of runners, there's no way that I could keep up my pace.`@
br
;　私は先頭集団に混じって、かなり速いペースで走り出した。\
` So I had stood with those closest to the starting line, and took off with considerable speed.`\
bg black,22
bg roji_03a,22


;　……今日まで、持久力はかなり付けたと思う。@
` ....So far, I think my stamina has been fine.`@
;　でも、スピードに関しては意識したことがない。@
` But I wasn't so sure about my speed.`@
;　だから、このスタートダッシュは、やや無理をしていた。@
` So I may have forced myself to run a bit too fast in my starting dash.`@
;　でもいい。@とにかく、人ごみからさえ逃れられれば、あとは自分のペースで走れる。\
` But it's okay. `@`If I can escape from the mass of people at the beginning, then I can run at my own pace from then on.`\
;　最初くらいは一位気分を味わいたいと、@威勢良くスタートダッシュをした男子たちは、次々に体力切れで脱落していく。@
` At first, all the boys who wanted to be in first place started off running with all their strength,`@` but one by one they started to run out of stamina and fall behind.`@
br
;　私は脱落しない。@……あんたたちとは鍛え方が違うんだからっ。\
` But I won't fall behind.`@`... My discipline is different than theirs.`\
bg black,23

;　やがて、運動部で鍛えられた生徒だけになって、先頭集団もまばらになると、@私は速度を落とし、いつものペースを取り戻した。\
` Finally, the pack thinned, and only those who were in sports clubs remained. `@`I dropped my speed, and brought myself back to my normal pace.`\
;bg black,23
bg roji_04a,0
ld c,IZA_D6,23

;　後を振り返ると。@…………居た。@
` And when I turned my head around to look behind me.......`@` I saw him.`@
;　イザナミが私を追って来ているのが見えた。@
` I saw Izanami chasing after me.`@
br
;　その速度は、決して速過ぎるものではない。@
` But at not too fast a rate.`@
;　私が自分のペースを守ることが出来れば、リードを守ることは充分に可能だった。\
` If I can just hold my pace, I should probably be able to keep the lead.`\
;　本当は、もっと早く走ることも出来るのだろう。@
` Honestly, that's probably not the fastest that he can run.`@
;　イザナミは捕まえることより、追い回すことを好む。@
` He preferred the chase to the catch.`@
;　きっと、最後の最後まで、ぎりぎりの速度で私を追い上げ続けるに違いない。\
` He's most likely going to gradually gain on me until the very last moment.`\
ld c,IZA_D2,80

;「すっかり体力を付けたなァ。@お前が今抜いたヤツ、男子だぜェ？@　お前、その辺の部活やってる男子より体力つけてるぞォ。」@
`"You've got quite a bit of strength, don't ya? `@`You see those boys you just passed? They're training all the time in their after school clubs. `@`You've got even more strength than them."`@
br
;　……お陰様で。@皮肉を言ってやりたいが、呼吸のペースが乱れるので、口には出さなかった。@
` ...'Well, I have you to thank for that.' `@`I wanted to snark back at him, but that would affect my breathing rate. So I didn't open my mouth.`@
;　それに、どうやらイザナミは、私が口に出さなくても心の声が聞こえるらしい。\
` And, somehow, It seems like even without opening my mouth, Izanami can still hear the words in my heart.`\
ld c,IZA_D3,80

;「まだ、お前は考えてるのかァ？」@
`"Are you still thinking?"`@
br
;　……何を。\
`....about what?`\
ld c,IZA_D5,80

;「生きることの意味だの価値だの。@そんな下らねェことをだよォ。」@
`"The meaning of life. The value of living. `@`Stupid shit like that."`@
br
;　……あんたのお陰で、それを考える暇もないのよ。\
`....Thanks to you I don't have time to think about that.`\
ld c,IZA_D2,80

;「なら良かったじゃねェか。@その暇がなくてよォ。」@
`"Well isn't that good?`@` That you ain't got time to think."`@
br
;　何が良かったのよ。\
` What's good about that?"`\
ld c,IZA_D3,80

;「それを毎日考えちまうから、苦しかったんだろォ？」@
`"Wasn't thinking about that every day painful?"`@
br
;　……………………。\
`...........`\
ld c,IZA_D1,80

;「その苦しみに耐えられなくて、お前は死にたいと願ったんだろォ？@　なら、良かったじゃねェか。@俺のお陰で、お前は下らねェことを考える暇がなくなったってェわけだ。」\
`"It was so unbearably painful that you wanted to die, right? `@`So then, it's good. `@`It's good that, because of me, you no longer have time to waste thinking about that stuff."`\
bg black,24

;　…………そうかもね。@
`.....maybe he's right.`@
br
;　下手の考え、休むに似たりって諺があるもんね。@
` There's a saying that goes 'it's hard to tell a poor thinker from a sleeping one.'`@
;　考えても無駄なことって、世の中にはきっとある。@
` No matter how hard you think about it, pointless things will always exist in this world.`@
;　多分、人生の意味や価値なんて、一見高尚そうなことも、@考えるだけ無意味で無価値なことに違いない。\
` At first glance, it seems like searching for the meaning or worth in life is a noble cause, `@`but if all you're doing is just thinking about it, then what you're doing is meaningless and worthless in itself.`\
;bg black,24
bg air_02,24

;　そんな下らないことを考える暇があったなら。@
` If you have time to think about such trivial things,`@
br
;　……勉強したり、運動したり。@美味しく給食を食べてお代わりしたり。@
`....then studying, or exercising, `@`or eating seconds of a delicious meal...`@
;　思いっきり汗を流して、シャワーを浴びてすっきりして。@
` Or sweating buckets and washing off in the shower...`@
;　夜は布団の柔らかさを全身で楽しんで、ぐっすり眠った方が、遥かにマシなのだ。\
` Or enjoying the softness of a futon in the evening and falling fast asleep. Any of that would be far better.`\
;　私はかつて、@生きることの意味を考えようともしない人たちのことを、愚かだなと見下したことがある。@
` I used to look down on people who didn't care to know the meaning of living. `@`I used to think they were foolish.`@
br
;　そんな哲学的なことで頭をいっぱいにする自分は、どんなに高尚かと自惚れていたかもしれない。\
` I may have been so full of myself that I thought by being philosophical, I was somehow nobler than those around me.`\
;　しかし、今になると思う。@
` However, I've realized my mistake.`@
br
;　馬鹿馬鹿しかった。@
` I was being absurd.`@
;　自分の生きる意味？@　価値？@
` One's own meaning of life?`@` Or value?`@
;　そんなこと考える暇があったら、もっともっとやるべきことが、世の中にはいっぱいあった。\
` If you have the time to worry about that, then there's so many other things in the world that you should be doing instead.`\
bg kyou_01,22

;　学校は勉強して運動して、遊んで笑うところでしょ。@
` Like studying, exercising and laughing with friends at school.`@
br
;　私は何をしてた？@　毎日ぼんやりとして、勉強もせず運動もせず、遊びもせず笑いもせず。@
` What was I doing? `@`All I ever did was daydream. I never studied, or exercised, or laughed with friends.`@
;　なのに、人生の意味なんて、馬鹿馬鹿しいことで頭をいっぱいにして、@自分は高尚な人間だと自惚れていた。\
` What I did do was fill my mind with foolish thoughts about the meaning in life, `@`I convince myself that I was noble for doing so.
bg black,22

;　私、やっとわかったかもしれない。@……人生の、意味。@
` I think I finally understand. `@`....the meaning of life.`@
br
;　“死にたくないから生きる”で、充分なんだ。\
` 'Living because you don't want to die,' That's enough of a meaning.`\
;　人が生きると書いて、人生。@
` The two characters that make up the Japanese word for life (人生) mean 'person' and 'living.'`@ ;(?) Can this be done better in English? (?)
br
;　人は、ただ生きているだけで、立派に意味と価値があるんだ。@
` People, just by living, already have a wonderful meaning and worth in life.`@
;　そしてさらに人生に意味や価値が求めたいなら、……さらに今を精一杯、生きればいい。\
` And if you find yourself wanting more meaning to life... then you should try living each moment to its fullest.`\
bg ura5,24

;　学ぶ。@遊ぶ。@笑う。@怒る。@泣く。@何でもいい。@精一杯精一杯。@
` Learn.`@` Play.`@` Laugh.`@` Be angry.`@` Cry.`@` Anything is fine.`@` Just live life with all your might.`@
br
;　それを全力でやり尽くして生きることそのものが、人間の価値なのだ。\
` To be able to put your heart into something, and do it until you're literally too exhausted to continue. That is the value of human life.`\
bg black,24
bg roji_03a,24

;「あやァ！！@　またペースが落ちてるぞォ！！@　下らねェことで頭を満たすな！！@　カラッポにしろ！@　考えるんじゃねェッ、カラッポで走れぇええ！！」@
`"Aya!! `@`you're slowin' down again!! `@`Stop filling your head with useless thoughts!! `@`Keep it empty! `@`Don't think, just clear your mind and keep running!!"`@
;「…………………！！」\
`"..........!!"`\
;　イザナミの声が近い。@
` Izanami's voice was near.`@
;　またぼんやりしてペースが落ちていたらしい。@
` It seems that I had spaced out and started slowing once again.`@
br
;　彼の言う通りだ。@……下らないことは頭にいらない。@全て追い出し、カラッポにしよう。@
` He's right.`@`... I don't need this sort of stuff filling up my head. `@`I'll cast it all away.`@
;　頭も心も、そして体もカラッポにして軽くするんだ……。\
` I will empty my head and my heart so that my body will be lighter.`\
bg black,24
bg roji_04a,24

me1v 5,85

;　頭の中が、すぅっと澄んでいく感触……。@
` In my head, there was a feeling of clarity...`@
;　体の中が空洞になり、羽にでもなった気がする。@
` It felt as if my body was hollow, and was as light as a feather.`@
;　目線は自然と遥か彼方へ。@……呼吸も穏やかなものになっていく。\
` My gaze drift far-off place.`@`... My breathing became calm.`\

;　足はどんどん軽くなる。@行ける、行ける、……まだまだ行ける……。@
` My legs rapidly became lighter. `@`I can make it, I can make it.... I can still make it...`@
;　陸上部の男子が抜かれ、驚きの目を向ける。@
` I overtake the boys from track and field club as their eyes turn on me with amazement.`@
br
;　でもそんなの興味ない。@全てをカラッポにして、………風になるんだ。\
` But none of that matters to me. `@`I am completely empty... I am the wind.`\
bg black,24
bg gakkou_01a,24

;　角を曲がると、再び学校が見えてくる。@
` Once I turn the corner, the school will once again come into view.`@
br
;　あの校門がゴールだ。@あと、ほんの数百メートル。\
` The school gate is the finish. `@`Just a few hundred meters more.`\
bg black,1

;「あやァ！！@　ラストスパートォ！！@　最後の気合、俺に見せてみやがやれェ！！」@
`"Aya!! `@`This is the last stretch!! `@`Show me your fighting spirit one last time!!"`@
;「………………ッッ！！！」\
`".........!!!"`\
;　今日は残り時間も、イザナミの距離も、上り階段も下り階段も何も気にしなくていい。@
` Today I don't have to worry about the time remaining, Izanami's distance, or climbing up and down staircases.`@
br
;　ゴールすれば全て終わりだ。@何も何も、残さなくていい。\
` It's all over the moment I reach the finish line. `@`I don't have to hold anything back.`\
;　走り抜けよう。@体の中の全てを吐き出そう。@
` I run. `@`I run with every last ounce of strength my body has to offer.`@
;　後先なんか考えなくていい。@下らない自問自答に、二度と心を満たさなくていい。@
` I won't think about what comes next. `@`Never again will I fill my mind with trivial introspective questions.`@
;　全部全部、カラッポの境地。\
` Every bit of my mind is empty.`\

;bg white,2
bg gakkou_01a,2
bg white,0
flushout 5000

bg black,42

;　……私は、………風になった………。\
` ...I became... the wind......`\
fede 1,4000
E_B

fedexx 0,50,0,0,0,0,2000


bg air_02,2



;　最後の１００メートルは頭が真っ白で、何も記憶にない。@
` For the last hundred meters, my head went completely blank -- I don't remember a thing.`@
br
;　気付いた時。@私は校庭にぶっ倒れ、大の字になって、青空を見上げていた。\
` When I came to, `@`I was sprawled out on the ground of the schoolyard, looking up at the blue sky.`\
;　全身は汗でびっしょり。@胸は激しく上下し、肺はまだまだ爆発しそうに熱かった。@
` My whole body was drenched in sweat. `@`My chest was moving up and down with labored breath. My lungs burned as if on the verge of explosion.`@
br
;　でも、………目の前いっぱいに広がる青空のように、……身も心も、全てが晴れやかで、@……広大な広大な、清々しいカラッポだった。\
` But.... like the great blue sky before my eyes... `@`my body, my soul, everything was magnificently and refreshingly empty.`\
fede 0,1000
E_A

;　そんな私の目の前に、ずいっと大きな手が突き出される。@
` That scene was quickly obscured by a large hand reaching down to me.`@
;　咄嗟にそれを、握ってしまう。@
` Without thinking, I grab it.`@
bgm1 4
;　大きな分厚い手だった。@
` It was a large, bulky hand.`@
br
;　そして、それが死神の手であったことに気付く。@
` And then I realize that the hand I'm grabbing belongs to the shinigami.`@
br
;　イザナミはぐいっと引っ張り、あやの上体を起こしてくれた。\
` Izanami pulled, and raised my--Aya's--upper body.`\
bg black,22
bg koutei_01,22
ld r,IZA_D4,22


;「……今、どんな気持ちだァ。」@
`"...What do you feel now?"`@
ld l,ay2_D11,26

;「全部カラッポで、………自分が青空になったみたいな気持ち、……です。」\
`"I feel empty..... like a blue sky..."`\
ld r,IZA_D1,80

;「カラッポは最高だろ。@走って走って走りまくりゃ。@誰だってカラッポになれるんだ。」@
`"Emptiness is the best, isn't it? `@`You ran and ran and ran. `@`Anyone can become empty if they do that."`@
ld l,ay2_D10,80

;「……はい。@……最高です。」@
`"...Yes.... `@`It is the best."`@
br
;　不思議だった。@
` It was strange.`@
;　あれだけ怯えた死神なのに、……まるで先生であるかのように、敬語で答えてしまう。\
` Even though I was so afraid of this shinigami... I answered him loudly and clearly, as if replying to a sensei.`\

ld r,IZA_D3,80

;「な？@　人が生きる意味なんて、理由なんて。@そんな馬鹿馬鹿しいモン、どうでもいいだろォ？」@
`"Right? `@`The reason that people live. `@`You're fine without knowing that, aren't ya?"`@
ld l,ay2_D9,80

;「はい。@……そんなもの、……すごくどうでもよくて、……馬鹿馬鹿しいです。」\
`"Yes.`@`... such things... are ridiculous at best."`\
cl r,0
mld c,IZA_D1,24

;「人間はなァ。@がむしゃらに走って、頭をカラッポにするくらいでちょうどいいんだよ。@お前の人生はこれからも長い。@また、おかしなことで頭をいっぱいにしちまうこともあるだろうよ。@………その時はどうすればいいか、わかってンな。」\
`"For humans, `@`it's really easy to empty their minds while running. `@`You're going to be living for a long time. `@`So, along the way, If you ever start gathering dumb thoughts in your head again... `@`I think you know what to do."`\
mcl c,0
bg black,22
bg air_02,22

;「はい。@……走って走って、……また頭をカラッポにします。」@
`"Yes. `@`I'll run and run... and empty my head of all those things!"`@
;「そうだァ！@　いいだろ、走るってのはァ！！」@
`"Exactly! `@`Ain't running great?!"`@
;「………はいっ。」\
`"...Yes."`\
mov %IZA_Isyou,2
bg black,22
bg koutei_01,0
ld l,ay2_D11,0
ld r,IZA_D2,22
ld r,IZA_D6,80

;「それにしてもお前、なかなかいい脚をしてるじゃねェか！@　陸上部に入れッ。@俺がじきじきに、バンバンしごいてやらァ！！@　わっはははははははは！！」\
`"By the way, you've got some good legs there! `@`Join the track and field team. `@`I'll be sure to personally oversee your training!! `@`Wahahahahaha!!"`\

ld l,ay2_D10,80

;「……私、走るの。@………好きになりました。@……先生。」\
`"...I really`@`.... grew to love running.`@`... Sensei."`\
;　イザナミの姿はいつの間にか、死神のマント姿ではなくなっていた。@
` Without my noticing, at some point Izanami's shinigami cloak had disappeared.`@
;　手に持っていたはずの大鎌は、竹刀に代わり。@……漆黒のマントは、ジャージに代わっていた……。\
` Instead of a scythe, he carried a bamboo kendo sword.`@`... and in place of his jet black cloak, he was wearing a track suit...`\
bg black,22
bg air_02,22

;　担任や他の先生たちも彼女のもとへ集まり、相馬あやの意外な大健闘を絶賛してくれた。@
` A group of teachers gathered around Aya, and the other runners that finished behind her were cheering for her.`@
;　彼女が休み時間の度に校庭を走っていたのは、すでに有名な話。@
` The story of the girl who spent her free time running had already became famous around the school.`@
;　その成果を存分に発揮した成績は、運動部に所属する生徒たちに並ぶものであった。@
` And because of that, groups of students that participated in sports clubs had lined up around her.`@
br
;　こんなにも寄って集って褒められた経験などない。\
` Never before had she experience such praise.`\
;「……ありがとう。先生。」@
`"Thank you, sensei"`@
;「生きろよォ、あやァ…！！！@　立ち止まったら、そのケツ、俺の竹刀でぶっ叩いてやるからなァ！」@
`"Live, Aya!! `@`If you stop, I'll whack your ass with my bamboo!"`@
;「はいっ。」\
`"Yes."`\
;　気持ちのいい風が、彼女の火照りを冷ます。@
` A pleasant wind cooled the girl's burning lungs.`@
br
;　あやは夢を見るような心地で、いつまでも青空を見上げているのだった……。\
` Feeling as if she was in a dream, she stared up at the blue sky for a long, long time.`\ 

mov %SIN_Isyou,2
bg black,42

fede 0,1000
E_A

bg koutei_05,22

ld r,SIN_D1,22

bgm1 1

;「立派な熱血教師ぶりですねぇ。」@
`"You're quite the excellent Sensei."`@
;＜教頭（紅茶紳士）

ld l,IZA_D1,22
ld l,IZA_D2,80

;「何だ、教頭かよ。@人が悪ィな。@ずっと見てやがったなァ？」@
`"Oh, it's you, Vice principal. `@`Ain't you got a sense of privacy? `@`Have you been watching all this time?"`@
ld r,SIN_D3,80

;「くっくっくっく。@気にしないことです。@子供たちを見守るのが、私たちの仕事ですから。」\
`"kukukuku. `@`Don't worry. `@`Watching over the children is my job."`\
ld l,IZA_D3,80

;「釣り逃がしちまったが、あやはもう、お前の獲物にもならねェぞ。@あいつはもう、妄想に逃げるようなクソ落ち目じゃねェ。」\
`"She may have gotten away from me, but don't go makin' Aya your prey. `@`She's no longer a delusional brat that runs away from reality."`\
ld r,SIN_D2,80

;「そのようですねぇ。@……先に目を付けたのが私だったら、@彼女を素敵な夢の世界に招待できたのですが。」\
`"You're right.`@`... If only I had found her first. `@`I could have offered to take her away to the world she desired."`\
cl l,0
mld c,IZA_D5,23

;「いいか、紅茶野郎ォ。@この学校のナンバー２は俺だァ！@　狩りの邪魔はさせねェし、@仮に釣り逃しても、お前の獲物にも断じてさせねェ…！@　校長の腰巾着風情が、影の第２位なんて百年早ェんだよ！」\
`"Listen up, Black Tea Bastard. `@`I'm the one who's ranked number 2 in this school. `@`I won't allow anyone to get in the way of my hunts. `@`She may not be my prey anymore, buy I sure as hell won't let you make her yours...! `@`You may be the Headmaster's lackey, but listen up, the 2nd ranked in the shadows ain't got nothing on me!"`\
ld r,SIN_D1,80

;「くっくっく。@私のことなど、気にしないことです。@さて。@……狙っていた相馬あやも、すっかり美味ではなくなってしまいましたからねぇ。@また、新しい獲物を探しましょう。@そして、早く夢の世界へ連れ去って、あなたの手が届かないようにしなくては。」\
`"Kukuku. `@`Don't worry about me. `@`You see`@`.... that Aya Souma girl you were hunting.... She no longer holds any interest to me. `@`I am going to find a new target,`@`and quickly whisk them away to my dream world so that you can't get them."`\
mld c,IZA_D2,80

;「けっ。@何が夢の世界だ。@俺がケツを引っ叩いて、現実に叩き戻してやるぜェ。」\
`"Geh. `@`Screw your dream world. `@`I'll just slap that kid up and bring 'em back to reality."`\
mcl c,0
bg black,23
bg koutei_04,0
ld l,HOK_D1,23
ld l,HOK_D3,80

;「教頭先生～。@表彰式が始まりますよ。@先生方が呼んでまーす。」\
`"Vice Principal~! `@`The award ceremony is starting. `@`They're calling for you."`\
;＜保健の先生

bg black,24
bg koutei_05,0
ld r,SIN_D1,0
ld l,IZA_D2,24

ld r,SIN_D2,80

;「……では失礼。@あなたとの決着はいずれ。」\
`"....Well then, I'll be taking my leave. `@`We'll settle this later."`\
cl r,23

ld l,IZA_D5,80

;「知るか。@紅茶でも啜ってやがれ。」\
`"Piss off. `@`Go drink your damn tea."`\
bg black,22
bg koutei_04,0
ld l,SIN_D2,0
ld r,AY2_D11,2

;　上位１００人には、入賞のメダルが与えられる。@
` Medals were being given to the first 100 kids who had placed in the marathon.`@
;　プラスチック製のチープなそれも、@あやにとっては、４９日間を生き抜いて生まれ変わったことを讃える、立派なメダルになるだろう。\
` They were plastic, and cheap plastic at that, `@`but to Aya, it was a wonderful symbol of her 49 day survival and rebirth as a person.`\
cl l,0
ld c,SIN_D3,23
wait 1000
ld r,AY2_D10,80

se3v 54,50

;　このような賞をもらうことが、生まれて初めての彼女は、@教頭先生からメダルを手渡され、顔を紅潮させて微笑んでいた。\
` This was the first time in her life that she had ever received such an award. `@`She held out her hands and accepted the medal from the principal, and a bright smile spread across her face.`\
bg black,22
bg koutei_05,0
ld c,IZA_D2,22
wait 1000
ld c,IZA_D5,80
wait 1000

cl c,22

bg white,29
bg air_02,29

;「けっ。@すっかり不味そうな魂になっちまいやがったァ。@……生きろよ、あやァ！！」\
`"Tch. `@`Ya know, your soul really did get nasty as hell.`@`...Live on, Aya!!"`\


bg black,42

;＜おしまい＞

bg e022,42
wait 1000
bg black,42
bgcopy ;背景をリセット

fede 0,2000
E_A
wait 2000

if %UMINEKOEND < 2 mov %UMINEKOEND,2 : mov %END_FLG,2 ;クリアフラグの変更

	saveoff            ;セーブオフで、処理を高速化する。
	erasetextwindow 0  ;テキストエフェクトを切る事で処理を高速化
	rmode 0            ;右クリックのメニュー表示の無効化
	textoff

goto *b_title
;reset



*higan6_opning

texton
csp -1

bg black,2
bgcopy ;背景をリセット

setwindow 31,16,22,16,26,26,0,2,20,1,1,#999999,0,0,639,479

!sd

mono 0
E_A





;bg kyou_01,0
;ld c,YUK_D1,22
;ld c,YUK_D1,80
bg kyou_01,22

bgm1 2
me1v 24,50
