;Chapter 6

;　榊由香里は、現在のクラスにすっかり馴染んでいた。@
`　Yukari Sakaki has been adjusting quite well to her new class.`@
br
;　欠席した日の社会科見学で、バスが事故を起こし、@クラスメート全員を失うというショックからも、すでに立ち直っていた。\
`　She had already recovered from the shock. `@`The shock of losing her entire class in a bus crash on a social studies field trip on a day she was absent.`\

;ld c,YUK_D1,80
ld c,YUK_i1,23
ld c,YUK_I3,80

;　いじめを人一倍憎む彼女は、いじめを見つけては、臆すことなく叱っていた。@
`　This girl, who had once been bullied especially bad, had made it her mission to seek out and prevent bullying of others.`@
;　それをうるさがる男子たちには疎まれていたが、@その正義感は誰にも認められ、クラスでの人気も上々だった。\
`　She was shunned by the boys who she annoyed by doing this, `@`but everyone else admired her sense of justice, and she became very popular among those in her class.`\

;bg black,22
;ld r,YUK_D1,22


;　今の彼女を見て、かつていじめられていたことを想像できる者はいないだろう。\
`　Looking at her now, no one could imagine that she had once been a victim of bullying herself.`\

bg black,22
bg kyou_04,22
;ld r,MAR_D1,23


;　楽しい学校生活を取り戻せても、彼女はいじめを憎むことは止めない。@
`　Even though she's regained her happy school life, she can't help but detest bullying.`@
br
;　いじめを注意することで男子と喧嘩になることがあろうとも、彼女が怯むことはない。\
`　Even when her warnings about bullying lead to quarrels with boys, she will not back down.`\

;ld l,MAR_D1,22
;ld l,MAR_D1,80
ld r,MAR_W1,22


;　そんな彼女を見て、毬枝は改めて彼女の強さを尊敬するのだった。\
`　Seeing her as she was now, Marie had gained a new respect for the girl's strength.`\

cl r,22
bg black,2
bg kyou_02,22

;「ほらほらこっちー！！」@
`"Hey, over here!!"`@
;「ヘイヘイー、パスパース！！」@
`"Here, pass! Pass!!"`@
;「ちょっと、……やめろよ、返せよぉッ。」\
`"Wait... stop it, give it back."`\

;　数人の男子が、誰かの筆箱をキャッチボールのように投げ合っている。@
`　A group of boys were playing catch with someone's pencil case.`@
;　その持ち主の男子が、返せよと言いながら、ぐるぐると追い掛け回している……。\
`　The owner of the pencil case was telling them to give it back while chasing it back and forth between them...`\


ld r,YUK_I2,24
ld r,YUK_I3,80

;「こらッ、そこの男子！！@　いじめはやめてッ！」@
`"Hey, you boys!! `@`Stop bullying!"`@
;＜由香里
br
;　由香里が大声を張り上げる。\
`　Yukari yells at them.`\
;　悪ふざけが過ぎて、遊びといじめの境がわからなくなる男子と、それを叱る由香里。@
`　She scolds them for taking their playing too far and not knowing where to draw the line between teasing and bullying.`@
;　このクラスの、最近ではすっかりお馴染みの光景だった。@
`　This is a scene that the students of this class have become well acquainted with.`@
br
;　由香里は彼らから筆箱を取り上げると、持ち主の男子に返す。\
`　Yukari takes the pencil case from them and hands it back to the owner.`\
;bg black,1
;bg kyou_01,23
;ld c,YOS_D1,0
;mld l,YUK_D1,22

bg black,24
bg kyou_01,24
;ld c,YOS_D4a,22
mld l,YUK_w1,23

mld l,YUK_W2,80

;「はい、吉川くん。」@
`"Here you go, Yoshikawa-kun."`@
ld c,YOS_D9,22
ld c,YOS_D3a,80

;「………あ、……ありがと。」@
`"....Th-... thank you."`@
br
;　吉川正明（よしかわ　まさあき）は、おずおずと筆箱を受け取る。@
`　Masaaki Yoshikawa (吉川正明) timidly takes the case from her.`@
;　するとそれを見て、さっきの男子たちが囃し立てた。\
`　The boys from earlier stood there jeering at the sight of that.`\

;「吉川、ダセー！@　女に助けられてんのかよー！」@
`"Yoshikawa, you're so lame! `@`You just got saved by a girl!"`@
;「お前なんか、女と遊んでんのがお似合いだよ！@　うっはははは！！」\
`"I bet you play with girls all the time, you sissy! `@`Uwhahaha!!"`\

;mcl l,0
;bg black,22
;mono 1
;ld c,YOS_D1,22

mcl l,0
mld c,YOS_D3a,0
bg black,22

;　正明は身長が低く小柄で、成長期を迎えた他の男子たちに比べると一回り華奢に見えた。@
`　Masaaki had a short, petite build. When compared to the other boys who had hit growth spurts earlier than he had, he looked very small.`@
;　そのせいもあってか、体格のいい意地悪な男子たちに目を付けられ、よくからかわれていた。@
`　Because of that he was often poked fun at by the mean boys with better physiques.`@
br
;　そのからかいがいじめに姿を変えるのに、そう長い時間は必要なかった。\
`　It didn't take long for that poking fun at to change into full-fledged bullying.`\
;　由香里がやって来てからは、教室で堂々といじめることも次第になくなってきた。@
`　Ever since Yukari showed up, the bullying in this class has, rather impressively, gradually disappeared.`@
;　だからといって、彼らが正明という愉快な玩具を手放すわけもない。@
`　Nevertheless, these boys had no intention of giving up on Masaaki, their newest toy.`@
br
;　そのいじめは、水面下でしつこくと続き、悪化の一途を辿っているらしかった……。\
`　They had continued their bullying behind the scenes, and it had been getting worse day after day...`\

;bg black,22
;mono 0
;bg kyou_02,0
;ld c,YOS_D1,0
;ld l,YUK_D1,22

mcl c,0
bg kyou_02,0
ld c,YOS_D3a,0
mld l,YUK_w4,22


;　男子たちに囃し立てられた正明は、気まずい顔で俯きながら、由香里の手から筆箱を引っ手繰る。\
`　Masaaki lowered his head with an uncomfortable expression at the sight of the boys jeering at him. He quickly snatched the pencil case from Yukari's hands.`\
;se1 9
cl c,0
ld r,YOS_D2,23

;「べ、……別に助けてくれなんて言ってねぇよ……。」@
`"I... I didn't ask you to help me..."`@
;ld l,YUK_D1,22

mcl l,0
ld l,YUK_I1,80

;「でも、いじめられてたじゃない。」\
`"But weren't you being bullied?"`\


;ld r,YOS_D1,0

ld r,YOS_D10a,80

;「い、いじめられてなんかねーよ…！！」@
`"I- I wasn't being bullied!!"`@
br
;　心にもない言葉だ。@
`　There was no sincerity in those words.`@
;　でも、正明はつい強がってそう言ってしまった。\
`　But Masaaki blurted them out to seem tough.`\
;cl a,0
;bg black,22

;　……彼も自分がいじめられっこであることは、薄々自覚している。@
`　He was a bit self-conscious about being bullied.`@
br
;　しかし、それを認めたら負けだと、自分に言い聞かせて今日まで堪えてきたのだ。\
`　But feeling like he'd lose if he admitted it, he'd endured it this whole time.`\
;　正明の、いじめられてなんかないという言葉に、@いじめっこたちも、そうだそうだと同調する。\
`　The bullies agreed with Masaaki, `@`claiming they would never bully him.`\

;bg kyou_07,2
;ld l,YUK_D1,22

cl l,0
ld c,YUK_D3,23

;「本当に、……いじめられてないの？」@
`"You're... really not being bullied?"`@
;ld r,YOS_D1,22

ld r,YOS_D3a,80


;「…………い、……いじめられて……ねぇよ……。」@
`"......I- ...I'm not... at all...."`@
br
;　由香里もわかって聞いている。@
`　Yukari was the only one who heard him.`@
;　だから、正明にしか聞こえない小声で言った。\
`　His voice was too quiet to be heard by anyone but her.`\

;ld l,YUK_D1,80

ld c,YUK_D2,80

;「……私で力になれることがあったら、いつでも言ってね。」\
`"...If you ever need me to lend you my help, let me know."`\
ld r,YOS_D8a,80

fede 1,1000
E_B

ld r,YOS_D10a,80

;「お、女の世話になんかならねぇよ…！！」@
`"I- I don't need to be helped by a girl...!!"`@
;cl r,23

cl r,23
br
;　正明はそう怒鳴りつけ、席へ戻る。\
`　Masaaki shouted at her and returned to his seat.`\

;bg black,1
;bg kyou_01,2
;ld c,YOS_D1,22

bg black,23
bg kyou_03,23
;ld c,YOS_D2,23
;ld c,YOS_D4a,80

;　いじめっこたちも同調して、けらけらと笑った。@
`　The bullies agreed with him, and cackled.`@
br
;　正明もその笑いに同調するかのように笑ってみせるが、少しぎこちなかった。\
`　Masaaki laughed along with them as if in agreement, but his laugh was a bit awkward.`\

;　自分は、おちょくられやすいキャラクターだから。@……これはいじめられてるんじゃなく、みんなで悪ふざけをしているだけ。@
`　He had a personality that was easy to make fun of.`@` ...So this wasn't bullying, it was just teasing.`@
br
;　そう信じなければ、やっていけないようだった……。\
`　He forced himself to believe that...`\
bg black,22

fede 0,1000
E_A
wait 1000

bg ura8,22

bgm1 8

;「吉川、トロぇよ！！@　早く来いよ早く来いよ！！」@
`"You're so slow, Yoshikawa!! `@`Hurry up, hurry up!"`@
;ld r,YOS_D1,22

;ld r,YOS_D3,24
ld r,YOS_D4a,24

;「……む、……無理だよ…、……重くて……。」\
`"...I- ...I can't..... It's too heavy..."`\


;「お前、絶対ぇ土、付けんなよ…！！@　一個でも落としたらズボン、ドブに捨てっからな！！」@
`"Don't let any of them touch the ground...!! `@`If you drop even one we'll throw your pants away!!"`@
br
;　下校中、正明はいくつものランドセルを担がされていた。@
`　They were forcing Masaaki to carry a multitude of backpacks on their way home from school.`@
;　後に背負い、前にも背負い、両腕に通し、肩にも担いで。\
`　He had them on his back, on his front, in both hands, and on both shoulders.`\


;ld r,YOS_D1,22

ld r,YOS_D3a,80

;　重さ以上に、バランスが不安定で、今にも落としてしまいそうだった。@
`　It wasn't so much the weight as his trouble at keeping balance was almost causing him to drop them.`@
;　しかも彼らは一つでも落とせば許さないと囃し立てる。\
`　But they just kept mocking him, saying that they wouldn't let him off easy if he dropped any.`\
bg black,23
bg ura7,23

;　彼らが手に持って振り回しているのは、正明のズボン。@……もしランドセルにわずかでも土を付けたら、ズボンをドブに捨てると言っている。\
`　In their hands, they swung Masaaki's pants back and forth.`@` ...They said they would throw them away if he even let one of the bags touch the ground just slightly.`\


;bg black,0
;bg ura7,24

;　……だから、正明はズボンを脱がされたみっともないパンツ姿で、@たくさんのランドセルを担がされていたのだ。@
`　...And so Masaaki was walking pantless, his underwear shamefully displayed, `@`carrying multiple backpacks.`@
;　重さより、そんな姿で歩かされる屈辱の方が、正明には耐え難かった。\
`　The weight of the bags was nothing next to the disgrace of being forced to walk dressed like that.`\
me1v 30,50

;「ほら、早く！@　この電信柱まで来いよ！！」@
`"Hey, hurry up! `@`Make it to this telephone pole!!"`@
;「走れ吉川ッ、ダッシュダッシュ！！」@
`"Run, Yoshikawa! Sprint, sprint!!"`@
ld c,YOS_D4a,24

;「そ、……そんな……無理………。」\
`"I-... I... can't..."`\

se1v 12,30
quakex 1,100

;「走れ走れッ。@ズボン、ドブに漬けるぞコラ！」@
`"Run, run. `@`Or we'll throw your pants in the gutter!"`@
br
;　男子たちが、走れ走れと煽り、彼のお尻を叩く。@
`　 The boys hit his butt, urging him to run.`@
;　それに急かされ、正明も逃げるように駆け出す。\
`　That made Masaaki speed up.`\
ld c,YOS_D3a,80

;「……や、やめてよ痛いよ…！@　あッ…、」@
`"...S- stop, that hurts...! `@`Ah..."`@
ld c,YOS_D10a,80

cl c,25
se1 13
quakey 2,200
br
;　わずかのバランスを崩した拍子に、ランドセルがどさどさっと落ちる。@
`　He slightly lost his balance for a moment, and all the backpacks came tumbling down.`@
;　その内の一つが転げてドブに突っ込む。\
`　And one of them fell into the gutter.`\


;bg ura5,22
bg black,24
bg ura5,24

;「ふッ、ふざけんじゃねぇよッ！！@　俺のランドセル、ドブに落としてんじゃねーよ、このッ！！」@
`"Wh- What the hell!! `@`Don't drop my backpack in the gutter!`@
se1 10
quakex 1,100
wait 300
se2 12
quakex 1,100

;「ぎゃッ！！@　い、痛いっ、……ぎゃ…！！」\
`"Ahh!! `@`Th- that hurts... aghh..!!"`\

;　そのランドセルの持ち主が、鬼のような形相で激高し、@正明のお尻をサッカーボールのように、何度も何度も本気で蹴りつける。@
`　With an unbridled rage on his face, `@`the owner of that backpack kicked at Masaaki's butt over and over with all his strength as if it were a soccer ball.`@
br
;　彼の白いパンツのお尻が、土汚れでみるみる汚れた。\
`　His white underwear were quickly dirtied with mud.`\


ld r,YOS_D2,26
ld r,YOS_D4a,80

;「や、やめてよ……。@あはは……、痛いよ……、痛いよ……。」\
`"S- stop it... `@`Ahaha... that hurts... ouch..."`\

se1 10
quakex 1,100

;「テメェ、わざとだろッ！！@　わざとドブに落としやがっただろ！！」@
`"You did that on purpose!! `@`You dropped my bag in the gutter on purpose, damn it!!"`@
;「わざとだよ、こいつ絶対わざとだよ！」@
`"It was on purpose, he definitely did it on purpose!"`@
se1 10
quakey 1,100

;「わざとじゃねぇかよテメェ！！@　なめんなテメェ！！」\
`"It was on purpose, wasn't it!! `@`Don't fuck around with me!!"`\
;se1 10

bg black,22

;ld r,YOS_D3a,80

;「い、痛いよ、やめてよ……。@本当にわざとじゃないんだよ……、ごめんよごめんよ……。」@
`"O, ow, stop... `@`I really didn't mean to... I'm sorry..."`@
;「本当にわざとじゃねぇのか？！@　絶対ぇかよ？！？！」@
`"Really?! `@`You bein' serious?!?!"`@
;ld r,YOS_D10a,80

;「ぜ、絶対だよ、絶対だよ……！！@　ごめん、ごめん、ごめん、ごめん…！！」\
`"R- really, seriously...!! `@`Sorry, sorry, sorry, sorry...!!"`\


;「……………そっかー。@じゃー許してやるかな。@俺たち友達だもんな。@友達は信じねーとなぁ。」@
`"......Okay then. `@`We'll forgive you. `@`We're friends after all, right? `@`You gotta trust your friends, right?"`@
;ld r,YOS_D4a,80

;「あ、ありがとう……。@はは、は……。」\
`"Th- thanks... `@`Haha, ha..."`\

;cl r,0
bg ura7,22

;「でも、ランドセル落としたから罰ゲームだからな。@お前のズボン、ドブ漬けな。」@
`"But since you dropped my bag, you've gotta do a punishment game. `@`Time to dunk your pants in the gutter."`@

;ld c,YOS_D1,22
;cl r,0
;ld r,YOS_D4a,24
;ld c,YOS_D1,80

;「え、そ、そんな……、止めてよぉ……。」\
`"Huh, n-, no... stop that..."`\
;「落としたら罰ゲームって約束だったろ。@俺たち友達だもんな。@友達は約束守んねぇとなー！」@
`"We promised that if you dropped 'em we'd play a punishment game, right? `@`Aren't we friends? `@`Friends gotta uphold their promises!"`@


ld r,YOS_D4a,24

;「そ、そんな……。」\
`"Th- that's..."`\

;「え？　何？@　俺たち友達じゃねぇの？@　友達じゃねぇの？！@　え？　え？！@　俺はお前の友達じゃねぇのかよ！！@　友達だろッ、友達だろッ、ああッ？！？！」\
`"Huh? What is it? `@`Are we not friends? `@`We're not friends?! `@`Huh? HUH?! `@`I'm your friend, aren't I?!! `@`We're friends, friends, huh?!?!"`\


se1 6
quakex 1,100

se1 7
quakey 2,200

wait 400

se1 6
quakex 1,100

se1 7
quakey 2,200

;ld c,YOS_D1,80

;　そう詰め寄りながら、正明のお尻を何度も蹴る。@友達に対してじゃれ付くように、とはお世辞にも言えないくらいの強さで、何度も何度も。\
`　While pressuring him for an answer, he kicked Masaaki's butt many more times. `@`Many, many times, with so much strength that it couldn't prove anything except that they weren't friends at all.`\


se1 6
quakey 1,100
wait 500
se2 10
quakex 2,200

ld r,YOS_D10a,80

;「痛いッ、とッ、友達だよ…！@　友達ッ、友達ッ……！！」@
`"Ouch, w-, we're friends...! `@`Friends, we're friends...!!"`@
;「……ほらな？！@　友達だろ？！@　じゃあ、約束守れるよな！@　守れるよな？！@　約束守んねぇなんて、友達じゃねぇもんな？！」\
`"...See?! `@`We're friends, right?! `@`Okay then, keep your promise! `@`You're gonna keep it, right?! `@`Don't friends keep promises?!"`\

ld r,YOS_D12,80

;「う、うんッ。@ま、守れるよ、守れるよ……。」@
`"Y, yeah. `@`I- I'll keep it, I'll keep it...."`@
;「じゃあ、ほらッ。@約束守ってお前がやれよッ。」\
`"Okay, here. `@`It's your promise, so you do it."`\

;　いじめっこは、取り上げていた彼のズボンを、ずいっと突き出す。@
`　The bully held the pants out to him.`@
br
;　もちろん、返す為に渡すのではない。\
`　He wasn't holding them out to politely return them of course.`\

;bg black,0
;bg ura7,22
;ld r,YOS_D1,22

ld r,YOS_D10n,80

bg black,22
;bg ura7,23
;wait 500
;ld r,YOS_D1,22

;「約束だからなッ。@ランドセル落としたら、お前のズボンドブ漬けッ。@やるんだよ、ほら！」@
`"It's a promise right? `@`If you drop our bags, your pants have gotta get dunked. `@`Do it, now!"`@
;「友達だから約束は絶対だもんなー！！」@
`"We're friends so you gotta keep your promise!!"`@
;「やれねーなら、お前友達じゃねぇぞ、ただの嘘吐きだぞー！！」@
`"If you don't do it, you're not our friend, just a liar!!"`@
;「友達じゃねぇなら、マジ手加減しねー。@嘘吐きはお仕置きしねぇとなー！」@
`"If you're not our friend, we're not gonna go easy on you. `@`Liars need to be punished!"`@
br
;　いじめっこたちが、凄みながら詰め寄る。\
`　The bullies drew closer, threatening him.`\

fede 1,1000
E_B

;ld r,YOS_D1,80

;　……正明に、それを断ることなど、出来るはずもない。@
`　...There's no way Masaaki could refuse them.`@
;　彼は結局、いじめっこたちに囃し立てられる中、自分のズボンを自らの手で、ドブの中に浸さなければならなかった……。\
`　In the end, with the accompaniment of the bully's jeers, he had to dunk his own pants in the gutter...`\


;bg black,22
;bg ie_01,2


;bg black,42

fede 0,3000
E_A

bg ie_01u,22

bgm1 14

;　家で母親に、どうしてそんなに汚してしまったのかと怒られた。@
`　When he got home his mother got mad at him, asking how he got his pants so dirty.`@
br
;　自分がいじめられていると認めたくない正明は、@友達とふざけていて、つい汚してしまったと言い訳するのだった。\
`　Not wanting to admit that he was being bullied, `@`Masaaki said that he was messing around with his friends and he got them dirty.`\
bg black,22

;　……こういうことは、これが初めてではない。\
`　...This wasn't the first time this had happened.`\

;bg ie_02u,22
;ld r,YOS_D1,22

bg ie_02u,0
ld r,YOS_D10n,22

;　自分の部屋に戻り、ランドセルを下ろした彼は、惨めな気持ちでいっぱいになった。\
`　He went up to his room, set down his backpack and sat, miserable.`\

;ld r,YOS_D1,80
;se1 7

cl r,22
;ld c,YOS_D1,24
se1 7
wait 500

;ld c,YOS_D1,80
se2 10

;　そして、彼らが自分にそうしたように、枕を何度も何度も蹴り付けるのだった……。\
`　And he threw down his pillow and kicked it over and over again, as if he was kicking himself...`\
bg black,2
fede 0,2000
E_A

bg gakkou_01,22
wait 2000
bg black,22

;■教室
;bg black,22
;bg kyou_02,0

bg kyou_02,22
me1v 24,50

wait 1000

ld r,YUK_D1,24
ld r,YUK_i3,80

;「あんたたちっ。@また吉川くんをいじめてんじゃないでしょうねっ。」@
`"Hey! `@`You guys aren't bullying Yoshikawa-kun again, are you?"`@
;＜由香里
;「いじめてなんかねーよ！！@　なぁ？！」@
`"We're not bullying him!! `@`Right, buddy?!"`@
ld l,YOS_D3,22

;「う、……うん。」\
`"y-... yeah."`\
;＜正明


ld r,YUK_i3a,80

;「いじめてるじゃない！@　何で、そんな何人もで寄って集って吉川くんを取り囲んでるのよ…！」@
`"If you're not bullying him! `@`Then why are so many of you crowding around him...?!"`@
;＜由香里
br
;　今日も正明は、いじめっこたちに囲まれ、いじめられている。\
`　Today as well, Masaaki was being surrounded and bullied.`\


;　彼らが言うには、遊んでいるだけ、からかっているだけらしい。@
`　According to them, they were just hanging out and teasing him.`@
;　しかし、正明にとっても由香里にとっても、それは明白ないじめに他ならなかった。\
`　But it was incredibly obvious to both Masaaki and Yukari that he was being outright bullied.`\


;「ほらッ、吉川も言ってやれよ！@　俺たちは仲良く遊んでるんだから放っとけって言ってやれよ！」@
`"Hey, Yoshikawa, you tell her too! `@`We're just good friends hanging out, and she needs to leave us alone!"`@
;「俺たちは友達だもんなー！@　なあ！！」\
`"We're friends! `@`Right?!!"`\
ld l,YOS_D3a,80

;「……………ぅ、……うん……。」\
`"......y-... yeah..."`\

cl r,0
ld c,YUK_i2,24

;「吉川くんっ、おいでっ。」\
`Yoshikawa-kun, come here."`\
;cl l,0
;cl r,23
;bg black,23


cl a,23

;　由香里は強引に正明の腕を掴むと、教室の外へ連れ出す。@
`　Yukari grabbed Masaaki on the arm, and forcibly pulled him outside the classroom.`@
br
;　いじめっこたちはそれを、あの二人付き合ってるぞーヒューヒュー！@　などと言って、囃し立てていた……。\
`　The bullies poked fun at him for that.... `@`With mocking exclamations of 'they're going out!' and whistling.`\

;bg kyou_04,23
;ld r,YUK_D1,0
;ld c,YOS_D1,22

bg black,23
bg kyou_04,0
ld r,YUK_i2,0
ld c,YOS_D3a,23


;　廊下に連れ出されると、正明は由香里の手を、少し乱暴に振り払った。\
`　Once out in the hallway, Masaaki angrily pulled his arm out of Yukari's hand.`\


cl c,0
ld l,YOS_D12,24

;「………な、何だよ、榊……。@離せよ……。」@
`"...W- what do you want, Sakaki.... `@`Let go of me..."`@
ld r,YUK_i3a,80

;「何だよじゃないでしょッ。@あんな意地悪な人たちが友達なの？！@　友達ってあんな意地悪なことをする人たちなの？@　違うでしょ？！」\
`"Is everything really fine? `@`Are those mean kids really your friends?! `@`Would friends really do such mean things to you? `@`Of course not, right?!"`\


ld l,YOS_D10a,80

;「そ、……そんなことねぇよ……。」@
`"I-... It's not like that..."`@
ld r,YUK_i3,80

;「あれがいじめじゃないって言うの？！」\
`"Are you telling me that it isn't bullying?!"`\
ld l,YOS_D10,80

wait 1000

ld l,YOS_D8a,80

;「……いじめじゃねぇよ！@　ふ、……ふざけてるだけだよ…。」@
`"...It's not bullying! `@`P-... Piss off..."`@
br
;　自分がいじめられているなんて、認めたくない。@
`　He didn't want to accept the fact that he was being bullied.`@
;　……本当はわかっているのに、それを認めない虚勢を張ってしまう。\
`　...He knew he was being bullied, but he refused to admit it.`\

;bg black,22
;mono 2
;bg Different_spiral_1a,22

bg black,22

;　いじめられてることを認めない限り、自分はいじめられっこじゃない。@ただのいじられキャラなんだ。@
`　If he didn't admit he was being bullied then he wasn't. `@`He was just the kind of person people liked to play around with and tease.`@
br
;　……そう信じることだけが、彼を支える最後の拠り所だった。\
`　...Believing that was the last resort he had.`\
;ld r,YUK_D1,80

;　もちろん、由香里もわかっている。@
`　Of course, Yukari knew that as well.`@
;　それこそが彼の心の強さだし、異性に対して弱みを見せたくない男心も理解できる。@
`　She knew it was part of his male pride to not want to let himself be seen as weak by someone of the opposite sex.`@
br
;　しかし、それではいじめはますますエスカレートするだけだ。\
`　But because of that, his bullying has only gotten worse and worse.`\
;bg black,0
;mono 0
;bg e010,2

bg rouka_03,22

;　今のままでは、いじめっこたちは本気で、@自分たちのしているそれをいじめじゃないなどと信じてしまう。@
`　As things are now, `@`the bullies really don't believe that what they're doing is bullying.`@
;　犠牲者の彼が、いじめだと認めないのをいいことに、@これはおちょくって遊んでいるだけでいじめではないと、半ば本気で思っている。@
`　Even he as the victim, by not being able to admit he's being bullied, `@`he's halfway convinced himself that this is really just playful banter with friends.`@
br
;　いじめに良し悪しなどないけれど、それを自覚しないいじめは陰湿だと由香里は思っていた。\
`　There's no preferable way to be bullied, they're all equally horrid, but still, Yukari felt that being bullied like that without even realizing it is particularly awful.`\


;bg black,22
;bg rouka_03,0
;ld r,YUK_D1,0
;ld l,YOS_D1,22

;bg black,23
;bg rouka_03,0
;ld l,YUK_D1,0
;ld r,YOS_D1,23

ld l,YUK_i1,23

;「こんなので、本当に吉川くんは楽しいの？」@
`"Are you really having fun like this, Yoshikawa-kun?"`@
;ld l,YOS_D1,80
ld r,YOS_D8a,24

;「………た、……楽しいよ……。」\
`"....Y-... yeah I'm having fun..."`\
;ld r,YUK_D1,80
ld l,YUK_i1a,80

;「お願い。@本当のことを言ってよっ。」@
`"Please. `@`Tell me the truth"`@
;ld l,YOS_D1,80
ld r,YOS_D3a,80

;「………………………。」\
`"............."`\


;ld r,YUK_D1,80
ld l,YUK_D1,80

;「私は吉川くんの味方だよ。@あなたを守ってあげるから。@……一緒にいじめを止めさせよう？」\
`"I'm your ally, Yoshikawa-kun. `@`I'll protect you.`@` ...So work together with me and help me stop bullying?"`\


;　正明にとって、自分の受けている仕打ちが「いじめ」であると自覚させられることは、@とてもナーバスなことだった。@
`　To Masaaki, the act of admitting that he was being 'bullied', `@`was the source of much nervousness for him.`@
br
;　その一言に、逆上するかのように激高する。\
`　With that one utterance, he was thrown into a frenzy-like rage.`\

;ld l,YOS_D1,80
;ld l,YOS_D1,80

cl r,0
mld c,YOS_D12,24

E_A
se1v 8,30
ld l,YUK_i1a,1
quakex 1,100
mld c,YOS_D11,80

;「だッ、だからいじめられてなんかねぇって言ってんだろ？！@/
`"I-, I thought I told you I'm not being bullied!!`@/
bgm1 8
;　俺は別に、だ、誰にもいじめられてなんかねーよ！！@　余計なお世話なんだよッ。@二度と俺に話し掛けんじゃねーよ！！@　迷惑なんだよッ！」\
` No one is-, is bullying me like that!! `@`This is none of your business. `@`Don't talk to me ever again!! `@`You're being a nuisance!"`\
mcl c,23

wait 1000

;ld r,YUK_D1,80
ld l,YUK_D3a,80

me1v 24,50

;「…………………………。」\
`"............."`\

bg black,22
;mono 1
;ld c,YUK_D1,22
bg rouka_04,22

;　由香里にはわかっている。@心にもないことを言っていると、わかっている。@
`　Yukari understood. `@`She understood that he didn't really mean what he had said.`@
;　しかし、手は二人が伸ばし合わないと届かない。@
`　But the helping hand she extended was unable to reach.`@
;　由香里だけが手を伸ばしても、正明も手を伸ばさなければ届かないのだ。\
`　Yukari couldn't lend a hand, unless Masaaki was willing to take it.`\

;　……それ以上を問答しても、彼の心には届かない。@由香里はそれ以上を諦め、大きなため息を漏らす。\
`　...Even if she tried to continue this discussion, he wasn't going to open up to her. `@`Yukari decided to drop it here, and let out a big sigh.`\

bg black,22
;mono 0
;bg kyou_04,0
;ld r,YUK_D1,0
;ld l,YOS_D1,22


;ld r,YUK_D1,80
bg kyou_04,22

;ld l,YUK_D1,0
;ld r,YOS_D1,22

ld c,YUK_D1,22

;「……わかった。@じゃあ、余計なお節介はもうしないようにするけど。」@
`"...Okay. `@`I'll try not to meddle in your affairs any further."`@
;ld l,YOS_D1,80
ld l,YOS_D8a,24

;「そうしてくれよ。@俺、もう行っていいか。@……お前なんかと一緒にいて、変な噂とかされたくねーし……。」\
`"Good. `@`Can I go now?`@` ...If I'm together with you for too long people are going to start weird rumors and stuff..."`\
;ld r,YUK_D1,80
cl c,0
ld r,YUK_w3,23

;「私、いつでも味方になるからね。@………本当に困ったら、いつでも相談してね。」@
`"I can become your ally at an moment.`@` .....If you're ever really in trouble, you can come talk to me at any time."`@
;ld l,YOS_D1,80
ld l,YOS_D10a,80

;「しねーよ、絶対ぇッ。」@
`"I won't, ever."`@
br

;cl l,24
cl l,24

;　正明はそう言い捨てると、踵を返す。\
`　Masaaki spit out those words, and turned around on his heels.`\


;bg black,2
;mono 1
;ld c,YOS_D1,22


bg black,24
;bg kyou_04,24

;　……彼女の言葉に、ほのかな温かさも覚えたが、@それを認めたら負けだという意地の方が勝っていた。@
`　...He felt a bit of kindness in her words, `@`but if he recognized it, it mean admitting defeat.`@
br
;　彼はずかすかと足早に教室へ戻る。@
`　He hurried straight back to the classroom.`@
;　……ちくりと心が痛むのを感じながら。\
`　...While his heart stung with a small pain.`\
bg black,2
;mono 0

wait 1000

;bg kyou_02,2
;ld r,YOS_D1,0
;ld l,YUK_D1,22

bg kyou_02,22
;ld c,YOS_D1,2

;　それ以来、由香里は教室で正明がいじめられっこに絡まれていても、@あまり口出しをしないようになった。\
`　Since that time, whenever Yukari saw Masaaki getting pushed around by the bullies in the classroom, `@`she never really interfered.`\




;　見捨てたわけではない。@彼に、いじめは嫌だという気持ちが自発的に芽生えるのを待とうと思ったのだ。\
`　It's not that she had abandoned him. `@`She simply tried to wait until he voluntarily decided he had enough of the bullying.`\

;　いじめられっこには、いじめられまいとする克己が不可欠。@それが由香里の持論だった。@
`　Someone who is being bullied must have the resolve to stop that bullying themselves. `@`That was Yukari's theory.`@
br
;　それがなければ、いくら第三者がいじめを止めたところで、その場限りにしかならない。\
`　If they don't have that resolve, even if a third-party steps in and stops the bullying, it will only be a temporary fix.`\

;　……もちろん、それがいじめられっこにとって、容易なことでないことは、@由香里も身に染みてわかっている。@
`　...Of course, gaining that resolve is no simple task to someone who is being bullied. `@`She knew that all too well.`@
br
;　でも、その強さを彼に持って欲しい。\
`　But, she wanted him to have that strength.`\

;cl l,0
;bg kyou_03,22

bg black,22
bg kyou_01,0
ld r,YUK_D3,22

;　そう願い、彼が助けを求める時、@それがいつでも出来るよう、さりげなく側にいるように努めた。@
`　When he did ask for ask from her, `@`she strived to stand by his side and help out as if she had been there all along.`@
br
;　余りに酷いいじめの際にはさすがに割って入ったが、それ以上のお節介は避けた。\
`　If the bullying ever got to serious, she would force her way into the situation, but she avoided doing any further than that.`\
cl r,22
fede 1,1000
E_B

;ld c,YUK_D1,22
;ld c,YUK_D1,80

;　しかし、割って入るべきないじめの頻度は次第に増えていった。@
`　However, the number of occurrences in which she would have to force her way in to stop the bullying were increasing.`@
br
;　先生も時には注意してくれるのだが、@いじめっこたちはへこたれないし、当の本人もそれをいじめとは認めない。\
`　The teacher even issued a few warnings to them, `@`but the bullies never let up, and the boy being bullied never admitted it.`\


;　……吉川正明に対する状況は、ゆっくりとゆっくりと、深刻の度合いを増していくのだった……。\
`　...Masaaki Yoshikawa's situation gradually became increasingly more serious...`\
bg black,2

fede 0,2000
E_A

bg gakkou_02u,22

me1v 5,50
wait 2000

bg black,22
bg kyou_02u,22



;　放課後の夕方。@
`　After school, at dusk.`@
;　……ほとんどの生徒たちはすでに下校を終えている時間だった。@
`　...It's past the time when most of the students should have already left to go home.`@
br
;　校庭で遊んでいる子供たちは見えるが、校舎内に残っている子供はいないだろう。\
`　Some kids could still be seen playing in the schoolyard, but there shouldn't be any students still remaining inside the building.`\

ld r,YOS_D3,24

;　正明はクラス委員長の仕事で残され、ようやくそれを終えて教室に戻ってきたところだった。@
`　Masaaki was made to stay after class to do his work as the class representative. Once that was over he was about to return to the classroom.`@
br
;　……彼がクラス委員長に、自発的に立候補したわけもない。@
`　...He didn't volunteer to be the class representative.`@
;　いじめっこたちが画策し、投票で無理やり彼を推薦したのだ。\
`　The bullies had hatched a scheme and voted him into the position against his will.`\
;　クラス委員長など、生徒にとってみれば、仕事を押し付けられる面倒臭い役職でしかない。@
`　From the point of view of the students, the class representative was nothing more than an annoyance that made them do extra work and bother them.`@
br
;　当然、彼自身にもそれに相応しいカリスマはなく、@……名ばかりの、クラス委員長だった。\
`　Naturally, he didn't have the charisma that the position required.`@` ...And so he was the class representative in name only.`\
;ld r,YOS_D1,80
cl r,22

;　……すっかり夕方になり、校内は静まり返っている。@
`　...Now that it was dusk, the inside of the school had fallen completely silent.`@
br
;　校庭で遊ぶ子供たちの声は、とても楽しそうなのに、@それがとても遠くに聞こえて、何だか悲しい気持ちだった。\
`　The kids playing in the schoolyard sounded like they were having a lot of fun, `@`but it sounded so far off that it sounded somewhat sad.`\

;bg koutei_03,0
;ld r,YOS_D1,24

bg black,23
bg koutei_03,23

;　正明はベランダに出て、それを見下ろしていた。@
`　Masaaki had gone out on the balcony, and was watching them play.`@
br
;　その目は遠く、@……夕日を浴びて黄昏色に染まるその表情は、生気あるものとはとても言えなかった。\
`　From this far away... `@`dyed in the colors of twilight, their expressions hardly seemed lifelike.`\

fede 10,2000
E_MA
bgm1 14

;ld r,YOS_D1,80

;　………はぁ………。@
`　.....Hah....`@
br
;　正明は希薄なため息を漏らす。@
`　Masaaki let out a weak sigh.`@
;　最近、自分の意識も希薄になってきた気がしていた。\
`　Lately, he felt like even his consciousness had grown weak.`\


bg black,22
;mono 1
;bg different_spiral_1a,22

;mono 2
;bg different_spiral_1a,22

;　頭にはもやがいつも掛かっていて、@……昨日はおろか、今朝の朝食が何だったかさえ思い出すことが出来ない。@
`　His head felt like it was perpetually shrouded in a haze.`@` ...He couldn't even remember what he had for breakfast yesterday, or even this morning for that matter.`@
br
;　……それは彼の心を守るために、彼自身が無意識に行なっていることなのだろう。\
`　...That was probably his body's way of subconsciously protecting his heart.`\
;　日々、エスカレートするいじめ。@
`　Every day the bullying gets worse.`@
;　でも、それをいじめとは決して認めたくない、自己矛盾。@
`　But paradoxically, he refused to admit it.`@
;　それに彼を苦しめることがないよう、@……彼の頭に常にもやがかかり、記憶と苦しみを薄れさせているのだ。\
`　In order to prevent that suffering... `@`the haze took over his head, and faded both him memories and pain.`\

;　……だからといって、彼が気楽になれるわけでもない。@
`　...That's not to say that he was at ease.`@
br
;　麻酔をしたって、歯医者の激痛がゼロになるわけはないのだ。\
`　Even when given anesthesia at the dentist's office, it doesn't reduce the pain to nothing.`\
bg Different_spiral_1b,22

;　さりとて、その麻酔がなければ、@彼の心はとっくの昔に、粉々に砕けてしまっていただろう。@
`　That said, if he didn't have that anesthesia, `@`his heart would have been smashed to pieces long ago.`@
br
;　歯医者なら、麻酔が切れる前に治療は終わる。@
`　When used in the dentist's office, the medical procedure is finished before the anesthesia wears off.`@
;　……しかし、彼に対するいじめは永遠に終わらず、むしろ苛烈を極めるばかりだった。\
`　...but the bullying he faced was rather severe, and never ended.`\
;　心の麻酔で、もう痛みを誤魔化せないなら。@
`　The anesthesia of his heart could no longer evade that pain.`@
br
;　……それ以上の劇薬で、痛みを消す他ない。\
`　...So he had no choice but to use an even stronger medicine to ease the pain.`\
bg black,22
bg koutei_03,22

me1v 16,50

;　彼が眼下の校庭を見下ろして、@……そこから飛び降りる想像に解放感を覚えることになったとしても、無理もないことだった。\
`　As he looked down on the schoolyard beneath him... `@`it was only natural that he would consider the liberation that jumping from there would give him.`\



;bg black,22
;mono 0

;bg koutei_03,0
;ld c,YOS_D1,22

ld r,YOS_D3,22

;「……………………………。」@
`"............."`@
br
;　正明は眼下を見下ろす。@
`　Masaaki looked down at that ground.`@
br
;　ここから飛び降りて、大空に溶けるように、消えてしまう想像。@
`　He imagined jumping from the balcony, and melting away into the sky.`@
;　魂は空に溶け、……体は、大地にやわらかに包み込まれる。\
`　His soul melting into the sky... as his body was softly enveloped by the earth.`\

;　不思議な想像だった。@
`　It was a strange thought.`@
br
;　かつては、こうして眼下を見下ろせば、高所の恐怖を感じることが出来たのに。\
`　Before now, whenever he would look down from a high place, he would feel fear.`\


;　……今はまるで、@……ホテルでふかふかのベッドを前に、駆け出して飛び込みたいような、童心にも似た衝動を覚えていた。\
`　...But now... `@`he felt a childlike impulse like wanting to take a running dive into a soft hotel bed.`\


;ld c,YOS_D1,80
ld r,YOS_D3a,80

;「…………ここから飛べば、…………………。」@
`".....If I jump from here........"`@
br
;　解放されるわ。@
`　You'll be liberated.`@
br
;　……正明の心の中で、誰かが答えた。\
`　...Within Masaaki's heart, someone answered.`\`\


;ld c,YOS_D1,22
ld r,YOS_D3,80

;　そう。@解放される。@ここから飛べば、……全てから。@
`　That's right. `@`If you jump from here, `@`you'll be liberated... from everything.`@
br
;　解放って何だろう。\
`　What does it mean to be liberated?`\
bg black,22

;　……解放とは、永遠の安らぎよ。@もう、誰もあなたを苛めない。@あなたは永遠に、安らかに眠り続けることが出来るのよ……。\
`　...Liberation means eternal peace. `@`No one will ever torment you again. `@`You'll be able to sleep eternally and peacefully...`\

;　そう、心の中の誰かが答える。@
`　Yes, someone answered within his heart.`@
br
;　……それが本当なら、………彼にとって躊躇する理由など、何もない。\
`　...If what they said was true... then he had no reason whatsoever to hesitate.`\
bg Different_spiral_1a,22

me2v 17,50

;　さぁ、………飛んでみて。@
`　Come.... jump now.`@
;　それであなたは安らぎを得られるわ。@
`　And grant yourself peace.`@
br
;　……怖くないわ。@……ほら、私はここにいる。@
`　...Don't be afraid.`@` ...I'm right here.`@
;　あなたを、……受け止めてあげるから……。@
`　I... will catch you...`@
br
;　くす、くすくすくすくすくすくす……。\
`　Heehee, teeheehee...`\
textoff
fede 0,1000

E_A
se1 22
;bg white,28
;bg e013,46
bg e013,48

wait 1000

bgm1 8

;　その時、正明は多分、白昼夢を見た。@
`　Masaaki was probably having a daydream at that point.`@
;　それは不思議な不思議な、………そして美しい幻想。@
`　It was a mysterious wonder... as well as beautiful fantasy.`@
br
;　眼下に、ゆっくりと赤い花の絨毯が広がっていく、美しい幻想。\
`　On the ground below, he saw a beautiful illusion of a carpet of red flowers spreading out before him.`\

;　……それは、彼岸花の花園。@
`　...It was a garden of higanbana.`@
;　血のように赤くて儚い彼岸花が、ゆっくりと咲きながら広がっていくのだ。@
`　A fleeting carpet of blood red higanbana, slowing blooming and spreading outwards.`@
br
;　その中心に、………黒い髪の少女が立って、こっちを見上げているのだ。\
`　In the center of that flower garden..... stood a black haired girl, looking up at me.`\


ld c,HIG_w3,42

wait 1000

ld c,HIG_D2,22

;「おいで。正明。@……私が受け止めてあげるから。@くすくすくす……。」@
`"Come on, Masaaki.`@` ...I'll catch you. `@`Teeheehee..."`@
br

;ld c,HIG_D1,80

;　少女は優雅に微笑みながら、両手をこちらに差し出した。\
`　The girl gracefully smiled and extended both her arms this way.`\
;　……飛べば、……無残なこの現実から逃れられる。@
`　...If I jump... I can escape from this miserable reality.`@
br
;　そしてあの儚くも美しい、彼岸花の世界へ迎えられるのだ。\
`　And be welcomed to that fleeting, beautiful world of higanbana.`\
;　もう、学校もいじめもない。@
`　There will be no more school, no more bullying.`@
br
;　罰ゲームと称して痛いことをされることもないし。@
`　There would be no more pain in the form of punishment games.`@
;　友達だからと、恥ずかしいことを強要されることもない。\
`　There would be no more being force to do embarrassing things under the false pretense of being friends.`\
cl c,0
ld l,HIG_D3,24
;ld l,HIG_D1,80

;「……何を躊躇うの？@　……あなたにとって、そちらの世界に、何の希望があるというの……？」@
`"...Why do you hesitate?`@` ...What hope is left for you in this world...?"`@
br
;d r,YOS_D1,80
ld r,YOS_D3,22

;　……あるもんか。@この世界に、希望なんてあるものか。\
`　...Do I have any? `@`Do I have any hope left in this world?`\



;ld c,HIG_D1,80

cl l,0
mld c,HIG_w4,3


;「ならばおいでなさい。@この彼岸花の世界へ。@……さぁ、おいでなさい。@……あなたが自分で決めて、自分でここへ来るのよ。@……あなたの腕で、脚で。@……そのベランダを乗り越えなさい……。」\
`"In that case, come to me. `@`To this world of higanbana.`@` ...Come here to me.`@` ...Make your own decision, and come to me on your own.`@` ...With your own arms, and your own legs.`@` ...Climb off that balcony..."`\
textoff

se1 84

bg e005,2
mld c,HIG_d4,22

;ld r,YOS_D1,80
;bg black,22
me1v 16,50

mcl c,2

wait 1000

bg e013,2

;　正明の瞳にはもう、……一面に咲き乱れる彼岸花しか映っていない。@
`　By now... that field of blooming higanbana was the only thing reflected in Masaaki's eyes.`@
br
;　彼はゆっくりと……、ベランダの柵に這い上がろうと脚を上げる……。\
`　Slowly... he crept up to the railing of the balcony and raised his leg...`\
E_A
se1 12

bg white,1
quakey 1,200

;「待って…！！@　死んで咲く花なんて、ありはしませんっ。」\
`"Wait...!! `@`There are no flowers that bloom in death."`\
bg black,22

bgm1 27

;　突然、別の声がした。@
`　Suddenly, another voice yelled out.`@
;　その声には叱り付けるような厳しさがあり、正明は我に返った。\
`　That harsh scolding voice brought Masaaki back to his senses.`\



;bg e013,22
;mld l,HIG_D1,0
;ld r,MAR_D1,22
;ld c,YOS_D1,22


;mld l,HIG_D1,80

bg e013,0
ld c,HIG_D4,22
;ld r,MAR_D1,22

ld c,HIG_w3,80

;「………また毬枝に見つかったわ。@あんたがお菓子を探しに行ってる間に、目を付けてた子でもいただいちゃおうと思ってたのに。」\
`"....So I've been found out by Marie again. `@`While you were out looking for sweets, I thought I would try helping myself to a kid I've had my eyes on for a while now."`\


ld r,MAR_i1,22

;「お菓子は見つけてきました。@今日はモナカです。@ですから、その狩りを止めて下さい。」@
`"I found some sweets. `@`Today we're having monaka. `@`So please stop this hunt."`@
; ^^^ Note To Editor: Monaka - http://en.wikipedia.org/wiki/Monaka
br
;　彼岸花の畑には、いつの間にか眼鏡の少女の姿もあった。\
`　At some point a second girl appeared in the field of higanbana, this one wearing glasses.`\


;mld l,HIG_D1,80
cl c,0
ld l,HIG_D5,24

;「嫌よ。@それに狩りなんてとんでもない。@私は誘っているだけよ。@……彼の魂がより安らぐ世界があると、教えてあげているだけよ。」\
`"I don't want to. `@`Besides this isn't even hunting. `@`I'm just inviting him.`@` ...I'm just telling him about a world where his soul will be more at ease."`\

cl r,0
ld c,MAR_i4,24

;「……吉川くん。@考え直して下さい。@……生きていれば出来ることはたくさんあります。@でも、死んで出来ることなど、何一つありません。」\
`"...Yoshikawa-kun. `@`Please reconsider this.`@` ...There is plenty of things you can do while still living. `@`But, when you're dead, there's not a single thing that you can do anymore."`\


;mld l,HIG_D1,80
ld l,HIG_w2,80

;「生きて何が出来るの？@　何もないから、彼は苦しんでいるんだわ。」@
`"What can he do while he's alive? `@`There's nothing, that's why he's suffering."`@
ld c,MAR_i3,80

;「死んで何が出来るんです？@　死後に後悔して、苦しむだけですっ。」\
`"What can he do when he's dead? `@`After death there's ONLY regret and suffering."`\
me1v 16,50

;　正明は何が何やらわからない。@
`　Masaaki didn't know what to think.`@
br
;　これは、……夢……？\
`　Was this... a dream...?`\
mbg black,22

;　見たこともない少女が二人も現れて、言い合いをしているのだ。@
`　Two girls he had never seen before appeared out of nowhere and starting having a quarrel.`@
br
;　しかし、彼女らが何を言っているのかはわかる。\
`　But he had no idea what they were saying.`\
;　……死ねば、何もかもから解放されるだろう。@
`　...If he died, he would be liberated from everything.`@
br
;　しかし、死んだらもう、何もすることは出来ない。\
`　But after he's dead, he can't do anything anymore.`\
mcbg 22

ld l,HIG_D2,80

;「彼にはもう、生きてしたいことなんて何もないのよ？」@
`"What does he have to live for anymore? Nothing."`@
cl c,0
ld r,MAR_i1a,23

;「……そんなことないです！@　彼にだって夢や希望が！@　生きて成し遂げたいことが必ずあるはずです！@　吉川くんっ、それをどうか思い出して…！」\
`"...That's not true! `@`Even he must have hopes and dreams! `@`Things that he still wants to accomplish in his life! `@`Yoshikawa-kun, please remember that...!"`\
;mld l,HIG_D1,80
cl l,0
mld c,HIG_D4,23

;「正明。@……あなたには生きて成し遂げたいことなんてあるの…？」@
`"Masaaki.`@` ...Do you really have anything you want to accomplish...?"`@
;「……………ぅ……。」\
`".......uh..."`\
mld c,HIG_w3,80

;「私はあなたを今日までずっと見てきたわ。@……あなたは日々、何かを積み上げてきたの？@　……私は知らない。@あなたはただ、流れに身を任せて、@水面に浮かぶ木の葉のように、ただただ流されてきただけよ。@……その結果、あなたは澱みに流れ込み、そのまま朽ちて消えようとしている。@あなたの現在はまさに、その結果の至極当然の末路じゃない。」\
`"I've been watching you for a long time.`@` ...Is there something that you have been working towards?`@` ...I haven't seen it. `@`You have just given yourself up to the flow of life, `@`like a leaf on the surface of the water, just being swept along.`@` ...And in the end you will become stagnant waste and rot away. `@`As you are now that is very likely the end you will meet."`\


;ld c,YOS_D1,80
mcl c,0
bg black,22

;　………言い返せない。@
`　....He had no response.`@
br
;　正明には今日まで、何の意志も使命も目的もない。@
`　Up until today, Masaaki has had no motive, mission or goal.`@
;　彼がしてきたことはただ一つ。@……自分が受けているいじめを、そうだと頑なに認めなかったこと。@ただそれだけだ。\
`　There's only one thing he's been doing.`@` ...Refusing to admit that he's been bullied. `@`And that's it.`\


;mld l,HIG_D1,80

bg e013,0
;mld c,HIG_D1,0
ld r,MAR_D3a,0

mld c,HIG_w3,22
mld c,HIG_w4,80

;「あなたがしたのは認めないことだけ。@……認めなければ、それはいじめじゃない。@だから、自分はいじめられてないんだ。@………それだけが、あなたが生きて成し遂げたことよ。@……それの何が、生きているということになるの？」\
`"All you've done is deny.`@` ...As long as you keep denying, then it's not bullying.`@` So, you're not really being bullied.`@` ....That is all you have accomplished.`@` ...Can that really be called living?"`\


;ld c,YOS_D1,80

;　正明にとって、それは胸が痛くなるほどの正論だった。@
`　Her reasoning was so strong that it brought a pain to Masaaki's chest.`@
br
;　……彼がしたのは、心を閉ざして石になることだけ。@
`　All he had done was shut his heart away in stone.`@
;　石は人間じゃない。@それは生きていることにならないのだ。\
`　Humans are not stone. `@`That is no way to live.`\
mcl c,0
ld c,HIG_w4,0
ld r,MAR_i4,80

;「彼岸花さん、言い過ぎですっ。」@
`"Higanbana-san, you've said too much."`@
;mld l,HIG_D1,80
cl c,0
ld l,HIG_D1,24

;「図星じゃないの。@くすくすくすくす……。」\
`"But isn't it the truth? `@`Teeheehee..."`\
ld r,MAR_i1a,80

;「確かに、今までの彼はそうだったかもしれません。@でも、生きている限り、これからもそうとは限りませんっ。@人は生きている限り、常に何かを試み、成し遂げることが出来るんですっ。@死ぬなんて短気は、それを全て投げ出すだけなんですっ。」\
`"He may have been living his life like that up until now. `@`But, that doesn't mean he has to live that was for the rest of his life. `@`As long as people are alive, they can constantly try and accomplish new things. `@`If you kill yourself on an impulse, you've thrown that all away."`\

;mcl l,0
bg black,22
;bg e002,22

;　……生きている限り、出来ることはある。@
`　...As long as you're still alive there are things you can do.`@
br
;　死ねば、……何も出来はしない。\
`　When you die... you can't do anything.`\

;　思えばそれは、悲しくもあり、悔しくもあった。@
`　Thinking of it that way is both sad and frustrating.`@
;　自殺に踏み切る勇気があるなら、……捨て身の覚悟で何かが出来るはずなのだ。\
`　If you have the nerve to jump to your own death... then you have the resolve to risk your life.`\
;bg black,22
mld c,YOS_D14,22
;mld c,YOS_D1,80

;　……自分を自殺に追い込むということは、……それは彼らが自分を殺したのと同じことじゃないか。@
`　...Being driven to my own death... isn't that the same as being killed by those guys?`@
br
;　なら、自分だけが殺されて堪るものか。@
`　Then why should I be the only one to die.`@
br
;　同じ死ぬのでも、……せめて一矢報いてからじゃなきゃ、……悔し過ぎる……。\
`　Even though I meet the same end... doing so without fighting back at all... it's just too frustrating...`\


;bg e013,22
;mld l,HIG_D1,0
;ld r,MAR_D1,0
;ld c,YOS_D1,22

ld r,HIG_w3,22
;ld r,HIG_D1,80

;「………あら。@死ぬ気が薄れてきちゃったわ。@……毬枝のせいよ。@もう一息でぺろりといけたものを。」\
`"....What's this. `@`Looks like he's losing the want to die.`@` ...This is your fault, Marie. `@`Just one more push and I would have had him."`\


;ld r,MAR_D1,80
ld l,MAR_i4,22

;「吉川くんっ。@死ぬ覚悟があるなら、死ぬ前にやれることなんていくらでもあるのっ。@だからお願い、勇気を出して…！」\
`"Yoshikawa-kun. `@`If you have the resolve to die, then before you do die there are many things you can do. `@`So please, show some courage...!"`\
;ld c,YOS_D1,80
mld c,YOS_D13,80

;「…………勇気………。」\
`".....Courage......"`\


;ld r,MAR_D1,80
ld l,MAR_i1,80

;「諦めないで、みんなに相談してみてっ。@……先生やお父さんやお母さんや友達や……！」\
`"Don't give up hope, try talking to everyone.`@` ...To your teachers, your father, your mother, and your friends....!"`\

;ld c,YOS_D1,80
mld c,YOS_D14,80
se1v 12,30
quakex 2,200

;「そ、………相談しても、誰も聞いてくれねぇよ……！」@
`"E-... Even if I talk, none of them will listen...!"`@
br
me2v 17,50
;　正明の心が、怒りと悲しみで震えた。\
`　Masaaki's heart trembled with anger and sorrow.`\


;mcl l,0
;bg black,22
;mono 1

mcl c,0
bg black,22
mono 1
bg shokuin_01,22


;　先生にも相談したが、喧嘩両成敗みたいな扱いで、まったく庇ってくれなかった。@
`　He tried talking to his teachers, but they just treated him like he was too blame as well, and wouldn't protect him at all.`@
;　両親も仕事のことで頭がいっぱい。@子供の喧嘩に親は出ない、みたいなことを言って、まったく相手にしてくれない。@
`　As for his parents, all they cared about was work. `@`They would always say something about parents not getting involved in fights between children, and wouldn't help him at all.`@
br
;　相談できるような友達なんていやしない…！\
`　And he didn't even have any friends that he could honestly talk to...!"`\
;ld c,YUK_D1,22
bg black,22
ld_p YUK_D1
lsp2 2,$ld_pass,400,480,200,200,0
lsp2 3,$ld_pass2,400,480,200,200,0
print 22

;　……その時、正明の脳裏にわずかに、由香里のことが過ぎった。@
`　...And then, in the back of Masaaki's mind, he remembered Yukari.`@
br

csp2 -1
print 22
mono 0

;　しかし、すぐにぶるぶると頭を振る。\
`　But he quickly shook the thought out of his head.`\
;quakex 2,400
;cl c,22
;bg black,0
mono 2
bg different_spiral_1a,22

;　ふざけんなよっ……。@俺はいじめられてなんかいないんだ……。@女なんかの助けなんかいるもんか…！@
`　Screw that.... `@`I'm not being bullied... `@`I don't need a girl to help me...!`@
br
;　あの女、いつもお節介ばかり焼きやがって…！@　お前は楽しいかもしれないが、女に庇われて、俺はいつも惨めな気持ちになるんだよッ！\
`　That girl is always meddling in people's business...! `@`It may be fun for you, but for me, being saved by a girl is miserable!`\

;　畜生、畜生ッ！@　どいつもこいつも俺のことを馬鹿にしやがって…！！@
`　Damn it, damn it! `@`everyone keeps looking down on me...!!`@
br
;　これで俺がまんまと自殺したら、あいつら、何て言うんだ？\
`　If I killed myself right now, what would they say?`\

;　葬式では一丁前に悲しんでるフリして、@うちの親には、大の仲良しでしたとか、しゃあしゃあと言うのかよ？！@
`　Would they just casually attend my funeral and pretend to grieve my passing? `@`Would they go up to my parents and shamelessly tell them they were good friends of mine?!`@
;　で、いい思い出にして、@昔はチョイ悪でいじめとかしてたことがあるんだーって、武勇伝気取りかよ？！@　ふざけんなよ、ふざけんなッ！！@　死んで堪るか、殺されて堪るかよ！！\
`　And then, would they talk about the 'good times', `@`and talk about how I was bullied by some bad kids, and pretend that they were the heroes of the story?! `@`No, FUCK THAT!! `@`Like hell I'm gonna die! Like hell I'm gonna be killed!!`\
;bg black,0
bg black,22
mono 0

fede 10,1000
E_MA

;bg e013,22
bg e013,22
;ld c,HIG_D1,0
;ld r,MAR_D1,22

ld c,HIG_D4,22

;「…………良かったじゃない。@あの子、生きる気力、出てきたみたいよ。」@
`".......Well this isn't good. `@`Looks like he's got the will to live again."`@
ld l,MAR_D2a,22

;「ちょ、ちょっと違う方向にみたいですけど……。」\
`"It-, it looks like he's taking it a different direction than I intended though...."`\
;　正明の心を怒りが満たすにつれ、眼下に飛び降りたいという、死への誘惑は霧散していく。\
`　As Masaaki's heart filled with anger, his want to jump to his death rapidly vanished.`\
;se1 6
cl a,0
;se1 6
;print 99,1000,"trvswave.dll/r"
print 99,2000,"trvswave.dll/r"

bg black,2

;silent 3,1

fede 0,2000
E_A

bg koutei_03,2
me1v 16,50

;　すると、二人の少女の姿も一面の彼岸花もゆらりと消え、@……黄昏色に染まる校庭の景色に戻るのだった。@
`　And thus, the two girls and the field of higanbana gradually disappeared... `@`and the view of the schoolyard dyed in twilight reappeared.`@
br
;　正明は肩でぜいぜいと息をしながら、……ベランダの柵を叩く。\
`　Breathing heavily... Masaaki hit the railing of the balcony.`\
se1 8
quakey 1,100

;ld c,YOS_D1,22
;ld c,YOS_D1,80

ld r,YOS_D9,22
ld r,YOS_D10n,80

bgm1 14

;「……死ぬくらいなら、……むしろ俺が殺してやるッ。@…………でも、そんなことしたって、結局、逮捕されるだけ……。@そしてあいつらは逮捕された俺のことを、@おかしなヤツだったとか普段からキレるヤツだったとか、適当なことをしゃあしゃあと言いやがるに決まってるんだ……。@/
`"...If I'm willing to do... then I'll kill instead.`@` ......But even if I do that, in the end I'll just end up getting arrested... `@`And if I do get arrested, those guys would just say I was always a strange guy, and was always snapping like that, and keep shamelessly giving excuses to take the blame off them...`@/
;ld c,YOS_D1,80
;ld r,YOS_D1,80

;………くそッ、くそッ……。@………悔しい、悔しい……。@このまま死んでなんかやるものかッ。@……絶対に生きて、……あいつらに仕返ししてやる……。」\
` ....Shit, shit...`@` ....This is annoying, so annoying.... `@`There's no damn way I'm going to just lay down and die.`@` ...I'm definitely going to live... and get even with those bastards..."`\
cl r,22

;　………でも、どうやって………。@
`　....But, how.....?`@
br
;　……………………………。\
`　..............`\
bg black,22

fede 10,1000
E_MA

;　殺すなんてこと、出来るわけがない。@
`　There isn't really a way for him to kill them.`@
;　刺し違えることは出来るだろうが、……結局、自分も殺されたり、あるいは逮捕されたり。@………無事では済まない。@
`　He could maybe try to take them to the grave with him... but in the end that would leave him dead too, or at the very least, arrested.`@` ...It was a double-edged sword.`@
br
;　……怒りに飲まれ、様々な物騒なことを考えはしたが、……結局、どれもやれはしない。\
`　...Engulfed in his anger, he continued to think many terrible thoughts... but in the end, none of them would have worked.`\
bg koutei_03,22
;ld r,YOS_D1,22

;　現実的な仕返しの方法はせいぜい、@………こっそりと上履きの中に画鋲を入れるとか、そんなことがせいぜいだ。@
`　Realistically speaking, the best he could do for revenge.... `@`was to sneak some tacks in the indoor shoes in their shoe lockers.`@
br
;　それに、どうせすぐ自分が疑われるに決まってる。\
`　But even then, it's obvious that he would be the first person they would suspect.`\

;ld c,YOS_D1,80

;　彼らのことだ。@別に証拠なんか何もなくても自分のせいにされ、より酷い仕打ちを受けることになるだろう。@
`　But this is those bullies he's talking about. `@`If they even so much as suspect he's behind something like that, they wouldn't hesitate to start treating him even worse.`@
br
;　正明はゆっくりと踵を返し、教室に戻る。\
`　Masaaki slowly turned on his heels, and went back in to the classroom.`\
;bg black,1
;mono 0


;bg e005,22

bg black,23
bg kyou_02u,23

;　……もう、死にたいとは思わない。@
`　...He no longer wanted to die.`@
;　出来ることなら、仕返しがしたい。@
`　He wanted to have his revenge in whatever way possible.`@
br
;　死ねば永遠にそれが出来なくなるのだから。\
`　If he died, he would never be able to do that.`\
ld c,YOS_D13,22

;　……今日までの借りを返す権利が、自分にはあるのだ。@
`　...He had the privilege to repay everything that had been done to him up until now.`@
;　その権利を自ら捨てるなんて、……馬鹿馬鹿しいし、何より悔しかった……。@
`　Too willingly throw that privilege away... that's beyond stupid, and beyond aggravating...`@
br
;　彼は、今こそはっきりと自覚する。@自分がいじめられっこであったことを、はっきりと自覚する。\
`　He was now painfully aware of his situation. `@`He knew all too well that he was being bullied.`\

;bg black,0
;bg kyou_02u,23
;ld r,YOS_D1,22
ld c,YOS_D14,80

;「いつか絶対、仕返ししてやる……。@絶対、……いつか……、……畜生……。」@
`"At some point, I WILL have my revenge.... `@`Eventually... I WILL....... Damn it...."`@
br
;　由香里が望んだ形とは違うが、@……彼がいじめられっこであることを自覚し、自殺という方法で逃れようと思わなくなっただけでも、@良しとすべきかもしれない……。\
`　It was different than the way Yukari would have wanted... `@`but because he finally accepted that he was being bullied, and wasn't trying to kill himself to escape from it, `@`she would probably have to agree with him...`\


;bg black,22
;bg akiti_1y,2

bg black,22
bg shoukou_01,22

;　正明はとぼとぼと下校する。@
`　Masaaki walked wearily home.`@
br
;　俯きながらも、……やり場のない怒りに両拳を震わせるのだった……。\
`　With nothing to take his rage out on... he cast his eyes down at the ground, while clutching his fists so hard they trembled...`\
bg black,2

fede 0,2000
E_A

bg akiti_2y,22

me1v 5,50

;　途中、大きな空き地があった。@
`　On his way home he walked past a large vacant lot.`@
br
;　本来は宅地だろうが、手入れされておらず、雑草が茂るに任されている。\
`　It was probably originally a housing site, but it fell into disrepair and the weeds were left to run rampant.`\


;bg akiti_2y,23

;　そこは一面にアザミの紫の花が咲く、アザミ畑のようだった……。@
`　Throughout that field, the purple flowers of thistles bloomed. It was like garden made for thistles...`@
; ^^^ Note To Editor: The word for thistle in Japanese is "azami" (アザミ). Azami is the name of the youkai that's going to be introduced in this chapter. This is probably going to need a glossary entry. I can make one once I'm done translating chapters. - Jorwil 
br
;　正明はふと足を止める。@
`　Masaaki suddenly stopped in his tracks.`@
;　そして、アザミの茂みに足を踏み入れた。\
`　And stepped into the thicket of thistles.`\

;bg black,0
;bg azami1,24
;ld r,YOS_D1,24
;ld r,YOS_D1,80

bg black,24
bg azami1,24

;　………アザミの花に関する、……何か話がなかったっけ………。@
`　....Wasn't there... some sort of story about thistles that he heard somewhere....?`@
br
;　そうだ。@……学校の八不思議の中に、アザミの話があったような……。\
`　That's right.`@` ...There's a story about thistles in one of the Eight School Mysteries...`\

;bg black,1
mbg black,22

E_A

;「学校や通学路の途中に咲き乱れる、紫のアザミの花。@……その花言葉は、復讐。」\
`"A field of blooming thistles at school, or on the way home from it.`@` ...In the language of flowers, they represent revenge."`\

;bg akiti_2y,22
mcbg 22

me1v 16,50

;　突然、女性の透き通るような声が聞こえた。@
`　Suddenly, he heard a disembodied female voice.`@
br
;　周りに人の気配などないはずなのに、………一体、誰がどこから。\
`　There isn't anyone standing next to him.... so where did that voice come from?`\


;bg black,24
;bg azami1,22
;ld c,AZA_D1,22

bg white,24

bg akiti_2y,24
;bg azami1,0

ld c,AZA_D2,42

fede 0,1000
E_A

ld c,AZA_D1,22

bgm1 18

;　……その時、ざぁっと風が吹き、アザミの花々を波のように揺らめかせた。@
`　...At that moment, a strong breeze passed by and blew the thistles back and forth like a wave.`@
br
;　そのアザミの花々の中に、……いつの間にか、少女、……いや、女性が立っていた。\
`　And within the blink of an eye... there in that field of thistles stood a girl... no, a woman.`\

;　中学生かもしれないし高校生かもしれない。@……いや、あるいは大学生かも。@
`　She may have been a middle schooler, or high schooler.`@` ...No, it's more likely that she was a college student.`@
br
;　整った顔立ちと、長く美しい髪はとても知性的で、とても大人っぽく見えた……。\
`　Her sculpted face and long, beautiful hair made her seem very intellectual and adult-like...`\
ld c,AZA_D2,80

;「ずっといじめられていた気の毒ないじめられっこが、@……クラス替えや夏休み明けに、人が変わったかのように豹変し、@いじめっこに生まれ変わることがあるいう。@………それは、復讐の力を宿らせる、魔法のアザミの仕業……。」\
`"A pitiful child who was always being bullied.... `@`suddenly becomes a new person after changing classes or coming back from summer break, `@`and are born anew as a bully themselves.`@` ...That is the revenge granting power of a magical thistle..."`\


bg black,22

;「………そうだ…、思い出した……。@……学校八不思議の一つ。@……復讐の、アザミ……。」\
`"....That's right... I remember...`@` ...That's one of the Eight School Mysteries.`@` ...Azami the Vengeful..."`\
bg Different_spiral_1b,22

;　それは学校八不思議が語る内の一つ。@
`　It was one of the eight ghost stories of the school.`@
br
;　時折、前学期までは気弱ないじめられっこだった子が、@長期休暇が明けると、まるで別人のように生まれ変わることがある。@
`　Occasionally there would be a timid, bullied student who would come back after a long vacation, `@`and upon the start of the new term, would be born again as a different person.`@
br
;　それは、魔力の宿る、復讐のアザミの花を、食べたから。\
`　That was because they ate a magical thistle from Azami the Vengeful.`\


bg azami4,2

;　学校にも通学路にも、当り前のように見られるアザミの花。@
`　At school, and on the way home, there were plenty of ordinary looking thistles.`@
;　その中に稀に、魔法のアザミが混じっているらしい。@
`　But every once in a while, there's apparently a magical thistle mixed in with them.`@
br
;　そして、そのアザミは、いじめられっこにだけ見つけることが出来るという。\
`　And only those who are bullied can see it.`\


;　……その花を食べると。@
`　...If that bullied child eats that flower,`@
br
;　いじめられっこは、それまでの悔しさの分、@より恐ろしいいじめっことして生まれ変われるという……。\
`　The frustration they had felt up until then, `@`will be overtaken by anger and they will be born anew as a bully themselves...`\

bg black,22

;　学校では、唐突に性格が変わった子がいると、@アザミでも食ったんじゃねぇ？　と囁く子がいるが、@それはこの「復讐のアザミ」のことなのだ……。\
`　Whenever a kid shows up to school and their personality has done a complete 180, `@`you'll often hear some kids whispers between themselves, `@`'Did they eat a thistle?' `@`When they do, they're referring to this story of 'Azami the Vengeful'....`\
;bg akiti_2y,22
;ld l,AZA_D1,0
;ld r,YOS_D1,22

bg akiti_2y,22
;ld r,YOS_D1,22

ld c,AZA_D1,22
;ld l,AZA_D1,80

;「こんにちは、吉川正明くん。@妾の姿が見えますか……？」\
`"Hello. Masaaki Yoshikawa-kun. `@`I assume you can see me...?"`\

ld r,YOS_D3a,80

;「………え、……ぁ、………はい……。」@
`"....Oh-... uh.... Yes...."~@
br
;　その不思議な問いに、正明はすぐに理解する。@
`　Masaaki instantly knew what she meant by asking such a strange question.`@
;　彼女の姿は、見えざるものなのだ。\
`　He knew that she was a being who could not normally be seen.`\


;　……自分は今、……この世ならざる何者かと話をしている……。@
`　...Right now... he was speaking to a something not of this world....`@
;　決して威圧されているわけではないのだが、その不思議な貫禄に、全身が竦むのを覚えた。\
`　He was in no way intimidated by this encounter, but nevertheless, every muscle in his body tensed at her presence.`\
cl c,0
ld l,AZA_D2,24

;「怯える必要はありません。@妾の名はアザミ。@……学校妖怪序列第４位、復讐のアザミとは妾のこと……。」@
`"There is no need to be frightened. `@`My name is Azami.`@` ...Fourth Ranked of the School Youkai, Azami the Vengeful..."`@
ld r,YOS_D9,80

;「…………復讐の、アザミ………。」\
`"......Azami, the Vengeful....."`\


ld l,AZA_D3,80

;「可哀想に。@妾の姿が見えるということは、あなたが気の毒ないじめられっこということです。@………そうですね……？」@
`"How unfortunate. `@`If you can see me, then that means you're a pitiful bullied child.`@` ...Is that true...?"`@
ld r,YOS_D3a,80

;「ぅ…………………。」\
`"uh........"`\


;bg black,22
;ld c,YOS_D1,22

mbg black,22
;mono 1
;bg kyou_02,0
;ld c,YOS_D1,22


;　かつての正明なら、自分はいじめられていないと激高しただろう。@
`　If someone had said that to him earlier, he probably would have gotten enraged and refused to accept the fact.`@
br
;　しかし今の彼は違う。@……自分がいじめられてきたことを、しっかり自覚している。\
`　But he is different now.`@` ...He fully understood his own situation.`\
mcbg 22

;　……だから今日、彼女のような存在に出会えたに違いない。@……正明はそれを理解する。\
`　...That was surely the reason why he met her today.`@` ...Masaaki knew that.`\
ld r,YOS_D10a,80

;「……あの、復讐のアザミの話は本当なんですか……。」@
`"...Umm, is the story of Azami the Vengeful really true...?"`@
ld l,AZA_D4,80

;「本当です。@……復讐の力を与える、魔法のアザミ。@それがどれなのか、見分けることが出来るのは、その力を真に欲するいじめられっこのみ……。」\
`"It's true.`@` ...A magical thistle that grants the power of revenge. `@`The only ones who can find them are the bullied children who truly want that power..."`\



ld r,YOS_D10,80

;「そのアザミは、……本当にあるんですか……。」@
`"And does that thistle... really exist...?"`@
ld l,AZA_D1,80

;「あなたが、真に欲するなら。@……魔法のアザミは自ずからあなたにその存在を囁きかけるでしょう。@……御覧なさい。@この紫のアザミたちを。」\
`If you truly want them to.`@` ...Then the thistle will whisper to you.`@` ...Look here. `@`At these purple flowers. "`\


;bg azami1,23
bg black,24
bg azami1,24

me1v 16,50

;　アザミが、御覧なさいと紫の花々の茂みを示す。@
`　Azami pointed to the thicket of purple flowers.`@
br
;　……その中に、……魔法のアザミが混じっているのだろうか……。\
`　...Somewhere in there... there was a magical thistle mixed in...`\


;「よく目を凝らし、そして耳を澄まして、じっくりと探して御覧なさい。」@
`"Strain your eyes, and clear out your ears, and try to find one."`@
;「……………………………………。」@
`"................."`@
br
;　無数に咲く紫の花。\
`　There were countless purple flowers.`\


;　……どれもこれも、ただのアザミに見える。@……特別なものが混じっているようには思えない。@
`　Each and every one looked like just a normal thistle.`@` ...It didn't look like there were any special ones among them.`@
br
;　いや、……そんなことはあるものか。\
`　No... there must be one.`\


ld l,AZA_D1,0
ld r,YOS_D3a,22

;ld r,YOS_D1,80

;　今こうして、自分はこの世ならざる存在の姿を見て、会話までしている。@
`　He's already seen and had a conversation with something not of this world.`@
br
;　ならば、あるはずだ。@
`　So there must be one.`@
;　いじめられっこにしか見つけることの出来ない、この世ならざる花が、@見つけられるはずだ………。\
`　There's an otherworldly flower in here that only those who are bullied can find, `@`and he should be able to find it.....`\
ld r,YOS_D2,80

E_MA

;　……その時、……アザミの茂みの中から、……かすかな音を聞いた気がした。@
`　...And then... coming from that thicket of thistles... he felt like he could hear a faint noise.`@
br
;　それは、風に揺れる小さな鈴のような音。\
`　It was like a small bell being shaken by the wind.`\
;cl a,0
;bg black,1
;ld c,YOS_D1,80

bg black,25

;　確かに聞こえる。@
`　He was certain he could hear it.`@
br
;　風が花を揺らす時、それに混じってかすかに聞こえるのだ。\
`　Whenever the wind blew through the flowers, he could hear that faint noise as well.`\
bg azami1,0
ld c,YOS_D2,22

;　正明は茂みににじり寄り、……音の聞こえた辺りの花々を、じっと凝視する……。\
`　Masaaki ventured further into the thicket... staring intently at the group of flowers where he heard the sound coming from...`\

bg black,22
bg azami2,22

;　………するとやがて、……不思議なアザミを見つけた。@
`　....And finally... he found a strange looking thistle.`@
br
;　それは、かすかに花が光を帯びているように見えた。@
`　It looked like the flower was tinged with a faint light.`@
;　蛍の光を思わせるくらいに、それはか細くか弱い。\
`　It was a very weak and delicate light, like that of a small firefly.`\


;　しかし、いじめ抜かれて心を暗くしてしまった、哀れな子には、@その心の暗闇ゆえに、そのわずかの光が、確かに見えるのだ……。\
`　But to a miserable child, with a heart darkened by bullying, `@`this faint light is be clearly visible...`\


ld r,YOS_D3a,22

;「………こ、……これ…………？」@
`"....Is-... is it this.....?"`@
ld l,AZA_D1,22
ld l,AZA_D2,80

;「よくぞ見つけました。@……そう。@それが復讐の魔力を秘める、魔法のアザミです。」\
`"Good work.`@` ...Yes. `@`That is the magical thistle, containing the power of revenge."`\


;　ぶちりと、そのアザミを摘む。@
`　He picked the thistle from the ground.`@
br
;　ちりんとかすかな音がした。@……摘んでも、花のほのかな光は消えなかった。\
`　It made a quiet ringing sound.`@` ...Even when plucked from its roots, the faint light coming from the flower did not disappear.`\
cl l,0
ld c,AZA_D1,23

;「その花を食べれば。@あなたに魔法の力が宿るでしょう。」@
`"If you eat that flower, `@`you will gain its magical power."`@
ld r,YOS_D4a,80

;「…………そうすれば、……僕は、……いじめっこになれる……？」\
`".....And when I do so... I will... become a bully...?"`\
cl c,0
ld l,AZA_D2,24

;「あなたがこれまで酷くいじめ抜かれたならいじめ抜かれたほど。@……その魔力は強まり、@あなたを、誰もが怯えるいじめっこに生まれ変わらせてくれるのです。」@
`"Depending on exactly how bad you have been bullied up until now.`@` ...The strength of its magic will increase. `@`And it will remake you into a bully feared by all."`@
ld r,YOS_D8a,80

;「も、もう、……誰にもいじめられなくなる……？」\
`"I-, I... won't be bullied anymore...?"`\
bg black,22

;ld l,AZA_D1,80

;「あなたは、いじめっこをいじめようと思ったことはありますか？@　……ないでしょう？@　いじめっことは、いじめの風上に立つ者のこと。@あなたがいじめっこであり続ける限り、@もはや誰も、あなたをいじめることなど叶わぬのです。」@
`"Do you think that bullies ever get bullied by other bullies?`@` ...Of course they don't. `@`Bullies are people who live hand in hand with bullying. `@`As long as you keep bullying others, `@`you yourself will never be bullied again."`@
;「…………………………。」\
`"............"`\
;　この花を食べれば、……仕返しが出来る。@
`　If I eat this flower... I'll have my payback.`@
;　自分に今まで酷いことをしてきたあいつらに、復讐が出来るのだ。\
`　Revenge for every horrible thing that they've done to me up until now.`\
bg akiti_2y,22

;　……夜、布団を噛みながら思い描いたことはある。@
`　...All the ways that he's imagined getting his revenge while biting his pillow at night in desperation.`@
br
;　自分がいじめっこに生まれ変わることが出来たら、逆にあいつらを絶対にいじめてやる。\
`　If he could be born again as a bully, he could turn the tables on those bullies and give them a taste of their own medicine.`\

;　そしたらきっと愉快だろう、痛快だろうと……。@
`　And then, he would be happy, and filled with pleasure...`@
br
;　この花を食べれば、……それが現実になる………。\
`　If he eats this flower... all of that will become reality....`\
bg black,22
bg azami2,22
;ld l,AZA_D1,0
;ld r,YOS_D1,22

;ld r,YOS_D1,80

;　正明は躊躇うことなく、その花を食い千切り、噛み砕いた。\
`　Without hesitation, Masaaki bit the flower off of its stalk and chewed.`\
;　……口の中に渋みが広がる。@吐き出したい衝動に駆られる。@
`　...A bitter taste spread throughout his mouth. `@`An urge to throw up overcame him.`@
;　でも、吐き出さず、尚も噛み締める。@
`　But he didn't spit it out. He kept chewing.`@
br
;　その魔力を、余すことなく吸収するために……。\
`　He wanted to make sure that he absorbed every last bit of magic power it held...`\
bg black,22
bg azami1,0
ld r,AZA_D2,22


ld r,AZA_D1,80

;「世は常に因果応報であらねばなりません。@悪人には報いを。@善人には労いを。@……しかし、時代は変わりました。@今や学校では、いじめっこという悪人が、@何ら罰せられることなく青春を謳歌して卒業し。@いじめられっこという善人が、生涯癒せぬ傷を背負わされて、社会に放逐されていきます。@………それは、天の摂理に反することです。」\
`"In this world there must always be retribution. `@`Punishment for those who are evil. `@`And reward to those who are good.`@` ...But the times have changed. `@`Now there are villains known as bullies attending school, `@`and they run free, doing what they want, and enjoying their youth right up until they graduate with no punishment whatsoever. `@`Meanwhile, good natured kids are thrown out into society with the trauma still holding the trauma caused by those bullies.`@` ...That goes against the laws of karma."`\

ld l,YOS_D3a,22
;ld l,YOS_D1,80

;　正明はごくりと、充分に噛み砕いたアザミを飲み込む。@
`　With a gulp, Masaaki swallowed down the chewed thistle.
;　口の中は渋みでいっぱいで、気持ち悪かった。\
`　His mouth was filled with an awful bitter taste.`\
se1v 55,30
bg red1,48

se2v 22,30
bg black,22
;bg black,1
;bg e002,22
;bg e005,26

;　でも、胃袋の中には不思議な熱を感じる。@
`　But he felt a strange heat rising in his stomach.`@
br
;　それが何かの力を全身にゆっくりと巡らせていくのを、確かに感じていた……。\
`　He was sure the feeling was that of some sort of power slowly spreading throughout his entire body...`\
bg azami2,22

;「いじめる者はいじめられることを知らねばなりません。@そして、いじめられる者はいじめることを知る権利があります。@昼があれば夜があるように、夏があれば冬があるように。@……あなたが生まれ変わることは、何もおかしいことではないのです。」\
`"Those who bully must know should know what it's like to be bullied. `@`And those who are bullied have the right to know what it's like to be the bully. `@`Like night exists because there is day, like winter exists because there is summer.`@` ...It is not that odd for you to be born again."`\
bg black,22
bg akiti_2y,22
ld r,YOS_D8a,22
;ld r,YOS_D1,80

me1v 5,50

;「これで……、俺は、……いじめっこに……。」@
`"With this... I will... become a bully..."`@
br
;　まだ実感はない。@しかし、胃の中の熱い何かは、紛れもなく本物だ。\
`　It still didn't feel real too him. `@`But the warmth in his stomach was, without a doubt, the real thing.`\

;bg black,1
;bg azami1,22
;ld l,AZA_D1,0
;ld r,YOS_D1,22

ld l,AZA_D2,22
;ld l,AZA_D1,80

;「その復讐の魔力は、明日、学校に行けば、すぐにも理解できるでしょう。@あなたの望むままにお生きなさい。@あなたは今日まで、何を望むことも許されなかったのですから。」@
`"By the time you go to school tomorrow you will instantly realize its magical power of revenge. `@`Live as you wish to from now on. `@`Because you have not been able to do so until today."`@
ld r,YOS_D4,80

;「……あ、ありがとう……ございます……。」\
`"...T-, thank... you..."`\
ld l,AZA_D4,80

;「礼などいりません。@どうしてもしたいならば、@今日まで耐え忍んできた、昨日までの自分にすると良いでしょう。@……妾は、いつもあなたの側で見守っていますよ……。」@
`"No need for thanks. `@`If there's anyone you should thank, `@`it's the you of yesterday who endured so you could reach today.`@` ...I will always be watching over you..."`@
ld r,YOS_D6,80

;「ありがとうございますっ、アザミさん…！！@　本当にありがとうございますっ！！」\
`"Thank you, Azami-san...!!`@ Thank you very much!!!"`\
ld l,AZA_D2,80
cl l,2

;　アザミが微笑むと、……その姿はゆっくりと透き通って消えていく。@
`　Azami smiled... and slowly began to fade away.`@
br
;　そしてもう一度、ざぁっと風が吹く。\
`　The wind blew one more time.`\
mbg white,24
mcbg 22

;　もうその姿は、完全に掻き消えていた。@
`　And with that, her body completely disappeared.`@
br
;　……後には、アザミの茂みの中に、自分がひとり、取り残されている。\
`　...And he was left standing alone in the thicket of thistles.`\


;ld r,YOS_D1,80
cl r,0
ld c,YOS_D7,24

;　今のは丸々、白昼夢だったのではと疑いたくもなる。@
`　He wanted to believe that what just happened was all a daydream.`@
br
;　しかし、……胃の中の熱さは収まらない。\
`　But... the warmth in his stomach was still there.`\


;ld r,YOS_D1,80
ld c,YOS_D8a,80

;　正明は自分の両手を見る。@
`　Masaaki looked down at his hands.`@
;　手の平にも、何か熱さが宿ったように感じた。@
`　He could feel a warmth spreading through the palms of his hands as well.`@
br
;　自分は本当に、……いじめっこになれたのだろうか。\
`　Could he... really become a bully?`\


;　全ては、明日の学校でわかる。@
`　He'll find out at school tomorrow.`@
br
;　正明はぐっと両手を握り締めながら、空き地を後にするのだった……。\
`　Masaaki clenched his hands into fists and left the vacant lot behind...`\
cl c,2

fede 1,2000
E_B

wait 1000

;bg black,22
;bg akiti_2y,0
;bg akiti_1y,22
ld r,AZA_D1,22

;　その正明の後姿を、アザミは見送っていた。@
`　Azami was watching Masaaki walk off into the distance.`@
;　すると、もう一人の妖怪が、すぅっと姿を現した……。\
`　Just then, another youkai appeared next to her...`\
E_A

mov %SMI_Isyou,2
ld c,SMI_w1,2
ld c,SMI_w3,80

bgm1 28

;「さすがは姉者なのじゃ！@　いつもながら、見事なお手並みなのじゃ…！」@
`"As expected of my big sister! `@`You're as skillful as ever...!"`@
;＜スミレ

ld r,AZA_D4,80

;「うふふふふ。@……スミレ、人間は脅しても動きません。@認め、肯定し、唆すのが何よりも最良なのですよ。」\
`"Ufufufu.`@` ...Sumire, humans won't act even when threatened. `@`The best way to get them to do something is through acceptance, positive affirmation and enticement."`\


ld c,SMI_w4,80

;「姉者の唆しは天下一品なのじゃ！@　私も昔はそれに引っ掛かって、何度もおやつを横取りされたのじゃ…！@/
`"Your ability to entice is unsurpassed! `@`I too once fell for something like that and had many of my snacks taken from right under my nose...!`@/
;cl l,23
;mld c,AZA_D1,23
;ld r,SMI_D1,80

se1 47
;cl l,0
ld r,AZA_D5,80

ld c,SMI_i3a,80
quakex 1,100

;　あいだだだだだだッだだだッ…！！」\
` Ahh OWOWowowowOWowouch...!!"~\
ld c,SMI_i1,80

se1 48
quakex 2,200
se2 47
quakey 2,200
se1 48
quakex 2,200
se2 47
quakey 2,200

;cl a,0
;ld l,AZA_D1,0
;ld c,SMI_D1,24


;　アザミはにこやかな笑顔で、スミレの頬を、まるでお雑煮のお餅のように、びろーんとひん伸ばして抓り上げる。\
`　With a smile on her face, Azami pinched Sumire's cheeks and stretched them out like two balls of mochi.`\

;mcl c,0
;■ｱｻﾞﾐ背景
;bg black,22
;ld l,AZA_D1,0
;ld r,SMI_D1,22


;mld c,AZA_D1,80
ld r,AZA_D4,80

;「可愛い妹のたっての頼みです。@たまにはあなたの話にも乗ってあげましょう。」\
`"If my cute little sister requests it, `@`I could help you out with your hunts every now and again."`\

;ld r,SMI_D1,80
cl c,0
ld l,SMI_w4,24
ld l,SMI_w2,80

;「ふ、ふふふふひひひはははは…！！@　私は前回の恨みを忘れてはおらぬのじゃ！@　おのれ彼岸花め、@私の育てし可愛い可愛いいじめの花たちを、ぜーんぶ横から掻っ攫いおったあの恨み、忘れはせぬのじゃ！@/
"Heh, fufufuhihihihahaha...!! `@`I still bear a grudge for what she did to me last time! `@`That damnable Higanbana. `@`I still haven't forgiven her for stealing away all my cute little flowers I raised to be bullies!`@/
;ld r,SMI_D1,80

;　……だが、彼岸花はおっかないからのぅ。@あやつに仕返しはちょいと難しいのじゃ。」\
` ...But Higanbana's fierceness is nothing to bat an eye at. `@`Getting my revenge on her may be difficult."`\


;mld c,AZA_D1,80
ld r,AZA_D5,80

;「それで目標を変更した。@……スミレは偉いです。@届かぬ高望みはいけません。」\
`"And thus you changed your goals.`@` ...You are so admirable, Sumire. `@`It's not good to set your sights too high."`\
cl l,0
mld c,SMI_D7,23
se1 2
quakey 2,200

;「許せんのは彼岸花ではないぞ、あの榊由香里じゃッ。@人間の分際で私を愚弄しおったのだ…！@　いじめは許さぬなど、よくも私を前に偉そうなことを！」\
`"It's not Higanbana that I can't forgive, it's that Yukari Sakaki. `@`How dare she spout those pretentious words to me about how bullying is wrong...! `@`A mere human made a mockery of me!"`\
ld r,AZA_D3,80

;「くす。@いじめは摂理。@それを否定することは、日に沈むことを拒むも同じ、愚かなこと……。」\
`"*giggle* `@`Bullying is divine intervention. `@`Trying to prevent it is just as foolish as trying to stop the sun from setting...."`\
mld c,SMI_w6,80

;「さぁ、由香里よ…！@　我ら、アザミスミレ姉妹の巻き起こすいじめに、どう抗うか見せてみるがよいのじゃっ。@ふっふふふ、ひっひひひはっははははははははッ！！\
`"Come, Yukari...! `@`Show us how you intend to stand up to the bullying caused by the sisters Azami and Sumire. `@`Ufufufu, Hihihihahahahaha!!`\
mcl c,0
bg black,2

fede 0,1000
E_A
wait 1000



bg gakkou_01,22

me1v 5,50

;　翌日。@
`　The next day.`@
;bg roji_04a,2
br
;　正明は、決意と緊張の入り混じった、……まるで転校生の初登校のような心境で登校した。\
`　Masaaki was filled with a sense of both determination and nervousness as he approached the school.... He felt like a transfer student on their first day at a new school.`\

;　……自分はもう、……いじめられないんだ。@いじめられないんだっ。@
`　...He was... no longer going to be bullied. `@`He was not going to be bullied again.`@
br
;　決意。@覚悟。@
`　Determination. `@`Resolution.`@
;　それをもう一度自分に言い聞かせ、昇降口に入る。\
`　He repeated those words to himself once more as he walked into the main entrance.`\

;bg black,1
;bg shoukou_03,23
bg black,22
bg shoukou_03,22


;　……上履きを履く前に、その中を見る。@
`　...Before putting on his indoor shoes he checked inside them.`@
br
;　やっぱり。@
`　Just as he thought.`@
;　また、画鋲が放り込まれていた。\
`　There were tacks put inside again.`\

;　……昨日までの自分なら、@それを見て、今日もまた嫌な一日が始まったと、陰鬱な気持ちで俯くところだ。@
`　...If he was the same person he was yesterday, `@`upon seeing that he would see this as just another horrible start to a bad day, and hang his head in depression.`@
br
;　しかし、今日は少し違う。\
`　But today was a little different.`\
ld c,YOS_D1,22
ld c,YOS_D8a,80

;　いつもいつも、……いつもいつもいつも、朝からこんな悪戯しやがって。@
`　Every day, every day... every single day he kept getting these pranks pulled on him.`@

;ld c,YOS_D1,22

;　これは、暗い気持ちじゃない。@……至極当然な、怒りの感情だった。@
`　He didn't feel depressed about it.`@` ...He felt an all too natural sense of rage.`@
br
;　上履きを取り、乱暴に振るって、画鋲を放り捨てる。\
`　He grabbed his shoes and violently shook all the tacks out of them.`\

;bg black,1
;bg kyou_01,0
;ld r,YOS_D1,24

bg black,22

fede 0,1000
E_A

se1 82
bg kyou_01,24

me1v 24,50

wait 500
ld r,YOS_D1,22


;　教室にやって来ると、自分の席を取り囲んで、いつものいじめっこたちが、何かやっているのが見えた。\
`　When he got to the classroom he say the normal group of bullies crowded around his desk doing something to it.`\

;ld r,YOS_D1,80

;　……今までにもこういうことはあった。@
`　...This sort of thing had happened before as well.`@
br
;　その時、なぜか酷く気まずい気持ちになり、@彼らが悪戯を終えるまで、意味もなく廊下をうろついて時間を潰したこともあった。\
`　Back then, for some reason, he would just start to feel really awkward, `@`and go aimlessly wander the halls and wait for them to finish their prank.`\

;ld r,YOS_D1,80

;　しかし今日は違う。@
`　But today was different.`@
br
;　彼らがとても小さく見える。@……幼稚園に通うくらいの小さな子供に見えるのだ。\
`　They looked small today.`@` ...Like tiny, little kindergarteners. 
ld r,YOS_D8a,80

;　そんな小さな悪ガキどもが、何か悪戯をしている。@ふざけやがって、叱り飛ばしてやる。@そんな感情で胸が満たされるのだ。@
`　And those little brats were playing a prank on him. `@`They were screwing with him, and he was going to teach them a lesson. `@`Those were the feelings his head was filled with.`@
br
;　正明は踵を踏み鳴らしながら、ずんずんと彼らに歩み寄る。\
`　Masaaki stamped the heels of his shoes hard into the ground as he walked up to the group.`\

bg black,23

;bg kyou_07,0
bg kyou_02,23
ld c,YOS_D8a,24
ld c,YOS_D10a,80

E_A
bgm1 28

;「何やってんだよ。@……俺の席で何やってんだよっ。」@
`"Hey, what're you doing.`@` ...What're you doing to my desk."`@
;quakey 1,300
quakex 2,300

「「「……………ッ！！」」」\
"""......!!"""`\


;　彼らは正明の低い怒声に、ぎょっとして振り返った。@
`　The group of kids turned around with a fright at Masaaki's low, angry voice.`@
;　……小学生が軽い気持ちで悪戯をしたら、不良高校生が出てきたかのような、@ぎょっとした驚きを満面に浮かべていた。\
`　...Surprised spread across their faces. `@`They looked like elementary schoolers do when their caught playing lighthearted mischief by a delinquent high schooler.`\


;　見ると、彼らは鉛筆で、正明の机の上に、下品な落書きをしているところだった。@
`　Each of them held a pencil, and were scribbling vulgarities on Masaaki's desk.`@
br
;　正明は、胸の奥から湧き上がる怒りの言葉を、そのままにゆっくりと吐き出す。\
`　Words born of anger boiled from the depths of Masaaki's mind and slowly crept out of his mouth.`\


ld c,YOS_D9,80

;「………消せよ。@……………………。@/
`"....Erase it.`@` ............`@/
ld c,YOS_D11,80
quakey 2,200
;……消せって言ってんだよッ！！」@
` ...I SAID ERASE IT!!"`@
br
;　その厳しい声に、彼らは跳び上がる。\
`　They jumped at the sound of his stern voice.`\

;　皆、慌てて消しゴムを持ち寄り、ゴシゴシと消し始めた。@
`　In a panic, they all grabbed erasers and started rubbing the scribbles away.`@ 
br
;　彼らはそれを終えると、こそこそと逃げるように正明の席を離れる……。\
`　Once they were finished they nearly sprinted away from Masaaki's desk...`\
ld c,YOS_D10,80

;「おい、待てよ。@まだここに残ってるじゃねぇかよ…！」@
`"Hey, wait. `@`You missed a spot...!"`@
br
;「……ぁ、あれ書いたの俺じゃねぇよ……。」@
`"...ah, that wasn't me who wrote that..."`@
;「俺じゃねぇよ、お前だろっ……。」@
`"Well it wasn't me, it must have been you..."`@
;「……い、いや俺じゃねぇよ……ボソボソ……。」\
`"...N- no it wasn't me... *whisper* *whisper*..."`\ 
ld c,YOS_D12,80
se1 2
quakey 2,200

;「誰でもいいよッ、早く消せって言ってんだよッ…！！」@
`"I don't care who did it, just hurry up and erase it...!!"`@
br
quakey 2,300
;　彼らは再び跳び上がり、慌てて消すのだった。\
`　Once again, they jumped up and hurriedly started erasing.`\



;　正明は、彼らが去った後、ゆっくりと自分の席に座る。\
`　After they left Masaaki leisurely pulled out his chair and sat down.`\


;bg black,0
;mono 2
;bg Different_spiral_1b,22
;ld c,YOS_D1,22

bg black,22
bg kyou_03,22

me1v 24,50

;　…………………………。@
`　..............`@
br
;　昨日までは、椅子に座る時、縮こまるように、両方の膝を付けて座っていた。\
`　Before today, whenever he sat in a chair, he would bring his knees together as if cowering.`\


;ld c,YOS_D1,80

;　でも今日は違う。@……何だか体が大きくなったように感じ、自然に両足を開いて座ってしまった。\
`　But today was different.`@` ...Today he felt like his body was much bigger, and he naturally spread his legs out while he sat.`\


;　正明は実感していた。@……明らかに自分が、昨日までと違う。@
`　Masaaki could feel it.`@` ...He could feel how different he was compared to yesterday.`@
br
;　同じことを、いじめっこたちもクラスメートたちも思っていた。\
`　And his classmates and the bullies felt it too.`\
bg black,22
bg kyou_02,0
ld c,YOS_D7,22
;ld c,YOS_D1,80

;　気弱ないじめられっこのはずの吉川……くんが、今朝は何か一味違う……。@
`　There was something off about the normally timid and bullied Yoshikawa-kun...`@
;　彼らはヒソヒソとそれを囁き合うが、正明に目が合うと、萎縮しながらそっぽを向く。@
`　His classmates would whispers things like that back and forth between each other, but then Masaaki would make eye contact with them, and they turn around and shrink down.`@
br
;　……正明の胸に不思議な気持ちが、じわりと湧き上がる。\
`　...A strange feeling was gradually building up within Masaaki's mind.`\


;bg black,22
;mono 0

ld c,YOS_D8,80

;　正明は生まれて初めて。@クラスメートたちが自分に畏怖を覚えていることを感じた。@
`　For the first time in his life. `@`Masaaki knows what it feels like to be feared by his classmates.`@
br
;　ぞわりとした高揚感が、全身に染み渡るのを感じる。\
`　A sort of uplifting feeling spread throughout his whole body.`\
mbg black,22

;「どうです？@　……あなたがもはや、いじめられっこではないことが、わかったでしょう。」\
`"How's it going?`@` ...You're not getting bullied anymore are you?"`\


;bg kyou_02,0
;ld r,YOS_D1,22
;ld c,AZA_D1,2

mcbg 22

ld r,AZA_D2,2

;　アザミがすぅっと姿を現す。\
`　Azami's figure appeared before him.`\


;ld r,YOS_D1,80

cl c,0
ld l,YOS_D7,24
ld l,YOS_D8a,80

;「アザミさん……。@……お、俺、今日は何かが違います……。」@
`"Azami-san...`@` ...Th-, there's something different about me today..."`@
;ld c,AZA_D1,80
ld r,AZA_D5,80

;「どう違いますか？」\
`"Different how?"`\


;ld r,YOS_D1,80
ld l,YOS_D8,80

;「……な、何て言うかその、……教室がすごく広く感じます。@……何か天井も高く感じる…。@……いやその、……世界が明るくさえ……。」\
`"...It's kind of like, I don't know... like the classroom feels much bigger today.`@` ...Like the ceiling is higher up than usually...`@` ...No, it's more like... The world just feels brighter all of a sudden..."`\


bg kyou_03,26

;　意識すればするほど、……昨日までと何も変わらないはずの教室の景色が違って感じられた。@
`　Even though the classroom itself hasn't actually changed at all, the more he thinks about it... the more he feels like its changed.`@
br
;　一言で言えば、……視野がものすごく広がったような感じ。\
`　To put it simply... he feels like his outlook has significantly expanded.`\
;　いじめっこもいじめられっこも、同じ人間だと思った日もあった。@
`　He once thought that bullies and those who get bullied were the same, just humans.`@
br
;　違う。@
`　That's wrong.`@
;　いじめっこといじめられっこでは、……感じ方ひとつでも、こんなにも違ったのだ……。\
`　Who would think that what made the difference between being a bully or being bullied... would all come down to one simple way of looking at the world...`\


;ld c,AZA_D1,0
;ld r,YOS_D1,22


;ld c,AZA_D1,80


bg black,22
bg kyou_02,0
ld l,YOS_D5,0
ld r,AZA_D2,22

ld r,AZA_D1,80

;「そう。@それが、いじめっこの世界です。」@
`"Yes. `@`This is the world of bullies."`@
;ld r,YOS_D1,80
ld l,YOS_D6,80

;「……すごい。@……空気の味さえ変わった気がする。@……信じられないくらい、……清々しい気持ちです……。」\
`"...Amazing.`@` ...It feels like even the taste of the air has changed.`@` ...It's unbelievable... and feels so refreshing..."`\
ld r,AZA_D4,80

;「いじめとは、妾たち妖怪だけでなく、人間にとっても狩りなのです。」\
`"Us youkai are not the only ones who hunt. Bullying is the human equivalent of hunting."`\


;ld l,SMI_D1,22
;ld l,SMI_D1,80

ld c,SMI_w4,22
ld c,SMI_w1,80

;「魂を狩り、食らう狩りなのじゃ。@人間も我らと同じように、いじめによって、魂を狩り、食らっているのじゃ。」@
`"We hunt down souls and eat them. `@`Humans are the same way, using bullying to hunt souls and feed on them."`@
br
;　もう一人妖怪が現れ、いじめは魂を食らう狩りだと告げる。\
`　Another youkai appeared, telling him about how bullying is like hunting.`\


;ld c,AZA_D1,80
ld r,AZA_D2,80

;「いじめっこは、いじめられっこの魂を食らうことで、今、あなたが感じている世界を得ているのです。@……つまり、あなたのその世界は、昨日まではあなたをいじめていた彼らの世界だったのです。」\
`"By feasting on the souls of other, bullies are able to reach the world you are in now.`@` ...Basically, right now you're living in the same world as those who had been bullying you up until yesterday."`\


;ld l,SMI_D1,80
ld c,SMI_w4,80

;「逆に、そなたの世界はどうであったか。@……暗く狭く、息苦しい世界であったろうが。」@
`"Conversely, what was your world like before now?`@` ...Was it a dark, small and stifling world?"`@
;ld r,YOS_D1,80
ld l,YOS_D8a,80

;「た、……確かに……。」\
`"Y-... yes, it was..."`\


;ld l,SMI_D1,80
ld c,SMI_w2,80

;「それは、そなたの魂を彼らが食らっておったからなのじゃ。@食われたお前の世界は暗く狭くなり、@食っていた奴らの世界はこんなにも明るく清々しいのじゃ。@……面白いものであろうが、いじめというものはっ。」\
`"That's because your soul was being devoured by them. `@`As your world was being eaten it became small and dark. `@`And their world was bright and refreshing.`@` ...Bullying is so interesting."`\


;cl a,0
bg black,22

;　正明は少し納得していた。@
`　Masaaki somewhat understood now.`@
br
;　いじめられている自分が、暗く落ち込んでいるのに比べ、@いじめっこたちはいつも馬鹿みたいに上機嫌で陽気だった。@
`　Back when he was feeling depressed, `@`those bullies were always joking around and acting all happy like a bunch of idiots.`@
;　これが彼らの世界だったというなら、……納得できる。\
`　If this is how they were seeing the world... then he could understand why they were like that.`\

bg azami2,0
ld c,AZA_D1,22
ld c,AZA_D2,80

;「あなたはこれまで暗い世界でいじめられた分を、取り返すのです。@そして彼らに、@これまでの上機嫌な世界が、どのような犠牲の上に成り立っていたかを思い知らせるのです。@それこそが、因果応報。@人の世の摂理を、今こそ示すのです。」\
`"From now on, you will take back the world that was stolen from you. `@`And them, `@`you will make them pay for what they did at the expense of cheerful world. `@`That will be their punishment. `@`Here is where their karma will come into play."`\
cl c,22
bg black,42

fede 1,2000
E_B
wait 1000

bg kyou_01,22
ld r,YUK_w1,24
ld r,YUK_w2,80

;「おはよー。@……………？」@
`"Good morning.`@` .........?"`@
;＜由香里
br
;　教室に入ってきた由香里は、教室の空気が少しだけいつもと違うのを感じる。\
`　As she walked in the door Yukari felt like the mood in the classroom was a bit different than usual.`\

bg black,23
bg kyou_02,0
ld l,YOS_D7,23
;ld l,YOS_D1,22

;　喧嘩でもあったのだろうか。@……まさかと思い、正明を見るが、喧嘩をしたようには見えない。@
`　She was wondering if there might have been a fight.`@` ...But when she looked over at Masaaki, she didn't see any evidence of a fight on him.`@
br
;　………でも、彼の雰囲気が昨日までとは何かが違った。\
`　....But something about him was different compared to yesterday.`\
;　しかし、それは少なくとも、いじめられっこの気の毒な雰囲気とは異なる。\
`　But at the very least he didn't have the same pitiful bullied feel to him.`\
;ld r,YUK_D1,80
ld r,YUK_w4,24
ld r,YUK_w3,80

;「………吉川くん。@おはよう。」@
`"....Yoshikawa-kun. `@`Good morning."`@
ld l,YOS_D8,80

;「…………おはよう。」\
`"......Morning."`\
ld r,YUK_i1,80

;「…………………。」@
`"..........."`@
ld l,YOS_D8a,80

;「何だよ。@……俺の顔に何か付いてっかよ。」\
`"What?`@` ...Is there something on my face or something?"`\


ld r,YUK_i1a,80

;「……何も。」@
`"...No, it's nothing."`@
br
;　やっぱりだ。@昨日までの彼とはまるで雰囲気が違う。@
`　There's no doubt about it. `@`He was somehow different than he was yesterday.`@
;　良く言えば、たくましく。@……悪く言えば、ちょっと粗暴そうな感じ。\
`　To put it nicely, he seemed stronger.`@` ...To put it not so nicely, he seemed a little rude.`\


;ld r,YUK_D1,80

;　でも、俯いて暗そうにしていればいじめっこたちを呼び寄せるだけだ。@
`　But if he hanged his head in shame like usually, it would bring the bullies over to him.`@
;　なら、ちょっと目つきが悪くても、堂々としていた方がいい。\
`　So it's probably better this way, even if his expression does seem a little mean.`\

;　彼の中にたくましさが生まれ、@それがちょっぴり、目つきを悪そうに見せているだけかもしれない……。@
`　Maybe he just finally gathered up some strength in his heart, `@`and that just made him look a little bit meaner overall...`@
br
;　由香里はそう思うことに決め、正明の前を通り過ぎるのだった。\
`　That's what Yukari thought as she walk past the front of Masaaki's desk.`\
;cl r,23
cl r,22

;wait 1000
;cl l,0
bg black,2
ld r,SMI_w1,22
ld r,SMI_w5,80

;「由香里よ。@いじめは決して許さぬと、この私に啖呵を切りおったお前が、@どのようにいじめに抗うのか、楽しみじゃぞ…！@　ふっふふふふふふふふふ！」\
`"Yukari. `@`The girl who preached to me about who she would never forgive bullying. `@`I wonder how you're going to fight this bullying. I'm looking forward to it...! `@`Ufufufufufufufu!"`\
;＜スミレ

bg black,2

fede 0,1000
E_A

bg kyou_01,22
;ld r,YOS_D1,22

bgm1 18

;　いじめっこになれたとはいえ、……正明は何をすればいいのかわからない。@
`　Even though he was used to being bullied... Masaaki wasn't quite sure he should be doing as a bully himself.`@
;ld l,AZA_D1,22

;　アザミは、何をしても自由ですと言ってくれるが、@自由だからこそ、何をしていいのかわからない。@
`　Azami told his that it was just freedom to do whatever he wanted, `@`but because he had such freedom, he had no idea where to start.`@
br
;　でも、その自由という名の解放感は、@退屈な授業中でさえ、彼の全身に泡立つ感触を感じさせてくれるのだった。\
`　But as he was sitting, listening to a boring class lecture, `@`he could feel that sense of liberation called freedom bubbling up in him.`\


;ld r,YOS_D1,80
ld c,YOS_D2,22

;「そういえば……。@授業中に、消しゴムのカスをぶつけられたことがあったっけ……。」@
`"Oh yeah... `@`Didn't they used to throw bits of eraser at me during class...?"`@
ld l,AZA_D2,22
ld l,AZA_D3,80

;「では、それを仕返ししてみるというのはどうです。」\
`"Why don't you try getting revenge for that."`\

;　さっき、ノートに書き間違いをして、ごしごしと消したので、@机の上にはたっぷりの消しカスがある。@
`　Since he made some mistakes in his notebook earlier, `@`he happened to have some eraser shaving on his desk.`@
br
;　それらを指でこねると、@彼らがよく自分にぶつけてきたのと同じような、小さな玉がいくつも出来た。\
`　He gathered them up in his fingers, `@`and made a bunch of little balls out of them, just like the ones he used to be hit with.`\


ld l,AZA_D5,80

;「くす。@……やってみるといいでしょう。@彼らはそれを人にぶつけることを知り、@あなたはそれをぶつけられることを知ったのです。@ですから、今度は互いに逆のことを知り合うべきでしょう。@それが、」@
`"*Giggle* `@`...Go ahead and try it. `@`They're used to throwing eraser bits at people, `@`and you're used to getting hit by them. `@`So now you should return the favor. `@`This is-,"`@
;＜アザミ


;ld r,YOS_D1,80
ld c,YOS_D8a,80

;「因果応報、ってわけだ……。」\
`"-retribution for their actions. That's what this is..."`\
;ld c,SMI_D1,22
;ld c,SMI_D1,80
ld r,SMI_w2,22
ld r,SMI_w3,80

;「そういうことじゃ！@　さぁさぁほれほれ。@やってみるが良いのじゃ！」\
`"Exactly! `@`Now come on, go for it. `@`See what it's like!"`\
;＜スミレ


;bg black,1
;bg kyou_06,0
;ld c,YOS_D1,80

bg black,22
bg kyou_06,22
;ld c,YOS_D1,22

;　正明は消しゴムのカスで作った玉を摘み上げ、@……それを自分の前にいる、いじめっこの１人の頭に、狙いをつける……。\
`　Masaaki picked up one of those eraser balls... `@`And took aim at the head of one of the bullies sitting in front of him...`\


;　……ちょっと緊張する。@
`　...He got a little nervous.`@
br
;　でもその緊張感は、スリリングなもので、相手にバレたら怖いという、恐怖感ではない。\
`　But it was a thrilling sort of nervousness, nothing like being afraid of being caught throwing it.`\

;　………………それっ。@
`　And........ throw.`@
se1 47
br
;　ぴしり。\
`　Tap.`\
; ^^^ Note To Editor: SFX for eraser hitting hair. Couldn't think of a good one.
;　カス玉が、いじめっこの後頭部に当る。@
`　The eraser ball hit the back of the bully's head.`@
br
;　相手には気付かれなかったようだが、それは髪に絡まってその場に留まった。\
`　It didn't look like the kid noticed, but it got stuck in their hair.`\
;ld c,YOS_D1,80

;　それが滑稽で、思わず、ぷぷっと噴き出してしまう。@
`　Masaaki found this funny, and accidentally let out a little chuckle.`@
;　気付かないなら、もう一発やってやろう。@
`　He didn't notice, so let's try one more time.`@
br
;　それ、ぴしり。/
`　Throw, tap.`/
se1 47

;@ぴしり。/
@` Tap.`/
se2 47
\
ld r,YOS_D7,22

;　いじめっこの後頭部に、いくつものカス玉が絡みつく。@
`　The bully had a bunch of little eraser balls stuck in their hair.`@
;　すっかりみっともない頭になり、笑いを堪えるのも難しくなる。\
`　They looked so stupid that Masaaki could barely keep from bursting out laughing.`\


;　普段なら、ぼんやりと俯くことしか出来なかった授業時間に、@こんなにも愉快になったことなど、かつてあっただろうか？\
`　Usually, the only thing he could do during class time was absentmindedly stare down at his desk. `@`Had he ever had this much fun during class?`\


;　あるわけがない。@そして、この愉快な世界が、いじめっこの世界だったのだ。\
`　No, not at all. `@`And this fun world is the world of bullies.`\


ld r,YOS_D8a,80

;　……そりゃあ、やめられないわけだ。@
`　...I can't stop throwing these things.`@
br
;　だって、こんなにも楽しいのだから。\
`　It's just so fun.`\


;bg kyou_07,0
;ld r,YOS_D1,22

;　とうとう、いじめっこはカス玉をぶつけられていることに気付き、振り返る。@
`　Eventually the bully finally realized that he was being pelted with eraser shavings, and turn around to look behind him`@
br
;　しかし、その顔つきは恐る恐ると言う感じ。\
`　But the expression on his face was that of fear.`\


;ld r,YOS_D1,80
ld r,YOS_D10,80

;「………何だよ。@授業中に後、向くなよ。」@
`"....What? `@`Don't be look back here when class is in session."`@
;「…………ん………。」@
`".....N-....."`@
br
;　正明が凄むと、いじめっこは頭をさすりながら、おずおずと前を向く。\
`　Once Masaaki threatened him, the bully turned brushed off his hair and nervously turned back around.`\


;ld r,YOS_D1,80
cl r,0
ld c,YOS_D8a,24

;　………は、ははは。@……こりゃ面白いや。\
`　.....Hah, hahaha.`@` ...This really is funny.`\


;　意味もなく消しゴムをごしごしと削り、新たなカス玉を作って、ぴしぴしと弾く。@
`　Masaaki picked up his eraser again, and needlessly rubbed it on his paper to make more shavings. Then, he made those into new eraser balls and started flicking them again.`@
br
;　相手は気まずそうに頭を払い、ちらりとこちらの様子をうかがうのだが、正明と目が合うと、再びおずおずと前を向く。\
`　The target awkwardly brushed his hair again, and glanced behind him again, only to meet eyes with Masaaki and nervously turn back towards the front of the class once again.`\
;cl r,0
;bg black,0
;mono 1
;bg aka2,22

;ld c,YOS_D1,80

bg black,22

;　……文句が言いたいだろうよ。@でも怖くて言えないんだ。@
`　...It looked like he wanted to say something. `@`But he was too scared to open his mouth.`@
;　かつて、こいつらにさんざんいじめられていた自分には、@今のこいつの気持ちがよーくわかる。@
`　Because Masaaki had once been really severely bullied by this particular kid, `@`he knew exactly who he was feeling at this very moment.`@


;ld c,YOS_D1,80
br
;　ならば、思い知れっ。@お前らが俺に今までしてきたのが、どんなに卑劣なことだったか、@身に染みて思い知れっ。\
`　Good. Realize what you've done. `@`Realize how mean you have all been to me up until now. `@`Let that feeling soak into your body.`\

bg kyou_02,0

;bg black,1
;mono 0

;bg kyou_03,22
ld r,SMI_w1,0
ld l,AZA_D2,22

ld r,SMI_w3,80

;「あいつ、なかなかやるのじゃ！@　いじめっこの素質があるのぅ！」\
`"He's not half bad! `@`He's got some real potential as a bully!"`\
;＜スミレ

ld l,AZA_D3,80

;「くす。@いじめは楽しいですから。@ゆえに禁断の果実。@……それをかじる者は、かじられることを知らねばならないのです。@妾は、それを思い知らせることを司る者。@……いじめられた悔しさを知る者こそ、いじめっこに相応しく。@いじめの快楽に溺れた者こそ、いじめられるのに相応しいのです。」\
`"*Giggle* `@`That's because bullying is fun. `@`It's like a forbidden fruit.`@` ...Whoever eats it, begins to crave it. `@`And I'm the one in charge of giving the fruit to them.`@` ...Those who know the frustration of being bullied, are ideal candidates for becoming bullies. `@`And those who drown in the pleasures of bullying, make good candidates for being bullied themselves."`\
;＜アザミ

ld r,SMI_w2,80

;「正明めはずいぶんいじめられておったのじゃ。@その反動で、素晴らしいいじめっこになってくれるのじゃ！」\
`"Masaaki was bullied pretty badly. `@`So when he rebounds, he makes a great bully!"`\

ld l,AZA_D1,80

;「さぁ、正明くん。@これまでの悔しさの全てを吐き出してやりなさい。@あなたにはその資格があるのです。@そして慄きなさい、正明くんをいじめていた愚かなる者たち。@彼がどれほど苦しんできたか、その身を以って思い知ると良いでしょう。@それが因果応報です。」\
`"Come now, Masaaki-kun. `@`Take all the frustration you've felt so far and release it. `@`You have the potential of becoming a great bully. `@`And tremble in fear, all those who bullied Masaaki. `@`Know how badly he suffered. `@`That will be retribution for your actions."`\
;cl a,0
bg black,2


;　その日を境に、正明が変わったことは、クラスで話題になった。\
`　By the end of that day, the change in Masaaki had become the hot topic among his classmates.`\
bg kyou_01,0
;bg kyou_01,2
ld c,YOS_D7,22

me1v 24,50

;　……あれが噂に聞く、魔法のアザミを食ったってやつなんだろーね。@……クラスメートたちが囁く。\
`　...Did you hear the rumors? They say he ate one of the magical thistles.`@` ...His classmates would whisper behind his back.`\

;ld c,YOS_D1,80

;　正明は、かつて自分が彼らに言われていたように。@俺たち友達だろうと言って絡みながら、悪戯をし返していた。@
`　Just like Masaaki what had once happened to Masaaki, `@`he would get away with pulling pranks on those who bullied him before by insisting that they were his friends.`@
br
;　そのシーンだけを切り出してみれば、それも立派ないじめだったろう。\
`　Simply by trying to do what they did to him, he was able to unleash a good deal of bullying on them.`\

;　しかし、誰もがかつての正明が気の毒ないじめられっこであったことを知っている。@
`　But everyone knew that Masaaki used to be a pitiful bullied kid before.`@
br
;　だからこそ、彼の復讐を正当なものだと理解した。\
`　So most of them realized that what he was doing was a justified revenge.`\

;　いじめっこたちが逆にいじめられるなんて。@いい気味だ。@人をいじめることの罪深さを思い知ればいい。@
`　Those bullies are now getting bullied in return. `@`That's what they deserve. `@`They should be taught the dangers of bullying.`@
br
;　みんなそう思い、正明のささやかな復讐を見て見ぬふりをした。\
`　That's what everyone thought, and pretended not to see Masaaki enacting his revenge.`\
bg black,22

fede 1,1000
E_B

bg kyou_02,22
;bg black,1
;bg kyou_04,2
ld r,YUK_D3,22
;ld l,YOS_D1,22


;ld r,YUK_D1,80

;「吉川くん。@……最近、変わったね。」@
`"Yoshikawa-kun.`@` ...You've changed recently."`@
;＜由香里

ld l,YOS_D8,22

;「………そうかよ。@……そうかもな。@へへ……。」@
`"....Have I?`@` ...Maybe you're right. `@`Hehe...."`@
br
;　正明は不機嫌を装いながらも、にやっと笑ってそう答えた。\
`　Masaaki grinned a sour smile.`\


ld r,YUK_D1,80

;「何かあったの？」@
`"Did something happen?"`@
ld l,YOS_D8,80

;「……みんなが噂してる通りだよ。」\
`"...It's just like all the rumors say."`\
ld r,YUK_D3a,80

;「噂って。@……アザミを食べた、とかいうやつ？」@
`"Rumors?`@` ...You mean the ones about eating a thistle?"`@
ld l,YOS_D7,80

;「まぁ、そんなところだぜ。@……俺もいつまでもいじめられっこじゃないってことさ。」\
`"Yeah, pretty much.`@` ...I'm done being bullied around."`\


ld r,YUK_w3,80

;「……………そうだね。」@
`".......I see."`@
br
;　正明のその表情には、自信が見て取れる。\
`　She saw confidence in Masaaki's face.`\



;bg black,22

;　かつてはいつも俯いていた。@それに比べたら、どれほど生気に溢れていることか。@
`　There was a time when he used to always hang his head, and cast his eyes down. `@`Compared to that, he now seemed overflowing with vitality.`@
br
;　それを見て由香里は、どんな形であれ、彼がいじめられっこの境遇から逃れられたことを、率直に喜んだ。\
`　No matter the circumstances, Yukari was honestly happy to see him being not only confident, but also no longer being bullied.`\

bg black,23
bg kyou_01,23
ld l,YUK_w3,23
;ld l,YUK_D1,80

;bg kyou_04,0
;ld r,YUK_D1,0
;ld l,YOS_D1,22

;ld r,YUK_D1,80

;「……確かにあの子たちは、すごく意地悪で、しつこく君をいじめてたもんね。@……私もちょっぴり、いい気味だと思う。」@
`"...It's true that they were being really mean, bullying you so often.`@` ...Even I think they kind of deserve this."`@
;ld l,YOS_D1,80
ld r,YOS_D7,24
;ld r,YOS_D1,80

;「ざまぁ見ろってんだ……。」\
`"Serves 'em right..."`\
;ld r,YUK_D1,80
ld l,YUK_D2,80

;「でも。@……君までいじめっこになっちゃだめだよ。」@
`"But.`@` ...You can't become a bully yourself."`@
;ld l,YOS_D1,80
ld r,YOS_D10,80

;「なっちゃ悪いかよ。@俺はずっといじめられてたんだぞ。@だから俺には同じだけやり返す権利があるんだ…！」\
`"What's so wrong with that? `@`I was bullied by them for so long. `@`So what's wrong with a little payback...?!"`\


;ld r,YUK_D1,80
ld l,YUK_D1,80

;「…………正明くんの気持ちもわかるの。@だから、私もしばらくは様子を見るけれど。@……あまりやり過ぎるようだったら、私も怒るからね。@だから、」\
`".....I understand how you feel, Masaaki-kun. `@`That's why I've been letting this slide for now.`@` ...But if you start to overdo it, I'm going to get mad. `@`So..."`\


;ld l,YOS_D1,80

cl r,0
ld c,YOS_D11,24

E_A

se1v 12,50
ld l,YUK_N1,1
quakex 2,200

ld c,YOS_D12,80

'「何だよ、お前はよ！！@/
`"Who do you think you are!?`@/
bgm1 7
;　俺の親かよッ、先生かよッ？！@　俺はずっとあいつらに好き放題にされてきたんだ！@　だから今度は俺があいつらを好き放題にする！！@　それが因果応報だろ？！@　違うのかよ！@　それがなかったら、世の中ずっといじめ得じゃねぇかよ？！@　俺だっていじめは大嫌いだ！@　いじめっこは絶対に許せねぇ！！」\
` My mom? My teacher?! `@`They did whatever the hell they wanted to me! `@`So now I'm doing whatever the hell I want right back!! `@`That's just karma! `@`Right?! `@`Without it, bullies would just have their way with everything! `@`I hate bullying! `@`And I will never forgive any bullies!!"`\
;ld l,YOS_D1,80
cl c,0
ld r,YOS_D11,23

;「だからこそ、あいつらが俺にしてきたことを絶対に許さない！@　悪いことをすれば絶対に報いがあるように、@あいつらも報いを受けなくちゃならない。@これは俺の個人的な仕返しじゃねぇ。@それが世の摂理、因果応報ってもんなんだ！！@　日が昇ったら、必ず沈まなくちゃいけねぇだろ。@そういうことなんだよッ！！」\
`"I'll never forgive them for what they did to me! `@`When you do something bad, you've got to face the punishment! `@`That's what I'm doing to them. `@`This is my own personal revenge. `@`It's divine retribution!! `@`Just like the sun rises, it's got to set. `@`That's just how things work!!"`\
;cl l,24


;ld r,YUK_D1,80
;ld r,YUK_D1,80
ld l,YUK_D3a,80

;「………正明くん………。」@
".....Masaaki-kun......"`@
ld r,YOS_D8a,80
wait 1000
cl r,23

br
;　正明は今度こそ不愉快な表情を浮かべ、踵を返す。@
`　Masaaki's expression had now gotten unpleasant, and he turned his back to her.`@
;　その背中を、由香里は呆然と見送ることしか出来ない……。\
`　Yukari could do nothing but watch him walk off, dumbfounded...`\

bg black,22
;bg black,0
;bg kyou_03,24
ld c,SMI_w1,22
ld c,SMI_w2,80

;「くっくっく…！！@　どうした由香里よ。@お前はいじめは許さないのではなかったか？@　正明の復讐という名の新たなるいじめ！@　お前はどう抗っていくというのか！@　くっくっくっくっく！！」\
`"Kukuku...!! `@`What's wrong, Yukari? `@`Didn't you say you wouldn't allow bullying? `@`Masaaki's bullying is unlike anything you've seen so far! `@`How are you going to fight bullying born from revenge! `@`Kukukukuku!!"`\
;＜スミレ

bg black,22
;cl c,0
;bg black,0
mono 2
bg different_spiral_1a,22

me1v 5,50

;　正明には、自分がいじめっこだという自覚など、あるわけもなかった。@
`　Masaaki didn't realize that he had become a bully at all.`@
br
;　自分のいじめられっこの汚名は、@彼らに正当な分の復讐を終えて初めて、返上できると考えていたからだ。\
`　He won't give up until he's enacted what he considers the right about of revenge `@`for all the disgraces inflicted on him.`\


;　自分は、このクラスになってから数ヶ月の間、ずっとずっといじめられた。@最低でも、それと同じ期間はいじめ返さなくては、割りが合わない。@
`　It's been a several months since the year started and he joined the class, and he had been bullied every single day for that whole time. `@`He wasn't going to be satisfied until he did the same to them for at least the same amount of time.`@
br
;　だから次の日より正明は、これから数ヶ月の間、@みっちりたっぷりといじめ抜いてやると決意を新たにした。\
`　So from the next day on, Masaaki came to school with a new devotion. `@`He vowed to spend the next few months completely and utterly bullying those who bullied him.`\


;　……よくよく考えてみれば、同じ期間をいじめたとしても、まだ割りが合わない。@
`　...Even when he thought he might have been bullying them for as long as he had endured, he still didn't give up.`@
br
;　あいつらは、数人掛りで、たった一人の自分を寄って集っていじめたんじゃないか。\
`　After all, didn't they used to team up on him when he was being bullied?`\


bg Different_spiral_1b,0
ld c,YOS_D8a,22

;　自分など生温い。@一人が、彼ら数人を代わる代わるいじめているのだから、@彼らへの仕返しの量は、ほんのわずかじゃないか。@
`　He was too lenient on them. `@`There was only one of him, and he had to take turn bullying them one by one. `@`So the amount of time he spent bullying each of them was nowhere near enough.`@
br
;　……なら、もっともっといじめてやらなきゃ、割りが合わない。\
`　So he just kept bullying more and more, refusing to give up.`\
;　期間じゃない。@それは密度だ。@
`　It wasn't the time he was being bullied. `@`It was all the time the bullies spent combined.`@
br
;　何人ものいじめっこたちに、@毎日取り囲まれていじめられたあの恨みに匹敵するいじめを、きっちり全員にし返さなきゃ、復讐にならない。\
`　He was bullied be many kids. `@`So if he didn't pay each of them back for each day they bullied him, his revenge wouldn't be complete.`\
bg black,22
mono 0

;　その次の日より、正明は、露骨にいじめをエスカレートさせ、@到底、悪戯や悪ふざけとは言い難いものに変えていった。\
`　From that day on, Masaaki's bullying became more conspicuous. `@`He starting playing pranks and teasing them in unspeakable ways.`\


;bg black,1
;mono 1
bg kyou_02,0
ld r,YOS_D8a,22

me2v 17,60

;　……最初は、彼も多少は恐る恐るだった。@
`　...At first, he was somewhat cautious.`@
br
;　こんなことまでしてしまったら、@さすがに相手も逆上するのではないかと、おっかなびっくりだった。\
`　He was being careful about not going too far. `@`He was worried they might get angry at him and retaliate.`\

;　しかし彼らは、何をしても怒らない。@
`　But they didn't get angry no matter what he would do.`@
br
;　曖昧に気持ち悪く笑って誤魔化すばかりで、何もかもが言い成りだった。\
`　They would just fake a vaguely unpleasant smile and do whatever he said.`\

bg black,22
bg kyou_04,22
;bg kyou_01,23
;mld c,YOS_D1,22
;mld c,YOS_D1,80

;　ある日、いじめっこの一人が堪えかねて、初めて涙を見せた。@
`　One day, one of the bullies just couldn't handle it anymore and started to cry.`@
br
;　少し驚いたが、……正明は怯まなかった。\
`　Masaaki was a little surprised... but he still didn't let up.`\
mld c,YOS_D10a,22

;　自分は彼らに、何日泣かされてきたというのか。@
`　They made him cry plenty of times.`@
br
;　これは復讐なんだ。@
`　This was his revenge.`@
;　それも、この上なく正当な！\
`　This too was entirely justified!`\

;mono 0
;bg black,1
;ld r,YOS_D1,22
bg black,22
mld c,YOS_D8a,80

;　俺がいじめっこ？@　とんでもない！@　俺は被害者だ、犠牲者だッ。\
`　Was I a bully? `@`Not at all! `@`I'm the one who's the scapegoat here, the victim.`\
;mld c,YOS_D1,80

;　わかってるさ！@　いじめは悪。@絶対に許しちゃいけない、絶対悪だ！@
`　I know! `@`Bullying is bad. `@`It's absolutely unforgivable!`@
br
;　だからこそ、俺はあいつらを、その絶対悪で復讐しなくちゃならない！\
`　That's why I have to use it to get revenge on them!`\

;ld r,YOS_D1,80
mld c,YOS_D10,80

;　俺が復讐しなかったらどうなる？！@
`　What will happen if I don't get revenge?!`@
br
;　いじめっこのいじめ得だ！@　そんなことになったら、@世の中はいじめだらけになって、いじめで溢れてしまう！\
`　Those bullies will win! `@`And if that's allowed to happen, `@`this world will be filled to the brim with bullying and those who benefit from it!`\
;mld c,YOS_D1,80

;　そんなことを許しちゃいけない。@だからこれは正義。@正義の執行なんだ。@
`　I can't let that happen. `@`This is justice. `@And I am the enactor of that justice.`@
br
;　人をいじめる者には、必ず正義の鉄槌が振り下ろされる。@それを示すことこそが、正義の執行なんだ。\
`　Those who bully will be crushed by the iron hammer of justice. `@`That is how justice is enacted.`\
mcl c,0
bg black,22
bg e002,22

;　しかし、その執行の資格は、誰にでもあるわけじゃない。@
`　But not everyone is capable of enacting that justice.`@
;　何も背負わぬ者がそれを執行すれば、それはただのいじめだ。@
`　If someone who hasn't faced bullying tries to enact that justice, that's nothing more than bullying itself.`@
;　それをいじめでなく、正義として執行できる者にのみ、資格があるのだ。\
`　Only those who know that pain are qualified to bring justice without it being bullying.`\


bg e005,26

me3v 28,70

;　それが俺ッ。@彼らにずっといじめられてきた俺なんだ。@
`　I am the one who is qualified. `@`I am the one who has endured that bullying.`@
;　だから俺が彼らにするのはいじめじゃない！@　正義の執行なんだ。\
`　So what I'm doing to them is not bullying! `@`It's simply justice.`\
;bg black,22
mono 2
bg different_spiral_1a,22

;　それに、俺はいじめっこになるつもりなんて、さらさらない。@
`　Besides, I have no intention of ever becoming a bully.`@
br
;　彼らの罪に相応しい分の正義をきっちりと執行するだけ。\
`　I'm only dealing out the appropriate amount of justice for their sins.`\
;　……それはいつまで執行されるのか？@
`　...How long will that be for?`@
br
;　彼らが己が罪に気が付いて認め、生涯を謝罪と賠償に捧げるまで続けなければならない。\
`　Until they realize their own sins, and devote their lives to apology and reparation.`\


;　そしてそれは、彼らの良心が目覚めるまで続かなくてはならない。@
`　I will continue until their consciences awaken.`@
br
;　そう。@この正義の執行は、彼らが誠意に目覚めるまで、永遠に続かなくてはならないのだ。\
`　That's right. `@`I will enact my justice endlessly until they become sincere and honest people.`\


bg black,2
mono 0

fede 0,2000
E_A

bg ura7,22

bgm1 14

me1v 30,50

;bg ura7,2
ld r,YUK_i3a,24
;ld l,YOS_D1,22


;ld r,YUK_D1,80

;「……吉川くん、正気なの？！@　こんなの、ただのいじめじゃない！@　何が正義の復讐よ…！！」\
`"...Are you out of your mind, Yoshikawa-kun?! `@`That's just bullying! `@`That's not justice at all...!!"`\
;＜由香里



;　由香里は、いじめっこの少年を庇い、正明の前に立ちはだかっていた。@
`　Yukari stood blocking Masaaki's path to protect one of the bully boys.`@
br
;　……正明は宝探しごっこと称して、いじめっこの自宅の鍵を奪い、@それをヘドロで埋まったドブに放り込み、探させていたのだ。\
`　...Masaaki had stolen the bully's key under the false pretense of a 'treasure hunt'. `@`He had thrown the key into a muck filled gutter and was forcing the boy to search through it.`\

;　その上、タイムアタックなどと称して、@正明が１０を数えるごとに少年のお尻を蹴るという暴行付きで。@
`　Furthermore, he claimed it was a 'time trail', `@`in which Masaaki would count to 10 and then kick the bully in the butt.`@
br
;　その日、由香里は都合でいつもと違う通学路で帰り、その現場に出くわしたのだ。\
`　Yukari had taken a different route home from usually that day for various reasons, and happened across this display of violence.`\

ld r,YUK_D4a,80

;「可哀想に……。@私も一緒に探してあげるね。@……正明くんも一緒に探してあげなさいよ…！！」@
`"You poor thing... `@`I'll help you look for your key too.`@` ...Masaaki-kun, you help find it too...!!"`@
ld l,YOS_D10,23

;「……うっせぇな。@俺はこいつと一緒に宝探しをして遊んでるだけなんだよ。@……なぁ？！@　俺たち友達だもんなぁ？！」\
`"...Shut up. `@`We were just having a little treasure hunt.`@` ...Right?! `@`We're friends, right?!"`\

;bg black,22

;　それはかつて、まったく逆の立場だった時、正明が彼らによく投げ掛けられた言葉だ。\
`　Those were the same words that Masaaki had thrown at him all the time back in the day.`\


;　いじめっこは、……いや、今となってはそれが正しい呼び方かは怪しいが…。@
`　The bully... actually, it would be strange to still call him a bully at this point, but at any rate...`@
br
;　いじめっこは弱々しい笑顔でおずおずと、「う、うん……。」と正明に答える……。\
`　The bully moved his lips into a slender smile, and answered Masaaki with a nervous "Y-Yes....."`\

;bg ura8,0
;ld r,YUK_D1,0
;ld l,YOS_D1,22


;ld r,YUK_D1,80

bg black,23
bg ura8,23
ld l,YUK_i3a,23

;ld l,YUK_D1,80

;「何が遊んでるだけよっ。@どう見てもいじめじゃない！」\
`"How is thing playing? `@`This is clearly bullying!"`\


;ld l,YOS_D1,80
ld r,YOS_D12,24
;ld r,YOS_D1,80

;「いじめじゃねぇよ、遊びだよッ！@　俺だって、逆の立場で遊んでもらったことがあるんだぜ。@なっ。@ランドセル運ばされて、@罰ゲームでズボンをドブに捨てられたりとかして遊んだもんな？！@　なッ！！」@
`"It's not bullying, it's playing! `@`When I was in his place they made me play like this all the time. `@`Right? `@`You would make me carry your backpacks, `@`and then make me play a punishment game of throwing my pants in the gutter!! `@`Right?!"`@
;「ぅ、………ぅん………。」\
`"y-..... yeah...."`\


ld r,YOS_D8,80

;「ほらな。@いじめじゃねぇんだよ。@女のお前にはいじめに見えるだろうけど、@これは俺たちには普通の遊びなんだよ。@女は引っ込んでろッ！！」@
`"See? `@`It's not bullying. `@`A girl like you might think it's bullying, `@`but this is just how we play. `@`Girls should just mind their own business!!"`@
ld l,YUK_i2a,80

;「引っ込まないよっ。@私、いじめは絶対に見過ごさないもんっ。」\
`"I will do no such thing. `@`I refuse to overlook bullying."`\
ld r,YOS_D11,80

;「て、てめぇ、……お、俺がいじめっこだって言うのかよ？！@　俺はいじめられっこなんだよ、被害者なんだよ…！！」\
`"Y-You bitch... are you calling me a bully?! `@`I'm the one being bullied here, I'm the victim...!!"`\


;bg black,1
;bg ura5,23
;ld r,YUK_D1,0
;ld l,YOS_D1,1


;cl l,0
;mld c,YOS_D1,23
;ld r,YUK_D1,80

cl r,0
ld c,YOS_D11,24
ld l,YUK_D3a,1
se1v 10,50
quakex 2,200


;「きゃッ……！」@
`"Ahh-....!"`@
br
;　由香里の胸倉を掴み上げ、塀に押し付ける。@
`　He grabbed Yukari's collar and held her against a wall.`@
br
;　女のくせして図体のでかいヤツとは思ってたが、こうしてみると、案外、華奢なヤツだった。\
`　Before, he thought that she had a relatively large build for a girl, but when she was backed against the wall like this, she seemed unexpectedly slender.`\
ld c,YOS_D10a,80

;「俺はいじめられっこなんだよ、いじめっこじゃねぇんだよ！！@　二度と俺をいじめっこなんて言うんじゃねぇ！！」@
`"I'm the one who's bullied. I'm not the bully here!! `@`Don't ever call me a bully again, are we clear?!"`@
ld l,YUK_i2a,80

;「……うぅん、言うよ。@君はいじめっこだよ……！」\
`"...No, I'll say it again. `@`You are a bully...!"`\
ld c,YOS_D12,80
quakey 1,100

;「このアマ、言わせておけば………！！！」@
`"You bitch, if you say that one more time....!!!"`@
br
;　さらに胸倉を掴み上げる。@彼女の喉は圧迫されて息苦しいようだった。\
`　He grabbed her collar again. `@`This time he applied pressure to her throat, choking her.`\
ld l,YUK_i3a,80

;「……何があったの、……吉川くん……。@………最初は、私もいいかなって思ったの。@……今までずっといじめられていた君が、急にたくましくなって。@一方的にやられるだけじゃなくて、少しやり返せるようになって。@……もういじめられっこじゃなくなったって思って、喜んでたの。@……でも、君はどんどんおかしくなって、……今じゃ、ただのいじめっこじゃない！！」\
`"...What happened to you... Yoshikawa-kun...`@` ....At first I was glad about the change.`@` ...To see a kid that was bullied for so long to suddenly become stronger. `@`For you to not just take the bullying lying down, but fight back.`@` ...I thought you were no longer going to be bullied, so I was happy for you.`@` ...But, something about you changed... and now you're nothing more than a bully yourself!!"`\

;mld c,YOS_D1,80

bg black,22
bg roji_03a,22

;bg aka1,0
;mld l,YOS_D1,22
;mld l,YOS_D1,80

me2v 5,50

;「いじめっこじゃねぇよ、俺はいじめられっこだよ！！@　あいつらに、寄って集っていじめ抜かれてきた日々の心の傷は、@ちっとも癒えちゃいねぇんだよ…！！@　それが癒えねぇ限りッ、俺はずっとずっといじめられっこ！@　そしてこいつらは俺をいじめた、@いじめっこ、……加害者、犯罪者なんだよッ！！」\
`"I'm not a bully! I'm being bullied!! `@`I have wounds on my heart from the days when they would team up and pick on me, `@`and they still haven't healed yet...!! `@`Until they heal, I'm the one who is being bullied! `@`And those who picked on me, `@`they're the bullies... they're the aggressors and criminals!!"`\
;mld r,YUK_D1,22
;mld r,YUK_D1,80
;ld r,YUK_D1,80

;「だからそれをやり返すのが、君の言う正当な復讐ってわけね。@………君の気持ちも理解は出来るよ。@これまでの分を仕返ししたい気持ち、わからないわけじゃない。@……なら、それはもう充分じゃないの？！@　もう充分、彼らをいじめたでしょ！！」\
`"And so you want to get back at them, have your rightful revenge.`@` ....I understand how you feel. `@`It's not like I don't understand the feeling of wanting payback for all that.`@` ...But isn't this enough?! `@`Haven't you bullied them enough?!"`\
bg black,22

bg ura7,0
ld c,YOS_D10,22
ld c,YOS_D10n,80

;「全然足りてねぇよ！！@　あいつらは寄って集って大勢でいじめたんだ！@　それに比べたら、こいつらは俺一人にいじめられるだけ。@大甘じゃねぇか！！@　それにな、俺の心の傷が癒えたかどうかは、お前じゃねぇ、俺にしか決められないんだ！！@　被害者である俺だけが、復讐の権利と、心の傷がいつ癒えたかどうかを決定できるんだッ！！」\
`"It's nowhere near enough!! `@`They all ganged up on me when they bullied me! `@`Compared to that, what I can dish out to them alone, `@`it's far too lenient on them!! `@`And you're not the one who can decide whether or not I've had enough to heal my heart, I'm the only one who knows that!! `@`I'm the victim, so I'm the only one who can decide what amount of revenge is necessary to heal the wounds caused to my heart!!"`\
ld r,YUK_i1a,24
;ld r,YUK_D1,80

;「…………じゃあ！@　彼らが、君を今までいじめてきてごめんなさいって謝ったら！@　君は許してくれるの？！」\
`".....But! `@`What if they apologized for everything they did to you! `@`Would you forgive them then?!"`\
cl c,0
ld l,YOS_D8a,24

;「その謝罪が本気だったら、そりゃ俺の心にも届くだろうさ。@でもな。@心に届いたかどうかを決めるのは俺だ、被害者の俺だけなんだ！@　あの執拗ないじめの日々の謝罪が、@ちょっと一言、ごめんなさいと言ったくらいで、簡単に許してもらえるとか思うんじゃねぇぞ…！！」@
`"Only if I find their apology sincere enough. `@`But, `@`the only one who can decide if it's sincere enough is me, the victim! `@`Their bullying went on for a long time! `@`So I'm not about to let off the hook with just a simple 'I'm sorry'...!!"`@
br
;　そう言い、正明は少年の背中を蹴り飛ばす。\
`　Masaaki kicked the boy on the back.`\


;mcl c,0
;bg black,1
;bg ura7,23
;ld r,YUK_D1,0
;ld l,YOS_D1,22

se1v 12,50
quakex 2,200

wait 500

;「ご、……ごめん……、ごめん………。」@
`"I-... I'm sorry... I'm sorry....."`@
br
;　少年はすっかり怯えきり、由香里の背中に隠れて半泣きしている……。\
`　The boy fearfully hid behind Yukari's back, on the verge of tears...`\
ld r,YUK_i3a,80

;「ほらっ。@彼は謝ったわよ！@　許してあげなさいよ…！！」\
`"See? `@`He apologized! `@`Forgive him...!!"`\
ld l,YOS_D8,80

;「それっぽっちで許すかよ。@俺がいじめられてきた日にち分、毎日、土下座して謝罪し続けやがれ…！！@　お前らは永遠に加害者なんだよ！@　そして俺は永遠に被害者なんだ！@　俺の心の傷は永遠に癒えねぇんだ。@だから永遠に土下座して謝り続けやがれ…！！」\
`"Do you really think something that half-assed is going to be enough? `@`They'll have to get down on their knees and profusely apologize for every single day that they bullied me...!! `@`They will always be the criminals! `@`And I will always be the victim! `@`The wounds on my heart will never disappear. `@`So they should have to apologize forever...!!"`\
cl r,0
ld c,YUK_D1,24
;bg white,24

E_A

se1 10
mbg white,1
mbg black,22

;bg ura7,0
;ld c,YUK_D1,0
;ld l,YOS_D1,22

;　……乾いた音と同時に、正明の世界が、少しだけ横にぶれた。@
`　...There was a sharp echoing sound, and Masaaki's vision was pushed slightly to the side.`@
bgm1 22

br
;　目に涙を溜めた由香里に、平手で打たれたと気付くのに、少しだけ時間が掛かった。\
`　It didn't take him long to realize that Yukari had hit him across the face with her open palm, tears gathering in her eyes.`\
mcbg 22
ld l,YOS_D10a,80

;「………………………………。」@
`"..............."`@
;＜正明

ld c,YUK_i2a,0

;「………私はいじめもいじめっこも大嫌い。@……いじめと悪ふざけを履き違えた、無自覚ないじめっこはもっと嫌い。@………でも、あなたみたいないじめっこは、もっともっと嫌いッ………。」\
`"....I hate bullies and bullying.`@` ...I hate those who can't the difference between bullying and messing around even more.`@` .....But, I hate bullies like you most of all....."`\
cl c,23

;ld l,YOS_D1,80

;「……………………………。」@
`"............."`@
br
;　由香里はくるりと背を向け、@涙で目を真っ赤にしている少年の肩を叩き、一緒に鍵を探そうと話し掛ける。@
`　Yukari abruptly turned her back to him, `@`and patted the shoulder of the boy who's eyes were red from crying, telling him that she'd help him find his key.`@
;　もう、正明のことは完全に無視していた。\
`　She was now completely ignoring Masaaki.`\


;ld l,YOS_D1,80
cl l,0
ld c,YOS_D8a,23

;「…………ンだよ…………。@……ンだよ、……畜生………。@……何しやがんだよ、……榊てめぇ………。」@
`"......What the.....`@` ...What the.... damn it.....`@` ...What the fuck was that?... Sakaki, you bitch....."`@
br
;　由香里は応えない。@聞こえているはずなのに、まったく聞こえないかのように無視している。\
`　Yukari didn't respond. `@`She heard what she said, but she just ignored him.`\


;ld l,YOS_D1,80
ld c,YOS_D11,80

;「…………畜生ぉ……。@……畜生ぉ、畜生ぉッ、……畜生ッッ！！！」\
`"......Damn it...`@` ...damn it, damn it... Damn it!!!!"`\


;cl l,24
;bg black,22

cl c,24
bg black,24

;　正明は駆け出す。@
`　Masaaki ran off.`@
br
;　……由香里の無視が、それほどまでに彼の心を抉ったのだろうか。\
`　...Out of everything that had happened to him thus far, being ignored by Yukari probably hurt his heart the most.`\
;　いや、それは彼自身にしかわからないこと。@
`　Or rather, it was a pain that only he could understand.`@
br
;　彼はその日を境に、自他共に認める本当のいじめっことなった……。\
`　That day was the turning point for him. From then on everyone, himself included, consider him to be a true bully...`\

fede 0,2000
E_A
wait 1000







;■ここから後半


me1v 16,50

bg gakkou_01,22
wait 2000
bg black,22

bg kyou_04,22
;ld c,YOS_D1,22

;　正明によるいじめの矛先は、@かつて自分をいじめていた生徒以外にも向けられるようになった。@
`　Masaaki's targets changed. `@`He no longer only bullied those who had once done the same to him.`@
br
;　彼は今や、クラスの暴君。@
`　He was now the tyrant of this class.`@
;　彼と目が合わないよう、皆、俯きながら学校生活を送る他なかった。\
`　His classmates had no choice but to go about their school lives with their heads held low, trying not to look at him.`\


;　誰もが暗く俯き、意識は希薄になっていく。@かつて正明がそうだったように。@
`　Everyone lowered their head gloomily, trying to make themselves as unnoticeable as possible. `@`Just as Masaaki had once done himself.`@
br
;　その一方で。@正明にとっての世界は、燦々と太陽が照りつける南国かのように、@日々が明るく快晴で、満ち足りたものだった。\
`　On the other hand, `@`Masaaki's life was like living on a bright sunny tropical island. `@`Every day was sunny and beautiful and happy.`\
;ld c,YOS_D1,80

bg kyou_03,2

;　クラスメートにとっては、教室の天井は圧迫感を覚えるほどに低く暗く感じられるのに。@
`　To the others in the class, it felt like the ceiling of the classroom was closing in on them day after day, making the world feel small and dark.`@
br
;　正明にとっては、天井どころか、@まるでリゾート地のビーチで、パラソルの下でくつろいでいるかのようにさえ感じられるのだ。\
`　But to Masaaki, `@`that ceiling felt like a big parasol on the beach next to a resort, providing him a relaxing shade.`\

;　全てが広々として快適で。@……学校そのものが、@彼にとってはもはや、リゾートホテルのような気分だった。@
`　In fact... `@` everything was so spacious and comfortable to him, `@`that the entire school itself felt like a resort hotel.`@
br
;　それに伴い、正明にも自覚できるくらいの愉快な変化があった。\
`　And in addition to that, just about everything had changed for the better for him.`\
bg black,22
bg kyou_01,22

bgm1 7

;　まず、成績の上昇だ。@
`　First of all, his grades were getting better.`@
br
;　視界が明るくなり、頭の回転が早まり、記憶力が著しく上昇した。@
`　His vision had also gotten sharper, his thinking quicker, and his memory remarkably better.`@
;　その結果、黒板に書かれる内容や、先生の話す内容が、@まるでスポンジで水を吸うかのように、どんどん吸収できた。\
`　Because of that, he could understand what's written on the backboard and the contents of the teacher's lectures better. `@`He was soaking up the lessons just like a sponge.`\

;　勉強そのものも、まるでテレビのバラエティ番組のように感じられ、@応用問題も愉快なクイズのように感じられた。@
`　Even studying felt like a variety TV show to him. `@`Application exercises like pleasant little quizzes.`@
br
;　その結果、どんどん成績は上昇し、勉強は更に面白くなり、@それらが好循環となり、正明の成績はどこまでも上昇していった。\
`　And so, his grades got even better because of that, and then studying got even more fun in result. `@`It became a cycle of rising grades for Masaaki.`\

bg black,22
bg koutei_01,22

;　それは勉強だけでなく、運動もだった。@
`　And it didn't just apply to studying either, he always exercised more.`@
br
;　世界が明るくなるにつれ、体がどんどん動くようになった。@
`　As his world got brighter, he worked his body harder.`@
;　息も長く続くようになったし、何より、テンションが上がるようになった。\
`　His breathing got steadier, and his spirits rose higher.`\

;　辛くて苦手だったマラソンさえ、友達を小突いてじゃれ合いながらの遊びに感じられた。@
`　Even a difficult marathon felt like playing and running around with friends.`@
;　球技も競争も、何もかもが遊びに感じられる。@
`　Ball games, competitions, they all felt like playing.`@
br
;　だから、あらゆる教科の成績がぐんぐん上昇した。\
`　So he gradually got better grades in physical education as well.`\
mov %SMI_Isyou,2
bg black,22
bg shokuin_01,22

;　それを先生に褒められるようになり、先生からの評判も鰻上りだった。@
`　And thus, that became a source of praise from his teachers, and he quickly became well-known amongst them.`@
br
;　だから、先生は正明がクラスメートにちょっかいを出していても、好意的に見て、いじめとは捉えなかった。\
`　So whenever Masaaki would pick on a classmate, the teacher would take his side and wouldn't see it as bullying.`\
;　勉強も運動も全てが好調。@
`　Studying, exercising, he was good at everything.`@
br
;　先生の受けもよく、正明にとっての学校生活は、まさに薔薇色だった。\
`　Even the teachers loved him. Masaaki was living an ideal school life.`\
bg black,2
;bg aka1,0
ld l,SMI_w2,22
ld l,SMI_w3,80

;「どうであるか、正明。@これがいじめっこの世界なのじゃ…！」@
`"How is it, Masaaki? `@`This is the world of bullies...!"`@
;＜スミレ

mld c,YOS_D7,22
mld c,YOS_D8a,80

;「……はは、はははははは……。@すげぇや……。@信じられない……。@これが、あいつらの世界なんだ………。」\
`"...Haha, hahahahaha....`@` It's great... `@`It's hard to believe... `@`that this is the world they were living in....."`\
ld r,AZA_D3,22

;「いじめられっこは、蔑まれるだけでなく、その世界も暗く澱み、希望の光さえ消え去る。@……しかし、いじめっこの世界は、これほどまでに輝き、充実し、希望に満ちているのです。」\
`"The world of those who are bullied is not only one of disdain, but it is also dark and stagnant, with any slight ray of hope immediately erased by the darkness.`@` ...But the world of bullies is this bright, fulfilling and brimming with hope."`\
mld c,YOS_D8,80

;「……確かに……。@かつては大嫌いだった勉強も運動も、@……全てが信じられないくらいに絶好調で……。@今の俺なら、何も出来ないことなんかないって、気持ちになります……。」\
`"...It really is....`@` I used to hate studying and exercising.... `@`But now I'm doing so well at them... `@`I feel like there's nothing I can't do nowadays..."`\
ld r,AZA_D2,80

;「気持ちではありませんよ。@それは今や、あなたの立派な実力なのです。@今のあなたなら、学業も学校生活も私生活も、全てを完璧にやり遂げ、@立派な成績と自信をもって、より素晴らしい世界に羽ばたいていくことが出来るでしょう。」\
`"It's not just a feeling. `@`That is truly what you are capable of right now. `@`Right now you are perfectly accomplished in your schoolwork, school life and private life. `@`Using your excellent grades and self-confidence, you are able to fly yourself to a whole new, even more wonderful world."`\
;＜アザミ

ld l,SMI_w4,80

;「お前もテレビで、一流の芸能人やスポーツ選手、あるいは政治家を見て、@彼らと自分は違う生き物なのだと思ったことが、一度はあるはず。」@
`"You must have seen some talented actors, athletes or politicians on the TV before, `@`and thought to yourself, 'I'll never be as good as them' right?"`@
;＜スミレ

ld r,AZA_D4,80

;「彼らは皆、あなたと同じ境地だったのです。@今のあなたになら理解できるでしょう。@その世界でなら、彼らの領域に辿り着くことも可能であることを。」\
`"Each and every one of them is living with the same state of mind as you have right now. `@`You should be able to understand as you are now. `@`It's completely possible for you to reach their level."`\

;　理解できる。@
`　He understood.`@
;　そして、人の世が、ピラミッド構造になっていることだって、理解している。@
`　The world of humans is built in the shape of a pyramid.`@
br
;　一流の人間たちは皆、大勢の人間たちを踏み台にして、その上に立っているのだ。\
`　All of the top-class human beings use the masses of other people as stepping stones to each the top.`\
me2v 28,70

bg aka1,2

;　それはまさに、……この境地だったのだ。@
`　That... is the state of mind she was talking about.`@
br
;　皆を虐げ、魂を食らう。@
`　To oppress everyone, and feed on their souls.`@
;　自分の世界は明るくなり、何もかもが充実し、それを先生に大いに評価される。\
`　To brighten his world, and become perfect at everything, that is what the teacher's admire.`\

;　評価された人間はもう、誰にも咎められない。@遊ぶようにいじめ、遊ぶようにどこまでも上り詰める。@
`　Valued people are never judged by anyone. `@`They bully like it's a game, and climb to the top, like it's a game.`@
br
;　逆に、魂を食われた人間たちは。@……どこまでも暗く狭い世界に落ち込み、@まるでいじめっこを引き立てるかのように転落していく……。\
`　On the other hand, those who have their souls eaten.... `@`they will always stuck in their small and dark worlds. `@`It's like they fall just to help the bullies reach the top...`\
;bg aka2,22
ld r,SMI_w5,22

;「いじめは、いじめられる人間にとってのみ、害悪なのじゃ。@上り詰める人間にとっては、@それはただ、人生の階段を一段一段踏みしめることでしかないのじゃ。」\
`"Bullying is harmful only to those who are bullied. `@`But to those who will reach the top in life, `@`they are just single steps on the stairway to success."`\
;＜スミレ

ld l,AZA_D4,22
;ld l,AZA_D1,80

;「草原では、ヤギにとってライオンは恐ろしい害悪でしょう。@しかし、ライオンにとって、ヤギは生きるための糧でしかなく、@それを狩ることは悪でも何でもないのです。」\
`"Out on the grasslands, lions are a terrifying form of harm to the wild goats. `@`But to the lions, those goats are nothing more than food. `@`The fact that they hunt is not seen as evil or anything of the sort."`\
;＜アザミ
; ^^^ Note To Editor: I can't figure out if Ryukishi is talking about Lions on the savanna eating gazelle, or Lions on the Indian subcontinent eating goats. He uses the word "goats" but most English speakers don't associate Lions with praying on goats. Feel free to leave it as goats or change it to another horned animal, it never comes up again so it's not that important. -Jorwil
ld r,SMI_w6,80

;「その上、動物の王者と持て囃され賞賛を浴びるのはライオンだけ！@　ふっふふふふ！！@　何と素晴らしきいじめの世界なのじゃ！」@
`"Rather, the lion is actually praised and admired as the king of the animals! `@`Fufufufu!! `@`What a magnificent world of bullying they live in!"`@
;＜スミレ

ld l,AZA_D2,80

;「あなたは、いじめられることを知るからこそ、いじめっことして今の境地に至ったのです。@あなたは、どこまでもどこまでも上り詰める資格と権利があります。」\
`"You know what it was like to be bullied before reaching your current state of mind as a bully. `@`Because of that, you have the capability and privilege to climb to any heights."`\
;bg black,23
;bg aka3,0
mld c,YOS_D8a,80

;「どこまでも上り詰める、……権利………。」\
`"The privilege... to climb to any height...."`\
mcl c,0
bg black,22

;ld r,AZA_D1,22
;ld r,AZA_D1,80

;「くす。@夜を知らねば、朝日の価値を理解できぬに同じこと。@いじめの闇を知るあなただけが、その権利を持つのです。」\
`"*Giggle* `@`It's the same as needing to know the darkness of night in order to appreciate the rising sun. `@`You have that privilege because you've seen the darkness of bullying."`\
;mld c,YOS_D1,80

;「………そ、……そうさ……。@……俺はずっとずっと……、憐れなくらいのいじめられっこだった……。@その底辺を、這って這って這いずり回ってきたからこそ……、@このいじめっこの世界が理解できるんだ……。」\
`".....That... that's right...`@` ...I was... miserably bullied for a long, long time.... `@`Because I crept around that bottom level of the pyramid for so long... `@`I'm able to better understand this world of bullies..."`\
;ld l,SMI_D1,23
;ld l,SMI_D1,80

;「うむ。@お前をいじめていたヤツらは、ただ面白おかしかっただけ。@その世界の素晴らしさをまったく理解できてはいなかったのじゃ。」@
`"Mhmm. `@`Those who bullied you did so only for fun and laughs. `@`They didn't grasp the true magnificence of the world they lived in"`@
;ld r,AZA_D1,80

;「蔑まれた毛虫も、やがては美しい蝶となる……。@どこまでも羽ばたくと良いでしょう。@あなたの活躍を、ずっと見守っていますよ………。」\
`"Like a scorned caterpillar finally turning into a beautiful butterfly... `@`you can fly yourself anywhere. `@`I will be watching what you will accomplish....."`\
se1 84

fede 1,3000
E_B

mld c,YOS_D8,2

;　俺は、……王様なんだ。@
`　I... am a king.`@
br
;　このクラスの全てのヤツらから、魂を税金のように吸い上げて君臨する、王様なんだ。\
`　A king that rules over the class and taking tax on their souls.`\
;　そして王様は、こいつらを踏み台に、さらに上の世界を目指す。@
`　And as king I will use them as stepping stone to reach a higher world.`@
br
;　そうさ。@俺の踏み台になってくれたこいつらの分まで、@俺は上の世界へ行かなくちゃならないんだ。@
`　That's right. `@`I have to take myself to a higher world, `@`not just for my sake, but for the sake of my stepping stones as well.`@
;　俺は王様。@……王様、王様……。\
`　I am the king.`@` ...The king, the king....`\
mld c,YOS_D8a,80

;「はは、………ふっはははははっはっはっはっは！！」@
`"Haha..... FuhahahahahaHAHAHAHA!!"`@
;「やめてよ、吉川くんッ！！@　もう止めてあげて……！！」\
`"Stop, Yoshikawa-kun!! `@`Please stop already...!!"`\
mcl c,0
bg black,22

fede 0,1000
E_A


;■通学路


bg roji_01,2

bgm1 6

;ld c,YUK_i2a,22

;　人が気持ちよく、いじめてたって言うのに。@
`　As I was enjoying myself bullying a classmate...`@
;　またあの、クソうるさい榊由香里が俺を見つけて、絡んできた。@
`　That annoying-ass Yukari Sakaki found me and involved herself in my business again.`@
br
;　……どいつもこいつも、俺を恐れて言い成りなのに、こいつだけは未だに俺を恐れていない。\
`　...Everyone else was too scared to stand up to me, but she was the only one left unafraid.`\
ld c,YUK_i3a,23

;「とにかく、降りなさいよ…！！@　可哀想でしょ…！」@
`"At least get down from there...!! `@`It's pathetic...!"`@
br
;　正明は、クラスの少年を四つん這いで歩かせ、その上に跨って下校していたのだ。\
`　Masaaki was forcing one of the boys from their class to crawl on all fours on the way to his house while he rode on the boy's back.`\
bg black,23
bg roji_02,0
ld r,YOS_D7,23
ld r,YOS_D4,80

;「……こいつは俺とタクシーごっこをしてるだけなんだよ。@こいつは俺の舎弟だから、俺のタクシーが出来て嬉しいんだよ。@……な？」@
`"...He's just playing taxi with me. `@`He's my underling, so he's more than happy to help me out by being my taxi.`@` ...Right?"`@
;「……………ん…………。」\
`".......y........"`\
ld r,YOS_D12,80

se1 12
quakey 1,100
wait 300
se2 12
quakey 1,100


;「嬉しいってさっき言ったじゃねぇかよ…！！@　おらッ、言えよ、グズ！！」@
`"Didn't you tell me you were happy to...?! `@`Say it out loud, you dimwit!!"`@
;「うッ、嬉しいっす…！@　嬉しいっす！！@/
`"I-I'm happy to...! `@`So happy!!`@/
se2 12
quakey 1,100
;　ぐッ、ぎッ…！！」\
` Guh, gahh!!"`\

;　正明はその言葉を聞けると、ようやく少年のお尻を蹴り上げるのを止めた。@
`　Upon hearing those words, Masaaki finally stopped digging his foot into the boy's butt.`@
br
;　断りなく立ち上がると、正明にまた乱暴されると怯える少年は、@それでもなお、四つん這いを止めることが出来ない……。\
`　Masaaki suddenly stood up, `@`but the boy, who was afraid of getting hurt by Masaaki again, stayed down on his hands and knees...`\

ld l,YUK_i1a,24
ld l,YUK_i3a,80


;「……あなただって、かつてはいじめられていたじゃないっ。@そのあなたが、なぜいじめられっこの気持ちをわからないの？！」\
`"...You were bullied once too, you know? `@`How can you have no sympathy for those you bully now?!"`\
ld r,YOS_D10,80

;「前にも言っただろ。@いじめられていた俺だからこそ、人をいじめる資格と権利があるんだよ。」@
`"You've asked that same thing before. `@`It's precisely because I was bullied that I have the capabilities and right to bully as I do now."`@
ld l,YUK_i2,80

;「そんな権利、誰が与えたって言うのよ！」@
`"Who gave you that right?!"`@
ld r,YOS_D8,80

;「お前には言ってもわからねぇよ。@くっくっく……。@もう誰も、俺には逆らえねぇ、止められねぇ。」\
`"Even if I told you it wouldn't matter. `@`Kukuku... `@`No one can oppose me now, no one can stop me."`\
ld l,YUK_i1a,80

;「……せ、先生やご両親に言いつけるよ。」@
`"...I-I'll go tell your teachers and parents on you."`@
ld r,YOS_D7,80

;「言ってみりゃいい。@先生も親も、ぐんぐん成績の上がる優等生の俺を、@目に入れても痛くないくらいに可愛がってくれてるぜ。@お前の言うことなんて、相手にするかよ。」\
`"Go ahead and try. `@`With my grades as they are now, I'm an honors student. `@`Both my parents and teachers are more proud of me than anything. `@`Do you really think they'll take your tattling seriously."`\
ld l,YUK_i2,80

;「それでも私は……、……絶対にいじめを許さないっ。」\
`"Still..... I refuse to let you get away with bullying."`\
ld r,YOS_D8a,80

;「しつこい女だな。@何でそんなに、いじめいじめってうるせぇんだよ。」\
`"You're such a persistent girl. `@`Why do you care that much about bullying?"`\
ld l,YUK_i3a,80

;「……私も、………かつてはいじめられていたからよっ。@だから私は、いじめの酷さや悲しさを知ってるのっ。」@
`"...I... was also a bullied child once. `@`So I know the horrors and sorrow that bullying brings."`@
ld r,YOS_D8,80

;「……………………………。」\
`".............."`\
bg black,22

;　なるほど………。@正明は納得する。@
`　I see.....`@` I understand now.`@
br
;　榊由香里の、いじめに対するしつこいくらいのこだわりは、@自分がいじめられっこだったことに由来するのだ。\
`　The reason for Yukari Sakaki's obsession with bullying, `@`is because she was once bullied herself.`\
bg roji_03,22

;「………前のクラスでかよ？」@
`".....Were your classmates the one who did it?"`@
;「うん。@………かつての吉川くんと、同じように。」@
`"Yes.`@` ....The same way your classmates once did to you."`@
;「なるほど。@……それでラッキーにも、あの事故でいじめっこが全員死んで、@俺たちのクラスに来たってわけだ。」\
`"I see.`@` ...Then you're lucky. `@`Since you're whole class died in an accident, and you got to come to our class."`\
bg black,24
bg roji_01,0
ld r,YUK_D1,24
ld r,YUK_i2,80

;「ラッキーなんて言わないで。」@
`"Don't call it being lucky."`@
ld l,YOS_D8,23
;ld l,YOS_D1,80

;「ラッキーだったさ。@そうでなきゃ、お前は今でもそいつらにいじめられてたんだろ。」@
`"But it was lucky. `@`If that didn't happen, you would still be facing their bullying right now."`@
ld r,YUK_i4,80

;「………………………。」\
`"............"`\
ld l,YOS_D7,80

;「お前はそのラッキーに救われた。@……俺にはそのラッキーがなかった。@……いや、あったか。@………俺は、……魔法のアザミを見つけることが出来たんだから。」\
`"You were lucky enough to be saved.`@` ...I didn't have that luck.`@` ...No, maybe I did.`@` .....I... found a magical thistle."`\

;　魔法のアザミの話は由香里も、一応は知っている。@
`　Yukari was mostly familiar with the story of the magical thistles.`@
;　彼の豹変を囁く時、誰もが口にする。@
`　Everyone was talking about it after his personality suddenly changed after all.`@
br
;　しかし、当の本人の口からそれが語られるとは思いもしなかった。\
`　But she never though that she'd hear Masaaki himself say he did it.`\
ld r,YUK_i1a,80

;「魔法のアザミって、……学校の八不思議の話だよね……？」@
`"The magical thistles... are one of the eight mysteries of the school, right....?"`@
ld l,YOS_D8a,80

;「あぁ。@俺も昔は、どうでもいい与太話だと思ってたぜ……。@……だがな、本当にあるんだよ。@それはいじめられっこにしか見つけることが出来ないんだ。」\
`"Yeah. `@`I used to think it was just a baseless rumor...`@` ...But they really exist. `@`Only those who are bullied can find them."`\
ld r,YUK_D3a,80

;「……それを食べればいじめっこになれるって言うけど……。@……まさか、本当に……？」@
`"...They say that if you eat one you'll be able to become a bully...`@` ...Did you really....?"`@
br
;　アザミはアザミだ。@ただの雑草だ。@
`　A thistle is just a thistle. `@`They're nothing more than weeds.`@
;　そんなものを食べても、いじめられっこをいじめっこに変えるような魔力が、あるわけもない。@
`　Even if a bullied kid eats one, they shouldn't have any magic power to change them into bullies.`@
br
;ld r,YUK_D1,80

;　……しかし、由香里は何か引っ掛かるものを感じる。\
`　...But Yukari felt like there was a catch.`\

ld l,YOS_D8,80

;「俺は教えられたのさ。@いじめっこの世界ってのをな。@……いじめは楽しいぞ、最高だ。@いじめこそは、魂を食らう狩りなんだ…！」\
`"I was taught. `@`Taught about the world of bullies.`@` ...About how great it was to bully. `@`About how bullying was like hunting and devouring souls...!"`\
ld r,YUK_i1a,80

;「…………吉川くんは、……教えられたんだね。@……いじめの、………愉悦を……。」@
`".....Yoshikawa-kun... was taught.`@` ...About the joy.... of bullying..."`@
br
;　由香里は確信する。@
`　Yukari was positive.`@
;　いじめの楽しさを、囁く者、唆す者。\
`　She knew who was whispering to him, and tempting him with the joys of bullying.`\
;　由香里は辺りを見渡す。@……もちろん、自分たち以外に誰もいるはずはない。@
`　Yukari surveyed they area around her.`@` ...Naturally, there shouldn't be anyone else here but these three children.`@
br
;　だけれども、確実に居ることを確信し、言った。\
`　However, to confirm her suspicion, she spoke.`\
cl r,0
ld c,YUK_i3a,24

;「……スミレちゃんでしょう……。@出てきて……！！」\
`"...Sumire-chan, you're here aren't you....? `@`Show yourself...!!"`\
bg black,22

fede 0,1000
E_A

wait 1000

se1 84
bg roji_03,22

wait 1000

ld c,SMI_w3,2
ld c,SMI_w2,80

bgm1 12

;「ふっふふふふ……。@……ひっひひひはっははははははははは！！@　久し振りじゃのう、由香里…！@　私の名を覚えていてくれたとは嬉しいことじゃ！！」\
`"Fufufufu....`@` ...Hihihihahahahahahaha!! `@`It's been a while, Yukari...! `@`I'm glad you still remember my name!!"`\
;＜スミレ

;「あなたね。@吉川くんに、いじめの愉悦を教えたのは。」\
`"Was it you who told Yoshikawa-kun about the joys of bullying? `@`It was wasn't it."`\
ld r,AZA_D2,22
ld r,AZA_D4,80

;「全ては因果応報。@日が昇れば沈むように、彼がいじめられてきたならば、@いじめることを知るのもまた、摂理。」\
`"It is all karma. `@`Just like when the sun rises it must set, `@`because he was bullied, he deserve to know what it's like to bully. It's divine intervention."`\
;＜アザミ

bg black,23
bg roji_02,0
ld l,YUK_i1,23
ld l,YUK_i1a,80

;「……スミレちゃんと……、……誰？」\
`"...Sumire-chan and..... Who are you?"`\

ld r,SMI_w2,22
ld r,SMI_w5,80

;「ふっふふふふ！@　私の姉者なのじゃ！！@　学校妖怪序列第４位、復讐のアザミとは姉者のことよ…！！」@
`"Fufufufufu! `@`This is my elder sister!! `@`Fourth Ranked of the School Youkai, Azami the Vengeful...!!"`@
ld l,YUK_i2a,80

;「……なるほど。@吉川くんに魔法のアザミを与えて豹変させたのは、@……やっぱり妖怪の仕業だったのね。」\
`"...I see. `@`You are the one who gave that Yoshikawa-kun the magical thistle that changed him.`@` ...I had a feeling this was the work of a youkai."`\
ld r,SMI_w6,80

;「お前も覚えている通り。@我らはいじめの愉悦を教えるだけ。@それに酔い、染まるのは人間の勝手なのじゃ！@　我らは別に、正明を操っているわけではないのじゃ！」\
`"You must remember. `@`All we do is teach humans the joy of bullying. `@`Whether they choose to become tainted by it or addicted to it is up to them! `@`We weren't manipulating Masaaki, he did it of his own accord!"`\

;　……それは由香里も覚えてる。@
`　...Yukari remembered that.`@
br
;　スミレはいじめの愉悦を教えるだけ。\
`　Sumire only t only teaches the joy of bullying.`\
;ld l,YUK_D1,80

;　しかし、教えられたらもう、いじめっこに成り果ててしまう。@
`　But once she's done teaching them, they've already become a bully.`@
br
;　人間らしい心を忘れ、知らず知らずの内に妖怪の手先となっていじめを繰り返すだけの存在に成り果ててしまう。\
`　They lose the humanity in their heart, and unwittingly become a pawn of the youkai, able only to continue their streak of bullying.`\
cl r,0
ld c,SMI_w2,24

;「お前が私に、いじめを許さないなどと啖呵を切ったこと、よぉく覚えているのじゃ！@　人間の分際でよくも私にそのようなことを！@　身の程を思い知らせてやるために、@こうして姉者の力を借りて、再び現れたわけじゃ！」\
`"I haven't forgotten how you preached to me about not allowing bullying! `@`To think that a lowly human such as yourself would have such nerve! `@`I will make you know your place. `@`That is why I have borrowed my sister's help and appeared before you once again!"`\
;ld l,YUK_D1,80

;　本来、スミレが恨むべき相手は、彼女の狩りを横から全て掻っ攫った彼岸花のはずだ。@
`　Originally, Sumire wanted to get revenge on Higanbana, the one who stole her prey out from under her nose.`@
br
;　しかし、彼岸花は恐ろしい妖怪なので、到底、仕返しできない。@
`　But Higanbana is a terrifying youkai. There's no way Sumire could get revenge on her.`@
;　それで、逆恨み的に、由香里を仕返しの相手に選んだわけだ……。\
`　And so, she shifted her resentment, and chose to take her revenge out on Yukari instead...`\
ld c,SMI_w6,80

;「お前、いじめは許さないのであろう？@　正明のいじめ、どう止めてみるというのか！」\
`"You said you won't allow bullying, right? `@`Well then, how do you intend to stop Masaaki from bullying?!"`\
ld r,AZA_D1,22
ld r,AZA_D3,80

;「くす。@……吉川正明は、いじめ抜かれ、深く傷付いたからこそ、@誰にも負けない、素晴らしいいじめっことなりました。@故に、あなたが如何に咎めようとも、耳を貸さないのです。」\
`"*Giggle* `@`...Masaaki Yoshikawa was hurt very deeply by bullying. `@`So he became a great bully, that won't lose to anyone. `@`Furthermore, how do you intend to scold him when he won't even listen to you."`\
ld c,SMI_w5,80

;「ふっふっふ！@　自分をいつまでも被害者だと思っているからのぅ！@　自分のことを被害者だと思い込む加害者ほど、性質の悪いものはこの世にないのじゃ！」\
`"Fufufu! `@`He will always think he's the victim! `@`There is no one more bad natured in this world than a perpetrator who refuses to see himself as anything but a victim!"`\
cl l,0
mld l,YUK_i2,80

;「……確かに吉川くんはかつて、気の毒ないじめられっこだった。@……だからこそ、私も彼が変わった最初、@……少しくらいはやり返しても、それは仕方ないことと思ってた。」\
`"...It's true that Yoshikawa-kun was once a pitiable bullied child.`@` ...And it's true that in the beginning.... `@`I too thought he was entitled to a little payback."`\
ld r,AZA_D5,80

;「それこそが、因果応報なのです。」\
`"It was karma, retribution for evil deeds."`\
mld l,YUK_i3,80

;「違うよ。@因果応報という言葉を振りかざして繰り広げる、これは第二のいじめでしかないっ。@……あなたたち妖怪が甘言で、……吉川くんを最悪のいじめっこに育て上げてしまったっ。」\
`"Wrong. `@`You throw words like 'karma' and 'retribution' around, when it's nothing more than another bullying.`@` ...You youkai used your honeyed words... to make Yoshikawa-kun into the worst imaginable bully."`\
ld c,SMI_w2,80

;「くっくっくっく！！@　その通りなのじゃ！@　いじめは許さぬと大見得を切ったお前が、@正明をどう止められるか、実に見物なのじゃ！！」\
`"Kukuku!! `@`You're right! `@`You spoke so proudly before about stopping bullying before. `@`So I just wanted to see if you could stop Masaaki!!"`\
mcl l,0
bg black,22

fede 0,2000
E_A

bg roji_01,0
ld l,YOS_D3a,22

me1v 16,30

;　正明には、由香里が誰と何をやり取りしているのか、さっぱりわからないようだった。@
`　Masaaki confusedly watched as Yukari appeared to be arguing with someone.`@
br
;　だから不愉快に、ドンっと由香里の肩を小突く。\
`　He decided to push Yukari on the shoulder.`\
se1 10
quakex 2,200
ld l,YOS_D10a,80

;「………誰と喋ってんだよ。@シカトすんじゃねぇよ。」@
`"....Who are you talking to? `@`Don't ignore me."`@
ld r,YUK_i4,24

;「…………………………。」\
`"............."`\
ld l,YOS_D9,80

;「榊。@……俺がいじめられてた時、お前だけはいつも庇ってくれたよな。@……よくもしつこく、……何度も何度も。」@
`"Sakaki.`@` ...When I was being bullied, you were the only one who ever stood up for me.`@` ...You went out of your way... time and time again."`@
ld r,YUK_i2,80

;「……私、……いじめは絶対許さないから。」\
`"...Because... I will never allow bullying."`\
ld l,YOS_D8a,80

;「それに、……俺なりに感謝してたつもりなんだぜ。@……だから今日まで、クラスの誰をいじめようとも、……お前だけはいじめなかった。」@
`So... I wanted to thank you in my own way.`@` ...That's why... you were the only one in our class that I didn't bully."`@
ld r,YUK_D1,80

;「…………………………。」\
`"............"`\
bg black,22
mono 1
bg kyou_01,22


;　それは、由香里も多少は理解していた。@
`　Yukari more or less knew that as well.`@
br
;　彼は人変わりしてから、クラスの誰でも彼でも、機嫌次第で目に付いた子に、@好き放題ちょっかいを出し、いじめてきた。\
`　Since he changed, `@`Masaaki would indiscriminately bully anyone and everyone in his class as he pleased.`\

;　……しかし、由香里にだけは、手を出さなかった。@
`　...But Yukari was the only one who he never did anything to.`@
br
;　由香里が割って入ってくると、正明は舌打ちをして立ち去り、決して絡むことはなかった。\
`　Whenever Yukari would show up and try to interfere, he would just click his tongue and walk away, never involving her.`\
bg black,24
mono 0
bg roji_02,24
ld r,YOS_D8a,24

;「お前はうぜぇしうるせぇ。@だが、お前だけは特別に見逃してやる。@……だからそれに感謝して、二度と俺に絡むんじゃねぇ。」\
`"Your annoying and meddlesome. `@`But I'll make sure to overlook all that.`@` ...So as thanks, don't ever involve yourself with me again."`\
ld l,YUK_i1,23
;ld l,YUK_D1,80

;「……嫌だよ。@君がいじめをする限り、……私は絶対に見逃さない。」\
`"...No. `@`As long as you keep it up... I will never overlook your bullying."`\
ld r,YOS_D10,80

;「じゃあ、明日からお前もいじめてやるよ。@お前だけ特別扱いしない。@……むしろ、これまで見逃されてた分、明日からしつこくいじめてやるよ。@二度と俺に口出し出来なくなるまでな。」\
`"Fine, then starting tomorrow I'll bully you as well. `@`I won't give you special treatment.`@` ....Or rather, I'll start bullying you enough to make up for all the times I've overlooked you. `@`So bad that you'll be able to interfere again."`\
ld l,YUK_D1,80

;「………やってみたら？@　私だって、吉川くんに負けないくらい、いじめられてきたもん。@……だから絶対、挫けないよ。」\
`".....Go ahead and try. `@`I've already faced bullying worse than yours, Yoshikawa-kun.`@` ...You won't break me."`\
cl r,0
ld c,YOS_D8a,24

me2v 17,50

;「俺に負けないくらいだぁ……？@　面白ぇこと抜かすじゃねぇかよ……。@気に入ったぜ、榊！！@　明日からは覚悟しろよ、お前が泣くまで、いじめていじめて、いじめ抜いてやるぜ！@　……降参するなら早めにしろよ。@何しろ俺は、いじめが楽しくて楽しくて仕方がねぇんだからな。@ついつい手加減を忘れて、何をしちまうかわからねぇぞ…！！」\
`"Worse than mine....? `@`Sounds interesting.... `@`You've piqued my interest, Sakaki!! `@`Prepare yourself, because starting tomorrow I'm going to bully you endlessly until you cry!`@` ...If you want to surrender, do it now. `@`Otherwise, don't think I'll go easy on you. `@`I love bullying so much, I might just lose control of myself...!!"`\

;　正明は由香里の鼻を食い千切らんばかりに顔を近付けて、にやりと笑い、凄む。\
`　Masaaki threatened Yukari with a grin on his face. His face was close enough to hers to bite her nose.`\
cl l,0
mld l,YUK_i1,80

;「………そうしたいなら、そうしたらいい。@……吉川くんが私をいじめてる間は、……他の子たちは君にいじめられなくて済むだろうし。」\
`"....If that's what you want to do, go ahead.`@` ...If you're wasting your time bullying me... then that you won't be able to spend that time bullying the other kids."`\
cl c,0
ld r,YOS_D8a,24

;「…………………………。@……へっ。@……へっへへへへへへへへへ。@面白ぇや、榊由香里。@……明日からは覚悟しろよ。@……たっぷりたっぷり。@お前だけと、遊んでやるからな……。@……くっくくくくくくくくくく……。」\
`".............`@` ...Heh.`@` ...Heheheheheheh. `@`You're an interesting one, Yukari Sakaki.`@` ...Prepare yourself.`@` ...Starting tomorrow, `@`I'm only going to be playing with you...`@` ...Kukukukukukuku..."`\
cl r,22

;　正明は気色悪く笑いながら、由香里を残して立ち去る。@
`　With a sickening laugh, Masaaki left.`@
;　いじめられていた子も、おずおずとその後を追って駆け出す。@
`　After which, the nervous bullied kid ran off.`@
br
;　……残された由香里は、正明の背中をじっと見詰めていた。\
`　...Yukari was left alone, staring at Masaaki as he walked away.`\
mcl l,0
bg black,22

fede 0,1000
E_A

bg roji_03,22
ld c,SMI_w3,22
ld c,SMI_w5,80

bgm1 7

;「自らいじめられることを望むとは！@　つくづく由香里は面白いヤツじゃ！」\
`"Literally asking to be bullied! `@`That Yukari kid is so interesting!"`\
;＜スミレ

bg black,24
bg roji_02,0
mld c,YUK_i4,24

;「……私は絶対。@……いじめなんか、許しませんから。」\
`"...I will never.... `@`forgive anyone who bullies."`\
;bg black,23
;bg roji_03,0
ld l,SMI_w6,22

;「明日よりお前は正明に、たっぷり目を掛けられることになるのじゃ。@どう抗う？@　また無視をするのか？@　それとも先生に言い付けるのか？@　ふっふふふ、どれも無駄なことよ！@　正明にたっぷりたっぷりいじめられて、己が無力を思い知るが良いのじゃ…！！」\
`"Starting tomorrow, he's only going to have eyes for you. `@`How will you fight him? `@`Will you return to ignoring the bullying? `@`Or maybe you'll try telling the teacher? `@`Fufufu, neither of those will work! `@`Masaaki will completely bully you, until you realize your own worthlessness...!!"`\
ld r,AZA_D5,22
ld r,AZA_D3,80

;「もしあなたが彼のいじめに堪えかねたなら。@……その時はあなたを、魔法のアザミの下へ案内しましょう。」@
`"If you find yourself unable to withstand his bullying... `@`then I will lead you to where the magical thistles grow."`@
ld l,SMI_w3,80

;「おお、姉者、それは素晴らしき名案じゃ！@　いじめと抗うと申した由香里が、いじめっことなりいじめの愉悦に染まるとは…！！@　ふっふふふふ、それは実に面白き名案じゃ！」\
`"Ohh, sister, what a splendid idea! `@`The once proud Yukari who went against bullying giving in to the joys of bullying herself...!! `@`Fufufufu, That really is an amusing idea!"`\
mld c,YUK_i2,80

;「……私は、いじめっこになんか、絶対になりません。」\
`"...I will never become a bully."`\
ld l,SMI_w6,80

;「そうは行かぬぞ、そうは行かぬ…！@　必ずやお前にいじめの愉悦を教えてやろうぞ…！@　やがてそなたは、史上最悪のいじめっことなって、@私にいじめの蜜を垂らす、最高のいじめの花となって開花するのじゃ！！」\
`"That won't do, that won't do at all...! `@`One day I will surely teach you the joys of bullying...! `@`I'll make you into the worst bully ever! `@`You will bloom into the greatest bullying flower in the world, and overflow with nectar for me!!"`\
ld r,AZA_D4,80

;「いじめに屈したら、いつでも妾を呼ぶと良いでしょう。@……あなたに、魔法のアザミを授けてあげますよ。@……くすくすくす。」\
`"When you can't handle the bullying any longer, feel free to call me at any time.`@` ...I will gladly grant you a magical thistle.`@` ...Heeheehee."`\
se1 84

cl a,42

mcl c,0
bg black,2

;　………次の日より、榊由香里は、執拗ないじめを受けることとなるだろう。@
`　....Starting tomorrow, Yukari Sakaki will encounter relentless bullying.`@
br
;　正明も、とことんいじめ抜いて屈服させてやろうと、心の中の黒い炎を存分に燃え上がらせていた。\
`　And within Masaaki's heart there burned a black flame that told him to tenaciously bully her until he gives in.`\
;　……しかし、翌日。@
`　...But, the next day.`@
br
;　待ち構えていた事態は、由香里にとっても正明にとっても、衝撃的なことだった……。\
`　With both parties on the lookout for each other, the day turned out to be gut-wrenching for both Yukari and Masaaki...`\
fede 0,2000
E_A



bg gakkou_01,22
wait 2000

bg black,22
bg kyou_01,22

me1v 24,50

;　朝。@ホームルーム前の教室は賑やかだった。\
`　Morning. `@`The classroom before homeroom period was lively.`\

;　由香里はまだ来ない。@
`　Yukari was not there yet.`@
br
;　家の家事もこなす由香里は、朝食の後片付けなどもあるので、登校は少し遅いのだ。\
`　Yukari is in charge of cleaning up after breakfast, so she's always a little late in getting to school.`\

;　正明は、今日からどういじめてやろうかと、黒い笑いを浮かべていた。@
`　Masaaki had a dark grin on his face as he pondered how to best bully her today.`@
br
;　もちろん、由香里が来るまでの間、ぼんやりと席に座っているわけもない。@
`　Naturally, he had no intention of sitting idly at his desk waiting for Yukari to arrive.`@
;　いつも通り、気弱そうに俯くクラスメートたちに絡んでいた。\
`　As usual, he was picking on a group of his timid classmates, their heads hanging in shame.`\
bg black,23
bg kyou_02,23

;　一人の少年の筆箱を取り上げ、こっちこっちと囃し立てながら逃げ回る。@
`　He had stolen one of the boy's pencil cases and was playing keep away with it while mocking the boy the whole time.`@
;　そしてベランダに逃げ、そら返してやるよと、彼に向かって放った時、@……少し強い風が吹いた。\
`　Both of them ended up on the balcony outside the classroom, where Masaaki told the boy if he wanted it so bad, he could have it, and threw the case at the boy.`@` ...And at that moment, a somewhat strong gust of wind blew by.`\
bg koutei_03,23

me2v 5,50

;　投げた筆箱が風に浮き、……ベランダの手すりを越える。@
`　The thrown case got in the wind... and got blown over the balcony railing.`@
;　少年は落とすまいと、ベランダから大きく身を乗り出す。@
`　Not wanting to lose it, the boy leaned out over the railing.`@
;　幸いにもキャッチ出来たが、………少年はあまりに、身を乗り出しすぎていた。\
`　Fortunately he caught it..... but in doing so he also leaned out too far.`\

;「………ぁ、…………ぁ、……ぁ…………。」@
`".....ah..... ah.... ah......."`@
ld r,YOS_D8,24

;「わはははは！@　何やってんだよ、ダセぇなぁ！」\
`"Wahahaha! `@`What are you doing? So lame!"`\

;　危なっかしそうにする少年の姿を、正明は嘲笑う。@
`　Masaaki laughed at the boy, shakily holding his case out over the balcony.`@
br

E_M1

;　……しかし次の瞬間。@……呆気なく、少年の体は、手すりをずるりと乗り越えた。\
`　...But, the next moment... `@`The boy's body tipped a bit too far beyond the railing.`\
bg white,22
bg koutei_03,25
se1 13
quakey 3,500

;　ばきばきめきめきっ。@どさっ。@
`　Crack. Smash. `@`Thud.`@
br
;　少年はベランダの真下に転落した。\
`　The boy fell directly beneath the balcony.`\
bgm1 16

;　そこには、下級生が育てているヒマワリの鉢植えが並んでいた。@
`　Running along the wall there were a line of potted sunflowers being grown by the underclassmen.`@
;　それらをなぎ倒し、……少年は横たわっていた。\
`　The boy had smashed into those pots... and lay on the ground there.`\

;「……ば、……馬鹿、……何やってんだよ…………。」@
`"...Y-... You idiot... Why'd you go and do that....."`@
br
;　正明のその呟きが、眼下の少年に届くわけもない。@
`　Masaaki muttered that under his breath, but there was no way that the boy below could hear him.`@
;　少年は頭を、花壇の縁のレンガにぶつけていたようだった。\
`　He had hit his head on the brick edge surrounding the flower bed.`\
bg blood_1a,48

fede 10,1000
E_MA

;　コンクリートの床の上を、ゆっくりと赤い血が広がっていく……。@
`　Dark red blood slowly spread out over the pavement....`@
br
;　……それを女子が見つけて、絹を引き裂くような悲鳴をあげるまで、@……正明の思考は停止したままだった……。\
`　...Until a girl saw what had happened and let out a shrill shriek... `@`Masaaki had been frozen in thought...`\
bg black,22

;　朝のホームルームは騒然としていた。@
`　There was a big commotion during the morning homeroom.`@
br
;　先生たちは慌しく駆け回り、救急車が出て行くのが見えた。\
`　The teachers were hurriedly running about, and the ambulance could be seen driving off.`\

;「誰か、彼が落ちるのを見てた者はいないか？！」@
`"Was there anyone who saw how he fell?!"`@
br
;　先生がクラス全体に問い掛ける。\
`　The teacher questioned the whole class.`\
bg kyou_03,22

;　……見た者は、いる。@
`　...Yes, there were people who saw him fall.`@
br
;　正明が筆箱を取り上げてからかい、それを放り投げた為、@……それを取ろうとして、眼下に落ちたのを、見ていた者は何人かいる。\
`　Masaaki had stolen his pencil case and thrown it at him... `@`There were many students in the class who had seen him try to catch it, and fall down below.`\

;　しかし、彼らは正明を恐れ、……俯き黙っていた。@
`　But, they were too afraid of Masaaki... and so they avoided eye contact and kept silent.`@
;　そんな中、……おずおずと手を上げる者があった。@
`　But among them... there was one person who nervously rose his hand.`@
br
;　それは、正明本人だった。\
`　And that was Masaaki himself.`\
bg black,22
bg kyou_01,22

;「おぉ、吉川が見ていたか。@先生に詳しく状況を教えてくれ。」\
`"Oh, you saw what happened Yoshikawa? `@`Please tell me the details."`\
ld c,YOS_D3a,22
ld c,YOS_D10a,80

;「………あ、あいつ、@…………ふざけて駆け回ってて。@……それでその、……手すりにでも跨ろうとしたのか、急に手すりを登り出して、@………落ちて……。」\
`"....H-He....... `@`was messing around.`@` ...And then he... sat on the up on the railing, then suddenly decided to stand on it.... `@`and fell..."`\
;　落ちた少年が、ひとりでふざけていて、転落した。@
`　The boy fell when he was playing around, alone.`@
;　正明はそう、証言する。@
`　That was Masaaki's testimony.`@
br
;　それは事実にまったく反する。@しかし、そういうことにするのも、不可能ではないだろう。@
`　It was the complete opposite of what had really happened. `@`But, it wasn't impossible to imagine the boy doing something like that.`@
br
;　クラスの暴君である彼がそう宣言したのだ。@……彼を恐れるクラスメートたちは、真実を告発できるわけもない。\
`　That story was the he as the tyrant of the class declared to be the truth.`@` ...And his classmates were to frightened to say otherwise.`\

;　それは転落した少年も同じだ。@
`　The boy who had fallen was the same.`@
;　いじめっこのせいで落ちた、などと言えば以後、執拗にいじめられるに違いない。@
`　If the kid said that he fell because of bullying, he knew that he would face even harsher bullying from then on.`@
br
;　だから、正明の嘘を告発できる生徒など、存在するわけもなかった……。\
`　So, there was not a single student who would speak up against Masaaki's lie...`\
bg black,22
bg Different_spiral_1a,22

me1v 16,50

;　正明の心臓は、ばくばくと高鳴り続けている。@
`　Masaaki's heart continue to beat rapidly.`@
br
;　……下手をしたら警察沙汰だろうか。@これは傷害罪になるだろうか。@
`　...But what if his lie was caught, would the police get involved? `@`Could this be charge under bodily harm?`@
;　いやそもそも、あいつは無事なんだろうか。@救急車に運ばれる間、身動き一つしないように見えた。\
`　Was the boy even alright? `@`When they loaded him into the ambulance he wasn't even moving an inch.`\

;　もしも病院で死んだ、……なんてことになったら、俺は人殺し………。@
`　What if he dies at the hospital... wouldn't that make me a murderer......?`@
br
;　全身から噴出す汗を堪えることなど、出来るわけもない。\
`　So much sweat was pouring out of his body that he could hardly bear it.`\

bg kyou_03,22

;　そんな正明からは、@……何をしても許されるという、クラスの暴君としての威厳や畏怖は、失われていた……。\
`　As he was right then... `@`Masaaki, the tyrant of the class who could get away with anything, had lost ever last ounce of dignity and dread he held...`\
bg black,2

fede 0,2000
E_A

bg kyou_02,22

me1v 24,50

;　昼休み。@……正明はクラスの男子数人に取り囲まれた。@
`　Lunch break.`@` ...Masaaki was surrounded by a large group of boys from his class.`@
br
;　彼らは少し及び腰ではあったが、……正明の暴政に対し、抗おうという強い意思が感じられた。\
`　They were a bit apprehensive... but it felt like they were determined to oppose Masaaki's tyranny.`\
ld c,YOS_D9,22
ld c,YOS_D10a,80

;「……な、何だよお前ら。@何か用かよ……。」@
`"...W-What? `@`Do you guys want something..."`@
br
;　正明も、彼らの様子にわずかに気圧される。\
`　Masaaki was slightly intimidated by their presence.`\
fede 0,1000
E_A

;「吉川さ……。@な、……何、ウソ吐いてんだよ……。」@
`"Yoshikawa... `@`Wh-... why did you tell that lie...?"`@
ld c,YOS_D8a,80

bgm1 7

;「はぁ…？@　俺が、ウソ……？」\
`"Huh...? `@`What lie...?"`\
;「ウソ吐いてたじゃねぇかよ！@　何が手すりに跨ろうとしただよ…！！」@
`"You told a lie earlier! `@`What was that about sitting on the railing...?!"`@
;「そうだそうだッ。@お前が筆箱取り上げて、ベランダから投げ捨てようとしたんじゃねぇかよ！」@
`"Yeah. `@`You took his pencil case and threw it over the balcony!"`@
;「そうだそうだ！！@　お前のせいであいつ、ベランダから落ちたんじゃねぇかよ！@　なのに何、先生にウソ吐いてんだよッ！！」\
`"Yeah, yeah!! `@`It was your fault that he fell! `@`So why did you lie to the teacher?!"`\
ld c,YOS_D12,80

;「……な、……何だと、てめぇら……。@う、うるせぇよ！！@　いい加減なこと言うんじゃねぇ！！」@
`"...Wh-... what'd you guys say...? Shut the hell up!! `@`Stop making things up!!"`@
;「いい加減なこと言ったのはそっちじゃねぇかよ！！」\
`"You're the one who's making things up!!"`\
ld c,YOS_D11,80
se1 13
quakey 1,100

me1v 5,50

;「ンだてめぇらッ！！@　痛ぇ目に遭わされてぇのは誰からだッ？！@　ああッ？！」@
`"What was that?! `@`Do you want me to teach you a lesson?! `@`Huh, DO YOU?!"`@
br
;　昨日までは、正明がそう凄めば彼らは竦みあがってくれた。@
`　Up until today, whenever Masaaki would threaten like that they would cower in fear.`@
;　もちろん、今日だって彼らは竦み上がるが、……臆して閉口したりはしない。\
`　But of course, today, they didn't cower... and they didn't hesitate to continue calling him out.`\
bg black,22

me2v 16,50

;「い、いつまでも俺たちがビビってると思ってんじゃねぇぞ…！」@
`"W-We're not going to be scared of you forever...!"`@
;「……そ、そうよそうよ…！@　吉川くんって、いつも暴力ばっかり…！」@
`"...That's right...! `@`Yoshikawa-kun, you're nothing but a brute...!"`@
;「お前のこと、クラスみんな迷惑がってんだよ…！！」@
`"You're an problem for everyone in the class...!!"`@
;「吉川くんの嘘吐き！@　人殺し！！」\
`"Yoshikawa-kun is a liar! `@`A murderer!!"`\
bg kyou_03,22

;cl c,0
;ld c,YOS_D1,80

me3v 28,70

;「な、何だ、てめぇら？！？！@　俺のことを人殺しとか言いやがったのは誰だ！！@　てめぇか！！」@
`"Wh- What was that?!?! `@`You just called me a murderer!! `@`Was it you!!"`@
br
;　クラスメートたちが、次々に加勢してくる。@
`　One by one, the fellow classmates had been coming to help back up the group of boys.`@
;　気付けば、正明一人をクラス中が囲んで糾弾していた。\
`　By the time Masaaki had realized it, he was being surrounded and blamed by every person in the class.`\
cl l,24
se1 13
quakex 1,100

;　正明は、身近にいた誰かの胸倉を掴み、小突く。@
`　Masaaki grabbed the collar of one of the kids standing closest to him, and pushed him back.`@
;　しかし、今の彼らには火に油を注ぐようなものだ。@
`　But that just added fuel to the fire.`@
br
;　すぐに取っ組み合いになる。\
`　And it very quickly turned into a fight.`\
se1 13
;mbg white,1
;mcbg 22
quakex 2,200

wait 300

se2 13
;mbg white,1
;mcbg 22
quakey 2,300

bg black,22

me4v 17,70

;　しかし多勢に無勢。@
`　But he was outnumbered.`@
br
;　転落事故の動揺のせいでアザミの魔法が切れてしまったのか、@正明がまとっていた、いじめっことしての凄みももはや失われていた。\
`　Because of the unrest caused in Masaaki's mind by the falling incident, the thistle's magical power had been cut off. `@`He no longer held the guise of a bully that he had for so long.`\

;　クラスメートたちのこれまでの鬱積に火がつき、それが野火のように教室中に広がっていく……。@
`　The pent up emotions of his classmates went up in flames and spread throughout the classroom like a wildfire...`@
br
;　いつしかそれは取っ組み合いではなく、うずくまる正明への袋叩きと化していた。\
`　Before he knew it, it went beyond being a fight and became a group mauling of a cowering Masaaki.`\
bg kyou_02,24
ld r,YUK_N1,24
ld r,YUK_i3a,80

;「や、やめてみんな……！@　乱暴はやめて…！！@　いじめはやめて！！」@
`"S-Stop it, everyone...! `@`Stop the violence...!! `@`Stop bullying!!"`@
br
;　由香里が割って入ろうとするが、誰も聞き入れてはくれない。\
`　Yukari tried to stop the group, but no one listened her.`\
me5v 24,70

;bg black,22
bg e009,22

;「これはいじめじゃねぇよ！@　復讐だよ、仇討ちだよ！！」@
`"This isn't bullying! `@`It's revenge, payback!!"`@
;「こいつに俺たちはみんな、酷ぇ目に遭わされてきたんだ。@いい気味だぜ！」@
`"He was always making us suffer. `@`It serves him right!"`@
;「そうよそうよ！@　吉川くんは少し痛い目に遭えばいいんだわ…！」\
`"Yeah! `@`It's our turn to teach him a lesson...!"`\

bg e010,22

se1 12
quakey 2,200
;「あんたが壊したキーホルダー、私のお気に入りだったんだから！！」@
`"You broke my key holder, I really liked that one!!"`@
se2 13
quakex 2,200
;「よくも俺のノートをぐちゃぐちゃにしてくれやがって…！！」@
`"You scribbled all over my notebook, you bastard...!!"`@
se3 8
quakey 2,100
;「何が舎弟だよ、人のこと奴隷扱いしやがって…！@/
`"What was that crap about me being your underling...?!`@/
se2 7
quakex 2,200
;　いつもいつも、いつもいつもッ！！」@
` You're always treating us like slaves!!"`@
se1 12
quakey 2,200
;「もうお前なんか怖くないぞ、死ね死ね死ね死ねッ！！！」\
`"We're not afraid of you anymore, die die die die!!!"`\
textoff
se2 13
quakex 3,200
wait 300
se3 12
quakey 4,500

bg black,22
bg kyou_03,22
ld r,YUK_N2,26

;「止めて、みんな！！@　こんなことは止めてぇえええぇ！！！」\
`"Stop, everyone!! `@`Please stop this!!!"`\

bg black,22

;　確かに今日まで正明がしてきたことは、紛れもなくいじめだろう。@
`　It's true that what Masaaki had been doing up until today had obviously been bullying.`@
br
;　しかし、それに対する報復と称したこの袋叩きも、紛れもなくいじめなのだ。\
`　But this attacking of him in the name of revenge was nothing more than bullying as well.`\
;　でも、クラスメートたちにいじめの自覚はない。@
`　But the class was not aware that they were bullying.`@
;　クラスの仲間をベランダから転落させた「悪党」への、正当な復讐、いや、制裁なのだ。\
`　To the students of this class, Masaaki was a villain who threw their classmate off of the balcony, and this was their rightful revenge, no, his rightful punishment.`\

bg kyou_02,22
;se1 13
;mbg white,1
;mcbg 22

;　この図式は、かつて正明がいじめっこたちに復讐した時とまったく同じだ。@
`　This situation is exactly the same as what happened when Masaaki got revenge on his bullies.`@
br
;　自分たちはいじめられてきたから、この仕返しは正当であるという、@自分たちのいじめの美化、正当化。\
`　Because they were being bullied, they consider this to be fair payback. `@`That's how they justify their glorified bullying.`\

se1 13
quakex 2,200
wait 200
se2 12
quakey 3,200
wait 100
se3v 13,100
quakex 3,300


;　クラスメートたちは正明を袋叩きにしながら、これまでの憂さを晴らしていく。@
`　By beating on Masaaki like this they were able to forget their troubles.`@
;　そこには奇妙な仲間意識や連帯感が生まれ始めていた。@
`　And in doing so a strange sense of camaraderie and teamwork was born among them.`@
br
;　……この感覚、……わかってる。@スミレによって、いじめの愉悦を教えられているのだ。\
`　...This feeling... she knew it. `@`Sumire has taught them the joy of bullying.`\
bg black,23
bg kyou_01,23
ld l,YUK_i3a,23

;「………いるんでしょ、スミレちゃん……！」\
`"....You're here aren't you, Sumire-chan....!"`\
se1v 84,100

wait 1000

fede 10,1000
E_MA


ld r,SMI_w3,22
ld r,SMI_w2,80

;「いるとも、由香里よ！@　正明を袋叩きにして、みんなで友情を深め合う！@　ふっふふひひひはははははは！！@　素晴らしいユートピアなのじゃ！」@
`"Indeed I am, Yukari! `@`Everyone is becoming such good friends by beating up Masaaki! `@`Fufufuhihihihahahahaha!! `@`What a splendid utopia!"`@
ld l,YUK_i2a,80

;「……クラスは、正明くんをいじめることで一つになると？@　またあなたはそんな、馬鹿げたことを…！」\
`"...Trying to unite the class as one to bully Masaaki-kun? `@`You haven't given up that stupid idea yet...?!"`\
cl r,22

bg black,24
bg kyou_02,24
ld l,SMI_w5,23

;「見よ、彼らのこの連帯感を！@　生き生きとした眼差しを！！@　もう彼らはいじめの虜なのじゃ！@　皆で正明を一緒にいじめることで正義を執行する！@　その愉悦の虜なのじゃ！！@　そしてやがては私がこのクラスに現れ、再び同じことを繰り返す！@　そしてこのクラスは全員、たった１人をいじめることでクラス全体が連帯できる喜びに酔う、@私の可愛いいじめの花に育つのじゃ…！！」\
`"Look at their teamwork! `@`Look at the lively emotions on their faces!! `@`They have become slaves to the bullying! `@`They will enact their justice on Masaaki by bullying him! `@`They're slaves to the joy of it!! `@`And then, I will appear before the class and cause it all to repeat once again! `@`And then the class will all team up on another single student, and drown in the delights of bullying. `@`They are my cute little flowers of bullying...!!"`\
ld r,AZA_D3,22
;ld r,AZA_D1,80

me1v 16,50

;「くす。@今度はスミレが狩りをする番です。@妾は吉川くんのいじめのお陰で、たっぷりと魂を得られましたから。」\
`"*Giggle* `@`It's Sumire's turn to hunt now. `@`Thanks to Yoshikawa-kun's bullying, I've helped myself to my fair share of souls."`\
cl l,0
ld c,SMI_w2,23

;「どうだ、由香里よ、驚いたであろう！！@　これぞ、アザミスミレ姉妹の姉妹狩りじゃ！！@　いじめられっこを極上のいじめっこに仕立て上げる、姉者の狩り！@　そしてそれが反転してクラス全体がいじめっことなる、私の狩り！@　そしていじめられっこに転落した正明は、再び姉者に唆され、魔法のアザミを口にし、@これを永遠に繰り返すのじゃ！！」\
`"What do you think, Yukari? Are you surprised!! `@`This is the sisterly hunt of the Azami-Sumire sisters!! `@`My older sister hunts by picking out the weakest most bullied kid, and turning them into a bully! `@`While I hunt by making the class band against that new bully! `@`And then, once Masaaki has fallen, she will tempt him once again with her magical thistles. `@`And we keep repeating that forever!!"`\
ld r,AZA_D2,80

;「くす。@因果応報、わかっていたはず。@いじめられれば、いじめる権利を得る。@いじめれば、いじめられる義務を負う。@彼がこのような日を迎えることも全て、摂理なのです。」\
`"*Giggle* `@`You must have realized this cycle of karma by now. `@`When you're bullied, you gain the right to bully back. `@`And when you're bullying, you are liable to be bullied. `@`Everything that has happened to him, including this day, has been divine intervention."`\
ld c,SMI_w3,80

;「いじめっこといじめられっこが、延々と立場を入れ替えながら、いつまでもいじめを繰り広げていく！！@　我ら姉妹の狩りは永遠に終わらぬ！@　いじめの連鎖を、人間に打ち破ることは出来ぬのじゃ…！！」\
`"The bully and the bullied forever switch places, causing an endless chain of bullying!! `@`The hunt of us sisters goes on forever! `@`Humans cannot break this chain of bullying...!!"`\
bg black,22

fede 1,2000
E_B

;se1 69
bg kyou_03,22

;　昼休みの終わりを告げるチャイムに、正明は救われる。@
`　When the bell that signals the end of lunch period rings, Masaaki would be saved.`@
br
;　しかし、これはこの昼休み限りのことにはならないだろう。\
`　But that would not be the end of what had started here.`\

;　血気盛んなクラスメートたちは、これからも四六時中、正明に対し、復讐を目論む。@
`　The classmates would plan to take their newfound revenge out on him all day, every day.`@
br
;　……彼がどんなに虚勢を張ろうと、@……彼は今や、クラス全体のいじめられっこに転落しているのだ……。\
`　...No matter what false courage he would try to show... `@`he would be taken down by the every bullied student in the class...`\

bg black,22
bg kyou_02,0
ld r,YOS_D13,22

bgm1 13

;　正明は生傷だらけになりながら、俯き、……溢れそうになる涙を堪えながら、@……畜生、畜生と呟いていた……。@
`　While covered in bruises, head hanging in shame... and fighting back tears overflowing from his eyes... `@`Masaaki cursed under his breath...`@
br
;　いじめられっこに逆戻りした彼に、やがて再び、魔法のアザミが与えられ、またいじめの構図が逆転し、@……いつまでもいじめは繰り返される。\
`　Once he had reverted back to being the bullied kid again, he would once again be given a magical thistle, at which point he would relapse into bullying... `@`and this would continue on forever.`\
bg black,23
bg kyou_01,0
ld l,SMI_w4,23

;「そうなれば理想的じゃがな。@まぁ、そううまくは行かぬだろうて。」@
`"It will be an ideal situation. `@`Well, if everything goes smoothly that is."`@
ld r,YUK_D3a,22

;「……うまく、行かない…？」\
`"...If it goes smoothly...?"`\
;＜由香里

cl a,0
ld c,SMI_w6,23

;「お前も覚えておる通り、クラス全体によるいじめは苛烈じゃ。@ほんの数人のいじめに根を上げていた正明如きに、いつまでも耐えられるわけがなかろう。@……元々、か弱いいじめられっこよ。@化けの皮が剥がれた今、そういつまでも持つわけがあるまい！」\
`"As you no doubt remember, being bullied by an entire class is especially severe. `@`Someone like Masaaki, who caved in after being bullied by just a few people, may not be able to tolerate it.`@` ...Originally he was a weak, bullied child. `@`Now that he's shed his transformation, he won't be able to keep up like that forever!"`\
ld l,AZA_D4,22
;ld l,AZA_D1,80

;「復讐しようという気力が、再び生まれれば良いのですが。@……妾の見たところ、次はそうはならないでしょう。」@
`"It would be nice if he regained the willpower to get revenge once again.`@` ...But as far as I see it, next time that won't be the case."`@
cl c,0
ld r,SMI_w2,23

;「落ちて病んで、這いつくばって！@　くっくくくくく、@正明はとことんまで転落して、恐らくは自ら命を絶つことになるのじゃ！@　もちろん、その魂も丸々、私と姉者がいただくのじゃ！」\
`"Depressed and crawling on all fours! `@`Kukukuku, `@`if Masaaki falls that far, he'll probably end up taking his own life! `@`Of course if that happens, my sister and I will eat up the rest of his soul!"`\
ld l,AZA_D3,80

;「その頃には、クラスメートたちはいじめの愉悦にどっぷりと浸かり。@……スミレの狩りを担う、素晴らしき花たちに育っているでしょう。くすくす。」\
`"When that time comes, your classmates will be totally immersed in the joys of bullying.`@` ...And her wonderful little flowers will then do her hunting for her. *Giggle*"`\
ld r,SMI_w6,80

;「さぁ、由香里よ、そなたはどうするというのじゃ！@　正明が自殺するまで見守っておるか？@　ふっふふふ、それは出来まい？@　ならばどうやってあやつを救うというのか！」\
`"So Yukari, what will you do now?! `@`Will you watch Masaaki suffer until he commits suicide? `@`Fufufufu, will you be able to do that? No? `@`Then how do you intend to save him?!"`\ 
mld c,YUK_D3a,22

;「…………………………………。」\
`"..............."`\
ld l,AZA_D4,80

;「およしなさい、由香里。@吉川くんを庇えば、あなたにもいじめられっこのレッテルが貼られますよ。@そうなれば、あなたも吉川くんと同じ末路に……。」\
`"Give it up, Yukari. `@`If you try to help Yoshikawa-kun, then you will be labeled a target for bullying as well. `@`And if that happens, you will meet the same end as him..."`\
ld r,SMI_w3,80

;「ふっふふふふひひひひはははははは！！@　さぁ、由香里よ！@　このいじめ、どうやって止めてみせるというのか！！@　終わらぬいじめの連鎖、復讐という名のいじめの免罪符！@　どう断ち切ってみせるというのか、私に見せてみるのじゃ！！」\
`"Fufufufufuhihihihahahahaha!! `@`Come on, Yukari! `@`Show me how you are going to stop this bullying!! `@`A chain of bullying rationalized as revenge! `@`I want to see how you plan on breaking this chain!!"`\
mld c,YUK_i2a,80

;「………………………………。」@
`"..............."`@
br
;　由香里は下唇を噛みながら俯く。\
`　Yukari bit her lip and stared down at the ground.`\
me2v 5,50

mcl c,0
bg black,22

;　……時間はそうは残されていないだろう。@
`　...There wasn't much time left.`@
br
;　クラス全体でのいじめがどれほど辛いか、由香里はよく知っている。@
`　Yukari knew how hard it was for the class to endure Masaaki's bullying.`@
;　それに正明がいつまでも耐えられるわけもない。@
`　But Masaaki couldn't withstand this attack forever.`@
br
;　彼が自殺の誘惑に負けるのも、時間の問題だ……。\
`　It was only a matter of time before he would resort to suicide...`\
;bg black,22
bg Different_spiral_1a,22

;　いじめは絶対に許したくない。@
`　She would never allow bullying.`@
br
;　そしてそれ以上に、自殺なんて愚行を、絶対に許したくない。\
`　But even more so, she would never allow some to do something as foolish as suicide.`\

;　その為には、……正明を何とか守り、@………みんなを、復讐という名のいじめから、目を覚まさせなければ。@
`　To do that... she had to find some way to protect Masaaki.`@` ....And a way to make her classmates come to their senses and stop their revenge.`@
br
;　しかし、そんなこと、ついさっきの乱闘さえ止められなかった自分に、出来るわけもない………。\
`　But, she wasn't even able to stop that fight just then, how was she supposed to do all that....`\
ld c,MAR_w1,22

;　……毬枝さんのような人間の味方の妖怪が、また助けてはくれないだろうか。\
`　...She wondered if a youkai who supports humans, like Marie-san, might show up and help them out again.`\
cl c,0
mbg black,23
mcbg 23

;　……………それじゃ駄目だ。@
`　......But that wouldn't work.`@
br
;　いじめの輪廻は、常に人間の問題なんだ。@
`　The cycle of bullying has always been a problem of humans.`@
;　だからそれは、人間が解決しなくちゃいけない。\
`　So it must be solved by humans.`\
;　人ならざる者が解決したとしても、それはその場凌ぎに過ぎない。@
`　Even if an inhuman being saved them, that would only be a temporary fix.`@
;　……人間である私が、何とかしなくちゃならないんだ……。@
`　...As a human, I have to do something to solve this on my own...`@
br
;　でも、………どうやって…………………。\
`　But.... what.......?`\
bg black,22

fede 10,1000
E_MA

;　……その時、……由香里の脳裏に、小さなひらめきが浮かぶ。@
`　...And then... a small flash of inspiration crossed Yukari's mind.`@
br
;　しかしそれは、………相当の覚悟を必要とするものだった。\
`　But, in order to work... it would require a considerable amount of determination.`\
bg kyou_01,0
ld r,SMI_w2,22
ld r,SMI_w5,80

;「ほう？@　あやつらのいじめを止める妙案が思いついたというのか？@　これは興味深いぞ、聞いてやろうぞ…！」\
`"Oh? `@`Have you thought up a way to stop their bullying? `@`How intriguing, do tell...!"`\
;＜スミレ

ld l,YUK_i4,22
ld l,YUK_i2a,80

;「………誰か一人をいじめることで生まれるユートピアを、……今は利用するしかない……。」@
`"....I have no choice... but to use that utopia born out of bullying one person..."`@
ld r,SMI_w2,80

;「ほぅ？@　それはどういう意味なのじゃ。」\
`"Oh? `@`What do you mean by that?"`\
ld l,YUK_i3a,80

;「………スミレちゃん。@あなたの力で私を…………、@/
`"....Sumire-chan. `@`Use your power.....`@/
E_A
;クラスのいじめられっこにしてっ。」@
` to make the class bully me."`@
bgm1 6

br
;　その突拍子もない提案に、妖怪姉妹は目を丸くする。\
`　That crazy proposal made the youkai sisters' eyes widen.`\
ld r,SMI_w4,80

;「ほ、ほぅ……！@　これは面白いことを言い出すのじゃ！@　どういう風の吹き回しなのか！」@
`"O-Oh...?! `@`Now you've gone and said something really interesting! `@`What a pleasant surprise!"`@
ld c,AZA_D1,22

;「……くす。@これは素晴らしい自己犠牲です。@……自分がいじめらっこになることで、吉川くんを庇おうというのですね？」\
`"...*Giggle* `@`What a wonderful self-sacrifice.`@` ...Do you intend by protect Yoshikawa-kun by taking the bullying on yourself?"`\
ld l,YUK_i4,80

;「……………このままじゃ、吉川くんはみんなに乱暴されて、@……大喧嘩になって大怪我をすることになってしまう。@……確かに吉川くんは、酷いいじめをみんなにした。@仕返しをしたいみんなの気持ちも、確かにわかるの。@……でも、それを認めて延々と繰り返したら、ずっとあなたたちの思う壺っ。@いじめの連鎖が、永遠に終わらないっ……。」\
`".......At this rate, Yoshikawa-kun will be attacked by everyone... `@`and it will turn into a huge fight and cause him serious injury.`@` ...It's true that Yoshikawa-kun bullied everyone else really badly, `@`and I do understand everyone's feelings in wanting to get back at him.`@` ...But if I let them continue, the same situation will just repeat forever, just like you two want it to. `@`And the chain of bullying will never end..."`\
ld r,SMI_w1,80

;「それで由香里がいじめられっこを引き受けようというのか。@すると、いじめられたお前は一体どうするつもりじゃ？」\
`"So, that's why you will undertake the role of the bullied, Yukari. `@`And then? What do you intend to do then?"`\
cl l,0
mld l,YUK_D3a,22

;「………私をいじめようとする人たちと、……何とか仲良くなれるように、頑張ります。@……彼らは吉川くんの件については、仕返しを正当化できているけれど、私に対しては何もない。@……だから、ちゃんと話し合えば、……いじめは、………なくせるはず………。」\
`"...I will do my best... to get along with everyone trying to bully me.`@` ...They may be able to justify their payback on Yoshikawa-kun, but they won't be able to do the same to me.`@` ...So, if I just talk to them... I should be able... to stop the bullying."`\
mcl l,0
bg black,22

;　それは一理あるかもしれない。@
`　She may have a valid point.`@
br
;　正明とクラスメートたちの確執は、今さら解くのは難しいだろう。\
`　Trying to solve the bad blood between Masaaki and his classmates would be very hard at this point.`\

;　しかし、由香里がいじめられっこになるならば、@その確執は正明に比べ、ないも同然のものになるだろう。@
`　But if Yukari took the bullying upon herself, `@`compared to Masaaki, the class had very little problem with her at all.`@
br
;　……ならば、いじめを止めるように訴えることも、まだ望みがあるはず。\
`　...So there's still a chance that she can stop the bullying.`\

;　自らいじめられっこになることで、……正明を救う。@
`　She will save Masaaki... by become the new bullied kid.`@
;　そして、……何とかみんなと和解して、クラスからいじめをなくす。@
`　And... somehow find a way to reconcile with the class, and end the bullying there.`@
br
;　………由香里が真にいじめと抗うために選ぼうとする、……身を捨てての決断だった。\
`　.....Yukari so genuinely wants to put an end to bullying... that she's ready to sacrifice her own well-being.`\
bg kyou_02,22
ld l,SMI_w2,22

me1v 16,50

;「これは………。@……とんでもないことを考えるヤツなのじゃ。@……姉者はどう思う…？」@
`"This girl....`@` ...really thinks of some outrageous things.`@` ...What do you think, sister...?"`@
ld r,AZA_D2,22

;「………………。@美しい自己犠牲の精神です。@……見てみたくなりました。」\
`"....... `@`It would be a beautiful show of self-sacrifice.`@` ...I would like to see it."`\
ld l,SMI_w6,80

;「ならば決まりじゃ！@　私の力で、お前をこれより、クラス一のいじめられっこにしてやろうぞ！@　皆は正明のことなどケロリと忘れて、そなたをいじめることに夢中になろうぞ！@　……クラス全体とのいじめに、どう抗うか楽しみじゃ！！@　前は結果的に彼岸花に救われたが、……今度は同じ幸運は訪れぬぞ…？@　仮にやって来ても、もう好きにはさせぬ。@姉者は彼岸花と互角の凶暴さを持つ、@凶悪極悪の意地悪偽善妖怪なのじゃからなー！@/
`"Then it's decided! `@`From here on I will use my power to make the class bully you! `@`Everyone will completely forget about Masaaki, and become engrossed in bullying you!`@` ...I'm looking forward to seeing how you'll fight the bulling of an entire class!! `@`Before, you were consequently saved by Higanbana... but can you expect the same stroke of good luck this time around...? `@`Even if it does happen, don't expect us to allow you to have your way for long. `@`My sister's brutality is on par with Higanbana's. `@`She's a diabolical, heinous, malicious and hypocritical youka--!`@/
se1 48
quakey 1,100
;　ふぎーー？！」\
` Fugye--?!"`\
cl r,0
ld c,AZA_D6,24

bgmvol 0

se1 47
quakex 1,100

ld c,AZA_D7,80

;「誰ガ偽善デス、ダ・レ・ガ～～～！！」@
`"W h o are you calling a hypocrite~~~?!"`@
ld l,SMI_i1,80

;「痛たたたたたッ、姉者ぁあぁぁぁぁ痛い痛い痛い……！！」@
`"Owowowowow, SisterrrrraaaaOUCHOuchouch...!!"`@
cl l,22
br
;　アザミがびろーんとお餅のように、スミレの頬を抓って伸ばす。\
`　Azami stretched out Sumire's cheeks liken two balls of mochi.`\
textoff
fedexx 70,50,0,0,0,0,2000

;　……しかし、由香里の決意は揺るがない。\
`　...But Yukari's determination did not falter.`\
ld c,AZA_D1,80

;「良いのですね？　由香里。@　……ならば、あなたの望み。@妾たちが叶えてあげましょう。」\
`"Is that fine with you, Yukari?`@` ...If so, `@`we will grant your wish."`\
ld r,YUK_i2a,22

;「………私が絶対、……このクラスからいじめをなくして見せます。」\
`"....I will definitely... remove the bullying from this class."`\
ld c,AZA_D2,80

;「くす。@……その威勢、どれだけ続くか見せてもらいますよ。@妾はいつもあなたの側で見守っています。@……もしあなたがいじめに屈し、いじめられっこを返上したいと思ったなら。@いつでも妾を呼ぶとよいでしょう。@……そうしたら、あなたにも魔法のアザミを授けてあげますよ。@……あなたにも、いじめの愉悦。@……たっぷりと教えてあげましょうとも。@……くす、……うふふふふふふふふ…………。」\
`"*Giggle*`@` ...Show us how long you can keep up that strength. `@`I will always be by your side, watching you.`@` ...If you ever can't handle the bullying anymore and want to get some payback on your bullies, `@`you can call me at any time.`@` ...When you do, I will grant you a magical thistle.`@` ...Even you can learn the joy of bullying.`@` ...And if you want to, I can certainly teach it to you.`@` ...*giggle*... Ufufufufufu......"`\
cl c,2

fede 10,1000
E_MA

;　スミレの頬を抓り上げたまま、アザミたちはすぅっと姿を消す。@
`　While still pinching Sumire's cheeks, the two of them disappeared.`@
br
;　そして、由香里は体の中に、じわりと嫌な感覚が染み渡るのを感じた。\
`　And Yukari felt an awful feeling spread throughout her body.`\
ld r,YUK_d4a,80

;　……この感覚、……覚えてる。@
`　...She remembered... this feeling.`@
br
;　私はまた、……いじめられっこに、……戻ったんだ………。\
`　I have... once again... become the target of bullying...."`\
bg black,22
bg kyou_03,22

me1v 24,50

;「……み、みんな……！@　吉川くんをいじめるのを止めて……！」@
`"...E-Everyone...! `@`Stop bullying Yoshikawa-kun...!"`@
br
;　由香里がそう叫ぶと、みんながぎょろりと振り返り、……不満げに睨みつける。\
`　As she yelled at them, each and every one of them slowly turned their heads... and gave her a dismal stare.`\

;　そして、悪党を庇うなら榊由香里も悪党だと口々に叫び、@……その矛先を正明から由香里を変えた。@
`　And then, because she was defending a villain, she started all started yelling at Yukari Sakaki like she was a villain too.`@` ...And they changed the target of their attack from Masaaki to Yukari.`@
;　クラスメートたちは、何かに取り憑かれたかのように、@由香里を取り囲んで、口々に罵声を浴びせ、小突いたり蹴ったりする。\
`　As if possessed by something, `@`all of the classmates gathered around Yukari, and engulfed with ridicule and pushed and kicked at her.`\
se1 13
quakey 2,200
wait 200
se2 13
quakex 3,300

bg black,22
bg kyou_01,22

;　彼らの突然の変わりように、正明は呆然とする……。@
`　Masaaki was stunned at how abruptly they moved on from him...`@
br
;　見る見るうちに、人だかりは正明を無視して、由香里を取り囲むものになっていく。@
`　Before their eyes, the entire crowd disregarded Masaaki, and went straight to surrounding Yukari.`@
;　いじめを止めるように説く由香里だが、誰も耳を貸すわけもなかった。\
`　Yukari tried to persuade them to stop bullying, but none of them would lend her an ear.`\
ld l,YOS_D10a,22

;「………お、……お前ら、……何してんだよ……。@……や、……止めろよ………。」@
`"....W-... What... are you guys doing....`@` ...No.... Stop it....."`@
br
;　正明はおずおずと小声で言うが、@……いじめの熱気で頭に血を上らせた彼らの耳に、それが届くわけもなかった………。\
`　Masaaki nervously spoke in a small voice.`@` ...But they were so absorbed in madly bullying the girl, that they didn't hear him.....`\
bg black,2

fede 10,2000
E_MA

bg gakkou_02,2

;　由香里への、クラス全体のいじめは、その後も執拗に続いた。@
`　The entire class continued to relentlessly bully Yukari.`@
;　そんな日々が積み重なり、……すでに十日以上が過ぎていた。@
`　Days passed... and before long ten days had already passed.`@
br
;　数々の乱暴をされ、生傷も絶えず、絆創膏を貼った顔が痛々しい。\
`　They were always attacking her and leaving countless painful looking wounds. Her face was always covered in bandages.`\
bg black,22

;　とぼとぼと下校する彼女を追い、正明は声を掛ける……。\
`　Masaaki caught up with her as she wearily walk home, and called out to her...`\
fede 0,1000
E_A

bg roji_01,22
ld l,YOS_D1,23

me1v 5,50

;「………榊………。」\
`"...Sakaki...."`\
ld r,YUK_D2,2

fede 0,1000
E_A

ld r,YUK_D4,22

;「吉川くん。@…………何……？」@
`"Yoshikawa-kun.`@` ......What is it...?"`@
ld l,YOS_D3a,80

;「………………。」\
`"........"`\
bgm1 24

;　いじめを憎み、決して怯まぬ決意を常に顔に浮かべていた彼女の顔が、@……痛々しいくらいに変わり果てていた。\
`　The face of the girl, who once hated bullying and refused to ever falter in the face of bringing it down... `@`now looked entirely too pitiful.`\

;　あれだけ毎日、酷いいじめに遭っているのだ。@……彼女の世界が今、どれほど暗く窮屈なものか、正明には容易に想像できた。\
`　After having to endure such horrible bullying every day.`@` ...Masaaki could easily imagine how dark and constrained her world must have felt right now.`\
ld l,YOS_D2,80

;「……き、……聞いたぜ。@……あの、妖怪たちに。」@
`"I-... I heard what you did`@` ...from those youkai."`@
br
;　正明はスミレに聞かされていた。@由香里が、彼を庇うために望んでいじめられっこに堕ちたことを。\
`　Masaaki asked Sumire what had happened. `@`She told him about how Yukari wished to take the bullying upon herself in order to protect him.
ld r,YUK_w3,80

;「………私、いじめは絶対、許さないから。」@
`"....I will never allow bullying."`@
br
;　由香里はそう言って、強がるように微笑んだ。@
`　Yukari replied with a smile on her face, pretending to be strong.`@
;　それがかえって痛々しくて、正明の胸が締め付けられた。\
`　But that made her all the more pitiful, and made Masaaki's chest tighten up.`\
ld l,YOS_D3a,80

;「ぜ、………全部、俺のせいだ……。@俺が調子に乗って、……たくさん酷いことをしたから………。」@
`"I-..... It was all my fault... `@`I got carried away... and did a lot of horrible things...."`@
ld r,YUK_w4,80

;「そうだね。@……多少の仕返しならともかく。@少し、やり過ぎちゃったね……。」\
`"That's right.`@` ...It would have been fine if you just settled for a little payback. `@`But, you kind of overdid it..."`\
cl l,0
ld c,YOS_D10a,23

;「……だとしたら、そのやり過ぎた分をやられるのは、俺の役目だ。@……榊の役目じゃねぇ……。」@
`"...So I should be the one who has to pay for overdoing it.`@` ...Not you, Sakaki..."`@
ld r,YUK_w3,80

;「言ったでしょ。@私はいじめが大嫌いなの。@……だから、吉川くんが皆にいじめられるところなんて、絶対に見たくなかったの。」\
`"I already told you. `@`I hate bullying.`@` ...So I absolutely couldn't stand to see you bullied by everyone."`\
ld c,YOS_D10n,80

;「だ、……だからって、………自分がいじめられるのかよ……。」@
`"So.... what?.... You're just going to let yourself get bullied...?"`@
ld r,YUK_D4,80

;「私だって、ただいじめられてるわけじゃないよ。@みんなに、……こんなこと止めようって、@……お願いしてるよ。」\
`"I'm not just letting myself get bullied. `@`I'm... trying to ask everyone... `@`to please stop bullying."`\
ld c,YOS_D12,80

;「……でも、あいつら耳を貸さねぇ。@榊が何を言ったって、いじめを止める気はねぇ……！」@
`"...But, they won't listen to you. `@`They just ignore you and keep on bullying...!"`@
ld r,YUK_D2,80

;「……………………。@……そうみたいだね。」@
`"..........`@` ...It appears so."`@
br
;　由香里も、それを認めつつあった。\
`　Yukari was in the process of admitting that to herself as well.`\
bg black,22

;　……いじめは許さない。@
`　...She wouldn't allow bullying.`@
;　そして、いじめに抗いたい。@戦いたい。@
`　And she wanted to oppose bullying. `@`To fight it.`@
br
;　その気持ちは、今もわずかほども揺るぎはしない。\
`　She still firmly held those beliefs.`\

;　……しかし、認めつつあるのだ。@
`　...But she was beginning to admit it to herself.`@
br
;　今起こっているいじめを止める方法は、……存在しないのかもしれない。\
`　There may be no real way... to stop the bullying happening to her right now.`\
bg roji_03,22

me1v 16,50

;「……いじめってさ。@ババ抜きのジョーカーに似てるよね。」@
`"...You know. `@`Bullying is a lot like the joker in old maid."`@
;「…………………………。」\
`"............"`\

;「最初、君がいじめられてた。@いじめのジョーカーを渡されてた。@そして君はいじめっこになって、そのジョーカーを彼らに渡し返した。@……いじめを止めろと、言うだけなら容易い。@でも、止めたら、ジョーカーを持たされた子は、どうすればいいの。@………いじめられて悔しい悲しい思いをしたまま、ひっそりと我慢して生きていけなんて、@誰に言う権利があるっていうの。」\
`"At first you were the one who was being bullied. `@`You were dealt the joker of bullying. `@`And then you became the bully, and you gave the joker to those guys.`@` ...It's easy to just tell people to stop bullying. `@`But when it does stop, what are you supposed to do about the kid that gets handed the joker next?`@`.... Who's to say, `@`who should be the one to silently endure a life of frustrating and sorrowful bullying?"`\

;「…………………………。」\
`"............."`\
bg black,22

;「誰かがジョーカーを押し付けられなければいけない。@当然、誰もジョーカーなんか受け取りたくない。@……人間は誰だって、幸せに生きる権利があるんだよ。@……誰にだって、ジョーカーを受け取り、抱え込まなければならない義理なんてない。」\
`"Someone must always be holding the joker. `@`Naturally, no one wants to have the joker.`@` ...Everyone has the right to live a happy life.`@` ...But no one wants to take it upon themselves to hold the joker once they receive it."`\ 
bg roji_02,22
ld r,YOS_D8a,24

;「……だったら、榊が抱え込むこともねぇじゃねぇか…！」\
`"...So you don't want to be holding it either, right Sakaki...?!"`\
mld l,YUK_D4,22
mld l,YUK_D2a,80

;「そうだね。@……じゃあ、私は誰にそれを渡すの？@　……私から、いじめのジョーカーを誰かに渡すってことは、@……それって、私がその子をいじめるのも、同じことだよね…？@　だから、吉川くんにだって、それを渡したくない。@だって私は、……いじめが、絶対に許せないから。」\
`"That's right.`@` ...But who would I pass it on to?`@` ...If I pass my joker of being bullied onto someone else... `@`wouldn't that be the same as bullying them myself...? `@`So, I don't want to pass it back onto you. `@`Because... I will never allow bullying."`\
ld r,YOS_D3a,80

;「……………………………。」\
`"............."`\
;　いじめのジョーカーが生まれてしまったら、@……人間に出来るのは、それをババ抜きのようにして押し付けあうことだけだ。\
`　Once the joker being bullied has been created... `@`just like in old maid, humans can only pass it among themselves.`\
;　……かつての由香里はそのジョーカーを、@……クラスがバスごとの事故で全員死亡するという形で、失わせることも出来た。@
`　...Back when Yukari held that joker before... `@`Her class got into an accident while on the bus and they all died, and she was able to get rid of it.`@
br
;　つまりそれは、…………いじめのババ抜きは、@「死」でしか、終わりに出来ないということ……？\
`　So basically... does that mean, `@`that to get rid of the bullying old maid, they must die...?`\
cl r,0
ld c,YOS_D10n,24

;「ふ、……ふざけんなよ……。@誰かが死ななきゃ、……いじめの連鎖は終わらねぇってわけなのかよ……。」\
`"D-... Don't think that way... `@`Having someone die... isn't the way to stop the chain..."`\
mld l,YUK_D3,80

;「他に方法はないかって、……私もずっと考えてるよ。@……そして、思い付いたのがこれだった。」\
`"I've been thinking about it for a while... `@`and the conclusion that I've come to is that there is no other way."`\
mcl l,22

;　自己犠牲。@……いじめの、生贄。\
`　Self-sacrifice.`@` ...A scapegoat for bullying.`\
ld c,YOS_D13,22

;　……ふざけんな。@
`　...Damn it.`@
;　そのババ抜きに、どうして榊みたいないいヤツが犠牲にならなきゃいけねぇんだ……。\
`　Why does someone like Sakaki have to sacrifice herself for this game of old maid...`\

;　どうせ犠牲になるなら、クソッタレで最低なヤツがジョーカーを引き受ければいい。@例えば俺だっ。@……断じて榊なんかじゃねぇ…！@
`　If anyone has to be the sacrifice, it should be some worthless piece of trash kid. `@`Like me for example.`@` ...Just not Sakaki of all people...!"`@
br
;　正明は由香里の悲壮な決意に、涙を浮かべる……。\
`　The tragic, yet heroic, resolve of Yukari brought tears to Masaaki's eyes...`\
bg black,24
bg roji_05,24
ld r,YUK_D1,22

;「……最近、わかったの。@いじめのジョーカーは、生み出されたらもう、……どうしようもない。」@
`"...Recently, I've realized. `@`Once the joker of bullying has been created... there's nothing we can do."`@
ld l,YOS_D13,22

;「………………………。」\
`"..........."`\
ld r,YUK_w3,80

;「みんなで回して、いじめのバトンリレーをするか。@全てのジョーカーを誰か一人に集めて、残りの全員が幸せになるユートピアか、@……そのどちらかしかないの。」\
`"Either it's like a relay race, and everyone passes around the bullying baton between each other. `@`Or one person ends up getting all the jokers and everyone else lives happily in their utopia.`@` ....Those are the only options."`\
ld l,YOS_D14,80

;「……いじめが生まれた時点で、……必ず誰かが不幸になる。@それが救われても、次の誰かが……犠牲になるっ……。」\
`"...When the bullying starts... someone becomes happy. `@`And then, even if they're saved, someone else... becomes a sacrifice..."`\
bg black,22
bg roji_06,22

;「そう。@いじめのジョーカーが生まれた時点で、@……そのババ抜きは、誰かを犠牲にするまで、決して終わらないの。@……それが、クラスや学年、学校全体、……あるいはこの世の全てをぐるぐる、ぐるぐると巡って、悲しみを連鎖させているの。@……生まれたジョーカーは、……どうしようもない……。」\
`"That's right. `@`Once the joker is born.... `@`that game of old maid will indefinitely continue on until someone becomes a sacrifice.`@` ...That chain of sorrow circles around every class, every year, throughout the entire school... and even throughout this entire world.`@` ...Once the joker is born... there is nothing we can do..."`\

;「…………………榊………。」\
`"..........Sakaki....."`\
bg black,22

fede 10,1000
E_MA

bg roji_05,22
;ld r,YUK_D1,0
;ld l,YOS_D1,22

;ld r,YUK_D1,80

;「……いじめに抗うのなんて、……不可能だったかもしれない。@……ひょっとしたら、……私は大きな勘違いを、……していたのかもしれない……。」\
`"...It might be... impossible to oppose bullying.`@` ...I may... have made... a huge mistake..."`\

;　それは、あまりに弱々しい言葉。@
`　Those words were far too feeble.`@
br
;　……由香里の心の、最後の拠り所に、亀裂が入ったかのようにさえ見えた……。\
`　...It seemed like the last foundations of Yukari's heart had started to crack...`\
ld l,YOS_D13,22

;「な、………なら……。」@
`"T-.... then..."`@
ld r,YUK_D2,22

;「…………何……？」\
`"......What...?"`\
ld l,YOS_D14,80

;「い、いじめがどうにも出来ないババ抜きだって言うなら…！！@　お前だって、それを誰かに押し付けていいんだっ。@お前が犠牲になる義理なんてねぇんだ…！！」@
`"I-If it's like a game of old maid...!! `@`You just have to pass it on to someone else. `@`You don't have to be the one to sacrifice yourself...!!"`@
ld r,YUK_D3,80

;「………………………。」\
`"............."`\
cl l,0
ld c,YOS_D14,23

;「……今の榊は、紛れもないいじめられっこだ。@……今のお前になら、絶対に見つけられるはずだ。@……あの、……魔法のアザミを……！」@
`"...Right now you are undoubtably being bullied.`@` ...So right now, you should be able to find one.`@` ...Find... a magical thistle...!"`@
ld r,YUK_D2,80

;「…………………………。」\
`"............"`\
bg black,26
bg roji_03,26

;「アザミさん！！@　聞こえてるなら姿を見せてくれ…！！@　そして榊に、あの魔法のアザミを授けてくれッ！！」@
`"Azami-san!! `@`If you can hear me, show yourself...!! `@`And give a magical thistle to Sakaki!!"`@
br
;　正明は叫ぶ。@
`　Masaaki called for her.`@
;　すぐに笑い声と共に、アザミとスミレの姉妹が姿を現す。\
`　And instantly, two sets of laughter were heard, and the sisters Azami and Sumire appeared.`\
ld c,SMI_w1,0
ld r,AZA_D1,2

ld r,AZA_D2,80

;「くす。@今の由香里は立派ないじめられっこ。@……望むのならば、授けても良いのですよ。」\
`"*Giggle* `@`Yukari has become a splendid bullied child.`@` ...If she wishes it, I will give her one."`\

;「榊っ。@魔法のアザミを食うんだ…！！@　あれを食えばすぐにもいじめっこになれる…！@　誰にもいじめられなくなる…！！」\
`"Sakaki! `@`Eat a magical Thistle...!! `@`If you eat one, you'll instantly be made into a bully...! `@`You'll never be bullied by anyone again...!!"`\
ld c,SMI_w3,80

;「ふっひはははははは！！@　これは面白いのじゃ！@　あの、いじめを憎むと豪語しよった由香里がいじめっこに目覚めるとは、実に面白いのじゃ…！！」\
`"Fuhihahahahaha!! `@`How interesting! `@`Awakening Yukari, who used to brag about hating bullying, to the pleasures of it, how interesting...!"`\
;「………いじめられなくなるかもしれないけど、@……今度は、……私が誰かをいじめちゃうんだよね………。」\
`"....It may save me from the bullying... `@`But... it will also mean that I will start bullying someone myself this time, right.....?"`\
ld c,SMI_w5,80

;「うむ。@姉者のアザミを口にすれば、いじめっことして覚醒することになるのじゃ！」@
`"Yes. `@`If you eat my sister's thistles, you will be awakened as a bully!"`@ 
ld r,AZA_D3,80

;「内より湧き出す覇気と暴力。@……これまでのあなたではいられませんよ。」\
`"Your ambitions and violence will overflow from you.`@` ...You will not be able to remain as the same person you have been thus far."`\
bg black,22

me1v 5,50

bg aka1,22

;　それは正明もよく知っている。@
`　Masaaki knew that very well.`@
;　あのアザミを食べれば、次の日より、まったくの別人として生まれ変わってしまう。@
`　Once he ate the thistle, the very next day he was reborn as a completely different person.`@
br
;　……いじめを誰よりも憎む由香里ですら、その豹変には抗えないのだ。\
`　...Even though Yukari hates bullying more than anyone else, that will not save her from undergoing a complete change.`\
bg black,22

;　しかし、それでもいい。@
`　But, that's fine.`@
br
;　彼女はいじめられるべき人間ではないのだ。@だから彼女は、魔法のアザミを口にしなくてはならない……。\
`　She shouldn't be someone who's bullied in the first place. `@`So she has to eat the magical thistle...`\
bg roji_05,0
ld r,YUK_D2,0
ld l,YOS_D13,22

cl l,0
mld c,YOS_D14,23
;ld c,YOS_D1,80

;「頼むっ。@……榊に魔法のアザミを食わせてくれっ。@そして榊っ。@いじめるなら俺をいじめろ…！！@　調子に乗ってやり過ぎた俺が元凶なんだッ。@お前のジョーカーは俺が引き受けるから！！！」\
`"Please, I'm begging you.`@` ...Let Sakaki eat the magical thistle. `@`And Sakaki. `@`If you have to bully someone, bully me...!! `@`It's my fault you're in this mess. All because I got carried away. `@`Pass your joker onto me!!!"`\
ld r,YUK_D3,80

;「…………………吉川くん……。」\
`".........Yoshikawa-kun..."`\
mcl c,0

bg black,22
bg roji_04,22
ld l,AZA_D4,22


;「くす。@美しい愛情です。@ならばそれを叶えてやることこそ、愛というもの。」@
`"*Giggle* `@`Such beautiful devotion. `@`Then what I grant you is love."`@
ld r,SMI_w3,24


;「さすが姉者じゃ！　@愛という言葉が実に偽善的なのじゃ！！@/
`"As expected of my sister! `@`Love is such a hypocritical word!!`@/
cl l,0
ld c,AZA_D7,23
ld r,SMI_i1,1
se1 47
quakex 1,100

;　ふぎぎぎー、痛だだだだーーッ！！」\
` Fugehgyaa-, Ouchowowowow--~!!"`\
ld c,AZA_D3,80

;「さぁ、どうするのです、由香里さん。@あなたは復讐のアザミを望みますか…？」\
`"Now then, Yukari, what shall you do? `@`Do you wish for a thistle of vengeance...?"`\
bg black,23
bg roji_05,0
ld c,YUK_D3,23

;「……………………………。」\
`".............."`\
ld r,YOS_D13,24
ld r,YOS_D14,80

;「頼む、榊っ。@アザミを食ってくれ…！！@　その後のことは何も考えなくていい！@　後生だからッ。@頼むッ…！！！」@
`"Please, Sakaki! `@`Eat a thistle...!! `@`You don't have to worry about what happens next! `@`For the love of god. `@`I'm begging you...!!!"`@
br
;　正明は、涙を零しながら懇願する。@
`　Masaaki begged Yukari with tears dripping from his eyes.`@
;　日々のいじめによって、暗く曇ってしまった由香里の瞳に、それがどう映ったかはわからない……。\
`　The light in Yukari's eyes was so darkened by the days upon days of bullying, that he had no idea what she thought of all this...`\
ld l,SMI_w3,23
ld l,SMI_w2,80

;「いじめ抜かれ、心がもはや擦り潰れておるではないか！@　迷うことはない、姉者のアザミを食らって生まれ変わるのじゃ…！！」\
`"You've already lost to the bullying, your heart has been grinded to dust! `@`Don't hesitate, eat my sister's thistles and be born anew...!!"`\
bg black,22
bg azami2,22

;　アザミは路肩に咲くアザミの花を摘むと、それに魔力を込める。@
`　Azami plucked a blooming thistle from the edge of the road and imbued it with magical power.`@
br
;　そしてそれを、由香里の眼前に差し出す……。\
`　And presented it to Yukari...`\
bg black,22
bg roji_05,0
ld r,AZA_D1,22
ld r,AZA_D2,80


;「さぁ。@このアザミを食べるのです。@……これであなたはもう、いじめられっこではなくなるのですよ。」@
`Here. `@`Eat this flower.`@` ...With this you will no longer be bullied any longer."`@
ld l,YUK_D3a,22

;「……………………………。」\
`"..............."`\
ld r,AZA_D3,80

;「引き換えに、あなたの心は暴力で満たされ、@常にいじめる誰かを捜し求める飢えた狼に生まれ変わるでしょうが……。@くす、うふふふふふふふ………。」\
`In exchange, your heart will be filled with violent urges. `@`You will be born again as a hungry wolf, always searching for someone to bully... `@`*Giggle* Ufufufufu....."`\
bg black,22
bg roji_03,22

;　由香里の震える指が、……ゆっくりとアザミに伸びる。@
`　Yukari's trembling fingers... slow extended towards the thistle.`@
br
;　しかし、……そのぎりぎりで、……理性で堪えている……。\
`　But... at the last second... her sense of reason held her back...`\

;「……榊っ。@……頼むっ、……頼むッ……！！」@
`"...Sakaki.`@` ...Please... PLEASE...!!"`@
;「……………………………。」\
`"............."`\

;　由香里の指が、………アザミに、……触れる。@
`　Yukari's fingers.... touched... the thistle.`@
br
;　……そして、……それを受け取り、…………………。\
`　...And... she took hold of it.......`\
bg black,22
fede 1,2000
E_B

;「…………………………。」@
`"............."`@
br
;　口にする。\
`　And placed it in her mouth.`\
bg black,22
bg roji_05,0
ld c,YUK_d2a,22

;　……由香里には拒めなかったろう。@無理もない。@
`　...Yukari couldn't resist. `@`It was only natural.`@
;　あの日より、由香里はクラス全体にどれほど執拗にいじめられてきたというのか。@
`　Up until today she had been relentlessly bullied by the entire class.`@
br
;　彼女は精一杯抗った。@でも、それももう限界だ……。\
`　She fought with all her might. `@`But, she was at her limit...`\
;　彼女がいじめっこになったとしても、何の責任があるだろう？@
`　Even if she did become a bully, would it even be her fault?`@
br
;　彼女に何の罪もあるわけがない。\
`　She is innocent.`\

;　……明日より彼女は豹変するだろう。@それはきっと、……辛い光景になるだろう。@
`　...After tomorrow she will the complete opposite. `@`That will surely be... a bitter sight.`@
br
;　しかしそれでも、……彼女には権利があるのだ。@
`　But at the same time... she has the right to do so.`@
;　自分に代わってジョーカーを引き受けてくれた彼女にも、@それを誰かに渡す権利があるのだ……。\
`　This girl who took the joker upon herself, `@`has the right to pass it on to anyone she wants to...`\
ld c,YUK_D4a,80

;　……ごくりと、アザミを飲み込む。@
`　...She swallowed the thistle with a gulp.`@
br
;　その魔力がゆっくりと、由香里の体に浸透していく……。\
`　And its magical power slowly spread throughout Yukari's body...`\
se1v 66,30

bg red1,48
bg black,22
bg roji_04,0
ld c,SMI_w3,22
;ld c,SMI_D1,80

;「ふふ、ふっふふひひひひはっはははははははは！！@　これでもう、由香里はいじめっこなのじゃ！！」\
`"Fufu, fufufuhihihihahahahahahaha!! `@`And now, Yukari is a bully!!"`\
ld r,AZA_D3,22
;ld r,AZA_D1,80

;「明日よりあなたはいじめに飢えた狼です。@……吉川くんも、彼女に近付かぬように気を付けることですよ。@もっとも、あなたは望んで近付き、生贄となるつもりでしょうが。」\
`"Starting tomorrow you will be a bloodthirsty wolf, hungry for bullying.`@` ...Yoshikawa-kun, I would advice being careful of not getting to close to her. `@`Though if you do wish to get close to her, be aware that you will doing so as a scapegoat."`\
cl c,0
mld c,SMI_w2,80

;「いじめを憎む由香里が、その身を犠牲にして救ったお前をいじめるというのだっ。@これは何と愉快な見世物であろうか！！@　ふっふふひひひひひひひひ！！」\
`"The idea of Yukari, who hates bullying, in turn bullying the person she sacrificed herself to save. `@`Is there any greater spectacle than that?! `@`Fufufuhihihihihi!!"`\
mcl c,0

bg black,23
bg roji_05,0
ld l,YOS_D3a,0
ld c,YUK_D2,23

wait 1000

ld c,YUK_D3,22

;　アザミの魔力は、深くいじめられていればいるほど、強く作用する。@
`　The worse the bullying was at the time of eating the thistle, determines how bad of a bully the person will become, that is how its magical power works.`@
;　……由香里はどれほどのいじめっことして、豹変するのか。\
`　...How bad of a bully will Yukari become then?`\
;　それでも、………受け入れる。@
`　Still.... he will take it all on himself.`@
;　正明は、彼女がどれほど豹変しようとも、……彼女を決して見損なわないと誓うのだった……。\
`　No matter how much she changes... Masaaki vows to never be disappointed in her...`\
bg black,2
fede 0,2000
E_A
wait 1000

;　そして、………翌日を迎えた。\
`　And... on the next day.`\
bg gakkou_01,22
wait 2000
bg black,22

bg kyou_01,22

bgm1 14

;　由香里の登校はいつも遅い。@
`　Yukari was late to school as usual.`@
br
;　正明は先に教室に着き、……落ち着かない様子で、由香里を待った。\
`　Masaaki got to the classroom early... and waited nervously for her to show up.`\

;　クラスメートの何人かが、由香里の席に落書きをしている。@
`　A bunch of their classmates were scribbling on Yukari's seat.`@
;　……馬鹿なヤツらだ。@今日を境に金輪際、そんな真似は出来なくなるだろう。\
`　...What idiots. `@`They're going to regret doing that today.`\
ld r,YOS_D3a,22

;　いじめを誰よりも憎んだ榊が、……いじめっこに生まれ変わるなんて……。\
`　Sakaki hated bullying more than anyone out there... but today, she'll be reborn...`\
;　………いいんだ、榊。@
`　It's okay, Sakaki.`@
br
;　いじめのジョーカーを、誰かに受け渡すんだ。@
`　Go ahead and pass your joker on to somebody new.`@
;　……もし、俺みたいに、仕返しをやり過ぎるようなことがあったなら。\
`　...If you happen to overdo your payback like I did...`\

;　その時は、………俺がお前のいじめを全て引き受けてやるから…………。@
`　Then.... I will take all your bullying upon myself.....`@
br
;　お前はジョーカーを手放し、そして俺のようにやり過ぎて誰かに憎まれることもなく、@……いじめから解放されるんだ……。\
`　You will relinquish your joker and, unlike me, you want be hated if you overdo it.`@` ...You will be freed from bullying...`\
bg black,22

fede 0,1000
E_A

bg kyou_02,22
me1v 24,50
ld l,AZA_D5,22

;「そろそろ、由香里さんがやって来る頃です。@………くす。@どのような豹変を遂げているか、楽しみですね。」@
`"It's about time for Yukari-san to show up.`@` ....*Giggle* `@`I'm excited to see what kind of personality she will have."`@
ld r,SMI_w2,22
;ld r,SMI_D1,80

;「おお、姉者！@　由香里じゃ由香里じゃ！@　今、昇降口に入ったぞ…！」\
`"Oh, sister! `@`It's Yukari, it's Yukari! She's here! `@`She just came in through the front doors of the school...!"`\
ld l,AZA_D3,80

;「どんな様子でしたか？」@
`"How does she look?"`@
ld r,SMI_w6,80

;「傍目にはわからぬが、どんよりと重い気配をまとっておったぞ…！@　なかなかの迫力じゃ！」@
`"From an outsider's perspective she wouldn't look that different, but she definitely has a heavy aura about her...! `@`It's pretty intense!"`@
br
;　妖怪姉妹が笑い合っている様子が、正明にも見える。\
`　Masaaki could see the two youkai sisters laughing amongst themselves.`\

;　……俺が妖怪の甘言に乗せられて、おかしなアザミなど食べなければ……。@正明は深く後悔する……。@
`　...Since he was deceived by them and made to eat that strange thistle... `@`Masaaki deeply regretted getting involved with them...`@
br
;　そして、……………榊由香里が、教室にやって来た。\
`　And then....... Yukari Sakaki entered the classroom.`\
bg black,23
bg kyou_01,23

textoff
fede 0,1000
E_A

wait 1000

se1 82
wait 1000
ld c,YUK_i4,22

;「……………………………………。」@
`"................"`@
br
;　彼女は無言だった。@
`　She said nothing.`@
;　なのに、……教室中の人間が、ぎょっとして凍りついてしまうような凄みがあった。\
`　But... she had a sinister look that made everyone in the room freeze in place and stare.`\
me1v 17,50

;　その凄みは、かつての正明のそれより、ずっとずっと恐ろしいものだった。@
`　It was a sinister presence far more dreadful than when Masaaki was a bully.`@
;　その表情は暗く重い。@
`　Her expression was dark.`@
br
;　……迂闊に話し掛けられないどころか、@……近寄られたら、退かずにはいられない迫力があった。\
`　...It had the sort of intensity to it that made it clear that you shouldn't carelessly talk to her.`@` ...Or that if she approached you, you had better get out of the way.`\
bg black,24
bg kyou_03,0
ld r,SMI_w1,24
ld r,SMI_w2,80

;「これは………、凄まじい迫力じゃ…！」@
`"What... a fierce demeanor...!"`@
ld c,AZA_D5,22

;「目があっただけで、殺されてしまいそうですね。」\
`"It feels like she would kill you if you even made eye contact with her."`\

bg black,23
bg kyou_02,0
ld l,YOS_D2,23
ld l,YOS_D3a,80

;「……さ、…………榊……………。」@
`"...S-....... Sakaki......."`@
ld r,YUK_i4,22

;「…………………………。」@
`"............."`@
br
;　由香里は自分の席へ辿り着く。\
`　Yukari trudged on over to her seat.`\

;　……そこには、酷い落書きが残されている。@
`　...A series of horrendous scrawlings were written on her desk.`@
br
;　由香里はしばらくの間、それをじっと見詰めて、俯いていた。@
`　Yukari stared down at it for a while.`@
;　教室中が凍り付いている。@……誰も、……指一本、動かすことも出来ない。\
`　Everyone in the classroom was still frozen.`@` ...Not a single one of them... could move even a finger.`\
bg black,22

;　すると、………ゆっくりと…………。@
`　And then.... slowly.....`@
se1v 13,30
br
;　由香里が机を、…………担ぎ上げる………。\
`　Yukari...... picked up her desk....`\
me2v 28,70

;ld r,YUK_D1,80

;「…………………………………。」@
`"................"`@
;ld l,YOS_D1,80

;「さ、…………榊…………。」\
`"S-...... Sakaki....."`\
fedexx 0,100,100,0,0,0,1000

wait 1000

E_A
se1v 27,100
se2v 2,100
se3v 12,100
cl a,0
mbg white,1
mcbg 22
quakey 2,500


;　稲妻が落ちるような音がして、……その机が、床に激しく叩きつけられた。@
`　With a sound like lightning striking... she slammed her desk into the floor.`@
;　それでもなお、……誰も身動き一つ出来ない……。@
`　But still... no one moved a muscle...`@
br
;　……いや、……誰かが笑った。@
`　...No... actually, someone was laughing.`@
;　笑ったのは、………姉妹妖怪だった。\
`　It was.... the two youkai sisters.`\
bgm1 12

ld c,SMI_w3,0
ld r,AZA_D5,22

;「くす、……うっふふふふふふふふふ！！」\
`"*Giggle*... Ufufufufufufufu!!"`\
ld c,SMI_w6,80

;「素晴らしいぞ由香里！！@　いじめを誰よりも憎んだ由香里が、これほどのいじめっこになろうとは！！」@
`"Excellent job, Yukari!! `@`To think that a girl who hated bullying that much, would become this great of a bully herself!!"`@
ld r,AZA_D3,80

;「見事ですよ、由香里。@さぁ、あなたが今日まで受けた怒りを、悲しみを！@　全て吐き出すのです。@あなたが彼らをいじめることによって！！」\
`"Magnificent, Yukari. `@`Go on! `@`Release all of the hatred and sorrow that you've gathered up until today. `@`Free yourself by bullying them!!"`\
bg black,23
bg kyou_01,23
mld c,YUK_d1,2

me1v 5,70
wait 1000

mld c,YUK_i4,22

;　由香里はゆらりと、……教壇へ歩み出る。@
`　Slowly... Yukari walked over to the front of the class, in front of the blackboard.`@
br
;　そして振り返り、呆然として立ち尽くすクラスメートたちを、ぎょろりと見渡した。\
`　She turned around and looked over her classmates, still with shock.`\
ld l,AZA_D3,22

;「恐ろしい目です。@その瞳に映るは、哀れなるいじめの生贄たち……。」@
`"What frightening eyes. `@`Reflected in those eyes are the pitiful sacrifices to her bullying..."`@
ld r,SMI_w5,22

;「さぁ、由香里よ…！！@　まずは誰をいじめるのじゃ？！@　誰からでも良いぞ！@　選り取りみどりじゃ！！」\
`"Go on, Yukari...!! `@`Who will you bully first?! `@`Anyone is fine! `@`Have your pick!!"`\
ld l,AZA_D4,80

;「気に入る子がいないなら、あなたにいじめられたいと立候補している子もおりますよ。@……ねぇ、吉川くん。@うっふふふふふ……。」\
`"If none of them strike your fancy, there's always the possibility of getting back at the ones who bullied you.`@` ...Right, Yoshikawa-kun. `@`Ufufufufu..."`\

mcl c,0
bg black,24
bg kyou_02,0
ld l,YOS_D9,24
ld l,YOS_D10a,80

;「……………………………。」\
`".............."`\
;＜正明
bg black,22
bg kyou_01,0
ld c,YUK_i4,22

fedexx 0,50,0,0,0,0,1000
E_B

wait 1000

ld c,YUK_i2,80

;「……いじめは、……抗うことの出来ないもの………。」@
`"...You can't... fight bullying...."`@
ld l,SMI_w2,22
;ld l,SMI_D1,80

;「そうじゃ！@　いじめに抗おうなど、愚かなこと！」\
`"That's right! `@`Trying to oppose bullying is beyond foolish!"`\
ld c,YUK_i3,80

;「……いじめは、……生まれてはならない。@……生んではならない。」@
`"...Bullying... must not be born.`@` ...We must not allow it to be born."`@
br
;　生まれたいじめは、ババ抜きになる。@「死」でしか、清算できない。\
`　If it is born, it becomes an old maid. `@`Removable only by "death."`\
bg black,22

fede 0,1000
E_A

bg kyou_02,0
ld l,YOS_D3a,22

wait 1000

ld r,YUK_i1,22

bgm1 27

;「なら。@………いじめなどなかった一番最初。@……私たち人間は、……ユートピアにいたはず。」@
`"Then.`@` ....Back in the very beginning, before bullying existed.`@` ...We humans... must have lived in a utopia."`@
ld l,YOS_D9,80

;「…………………………。」\
`"............"`\
;＜正明

ld r,YUK_i2,80

;「……ねぇ。@……一番最初の人間は、………どうしていじめなんか、始めてしまったの……？@　………いじめなんか生まれなければ、……人間は永遠に、……幸せだったのに……。」\
`"...Hey.`@` ...Why did the first humans... start bullying in the first place...? `@`.....If bullying was never born... humans would have lived in happiness... forever..."`\
bg black,23
bg kyou_01,0
ld r,SMI_w4,23
ld r,SMI_w3,80

;「ふっふひひひはははは…！！@　さぁ、由香里よ！！@　私のユートピアを受け容れるが良い！！@　いじめを押し付けよ！！@　生贄を捧げ、皆で取り囲んで踊るのじゃ！！@　ふっふふふふっひっひっひ……、はっはははははははははははは！！」\
`"Fufuhihihihahahaha...!! `@`Come on, Yukari!! `@`Submit to my utopia!! `@`Force your bullying on them!! `@`Offer up a sacrifice as the others dance around you!! `@`Fufufufuhihihi... hahahahahahahaha!!"`\
ld l,YUK_i2,22

me1v 16,50

;「……だから、………これが、………ユートピア。@………これが私の考える、………ユートピア………。」\
`"...So.... this..... is utopia.`@` .....This is the utopia... that I've wanted....."`\
bg black,26
bg kyou_03,26


;「さ、………榊……ッ。@……やるなら俺を………ッ！」@
`"S-.... Sakaki...`@` ....If you're going to bully use me.....!"`@
br

;　正明が駆け寄ろうとした時。@再び、凄まじい轟音が教室に響き渡った。\
`　As Masaaki tried to run over to her, `@`another thunderous sound shook the classroom.`\
E_A
mbg white,1
se1v 27,100
mcbg 22
quakey 3,500




;　……教卓が、がらんがらんと転げた……。@
`　...The teacher's desk fall over with a clang...`@
;　由香里が教卓を蹴り飛ばしたのだ……。@
`　Yukari had kicked it over...`@
br
;　そして、スミレとアザミを、ぎょろりと睨んだ。\
`　And glared at Sumire and Azami.`\


bg black,24
bg kyou_01,0
mld l,YUK_i4,0
ld c,AZA_D2a,0
ld r,SMI_D7,22

mld l,YUK_i3,80

;「……あなたたちの思い通りになんか、絶対にならないから。@……これが、私の考えたユートピア。@……私の考えた、……いじめへの抗い方。」\
`"...I won't let you two have your way.`@` ...This is the utopia I've wanted.`@` ...The way to oppose bullying... that I've been looking for."`\
;ld c,AZA_D1,0
ld r,SMI_i1,80

;「……………………………ッ…、」@
`"............!"`@
me1v 5,50

br
;　その凄みには、妖怪たちも気圧されざるを得ない……。\
`　The intensity of those words could overwhelm even those youkai...`\
mld l,YUK_i4,80

;「……生まれたいじめの連鎖を、断ち切ることは難しいかもしれない。@……なら、……いじめそのものを、………生まれないようにするしかない。」\
`"...It may be too hard to sever the chain of bullying once it has been made.`@` ...In that case... there's nothing else to do... but make it like that bullying was never born in the first place."`\
ld r,SMI_D3a,80

;「は、はは……。@そ、そんなこと、………どうやって、……やれるというのか……。」\
`"Ha, haha... `@`H-How... do you plan... to do that...?"`\
mld l,YUK_i2,80

;「私がこの教室から、………二度と、いじめが生まれないようにする……。@………私の目が黒い内は、………二度とッ……！！！」\
`"I will make it... so that bullying is never born in this classroom again...`@` ....Never again..... as long as I am alive...!!!"`\

mcl l,24

wait 1000

cl a,0
mbg white,1

E_A
se1v 27,100


mcbg 22
quakey 3,500

;　由香里はもう一度、激しく教卓を蹴り転がした。@
`　Once more, Yukari violently kicked over the teacher's desk.`@
bgm1 21
;　そして、ダンッと踏んで、……新たに君臨した、教室の暴君として宣言した。\
`　And, she stepped up onto it... declaring her reign as the new tyrant of the classroom.`\
ld c,YUK_i4,22
se2v 12,100
se3v 2,100
quakey 7,800

wait 1000

ld c,YUK_i2,80

;「………私はいじめが嫌いだ。」@
`"....I hate bullying."`@
br
;　シンとした教室で、由香里の声だけが、響き渡る。\
`　Yukari voice resounded throughout the otherwise silent classroom.`\
ld c,YUK_i5,80

me1v 5,70

;「……いじめが嫌いだ。@……いじめをするヤツが嫌いだ。@…………わかるか…………。」@
`"...I hate bullying.`@` ...And I hate anyone who bullies.`@` .....Understood......?"`@
br
;　ぎょろりと教室を見渡す。@
`　She slowly surveyed the classroom.`@
;　目があった生徒は、おどおどしながら、首を縦に振る。\
`　Whenever she would meet eyes with someone, they would hesitantly nod in agreement.`\
se1v 12,100
quakey 3,300

;　ダンッ。@
`　Bang.`@
br
;　もう一度、教卓が激しく踏まれた。\
`　She slammed her foot into the desk again.`\
;ld c,YUK_D1,80

bg black,22

;「………いじめをやるヤツは、私が殺す。@……殺されたくなければ、日々を慎ましやかに生きろ。@………いじめっこを食らういじめっこが、この私だ……。@……私は腹が減っている……。@……誰かをいじめたくていじめたくて……、仕方がないんだ……。@………私の餌食が早く現れろ。@………くっくくくくく、……くくくくくくくくく……。@はははは、あっははははっはっはっはっはっはっはッ！！！」\
`"....If anyone of you bullies again, I will kill them.`@` ...If you don't want to be killed, live a modest life.`@` ...I am the bully who devours other bullies...`@` ...And I'm hungry...`@` ...I really... really want to bully someone...`@` ....So if you want to become my prey, show yourself now.`@` ...Kukukuku... kukukukukuku... `@`Hahahaha, Ahahahahahahaha!!!"`\
bg kyou_01,1
se1v 12,100
se2v 2,100
quakex 4,600

;　狂った笑い声は、彼女が激しく黒板を蹴る音で掻き消される。\
`　The sound of her insane laughter was drowned out by the sound of her kicking the blackboard.`\
ld c,YUK_i4,22

;「私にいじめられてぇヤツはいるか。」@
`"Is there anyone here who wants to bully me?"`@
br
;　いるわけもない。@由香里と目が合うと、皆、慌てて首を横に振る。\
`　Of course there wouldn't be. `@`Everyone who met Yukari's eyes hurriedly shook their head.\
ld c,YUK_i5,80

;「…………なら。@……慎ましく生きやがれ。@…………返事はぁあああぁッ！！！」@
`"......In that case.`@` ...You better live an honest and humble life.`@` .......ANSWER ME!!!"`@
se1v 2,100
quakey 3,400
;「「「はッ、はいぃぃぃ…！！」」」@
`"""Y-Yes ma'am...!!"""`@
br
;　その凄みに、クラスメートたちは返事をせずにはいられなかった……。\
`　She was so terrifying that her classmates had no choice but to reply...`\



;<<<<<<<<<<<<<<<<<<




bg black,24
bg kyou_02,24
ld r,YUK_i2,24

;「………吉川。」@
`".....Yoshikawa."`@
ld l,YOS_D10a,22
;ld l,YOS_D1,80

;「あ、……あぁ……。」\
`"Y-... yeah...?"`\

ld r,YUK_i3,80

;「あんた、クラス委員長でしょ。@………いじめ、………ないかしっかり見張んなさいよ。」@
`"You're the class representative, are you not? `@`.....Be...... on the lookout for any bullying."`@
ld l,YOS_D8a,80

;「も、……もちろんさ……。」\
`"O-... of course..."`\
ld r,YUK_i5,80

se1v 2,100
quakey 3,400

;「もしッ！！@　……いじめを見つけやがったら。@すぐに私に言いなよ。@…………その間抜け野郎を、……私が食い殺してやるッ！！！」\
`"If!! `@`...You find any bullying. `@`Come tell me right away.`@` .......I will find that moron... and kill and devour him!!!"`\
ld l,YOS_D10a,80

;「お、……おう………ッ。@……き、……聞こえたか、皆……！@　こ、このクラスでは二度といじめは許さねぇぞ…！@　俺と榊の目の黒い内は、二度と絶対にだ…！！@　いいなッ？！」\
`"Y-.... yeah...`@` ...D-... did you hear that, everyone...?! `@`B-Bullying won't be allowed in this class ever again...! `@`Never again as long as Sakaki and I still draw breath...!! `@`Got that?!"`\
cl r,0
ld c,YUK_i5,24

;「てめぇらッ、返事はッ！！！！」@
`"ANSWER HIM!!!!!"`@
se1v 2,100
quakey 2,200
;「「「はッ、はいぃぃぃ！！！」」」\
`"""Y-Yes sir!!!"""`\
bg black,22

;　生徒たちは由香里のあまりの変わりようにヒソヒソと囁き合うが、@目が合うと俯いて愛想笑いを浮かべる他ない。@
`　The students whispered among themselves about the sudden change in Yukari, `@`but whenever they met eyes with her, they had no choice but to avert their eyes and force a smile.`@
br
;　……これが、由香里が考えて生み出した、彼女なりの、束の間のユートピア……。\
`　...This was the momentary utopia that Yukari had thought up...`\
fede 1,3000
E_B

bg kyou_01,0
ld r,SMI_i3a,22
ld r,SMI_i1,80

;「んな、………何なのじゃ、これは……！！@　これは、……ど、どういうことなのじゃ……！！」\
`"Rrgh.... What is this...!! `@`What... is the meaning of this...!!"`\
;＜スミレ

bg black,23
bg kyou_04,23
ld c,HIG_w3,22

E_A
wait 1000

ld c,HIG_d4,80

bgm1 5

;「くすくすくすくす。@/
`"Teeheehee.`@/

;……一本取られたようね、スミレちゃん？」@
` ...Looks like she got the best of you, didn't she, Sumire-chan?"`@
;＜彼岸花

ld l,MAR_i4a,22
;ld l,MAR_D1,80

;「……由香里ちゃんの強さは、……本当にすごいです。」\
`"...Yukari's strength... really is something."`\
;＜毬枝

ld r,AZA_D4,22

;「おやおや。@彼岸花さんに毬枝さんではありませんか。@妾たちの狩りにようこそ。」\
`"Oh my. `@`If it isn't Higanbana-san and Marie-san. `@`Welcome to our hunt."`\
ld c,HIG_D3,80

;「いつ横から掻っ攫ってやろうかと、ずっと様子を見ていたけれど。@……こんなオチが待っているとは、想像も出来なかったわ。@くすくすくすくすくすくすくす……！」\
`"I've actually been watching the whole time, waiting for a chance to steal your prey from you.`@` ...But I never imagined that this would be the outcome. `@`Teeheeheehee...!"`\
;＜彼岸花

ld l,MAR_D4a,80

;「由香里ちゃんは、……至ったんですね。@……これがいじめをなくす、唯一の方法だと。」\
`"Yukari-chan... found a way, didn't she? `@`....The one way to get rid of bullying."`\
;＜毬枝

bg black,24
bg kyou_02,0
ld c,YUK_i4,0
ld l,YOS_D8a,24

;　生まれてしまったいじめをどうにかするのは、あまりに難しい。@
`　It too difficult to remove bullying after it has been born.`@
br
;　しかし、ならば。@
`　So.`@
;　いじめが生まれない世界を、生み出すしかない。\
`　the only other option in that case is to create a world were bullying can't exist.`\

;　由香里は、自らが暴君として君臨していじめのジョーカーを握り潰し、@リーダーシップを発揮することで、二度とクラスにいじめが生まれないようにしようと、思い至ったのだ。@
`　Yukari realized that she could use her reign as tyrant to tear that joker to pieces, `@`and that by displaying her leadership she could prevent bullying from ever being born in this class again.`@
br
;　……無論、それは容易いことではない。\
`　...Of course, that is no simple task to accomplish.`\

;　由香里は常に睨みを利かせなければならないし、それを毎日続けるのは至難の業だ。@
`　Yukari must constantly hold her authority of the class, and keeping that up every single day would be near impossible.`@
br
;　そして同時に、彼女の存在が畏怖されるべきものでなくては、いじめに対する抑止にならない。\
`　And at the same time, if her presence ever stops striking fear into the others, she will not be able to keep the bullying in check for long.`\
bg black,22
bg kyou_03,22

;　……由香里は、魔法のアザミの力を借りることで、それを一時的に成し遂げたのだ。@
`　...Yukari will only be able to rely on the power borrowed from the magical thistle for a limited amount of time.`@
br
;　やがて、アザミの魔力も失われるだろう。@
`　The thistle's magical power will eventually wear off.`@
;　いつまでも永遠に、由香里のユートピアは続かないだろう。\
`　Yukari won't be able to keep her utopia intact forever.`\
;　……しかし。@
`　...But.`@
br
;　いじめを誰よりも憎む彼女は束の間であっても、@……真のユートピアを生み出すことが出来たのだ……。\
`　Even if it's only temporary, this girl who hates bullying more than anyone... `@`was able to create a true utopia...`\
bg black,22
bg kyou_01,0
ld r,AZA_D2,22
ld r,AZA_D5,80

;「くす。@……見事ですよ、由香里。@妾が望んだ通りになりましたね。」@
`"*Giggle*`@` ...Splendid job, Yukari. `@`You turned out exactly the way I expected you to."`@
ld l,HIG_D5,22
;ld l,HIG_D1,80

;「とか何とか言っちゃって。@負け惜しみを取り繕う偽善テクニックは相変わらずだこと。」\
`"So you say. `@`But you're just as much of a sore loser and hypocrite as always."`\
;＜彼岸花

cl r,0
ld c,AZA_D6,24
se1 47
quakex 2,200

;「ダ・レ・ガ、偽善デスッテぇええぇえぇ…？！」@
`"W H O are you calling a hypocriiiite...?!"`@
cl a,0
ld r,AZA_D6,0
ld c,HIG_w5,23

se2 48
quakex 2,200

ld c,HIG_w6,80

;「何よ、やる気ぃ？@　今日は豆大福を食べてるから絶好調よ。@何なら、今から一戦、やっちゃおうかしらぁ？！」\
`"What, do you want to fight? `@`I'm eating daifuku today so I'm in rather high spirits. `@`Shall we have a little battle, right here, right now?!"`\
;＜彼岸花

se3 12
mbg white,1
ld r,AZA_D4a,0
ld c,HIG_w5a,0

mcbg 22

mld l,YUK_i3,23
mld l,YUK_i5,80

;「うッさい、妖怪どもォ！！@　喧嘩なら表でやれッ！！！」@
`"Shut up, you youkai!! `@`If you're gonna fight, go do it outside!!!"`@
br

;ld r,AZA_D1,0
;ld c,HIG_D1,80
;wait 500
se1 3
cl a,23


;　由香里がドカンと黒板を蹴ると、妖怪たちはぴゅーっと姿を消す。\
`　Yukari banged her foot on the blackboard and the youkai disappeared.`\
mcl l,0

bg black,22
bg kyou_04,0
ld l,MAR_w2,0
ld r,SMI_i2,22

ld r,SMI_i1,80

;「ひぃ！！@　こんな怖い由香里、由香里じゃないのじゃ～！@　わぁああん！！」\
`"Eee!! `@`That Yukari is too scary, she's totally not Yukari at all! `@`Waaaaah!!"`\
se1 3
cl r,23

wait 1000

cl l,0
ld c,MAR_w1,23
;ld c,MAR_D1,80

;「……由香里ちゃんのいじめを憎む気持ち。@……いつまでも、見守っていますからね……。@がんばって、由香里ちゃん。」\
`"...I'll be watching over your hatred for bullying.`@` ...So...`@` Hang in there, Yukari-chan."`\
;＜毬枝

cl c,2
bg black,2

fede 0,2000
E_A

bg kyou_01,22

me1v 16,50

;　先生が朝のホームルームに訪れると、……普段ならみんなふざけ回っていて、着席すらしていないのに。@私語を慎み、ぴっしりと模範的に着席していた。\
`　When the teacher arrived for morning homeroom... usually he would expect everyone to be out of their seats, messing around. `@`But today they were sitting, discretely whispering under their breath.`\

;「……お、おや。@今朝はどういうわけだが、行儀がいい……。@……じゃあ、日直、号令。」\
`"...Oh, what's this? `@`Everyone is so well-behaved this morning...`@` ...Okay, whoever's the helper today, lead us through morning greetings."`\
textoff

wait 1000

ld r,YUK_i4,26
ld r,YUK_i5,80

E_A

se1v 2,100

bgm1 21

quakey 2,200

;「おらッ、日直！！」@
`"Hey, helper!!"`@
;＜由香里

se2 48
quakex 2,200

;「き、きりーつッ…！！」\
`"S-Stand...!!"`\

bg black,24
bg kyou_02,0
ld c,YOS_D3a,24
ld c,YOS_D4a,80

;「……………は、ははは。」@
`"........Ha, hahaha."`@
;＜正明
br
;　しばらくの間は、……こんな榊もいいかなと思う、正明であった。\
`　Masaaki was thinking... it wouldn't be so bad for Sakaki to be like this for a while.`\
cl c,2

;　暴君が必要悪であるかどうかという議論はさておき。@
`　And he set aside his internal debate on whether a tyrant is a necessary evil.`@
;　しばらくの間、榊由香里による圧政によって、束の間の平和が訪れるだろう。@
`　Even if it's just for a short while, Yukari Sakaki will be able to bring a temporary peace to this class.`@
br
;　……彼女の、真にいじめを憎む心に、正明は完全に脱帽せざるを得なかった……。\
`　...Masaaki had to tip his hat towards that girl's pure hatred of bullying...`\
bg black,22

;　その後、正明はベランダから落ちて怪我をした子に謝ったそうだ。@
`　Apparently, after that, Masaaki apologized to the boy that fell off of the balcony.`@
br
;　……その子が素直に許してくれたことが、正明は何よりも嬉しかった\
`　...Masaaki was beyond happy that the boy forgave him`\
;「吉川ッ、お前、委員長だろッ、@二度とあんなふざけたイタズラ、するんじゃねーぞ！！」@
`"Yoshikawa, you're the class rep! `@`Don't ever mess around like that again!!"`@
;「お、おうッ、すまねぇ、榊ッ。@/
`"Y-Yeah, sorry, Sakaki.`@/
se1 48
se2 13
quakey 2,200
;……ぎゃッ、痛ぇッ、蹴るな…！」@
` ...Gahh, ouch, don't kick me...!"`@
br
;　次の学期の委員長選挙では、榊に一票を投じよう。@
`　When the next term comes around, and they're voting for the next class representative...`@
;　そう心に誓う正明であった……。\
`　Masaaki swore to himself that he would cast his vote for Sakaki....`\


;＜おしまい＞

bg black,42

bg e022,42
wait 1000
bg black,42
bgcopy ;背景をリセット

fede 0,2000
E_A
wait 2000

if %UMINEKOEND < 6 mov %UMINEKOEND,6 : mov %END_FLG,6 ;クリアフラグの変更

	saveoff            ;セーブオフで、処理を高速化する。
	erasetextwindow 0  ;テキストエフェクトを切る事で処理を高速化
	rmode 0            ;右クリックのメニュー表示の無効化
	textoff

goto *b_title
;reset




*higan4_opning


texton
csp -1

bg black,2
bgcopy ;背景をリセット

setwindow 31,16,22,16,26,26,0,2,20,1,1,#999999,0,0,639,479

!sd

mono 0
E_A



;『少年達の肖像』


se1 14
wait 5000
E_A
bg bijutu_01,2
wait 500

se1 82
bg black,23
bg bijutu_06,22
